### ISSUE TITLE
Update Data Tracker Inventory Items to Match Finance & Purchasing Items

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#1001]
We need the inventory items in the Data Tracker to Match exactly what's in the Data Tracker.

We need to be careful here, because this item list is used for damage report tracking. So we'll have to figure out how to modify existing records in the Data Tracker if certain items need to change. We'll probably need to talk to Scott F. and Billy B. about that.

**Comment by johnclary** [comment]
@dianamartin this one is higher priority because it is blocking the work order <> inventory integration.

**Comment by johnclary** [comment]
let me billy know that names are going to change. I'm just going to "archive" all of the inventory items in data tracker.

**Comment by johnclary** [comment]
@dianamartin you can take care of this one. make a new `STATUS` choice for `inventory_items` in the data tracker called `ARCHIVED_REPLACE_BY_FINANCE_INVENTORY`. Then batch update all the existing inventory items in data tracker to that status. Then import the inventory items from the finance system and set the status to active. let me know if that doesn't make sense :)

**Comment by dianamartin** [comment]
- [x] Downloaded `inventory_items` object table from Finance & Purchasing
- [x] Added Status choice `ARCHIVED_REPLACE_BY_FINANCE_INVENTORY`
- [x] Set all AMD Inventory Items to new status `ARCHIVED_REPLACE_BY_FINANCE_INVENTORY` - 117 records
- [x] Imported `20191218_inventory_items.csv` - 222 items
- [x] Emailed stakeholders of the update
