### ISSUE TITLE
Update Netlify Deployments which use Xenial prior to November 15, 2022

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#10011]
Netlify has announced that it is going to deprecate the use of the Xenial base ubuntu image for deployments on November 15, 2022. At this point, any builds which depend on it will fail. This will prevent rolling out updates and development builds. 

This is an overdue and reasonable move on their part, Xenial was released 8 years ago in 2016 and has already hit its LTS EOL.

As it stands, this will affect:

- [x] Moped
- [x] Vision Zero
- [x]  data.mobiliy.austin.gov
- [x] austinmobilty.io 
- [x] knack-explorer
- [x] atd-knack-signs-and-markings
- [x] micro.mobility.austin.gov
- [x] help.austinmobility.io
- [x] mobile-signals.austinmobility.io
- [x] atx-census-2020
- [x] atx data and donuts

**_Every_** site we host on Netlify appears to be affected by this announcement.

Each site will need to have its build settings adjusted to use Focal (or Jammy if it's available) & tested. Individually, each site should be a fairly straight forward change, but there will be some tinkering for our more complex builds - moped & vz come to mind.

**Comment by frankhereford** [comment]
@amenity @mateoclarke @chiaberry I'd like to bring this to grooming in the near future. It's a task which is not urgent now, but we absolutely must address it prior to Nov 15.

**Comment by patrickm02L** [comment]
Thanks for bringing this up @frankhereford I'll add this to the Grooming agenda for 8/17/22.

**Comment by patrickm02L** [comment]
Talked about in Product Sync 8/17/22. This Issue seems well scoped we just need to decide when we're going to build this.

**Comment by johnclary** [comment]
@frankhereford i converted this to an epic and and am giving it a go for data.mobility.austin.gov 🤞

**Comment by frankhereford** [comment]
Thanks John!! I appreciate you doing that. I added you as an assignee on this task since you actually did it! Thanks again!!
