### ISSUE TITLE
Improve Finance and Purchasing Service Requests

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#10062]
> What application are you using?

Other / Not sure

> Describe the problem.

Hello, I need help creating a interactive form/questionnaire  (I think sharepoint may be best) to help Finance with transaction requests.  Would like the form to be able to be submitted, send to our Task email then also approved - it needs to have a workflow for completion and approval (if all that makes sense).   Happy to answer questions and give more info - just reach out to me when possible.  Thank you so much!

> How soon do you need this?

Flexible  — An extended timeline is OK

> Requested By
Sharon M.

Request ID: DTS22-104955

**Comment by johnclary** [comment]
@dianamartin i wonder if this could be related to the "service requests" module I built last year: https://atd.knack.com/finance-purchasing#service-requests

At the time the Finance folks decided to stick to email-based requests. But it's pretty well built out.

**Comment by dianamartin** [comment]
@johnclary thanks for this, I was unaware of this module. This is probably what this is regarding. I'm interesting to see what they have to say. The requester is a new employee on their team from DSD and she's familiar with the DSD sharepoint/power app processes.

**Comment by dianamartin** [comment]
Messaged user 8/19
>Hi Sharon, we received your request for assistance with streamlining a financial process. Do you have some time right now to chat so that I can scope your request out?

**Comment by dianamartin** [comment]
# Diana Notes
Current process too slow
Mailbox: Finance - writes email
- provide detail in email
- put into folder
- no standards, would like a form
- write a note - done - provide information to 
- unread - approve it
- approves, back in mailbox

## Requirements
- Add email notification when submitted request is submitted - atdtaskbudgetrequests
- Ability to have employee self assign
- Improve Submitted button - Add email notification for manager
- Improve Decision button - Approve or Completed
- Add email notification to requester when final decision has been made

**Comment by KaroEngstrom** [comment]
Previous work here: #[8009](https://github.com/cityofaustin/atd-data-tech/issues/8009)

**Comment by dianamartin** [comment]
Requested items from Finance
- SubProject ID

**Comment by dianamartin** [comment]
# 9/2
 Service Requests

**Comment by dianamartin** [comment]
# Proposed Build
- Create Service Request (parent)
- Go to Service Request details
- Reference Sub Projects table
- Reference FDU table

**Comment by dianamartin** [comment]
# Steps
- [x] created new object - `financials_task_order_TK`
- [x] created new object - `financials_funding_number_FDU`
- [x] created new object - `financials_subprojects`
- [x] Made connections to `service_request_line_item`
- [x] created new page - Service Requests
- [x] exported task order from Data Tracker
- [x] imported task orders into Finance and Purchasing - `10200 records`
- [x] exported subprojects from eCapri
- [x] imported subprojects from eCapri - `675 records`

**Comment by patrickm02L** [comment]
Meeting set for 11/16/22 where we'll discuss several options for what the parent-child relationship will look like for new SRs.

**Comment by stephaniemoorer** [comment]
Status Update
The new Service Request application provides TPW staff the ability to submit New Service Requests, track the statuses of requests submitted, and specify the jobs they are requesting from Finance. Other capabilities allow the TPW Finance team to Manage Service Requests, assign requests to Finance staff, and update information that can be seen directly by TPW staff in the Finance & Purchasing Knack application and through automated emails. The Service Request module Go Live July 2024.

**Comment by stephaniemoorer** [comment]
This is complete - closing
