### ISSUE TITLE
Rename systems in Annual Signal Retiming - Signal Systems

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#10082]
> What application are you using?

Data Tracker

> Describe the problem.

In Annual Signal Retiming - Signal Systems, can we please rename the following systems (format: from --> to)

Airport 1 --> Airport South
Airport 2 --> Airport North
Parmer 1 --> Parmer East
Parmer 2 --> Parmer Central
Parmer 3 --> Parmer West
Slaughter 1 --> Slaughter West
Slaughter 2 --> Slaughter Central
Slaughter 3 --> Slaughter East

> How soon do you need this?

Soon — This week 

> Is there anything else we should know?

We are already working on these corridors and they will be public facing so we have to make sure they show correctly.

> Requested By
Brian G.

Request ID: DTS22-104990

**Comment by dianamartin** [comment]
Checked to see which object had the Corridor Retiming Names that Brian G. was asking to change.
- `corridor_retiming_zones` - had the field `Retiming_Zone`

Update these names:
- [ ] Airport 1 --> Airport South
- [ ] Airport 2 --> Airport North
- [ ] Parmer 1 --> Parmer East
- [ ] Parmer 2 --> Parmer Central
- [ ] Parmer 3 --> Parmer West
- [ ] Slaughter 1 --> Slaughter West
- [ ] Slaughter 2 --> Slaughter Central
- [ ] Slaughter 3 --> Slaughter East

# Before
![image](https://user-images.githubusercontent.com/21112975/186471678-7ab9554d-e458-44e7-82d0-5606defe692e.png)

# After

**Comment by dianamartin** [comment]
Emailed user 8/24
>I’ve updated the Signal Retiming Zones Names that you requested (attached screen shot shown above)
Let me know if there’s anything else you need.

**Comment by dianamartin** [comment]
Have not heard back from user on this, closing. Will re-open if necessary.
