### ISSUE TITLE
Update "Journal Voucher" info in AMD Data Tracker - Warehouse Inventory- August 2022

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#10098]
W 8/24/22
- [x] Spreadsheet emailed from Finance staff month of: August 2022, all vouchers (250) with Journal Voucher Date 8/23/2022
- [x] Number of records being updated: 250
- [x] Format spreadsheet [(Review instructions)](https://atd-dts.gitbook.io/atd-knack-operations/warehouse-inventory-updating-journal-vouchers-jv-information)17586
- [x] Spot check Transaction IDs, no JV information before import: 17707; 17486
- [x] Import records
![image](https://user-images.githubusercontent.com/100615928/186440034-e4b10ff9-abc4-469e-ae58-fde71ca74d38.png)
- [x] Spot check Transaction IDs, no JV information after import: 17707, 17486
- [x] Added files to G: drive backup
- [x] Email Finance staff that update task complete
"Hello Crystal, 
We’ve updated the Journal Vouchers for August 2022. [Here is the filter](https://atd.knack.com/amd#inventory-reports/issued/?view_2799_filters=%7B%22match%22%3A%22and%22%2C%22rules%22%3A%5B%7B%22field%22%3A%22field_3825%22%2C%22operator%22%3A%22is%22%2C%22value%22%3A%2208%2F23%2F2022%22%2C%22field_name%22%3A%22Journal%20Voucher%20Date%22%7D%5D%7D&view_2799_page=1) for them. 
Let me know if you need anything else. 
Best,
Karo"
