### ISSUE TITLE
Create a SharePoint site to track and accumulate APWA documentation

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#10116]
> Name

 Kate L.

> What application are you using?

Other / Not Sure

> Describe the problem.

Need a SharePoint site to track and accumulate APWA documentation.

> Describe the solution you have in mind.

Use of SharePoint to create a repository for policies and procedures, schedule,  deadlines, milestones, etc.  Ability to have multiple users from across the department to access and edit documentation , etc.

> How will we know that our solution is successful?

Collaboration with department users

> Users

Department staff

> Sponsorship

Peggy M.

> Which Strategic Direction 2023 “Mobility” indicators would this new application impact?

['System efficiency and congestion']

> Which Austin Strategic Mobility Plan goals would this new application support?

['Sustainability — Promote integrated designs and quality additions to the built environment while reducing impacts and promoting efficient use of public resources.']

> Describe the outcome you'd like to see when this feature is implemented.

Single site to gather required documentation.  Workflow for simple review and approve at multiple levels.  Interactive schedule to keep moving forward.

> Describe any workarounds you currently have in place or alternative solutions you've considered.

Workarounds would include use of multiple folders on the network drive, attachments in emails.

> Is there anything else we should know?

It would be great if we could have the site available early in September so we can define work processes and document directions for users.

> How have other divisions/departments/cities addressed similar challenges? 

PWD has a similar site.  https://cityofaustin.sharepoint.com/sites/PW/PWOPM/APWA/SitePages/Home.aspx?OR=Teams-HL&CT=1661442810746&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiIyNy8yMjA3MzEwMTAwNSIsIkhhc0ZlZGVyYXRlZFVzZXIiOmZhbHNlfQ%3D%3D

> Requested By
Kate L.

Request ID: DTS22-105025

**Comment by dianamartin** [comment]
@KaroEngstrom Talked to Peggy about this request, looks like it will be a stand alone new SP site that we'll connect to the ATDHub. Add under 'Programs" in the menu.

**Comment by KaroEngstrom** [comment]
Th 8/25/22 
- messaged requester to schedule a chat to build the baseline site and scope out further use details

**Comment by patrickm02L** [comment]
@katelunceford 👀

**Comment by KaroEngstrom** [comment]
T 8/30/22 

Met with Kate to map out needs: 
- The three chapters that ATD will need to complete at already hosted by PW [here](https://cityofaustin.sharepoint.com/sites/PW/PWOPM/APWA/2023%20APWA%20Accreditation/Forms/AllItems.aspx?RootFolder=%2Fsites%2FPW%2FPWOPM%2FAPWA%2F2023%20APWA%20Accreditation%2FTransportation&FolderCTID=0x012000C6B3117D0AD6C040B4D0B7C66C613F7B&View=%7BF9267756%2D977B%2D4684%2DAF78%2DE7A3EE27EF6B%7D)
- Ideally we don't move/duplicate items so we will link to those documents 
- Within each chapter (folder) is document (practice) and a folder for evidence, if any. The documents and evidence need to be tracked. We plan to do that tracking in a SharePoint list that links to each document. This avoid the disconnect of a separate spreadsheet. 
- Kate has an existing spreadsheet with the planned milestones for the work, so Karo will use that as a guide when putting together the SharePoint list. Documents (practices) within the existing APWA folders for ATD correspond with the rows in the SharePoint list for progress tracking. 
- A Teams instance will be created for communications and easy control of participants.  
- Karo will get started on the following tasks and follow up with Kate this week (by Sept 2) to check progress. 

### TASKS 
- [ ] Create SharePoint page for ATD APWA 2023 Accreditation
- [ ] Link to existing content folders on the PW page 
- [ ] Connect from the ATD hub page 
- [ ] Create SharePoint list as Progress Tracker 
- [ ] Create connected Teams and make Kate admin
- [ ] Follow up with Kate on these for review

**Comment by KaroEngstrom** [comment]
W 8/31/22 

* completed review of the above items with Kate 

**Next Steps** 
- Contributors - Kate (or Karo) can add contributors in Teams; Karo will add them as editors (Members) in SharePoint to ensure safety of documents 
- SharePoint site - Karo added a link to a Tools page; Kate will collect item needed for that page and Karo will add and link to make these tools accessible by the contributors 
- Progress Tracker - Kate has access to add contributors in the Lead or SME columns; Karo will work on pulling Tracking and Progress information from the SharePoint list to make visualization of progress easier 
- Karo will check in again at the end of the current sprint (EOD Tuesday 9/6)

**Comment by KaroEngstrom** [comment]
Th 9/1/22

* Per @katelunceford, I deleted the Teams I had created for this request earlier and linked a new Teams instance created by @maccallump to the existing SharePoint built for this request (SharePoint page links to the new Teams; new Teams has tabs for Document Library, Progress Tracker, and the SharePoint page).

**Comment by KaroEngstrom** [comment]
T 9/6/22 

### Check-in with Kate via Slack:

Her requests:
**1) Give the ATD APWA - 2023 teams channel similar headings to what you had on our version of the teams channel**

- [x] I went ahead and changed the tab headers. I didn’t add Tools yet as that page is not really up, but will be soon and can be added. We could use that as a chance for me to show you how to manage that tabs.
Here’s what the tabs look like right now. The red arrows point to tabs where Peggy’s items are, and I think we can simplify by moving those to the SharePoint folders and pages (we can discuss in the sync meeting).
![image](https://user-images.githubusercontent.com/100615928/188709783-15b82805-233c-4d47-99ae-616beb723032.png)



2) **I want to add a ppt presentation to the Tools page. How can I do that? I'll also need to add these items in the near future:**
**ATD Procedure Template (word file I think)
How-to fill out the practice, prepare and save evidence, and use the progress tracker (ppt presentations or maybe a short video)
Recorded meetings & presentation files (videos & ppt)
APWA library (link to external source)
Need something else? Just ask! (an easy link/button to email me)**

- [x] All those items would fit on the Tools page. Videos can be embedded on the page or on a linked page.
PowerPoint can also be embedded. Here’s one example; [DSD Project Priorities](https://cityofaustin.sharepoint.com/sites/DSD/SitePages/DSD-IT-PROJECT-PRIORITIES.aspx)
The user can flip through the slides.
I have an idea for the Email Me item, too. I think overall we can get together to build this (won’t take long) and you can see the process at the same time. Does that work? I want to empower you to change things on your own but will also always be here to help. Hopefully best of both worlds :slightly_smiling_face:

### NEXT STEPS: 
- APWA Sync with Peggy and Kate this week 
- Add Tools page content with Kate when that content is ready in a build-and-learn session to empower her to update as needed

**Comment by dianamartin** [comment]
# 9/7
We have a short sync scheduled on 9/9 to take about being on the same page and what the process will look like. 
- Karo and Kate to schedule a sync/training in the future

**Comment by KaroEngstrom** [comment]
### Fri 9/9/22
Sync w/ Peggy, Diana, Kate, and Karo

**Comment by KaroEngstrom** [comment]
## Build and Learn Session 9/14/22

- Going over Permissions for the APWA site - specific set of contributors must have Edit access to Documents and Progress Tracker 
- Option to add as unique permissions (more locked down but really cumbersone) or as a Members group (easier but relies on everyone being responsible with the content)
