### ISSUE TITLE
IT Support: Update Henry Z. user roles to match Brian C.

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#10119]
Brian C. 
AMD

Emailed 8/25
>I created an account for Henry Z.a and set it up as an Account Admin. I wanted to modify it to give it the same permissions that I have, but I can’t edit it. Can you help?

**Comment by dianamartin** [comment]
- [x] Checked Brian's user role access
- [x] Screen shot access list
- [x] Updated Henry's user role access
- [x] Emailed Brian back about updating Henry's access

Emailed back 8/25
>I checked the system for your user role access and gave Henry the same rights. 
![image](https://user-images.githubusercontent.com/21112975/186717988-d2904fc5-f410-4995-9ca6-8ec31c91890b.png)
>Let me know if you need anything else.
