### ISSUE TITLE
Implement new order tracking fields in PROD (Finance and Purchasing)

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#10124]
Had worked on this but forgot to document my progress
- [x] Re-ordered the fields and added additional fields to the Inventory Report page
- [x] Added new details page for "Item Details"
- [x] Added `order_tracking` object
- [x] Added `delivery_received` object
- [x] Created forms for "order tracking" and "add delivery" 

## Details button
![image](https://user-images.githubusercontent.com/21112975/179096998-c26474d2-3730-4c44-8ca0-2d20eff31063.png)

## Item Details page
![image](https://user-images.githubusercontent.com/21112975/179097047-5baee0c2-0735-4c6e-8179-91c548f7cf9e.png)

## Track Order
![image](https://user-images.githubusercontent.com/21112975/179097827-361841b2-249b-4b2c-9c81-f32fcbc6e3ee.png)

## Add Delivery
![image](https://user-images.githubusercontent.com/21112975/179097723-9a60de03-dd57-492d-b9e7-c2c9d2cc9dfc.png)

_Originally posted by @dianamartin in https://github.com/cityofaustin/atd-data-tech/issues/9603#issuecomment-1184944428_

**Comment by ChristinaTremel** [comment]
@dianamartin can this issue be closed?

**Comment by dianamartin** [comment]
@ChristinaTremel I think so, but we might need to circle back with Cesar to see if he still wants to use this feature. He probably doesn't know about it.

**Comment by dianamartin** [comment]
@ChristinaTremel I think this feature was removed in the Finance and Purchasing
