### ISSUE TITLE
Test new Test Contractor account - access/permissions

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#10131]
CONTRACTORS
- [x] Create Test Contractor Account - 6/27/22
- [x] Test as Contractor to see what what they can do (similar as Technicians)
- Feature: like smb, have Contracts chosen (bc they have multiple contracts but same contractor) and Assign to Contractor Accounts 

OTHER
- Construction Contract: Erin/Brian
- Fiber Contract: Edgardo/Harrell

_Originally posted by @dianamartin in https://github.com/cityofaustin/atd-data-tech/issues/7822#issuecomment-1210784301_

**Comment by dianamartin** [comment]
- [x] Moved `WRK22-154045` from being assigned to me to the "Test Contractor" account
- [x] Opened the Work Order details to see what things this account can access
- Has access to:
  - Attachments
  - Comments.
  - DOSA
  - Time Log
  - Schedule Work
  - Completed Work
  - Inventory Item
  - Preventative Maintenance
  - Submit Work Order
