### ISSUE TITLE
Update "Journal Voucher" info in AMD Data Tracker - Warehouse Inventory- September 2022

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#10245]
- [x] Spreadsheet emailed from Finance staff month of: September 2022, 09/12/22-09/13/22
- [x] Number of records being updated: 228
- [x] Format spreadsheet [(Review instructions)](https://atd-dts.gitbook.io/atd-knack-operations/warehouse-inventory-updating-journal-vouchers-jv-information)
- [x] Spot check Transaction IDs, no JV information before import (17163; 16728)
- [x] Import records
- [x] Spot check Transaction IDs, has JV information after import (17163; 16728)
- [x] Email Finance staff that update task complete
"Hi Crystal,
We’ve updated the Journal Vouchers for September 2022. [Here is the filter ](https://atd.knack.com/amd#inventory-reports/issued/?view_2799_page=1&view_2799_filters=%7B%22match%22%3A%22or%22%2C%22rules%22%3A%5B%7B%22field%22%3A%22field_3825%22%2C%22operator%22%3A%22is%22%2C%22value%22%3A%2209%2F12%2F2022%22%2C%22field_name%22%3A%22Journal%20Voucher%20Date%22%7D%2C%7B%22match%22%3A%22or%22%2C%22field%22%3A%22field_3825%22%2C%22operator%22%3A%22is%22%2C%22value%22%3A%2209%2F13%2F2022%22%2C%22field_name%22%3A%22Journal%20Voucher%20Date%22%7D%5D%7D)for them.
Let me know if you need anything else.
Best,
Karo"

![image](https://user-images.githubusercontent.com/100615928/189992306-44b98ea9-8a42-44c7-b7a7-ef4553528b3c.png)
Reference link for Finance [here](https://atd.knack.com/amd#inventory-reports/issued/?view_2799_page=1&view_2799_filters=%7B%22match%22%3A%22or%22%2C%22rules%22%3A%5B%7B%22field%22%3A%22field_3825%22%2C%22operator%22%3A%22is%22%2C%22value%22%3A%2209%2F12%2F2022%22%2C%22field_name%22%3A%22Journal%20Voucher%20Date%22%7D%2C%7B%22match%22%3A%22or%22%2C%22field%22%3A%22field_3825%22%2C%22operator%22%3A%22is%22%2C%22value%22%3A%2209%2F13%2F2022%22%2C%22field_name%22%3A%22Journal%20Voucher%20Date%22%7D%5D%7D)
