### ISSUE TITLE
Feature: Implement Scheduled Follow-up in AMD Work Orders

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#10248]
Diana 
DTS

Created a new process for Scheduled Follow-up Work Order

**Comment by dianamartin** [comment]
# 10/3
Met with stakeholder (Brian VDW, Billy, Jorge)
- to figure out the timing and the plan to get this ready for go-live

# Changes
## My Work Order page
- [ ] Remove the old table on "My Work Orders"
- [ ] Remove field "Scheduled" on new "My Work Orders" table
- [ ] Move menu for new work order buttons from this page to "Work Order - Technicians"
- [ ] Keep "All Work Orders" button

## Work Order - Technician page
- Move menu navigation here
- Remove "New Work Order" button on second menu 

## New Schedule Work Order form
- When asset type is `Other/No asset`
- Show/Hide `Location` field 
- Add `Location` field 
  - include information about 8700 and 8900 Location IDs so that user can populate them in there
  - 8700 -  `LOC19-013855` - 
  - 8900 - 
  >Edited `LOC19-013895` to be 8900 Cameron location

**Comment by dianamartin** [comment]
# 10/6
## Updated "My Work Orders" and "Work Order | Technicians"
- see above modifications
## Configured Scheduled Work Follow-up form in Production
- Referenced TEST Data Tracker
- Had to test in Production
- Deleted all test attempts
- Working fine after 3rd or 4th attempt
- Configuration was interesting

## New Schedule Work Order form
- [x] Add "Location ID" field to form
- [x] Add information about 8700 and 8900 Location IDs so that user can populate them in there
        8700 - `LOC19-013855` -
        8900 - `LOC19-013895` - Edited to be 8900 Cameron location
- [x] Configure display rule when asset type is "Other/No asset"
- Show/Hide Location field
- [ ] Test if working correctly

**Comment by dianamartin** [comment]
## Messaged Billy, Jorge, Ed 10/6
So I updated the "My Work Order" page, looks like this now

Remove the old table on "My Work Orders"
Remove field "Scheduled" on new "My Work Orders" table
Move menu for new work order buttons from this page to "Work Order - Technicians"  
Keep "All Work Orders" button


On "Work Orders | Technician" page

Move menu navigation here
Remove "New Work Order" button on second menu


Configured Scheduled Work Follow-up form in Production
Referenced TEST Data Tracker
Had to test in Production
Deleted all test attempts
Working fine after 3rd or 4th attempt
Configuration was interesting


New Schedule Work Order form
Add "Location ID" field to form
 Add information about 8700 and 8900 Location IDs so that user can populate them in there
8700 - LOC19-013855 -
8900 - LOC19-013895 - Edited to be 8900 Cameron location
Configure display rule when asset type is "Other/No asset"
Show/Hide Location field


Let me know if this looks okay to you first thing tomorrow. We can tweak anything that looks off it there are any issues.

**Comment by dianamartin** [comment]
Users see the update and are okay with the changes. There was a "hotfix" required this morning when the user roles weren't configured correctly. That was addressed at around 9:30 am 10/7.
