### ISSUE TITLE
Enhancement: Contractor Transfer of Ownerships Account Admin Capabilities  in Data Tracker 

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#10272]
## As a Supervisor in Signal Management,  I want to be able to be able to manage Contractor Transfer of Ownership user accounts so that correct users have access to creating Contractor Transfer Forms. 

**Related to a problem?**
Data Tracker has existing accounts with various user roles. The task is to allow management of specific user roles without exposing all of them to the account manager for a small slice of Data Tracker functionality. 

**Desired Outcome?**
Ability for the supervisor to add and remove Contractor Transactions users independently from the application (without needing to put in a DTS SR). 
Original ask: "Billy, Edward, and I will need to be able to add, edit, or remove COA employee names."

**Additional Context?**
Building on #9766 
---
**Acceptance criteria**

- [ ] Supervisor has access to control Contractor Transactions user roles (add new users, add this role to existing users, remove this role from existing users).
- [ ] This control of Contractor Transactions does not expose the other user roles to the supervisor nor does the supervisor have the ability to edit or override those roles, or remove existing users. 
- [ ] This account control works independently of DTS staff having to manage accounts in the background. 

This issue is at same status as #10172 Create Auto-Assign Functionality for Court Case System

**Comment by KaroEngstrom** [comment]
@TracyLinder I'd love to icebox this. When we've discussed this in the past, I think the consensus is that this app isn't big enough (in terms of users and volume) to warrant a big accounts dash for supervisors. It seems to be working well w/o this functionality.

**Comment by TracyLinder** [comment]
@KaroEngstrom i think you may have commented on the wrong issue. This one is for AMD, not ROW.

**Comment by KaroEngstrom** [comment]
@TracyLinder Sorry, I mixed up the pieces and dragged you into it when I should have tagged @dianamartin  

@dianamartin This came out of the Contractor Transactions mini-feature we built. I don't think we wanted to build this for the low number of transactions and users. Can we icebox it? The main issue would be not having a way to work around other Data Tracker permissions.

**Comment by dianamartin** [comment]
I think Billy, Ed and Jorge can get "Account Administration" access which I believe they already have.

**Comment by ChristinaTremel** [comment]
We talked to stakeholders several months back and decided that this wasn't an urgent priority. Iceboxing this issue for now.

**Comment by KaroEngstrom** [comment]
![image](https://user-images.githubusercontent.com/100615928/227970897-12e3b99d-5d45-4ffb-a470-d3d61c534e40.png)
