### ISSUE TITLE
Artbox Program - Create New Features for 10/10/22 Sprint Review

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#10311]
# M 9/26/22 Meeting - Steps to Complete for Next Review 

**Header**
- [x] Select a number of images from existing Artbox pictures to create a header collage
- [x] Update Artbox Application form in Knack with this header, similar to SMO P3 
- Luke's example below; he also hoped to include some of the artists working on their projects in the collage 
![image](https://user-images.githubusercontent.com/100615928/192317396-2c423cea-5f26-46d4-8b39-a2a3e616256a.png)
Karo version (Luke specifically said it would be nice to incorporate the artists here as well) 
https://raw.githubusercontent.com/cityofaustin/atd-knack/master/media/SMO_Artbox_Header_20220927.jpg

**Commenting Feature** 
- [x] Build a Commenting feature - look for types from Sandra's project steps

**Attachment Feature** 
- [x] Build an Attachment feature - look for types from Sandra's project steps

**Milestones Feature** 
 - [x] Build a Milestones tracking feature - look for types from Sandra's project steps
 
 **Application Intake** 
- [x] Add Sandra as the recipient of the new application notification 
![image](https://user-images.githubusercontent.com/100615928/192323691-213562f4-ef6d-4107-88e9-e9711c4e11da.png)
- [x] Update outgoing email with language decided upon in the meeting 
![image](https://user-images.githubusercontent.com/100615928/192318604-f4d07632-5c40-449d-b975-e9c341e7493f.png)
![image](https://user-images.githubusercontent.com/100615928/192323604-6d82f9ac-b554-4689-9321-19dcc676a850.png)

 - Sandra and Luke will test the application and intake views 
 - Sandra will let us know when she's ready to start intake via Knack, at which point: 
- [ ] Ask PIO to update the application link from Google Forms to Knack 

**Contact Directory** 
- Sandra will send info on what details they'd like to keep in this directory. After that: 
- [ ] Create an object and a template for Contacts 

**Project Dates**
- Sandra will send a list of project milestones/dates to track. Once those are received: 
- [x] Add these Date fields into the Application object 

LIST: 

![image](https://user-images.githubusercontent.com/100615928/192531465-0b6b448d-bd72-483b-b8d8-eaa62728cda3.png)

**Comment by patrickm02L** [comment]
In planning 10/5/22 - Send reminder to Sandra and Luke to test out the application.

**Comment by KaroEngstrom** [comment]
### M 10/10/22 Sprint Review 

Next Steps (will be added to the new issue) 
* Keep Project dates as a quick reference
*Add a milestone Application Approval
*Make updates to the milestones table so that all the list items all showing to start, and there’s a button to add a non-milestone
*Ask @dianamartin  about limit for image upload, and discuss the ability for artists/partners to upload then to Knack 
* Get Artists spreadsheet from Sandra to start creating the directory
* Schedule meeting 2-weeks from now-  Friday, Oct 28th @2pm (scheduled by Patrick)
