### ISSUE TITLE
Release VZ v1.28.0 Guadalupe St.

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#10357]
**To-do's for upcoming release**

- [x] Schedule release party - @patrickm02L 
- [x] Advise users of downtime - @patrickm02L 
- [x] Merge open PRs - @patrickm02L 
- [x] Cut release branch - @frankhereford 
- [x] Propose + vote on release names - @patrickm02L 
- [x] Refine [release notes](https://github.com/cityofaustin/atd-vz-data/releases/tag/untagged-72a55f44825c5cba5c1a) - @frankhereford 
- [x] Bump VZ **staging** version to `v1.29.0` and VZ production to `v1.28.0`- @frankhereford 
- [ ] Send out release notes - @patrickm02L

**Comment by patrickm02L** [comment]
Will update VZ team on release 10/4/22 rather than send out release notes.
