### ISSUE TITLE
Update "Journal Voucher" info in AMD Data Tracker - Warehouse Inventory- September 2022 (second set)

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#10410]
- [ ] Spreadsheet emailed from Finance staff month of: FILL MONTH OUT, DATE RANGE
- [ ] Number of records being updated: ENTER NUMBER HERE
- [ ] Format spreadsheet [(Review instructions)](https://atd-dts.gitbook.io/atd-knack-operations/warehouse-inventory-updating-journal-vouchers-jv-information)
- [ ] Spot check Transaction IDs, no JV information before import
- [ ] Import records
- [ ] Spot check Transaction IDs, no JV information after import
- [ ] Email Finance staff that update task complete
