### ISSUE TITLE
Restore Permissions for Technician in for AMD Data Tracker - New Work Order - Scheduled Work 

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#10437]
**Describe the bug**
Edward G. via Teams reports one Technician cannot create new work orders for the Scheduled Work type in AMD Data Tracker. They get a request for sign-in and are not able to log on.

**URL**
https://atd.knack.com/amd#work-orders/?view_713_filters=%5B%7B%22field%22%3A%22field_3601%22%2C%22operator%22%3A%22is%22%2C%22value%22%3A%22Technicians%22%2C%22field_name%22%3A%22Workgroup%22%7D%5D

- [x] Checked the permissions and compared to another technician, all good
- [x] Checked with Diana and she was able to update the permissions; recent updates had changed the access 
- [x] Notified Edward who said he would have the technician try again

**Comment by KaroEngstrom** [comment]
Assuming this works as they're been putting in work orders without issues. Closing.
