### ISSUE TITLE
Provide help guide documentation for AMD Work Order training

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#10445]
Had originally started the documentation when I thought training was going to be at the end of September.

**Comment by dianamartin** [comment]
Created two new pages in GitBook "[AMD Data Tracker | Help Guides](https://atd-dts.gitbook.io/amd-data-tracker-help-guides/)"
- Updated - My Work Order Technicians
- Updated - Work Order | Technicians
outlining the changes to these pages
- [ ] Going to add photos for step by step process, all the content has been added
- [ ] Review help guide content

**Comment by dianamartin** [comment]
# 10/10- 10/11 
- [x] Updated AMD help guide in GitBook 
- [x] Added photos for all sections
- [x] Build out section for Preventative Maintenance
- [x] Added new section for "Edit Work Order"
- [x] Gave AMD supervisors the link to the help guides on 10/11
