### ISSUE TITLE
HR Digital SSPR Roll out and Stabilization Period

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#10450]
- Executive team approved rollout of the Digital SSPR
- Roll out plan is being developed by HR with our input
- Since we are currently in FY23 Planning Period we need a quick rollout 

- [x] HR will Identify and invite 3 - 4 Divisions as the initial participates
- [x] Training video will be created with a focus on Creating New SSPR for Planning. 
Additional modules (Mid Year & Year End) will be recorded and available later

- [x] Teams chat room will be created for participants input/questions/issues/feedback
- [x] HR will create a Comprehensive email will be forwarded to participants
- [x] Initial training session will be scheduled for Friday 10/14
- [x] Weekly check ins will be scheduled to review questions/issues/feedback
- [x] Rollout to all other Divisions within 3 weeks?

**Comment by dianamartin** [comment]
# 10/14 
I've made the recordings this morning, was able to update the SSPR GitBook with one of the recordings. The longer walk through it taking a long time to export. That's the only thing that needs to happen. 
- [ ] Export: `Recorded Help Guide - SSPR Supervisor - Planning`

**Comment by moorerst** [comment]
10/16 - Diana's Notes:
I recorded the SSPR help guide walk through, but one of the two videos I made was having trouble exporting (all Friday, all weekend). I finally tried something that the Adobe Creative Suite offered and I loaded it, and it successfully let me edit the video and export sooo fast!



So after many failed export attempts, I'm happy to announce that both videos are uploaded to the SSPR help guides and the help guides have been edited to showcase only the "Planning" steps for Supervisor and Employee.



GitBook [HR SSPR Help Guides](https://atd-dts.gitbook.io/human-resources-or-help-guides/planning/sspr-planning-creation-or-supervisor)

**Comment by moorerst** [comment]
Additional hot fixes:

1. Need a better way to manage employees within a Division. Break Divisions into sub Divisions
Created new Divisions for AMD, ROW and Signs and Markings. HR will move employees into the new Divisions.

2. Add ability to edit employee Division & Supervisor from the Employee page

@dianamartin you can add details

**Comment by dianamartin** [comment]
Closing, stabilization period is over and no other feedback changes is required.
