### ISSUE TITLE
Update "Journal Voucher" info in AMD Data Tracker - Warehouse Inventory- SEPTEMBER 2022

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#10452]
- [x] Spreadsheet emailed from Finance staff month of: September, 9/30/22 - multiple batches this month for end of fiscal year
- [x] Number of records being updated: 3
- [x] Format spreadsheet [(Review instructions)](https://atd-dts.gitbook.io/atd-knack-operations/warehouse-inventory-updating-journal-vouchers-jv-information)
- [x] Spot check Transaction IDs, no JV information before import - checked all three 16129-16131
- [x] Import records
- [x] Spot check Transaction IDs, no JV information after import - checked all three [here](https://atd.knack.com/amd#inventory-reports/issued/?view_2799_filters=%7B%22match%22%3A%22and%22%2C%22rules%22%3A%5B%7B%22field%22%3A%22field_3825%22%2C%22operator%22%3A%22is%22%2C%22value%22%3A%2209%2F30%2F2022%22%2C%22field_name%22%3A%22Journal%20Voucher%20Date%22%7D%2C%7B%22match%22%3A%22and%22%2C%22field%22%3A%22field_3563%22%2C%22operator%22%3A%22higher%20than%22%2C%22value%22%3A%2216128%22%2C%22field_name%22%3A%22Transaction%20ID%22%7D%2C%7B%22match%22%3A%22and%22%2C%22field%22%3A%22field_3563%22%2C%22operator%22%3A%22lower%20than%22%2C%22value%22%3A%2216132%22%2C%22field_name%22%3A%22Transaction%20ID%22%7D%5D%7D&view_2799_page=1)
- [x] Email Finance staff that update task complete
