### ISSUE TITLE
Artbox Program - Update Project Milestones Feature

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#10454]
## M 10/10/22 Sprint Review Notes
* Keep Project dates as a quick reference
* Add a milestone Application Approval
* Make updates to the milestones table so that all the list items all showing to start, and there’s a button to add a non-milestone

## Build To-Do for Th 10/20/22-Th 10/27/22
- [x] Add Application Approval Date to Project Dates 
- [x] Retain Project Dates view for quick reference 
- [x] Remove time (HH:MM) from the milestones 
- [x] Add the option for Sandra to add new non-milestone dates - repurpose button
- [x] Actual form to add non-milestones - figure out maneuver to replace multichoice type with written in description?  
- [x] Change the name of the Project Milestones table to Project Milestones and Non-Milestone Dates 
- [x] Add rules to create ALL Milestones when the Artbox Application is submitted 
- [x] Update the table to show these newly created milestones 
- [x] Keep table inline editable (only Sandra and Luke will be making edits in this space so audit fields are not necessary to show or track for modifications)
- [x] Remove current Add Non-Project Milestone button 
- [x] Update the name of current ~~Add Project Milestone~~ button to Add Non-Project Milestone 
- [x] Update Add Project Milestone form to reflect creating a new milestone ONLY (since all hardwired milestone are auto-created) 
- [x] Remove audit fields from the table 

---

### @dianamartin will assist by: 
- [x] breaking down current Application Details page into: 
- [x] Application Details page, and 
- [x] Manage Project page 
- [x] link to Manage Project page from the home page New Applications TABLE, as a final column 
- [x] faux nav menu between the Application Details | Manage Project page 

---

### Questions to ask in sprint review 
- Artist vetting - what does this mean? Do you need to track artists vetted in general, or per organization? 
- displaying contacts in the Contact table - filtered menu Primary/Secondary? That would NOT retain the ability to keyword search

**Comment by dianamartin** [comment]
# 10/20
- [x] Added new page "Manage Project"
- [x] Added new shortcut to "Manage Project" from ArtBox Application table
![image](https://user-images.githubusercontent.com/21112975/197072439-c660053f-6bdc-4261-8e65-d3e586df9f0e.png)
- [x] Manage Project page has 
  - Milestone button
  - Milestone table
  - Attachment button
  - Attachment table
  - Comment button
  - Comment table
![image](https://user-images.githubusercontent.com/21112975/197072518-b7d69578-9306-4f86-b8ee-b767412bd707.png)

**Comment by KaroEngstrom** [comment]
# W/Th 10/26 & 27
###  Remaining items

- [ ] Configure display of Milestones/Non-Milestones in the table - display order 
   - [ ] Add Display Order to 'milestone' object 
   - [ ] Configure order to milestones 
   - [ ] Set Milestones table to follow Display Order as a default  
- [ ] Configure pushing the inline-edited date for a Milestone record to the corresponding date in the Application object so as to display on the Project Dates Details view 
   - [ ] Add record rule to the Project Date column per every Milestone type to update to its corresponding Project Date field on the 'application' object 
- [ ] Add Modified By/Modified Date record rules to everything in the inline-edit tables, including the object (Milestone/Comment/Attachment) and 
- [ ] Run a full test of the new Project Milestones feature 

### Additions per Team Sync 10/20/22 
- [ ] Allow adding new option for Organization from Add Contact 
- [ ] Miro board model of the Project Statuses with mapping to triggers ([use list here](https://cityofaustin-my.sharepoint.com/:x:/r/personal/karo_engstrom_austintexas_gov/_layouts/15/Doc.aspx?sourcedoc=%7BAA950CFA-D013-4C37-9B8E-E6A38F6764C5%7D&file=Artbox_Steps_20221005.xlsx&action=default&mobileredirect=true))
- [ ] Add Cancel Project button to the Project Management page 
- [ ] Combine all edit buttons to one menu at the top of the page for Manage Project page

**Comment by KaroEngstrom** [comment]
## F 10/28/22

- demoed items per[ agenda and meeting notes](https://docs.google.com/document/d/1nsNxbPzMV4x3CkqZBmtE9A-AZdRjupUYRljFKjJwwYo/edit)
- updates in #10635
