### ISSUE TITLE
Major Roadway Construction-Special Event Coordination

### ISSUE THREAD

**Issue by ATD-ZachB** [cityofaustin/atd-data-tech#10478]
This epic is for tracking an ongoing project for meetings, map products, web map products. and web applications that will show reoccurring major special events that will intersect current and future construction projects.  Visualization of these 2 major data sets for the purpose of planning, preparation, and informing is the key factor for this epic.

Upcoming Potential Tasks:

From 3/3 meeting:
- [x] Explore ways of streamlining processing (Dynamic Joins in AGOL, Hosting features in AGOL Processing processing - local overwrite)
- [x] Add Event impact areas (Buffer areas, capture intersecting street segments, append to existing event linear data)
- [x] Add venues as reference to existing maps

-----------------------------------------------------------------------------------------------

- [x] #11161
- [x] #11294
- [x] #11295
- [x] #11162
- [x] #11060
- [x] #11297
- [x] #11296
- [ ] Look into using experience builder vs current tabbed storymap (In Extended Support - https://storymaps-classic.arcgis.com/en/app-list/map-series/tutorial/)
