### ISSUE TITLE
Release VZ v1.29.0

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#10542]
**To-do's for upcoming release**

- [x] Schedule release party - @patrickm02L 
- [x] Advise users of downtime - @patrickm02L 
- [x] Create a release PR - @frankhereford 
- [x] Propose + vote on release names - @patrickm02L 
- [x] Refine [release notes](https://github.com/cityofaustin/atd-vz-data/releases/tag/v1.29.0)  - @frankhereford 
- [x] Bump VZ **staging** version to `v1.30.0` and VZ production to `v1.29.0`- @frankhereford 
- [x] Send out release notes - @patrickm02L 
- [x] Create recommendations_partners table - @roseeichelmann 
- [x] Run partners migration script to fill table with recommendation/partner data - @roseeichelmann 
- [x] Delete coordination_partners_id column in recommendations table - @roseeichelmann

**Comment by frankhereford** [comment]
I think this is wrapped up - thanks everyone!

**Comment by patrickm02L** [comment]
Good and done. 

*Note: Netlify recognized that no substantive changes were made to the VZV application and therefore did not build a new application version. 1.28.0 still remains as the version number.
