### ISSUE TITLE
Project: APWA Accreditation

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#10566]
Legacy ATD joined the Citywide effort led by legacy PWD to [gain accreditation by](https://www.apwa.net/MYAPWA/Education___Credentialing/Accreditation/MyApwa/Apwa_Public/Education_and_Events/Agency_Accreditation.aspx?hkey=b7ef2b7a-ff55-47fa-9a01-50773572c9f5) the [American Public Works Association (APWA)](https://en.wikipedia.org/wiki/American_Public_Works_Association).

## Background
The [American Public Works Association (APWA)](https://www.apwa.net/) is a nonprofit professional association of public works agencies, private companies, and individuals dedicated to promoting professional excellence and public awareness through education, advocacy, and the exchange of knowledge. Its vision is, "Advancing quality of life for all." Its mission is to support those who operate, improve, and maintain public works and infrastructure.

**APWA accreditation** is a means of formally verifying and recognizing public works agencies for compliance with the recommended Practices set forth in the [Public Works Management Practices Manual](https://www.apwa.net/Store/detail.aspx?id=PB.APWM10). In other words, is the City of Austin following the best practices APWA has identified?

In 2015, the Public Works Department (PWD) became the 101st governmental entity to receive accreditation from APWA. 14 chapters including 211 "Practices" were evaluated and determined to be fully compliant. 7 Practices were granted “National Model” status, meaning they are now included in the APWA library of best practices for other cities around the country to model. To maintain accreditation, an agency must be re-evaluated every 4 years. During the re-accreditation evaluation in 2019, PWD was identified as the best-prepared agency in over 50 previous accreditations from around North America! 8 Practices were granted "National Model" status.

Legacy PWD was re-evaluated again in July 2023. This time around, they invited 5 partner departments to join the effort. Austin Resource Recovery, Watershed, Fleet Mobility, Building Services, and legacy ATD are all submitting new chapters for the first time, making this a true Citywide project. Legacy ATD is responsible for 3 chapters: Chapter 16 Right-of-Way Management, Chapter 34 Traffic Operations, and Chapter 35 Parking.

**An important note regarding the department merger:** PWD formally applied for reaccreditation in January (before the merger) and will use the City's organizational structure from that date. For the 2023 evaluation, we submitted documentation as legacy ATD. For reaccreditation in 2027 and beyond, we will submit as TPW.

## Scope & Deliverables
**Chapters Assigned to ATD:**
- Chapter 16: Right-of-Way (ROW) Management
- Chapter 34: Traffic Operations
- Chapter 35: Parking

There are 8 Practices in ROW Management, 24 Practices in Traffic Operations, and 10 in Parking, totaling 42 Practices across the 3 chapters.

**For each Practice, ATD must prove that the City follows a specific requirement set by APWA. We wrote a short explanation of how ATD and the City complies, and saved documentation as evidence to prove our compliance. The main goal of the project is to prove the specific requirement for each Practice.**

This is a true team effort. Elements crucial to the project's success are:
- Committed leadership all the way to the top 
- A high degree of employee involvement 
- An organized system of documentation 
- Commitment to improvement

### APWA Accreditation Process
**1. Plan + Build**
- Build SharePoint site, progress tracker + project tools
- Identify Lead + SME(s) for each Practice

**2. Document**
- Gather documentation as evidence
- Fill in Practice drafts

**3. Department Review**
- Peer review by Division Managers
- Executive review by Assistant Directors 

**4. Citywide Review**
- Cross-departmental review
- Mock evaluation 

**5. Accreditation**
- Submit documentation
- In-person evaluation

## Desired Outcomes
**We achieved our goal for ATD to earn a status rating of full compliance for our 3 chapters.** To do this, we built a team of leaders and subject matter experts (SMEs) across legacy ATD. We communicated the requirements from legacy PWD and followed their guidelines for success. We completed 42 Practices across 3 chapters by filling in the Practice draft and saving documentation as evidence. We centralized documentation with the [ATD APWA Accreditation SharePoint page](https://cityofaustin.sharepoint.com/sites/ATD_APWA_Accreditation) and tracked work with the [ATD APWA Progress Tracker](https://cityofaustin.sharepoint.com/sites/ATD_APWA_Accreditation/Lists/ATD%20APWA%20Progress%20Tracker/AllItems.aspx). Major milestones included sourcing and completing the documentation, several rounds of review and updates, a Citywide mock evaluation, finalizing and submitting all documentation, and the accreditation evaluation.

The project culminated in July 2023 with a formal submission to APWA and an in-person accreditation evaluation by certified APWA evaluators. During the in-person evaluation, designated presenters went through the Practices and answered questions posed by the evaluator. The average time per Practice was 2-3 minutes and only 1/3 of the Practices were selected to be presented on evaluation day (but we didn't know which ones those were so we had to be prepared for them all).

Following the 2023 accreditation, TPW must maintain APWA Practice drafts and evidence files in order to submit for re-accreditation in 2027. This will be an evolving relationship with regular, long term coordination across partner departments. There are also opportunities to tap into the vast resource of knowledge and documentation this project produces.

**An important note regarding official accreditation:** To gain APWA accreditation, an agency must submit Chapters 1-10, pay the APWA fees, and host an evaluation. The partner departments, including legacy ATD, gained valuable firsthand experience by preparing for and participating in an evaluation alongside legacy PWD. But this was an honorary evaluation for ATD and we did not receive the official accreditation because we did not submit Chapters 1-10 or pay the fees. However, OPM worked with APWA to design a custom accreditation logo that all partner departments are allowed to use, which says _City of Austin Public Works Accredited by APWA since 2015_.

### Benefits of the Accreditation Process
- Established department and Citywide culture of continuous improvement
- Improved operational performance
- Team building and staff development
- Succession planning and institutional knowledge retention
- Central location for documentation and standard operating procedures
- Increased efficiencies and reduced duplication and wasted resources
- Improved communication
- Justification for budget requests
- Lowering of insurance premiums
- Reduced liability

![51702919609_ac984087f6_c.jpg](https://images.zenhubusercontent.com/5a5f8dc94b5806bc2bc322a5/31baaf37-40f3-438f-bb22-8d098e7a3dff)

---
This Github issue represents a project of Austin Transportation's [Data & Technology Services](https://austinmobility.io/) team. Project status is documented regularly in the comments below.

**Comment by amenity** [comment]
Additional tasks not represented in the child issues of this epic:
- [ ] Update outdated evidence with an executive memo (3)
- [ ] Add memo as evidence to all practices
- [ ] Submit slide content for legacy ATD slide to OPM
- [ ] Rehearsal 6/22 
- [ ] Final edits and check by practice

**Comment by katelunceford** [comment]
## We achieved our goal!

Legacy PWD received reaccreditation; PWD and all partner departments (including legacy ATD) earned a rating of full compliance for each chapter submitted.

**One seasoned APWA evaluator said we (legacy ATD) were one of the best prepared groups.**

Executives sent kudos and a celebration is planned to recognize the achievement.

### Email from OPM with official accreditation 

Good Morning Partners!
 
I hope you all are feeling rested and accomplished after the APWA Evaluations! I am excited to share that the legacy PWD received reaccreditation status! The APWA evaluators sent the final evaluation report of all our departments [here](https://cityofaustin.sharepoint.com/:b:/r/sites/ATD_APWA_Accreditation/Shared%20Documents/DTS%20Internal/Evaluation%20Report%20from%20APWA.pdf?csf=1&web=1&e=oAqPzk).
 
Thank you all for the support, dedication, and passion you've given toward this massive effort… it couldn't have happened without your collaboration.

Partnering together,
Stephanie F.

### Email from OPM after evaluation 

Greetings all!
 
WE DID IT!
 
I am thrilled to announce that Public Works Department has been recommended for re-accreditation, and we have received preliminary indications that all Public Works and Partner departments' chapters have been found to be fully compliant. The formal decision will be delivered in the next 30-60 days. 
 
We could not have achieved this without the dedication, time, and support of each and every one of you. Your unwavering commitment has been invaluable and has propelled us towards this incredible recognition.
 
Planning for a celebratory event is underway and the details will be shared with you as soon as they are available. We look forward to celebrating with you all!
 
In the meantime, if you have any lingering questions or concerns, please do not hesitate to reach out to me. I am always available to assist in any way I can.
 
Once again, thank you again for your exceptional support and dedication.
 
Together,
Stephanie F. 

### Kudos from Richard M. 

Yall are awesome!!
Thank you I am looking forward to the official notice and celebrating together.
Richard

### Closing email to ATD participants 

To all our legacy ATD APWA participants, THANK YOU and JOB WELL DONE!
 
Last week we presented our 3 chapters to the APWA evaluators. We prepared, reviewed multiple times, prepared again, rehearsed, prepared some more and it was all worth it because...
 
We received preliminary indications that all legacy PWD, ATD, and partner departments’ chapters have been rated “full compliance” by the APWA evaluation team!!! 👏👏 👏 The formal decision will be delivered in the next 30-60 days.
 
I’d like to give a big shout out to our presenters who attended the evaluation last Tuesday. I’m going to deliver a little jar of my dad’s honey to each of you over the next few weeks as a small thank you because it was a crazy day, and some things went differently than how we were told—being hours behind schedule, having to use APWA’s software at the last minute, and a stricter evaluation just to name a few. But our team remained steady and professional the entire time. And most importantly, the evaluators were impressed with our Practices and gave us the “full compliance” rating we’ve been working toward.
 
We could not have achieved this department-wide goal and incredible recognition without the commitment and support that each and every one of you have shown throughout this last year. So, again, thank you and job well done!!
 
I’m told that planning for the party we’ve been promised is underway and I’ll share details as soon as they become available. In the meantime, give each other a giant virtual high five for achieving this amazing recognition 🙌
 
Thank you!!
Kate
### Kudos from Jim D.

Great news Kate! Many thanks to the dedication of everyone and the time found in your schedules! Looking forward to the official notification. 

Jim D., P.E., Interim Deputy Director
