### ISSUE TITLE
Self-led Usability Testing Guide for SMS Providers

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#10572]
Similar to Traffic Register Self-led Usability Testing Form

- [x] Create a form for providers to use while they're usability testing
- Reference SMRT Usability Testing we used for internal staff

**Comment by dianamartin** [comment]
- [x] Created new `usability testing` object
- [x] Created new page [`usability testing`](https://atd.knack.com/smrt#usability-test/), added it to "Account Details" 
![image](https://user-images.githubusercontent.com/21112975/197294134-bd7926c9-435c-4ba1-83a3-8bd8fbc34794.png)

@patrickm02L it's ready for review

**Comment by patrickm02L** [comment]
Really nice. I submitted a form. 

I think we should ask questions for every task. I found myself needing a prompt to get the thoughts rolling and have something to respond to in the input field. 

i.e. Describe your experience logging-in. How might you improve the log-in process?

**Comment by dianamartin** [comment]
@patrickm02L did you want to come up with Prompt questions for each task then and I can update the form?

**Comment by patrickm02L** [comment]
@dianamartin I added prompts when I submitted the form on the off chance you might ask that question. Is there a way to access the responses or did they disappear into the ether?

**Comment by dianamartin** [comment]
@patrickm02L They're saved on the back end, it didn't occur to me to check your responses. Good idea to create them while you were testing. How was the flow? Do we need to make any significant changes? I think we should sync on this a little. I had some concerns about them doing "self guided testing" bc of the whole account creation part and the back and forth part too.

**Comment by patrickm02L** [comment]
The flow works. I suggest making the Task the title of each test, and then having questions as the prompt for the text boxes at the end of the section. 

<img width="1081" alt="Screen Shot 2022-10-24 at 3 10 48 PM" src="https://user-images.githubusercontent.com/5566727/197620608-c792047d-c67c-4049-bc54-c875c077e8b3.png">

**Comment by dianamartin** [comment]
# 10/25
- Sync with Patrick, changed the Task headings and added questions to prompt user feedback
- Changed Rating this process to "star rating", includes half stars

## Planning
- Meeting with provider, let them know the process
- Schedule time frame with provider (so they can experience a rejected/need more info attachment)
  - and practice the "re-submit attachment" process 


  -

**Comment by dianamartin** [comment]
11/8 
from Claire
![image](https://user-images.githubusercontent.com/21112975/200673957-1e89123e-fdcb-47b1-92c1-135c94ecfacf.png)

**Comment by patrickm02L** [comment]
11/18/22. In the Sprint Review meeting we decided to send the Usability testing questionnaire/survey to Providers who have submitted application to get their feedback. 

Follow up with: Bird, Wheels, Link

**Comment by patrickm02L** [comment]
Completed.
