### ISSUE TITLE
Reassign certain performance measure (9191) to "Transportation Demand Management"

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#10593]
> What application are you using?

Data Tracker

> Describe the problem.

The performance measure 9191 "Percent of City of Austin employee commute trips by walking, bicycling, sharing rides, or transit" is currently listed in Knack & eCombs under Transportation System Development, but needs to be assigned to the Transportation Demand Management program under Smart Mobility per Cole K.

> How soon do you need this?

Soon — Within a week 

> Is there anything else we should know?

I am trying to get performance measures for FY22 entered by early November. 

> Requested By
Melissa B.

[Attachment](https://api.knack.com/v1/applications/595d00ebd315cc4cb98daff4/download/asset/6358138a210ac90021b0122a/screenshotcolekittenemail.png) (77.86kb)

Request ID: DTS22-105485

**Comment by dianamartin** [comment]
## Current Division Owner
9191-  "Percent of City of Austin employee commute trips by walking, bicycling, sharing rides, or transit" 
- [ ] Needs to move to Transportation Demand Management - Smart Mobility

**Comment by dianamartin** [comment]
Messaged Melissa - 10/26
>For request Reassign certain performance measure (9191) to "Transportation Demand Management" #10593, this has been done as well.
>- Is now showing up under Transportation Demand Management
![image](https://user-images.githubusercontent.com/21112975/198111311-bceb7268-997e-4376-832d-1a6bf0222c90.png)

**Comment by dianamartin** [comment]
Melissa said that the `9191` measure was still showing as SSD rather than TDM. Checked and she was right, had to update the `performance_measures_fiscal` object.
>Hi Diana, sorry, but I just noticed that in knack performance measure 9191 is still showing up under the Transportation Systems Development division when it should be Transportation Demand Management. Do I need to submit another service request for this?

I said
>I'm not seeing it

she sent
![image](https://user-images.githubusercontent.com/21112975/198400084-35ff7dea-4601-4a81-a902-e380b45e34f5.png)

- Synced with Melissa
- Had to fix it off the call

- [x] Removed part of rule
- [x] Force updated 3 records
- [x] Division MC updated to show TDM

Messaged Melissa
>Hi I figured out how to fix it
![image](https://user-images.githubusercontent.com/21112975/198400225-5f14bac7-ec87-49cc-892b-9d6a98f83f1a.png)
