### ISSUE TITLE
[Tech Debt] Eliminate the use of a record in `moped_entity` to represent `null`

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#10594]
In the `moped_entity` lookup table, we have an option with `id` `0` that is used to represent "None". We should remove this lookup option and instead simply use a `null` value in places where this empty lookup option would otherwise be used.

Please also see Frank's comment which explains the issue at length: https://github.com/cityofaustin/atd-moped/pull/835#discussion_r1001880685.

### Todo

* [x] Create a migration to set `moped_project.project_sponsor` from `0` to `null`
* [x] Create a migration to set `moped_project.project_lead_id` from `0` to `null`
* [x] Create a migration to delete all `moped_proj_partners` which have `entity_id` = `0`
* [x] Remove the record with `id` `0` in `moped_entity`.
* [x] Update front-end wherever this magic record is used and convert the columns which point to `moped_entity` to use the _null_ value to indicate that there is not a relationship to the `moped_entity` table.

**Comment by frankhereford** [comment]
@chiaberry Would it be alright to bring this to the next grooming meeting? Thanks!

**Comment by johnclary** [comment]
"Migrating" away from the use of this value may be slightly complicated by the way we store entity data that relates to project records. See: https://github.com/cityofaustin/atd-data-tech/issues/10607
