### ISSUE TITLE
[MEETING] AMD Non-Technician Work Order Discussion

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#10614]
### Objective 
Discussing the New Work Order Forms/Pages/Features and capturing what the other work groups (Inspections, Signal Engineering, Communications) use on the “Non-Technicians Work Order” 
•	Brief on the new pages (My Work Orders, Work Order – Technicians)
•	Brief on the new functionality (Attachments, Commenting, Scheduled Work, Completed Work, Preventative Maintenance)
•	Identify improvements/enhancements – anything missing?

### Participants
Brian C., Ivonne, Joshil, Harrell, 

### Agenda
Add agenda here or create agenda from [this template](https://docs.google.com/document/d/1d_49KW5C_vSz8Bs50v-cxyIJuTNJMwMrh7ypcxRHgZI/edit#) and add link. 

------
- [x] Schedule meeting -
- [ ] Optional: Schedule debrief
- [x] Meet and take notes
- [ ] Optional: Debrief with DTS team members
- [x] Create resulting issues

**Comment by dianamartin** [comment]
Add "Communications"

Non-Technician Work Order 
- Attachments
- Comments

## Enhancement
Unassign a Work Order
- Joshil 

Advanced Search Work Orders
- Add "Created By" field
- Add "Assigned To" field 

## How they use a work ticket
- Harrell, Joshil, Brian G. has been using Non-Technician work order

## Checking Out Inventory Equipment  
- Need the ability to 
- Didn't want DOSA or Location (Individual) location
- Do not require submit conditional

## Non-Technician Needs
- keep field "Work Location (if not at a signal intersection)"

PAIN POINT
Bulk Work Order creation
- ENHANCEMENT: Copy a work ticket (Work Order, Scheduled Work, Inventory Items

# Work Order Details - Detectors (Joshil)
- Check out equipment - leave it unassigned 
- Create work orders for contractors
- Get CSR --> Work Order (Currently in Technician format)

# Work Order Details - Communications 
- No DOSA
- Not mandatory to submit a ticket
- Never gets CSR --> Work Order
- One day will get CSR --> Work Order for Comms. group

# Work Order Details - Timing Engineers
- Checking out inventory - certain location (signal)
  - Controllers & Monitors
- Closing Abilities - allow others to close Work Order
- Engineer Review (SR), writes comments, they do not create work 

# Changes to Non-Technician Work Order
- Work Order Table - NO CHANGES

**Comment by amenity** [comment]
@dianamartin - add new issues when you get a chance.

**Comment by dianamartin** [comment]
-  [ ] Create issue for Discovery of "Non-Technician" work order - hide DOSA and PM based on Work Order Type
