### ISSUE TITLE
Update Data Tracker Account for Shanice D 

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#10643]
> What application are you using?

Data Tracker

> Describe the problem.

I recently changed my email. I may have had access before but I do not have access to the data tracker anymore. My old email address was 

> How soon do you need this?

Soon — Within a week 

> Requested By
Shanice D.

Request ID: DTS22-105555

**Comment by dianamartin** [comment]
@KaroEngstrom I've assigned this issue to you, the email address is in the details. We'd want to make sure this person is talking about the correct application.

**Comment by KaroEngstrom** [comment]
T 11/1/22 
- talked to Diana about this one and identified Traffic Counts, Attachments, and Comments as objects where the user's account information needs to be updated. 

- [ ] Create new account to mirror previous one 
- [ ] Update the above-mentioned objects 
- [ ] Inactivate old account 
- [ ] Ask user to test logging in and accessing the Data Tracker as before 
- [ ] When confirmed to be working, delete old account
