### ISSUE TITLE
AMD Non-Technician Work Order Updates from 10/26

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#10677]
Add "Communications"

Non-Technician Work Order 
- Attachments
- Comments

## Enhancement
Unassign a Work Order
- Joshil 

Advanced Search Work Orders
- Add "Created By" field
- Add "Assigned To" field 

## How they use a work ticket
- Harrell, Joshil, Brian G. has been using Non-Technician work order

## Checking Out Inventory Equipment  
- Need the ability to 
- Didn't want DOSA or Location (Individual) location
- Do not require submit conditional

## Non-Technician Needs
- keep field "Work Location (if not at a signal intersection)"

PAIN POINT
Bulk Work Order creation
- ENHANCEMENT: Copy a work ticket (Work Order, Scheduled Work, Inventory Items

# Work Order Details - Detectors (Joshil)
- Check out equipment - leave it unassigned 
- Create work orders for contractors
- Get CSR --> Work Order (Currently in Technician format)

# Work Order Details - Communications 
- No DOSA
- Not mandatory to submit a ticket
- Never gets CSR --> Work Order
- One day will get CSR --> Work Order for Comms. group

# Work Order Details - Timing Engineers
- Checking out inventory - certain location (signal)
  - Controllers & Monitors
- Closing Abilities - allow others to close Work Order
- Engineer Review (SR), writes comments, they do not create work 

# Changes to Non-Technician Work Order
- Work Order Table - NO CHANGES

_Originally posted by @dianamartin in https://github.com/cityofaustin/atd-data-tech/issues/10614#issuecomment-1292651813_

**Comment by dianamartin** [comment]
# Non-Techician Work Order Updates
- [x] Added "Inventory Item button" (menu) - to save page real estate
- [x] Removed embedded "Inventory Item button"

**Comment by dianamartin** [comment]
# Non-Techician Work Order Updates
- [x] Added "Inventory Item button" (menu) - to save page real estate
- [x] Removed embedded "Inventory Item button"

**Comment by dianamartin** [comment]
Emailed stakeholders 11/3
>Hi Everyone, 

Based on our meeting on 10/26, we talked about some updates to the Non-Technician Work Order details page. I’ve working on those changes and here things that changed. 

You’ll notice the navigation menu; I’ve added the following: 
•	Re-Assign (we can remove if you all don’t use this)
•	Add Attachment/Image
•	Add Comments
•	Added page rules for Close Work Order 
o	Will require the Completed Work and Inventory Items (even if it’s a “0” quantity, we have an item for that)
•	Added more fields to Non-Technician Work Order details - have been reordered to look similar to on the “Work Order – Technician” details page
•	Added Comment button/table
•	Added Attachments & Images button/table
![image](https://user-images.githubusercontent.com/21112975/199846947-51b29371-fd9e-4151-a08d-08d380d12ac8.png)

These are the additional features that have been added
•	Added Scheduled Work button/table
•	Added Completed Work button/table
•	Added "Inventory Item button" (menu) - to save page real estate
o	Removed embedded "Inventory Item button"
•	Renamed "File Attachments" to "Signal File Attachments"
![image](https://user-images.githubusercontent.com/21112975/199846878-11f025be-5727-450c-ba07-5860cd377ccb.png)

Please let me know if you run into any issues or have questions.
