### ISSUE TITLE
Add "Curve Early Warning Beacon" asset type

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#10771]
> What application are you using?

Data Tracker

> Describe the problem.

When +adding a new Flashing Beacon (asset), can you please add an option for a Curve Early-Warning Beacon?  We are working with Vision Zero on a project to install several of these signs and will be creating assets for them soon.

> How soon do you need this?

Flexible  — An extended timeline is OK

> Is there anything else we should know?

Needed soon (maybe not within a week but sooner rather than later). 
We need to create the assets for these signs in Data Tracker so the locations will import/show(?) in Moped map for VZ staff to see as well.

> Requested By
Erin B.

Request ID: DTS22-105660

**Comment by ChrispinP** [comment]
@dianamartin are you familiar with which object these assets are in? thanks

**Comment by dianamartin** [comment]
@ChrispinP it's on the object `flashing_beacon`, Column "BEACON_TYPE" - [backend](https://builder.knack.com/atd/amd/schema/list/objects/object_110/fields/field_1697/settings)

**Comment by KaroEngstrom** [comment]
# W 1/25/23 

- [x] Added CURVE_EARLY_WARNING_BEACON asset type to `flashing_beacon` object in Data Tracker 
- [x] Checked front-end Knack
![image](https://user-images.githubusercontent.com/100615928/214663980-2ffd6718-e09b-48ea-8e13-ae0f63fb39ce.png)
- [x] Updated the Data Tracker change log 
- [x] Notified the requester and PM

**Comment by KaroEngstrom** [comment]
From requester: "That should do it. Looks good. Thank you so much!"
