### ISSUE TITLE
Copy SMB Knack App and Create Gitbook Checklist for Copying Apps 

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#10780]
For completing and testing #10140, 
- [x] Copy SMB environment
- [x] Check on Slack to ensure no one needs the previous test environment 
- [x] Delete old test environment `TEST | SMB - 29 JUN 2021 | Signs and Markings Operations`
- [x] Write up checklist instructions in Gitbook for copying a Knack app

**Comment by KaroEngstrom** [comment]
## W 11/30/22 

- deleted the JUN 2021 test environment and updated the DTS Portal Application log
