### ISSUE TITLE
Update "Journal Voucher" info in AMD Data Tracker - Warehouse Inventory- October 2022

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#10800]
- [x] Spreadsheet emailed from Finance staff month of: October 2022, date range: 10/21/2022
- [x] Number of records being updated: 132
- [x] Format spreadsheet [(Review instructions)](https://atd-dts.gitbook.io/atd-knack-operations/warehouse-inventory-updating-journal-vouchers-jv-information)
- [x] Spot check Transaction IDs, no JV information before import (20700)
- [x] Import records
- [x] Spot check Transaction IDs, no JV information after import
- [x] Email Finance staff that update task complete
