### ISSUE TITLE
2023 Mobility Annual Plan

### ISSUE THREAD

**Issue by andrewshensky** [cityofaustin/atd-data-tech#10819]
**General tasks**

- [x] Dataset configuration for layers to be used in 2023 MAP Public Map (about 25)
- [x] Append relevant data from Charrette map to 2023 datasets
- [x] Create/configure new web map holding 2023 MAP Public data
- [x] Create/Configure Web App to Mirror 2022 MAP (Web App/data will remain shared to Org until Council Approval)
- [ ] Print map for use in 2023 MAP narrative
