### ISSUE TITLE
Update "Journal Voucher" info in AMD Data Tracker - Warehouse Inventory- December 2022

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#10907]
- [x] Spreadsheet emailed from Finance staff month of: December, 10/03/22-11/16/22
- [x] Number of records being updated: 208
- [x] Format spreadsheet [(Review instructions)](https://atd-dts.gitbook.io/atd-knack-operations/warehouse-inventory-updating-journal-vouchers-jv-information)
- [x] Spot check Transaction IDs, no JV information before import: 20880; 20350
- [x] Import records
- [x] Spot check Transaction IDs, has JV information after import: successful
- [x] Email Finance staff that update task complete

**Comment by KaroEngstrom** [comment]
## T 12/6/22 

- follow-up email from Crystal that six transaction items were included in above but were not yet ready
- will delete the JV date and JV ID and check status for those six items
- these items will be updated with JV info with a later batch

- [ ] remove false info from JV cells for these items 
- [ ] check JV status
- [ ] email Crystal to let her know those items are fixed
