### ISSUE TITLE
Import new codes to be inputted in a separate section under the MetroBike module of SMO app

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#10916]
> What application are you using?

Data Tracker

> Describe the problem.

I would like to request these new codes to be inputted in a separate section under the Bike Share Benefit database in SMO's Knack platform. I received some inquiries from ABIA employees who would like to redeem a MetroBike membership but their email domain was an issue before. 

> How soon do you need this?

Soon — Within a week 

> Requested By
Eliza Y.

[Attachment](https://api.knack.com/v1/applications/595d00ebd315cc4cb98daff4/download/asset/638a33f2abf0d50023c35d12/abiacodes.csv) (503.0b)

Request ID: DTS22-105815

**Comment by KaroEngstrom** [comment]
I'd love to learn how the different tenants were handled in the system since I'm often updating the codes for MetroBike.

**Comment by dianamartin** [comment]
- [ ] Add "@flyaustin.com" email to the add metrobike benefit form
![image](https://user-images.githubusercontent.com/21112975/206281159-b8c55385-8574-4dd8-8420-b8ddad7b1422.png)

- [ ] Add new "ABIA" as a category
![image](https://user-images.githubusercontent.com/21112975/206281022-a2a9f8eb-1fb4-4ec9-8d8d-4add4d9468b8.png)

- [ ] load ABIA promo codes to `promo_codes_bike_shared_benefit`

**Comment by KaroEngstrom** [comment]
F 12/16/22 

- used Diana's checklist above and added the changes to page views as well ^ 
- emailed Eliza about the completion 
- updated change log in SMO

**Comment by KaroEngstrom** [comment]
Eliza checked it and wrote back: "Wonderful, thank you Karo! Have a good weekend 🙂"

**Comment by KaroEngstrom** [comment]
## Th 12/22/22 

- follow-up from Eliza - an error when ABIA users are trying to submit a request 
- found additional conditional rule for the email field and updated it to allow @flyaustin.com emails
![image](https://user-images.githubusercontent.com/100615928/209169357-9f7c174e-7d0a-45fd-b87f-13e556c3187c.png)
- notified Eliza
