### ISSUE TITLE
Provide MCC with an export of signal timing data

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#10923]
Provide MMC staff (Lance and Allyson) with a export of signal timing data from the Data Tracker. This would include:
- corridors
- zones
- timing data

**Comment by johnclary** [comment]
@dianamartin after a quick glance in the Data Tracker, based on conversations with AMD and looking in the Data Tracker, AMD folks seem to updating both the new and old signal timing data. I guess we should probably just send them everything. i assume y'all want to run this through sprint planning but let me know if you'd like me to help with this. cc @amenity

**Comment by dianamartin** [comment]
# 12/5
Exported tables for AMD
- [x] `corridor_retiming_zones` - [corridor_retiming_zones.csv](https://github.com/cityofaustin/atd-data-tech/files/10157363/corridor_retiming_zones.csv)
- [x] `corridors` - [corridors.csv](https://github.com/cityofaustin/atd-data-tech/files/10157364/corridors.csv)
- [x] `corridor_retiming` - [corridor_retiming.csv](https://github.com/cityofaustin/atd-data-tech/files/10157365/corridor_retiming.csv)

**Comment by dianamartin** [comment]
Lance replied 12/30
>... I think we’d also like a list of membership for each signal (zone and corridor). Could we have that table as well?

Brian G. replied 12/30
>Most of that was imported from here:

`G:\ATD\Arterial Management\Programs\ASR - The Next Generation
Signal Systems List 8.8.22.xlsx`

This may not be perfectly up-to-date with any activations we have done this fall.
