### ISSUE TITLE
Enhancement: Add "Approved" (button) not part of current "Approval Information form"

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#10957]
Andrea M.
SMS

Said that she discovered an issue with the Permit Team workflow. Courtney's team prepares the Approval Letters, but Courtney's name should be the one that's on the letter itself. 

I renamed the existing button from "Approve" to "Save Approval Information"
- Removed the record rules
  - [x] Approval Date
  - [x] Approved By
  - [x] Application Status - Approved
- Added new "Approve" button
  - Removed the record rules
    - [x] Approval Date
    - [x] Approved By
    - [x] Application Status - Approved
    - [x] renamed the form submit button to "Approve"
    - [x] Added page rule that if App Status is Approve to hide this form/button

**Comment by dianamartin** [comment]
Was on the phone with Andrea when I fixed this issue so that Courtney's team can prepare the Approval letters and have Courtney sign them. Andrea said she's train Paul on the process so he can train his team mates.
