### ISSUE TITLE
[Data Tracker] Rename filter option names to match the columns in tables and be in that order

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#10994]
> What application are you using?

Data Tracker

> Describe the problem.

Can we have all of the filter option names match the columns in tables and be in that order.

> Describe the outcome you'd like to see when this feature is implemented.

Time savings when trying to filter tables

> Describe any workarounds you currently have in place or alternative solutions you've considered.

must spend a lot of time looking through the filter list. This is an issue with pretty much all of the tables. 

> Requested By
Brian C.

Request ID: DTS22-105850

**Comment by KaroEngstrom** [comment]
## M 12/19/22 

@dianamartin @ChrispinP 
- I'd like to discuss in an app sync is this work is feasible: willchanging the builder-side names of fields to reflect what is displayed in the table cause unintended consequences or tons of work on the level of rules and connections? 

**Filter option names** 
![image](https://user-images.githubusercontent.com/100615928/208476245-e95ad568-05e2-49c9-92c4-8e7ca8e05eb8.png)

**Table column names** 
![image](https://user-images.githubusercontent.com/100615928/208476314-de390b48-6d33-4365-8110-e7ee3c3e334b.png)

**Comment by KaroEngstrom** [comment]
## T 12/20/22 

- Synced with Chrispin M 12/19/22 - we can remove any non-table items from the filter and change the order of dropdown items (to a degree, depending on text formulas) 
- Changing the actual names of fields is more risky and we need to check with Diana 

**NEXT STEPS** 
- [ ] Limit filter fields to table fields only 
- [ ] Reorder fields as much as possible 
- [ ] Check with requester on this Signals table as a model - explain what was done and request feedback; which tables are the most crucial? 
- [ ] Check in with Diana once she's back on field name item and urgency of applying this to more/all tables in Data Tracker

**Comment by KaroEngstrom** [comment]
Th 12/22/22 

- a note from Brian: "This is certainly helpful. I will identify some other problematic tables to filter through. Thanks" 
- closing this issue for now; will update any additional tables that may need the switch as those are flagged by the requester
