### ISSUE TITLE
User Feedback from Finance Sprint Review 12/7/22

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#10993]
@dianamartin has started notes on what feedback to address [here](https://docs.google.com/document/d/1p69sxrPyap4wkGY3bWkuVg8N3GQEyvCSffME4q-OMjA/edit#).

- If Type “Memo”
  - [x] then Amount $50k
- If Memo
  - [x] Hide “Amount” 	
  - [x] Hide Encumbered

Reorder fields:
- Task Type: TK
- Type: Memo/Billable
- TK Name
- Encumbering FDU 
- Amount

### Job table 
- [x] Add Delete icon
- [x] Rename “Review Request” to “Review Service Request”

### SR Details page
- [x] Remove Estimated Amount if “Memo” - on Jobs table

### Encumbering FDU 
- 12 digits (3 sets of 4 numbers: Example: xxxx-xxxx-xxxx)

## Task Orders
- Modify TK
- Close TK
- New Field “Created Task Order No.” 
- ex. `24ENG01121` (10 characters) 
- formula: (`24`)(`ABR`)(`5 digits`)

## SubProject - Add new job
- Re order: Parent Project (on top)
- New field: “Created SubProject No.” 
  - 1152.043 (this is normally the format)
  - alternative should include four digits at the end and with letters.

## FDU 
- Funding Source FDU (change to required)
- Hide “FDU” field, needed for other types
- Internal Note to create BGEX if “Amount” is populated
- New field: “Created FDU No.” - (3 sets of 4 numbers: Example: xxxx-xxxx-xxxx)  (this is always the format)

## Service Request Jobs table
SR Details
- [ ] WORK ON: Close SR - send to customer

Provide Links: 

https://atd.knack.com/finance-purchasing#service-requests
https://atd.knack.com/finance-purchasing#service-request-jobs

**_May need to create an Issue to clean up TK with new structure._**

**Comment by patrickm02L** [comment]
@dianamartin, we believe that you've accomplished the tasks in this Issue, and may have documented them in a Sprint Agenda. 

Please review with the the intent to close out.

**Comment by dianamartin** [comment]
We created a new issue #11487 can close this issue.
