### ISSUE TITLE
Create Tracking Solution for Augmented Staff Hours

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#11044]
> What application are you using?

Other / Not sure

> Describe the problem.

Per my discussion with Diana M.:
We need to create a SharePoint sheet based on the XLS I have started (link below). This sheet, once approved by Brian Craig, will be used by augmented staff to track their hours per project for later JV transactions.  Please contact me for further information.

https://cityofaustin.sharepoint.com/:x:/r/sites/atdAMD/_layouts/15/Doc.aspx?sourcedoc=%7B309D4CBB-94D8-493F-B326-AF1452BB1CFF%7D&file=Augmented%20Staff-%20PROPOSED%20Draft.xlsx&action=default&mobileredirect=true

> How soon do you need this?

Flexible  — An extended timeline is OK

> Is there anything else we should know?

Flexible, but need it sooner rather than later so augmented staff can begin tracking their hours.

> Requested By
Erin B.

Request ID: DTS22-105930

**Comment by KaroEngstrom** [comment]
# W 12/21/22

- @dianamartin  and I had discussed this briefly before her vacation; putting this in Scoping and on our list to discuss in App Sync next week 12/29

**Comment by KaroEngstrom** [comment]
## W 12/28/22 

- plan scoping meeting w/ stakeholders (Erin B; Ivonne; Brian C) - Karo
- potential follow-up with Meredith

**Comment by dianamartin** [comment]
# 1/9
Met with stakeholders and discussed some potentially viable solutions.
- Excel spreadsheet
  - Meredith group has been doing it on spreadsheets for the last few augmented contracts
- SharePoint list
- new knack module
- use existing work orders

## Timeline
- work on it this week
- Let AMD know when this is configure Brian, Ivonne, Erin

## Prep Work
- [ ]  Add work log for non-technician
- [ ]  Add “Hours Worked” (optional)
- [ ]  Add “Minutes Worked” (optional)

## Next Steps
- have 2 new (aug. staff) employees enter non-technician work orders in Data Tracker for a week

- Find work ticket for non-technician enhancements
  - related ticket that Harrell submitted in Nov, #10779

**Comment by dianamartin** [comment]
@ChristinaTremel do we still need this?
