### ISSUE TITLE
Update "Journal Voucher" info in AMD Data Tracker - Warehouse Inventory- December 2022

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#11062]
- [x] Spreadsheet emailed from Finance staff month of: December (12/22/22)
- [x] Number of records being updated: 445
- [x] Format spreadsheet [(Review instructions)](https://atd-dts.gitbook.io/atd-knack-operations/warehouse-inventory-updating-journal-vouchers-jv-information)
- [x] Spot check Transaction IDs, no JV information before import: 22260; 21654
- [x] Import records
- [x] Spot check Transaction IDs, no JV information after import: 22260; 21654
- [x] Email Finance staff that update task complete; filter [here](https://atd.knack.com/amd#inventory-reports/issued/?view_2799_filters=%7B%22match%22%3A%22and%22%2C%22rules%22%3A%5B%7B%22field%22%3A%22field_3825%22%2C%22operator%22%3A%22is%22%2C%22value%22%3A%7B%22date%22%3A%2212%2F22%2F2022%22%7D%2C%22field_name%22%3A%22Journal%20Voucher%20Date%22%7D%5D%7D&view_2799_page=1)
- [x] Update change log
