### ISSUE TITLE
Update "Journal Voucher" info in AMD Data Tracker - Warehouse Inventory- January 2023

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#11075]
- [x] Spreadsheet emailed from Finance staff month of: January 2023; txn dates 12/12/22-1/24/23 
- [x] Number of records being updated: 303
- [x] Format spreadsheet [(Review instructions)](https://atd-dts.gitbook.io/atd-knack-operations/warehouse-inventory-updating-journal-vouchers-jv-information)
- [x] Spot check Transaction IDs, no JV information before import: 22665; 22709
- [x] Import records
- [x] Spot check Transaction IDs, has JV information after import
- [x] Email Finance staff that update task has been completed [with filter to display updates](https://atd.knack.com/amd#inventory-reports/issued/?view_2799_filters=%7B%22match%22%3A%22and%22%2C%22rules%22%3A%5B%7B%22field%22%3A%22field_3825%22%2C%22operator%22%3A%22is%22%2C%22value%22%3A%7B%22date%22%3A%2201%2F25%2F2023%22%7D%2C%22field_name%22%3A%22Journal%20Voucher%20Date%22%7D%5D%7D&view_2799_page=1)
- [x] Updated changed log
