### ISSUE TITLE
Add export button to the Technician Work Order page in Data Tracker

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#11089]
> What application are you using?

Data Tracker

> Describe the problem.

I cannot export data from the "Technician Work Order" page. Filters are available, but no export button.

When I export the database from the Work Orders Advanced Search page, I see that they are missing the Signal ID number and TK number. The Signal ID is needed for sorting and the TK number is needed to determine if it was back-chargeable work or not.

> Describe the outcome you'd like to see when this feature is implemented.

Using the data from these exports, AMD will be able to analyze the frequency of different equipment failure types over time. We will also be able to determine how many units of each component are being replaced due to failure or maintenance or installed new as a mod or upgrade.

> Describe any workarounds you currently have in place or alternative solutions you've considered.

No work arounds available at this time. This is the first step in a new task that has been assigned to several senior managers for implementation in their SSPRs for this year.

> Is there anything else we should know?

ASAP, as usual. I'm hoping this isn't too big of an ask and can be implemented fairly quickly. by modifying the two export tables to include the fields needed. If possible, please add the fields to the right of existing export tables so as to not mess with anyone else's lookup tables or ranges. Much thanks! BDVDW

> Requested By
Brian V.

Request ID: DTS22-106050

**Comment by KaroEngstrom** [comment]
# T 1/3/23

## Request 1 - Filter for Technician Work Orders Page
- [ ] Confirm with requester the correct page for this table
- [ ] Add Export option 
- [ ] Update change log
- [ ] Inform requester 

## Request 2 - Modify Work Orders | Advanced Search Page 
- from request: 
` Work Orders Advanced Search page [table is]  missing the Signal ID number and TK number. `
     - `The Signal ID is needed for sorting `
     - `The TK number is needed to determine if it was back-chargeable work or not`
     - `If possible, please add the fields to the right of existing export tables so as to not mess with anyone else's lookup tables or ranges.`
- @dianamartin @amenity This second item for the Work Orders Advances Search page might be for AMD Sprint Review discussion as it effects all users/managers.
