### ISSUE TITLE
Finalize ATD submissions for APWA accreditation - Chapter 16 ROW Management (7 Practices)

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#11084]
### Tasks for each Practice
- [x] Do a final review of the Practice sheet and corresponding EVIDENCE folder using the checklist below 
- [x] Communicate final gaps / questions to the Lead
- [x] Support Leads to ensure everything is finalized by **Jan 30th** to submit to PWD (but PWD said we can submit chapter by chapter if we don't have everything quite done by then)

### Final checklist for each Practice
1. Does the Agency Compliance statement match the Practice requirement (blue statement)? Is it specific, succinct, and easy to follow? (acronyms should be defined; vague, general statements are not good) 
2. Are naming and formatting standards used? (evidence number, file names, wording, etc.) 
3. Is each item of evidence listed in the Documentation/Directives table linked if possible?  
4. Is there a PDF file saved for each item of evidence listed in the Documentation/Directives table? 
5. Is each PDF file specific, highlighting or only including the info related to the specific Practice requirement? (entire manuals with lots of pages is not good - it should only include what's relevant; highlight exact sentences and/or headings when possible)
6. Are there any remaining comments / unanswered questions from the executive review guide? 

### [Chapter 16 ROW Management (7 Practices)](https://cityofaustin.sharepoint.com/sites/ATD_APWA_Accreditation/Lists/ATD%20APWA%20Progress%20Tracker/AllItems.aspx?FilterField1=field%5F4&FilterValue1=16%20%2D%20ROW%20Management&FilterType1=Choice&viewid=db3efeaa%2D5db2%2D4df4%2D99cb%2Df1da454529cb)
- [x] [16.01](https://cityofaustin.sharepoint.com/:w:/r/sites/ATD_APWA_Accreditation/_layouts/15/Doc.aspx?sourcedoc=%7B1E8089AA-0B7D-459B-9322-77E041BBFBD9%7D&file=ATD%2016.1%20Permit%20Issuance.docx&action=default&mobileredirect=true) Permit Issuance
- [x] [16.02](https://cityofaustin.sharepoint.com/:w:/r/sites/ATD_APWA_Accreditation/_layouts/15/Doc.aspx?sourcedoc=%7B1758B879-B39C-45A8-B4C1-60200E05E847%7D&file=ATD%2016.2%20Permitting%20Responsibilitty.docx&action=default&mobileredirect=true) Permitting Responsibility
- [x] [16.03](https://cityofaustin.sharepoint.com/:w:/r/sites/ATD_APWA_Accreditation/_layouts/15/Doc.aspx?sourcedoc=%7B904701F1-5226-431F-8879-44C855A38C08%7D&file=ATD%2016.3%20Codes%20and%20Permits%20Information.docx&action=default&mobileredirect=true) Codes and Permits Information
- [x] [16.04](https://cityofaustin.sharepoint.com/:w:/r/sites/ATD_APWA_Accreditation/_layouts/15/Doc.aspx?sourcedoc=%7BBA5726D4-41BD-41C7-9F61-17BB0B495312%7D&file=ATD%2016.4%20Permit%20Process.docx&action=default&mobileredirect=true) Permit Process
- [x] [16.05](https://cityofaustin.sharepoint.com/:w:/r/sites/ATD_APWA_Accreditation/_layouts/15/Doc.aspx?sourcedoc=%7B64B58B60-A6C5-4DCD-854F-82439359D517%7D&file=ATD%2016.5%20Permit%20Inspection.docx&action=default&mobileredirect=true) Permit Inspection
- [x] [16.06](https://cityofaustin.sharepoint.com/:w:/r/sites/ATD_APWA_Accreditation/_layouts/15/Doc.aspx?sourcedoc=%7B99E0AF59-6D0A-45A3-87CF-272234681437%7D&file=ATD%2016.6%20One-Call%20Center%20Coordination.docx&action=default&mobileredirect=true) One-Call Center Coordination
- [x] [16.07](https://cityofaustin.sharepoint.com/:w:/r/sites/ATD_APWA_Accreditation/_layouts/15/Doc.aspx?sourcedoc=%7BD53A5157-A585-44CC-BBD8-68CECB4D73E4%7D&file=ATD%2016.7%20Utility%20Marking%20Guidelines%20and%20Color%20Code.docx&action=default&mobileredirect=true) Utility Marking Guidelines and Color Code

**Comment by katelunceford** [comment]
Meeting notes w/ Peggy 1/10 at 9:30 AM:

Chapter 16 ROW 
16.1 - looks good
16.2 - two questions to ask at next review: 

- Is it ok that we mention dockless transportation in there?

- There are 33 SOPs for the different types of ROW permits. Do we need to include all of them as evidence with some sort of index/road map? Or should we only include a couple SOPs as an example?

16.3 -

**Comment by katelunceford** [comment]
[Practice 35.5 Parking Fees](https://cityofaustin.sharepoint.com/:w:/r/sites/ATD_APWA_Accreditation/Shared%20Documents/ATD_Chapter%2035%20-%20Parking/ATD%2035.5%20Parking%20Fees.docx?d=w25f8f756d35948d8878535e382a64b5c&csf=1&web=1&e=OpsWul)
- [ ] 35.05.1 Resolution NO 20080110-049 - **needs link**
- [ ] 35.05.2 Austin City Code Chapter 12-3 - [12-3-6](https://library.municode.com/tx/austin/codes/code_of_ordinances?nodeId=TIT12TRRE_CH12-3MEPASTPA_S12-3-6FEUSPAPASPPAPAZO) The fee for use of paid parking space and paid parking zones is set by separate ordinance. Source: Ord. 20090611-032 - **Where is this ordinance? Or is it now the ASMP?**
- [ ] 35.05.4 ASMP - **need PDF file of only info related to parking fees** (nothing is saved yet; 358 pages in ASMP)
- [ ] 35.05.5 ACR - **need link + highlight or only include info related to parking fees** (66 pages in ACR that is saved)
- [ ] 35.05.6 ATD Operating Budget FY20-21 - **need link + PDF file + blurbs in Practice sheet**

**Comment by katelunceford** [comment]
### Chapter 34
- 34.01 - @katelunceford cleaned up wording, file names, & formatting 
> Need PDF file saved of TCM (only what's related to a traffic control policy and procedure manual)
> Need PDF file saved of TMUTCD (only what's related) 
- 34.02 - @katelunceford cleaned up wording, file names, & formatting & combined work order examples into one file
> Need PDF file saved of TCM (only what's related to installing traffic control devices)
> Need PDF file saved of TMUTCD (only what's related)
> Need to add another piece of evidence per Anna M. - ATD typical maintenance schedule (like for xwalks, etc.)

**Comment by katelunceford** [comment]
All Practices in Chapter 16 are ready to be handed off to PWD - closing this issue.
