### ISSUE TITLE
Signs & Markings is ready to order 30 more iPad mini tablets

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#11139]
> What application are you using?

Other / Not sure

> Describe the problem.

Signs & Markings is ready to order 30 more iPad mini tablets. Since mid October, we've been testing 10 tablets with both signs and markings staff. The new tablets have solved the previous issues that Signs & Markings had when using the Tab A tablets.

> How soon do you need this?

Unsure

> Requested By
Christina T.

Request ID: DTS23-106080

**Comment by amenity** [comment]
@dianamartin @scottreedy - y'all got this?

**Comment by dianamartin** [comment]
@amenity I'll make sure Scot knows about this. He's out of the office today.

**Comment by dianamartin** [comment]
Scott emailed me and asked me who to contact at SMD since Christina was moving to DTS, I said Lauren/Susanne/Cathy potentially. He asked if they had completed thorough testing and I said they had. He was going to work on getting a quote for this.

**Comment by ChristinaTremel** [comment]
## To-Do
- [ ] Cathy will provide Chrispin with a list of people that need iPad profiles
- [ ] Schedule time to set up iPads with Otterboxes and screen protectors
- [ ] Schedule time to issue out iPads to technicians

**Comment by ChristinaTremel** [comment]
Tablets were received by Signs & Markings and issued out to Technicians.
