### ISSUE TITLE
Please update the Performance Measures module in the Data Tracker application

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#11183]
> What application are you using?

Data Tracker

> Describe the problem.

Please update the Performance Measures module in the Data Tracker application to show information for FY23. Everything will be the same as FY22 except for these few: Please remove performance measures with ID 8060, 8584, & 9453. Please add performance measures with ID 9526 & 9527. I've included screenshots of the measures to add with their information. 

> How soon do you need this?

Soon — Within a week 

> Is there anything else we should know?

I need this information to be updated within a week to make sure there is adequate time to enter information as Q1 of FY23 just closed. 

> Requested By
Melissa B.

[Attachment](https://api.knack.com/v1/applications/595d00ebd315cc4cb98daff4/download/asset/63bf0ae14cd4e400119791a1/pmstoaddtofy23.jpg) (44.75kb)

Request ID: DTS23-106130

**Comment by dianamartin** [comment]
Please REMOVE performance measures with ID:
- [ ] 8060
- [ ] 8584
- [ ] 9453

Please ADD performance measures with ID:
- [ ] 9526 
- [ ] 9527

**Comment by dianamartin** [comment]
# 1/26
- [x] Removed measures (seen above) 
  - 8060
  - 8584
  - 9453
- [x] Added measures (seen above)
  - 9526
  - 9527
 - [x] Exported `performance_measures_fiscal` object table
 - [x] Renamed it to `import_performance_measures_fiscal_fy2023`
- [x] Removed measures to table
  - 8060
  - 8584
  - 9453
- [x] Added measures (seen above)
  - 9526
  - 9527
- [x] Imported csv - `52 records`
- [ ] spot checking

**Comment by dianamartin** [comment]
# Before
![image](https://user-images.githubusercontent.com/21112975/214967897-ad533def-d756-4c5a-94bc-1fedc1ea4baf.png)

# After
![image](https://user-images.githubusercontent.com/21112975/214967974-6e3d28e4-772b-4c7f-a6d9-815cd0fd2646.png)

Emailed Melissa B. & Christina
>I’ve updated the Performance Measures for FY2023. Please review and let me know if there are any discrepancies you observe, and I can correct them. 

>Thanks for your patience on this.

**Comment by dianamartin** [comment]
@ChristinaTremel will reach out to Melissa on this request

**Comment by ChristinaTremel** [comment]
Followed up with Melissa and she saw the FY23 performance measure updates and sent out the request for Divisions to complete the quarterly updates this week. Performance measure updates are complete for FY23.
