### ISSUE TITLE
Configure Signals API View to include new datasets for EDP + ODP

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#11181]
ODP: Signals (existing API View)
[Traffic Signals and Pedestrian Signals](https://data.austintexas.gov/Transportation-and-Mobility/Traffic-Signals-and-Pedestrian-Signals/p53x-x73x)
- [x] Add field “corridor_retiming_zone” to existing Signals API view

EDP: Create new API view
(”**corridor_retimings” object table)**

- [x]     corridor_retiming_zone
- [x]     Scheduled FY
- [x]     Scheduled Month
- [x]     Re-timing Status
- [x]     Assigned Engineer
- [x]     Created Date
- [x]      Created By

**Comment by ChristinaTremel** [comment]
Lance wants this to be a PowerBi dataset, but was able to do something more manually for now. Would like this in the future to improve his process. Need to ensure that the ETL script doesn't break and is updated with the new field.

**Comment by lanceballard** [comment]
Yes,  I'm hoping to complete a new Annual Signal Retiming dashboard for Brian Craig in the next couple of months. The last piece we need is the status for each of the corridor retiming efforts. We got the definitions for each corridor and zone, but now we are still lacking the status and schedule information discussed in the original comment.

**Comment by ChristinaTremel** [comment]
@KaroEngstrom have you already created the API view for the ”corridor_retimings” object table? If not, no problem but this is going to be a priority for Jim Dale and I'll be adding it to the sprint next week.

**Comment by KaroEngstrom** [comment]
## Th 3/2/23
- Added a new page to house this view [in the private API views](https://atd.knack.com/amd#signal-queries/)
![image](https://user-images.githubusercontent.com/100615928/222537084-58edff3a-0a58-491a-b135-3bd66ccf3daa.png)
- the new [Corridor Retimings page and table](https://atd.knack.com/amd#signal-queries/corridor-retimings/) are live
- per @dianamartin, I did not yet add the “corridor_retiming_zone” field to existing Signals API view so as not to break the ETL

**Comment by KaroEngstrom** [comment]
## F 3/3/23
- checked [Traffic Signals and Pedestrian Signals](https://data.austintexas.gov/Transportation-and-Mobility/Traffic-Signals-and-Pedestrian-Signals/p53x-x73x)and the new Corridor Retiming Zone column is populating correctly from ETL 
![image](https://user-images.githubusercontent.com/100615928/222780755-a76377e0-3684-46b3-a740-d5276b4f5334.png)

**Comment by ChristinaTremel** [comment]
@KaroEngstrom I coordinated with the Dev team today and they were asking if we could add the "Modified Date" field to the [Corridor Retimings table](https://atd.knack.com/amd#signal-queries/corridor-retimings/) on Knack and to the new [Corridor Retimings](https://datahub.austintexas.gov/Transportation-and-Mobility/Corridor-Retimings/bp5z-kciq) asset in City Data Hub. They let me know that this field is important for setting up that ETL, which I made a note of for future requests!

**Comment by KaroEngstrom** [comment]
@ChristinaTremel Thanks, good point for all future API views. I added the field to the Knack table and the asset. The field is empty currently for all `corridor_retiming` records.

**Comment by ChristinaTremel** [comment]
@chiaberry Karo has added the Modified Date. This issue is ready to be worked on!

**Comment by chiaberry** [comment]
@ChristinaTremel I have pushed the data to the open data portal, and now am working on automating the script. How often do they need it to be updated? Daily?

**Comment by chiaberry** [comment]
@ChristinaTremel one more question, the knack view has a column "retiming_status" that isn't in the ODP, does it need to be included?

**Comment by KaroEngstrom** [comment]
@chiaberry I bet it's not included in error, I can add.

**Comment by chiaberry** [comment]
@KaroEngstrom @ChristinaTremel the column is there, my mistake. My script for some reason isnt finding it. i am going to blame the `-`

**Comment by ChristinaTremel** [comment]
> @ChristinaTremel I have pushed the data to the open data portal, and now am working on automating the script. How often do they need it to be updated? Daily?

@chiaberry Daily updates would be perfect.

**Comment by ChristinaTremel** [comment]
@chiaberry yay! I'm seeing data in the OPD dataset for corridor retimings!

**Comment by lanceballard** [comment]
yes, daily is plenty for us. Thanks everyone!!
