### ISSUE TITLE
Add other fields to the School Zone Beacons & Zones table. Data to be added are:

Power Source

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#11196]
> What application are you using?

Data Tracker

> Describe the problem.

Add other fields to the School Zone Beacons & Zones table. Data to be added are:

Power Source

> Describe the outcome you'd like to see when this feature is implemented.

Add other fields to the School Zone Beacons & Zones table. Data to be added are:

Power Source

> Describe any workarounds you currently have in place or alternative solutions you've considered.

No work around

> Requested By
Brian C.

[Attachment](https://api.knack.com/v1/applications/595d00ebd315cc4cb98daff4/download/asset/63c0814780ac280012a90387/schoolzonedata.png) (30.32kb)

Request ID: DTS23-106165

**Comment by dianamartin** [comment]
Brian messaged me 1/12
>FYI. I just submitted a request to add another field to the School Zone and Beacon Table so it can be exported with the rest of the visible data in the table.
>- We are trying to include this table in an RFP request so if it could be done **next week** that would be much appreciated.

**Comment by dianamartin** [comment]
# 1/27


## Also Updated 
`School Zone Beacons>School Zone Details` page
### Work Order table
- [x] Changed "details" icon to ATD Work Order ID (link)
- [x] Added "Scheduled Work" (connection)
- [x] Added "Comment" (actuals - connection)
- [x] Enabled hiding of blank fields

**Comment by dianamartin** [comment]
# 1/27
Emailed Brian C. 
>Sorry for the delay on this, I realized you were hoping this was done last week when you messaged me on 1/12. I updated the tables referring to school zone beacons and added the field “Power Source” in two tables.  (inserted screen shot of above information)
![image](https://user-images.githubusercontent.com/21112975/215219140-2681fa1c-9203-4e23-b81c-90a301f990c8.png)

**Comment by dianamartin** [comment]
2/8/23 - Closing this issue, as user has been notified by not replied.
