### ISSUE TITLE
Release VZ v1.30.0 (Iguana Cir)

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#11205]
**To-do's for upcoming release**

- [x] Schedule release party - @patrickm02L 
- [ ] Advise users of downtime - @patrickm02L 
- [x] Create a [release PR](https://github.com/cityofaustin/atd-vz-data/pull/1165) - @mddilley 
- [x] Propose + vote on release names - @patrickm02L 
- [x] Refine [release notes](https://github.com/cityofaustin/atd-vz-data/releases/tag/v1.30.0) @patrickm02L 
- [x] Bump VZ **staging** version to `v1.31.0` and VZ production to `v1.30.0`- @mddilley 
- [ ] Send out release notes - @patrickm02L

**Comment by frankhereford** [comment]
👍 Thanks for the checklist. When do you want to do this release?

**Comment by patrickm02L** [comment]
Thursday, 1/26/23. 1:45-2:30pm.

**Comment by frankhereford** [comment]
@patrickm02L I had assignments on this list, I think. Is that correct? Do you need anything from me for today?

**Comment by patrickm02L** [comment]
@frankhereford thanks for checking. We didn't know if you would be back today, so we reassigned some tasks. We do not need anything from you today other than your presence at the Launch Party!

**Comment by patrickm02L** [comment]
We didn't have any downtime, and we'll share the updates to the VZ suite at the next Sprint Review 2/2/23.
