### ISSUE TITLE
Import batch file for Signal Priority - edited and modified date

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#11228]
> What application are you using?

Data Tracker

> Describe the problem.

Add batch signal priority editing and modified date in signal priority details

https://atd.knack.com/amd#signal-priority/

> Describe the outcome you'd like to see when this feature is implemented.

Add batch signal priority editing and modified date in signal priority details

> Describe any workarounds you currently have in place or alternative solutions you've considered.

N/A

> Requested By
Allyson R.

Request ID: DTS23-106200

**Comment by dianamartin** [comment]
Need AMD to provide spreadsheet to batch update

**Comment by dianamartin** [comment]
# 2/23
- Allyson emailed the [TSP_Pilot_Signal_Priority_List spreadsheet ](https://github.com/cityofaustin/atd-data-tech/files/10816147/TSP_Pilot_Signal_Priority_List.xlsx) over
>Additionally I believe we’d like to mark EVP configuration as status ‘Legacy’ for right now. It will be launched separately from the pilot so I don’t think we want it to get entangled with the TSP stuff. 
- for questions ask Allyson or Joshil

**Comment by dianamartin** [comment]
@ChristinaTremel 

# 4/4
Allyson emailed, (per Joshil's request) 
>Hi folks,
Could we get this info loaded into Data Tracker? I believe we loaded it into this link before: [https://atd.knack.com/amd#signal-priority/](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fatd.knack.com%2Famd%23signal-priority%2F&data=05%7C01%7CDiana.Martin%40austintexas.gov%7C51030dc244564f0205be08db34fe25da%7C5c5e19f6a6ab4b45b1d0be4608a9a67f%7C0%7C0%7C638162038377498353%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=x7ftMq%2BS1N%2FZqaidDTdq0YNpjIh880s9z84QnbP3sgw%3D&reserved=0)

File: [TSP_Phase_1_V2_DT.csv](https://github.com/cityofaustin/atd-data-tech/files/11152850/TSP_Phase_1_V2_DT.csv)

**Comment by dianamartin** [comment]
Looking at these spreadsheets 
- 2/23: `12 records` to be updated
- 4/4: `35 records` to be updated

**Comment by dianamartin** [comment]
# 4/4
- Reviewed the tables just before importing and realized there were some issues, had to email stakeholders again

To Allyson, Joshil CC. Christina, Susanne
>Hi Allyson, 
I was working on updating this issue for you guys but ran into some obstacles. The spreadsheet provided “20230223_TSP_Pilot_Signal_Priority_List_12” shared with me on 2/23 has some issues. The “Priority Direction” you all are using aren’t standard to what’s in the system. 

This is what options are available. 
Signal Priority Form
![image](https://user-images.githubusercontent.com/21112975/229936493-c9a5b021-c10a-43f5-8b7e-8b365ba1d584.png)

>20230223_TSP_Pilot_Signal_Priority_List_12
- In this spreadsheet you have the Priority Direction as NBL and EBR.
  - Are you requesting to add new Priority Direction options?
- It should read NORTHBOUND, EASTBOUND 
![image](https://user-images.githubusercontent.com/21112975/229936564-9bcfa602-e0a9-4ebb-896b-44e1ef5a7c19.png)

>20230404_TSP_Phase_1_V2_DT_35
- In this spreadsheet, you have the same issue on the “Priority Movement”
- Also, on the “Priority_Phases”, you have commas. Not sure if the system will import correctly with them in the table. 
![image](https://user-images.githubusercontent.com/21112975/229936609-9e183bfb-1f03-48e9-907b-4b4eecd117b4.png)

>I’ve attached the export of the table; the table headings need to match exactly and be saved in a .CSV format for us to import in the system. Please let me know if you can assist with making the changes, otherwise I’ll have to get someone to help me because I have limited bandwidth the next couple of weeks due to conducting UKG training.

**Comment by dianamartin** [comment]
# 4/5
Allyson replied
>Hi Diana,
 I am not sure on how to clean and process the data. [@Joshil] , I think this might need to be something you take a look at. He’s out of office until next week so might just sit tight until then. Sorry and thank you!

I replied
>The main thing is getting clarity on if you all wish to add more choices to the priority direction field. 

she replied
>The directions listed (IE NBL) doesn’t correlate with the phases in the column adjacent. It looks like those phases are for the most part the NB/EB/SB/WB approaches. But that’s not consistent with some of the rows (IE I see a few phase 3, phase 5s floating around). If we had to pick one I don’t know if its needed to expand that definition, but up to Joshil.

# 4/10
Thanks for taking a look at this. I would say it’s worth adding the additional movements (e.g. northbound left and northbound right) as some buses will receive TSP to make left turns specifically or go straight. This way if anyone wanted to quickly check to see if there is a northbound left TSP, they can check that via Data Tracker rather than go into the D4 program or KITS to check. Let me know if you have further questions. No real rush on this, I just want to keep on top of record-keeping for others. Thanks!

**Comment by susannegov** [comment]
Sent email to Joshil requesting to
1. Fill out the Priority Movement to the listed options in AMD Data Tracker
2. Clarify whether the Priority Movement previously filled out should be in the Priority Direction column or to to leave it as-is

> I’m currently cleaning up the spreadsheet to allow the import to happen, but there is an issue with the Priority_Movement column. I’ve attached the spreadsheet with the column highlighted in yellow that needs to be filled out with the options listed below. 
> 
> The options for Priority Movement in the AMD Data Tracker are:
> •	LEFT TURN
> •	RIGHT TURN
> •	THRU ONLY
> •	THRU/LEFT TURN
> •	THRU/RIGHT TURN
> •	UNKNOWN
> The Priority Direction in AMD Data Tracker has been updated to include NORTHBOUND RIGHT, NORTHBOUND LEFT, EASTBOUND RIGHT, EASTBOUND LEFT, SOUTHBOUND RIGHT, SOUTHBOUND LEFT, WESTBOUND RIGHT, WESTBOUND LEFT.
> 
> My next question is that whether the Priority_Movement column that was previously filled out should be the Priority Direction column OR should the Priority_Direction column stay the same?

**Comment by susannegov** [comment]
## 4/13
Joshil response
> “SIGNAL_PRIORITY_MOVEMENT” is not required as “Priority Direction” covers it (with the changes). The things we need to have recorded is direction and movement which is covered by Priority Direction. See below. Thanks!
> ![image](https://user-images.githubusercontent.com/31259724/232159043-f838a43f-a99a-475e-891b-a28b0fe10b3f.png)

Diana talked with me and looking at email response looks like two options(?):

1. Only do Priority Direction with Priority Movement included in Priority Direction column
2. Do Priority Direction column and Priority Movement column

I've done the edits in `20230404_TSP_Phase_1_V2_DT_35_CLEAN.csv` where there were directions in priority direction. However, I'm still unsure on non-directional values should be THRU or UNKNOWN or left blank for option 2.

Meeting on 4/17 for details.

**Comment by dianamartin** [comment]
# 4/17
Synced with Joshil (Susanne, Diana and Christina)
- he said that we can archive all `TSP` types
- [x] We created an "archived folder" on the G drive 
- [x] Exported `147 records` and filed them in the archive folder

## Next Steps
- [ ] Update the `SIGNAL_PRIORITY_DIRECTION` and include "THRU" as an option for all directions
  - EASTBOUND THRU
  - NORTHBOUND THRU
  - WESTBOUND THRU
  - SOUTHBOUND THRU
- [ ] Clean up spreadsheets, 12 and 35
- [ ] Import spreadsheets
- [ ] Include "MODIFIED DATE" as today
- [ ] Spot check records
- [ ] Query for "MODIFIED DATE" is blank, however many records

**Comment by susannegov** [comment]
# 4/28
- Import 12 records from `20230223_TSP_Pilot_Signal_Priority_List_12_CLEAN`

Signal ID | name | Signal Priority | Signal Phase
-- | -- | -- | -- | 
920 |  CAMERON RD / RUTHERFORD LN | EASTBOUND THRU, SOUTHBOUND THRU | 6, 7 |
48 |  38TH ST / GUADALUPE ST | NORTHBOUND THRU, EASTBOUND THRU, SOUTHBOUND THRU | 2, 4, 6 |
2 |  GUADALUPE ST / LAMAR BLVD | NORTHBOUND THRU, SOUTHBOUND THRU | 4, 8

**Comment by susannegov** [comment]
# 5/5
- 157 records currently
- For the 9 records that were UPDATED
![image](https://user-images.githubusercontent.com/31259724/236553832-b17771cb-5c5e-43cd-b667-9a9eb4581aa0.png)
- 26 NEW records added
- 183 records total after import
- Remove TSP type signal priorities that do not exist were not updated
   - Export the records called `20230505_signal_priority_183_BACKUP_new_old` in `G:\ATD\ATD_GIS\02_ENT_APPLICATIONS\app_AMD_DATA_TRACKER\Signal_Priority\archived_TSP_147`

**Comment by susannegov** [comment]
# 5/11
- Sync with Joshil to delete 131 records of the 183 records.
   - Filtered to MODIFIED_BY is not Susanne G. and SIGNAL_PRIORITY_TYPE is TSP
   - SIGNAL_PRIORITY_STATUS did not need filtering
![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/96f4443e-ecc7-488d-a7db-e19e9b59e436)

   - Joshil confirmed in Teams that the records look good

# Next steps
- [ ] export the records for signal priority
- [ ] create a template for the next signal priority batch

After sending in the template can close out ticket. 👍

**Comment by susannegov** [comment]
# 5/15
I created a template file for next signal priority batch. It is located in `G:\ATD\ATD_GIS\02_ENT_APPLICATIONS\app_AMD_DATA_TRACKER\Signal_Priority` folder called `TEMPLATE_Signal_Priority` (Updated May 2023) excel file.

The purpose of the excel file is to notify the user requesting the batch import any errors, clarify the exact format before submitting the request, and ensure the batch import goes smoothly. Since batch import information may be retrieved from other data sources (excel files, other software, GIS), having it in the excel file would give the requester some freedom in clean up. 

@dianamartin Let me know if this template file looks good enough to sent to Joshil. 
[TEMPLATE_Signal_Priority.xlsx](https://github.com/cityofaustin/atd-data-tech/files/11481754/TEMPLATE_Signal_Priority.xlsx)

**Comment by dianamartin** [comment]
@susannegov the template is nice, a little complex. I think it'll need some explanation. If you are emailing this to Joshil, you should offer to walk him through it if he has questions. I would even ask Karo or Chrispin their thoughts too.

**Comment by susannegov** [comment]
Emailed Joshil and CC'd Allyson and Diana on 5/24:

> Hello Joshil,
> 
> Attached is the signal priority batch template for future requests. I have them separated into two different sheets: 
> -	template_new for creating new signal priority records.
> -	template_update sheet for updating existing signal priority records in data tracker.
> 
> I gave some descriptions on each column in the Read Me sheet with the list of current accepted values in the Example values sheet. The most important thing is making sure the SIGNAL_PRIORITY_DIRECTION (Priority Direction) and SIGNAL_PRIORITY_PHASES (Priority Phases) are properly formatted in future batch updates. 
> 
> Let me know if you have any questions and I can walk you through it,

**Comment by susannegov** [comment]
Follow-up to Joshil on Teams (5/31) asking if the template looks good, will close ticket. His response:

> The template looks good to me. Thanks!

Closing ticket.
