### ISSUE TITLE
Finalize ATD submissions for APWA accreditation - N/A Practices (6)

### ISSUE THREAD

**Issue by katelunceford** [cityofaustin/atd-data-tech#11247]
### Task for each Practice
- [ ] Update note column in tracker with status

### [N/A Practices across 3 Chapters (6 Practices)](https://cityofaustin.sharepoint.com/sites/ATD_APWA_Accreditation/Lists/ATD%20APWA%20Progress%20Tracker/AllItems.aspx?FilterField1=Lead&FilterValue1=Castignoli%2C%20Rachel&FilterType1=User&viewid=db3efeaa%2D5db2%2D4df4%2D99cb%2Df1da454529cb)
- [ ] 16.08 Pavement Cut Restoration
- [ ] 34.07 Vegetation Control
- [ ] 34.22 Streetlights
- [ ] 34.23 Roadside Memorials
- [ ] 35.03 Parking Facility Maintenance
- [ ] 35.04 Parking Facility Operations

**Comment by amenity** [comment]
These were ultimately assigned to other departments. @katelunceford will check with Public Works to ascertain they don't need anything from us here.

**Comment by amenity** [comment]
@maccallump  - Kate said you've taken this off her plate. Thanks! Close this when complete, plz.
