### ISSUE TITLE
Finalize APWA practice submissions for Chapter 35 Parking (8)

### ISSUE THREAD

**Issue by katelunceford** [cityofaustin/atd-data-tech#11245]
### Tasks for each Practice
- [ ] Do a final review of the Practice sheet and corresponding EVIDENCE folder using the checklist below 
- [ ] Final gaps / questions should be communicated to the Lead
- [ ] Support Leads to ensure everything is finalized by **Jan 30th** to submit to PWD (but PWD said we can submit chapter by chapter if we don't have everything quite done by then)

### Final checklist for each Practice
1. Does the Agency Compliance statement match the Practice requirement (blue statement)? Is it specific, succinct, and easy to follow? (acronyms should be defined; vague, general statements are not good) 
2. Are naming and formatting standards used? (evidence number, file names, wording, etc.) 
3. Is each item of evidence listed in the Documentation/Directives table linked if possible?  
4. Is there a PDF file saved for each item of evidence listed in the Documentation/Directives table? 
5. Is each PDF file specific, highlighting or only including the info related to the specific Practice requirement? (entire manuals with lots of pages is not good - it should only include what's relevant; highlight exact sentences and/or headings when possible)
6. Are there any remaining comments / unanswered questions from the executive review guide? 

### [Chapter 35 Parking (8)](https://cityofaustin.sharepoint.com/sites/ATD_APWA_Accreditation/Lists/ATD%20APWA%20Progress%20Tracker/AllItems.aspx?FilterField1=field%5F4&FilterValue1=35%20%2D%20Parking&FilterType1=Choice&viewid=db3efeaa%2D5db2%2D4df4%2D99cb%2Df1da454529cb) 
- [ ] [35.01](https://cityofaustin.sharepoint.com/:w:/r/sites/ATD_APWA_Accreditation/_layouts/15/Doc.aspx?sourcedoc=%7B455E8F1F-8D74-4C23-9D6A-E273716BAA2D%7D&file=ATD%2035.1%20Parking%20Facility%20Planning.docx&action=default&mobileredirect=true) Parking Facility Planning
- [ ] [35.02](https://cityofaustin.sharepoint.com/:w:/r/sites/ATD_APWA_Accreditation/_layouts/15/Doc.aspx?sourcedoc=%7B5B03AA44-CB33-4F59-AA12-E7D793AA3DD5%7D&file=ATD%2035.2%20Parking%20Facility%20Design.docx&action=default&mobileredirect=true) Parking Facility Design
- [ ] [35.05](https://cityofaustin.sharepoint.com/:w:/r/sites/ATD_APWA_Accreditation/_layouts/15/Doc.aspx?sourcedoc=%7B25F8F756-D359-48D8-8785-35E382A64B5C%7D&file=ATD%2035.5%20Parking%20Fees.docx&action=default&mobileredirect=true) Parking Fees
- [ ] [35.06](https://cityofaustin.sharepoint.com/:w:/r/sites/ATD_APWA_Accreditation/_layouts/15/Doc.aspx?sourcedoc=%7B5A76312F-8A35-4C05-AC93-6DA67CE4B5CF%7D&file=ATD%2035.6%20On-Street%20Parking%20Meters.docx&action=default&mobileredirect=true) On-Street Parking Meters
- [ ] [35.07](https://cityofaustin.sharepoint.com/:w:/r/sites/ATD_APWA_Accreditation/_layouts/15/Doc.aspx?sourcedoc=%7B74575FA3-6B0F-4D32-B084-600414CCB22A%7D&file=ATD%2035.7%20Parking%20Regulation.docx&action=default&mobileredirect=true) Parking Regulation 
- [ ] [35.08](https://cityofaustin.sharepoint.com/:w:/r/sites/ATD_APWA_Accreditation/_layouts/15/Doc.aspx?sourcedoc=%7B3F58D61B-7205-440D-B60F-7362CD0552C7%7D&file=ATD%2035.8%20Angle%20Parking.docx&action=default&mobileredirect=true) Angle Parking
- [ ] [35.09](https://cityofaustin.sharepoint.com/:w:/r/sites/ATD_APWA_Accreditation/_layouts/15/Doc.aspx?sourcedoc=%7BA46E4332-7970-480D-9B1C-3D162A29996C%7D&file=ATD%2035.9%20Access%20to%20Parking%20on%20Streets.docx&action=default&mobileredirect=true) Access to Parking on Streets
- [ ] [35.10](https://cityofaustin.sharepoint.com/:w:/r/sites/ATD_APWA_Accreditation/_layouts/15/Doc.aspx?sourcedoc=%7B1191872F-6566-4567-8EE9-06569A4C6542%7D&file=ATD%2035.10%20Residential%20Handicapped%20Parking%20Zones.docx&action=default&mobileredirect=true) Residential Handicapped Parking Zones

**Comment by katelunceford** [comment]
Meeting notes w/ Peggy 1/10/22 9:30 AM: 
- 35.01 - @katelunceford changed evidence labels from Peggy to Curtis 
- 35.02 - @katelunceford changed evidence labels from Peggy to Curtis 
- 35.05 - @katelunceford added Joseph's title, reformatted and honed in content to fit the Practice, added links, saved evidence files as PDFs, renamed files, and added evidence labels
> Now Kate needs help from @maccallum to fill in remaining blanks (see separate comment below)
- 35.06 - @katelunceford added David's title, reformatted content to fit the Practice, added links, saved evidence files as PDFs, renamed files, and added evidence labels 
> Need link for evidence # 4 + highlight or only include info related to meters (66 pages in ACR)
- 35.07 - looks good
- 35.08 - @katelunceford reformatted and honed in content to fit the Practice, resaved TCM evidence with highlighting
> If possible, add link for Evidence # 3 (work order example)
- 35.09 - @katelunceford reformatted and honed in content to fit the Practice, resaved TCM evidence with highlighting
- 35.10 - @katelunceford renamed files & did light editing
> Need evidence of City web page where a resident would go to submit a CSR for a handicap sign/zone
> Nothing in evidence mentions ADA - do we need to include that? --> no

**Comment by katelunceford** [comment]
### [Practice 35.5 Parking Fees](https://cityofaustin.sharepoint.com/:w:/r/sites/ATD_APWA_Accreditation/Shared%20Documents/ATD_Chapter%2035%20-%20Parking/ATD%2035.5%20Parking%20Fees.docx?d=w25f8f756d35948d8878535e382a64b5c&csf=1&web=1&e=OpsWul)
- [x] 35.05.1 Resolution NO 20080110-049 - **needs link**
- [ ] 35.05.2 Austin City Code Chapter 12-3 - [12-3-6](https://library.municode.com/tx/austin/codes/code_of_ordinances?nodeId=TIT12TRRE_CH12-3MEPASTPA_S12-3-6FEUSPAPASPPAPAZO) _The fee for use of paid parking space and paid parking zones is set by separate ordinance. Source: Ord. 20090611-032_ - **Where is this ordinance? Or is it now the ASMP?**
- [ ] 35.05.4 ASMP - **needs PDF file of only info related to parking fees** (nothing is saved yet; 358 pages in ASMP)
- [ ] 35.05.5 ACR - **needs link + highlight or only include info related to parking fees** (66 pages in ACR that is saved)
- [ ] 35.05.6 ATD Operating Budget FY20-21 - **needs link + PDF file + blurbs in Practice sheet**

**Comment by katelunceford** [comment]
Meeting notes w/ Peggy 1/19 3 PM: 

- 35.05 - Kate's updates look good; Peggy found Res. NO 20080110-049 link & ATD fee schedule; Kate updated Practice sheet and evidence files; Peggy emailed Jason R. & Joseph A. at Parking Enterprise regarding:
> - 35.05.2 - where is Ord. 20090611-032?
> - 35.05.4 - need PDF file of ASMP with only pages related to parking fees (358 pages total)
> - 35.05.5 - need link for ACR + only pages related to parking fees (66 pages total) 

- 35.06 - Kate's updates look good; deleted first piece of evidence & moved up others (including evidence labels & file names) & highlighted sections related to meters in evidence # 2 (code 12-5); Peggy emailed Jason R. & Joseph A. at Parking Enterprise regarding:
> - 35.06.4 - need link for ACR + only pages related to meters (66 pages total)
- 35.08 - Kate's updates look good; edit down evidence # 1 to just 9.2.1 - actually after looking at this deeper I think we should keep this as-is. Angle parking is mentioned throughout and it's highlighted. It'd be more work to cut it down at this point.
- 35.09 - Kate's updates look good
- 35.10 - added 311 page to request new sign as 6th item of evidence
