### ISSUE TITLE
Finalize ATD submissions for APWA accreditation - Chapter 34 Traffic Operations (21 Practices)

### ISSUE THREAD

**Issue by katelunceford** [cityofaustin/atd-data-tech#11246]
### Tasks for each Practice
- [x] Do a final review of the Practice sheet and corresponding EVIDENCE folder using the checklist below 
- [x] Communicate final gaps / questions to the Lead
- [ ] Support Leads to ensure everything is finalized by Feb 28th to submit to PWD (but PWD said we can submit chapter by chapter if we don't have everything quite done by then)

### Final checklist for each Practice
1. Does the Agency Compliance statement match the Practice requirement (blue statement)? Is it specific, succinct, and easy to follow? (acronyms should be defined; vague, general statements are not good) 
2. Are naming and formatting standards used? (evidence number, file names, wording, etc.) 
3. Is each item of evidence listed in the Documentation/Directives table linked if possible?  
4. Is there a PDF file saved for each item of evidence listed in the Documentation/Directives table? 
5. Is each PDF file specific, highlighting or only including the info related to the specific Practice requirement? (entire manuals with lots of pages is not good - it should only include what's relevant; highlight exact sentences and/or headings when possible)
6. Are there any remaining comments / unanswered questions from the executive review guide? 

### [Chapter 34 Traffic Operations (21 Practices)](https://cityofaustin.sharepoint.com/sites/ATD_APWA_Accreditation/Lists/ATD%20APWA%20Progress%20Tracker/AllItems.aspx?FilterField1=field%5F4&FilterValue1=34%20%2D%20Traffic%20Operations&FilterType1=Choice&viewid=db3efeaa%2D5db2%2D4df4%2D99cb%2Df1da454529cb)
- [x] [34.01](https://cityofaustin.sharepoint.com/:w:/r/sites/ATD_APWA_Accreditation/_layouts/15/Doc.aspx?sourcedoc=%7B7EBFC80E-5FFF-4DFF-B203-DC64AF7C7600%7D&file=ATD%2034.1%20Traffic%20Policy%20and%20Procedure%20Manual.docx&action=default&mobileredirect=true) Traffic Policy and Procedure Manual
- [x] [34.02](https://cityofaustin.sharepoint.com/:w:/r/sites/ATD_APWA_Accreditation/_layouts/15/Doc.aspx?sourcedoc=%7B01C7BF6B-2C74-4162-BBA0-C33CCD06B2C9%7D&file=ATD%2034.2%20Traffic%20Control%20Devices.docx&action=default&mobileredirect=true) Traffic Control Devices
- [ ] [34.03](https://cityofaustin.sharepoint.com/:w:/r/sites/ATD_APWA_Accreditation/_layouts/15/Doc.aspx?sourcedoc=%7B56E6D8DF-8D58-4C7D-B8F7-199B12A76ECF%7D&file=ATD%2034.3%20Requesting%20Installation%20of%20Traffic%20Control%20Devices.docx&action=default&mobileredirect=true) Requesting Installation of Traffic Control Devices
- [x] [34.04](https://cityofaustin.sharepoint.com/:w:/r/sites/ATD_APWA_Accreditation/_layouts/15/Doc.aspx?sourcedoc=%7BBB201803-1CAB-4223-92C3-46AC3BAB722C%7D&file=ATD%2034.4%20Traffic%20Signs%20Maintenance.docx&action=default&mobileredirect=true) Traffic Signs Maintenance
- [x] [34.05](https://cityofaustin.sharepoint.com/:w:/r/sites/ATD_APWA_Accreditation/_layouts/15/Doc.aspx?sourcedoc=%7B2FBA0E59-7AE3-45AE-9CC3-76A7933FBD54%7D&file=ATD%2034.5%20Statutory%20Speed%20Limits%20on%20Roadways.docx&action=default&mobileredirect=true) Statutory Speed Limits on Roadways
- [x] [34.06](https://cityofaustin.sharepoint.com/:w:/r/sites/ATD_APWA_Accreditation/_layouts/15/Doc.aspx?sourcedoc=%7BF93ED992-5C22-43CF-9847-455213B8F2DF%7D&file=ATD%2034.6%20Street%20Name%20Signs.docx&action=default&mobileredirect=true) Street Name Signs
- [x] [34.08](https://cityofaustin.sharepoint.com/:w:/r/sites/ATD_APWA_Accreditation/_layouts/15/Doc.aspx?sourcedoc=%7B361D30E0-4A58-4A23-82E6-99EEAC5114C6%7D&file=ATD%2034.8%20School%20Pedestrian%20Crossings.docx&action=default&mobileredirect=true) School Pedestrian Crossings
- [ ] [34.09](https://cityofaustin.sharepoint.com/:w:/r/sites/ATD_APWA_Accreditation/_layouts/15/Doc.aspx?sourcedoc=%7B97A3FCD1-34F1-4077-8751-7B4123A1D423%7D&file=ATD%2034.9%20School%20Zone%20Speed%20Limit%20Signs.docx&action=default&mobileredirect=true) School Zone Speed Limit Signs
- [x] [34.10](https://cityofaustin.sharepoint.com/:w:/r/sites/ATD_APWA_Accreditation/_layouts/15/Doc.aspx?sourcedoc=%7BE9A3926C-E502-45AD-B0BC-DF2314503D55%7D&file=ATD%2034.10%20Special%20Signs.docx&action=default&mobileredirect=true) Special Signs
- [x] [34.11](https://cityofaustin.sharepoint.com/:w:/r/sites/ATD_APWA_Accreditation/_layouts/15/Doc.aspx?sourcedoc=%7BA857E6CB-FAF1-4B39-8FF1-A6D040E9666E%7D&file=ATD%2034.11%20Alley%20Stop%20Signs.docx&action=default&mobileredirect=true) Alley Stop Signs
- [ ] [34.12](https://cityofaustin.sharepoint.com/:w:/r/sites/ATD_APWA_Accreditation/_layouts/15/Doc.aspx?sourcedoc=%7B4C970449-88F0-4FFD-9A16-3AC76C9995CE%7D&file=ATD%2034.12%20Pavement%20Markings%20Maintenance.docx&action=default&mobileredirect=true) Pavement Markings Maintenance 
- [ ] [34.13](https://cityofaustin.sharepoint.com/:w:/r/sites/ATD_APWA_Accreditation/_layouts/15/Doc.aspx?sourcedoc=%7B728D943F-8FEF-4219-B6FD-249BDE35D17A%7D&file=ATD%2034.13%20Installation%20of%20New%20Signals.docx&action=default&mobileredirect=true) Installation of New Signals
- [ ] [34.14](https://cityofaustin.sharepoint.com/:w:/r/sites/ATD_APWA_Accreditation/_layouts/15/Doc.aspx?sourcedoc=%7BCCCBD04B-6456-42FD-AC18-062FDA4AF31B%7D&file=ATD%2034.14%20Temporary%20Stop%20Signs%20for%20Signal%20Outage.docx&action=default&mobileredirect=true) Temporary Stop Signs for Signal Outage
- [ ] [34.15](https://cityofaustin.sharepoint.com/:w:/r/sites/ATD_APWA_Accreditation/_layouts/15/Doc.aspx?sourcedoc=%7B8240A3C3-78EE-4BFB-B362-C19947B13EE3%7D&file=ATD%2034.15%20Traffic%20Signal%20Timing.docx&action=default&mobileredirect=true) Traffic Signal Timing
- [ ] [34.16](https://cityofaustin.sharepoint.com/:w:/r/sites/ATD_APWA_Accreditation/_layouts/15/Doc.aspx?sourcedoc=%7BC6B9C849-AAEF-402F-9B06-10E52AE22650%7D&file=ATD%2034.16%20Truck%20Routes.docx&action=default&mobileredirect=true) Truck Routes
- [ ] [34.17](https://cityofaustin.sharepoint.com/:w:/r/sites/ATD_APWA_Accreditation/_layouts/15/Doc.aspx?sourcedoc=%7B13BC6D38-578C-4D09-9B73-19339CABB92C%7D&file=ATD%2034.17%20Bike%20Paths.docx&action=default&mobileredirect=true) Bike Paths
- [ ] [34.18](https://cityofaustin.sharepoint.com/:w:/r/sites/ATD_APWA_Accreditation/_layouts/15/Doc.aspx?sourcedoc=%7B9EFBA118-8081-4E02-9BA2-D41A28DAC2B6%7D&file=ATD%2034.18%20Bus%20Stops.docx&action=default&mobileredirect=true) Bus Stops
- [ ] [34.19](https://cityofaustin.sharepoint.com/:w:/r/sites/ATD_APWA_Accreditation/_layouts/15/Doc.aspx?sourcedoc=%7B4A52156B-FAB1-45F3-8075-27EC2F93F527%7D&file=ATD%2034.19%20Temporary%20Street%20Closings.docx&action=default&mobileredirect=true) Temporary Street Closings
- [ ] [34.20](https://cityofaustin.sharepoint.com/:w:/r/sites/ATD_APWA_Accreditation/_layouts/15/Doc.aspx?sourcedoc=%7B94F07606-85D4-4900-A1ED-AF621856848C%7D&file=ATD%2034.20%20One-Way%20Streets.docx&action=default&mobileredirect=true) One-Way Streets
- [ ] [34.21](https://cityofaustin.sharepoint.com/:w:/r/sites/ATD_APWA_Accreditation/_layouts/15/Doc.aspx?sourcedoc=%7BED1F902F-037A-4C9F-9FEE-E4F5BDC66AA6%7D&file=ATD%2034.21%20Traffic%20Calming.docx&action=default&mobileredirect=true) Traffic Calming
- [ ] [34.24](https://cityofaustin.sharepoint.com/:w:/r/sites/ATD_APWA_Accreditation/_layouts/15/Doc.aspx?sourcedoc=%7B39540D70-EA9D-4589-81AA-7C8EF3A5038C%7D&file=ATD%2034.24%20Roundabouts.docx&action=default&mobileredirect=true) Roundabouts

**Comment by katelunceford** [comment]
- 34.01 - @katelunceford cleaned up wording, file names, & formatting 
> - Need PDF file saved of TCM (only what's related to a traffic control policy and procedure manual)
> - Need PDF file saved of TMUTCD (only what's related) 
- 34.02 - @katelunceford cleaned up wording, file names, & formatting & combined work order examples into one file
> - Need PDF file saved of TCM (only what's related to installing traffic control devices)
> - Need PDF file saved of TMUTCD (only what's related)
> - Is it ok that the "Role in Compliance" section is the exact same as 34.01 for those two pieces of evidence?
> - Need to add another piece of evidence per Anna M. - ATD typical maintenance schedule (like for xwalks, etc.)
- 34.03 @katelunceford cleaned up wording, file names, & formatting
> - Need links for all evidence (8)
- 34.04 @katelunceford did light editing / formatting
> - Entire TMUTCD Part 2 is included (344 pages) - should we highlight/only include only what's related to sign maintenance? 
> - Need to respond to Jim D.'s questions
- 34.05 @katelunceford cleaned up wording, file names, & formatting, added link, honed in evidence & highlighted, combined PDF files 
> - Need links for evidence # 2 & # 4
- 34.06 @katelunceford cleaned up wording, formatting, added links, & saved PDF files for evidence
> - Does this speak specifically to identification signs at intersections?
> - Need to save TMUTCD and highlight/only include what's relevant (344 pages)
