### ISSUE TITLE
[Spike] Inventory Funding Enhancements

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#11244]
Dedicated time to explore
- Can we allow inventory items to be manually JVed before being closed?
- Can we enable manual overrides of TK + FDU values for individual inventory item transactions on the same work order?

**Comment by ChristinaTremel** [comment]
Related to #9808.

**Comment by ChristinaTremel** [comment]
# 4/26 Inventory Funding Enhancements Spike Brainstorm
Met with Diana and discussed 2 questions Ronnie wanted us to explore:

- Can we allow inventory items to be manually JVed before being closed?
      - Current JV Process:
         - Work Order Status must be `CLOSED`
         - Monthly, a JV REPORT is run by Crystal (checked by Ronnie beforehand)
              - JV Status is `Ready` at this time (ready for finance to process)
              - Transaction Status is `Complete` (inventory planners have completed the inventory request)
              - Work Order Status is `Closed` (work order including inventory request has been closed)
         - 
- Can we enable manual overrides of TK + FDU values for individual inventory item transactions on the same work order?

**Comment by ChristinaTremel** [comment]
# 5/8 Meting Notes
Attendees: Christina, Diana, Ronnie, Ivonne, Dan, Erin, Brian, Crystal, Melissa, Cesar

### Finance:
- Would adjustments be considered? - Would the person determining if an item could be JVed be the same person that identifies if an item will be returned.
- Benefits would be that we have a better sense of how inventory is moving through AMD, so Dan would like this!
- One issue in the past, is that if a work order is not completed, it won't charge to a CIP project and it causes problem for Grant Delivery.

### AMD:
- We would not JV from inventory items in the "Needs to be Issued"
- AMD would JV anything that was checked out, but when Ronnie looks at the FDU review, he opens the FDU and checks the balance. Tries to avoid creating a negative FDU balance. 
   - Dan says that you shouldn't care if you drive an FDU negative and it should be the Project Managers responsibility

### Next Steps
- DTS will test the process of removing the work order is `CLOSED` rule and have Ronnie review the JV report to ensure there are no red flags. 
- AMD to discuss internally what a potential process could look like for charging individual inventory items to FDUs - DTS does think this will make the process more complicated

**Comment by ChristinaTremel** [comment]
# 5/10 Email from Ronnie
> Since the meeting Monday, I spoke with Billy about the possibility of listing a task order and an FDU for each inventory transaction rather than listing a single task order and FDU for the overall work order.  This would eliminate the need to create separate work orders when inventory items are used at a location or for a project, but the items are funded from different FDUs or go to different task orders. 

> We feel that having separate task order and FDU fields for each transaction rather than for the overall work order would be beneficial in some cases.  However, doing so would make the FDU review process more difficult and would introduce potential sources for incorrect data entry that could result in charges to incorrect FDUs.  We do not feel that the benefits of such a change would exceed the potential for problems.  Therefore, we would like to discontinue consideration of listing a task order and an FDU for each inventory transaction rather than for the overall work order. 

 >We do want to continue consideration for
> 1.  the ability to process a transaction on a JV even if the work order has not been closed, and
> 2. a revision to address cases where one (or more) “needs to be issued” items on a work order allow that work order to bypass the FDU Review queue and be included on a JV.

**Comment by dianamartin** [comment]
# 5/15
- [ ]  Test the process for removing the rule that a Work Order is Closed to show up on the JV REPORT
- [ ] Add JV Status field to all of the Work Orders Details pages
- [ ] Add JV Status field to Inventory table
- [ ] In AMD Sprint Review, talk about the Finance Service Requests, new streamlined process AMD is creating to put money into a single FDU, and find out if that solves this problem "Can we enable manual overrides of TK + FDU values for individual inventory item transactions on the same work order?

**Comment by ChristinaTremel** [comment]
@ChristinaTremel set up work session with Diana for late this week/early next

**Comment by ChristinaTremel** [comment]
Scheduled work session on 5/22 with Diana.

**Comment by ChristinaTremel** [comment]
Schedule time to revisit this with Ronnie - 30 minute meeting

Schedule another time to present to the rest of the group when changes have been made.

**Comment by dianamartin** [comment]
# 6/16
- Added Notes to AMD Miroboard

## JV Status Changes
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/fac5ca73-7ed2-4111-9bf0-00db62c5d299)

**Comment by dianamartin** [comment]
# 7/6 - Testing "On Hold" Scenario

## Requested Changes
- [ ] Add new field on object `work_order_signals` - `INVENTORY_ON_HOLD` - 1/0 - `number`
- [ ] Repurpose Inventory Status field - "Needs AIMS entry"  to "On Hold"
- [ ] Add menu filter on Inventory Requests page to "On Hold"
- [ ] Add a button to change "Inventory Status" to "On Hold"

### Scenario 1
- Add Items - TXN completed
- Add "ON HOLD"
- JV Status - NOT READY
- Lift "ON HOLD"
- JV Status - READY

### Scenario 2 - Partially Approved items
- Add Items - TXN Status Completed
- Add New Items - TXN Status Not Completed
- Add "ON HOLD"
- JV Status - NOT READY
- See if WO is On Hold
- Lift "ON HOLD"
- JV Status - READY

**Comment by dianamartin** [comment]
# 7/12
- `WRK23-185870`

## JV Status Changes
Modified proposed Rule # 7, by added a new rule:
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/7c9ab298-8b3a-4a21-80d2-cc93dfd4f1f6)

**Comment by dianamartin** [comment]
# Steps followed to enable JV Status "On Hold"

## Back End Updates (object tables)
- [ ] 

## Front End Updates
- [ ] Add JV Status field to all of the Work Orders Details pages
>thought we already added this to some of the AMD pages
- [ ] `Journal Voucher Status` to Inventory Items tables (both editable & non-editable)
- [ ] My Work Orders
- [ ] Work Order Technicians
- [ ] Work Order Non-Technicians
- [ ] Work Order Communications

![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/20909b1c-f64b-4232-943f-237e914b74a7)

- [ ] Add JV Status field to Inventory Requests, "Inventory Items" table 
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/20bb7a86-7ea2-4067-8359-a01bc7e44b68)

**Comment by dianamartin** [comment]
Had already created https://github.com/cityofaustin/atd-data-tech/issues/12601 - will close this one since new issue will address the changes.
