### ISSUE TITLE
[Traffic Register] Enhancements: Usability Updates Part 2

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#11335]
This issue will be a running log of usability feedback, changes, and tasks needed based on 2023 Q1 Usability Testing and Traffic Register Sprint Review meetings. Changes made in the PTE environment will need to also be made in Prod.

### Searching
- [x] Make sure records are searchable by multiple criteria when connecting: RN, ID, Nickname, Reg Type, Primary St
   - Moved to #11559 
- [x] Fix broken Reg Doc ID nav link from Search Directory > Regulation Details > Reg Doc ID
   - Moved to #11559 
- [x] Update 'Directory Home' button to 'Search Directory Home' and move to front of menu
- [x] Add Directory button subtext to Search pages
- [x] Ability to do a side by side comparison of 3 regs
   - Moved to #11563

### Drafting
- [x] Make sure Draft Submittal Rules are correct so that Review Cycles are created
- [x] Fix the Connected ID field
   - Moved to #11564 
- [x] Slightly update Comments & Attachment table subtext
- [x] Move the Reg Text field to the top of the Regulation Editor, 
- [x] Update display rules based on Reg Type
   - Moved to #8738 
- [x] Allow Draft Authors to Re-Assign & Re-Submit their Draft if mistakes were made or if there is a system malfunction when Submitting.
- [x] Whether a Reviewer or Draft Author updates the Assigned, make sure it is reflective on both the Reg Doc and Review Cycle
   - Moved to #11564 
- [x] Add/Update Email Notifications for Draft Submitted
   - Moved to #11564 
- [x] Duplicate Review Cycles being created when Draft is submitted
- [x] Make sure Draft Author can edit Draft when Revision is requested
   - Moved to #11564 
- [x] General Location is entered for new regs
- [x] Improve instructional text for editing copied regulations during drafting
   - Moved to #11564 
- [x] Drafting option information text also displayed within drafting process
   - Moved to #11564 
- [x] Give the option for authors to draft an install only or retire only document?
   - Moved to #11564 

### Reviewing
- [x] Bring Attention to the Currently Assigned To field to be updated or automatically update
- [x] Update the Needs Revision feature into a popup for Engineers to associate a revision comment to a record or multi choice field for Correction Needed
- [x] Slightly update Comments & Attachment table subtext
- [x] Ask users if Review Notes should have formatting
- [x] Move the Reg Text field to the top of the Regulation Editor, 
- [x] Update display rules based on Reg Type
   - Moved to #8738
- [x] Update rules in the event that a Reviewer is both the TE and CTE
   - Moved to #11565
- [x] Fix the Review Decision field in the Review Cycle Details
   - Moved to #11565
- [x] Add/Update Email Notifications for TE Review Complete, CTE Review Complete
   - Moved to #11565
- [x] Information missing on CTE Review Cycle
   - Moved to #11565
- [x] Require Begin Review before Complete Review (error message)
- [x] Cycle submitted date should be the Draft Submitted Date
- [x] Simplify assigning Review Cycles to only one person but allow all Reviewers to see all cycles (do automatically if possible)
- [x] Ability to do a side by side comparison of 3 regs
   - Moved to #11563
- [x] Greater visibility on corrections needed and corrections made on a reg (version control)
   - Moved to #11565

### Task Board
- [x] Make the Print Page directly accessible from Task Board
- [x] Direct link to Approved Reg Doc from Completed Tasks
- [x] Update the Views & Quick Views to be formatted better, hide any unnecessary fields based on Reg Type
   - Moved to #11566
- [x] Link the IDs to the View/Quick View
   - Moved to #11566
- [x] Fix the Retired, Retired From, & Replaced With Regulation Connection ID fields that are displayed. Visually show connected pairs if possible.
   - Moved to #11566
- [x] Draft Author has correct vision on Review Cycles & Drafts
   - Moved to #11566
- [x] Reviewer has correct vision on the Review Cycles & Drafts
   - Moved to #11566

### Other
- [x] Fix Dates on Print Page
   - Moved to #11567
- [x] Hide Attachment Link field on table on Details pages if blank
- [x] Create task for auto expiring regs, should they have to go through review again?
   - Moved to #11567
- [x] Update existing records with General Location values
   - Moved to #11567

**Comment by ChristinaTremel** [comment]
Chrispin will organize these issues so we can create functionality epics within the traffic register epic.

**Comment by ChristinaTremel** [comment]
Thank you @ChrispinP! I'll create an additional epic grouping for Task Board enhancements. I'll also update here once I've created the issues for the unchecked items above.

**Comment by ChristinaTremel** [comment]
Created new issues for tasks still needing to be completed:

- Made notes of any tasks moved to new issues 
- Checked off the task list above after being moved to new issues

**Comment by ChristinaTremel** [comment]
Closing this issue because all outstanding issues have new issues created to track progress.
