### ISSUE TITLE
Upgrade to Prefect 2.0

### ISSUE THREAD

**Issue by chiaberry** [cityofaustin/atd-data-tech#11353]
Epic to keep track of the dev team's learning about prefect 2.0 as well as upgrading our existing flows in prefect 1.0

Flows on prefect 1.0 [will be frozen starting May 1. ](https://www.prefect.io/guide/blog/freezing-legacy-prefect-cloud-1-accounts-on-starter-and-standard-plans/), our flows will be frozen July 15.

Existing Flows in Prefect 1.0. If you want to claim one, feel free to open an issue and add to this epic. 

- [x] AFD import ETL https://github.com/cityofaustin/atd-data-tech/issues/11730
- [x] EMS import ETL https://github.com/cityofaustin/atd-data-tech/issues/11730
- [x] CR3 Narrative OCR https://github.com/cityofaustin/atd-data-tech/issues/11731
- [ ] Refresh DB Permissions for Read Replica (VZ) (doing https://github.com/cityofaustin/atd-data-tech/issues/12532 instead)
- [x] Moped Test Instance commission [not active, but triggerable] - will not migrate but need to preserve this work!
- [x] Parking data txn history https://github.com/cityofaustin/atd-data-tech/issues/11831
- [x] Parking data reconciliation https://github.com/cityofaustin/atd-data-tech/issues/11831
- [x] Microstrategy to S3 - https://github.com/cityofaustin/atd-data-tech/issues/11631
- [x] Trail counter pub test - Charlie
- [x] Knack banner HR (chia’s) - https://github.com/cityofaustin/atd-data-tech/issues/11354
- [x] Knack Services - markings contractor - Charlie
- [x] Knack Services - signals to artbox - Charlie
- [x] Knack Services - https://github.com/cityofaustin/atd-data-tech/issues/11442
- [x] Finance Data publishing - https://github.com/cityofaustin/atd-data-tech/issues/11355
- [x] service bot issues #11418
  - [x] Service bot issues to open data portal
  - [x] Service bot update issues

---
Things to think about while upgrading and learning

- Slack integration (error logging)
- Naming conventions / tags?
- What is a work queue? 
- How can we organize our flows by different projects?
- Secrets! Key value? Config storage? Secrets out of plain text
- Store them in 1pass? Prefect knows nothing
- Flow.register vs flow.run, does that exist in 2.0?
- Profiles? 
- Any reason why the free tier would not work for us
- Storage questions – github storage vs docker storage vs ?

**Comment by frankhereford** [comment]
While we were on `atd-data03` today, I observed that we had 3 containers in a endless restart loop. They were the 3 "dockerized agent"s on the machine, and I edited each `docker-compose.yaml` file to disable automatic restarting. 

They are no longer running -- we've turned down our infrastructure related to prefect 1 entirely now. 🙏
