### ISSUE TITLE
Service Request Feedback from Finance Sprint Review - 1/31

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#11350]
Q: Revisit how you want to assign work? (individual jobs, batch assign)
- Batch assign to one person to work on

NEW: Dashboard for the Manager so that they can have a designated place where they can go to complete their reviews. 
- Proposed new status: `Waiting for Approval`
- [x] Added on the fly during sprint review

NEW: Manage financials tab
If individuals want to be able to see their own assignments

## Changes requested 
- [x] Remove “Amount” on parent record
- "SubProject Coordinator" not needed
- [x] Copy the order of current ECapri Subproject form to the Knack SR form - done on the fly at sprint review
- [x] Move the Parent Project to the top under the Subproject - done on the fly at sprint review

## Email Notification
- [x] In email notification, change the number to "Service Request ID" number
- [x] Change colors of the Task Status 
- Yellow - Not Started
- Green - In Progress
- Blue - Completed

- [x] Highlight Subproject fields that need to be filled in
- [x] Send notifications for review at the individual TK level 
  - When status is "Completed"

- [x] Use case, once BGEX and JV/EIT is done create ability to make a note
  - [x] Add new field "Document ID"

- [x] Change Task Action options - done on the fly at sprint review
- New
- Increase
- Decrease
- Close

Update Display Rules - New Service Request form
### Task Order Action fields
- [x] New 
  - [ ] show "FDU Name", "Type"
- [ ] Increase
  -  [x] hide "FDU Name", "Type"
  -  [x] show "Existing 
  -  [ ] show "Task Order No"
  - show "Amount"
- [ ] Decrease
  - [x] hide "FDU Name", "Type"
  - [x] show "Existing 
  - [x] show "Task Order No"
  - [x] show "Amount"
- [ ] Close
  - [x] hide "FDU Name", "Type"
  - [ ] show "Existing TK"

**Comment by dianamartin** [comment]
# 2/3
- [x] Remove “Amount” on parent record
- [ ]

**Comment by dianamartin** [comment]
Added "Task Order Action fields" to issue #11639, closing.
