### ISSUE TITLE
Update "Journal Voucher" info in AMD Data Tracker - Warehouse Inventory- February 2023

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#11381]
- [x] Spreadsheet emailed from Finance staff month of: February (JV date 2/28/23)
- [x] Number of records being updated: 222
- [x] Format spreadsheet [(Review instructions)](https://atd-dts.gitbook.io/atd-knack-operations/warehouse-inventory-updating-journal-vouchers-jv-information)
- [x] Spot check Transaction IDs, no JV information before import (23665; 23587)
- [x] Import records
- [x] Spot check Transaction IDs, has JV information after import (23665; 23587)
- [x] Email Finance staff that update task complete
- [x] Update change log
- [x] Create next month's issue for backlog
