### ISSUE TITLE
[Feature] Cable Usage Tracking - Cable Management Module

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#11436]
## Billy is wanting to create a page with very limited access for Cable Management
- Page only editable for Billy and the one other person assigned to tracking cable usage (currently Josh)
- Page has "Cable QC" field to track the transactions he has checked when comparing to spreadsheet
- Table has existing information already on transaction table with additional fields such as: 
     - Beginning
     - End
     - Footage
     - Difference

**Nice to have features that could duplicate the spreadsheet currently tracking cable**
- Vehicle the cable comes from
- Reel number tracking

**Describe the outcome you'd like to see when this feature is implemented.**
- Would eventually like Data Tracker to be the space where cable tracking can be fully managed and where Technicians are capturing accurate measurements of the cable they've used. 

**Describe any workarounds you currently have in place or alternative solutions you've considered.**
- Cable is held securely and to get cable, the technician has to ask Billy or one of Billy's appointees (only 1 at all times) to release the cable to them. Billy or Josh will go to the inventory person and ask for the reel - inventory person sets the cable outside the secure area and the inventory people track that cable in their own way. They will tell Billy the reel number.
- Each reel has a measurement embossed in the cable so we know exactly how much is there.
- Two thing happens when a tech uses the cable:
     - Whoever completes the work order marks the beginning and ending footage on the Data Tracker work order. Footage is included in the notes part of the module.
     - Tech contacts Billy's point of contact (currently Josh) via phone, email or text and text them the cable type, number, and footage.
     - To check the cable usage: Billy looks at Transactions of the cable in Data Tracker and if it's correct, he highlights the spreadsheet. Currently he can't check the transactions on Data Tracker to confirm he's already seen it. Billy would like having that on Data Tracker.

**Comment by dianamartin** [comment]
- [ ] Created page "Cable Management"
- [ ] Copied transactions table from Inventory Item details page
- [ ] Added "inventory_item" field to table
- [ ] Re-ordered fields (as seen below), moved Inventory Transactions to the end
- [ ] Added "Created By", "Cable Begin", "Cable End", "Cable Used"

![image](https://user-images.githubusercontent.com/21112975/217962191-2e74036a-497b-44a4-bba2-d35a012d8c01.png)

**Comment by ChristinaTremel** [comment]
@ChristinaTremel schedule meeting with Diana and Billy to show the updates in the test environment.

**Comment by dianamartin** [comment]
# 2/22
Created a prototype in PROD
- [ ] Created page "Cable Management"
- [ ] Copied transactions table from Inventory Item details page
- [ ] Added "inventory_item" field to table
- [ ] Re-ordered fields (as seen below), moved Inventory Transactions to the end, moved "Comment" to the front
- [ ] Added "Created By", "Cable Begin", "Cable End", "Cable Used", "Cable QAQC"

![image](https://user-images.githubusercontent.com/21112975/217962191-2e74036a-497b-44a4-bba2-d35a012d8c01.png)

Inventory Transactions per Inventory Item Details
![image](https://user-images.githubusercontent.com/21112975/217963036-1221d190-fe54-49d0-a32b-1f17cb7d3ffa.png)

**Comment by ChristinaTremel** [comment]
# Review Cable Usage Meeting 2/23:

- Show Cable Module
   -  Determine who needs access to this page and who can edit the QA/QC field
- Show inventory form for cables
   - Determine which inventory items need the "Beginning" and "End" cable fields

**Comment by dianamartin** [comment]
# Diana's Notes
- Shared with Cesar that he'd need to change `CABLE, FIBER OPTIC 96 FIBER, FLEXLINK SMF-28E` to `Cable, Fiber Optic, 96 Fiber` in the Finance and Purchasing app, under Inventory Items. 
- They'd love to have a Cable Management/Reel Management module set up by mid to late March

## New Cable fields updated
- Diana said beginning to mid next week to get this task done
- When Work Orders are updated, notify: Billy, Jorge, Cesar, cc. Christina

**Comment by dianamartin** [comment]
# 2/23 Created
- [x] Create new object - `cable_reels` 
- Field Headings
![image](https://user-images.githubusercontent.com/21112975/221058272-ac2b68cf-e581-42ce-92a7-89543be3fcec.png)
- [x] Created New Page
![image](https://user-images.githubusercontent.com/21112975/221058160-48b0ff5e-f0cc-4697-a71b-82e62b62585b.png)
- [x] Created New Cable Reel form
![image](https://user-images.githubusercontent.com/21112975/221058426-cfccf728-1231-47be-9189-64794a5174fa.png)

**Comment by ChristinaTremel** [comment]
@dianamartin working on these changes this sprint.

**Comment by dianamartin** [comment]
# 3/16 
Synced with Billy, showed him the newly added "Cable Management" area. He's excited, he's going to deep dive tomorrow (3/17). He'll provide us some feedback.

**Comment by ChristinaTremel** [comment]
Had a review of the Cable Management page with Diana, Billy, and Cesar on 3/23 and they are happy with the Cable Management Module.
