### ISSUE TITLE
[Enhancement] Cable Usage Tracking - add fields for improved tracking

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#11440]
## Billy is wanting to add fields to improve Cable Management

- [ ] Add a check box “Cable QA” on Inventory_transactions
- [ ] New field “Beginning” (required)
- [ ] New field “End” (required)
- [ ] New field “Footage” (required)
- [ ] New field “Difference” (auto-calculated)

**Related to a problem?**
- Meeting notes to discuss this enhancements was [9759](https://github.com/cityofaustin/atd-data-tech/issues/9759)

**Desired Outcome?**
- Billy would like to have a way to mark the transactions on Data Tracker to show that he's already looked at that transaction. A field to mark the line item as checked.
- Add field to transactions list "Cable QC"
- Billy would like that field to highlight if it has been checked
- Only editable by Billy or someone Billy assigns (specific user)
- Include a beginning, end, and calculated footage field

**Comment by dianamartin** [comment]
# In Test Environment

Add to `Inventory_transactions` object table
- [x] Add a check box “Cable QAQC”
- [x] New field “Beginning” (required)
- [x] New field “End” (required)
- [x] New field “Footage” (required)
- [ ] New field “Cable Used” (equation)

![image](https://user-images.githubusercontent.com/21112975/217949279-e827c897-8902-489d-8395-cc7409c87816.png)

**Comment by dianamartin** [comment]
## Add Inventory Item form
![image](https://user-images.githubusercontent.com/21112975/217957991-8c472276-122d-442c-a2f7-fc3ab966e8fa.png)

## When Inventory is "Cable" on form
![image](https://user-images.githubusercontent.com/21112975/217958099-da990105-3b52-4f64-bb0c-9c8ca1a48694.png)

## When Inventory is "Cable" is added, appears on table
![image](https://user-images.githubusercontent.com/21112975/217958926-596fdd05-4f51-43da-9225-3cda0e6dc248.png)

**Comment by dianamartin** [comment]
# Add Cable fields into Production

**Comment by dianamartin** [comment]
# 3/10
## Add Inventory Item form
**Add fields - Add form**
- [x] Add "Cable Begin" field
- [x] Add "Cable End" field

**Add display rules - Add form**
- [x] Ex. inventory_item `is` - Cable, 20-Conductor | FT
- For all cable inventory items
  - [x] CABLE, SINGLE, TWISTED SHIELDED PAIR IMSA-50-2 - `Cable, Single (One) Twisted Pair`
  - [x] CABLE TRAFFIC CONTROL 5/C 600V # 11402 - `Cable, 5-Conductor`
  - [x] CABLE TRAFFIC CONTROL 7/C 600 V # 11402 - `Cable, 7-Conductor`
  - [x] CABLE, TRAFFIC SIGNAL, DIRECT BURY AND OVERHEAD 20C STSR IMS - `Cable, 20-Conductor`
  - [x] `Composite Camera Cable Double Braid 75 Ohm Coax` 
  - [x] CABLE, FIBER OPTIC 48 FIBER, FLEXLINK SMF-28E - `Cable, Fiber Optic, 48 Fiber`
  - [x] CABLE, FIBER OPTIC 96 FIBER, FLEXLINK SMF-28E - `Cable, Fiber Optic, 96 Fiber`

## Edit Inventory Item form
**Add fields - Edit form**
- [x] Add "Cable Begin" field
- [x] Add "Cable End" field

**Add display rules - Edit form**
- [x] Ex. inventory_item `is` - Cable, 20-Conductor | FT
- For all cable inventory items
  - [x] CABLE, SINGLE, TWISTED SHIELDED PAIR IMSA-50-2 - `Cable, Single (One) Twisted Pair`
  - [x] CABLE TRAFFIC CONTROL 5/C 600V # 11402 - `Cable, 5-Conductor`
  - [x] CABLE TRAFFIC CONTROL 7/C 600 V # 11402 - `Cable, 7-Conductor`
  - [x] CABLE, TRAFFIC SIGNAL, DIRECT BURY AND OVERHEAD 20C STSR IMS - `Cable, 20-Conductor`
  - [x] `Composite Camera Cable Double Braid 75 Ohm Coax` 
  - [x] CABLE, FIBER OPTIC 48 FIBER, FLEXLINK SMF-28E - `Cable, Fiber Optic, 48 Fiber`
  - [x] CABLE, FIBER OPTIC 96 FIBER, FLEXLINK SMF-28E - `Cable, Fiber Optic, 96 Fiber`

## Add to Inventory Items table on Work Order Details page
- [x] Add "Cable Begin" field
- [x] Add "Cable End" field
- [x] Add "Cable Used" field
- [x] Add display rule, if Cable Used lower than 1, hide value (on table)
![image](https://user-images.githubusercontent.com/21112975/217961487-f33d3ac7-59d5-43c0-8a1c-2981e09b425b.png)

# Testing Display Rules
- I learned that the best display rule is using the "IS NOT"
![image](https://user-images.githubusercontent.com/21112975/224449086-6808cc6a-1212-47d3-9fe6-f59155d53756.png)
- This took me a while to figure out, the forms weren't making the field visible
- Once I got the form exactly the way I needed to, copied forms to the other pages

### Work Order - Technicians
- [x] Copied Add Form 
- [x] Copied Edit Form 

### Work Order - Non-Technicians
- [x] Copied Add Form 
- [x] Copied Edit Form 

### Work Order - Communications
- [x] Copied Add Form 
- [x] Copied Edit Form 

### Work Order - Contractor 
- [x] Copied Add Form 
- [x] Copied Edit Form

**Comment by dianamartin** [comment]
# 3/10
Added "Mange Cable" on the Home page menu
![image](https://user-images.githubusercontent.com/21112975/224450507-9568bafc-5862-4fb8-814a-662b7a0760af.png)

**Comment by dianamartin** [comment]
# 3/16

Synced with Billy, showed him the newly added "Cable Management" area. He's excited, he's going to deep dive tomorrow (3/17). He'll provide us some feedback.

**Comment by ChristinaTremel** [comment]
Had a review of the Cable Management page with Diana, Billy, and Cesar on 3/23 and they are happy with the Cable Management Module.
