### ISSUE TITLE
[Data Tracker] Send email notification when a knockdown trouble call comes in

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#11467]
> What application are you using?

Data Tracker

> Describe the problem.

I would like to know when Knockdowns are happening so I can check Data Tracker.

> Describe the outcome you'd like to see when this feature is implemented.

I would to have an email notification sent to me when a trouble call comes in as a knockdown.

> Describe any workarounds you currently have in place or alternative solutions you've considered.

There are none.

> Is there anything else we should know?

I am asking for this as soon as possible as I'm not getting notifications from the signal team when knockdowns occur.
It would be great if this is in place by the end of this week ( 2/17/2023 ), if that is not possible next week is fine.

> Requested By
Harrell M.

[Attachment](https://api.knack.com/v1/applications/595d00ebd315cc4cb98daff4/download/asset/63ebde5484dda800288e17db/microsoftteamsimage.png) (58.64kb)

Request ID: DTS23-106400

**Comment by ChristinaTremel** [comment]
### Knockdown Trouble Call Email Notifications to Configure



- Email notification configured with new Technician work order and new MMC work order

- [ ] New Work Order | Trouble Call

- Email notification configured within 311 

- [ ] MMC SR Details Page

**Comment by ChristinaTremel** [comment]
Include this issue in the prioritization meeting and ask if anyone else would like to be included on the email notification.

**Comment by ChristinaTremel** [comment]
@ChristinaTremel work with Harrell to determine the language of the email and what fields he wants on the email.

**Comment by ChristinaTremel** [comment]
**Email Configuration: would like to see only knockdowns**
- Type: Knockdown
- Description: contains “cabinet"
- ONLY related to Work Order | Technicians
- Link goes to work order

**Comment by dianamartin** [comment]
# 4/5
## Request 

## Knockdown Trouble Call Email Notifications to Configure
- Email notification configured with new Technician work order and new MMC work order
- Email notification configured within 311

### Pages affected 
- New Work Order | Trouble Call
- MMC SR Details Page (SR to WO conversion)



    





- 



    Type: Knockdown
    Description: contains “cabinet"
    ONLY related to Work Order | Technicians
    Link goes to work order

**Comment by dianamartin** [comment]
# 4/6
On the MMC Details page
- Add work_order form
- [ ] Added Email Rule

**Comment by dianamartin** [comment]
# 4/6 
Synced with Harrell to show him the email notification and to see if he wanted any changes. He requested that Henry Z. and Toby T. be added to also receive the emails. I finished configuring the emails on the MMC page. He was happy with the changes. 

- He mentioned to add the "Lead Person Name" on the Work Order Communications table and I moved the "Created By" person to the end (on the right), removed the "Moped Project Link" on the table.
