### ISSUE TITLE
Validation for Task Orders and Subprojects

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#11487]
Reference #10993

Do research on whether or not we should validate these fields. Check with Dan V.

## Task Orders
- Modify TK
- Close TK
- New Field “Created Task Order No.” 
- ex. `24ENG01121` (10 characters) 
- formula: (`24`)(`ABR`)(`5 digits`)

## SubProject - Add new job
- Re order: Parent Project (on top)
- New field: “Created SubProject No.” 
  - 1152.043 (this is normally the format)
  - alternative should include four digits at the end and with letters.

**Comment by patrickm02L** [comment]
In planning 3/22/23:
Will revisit after the JobTypes are configured

**Comment by dianamartin** [comment]
# 5/24
- [x] Did some research on regular expressions
- [x[ Pulled the regex from SMD Tracker (Regulation No) - `\d{4}-\d{4}`
- [x[ Configured the new expression for the FDU field validations 
- [x] Tested it on the `https://regex101.com/` site
-  Updated the fields
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/849092ab-d4ae-4d8f-803b-4995d9eeb2e6)
- New Validation Rule
  -`\d{4}-\d{4}-\d{4}`
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/a6acf782-9be0-4075-a7fd-38fe075d81a8)
- [ ] Did further research on the regular expressions with alphanumeric characters for "TK Number" field
- Update field
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/4dae5e4b-bed8-48e0-b41b-4feb6c2aeefe)
  - New Validation Rule
- `\d{2}[A-Z][A-Z][A-Z]\d{5}`
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/f7cb5cde-2f6b-4483-b7cb-fd777c959ede)

**Comment by dianamartin** [comment]
# 5/24 
Synced planned with Christina on 5/25 to review updates.

**Comment by dianamartin** [comment]
# 5/25
- Synced with Christina and demoed this
- [x] Added validation to "From FDU" and "To FDU"
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/9c008817-4f07-4e15-a246-2f764f81778f)

**Comment by ChristinaTremel** [comment]
# 5/30
- After meeting on 5/30, there were a couple additional changes that need to be made to the validations of FDU and Task Orders:
- [ ] Remove "Task Order No" validation because old TKs are all numbers
- [ ] FDU validations needs options for numbers and letters

**Comment by dianamartin** [comment]
# 6/5
- Testing the new expressions shared by Chrispin
- Test 1:  `^[A-Z0-9]{4}[-]{1}[A-Z0-9]{4}[-]{1}[A-Z0-9]{4}$`

**Comment by dianamartin** [comment]
# 6/13
Met with stakeholders and reviewed the validations. Looked like they were happy with the changes, closing.
