### ISSUE TITLE
[SMD Tracker] Batch loading sign work orders & batch loading the sign points

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#11507]
> What application are you using?

Other / Not Sure

> Describe the problem.

I would like to batch upload around 164 sign work orders along with the sign points. The information was pulled from RAS vendor sign assets dataset filtered to poor condition Regulatory/Warning signs. A sign work order would include the listed sign specifications, precise geospatial locations, a photo attachment, and the work order plans attached to the work order.

The sign points would also be included with the work order so the sign technician would only be required to confirm that the sign was installed instead of refilling out the information already provided in GIS. 

> How soon do you need this?

Soon — Within a week 

> Is there anything else we should know?

Division Manager said the work orders needs to be entered in the Knack data tracker by March 1st, 2023 to comply with federal/Texas MUTCD standards given that we now have the information that these listed regulatory/warning signs are in poor condition. 

> Requested By
Susanne G.

[Attachment](https://api.knack.com/v1/applications/595d00ebd315cc4cb98daff4/download/asset/63ee67cf2a078000283581ef/layout.pdf) (107.39kb)

Request ID: DTS23-106445

**Comment by ChristinaTremel** [comment]
Need to provide Susanne with an excel document of the fields she needs to provide.

**Comment by ChristinaTremel** [comment]
To-Do
- [ ] Provide Susanne an excel list of fields she needs to provide for Sign Work Orders
- [ ] Susanne provides list to batch load Sign Work Orders
- [ ] TEST: try batch loading location points into the Sign Work Orders

**Comment by ChristinaTremel** [comment]
Sent [spreadsheet](https://cityofaustin-my.sharepoint.com/:x:/g/personal/christina_tremel_austintexas_gov/Ebq60xeU441Hlsd6Lr5na8sBAtZxKjcx_OoMis79liuCPQ?e=4%3ADfRlZj&CID=df01c2e1-9bc9-6a5d-7b34-c39c225ed34f) of fields to Susanne a couple weeks ago. Susanne is working on updating the spreadsheet with the work orders she would like to batch load.

**Comment by dianamartin** [comment]
# 4/19
- On import spreadsheet, Add "CREATED_BY" field, enter your email address @susannegov 
- Regulation = `No`
- Import another test record
- Spot check on the work order details, that Regulation is "No"

**Comment by susannegov** [comment]
## To-do
- [x] Test import 1 record `SGN23-143050`
- [ ] Need to import 109 records
- [ ] Spot check 5 random records:

**Comment by susannegov** [comment]
- [x] Spot check
   - `SMD23-36557`
   - `SMD23-187347`
   - `SMD23-192081`
   - `SMD23-195944`
   - `SMD23-280489`

**Comment by susannegov** [comment]
# 4/27
- The fields required for sign locations:
   - [ ] ` work_orders_sign` - This is connection field type tied to `ATD_WORK_ORDER_ID` need to export the batch and tied it to the Location spreadsheet via join
   - [ ] `Latitude` - X coordinate under `SIGNS_LOCATION` field
   - [ ] `Longitude` - Y coordinate under `SIGNS_LOCATION` field

**Comment by susannegov** [comment]
# 5/1
- Tested batch import one work order using `ONE_work_order_signs_locations` csv. The Work Order ID was `SGN23-144360`
- After success, batch load 108 records using `CLEAN_work_order_signs_locations` csv file
- Added "Created By" column for the CSV file associated to email
- @ChristinaTremel confirmed that the work orders have locations associated with it
