### ISSUE TITLE
Drafting Usability Updates

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#11564]
# To-Do
**(items moved from https://github.com/cityofaustin/atd-data-tech/issues/11335)**

- [ ] Fix the Connected ID field
- [ ] Improve instructional text for editing copied regulations during drafting
- [ ] Make sure drafting option information text also displayed within drafting process
- [ ] Give the option for authors to draft an install only or retire only document?
- [ ] Whether a Reviewer or Draft Author updates the Assigned, make sure it is reflective on both the Reg Doc and Review Cycle
- [ ] Add/Update Email Notifications for Draft Submitted
- [ ] Make sure Draft Author can edit Draft when Revision is requested

**Comment by ChristinaTremel** [comment]
The Traffic Register application has been restructured and these issues were already addressed. Closing this out!
