### ISSUE TITLE
General Traffic Register Usability Updates

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#11567]
# To-Do
**(items moved from https://github.com/cityofaustin/atd-data-tech/issues/11335)**

- [ ] Fix Dates on Print Page

- [ ] Format Print page for traffic regulations

- [ ]  Create task for auto expiring regs
   - Find out from users: should they have to go through review again?
 
- [ ] Update existing records with General Location values

**Comment by ChristinaTremel** [comment]
These general updates are no longer necessary or have already been completed in other issues. Closing this!
