### ISSUE TITLE
UKG Division Interviews - Parking Enterprise Timesheets

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#11646]
### Objective 
Interviews with the ATD Divisions to conduct research and document functionalities they need in the UKG system

### Participants
Jason, Gabriel, Shavyvonne, Vanessa, Lydon, Adan, Christine, Joe, Tyrone, Christina, Diana

### Agenda
- Demo UKG Timesheet process for adding TKs to Timesheets
- Parking Enterprise timesheet process 
   - Task Orders and Memo Task Orders
   - Operational Shifts (call back)
   - Differential Pay (overtime)
   - Inclement Weather
   - Holiday & Special Tasks
   - Flexible Schedule
   - Devices Used
   - Training
   - Document examples of Time sheets

------
- [x] Schedule meeting for 3/8
- [x] Meet and take notes
- [x] Debrief with DTS team members

**Comment by dianamartin** [comment]
# Diana's Notes

Adan showed time sheet demo as employee

## Task Orders and Memo Task Orders
Lyndon: a few task orders, not too many billable
- assisting APD and OSE (they have a lot of task orders)
- memo task orders: transitioning over to billable task orders: 0-2 task orders, will be 5+

## Operational Shifts (call back)
- future, adding that function

## Differential Pay (overtime)
- Uses this, every week

## Inclement Weather
- non-essential, but sometimes get reassigned to different assignments
- Does know how to use bad weather pay

## Holiday & Special Tasks
- Does know how to use Holiday pay
- Supervisors help/assist the employee to correct time sheets

## Level of Effort
- half and hour to an hour
- depends on task orders during that week
- night time supervisors need more time doing time sheets
- some corrections, more math problem
- night time have newer personnel

## Devices Used
- Computers at the office (total of 8 computers)
- Some people use their phone, brazos device 
  - ex. punching in on the office computer, punching out to lunch on different device (brazos device)

## Training
- In-person and hands on for all of them
- AM: 25 ppl, start at 7:30, Mon-Tues at 10:30 am
- PM: 15  ppl, start at 1:30 (Wed-Sat), no Monday or Tuesday

**Comment by ChristinaTremel** [comment]
# Christina's Notes

### Demo UKG Timesheet process for adding TKs to Timesheets

### Parking Enterprise timesheet process

**Task Orders and Memo Task Orders**
- Lyndon: right now there are a few task orders that are billable, but as they're turning the curve and assisting APD/Special Events, there are going to be way more task orders. 
- Memo task orders they are using are the ones transitioning over to billable task orders
- Right now they only use 0-2 task orders, but in the future 
- Memo Task Orders: Lyndon or Jason to review the memo task orders. Good to note that Jasons task orders are with right of way.

**Operational Shifts (call back)**
- No call back at the moment
- They are looking at this in the future

**Differential Pay (overtime)**
- Use overtime every week and people are used to adding this

**Inclement Weather**
- During inclement weather, there are times that the jobs shift

**Holiday & Special Tasks**
- Supervisors contact employees to get timesheets corrected

**How much time does it take to check a timesheet?**
- Shavyvonne: 1/2 to 1 hour
- Night time shifts take longer to check timesheets

**Flexible Schedule**

**Devices Used**
- Computers at the office. 8 computers available to staff.
- Some people use their phone.
- Brazos: if punching in and out, need to have this on the Brazos device if they need to clock in and out.

**Training**
- In person for ALL employees
- Hands on
- AM shift: 25 (Wednesday-Friday 7:30am and Monday-Tuesday 10am)
- PM shift: 15 (Wednesday-Saturday starts 1:30pm)

**Document examples of Time sheets**

**Comment by ChristinaTremel** [comment]
Added notes to [UKG Discovery Effort - ATD](https://docs.google.com/document/d/1KWkz0XcNLhjqHmo_ArkQMNZojXrxWEN8ZPMqMpD-V7E/edit#heading=h.lds4o3mycsyw) document.
