### ISSUE TITLE
Update "Journal Voucher" info in AMD Data Tracker - Warehouse Inventory- March 2023

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#11656]
- [x] Received JVDA spreadsheet,  transaction dates 2/6/23 through 3/15/23; JV date 3/21/23 
- [x] Number of records being updated: 177
- [x] Format spreadsheet [(Review instructions)](https://atd-dts.gitbook.io/atd-knack-operations/warehouse-inventory-updating-journal-vouchers-jv-information)
- [x] Spot check Transaction IDs, no JV information before import: 24105 ✅  17307 ✅ 
- [x] Import records
- [x] Spot check Transaction IDs, no JV information after import
- [x] Email Finance staff that update task complete

Delay: all the records were updated but [#23380](https://builder.knack.com/atd/amd/records/objects/object_36?builder_table_search=23380) is not showing up in the filter because it's Transaction Status in the system is listed as `Cancelled`. Checking with @dianamartin; flagged the inconsistent item for Crystal in the email.

**Comment by KaroEngstrom** [comment]
Closing this as the inconsistent item does not appear to be of concern to requesters.
