### ISSUE TITLE
Front End Enhancements on the Work Order - Communications Work Order Page

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#11663]
# Updates Requested

## [Work Orders | Communication Table](https://atd.knack.com/amd#work-orders-communications/)
- [x] Add “Assigned to” to the main work orders table

## New Work Order Form ([find here](https://atd.knack.com/amd#work-orders-communications/))
~~- [ ] Add “Work Requested By” field on New Work Order Form~~
~~- [ ] Add "Reported By" field on new work order form~~
- these refer to the same field but appear with under both labels in the app; see the work comment below for details

## Edit Work Order Form
- On [Communications - Edit Work Order page](https://atd.knack.com/amd#work-orders-communications/work-order-details2/64186d216a83be0029958640/edit-work-order3/64186d216a83be0029958640/) that Harrell uses, he needs fields added to mirror another form (including work reported by)
- Wanting to add additional fields from another [Communications - Edit Work Order page](https://atd.knack.com/amd#work-orders-communications/work-order-details2/64186d216a83be0029958640/signal-details/5817c07ee052e0422be6c4de/work-order-details/64186d216a83be0029958640/edit-work-order/64186d216a83be0029958640//) that has fields that doesn't currently exist on Edit Work Order table that Harrell uses.
- **Fields to Add**
   - [x] Work Type
   - [x] Schedule Immediately
   - [x] Schedule Date
   - [x] CSR/Issue #
   - [x] Work Reported By
   - [x] Follow-Up Needed 
   - [x] Follow-Up Description
   - [x] APD Case No

**Comment by ChristinaTremel** [comment]
Check with Brian C on anything new in this issue. Schedule time to review these @ChristinaTremel

**Comment by dianamartin** [comment]
# 4/6
I synced with Harrell and he mentioned to add the "Lead Person Name" on the Work Order Communications table and I moved the "Created By" person to the end (on the right), removed the "Moped Project Link" on the table. I forgot that this was on this issue. @KaroEngstrom one less thing for you to do. I might do this issue if it's quick enough today. I'll let you know.

**Comment by KaroEngstrom** [comment]
## F 4/7/23 

**NEW WORK ORDER FORM piece** 
- parent page [Work Orders | Communications](https://atd.knack.com/amd#work-orders-communications/)
- A. [Signals - New Work Order Trouble Call](https://atd.knack.com/amd#new-work-order-trouble-call/) | | [Builder](https://builder.knack.com/atd/amd/pages/scene_1308)
     - already has the **Reported By** labeled field that displays the `WORK_REQUESTED_BY` field
     - checked in with Christina and we will retain this as is and duplicate this on the Scheduled Work sibling form
- B. [Signals - New Work Order Scheduled Work](https://atd.knack.com/amd#new-work-order-scheduled/)
     - [x] Added a **Reported By** labeled field that displays the `WORK_REQUESTED_BY` field (similar to Trouble Call version of the New Work Order form)

**Comment by KaroEngstrom** [comment]
## F 4/7/23 
- this is done, @ChristinaTremel - thanks for working together to clarify the need! I followed field placement in the reference model. If the requester wants anything moved around, I'm happy to do that. 
- updated change log in Data Tracker

**Comment by ChristinaTremel** [comment]
# 4/17/23

Synced with Harrell to show him the front end enhancements that were made to the "Communications - Work Order"! He was happy with the fields available and with the formatting.
