### ISSUE TITLE
Email Notification Updates

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#11672]
Reference #11639 
Sharon M. 
Finance 

Emailed 3/3
>Looking forward to our meeting on Monday. I believe we needed to draft emails for the Requestor and Tim (our new manager) for when transactions were submitted. Below are my first attempts – we can talk about them on Monday.

>Also, not sure if we are still deciding what the menu verbiage should be in Knack for this project - I was thinking ‘CIP Service Requests’ then the drop down can have options such as:
(I believe you already have this part or it goes to an option menu)

>New Subproject w/ New FDU and Funding (and new TK option)
New FDU (w/ Funding)  (this one and one above will include the BGEX/ funding for the new FDU)
BGEX
TK Request (new and edits)
JVD (Journal expenses)
IET (Pay Invoice)
SA or SeRF  (need to talk to you about these – won’t require editable fields or transaction numbers if we decide to include!)

# Email to Finance Manager
_feedback from 3/6 meeting_
- [ ] "Add Task Action" to email
for TK

>Hello Tim – 
An Aims transaction has been submitted today, DATE, and it ready for you to review and approve.  Please see request information below:

>Transaction Type:  (BGEX, TK, JVD, IET)
Transaction #: (Aims transaction or TK# if TK)
Staff who submitted Transaction (Sharon or Jenny)
Dollar amount:  
Notes from Requestor:

>AND/OR ADD A LINK HERE TO KNACK SO HE CAN GO TO TRANSACTION AND LOOK AT DETAILS BEFORE GOING INTO AIMS
Note: - I don’t think any attachments are necessary in email since he will see them in Aims for JVD’s and IETs 

# Email to Customer
>Hello Requestor – 

>Your request number XXXX has been complete today, DATE, by Finance.  Please see request information below:

>Transaction Type:  (BGEX, TK, JVD, IET)
Transaction #: (Aims transaction or TK# if TK, which includes new TK)
Staff who submitted Transaction (Sharon or Jenny)
Subproject number if NEW
FDU number if NEW
**Question – can we/Staff attach a PDF in Knack that can go to Requestor?  For IET’s and for SA/SeRF’s we currently send back a PDF to the requestor.                  

>Your request still has to approved by the Controller’s or Budget office (maybe Tim, too) so please give the request at least 2-3 business days before you see the completed transaction in eCAPRIS.  

>Please contact Sharon or Jenny with questions, thanks!
-ATD Finance

**Comment by dianamartin** [comment]
# Mocked up email to Finance Manager
![image](https://user-images.githubusercontent.com/21112975/223843101-f38c7ede-216f-4397-ae10-bfa49da3511c.png)

# Mocked up email to Customer
![image](https://user-images.githubusercontent.com/21112975/223843194-f97a9646-f391-46c1-a886-f941a17f40e9.png)
- still unfinished "Subject Line" 
- Need **Transactions Number**
- Need **Subproject Number**
- Need **FDU Number**

**Comment by dianamartin** [comment]
# 4/25
- Update the emails for Customer and Finance Manager 
- Work on rolling up statuses, otherwise direct to SR Details page if too complex

**Comment by ChristinaTremel** [comment]
# 5/17 Meeting Follow-Up
- [ ]  Update completed email sent to Requester for when the Service Requests are in the Complete status

**Comment by dianamartin** [comment]
# 5/25
- Worked on this by creating new fields on the `service_request` object
- FDU No.
- Subproject No.
- Task Order No.
- Document ID
- [x] Added record rule on the editable tables on the SR Details | Admin pages for the various jobs types
- [x] Testing out the email

## Email 
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/a0aeabe4-8b52-4405-aaf7-d9040c044243)

**Comment by ChristinaTremel** [comment]
# 5/30
After meeting on 5/30, there were a couple additional changes that need to be made to the validations of FDU and Task Orders:
- [ ] Email notification to Tim: Remove job fields and add "Notes to Finance"
 - [ ] Need to update email when Tim "Completes" Service Request. Add link to the "Service Request Details" page. Remove the reference to Sharon and Jenny and say to reach out to TPW Finance with question
 - [ ] Email when a new SR is submitted needs to be changed to the finance inbox email address

**Comment by dianamartin** [comment]
Closing, we completed further tasks on #12498
