### ISSUE TITLE
Release VZ v1.31.0

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#11724]
**To-do's for upcoming release**

- [x] Schedule release party - @patrickm02L 
- [x] Advise users of downtime - @patrickm02L 
- [x] Create a release PR - @mddilley 
- [x] Propose + vote on release names - @patrickm02L 
- [x] Refine [release notes](https://github.com/cityofaustin/atd-vz-data/releases/tag/v1.31.0) @patrickm02L 
- [x] Bump VZ **staging** version to `v1.32.0` and VZ production to `v1.31.0`- @mddilley 
- [x] Send out release notes - @patrickm02L 

[Release Management Process gitbook](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-LzDGg7hKQ_fUjXnzGGx/product-ops/release-management-process)

**Comment by patrickm02L** [comment]
We'll need to coordinate with @roseeichelmann and make sure we're going through the steps for releasing the FTT Feature #11696.

**Comment by patrickm02L** [comment]
Very nice work folks!!!
