### ISSUE TITLE
Create Object Tables for SMD Training Tracker Prototype

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#11807]

**Comment by KaroEngstrom** [comment]
## Th 5/4/23 🏗️ 
- [ ] Copy `training_enrollment` object from `training_attendance` 
- [ ] Update object fields, connections, and rules  + edit out unnecessary fields

**Test New Process** 🧪 
- [ ] Update training event creation to include enrollment and test 
- [ ] Update training event completion to include attendance record creation
