### ISSUE TITLE
Back End Enhancements on the Work Order - Communications Work Order Page

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#11855]
# Updates Requested

## Drop-Down Fields - Add List Items
- [x] Add List Items to "Reported By" field
   - Communications
   - Signal Engineers
   - Smart Mobility (Requested by BC)
- Add Contractors to "Assigned To" field (need to clear this with Brian C if we can add these temporarily)
    - [x] JC Com
    - [x] Brycomm
    - [x] Primoris

- [x] Add work group to "Completed Work" field
   - Communications
- [x] Add item to "Component" field
   - Cable - Fiber Optic
- [x] Add item to "Action" field in the Completed Work Table
   - Issued to Contractor  

## Work Order - Rules
- [ ] Currently no way to move work order into "In Progress" without closing the work order and reopening. Need to create rule when Timelog is added, change status to “In Progress”

- [x] #11467 [Data Tracker] Send email notification when a knockdown trouble call comes in - separate issue submitted for this request

**Comment by dianamartin** [comment]
@ChristinaTremel did we ever clear with BC on the Contractors to be added as a new Data Tracker account?

**Comment by ChristinaTremel** [comment]
@dianamartin yeah, I specifically asked him about those new Data Tracker accounts for the Contractors that Harrell assigns work to and he was comfortable with adding those!

**Comment by dianamartin** [comment]
# 4/6 
- Christina and I synced to try to figure out the AMD WORK_ORDER_STATUS in our Miro board for AMD Work Order. Still working on this.

**Comment by ChristinaTremel** [comment]
Still need to do:
- [ ] Currently no way to move work order into "In Progress" without closing the work order and reopening. Need to create rule when Timelog is added, change status to “In Progress”
- [ ] Re-add the open text field when selecting the Asset Type = `Other`
