### ISSUE TITLE
Signal Request to put together a quick way to input new IPs

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#11852]
> What application are you using?

Data Tracker

> Describe the problem.

Signal Request to put together a quick way to input new IPs.

User to look up by signal, show 3 tables:

### Table 1 - `signals` object table
-    `CONTROLLER IP` field - MMC

### Table 2 - `signal_cabinet` object table
- `MONITOR IP` field - MMC
- (BBU) `UPS IP ADDRESS` field - MMC

### Table 3 - `camera` object table
- `CAMERA IP` field

> Describe the outcome you'd like to see when this feature is implemented.

Our team will be able to more efficiently update IPs in multiple areas. We have a major project coming up where we will be replacing over 200 cell modems and standardizing the IPs. This would help us more easily update things on the data tracker side.

> Describe any workarounds you currently have in place or alternative solutions you've considered.

Just going to each individual field and changing it.

> Is there anything else we should know?

Sometime in April. We will be starting this project within the next couple of weeks. If we could have it in time for this project that would be great if not would still be useful for future projects. Thanks 

> Requested By
Chris S.

Request ID: DTS23-106815

**Comment by dianamartin** [comment]
# 3/30
Configure this:
### Table 1 - `signals` object table
-    `CONTROLLER IP` field - MMC

### Table 2 - `signal_cabinet` object table
- `MONITOR IP` field - MMC
- (BBU) `UPS IP ADDRESS` field - MMC

### Table 3 - `camera` object table
- `CAMERA IP` field

- [x] Created new page `MMC Tracking` - will set as "Viewer" user permissions like "MMC page"
- [x] Added new details page
- [x] Added new table "Signals"

**Comment by dianamartin** [comment]
Christina and I synced with Chris and showed him the new page. We pivoted and made a navigation menu from the "Signal Details" page and copied the elements over. 

We added the page rules to only allow "TMC Operator" titles. Kenny discovered he can't access this page.

**Comment by dianamartin** [comment]
# 5/30
- added Kenny M. to have "TMC Operator" title
