### ISSUE TITLE
[CSWZ] Review Cycle Features EPIC

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#11850]
### Epic for this build to be used for scoping & meeting notes. 

----

> What application are you using?

Right-of-Way (ROW) Portal

> Describe the problem.

To create a multiple review cycle and Mutiple entry of dates on TCP conflict and Shared work zone portal. Basically if the review is returned and applicant provides the required information we can have a new review, cycle

> Describe the outcome you'd like to see when this feature is implemented.

Our team will be able to track reviews since Knack is our official record keeping tool.

> Describe any workarounds you currently have in place or alternative solutions you've considered.

The current work around will force applicants to re apply for request which will create duplicate requests.

> Is there anything else we should know?

as soon as possible since the web page is live.

> Requested By
Samson N.

Request ID: DTS23-106810

**Comment by TracyLinder** [comment]
Next: Meet w/ Samsun to discuss easier to implement solutions vs a public resubmittal feature.

**Comment by TracyLinder** [comment]
### Scoping Mtg Scheduled
- Monday 4/17

**Comment by TracyLinder** [comment]
## Meeting Notes

- Mirror TCP Submissions Table
- Reviewers want to see each cycle on their Reviewer Dashboard

**Comment by KaroEngstrom** [comment]
# Sa 4/29/23

@TracyLinder 
I was able to spend a few hours today deep-diving into TCP and I talked to @dianamartin about the build in general earlier this week. This is not going to be a quick two week add-on (which is why we didn't include it in the initial like-for-like build a few months ago).

The next meeting with Darren and team should be a scoping meeting to address the few dozen specific additional features in the TCP projects than in the TCP Conflict/Shared requests. These need to be understood and decided on before trying to copy this functionality from the TCP Review process to this like-for-like spreadsheet replacement. This is a bigger project than the like-for-like move from Smartsheet to Knack was for CSWZ.

**Comment by dianamartin** [comment]
# 5/1 - Build Steps (min. manual submission)

Starting with:
- `tcp_cswz_request` - parent
- `tcp_cswz_attachment`
- + create new`tcp_cswz_submission` object - review cycle
  - + add connection (to `tcp_cswz_request`)

Submission features (Reference)
- `tcp_project` - parent
- `tcp_submission` - review cycle
- `tcp_submission_content` - attachments/comments

**Comment by dianamartin** [comment]
## Intake Process
![image](https://user-images.githubusercontent.com/21112975/235538964-88db0495-e274-4935-99af-51549bc5e2ca.png)


Submission Status
- Under Creation
- Pending Intake
- Needs Review
- Review in Progress
- Review Complete
- Improper Completeness Check
- No Review Required
- Cancelled
- Returned

**Comment by KaroEngstrom** [comment]
## T 5/9/23 
- huddled with Tracy, Chrispin, and Susanne
- mapped out issue in Miro - identified the main points to convey to ROW 
- Karo and Tracy will sync briefly M 5/15 in preparation
- 30 min scoping/ build kick-off with Darren on W 5/17 
- **main points to cover with ROW:**
     - what to expect from this build: similarity and difference to TCP projects 
     - scheduled timeline: the next two sprints / the next month 
     - downtime to final go-live: 3-4 hours to allow for the switchover
     - builds up to current TCP model; plan to update along with TCP submission upgrades to customer code when that next step is taken

**Comment by TracyLinder** [comment]
### Apps Planning Notes 5/31

- Tracy needs to add the functional requirements to the issue description 
- Making this an epic, and repurposing to be the scoping/notes issue
- Karo will start building this sprint
- Demo goal date is still 7/18
- Karo is out VCU on 6/14
- Let's look at what has been built just before Karo leave's

**Comment by KaroEngstrom** [comment]
![image](https://github.com/cityofaustin/atd-data-tech/assets/100615928/d7b9ec67-ca1e-4073-8a3f-869629a04ac6)

**Comment by TracyLinder** [comment]
### Discuss w/ Stakeholders

- Add CSWZ to Workload page?

**Comment by KaroEngstrom** [comment]
## Agenda T 7/11/23 🍨 
- **Build So Far** 
    - object tables built (June)
    - test portal built (June) 
    - new views and pages built for cycle review 
    - records from test portal configured to go to new views and pages for cycle review 
- **Next Steps before stakeholder update mtg T 7/18/23** 
    -  ➡️ test workflow
    - ➡️ adjust connections (known issues list and testing notes go in #12569 )
    -  🌈 aspirational but possibly not completed until pilot period: adding cycle reviews to Reviewer Dashboard

**Comment by TracyLinder** [comment]
### Internal Demo Notes 7/11/23

- It's not ready because it's 3 days earlier than requested. 


**Build Notes:**
- [ ] Feature so that the Request Details shows user this is a no-cycle record. Karo suggested a new field that auto-determines it's status as a pre-cycle record. For those records


- [ ] Q: Can Tracy perform the demo? Or can i test independently prior to the demo? 


**Stakeholder Demo Notes:**
- [ ] Be sure to validate the status' workflow
1. Demo/test the features by use case:
   - Initial submittal by customer
   - Review of initial submittal with 'returned' outcome
   - Create a 2nd submittal with 'review complete' outcome 

2.  


**Advanced Search:** 
- Had a conversation. What are the needs? Tracy said to be sure the users have the ability to search all records regardless of which version it was created under (historical.)
- All CSWZ cases
- CSWZ submissions

**Landing Page**
- [ ] Discuss w/ stakeholders 
- Ask what they want to use this page for
- Various ways they can view the no-cycles and the future records on the page. ⁉️

**Comment by TracyLinder** [comment]
### Go-Live Info:

- Rollout scheduled for **8/14/23 at 3pm** `SYSTEM WILL BE DOWN`
- Checkin: CSWZ Review Cycle Features meeting scheduled for 9/15
