### ISSUE TITLE
Document Scope of ATD Funding Code Update for Dpt Merger 

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#11936]
### Per ATD Finance all ATD fees need to be updated with the public works funding number 5120

- [x] Discuss at product sync on 4/4/23
- [x] Meet with Erin from Finance on 4/7
- [ ] Gather a list from Apps team

**Notes**
- TBD if this is an immediate update or something to roll out on 10/1/23
- How do we find & document all the tech affected (fee codes, reporting...)
- How do we approach this?

**Comment by TracyLinder** [comment]
I've informed all product owners of this requirement and I've moved my focus to the AMANDA updates specifically.
