### ISSUE TITLE
Hello. I am trying to use Data Tracker / Knack to see updated statuses for safety improvement projec...

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#11956]
> What application are you using?

Data Tracker

> Describe the problem.

Hello. I am trying to use Data Tracker / Knack to see updated statuses for safety improvement projects at specific intersections so I can update data for a Safe Streets for All project/task. At the moment, I don't have access to the Data Tracker / Knack and would like to request access.

> How soon do you need this?

Flexible  — An extended timeline is OK

> Requested By
Michael K.

Request ID: DTS23-107020

**Comment by dianamartin** [comment]
@KaroEngstrom can you show @susannegov how we address these account access requests? 🙏🏽 ty

**Comment by KaroEngstrom** [comment]
## W 4/5/23 
- messaged Michael via Teams to check if there's another user whose permissions we might mirror
- he wasn't aware of any but confirmed the kind of access he needs - to view intersection data; he mentioned Mary V. as the person who referred him to use Data Tracker for this

**Next steps - Th 4/6/23 :** 
- [ ] Check Viewer level access in Knack 
- [ ] Check with supervisor if needed 
- [ ] Create Michael's account together with @susannegov 
- [ ] Notify requester with instructions for logging in
