### ISSUE TITLE
Micromobility Device (E-Scooter)

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#12004]
This is an epic to capture the "motorized conveyance" issues.

In 2020, investing agencies were directed to start using "motorized conveyance" as the unit type for e-scooters. Having 2 years plus of analysis has allowed us to see that the data integrity was compromised. Investigator are not using "motorized conveyance" consistently and thus required us to use a new flag `micromobilty_device_fl`. 

The Issues in this epic reflect the latest definitions of the use of e-scooters.

#### Order of Issues
- [x] 12161 - Update UI to make unit description and vehicle body style editable
- [x] 11324 - Move micromobility device flag to Units table
- [x] 7081 - Add scooter-rider involved and motorcycle involved filter to VZE
- [x] 12065 - Update ETL with unit crash changes for Scooter
- [x] 12308 - Add Other toggle to Units Type parameter group

- [x] 12012 - Remove micromobility device flag from Flags table
