### ISSUE TITLE
Release VZ v.1.32.0

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#12051]
**To-do's for upcoming release**

- [x] Schedule release party - @patrickm02L 
- [x] Advise users of downtime - @patrickm02L 
- [x] Create a release PR - @chiaberry 
- [x] Propose + vote on release names - @patrickm02L 
- [x] Refine [release notes](https://github.com/cityofaustin/atd-vz-data/releases/tag/1.32.0) @patrickm02L 
- [x] Bump VZ **staging** version to `v1.33.0` and VZ production to `v1.32.0`- @patrickm02L 
- [x] Send out release notes - @patrickm02L 

[Release Management Process gitbook](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-LzDGg7hKQ_fUjXnzGGx/product-ops/release-management-process)

**Comment by patrickm02L** [comment]
Another release success!
