### ISSUE TITLE
Add new selections to scheduled work assigned drop down

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#12067]
> What application are you using?

Data Tracker

> Describe the problem.

Under Add Scheduled Work, Scheduled Work Assigned drop down menu,
Can you add selections:
"Communications - Communication Switches City Wide 2020 Bond"
"Communications - Communication System Equipment Damage / Knockdown"
"Communications - Program Ethernet Switch"

> Describe the outcome you'd like to see when this feature is implemented.

These additions will give the communications team selections that are better suited for our team.

> Describe any workarounds you currently have in place or alternative solutions you've considered.

None

> Is there anything else we should know?

Can you please add as soon as possible. The Com team will start rolling out the new etherwan switches starting 4/24/2023.

> Requested By
Harrell M.

Request ID: DTS23-107200

**Comment by ChristinaTremel** [comment]
Reached out to Harrell asking to standardize one of the options he's wanting in the 'Scheduled Work" drop down
> Hey! I saw that you needed some drop down options added to the "Scheduled Work" field. For one of the options "Programs - Ethernet Switch" could I rename that to "Communications - Ethernet Switch Program"? Just so all of the options you need are grouped together.

@dianamartin once I hear back from Harrell, who can I assign this issue to? It sounds like he needs a quick turnaround on adding these options.

**Comment by ChristinaTremel** [comment]
Update "Scheduled Work" drop down with new items: 

- [ ] Communications - Communication Switches City Wide 2020 Bond
- [ ] Communications - Communication System Equipment Damage / Knockdown"
- [ ] Communications - Program Ethernet Switch

**Comment by ChristinaTremel** [comment]
@KaroEngstrom check in with @dianamartin on which page this can be found on!

**Comment by dianamartin** [comment]
# 5/17
@KaroEngstrom Add to this [page](https://builder.knack.com/atd/amd/records/objects/object_218) - `work order signals schedule work` object
- Add to this drop down list: https://builder.knack.com/atd/amd/schema/list/objects/object_218/fields/field_4205/settings

**Comment by KaroEngstrom** [comment]
Heard back from requester: "Thank You Very much!"
Closing
