### ISSUE TITLE
Create a mechanism to overload lookup tables

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#12162]
# Background
Today, in a conversation during the VZ sprint review and continued in a follow-on conversation, we discovered that we have at least a handful of lookup tables which we forked from the CRIS provided lookup tables and augmented them with additional records. 

This solution is problematic in the context that we're now being more diligent in keeping up with the on-going changes that CRIS makes to its upstream lookup tables. For reference, we made about 1,000 additions and edits to our lookup tables leading up to the LDM launch.

We do not wish to continue to augment our ETL process to handle these lookup table divergences, as it will become increasingly complex to maintain over time.

# Solution
* [ ] The LDM will be enhanced with a mechanism to allow for CRIS' lookup tables to exist exactly as reported by CRIS, and live in a schema dedicated to house them, perhaps `cris_lookup_tables`. 

* [ ] The LDM will contain a schema, perhaps `vz_lookup_tables` augmentations, which will contain tables that encode a set of changes to the CRIS lookup tables, stored in a way that will elegantly handle changes provided by CRIS. This encoding scheme is yet unknown, and if a suitable mechanism is not available, this approach will need to be revisited. The challenge is how to handle `id` fields, such that we generate stable ids to be be exposed for the combined lookup table output, described in the next paragraph.

* [ ] In the `ldm` schema, lookup tables will be exposed as a materialized view for each look up table which draws from the `cris_lookup_tables` and includes the augmentations defined in the `vz_lookup_table` if one exists for the lookup table in question. The creation and maintenance of these materialized views will be automated by a python script which will then become an ETL that runs on a daily or weekly basis to ensure that the materialized views remain current as changes are made to the `vz_lookup_tables` and the `cris_lookup_tables`.

**Comment by frankhereford** [comment]
I believe this is ready to roll, but there's an interesting question that falls out of the implementation I've chosen. 

I'm using a salted `sha1` value of the IDs from the contributing tables to a LDM lookup table, and as a result, the ID values in the exposed LDM view will have non-sequential IDs. They will appear randomly picked for each value, but they will remain stable, so they suit the needs of an ID.

The question that arrises is how big of a namespace of IDs do I need to allocate such that we can support the length of the lookup tables we want to overload. Meaning, if we only want to overload small tables, in the combined LDM view, the IDs can be constrained into smaller, easier to read numbers than if we want to support longer tables.

So, here's the question. For each group of results here, which is the first one in the list where the list of lookup tables contains no lookup tables that we'll ever want to enhance with extra records:

```
Testing with 5 characters of the sha1 hex value giving 1048576 possible values
The maximum value of sequentially assigned IDs in either contributing table is 882
The following tables have an ID that is too large:
['atd_txdot__agency_lkp', 'atd_txdot__cas_transp_locat_lkp', 'atd_txdot__cas_transp_name_lkp', 
'atd_txdot__city_lkp', 'atd_txdot__cntl_sect_lkp', 'atd_txdot__hazmat_idnbr_lkp', 
'atd_txdot__ins_co_name_lkp', 'atd_txdot__inv_da_lkp', 'atd_txdot__inv_notify_meth_lkp', 
'atd_txdot__ref_mark_nbr_lkp', 'atd_txdot__state_lkp', 'atd_txdot__veh_damage_description_lkp', 
'atd_txdot__veh_damage_severity_lkp', 'atd_txdot__veh_make_lkp', 'atd_txdot__veh_mod_lkp', 
'atd_txdot__veh_year_lkp']

Testing with 6 characters of the sha1 hex value giving 16777216 possible values
The maximum value of sequentially assigned IDs in either contributing table is 2885
The following tables have an ID that is too large:
['atd_txdot__agency_lkp', 'atd_txdot__cas_transp_locat_lkp', 'atd_txdot__cas_transp_name_lkp', 
'atd_txdot__city_lkp', 'atd_txdot__cntl_sect_lkp', 'atd_txdot__ins_co_name_lkp', 
'atd_txdot__inv_notify_meth_lkp', 'atd_txdot__ref_mark_nbr_lkp', 'atd_txdot__state_lkp', 
'atd_txdot__veh_damage_description_lkp', 'atd_txdot__veh_damage_severity_lkp', 
'atd_txdot__veh_make_lkp', 'atd_txdot__veh_mod_lkp']

Testing with 7 characters of the sha1 hex value giving 268435456 possible values
The maximum value of sequentially assigned IDs in either contributing table is 7757
The following tables have an ID that is too large:
['atd_txdot__agency_lkp', 'atd_txdot__cas_transp_locat_lkp', 'atd_txdot__cas_transp_name_lkp',
 'atd_txdot__city_lkp', 'atd_txdot__ins_co_name_lkp', 'atd_txdot__inv_notify_meth_lkp', 
'atd_txdot__ref_mark_nbr_lkp', 'atd_txdot__state_lkp', 'atd_txdot__veh_damage_description_lkp',
 'atd_txdot__veh_damage_severity_lkp', 'atd_txdot__veh_make_lkp', 'atd_txdot__veh_mod_lkp']

Testing with 8 characters of the sha1 hex value giving 4294967296 possible values
The maximum value of sequentially assigned IDs in either contributing table is 61616
The following tables have an ID that is too large:
['atd_txdot__cas_transp_name_lkp', 'atd_txdot__city_lkp', 'atd_txdot__ins_co_name_lkp']

Testing with 9 characters of the sha1 hex value giving 68719476736 possible values
The maximum value of sequentially assigned IDs in either contributing table is 174989
The following tables have an ID that is too large:
[]
```

**Comment by patrickm02L** [comment]
@chiaberry please add comments and feedback about this approach.

**Comment by frankhereford** [comment]
This is complete and is incorporated into the work on #12577

**Comment by frankhereford** [comment]
I closed this without realizing it's an epic! My error!
