### ISSUE TITLE
Remaining Build for Training Tracker Prototype

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#12163]
# Primary Work for Initial Stakeholder Review 

### 1. ~~Create Enrollment Object for~~ Status Flow Solution
- Task outlined in #11807 ✅ 
- single object solution in the `training_attendance` record 

### 2. Update Pages 
- Document in #11808 
- ~~Incorporate new Enrollment object from #11807~~ 

### 3. Configure IMSA Timestamping, Counts, and Displays 

- Map requirements in Miro 
     - User IMSA Details 
          - IMSA Membership number - field (manual or bulk entry) ✅ 
          - IMSA Certification date - manual entry ✅ 
          - IMSA Cert Expiration date - calculated field (+3 years) ✅ 
          - IMSA Cert Expiration warning period/flag - calculated field (less than six months to expiry) ✅ 
                - shows up on Participants table
                - expiry date with flag appears on each Participant Details page 
          
        [  **LATER ITEMS:**
          - IMSA Eligible Enrollment HRS in this cert period - count 
          - IMSA Eligible Completed Training HRS (`training_attendance`) in this cert period - count ]
     
     - IMSA Eligible Training 
          - column in Trainings table on Landing page and in Participant Details page

- Add the above configurations in Builder 

### 4. Add to Admin Page 
- Add ability to administer `training_type` records as follows: 
     - [x] Add Training Type (default to Active status)
     - [x] Edit Training Type 
          - [x] Make Active/Inactive (toggle status)
- IMSA specific fields for Training User account object 
     - [x] Add second table just for Training User management ✅ 
     - [x] ~~Add Action column in the Accounts table on the existing Accounts Admin page~~ Can't do this because the IMSA items are not available in the existing Account tables row (only present for Training User |Signs & Markings account ype) ➡️  Created a table under the Accounts for **Training User | Signs & Markings** management; this will be available to Cathy only ✅ 
     - [x] Add Edit modal pop-up for editing user's IMSA details ✅ 
     - [ ] ~~Add rule to not display the action button for users who do not have the Training User role~~ No longer relevant because not added to the existing Accounts table
     
# Secondary Work for a Later Stakeholder Review 

### 5. Any Updates from Stakeholder Review 
- demo outline [here](https://docs.google.com/document/d/112DOJr9ksq8bFPNvjhnytezQ8KSAi1BOPjFF78-_wQ4/edit#) and will document questions and notes there as well

### 6. Build Advanced Search Page 
 - IMSA related searching will likely be important
 - Need to understand the team's reporting requirements - we have a reporting sample from Cathy (from SMD to IMSA)

**Comment by KaroEngstrom** [comment]
## F 5/12/23 
- wrote up a [demo walkthrough plan](https://docs.google.com/document/d/112DOJr9ksq8bFPNvjhnytezQ8KSAi1BOPjFF78-_wQ4/edit#) and tested the listed features 
- @ChristinaTremel set up a quick sync for us Monday for a final lookthrough and goal setting 
- meeting with stakeholder Th 5/18/23

**Comment by KaroEngstrom** [comment]
## M 5/15/23 

- synced with @ChristinaTremel and will complete the final tweaks as follows: 
     - [ ] Move the flag icon to the Expired Cert field to visually signal any certs where the next expiry date has passed 
     - [ ] Update the colors to official SMD Knack App shades in the Events page Participants table and the Account Admin page Participants table 
- we will discuss document Attachments needs with Cathy as that might include attachments for both Participants records and the Training Event records
