### ISSUE TITLE
[Feature] Scoping Inspector Work Order form for AMD Inspectors

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#12176]
> What application are you using?

Other / Not Sure

> Describe the problem.

Brian C has requested a simple form to serve as an Inspector Work Order (rather than inspectors having to enter all the information in the current WRK).  I have created a Word Form to demonstrate what information to be collected by inspectors each time they are on site, or working on a location/project.  I have put more details on the type of field in parenthesis next to the field name (ex: Date (will default to the current date, but is editable)). We would either like a more user-friendly form like the attached example, or if possible, a separate Work Order for Inspectors within Data Tracker (but very simple like the form link below).  I am happy to explain further, as needed. 

https://forms.office.com/Pages/DesignPageV2.aspx?prevorigin=Marketing&origin=NeoPortalPage&subpage=design&id=9hleXKumRUux0L5GCKmmf8NzkHKLRudEtT004bmyr7BUNFk0RTEzSlVMUTEyRkkxUFlMTE1KTVVNOS4u&branchingelementid=re658506869bd41ae90bfd31b3ee7ae87&analysis=false

[From 12184](https://github.com/cityofaustin/atd-data-tech/issues/12184):

I just submitted a request (Request ID: DTS23-107675) and realized that I failed to add one thing. In addition to the creation of this Inspector form or work order, we would like, if possible, for it to have reporting capabilities so that inspectors could run a report at the end of the week to show all of the TKs they've used and the associated time on each one so they can easily transfer that information to their timesheets.

> How soon do you need this?

Flexible  — An extended timeline is OK

> Requested By
Erin B.

[Attachment](https://api.knack.com/v1/applications/595d00ebd315cc4cb98daff4/download/asset/6452aaebb6cbc90027909f62/inspectorworkorder.jpg) (46.53kb)

Request ID: DTS23-107675

**Comment by ChristinaTremel** [comment]
Scheduled meeting for 6/20 to start scoping this request.

**Comment by ChristinaTremel** [comment]
### Tracking
- Project Location
- Time Arrived
- Inspection Category
- Description
- Time Departed
- TK

### Inspector Daily Work
- Bulk of time is inspecting contractor work
   - Sometimes it's AMD Contractor
   - Sometimes it's other peoples Contractors near signalized intersections
      - The other contractor work sometimes causes work for AMD
      - Example: loading zone for moving materials at 15th & Lavaca, which creates a visibility concern so they will pay AMD to install overhead span to provide a nearside signal
      - Get notifications about this work in many different ways: different PMs through IDIQ will reach out periodically. Comes about via email or phone call or 311
- TK's
   - If someone pays for the work, a TK will be included
   - There are general TK's for downtown work, AE work, etc
   - Depends on who it is/where it is?
- People reach out to inspectors directly (90% of the time)

**Comment by dianamartin** [comment]
# Build Steps
- Reference the: Work Orders - Engineering in `TEST | Austin Transportation Data Tracker | 11 MAY 2023` environment
- Page [reference](https://builder.knack.com/atd/test--austin-transportation-data-tracker--11-may-2023/pages/scene_1539)

## New Work Order 
- Time Arrived button functionality
- Fill out Work Order Details
  - Location
  - TK
  - Description
  - Inspection Category

## Edit Work Order
- Have same fields in new work order editable

## Work Order Details
- Have same fields in new work order - non-editable
  - Completed Work table - non-editable
  - Time Log table - non-editable

## Functionality
- When work order is created, have "Time Arrived" button
- When work order is submitted, auto close work order (Time Departed)

**Comment by dianamartin** [comment]
# Build Notes
- Reference the: Work Orders - Engineering in `TEST | Austin Transportation Data Tracker | 11 MAY 2023` environment
- Reference: `Work Orders - Sign Engineering` page in TEST or PROD

## Object 
- Use object: `work_orders_signals`

## Page Creation
- Create new page `New Work Order Inspectors`
  - Add form, source: `work_orders_signals`
- Create new page `Work Orders Inspectors` OR use `Work Orders (Non-Technicians)` and rename to `Work Orders Inspectors` 

## Building Page - `Work Orders Inspectors` 
- Add menu - "New Work Order form" (link to `New Work Order Inspectors`)
- Add table - `work_orders_signals`
- Filter the source as `Construction Services`

**Comment by dianamartin** [comment]
# 8/28
- [ ] Built out pages for New Work Order Inspectors
- [ ] Built out pages for Work Order - Inspectors
- [ ] Built out pages for Edit Work Order - Inspectors
- [ ] Built out pages for Work Order - Inspectors Details page
Built this out with the Signal Engineering work orders as a reference because that's what Brian C's ask. He had similar goals in his previous request.

**Comment by susannegov** [comment]
# 9/25 Meeting
Need mobile friendliness. Currently people are assigned by specialties, but that process is being reviewed (primary/secondary/geographic?).

Need information to decide on whether travel time should be included in time log. Don't include travel time. The goal is to decide what to track.

## Edit Work Order
- Has a time log and leave site
- Work Performed Inspectors (make it multi-select?)
   - "Conduct meeting with contractor" and "Field Check" happen at same time 
   - Want to include 6 to 12 different multichoice
## Work Order Details | Inspectors
Ask what they want to track. 
- Need pole numbers field for inspection form since most inspectors just write down the pole number not the location
- Asset Type: Can be all assets
- Location ID
- Photo attachment (optional) from the work order (not from inspector)
- There is 1 inspector is assigned per project. If a person is missing (vacation/sick/etc.), they would re-assign to a different person

How to fit this into the contractor work tickets and the inspection section

Two different process for contractor and non-contractor projects
- Development contractor process

From stakeholders: Is it possible if we asked to fill out a daily log page, and in that time log for that day and push it to appropriate work order project or to Moped? 
- Example: for today, a table view that captured logs of these groups of people doing at a particular day

**Comment by ChristinaTremel** [comment]
# 9/25 Reviewing Work Order | Inspectors 
- Add Moped ID to the work order
- When doing an inspector work order, which assets would they normally navigate to?
   - Include all asset typesj
- Once submitting the work order, we've built it to auto close the work order but it doesn't have to do that. Just depends on what your goals are.
- BC would like to see attachments on the work order for taking pictures during the inspection.
- One master project ticket with time logs to track when they go there vs separate work orders for each timeshot
   - BC and Julian are leaning on having a work order for an overall project
- Work distribution is getting reassessed right now:
   - When Chris was working on assigning work, they would all have an area but realized that didn't work
   - Once you're assigned a project, it's usually one inspector per project
   - If someones on vacation, there might be a substitute - so maybe that person is an Assisting Technician 
- **Goal of the work orders:** To track how many locations inspectors are going to, how many projects they are inspecting total, and to start collecting data on velocity of work for labor/inspecting.
- **Work Performed Inspectors**
- Ben noted that there are going to be additional drop downs on the Work Performed
   - Research
   - Field Check
   - Conduct Meeting with Contractors
   - Conduct Meeting with Austin Energy
- **Types of work orders for the inspectors**
   - Contractor Work Orders
   - Inspecting other peoples work (developments)
   - Inspecting TxDOT signals
   - AMD Internal Projects
   - Knock down inspection tickets (maintenance work order)

**Comment by ChristinaTremel** [comment]
- Discussed in the sprint review and Ivonne had discussed with Brian. Need to decide the direction of the ticket: if it's for work logs or if it's linked to higher level projects. This is partially on hold.

**Comment by susannegov** [comment]
@ChristinaTremel Good to put this is backlog 👍

**Comment by ChristinaTremel** [comment]
Brian C has asked that we revamp this request and look at creating a super basic MVP for AMD inspectors to incorporate completing tickets in the field. I'm going to close out this initial issue of scoping the inspector work order form and 
- Will capture notes for the MVP in #19094
