### ISSUE TITLE
Add "Work_Location_Other" field back to New Work Order Form and add rule to move work order in-progress

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#12258]
# Still need to do these, creating new issues for these items: 

- [x] Re-add the open text field when selecting the Asset Type = `Other`
- [x] Currently no way to move work order into "In Progress" without closing the work order and reopening. Need to create rule when Timelog is added, change status to “In Progress”

_Originally posted by @ChristinaTremel in https://github.com/cityofaustin/atd-data-tech/issues/11855#issuecomment-1542889880_

**Comment by dianamartin** [comment]
# 5/10
Synced with Christina and we worked on this issue0

## Need to add "WORK_LOCATION_OTHER" to New Work Order forms
- old name: `Work Location (if not at a signal intersection)`
- new name: `Work Location | Other - if not an asset location`

WORK_LOCATION
- has a conditional rule, if no location = WORK LOCATION
- if, Location Other = WORK_LOCATION_OTHER

## TROUBLE CALL NEW WO FORM
- [x] Added field WORK_LOCATION_OTHER
- [x] Added rule WORK_LOCATION_OTHER
- [x] Modified rule for SIGNAL

## SCHEDULED WORK NEW WO FORM
- [x] Added field WORK_LOCATION_OTHER
- [x] Added rule WORK_LOCATION_OTHER
- [x] Modified rule for SIGNAL

## EDIT WORK ORDER FORM - Signals
- [x] Added field WORK_LOCATION_OTHER
- [x] Added rule WORK_LOCATION_OTHER
- [x] Modified rule for SIGNAL

## EDIT WORK ORDER FORM - Non-Technicians
- Already existed

## EDIT WORK ORDER FORM - Communications
- Already existed

## EDIT WORK ORDER FORM - My Work Order
- [x] Added field WORK_LOCATION_OTHER
- [x] Added rule WORK_LOCATION_OTHER
- [x] Modified rule for SIGNAL

Christina tested by creating a new scheduled work, work order, and then checking under "My Work Orders"

**Comment by dianamartin** [comment]
# 7/13
Christina scheduled some time to talk the stakeholders about this on Tue, 7/18

**Comment by ChristinaTremel** [comment]
## 7/18
- Met with stakeholders and determined that we would like to set up rules on these tables within work order details - if there are any records, it moves the work order to `IN PROGRESS`
   - Time Log
   - DOSA
   - Scheduled Work

**Comment by dianamartin** [comment]
# 8/2
Use these work orders to move into "In Progress"
- [ ] `WRK22-166545`
- [ ] `WRK22-162940`

**Comment by ChristinaTremel** [comment]
# 8/22 Testing in progress status
### EDIT WORK ORDER FORM - My Work Order
- Testing the in progress status trigger with existing test WO: WRK22-137560
   - WO currently assigned to Test Tech and in the `Assigned` status
   - Added Timelog entry to WO and the WO status updated to `In Progress`
   ![image](https://github.com/cityofaustin/atd-data-tech/assets/61209591/166d6804-12b2-49af-83d8-51a01f82ebb2)
   - Tested that when everything is filled out and I submit the work order, the work order status is updated to `Submitted`

### EDIT WORK ORDER FORM - Non-Technician
- Testing the in progress status trigger with existing test WO:

### EDIT WORK ORDER FORM - Communications
- Testing the in progress status trigger with existing test WO: WRK23-185780
   - WO currently assigned to Christina and in the 'Assiged' status
   - Added Timelog entry to WO and the WO status updated to 'In Progress'
   ![image](https://github.com/cityofaustin/atd-data-tech/assets/61209591/9e4e80e0-d866-4f80-a4c0-05f1d1d9abcd)
   - Logged in as myself so I could close work order and WO status updated from `In Progress` to `Closed`

### EDIT WORK ORDER FORM - Engineers
- These work orders won't go into the `In Progress` status because when the ticket is filled out, the work order is immediately `Closed`

**Comment by ChristinaTremel** [comment]
@dianamartin I've tested the various types of work orders and the `In Progress` status is working as expected! 👏

**Comment by dianamartin** [comment]
# 8/22
Update in Production

## New Record Rule
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/31975837-71cb-47a9-bdec-0df2c01c0a89)

Added new record rule"
    - **Update connected record** - `work order signals`
    - `IN_PROGRESS` is `1`

### EDIT WORK ORDER FORM - My Work Order
- [ ] Time Log -->only audit field rules - MODIFIED BY/DATE. 
  ### EDIT WORK ORDER FORM - Technicians
- [ ] Time Log
>only have "Non-Editable" Time Logs
### EDIT WORK ORDER FORM - Non-Technicians
- [x] Time Log

### EDIT WORK ORDER FORM - Communications
- [x] Time Log

### EDIT WORK ORDER FORM - Engineers
- [x] Time Log

**Comment by dianamartin** [comment]
# 8/23
@ChristinaTremel This is complete.
- [x] Added Record Rule to all "Add Time Log" forms (as referenced above)

**Comment by dianamartin** [comment]
# 10/27
We forgot to close this on 8/23
