### ISSUE TITLE
Updated user role permissions, Shelby S. (TED)

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#12267]
Shelby 
TED

Messaged 5/11
>Hello! I suddenly do not have access to "Manage Requests" under the data collection Knack. Do I need to submit a ticket somewhere? for this app: https://atd.knack.com/amd#traffic-count-traffic-data-requests/manage-requests/

**Comment by dianamartin** [comment]
# 5/11
I replied
>let me take a look
I know you were showing up as Smart Mobility and we switched you to TED. You didn't have the "Traffic Count Editor" role, but by the looks of it you never had it...? I could have sworn I gave you that before

We synced really quickly
- [x] Checked record audit and she did not have "Traffic Count Editor" roles, like Jamie and Ray
- [x] I gave her "Traffic Count Editor" user role
- [x] She refreshed and saw she had access
