### ISSUE TITLE
Add new CSR action "Storm-Related"

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#12268]
> What application are you using?

Data Tracker

> Describe the problem.

New CSR action "Storm-Related"

> Describe the outcome you'd like to see when this feature is implemented.

New CSR action "Storm-Related"

> Describe any workarounds you currently have in place or alternative solutions you've considered.

None

> Is there anything else we should know?

N/A

> Requested By
Allyson R.

Request ID: DTS23-107845

**Comment by ChristinaTremel** [comment]
Find out from Allyson which drop down list they want us to add `Storm-Related` to.

Screenshot:

**Comment by susannegov** [comment]
# Notes
The drop down list is from: `/pages/scene_512/views/view_1444/form/inputs/rows/0/columns/0/inputs/2`
Field name is `ISSUE_TYPE_MANUAL_CREATE` in the `tmc_issue` object

**Comment by susannegov** [comment]
@ChristinaTremel new CSR action has been created and old action was removed. 

Question - Does the field `ISSUE_TYPE` also require creating a multiple choice option for `Storm-related` as well? See previous comment.

**Comment by ChristinaTremel** [comment]
@susannegov I think the other field `ISSUE_TYPE` is the issues that come from 311 so I don't think you need to create the storm related issue there! 

@dianamartin could you confirm?

**Comment by dianamartin** [comment]
@ChristinaTremel cc @susannegov that's correct, that's the official Issue Types from 311. Only touch the field listed with the "Manual" label.

**Comment by ChristinaTremel** [comment]
@susannegov I think this was my misunderstanding, but Allyson is asking for `Storm-Related` to be added as an Activity Type instead of an Issue Type.
![image](https://github.com/cityofaustin/atd-data-tech/assets/61209591/28b1089e-977c-4eab-8b2b-c0637032d6a7)

So sorry, but we need to make the following changes to complete this issue:
- [ ] Remove `Storm-Related` as an **Issue Type**
- [ ] Add `Storm-Related` as an **Activity Type**

**Comment by susannegov** [comment]
@ChristinaTremel Does this mean I need to re-add "Signal on Flash - Storm" on the issue type?

**Comment by ChristinaTremel** [comment]
@susannegov I checked with Allyson and she would like to go ahead and keep that removed. And any issues that are currently set as `Storm-Related`, update to the general `Signal on Flash` issue type!

**Comment by susannegov** [comment]
# To do
- [ ] Set `ISSUE_TYPE_MANUAL_CREATE` = `Storm-Related` to `Signal on Flash` (65 records)
- [ ] Remove `Storm-Related` choice option from `ISSUE_TYPE_MANUAL_CREATE`
- [ ] Add `Storm-Related` as an Activity Type field

**Comment by susannegov** [comment]
@ChristinaTremel this is done!

**Comment by ChristinaTremel** [comment]
Let Allyson know:
> Storm-related has been removed as an issue type and added as an activity type!
