### ISSUE TITLE
Enhance the reimbursable process in SMD Data Tracker

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#12261]
# SMD requesting enhancements to the reimbursable process to improve efficiencies:

### 1. New feature to add to the reimbursable details page:
- [x] Button to modify FDU on the work order

### 2. New “Approve Invoice” page for the Requesters
- If “Send Invoice to Requester” is yes, add to table of invoices to be approved by requester
   - Make table viewable to the list of Requesters that can approve (Ramona will follow up on who should review invoices)
- Table of invoices that have date
   - Table similar to what we see on the reimbursable side and have a link to invoice details and link to work order details

### 3. New Fields to add to the reimbursable object table:
- New field `Contractor ID`
- New field `Send to Requester`
- New field `Invoice Approved` - yes/no field

### 4. New “Reimbursable Reporting” Page: that reflects the fields that Ramona reports on
- See FY23_InvoiceBatches spreadsheet for details
- Add advanced search features to search by Batch No

> Describe the outcome you'd like to see when this feature is implemented.

The enhanced reimbursable process will improve efficiencies.

> Describe any workarounds you currently have in place or alternative solutions you've considered.

Currently performing certain functions manually.

> Requested By
Cathy K.

[Attachment](https://api.knack.com/v1/applications/595d00ebd315cc4cb98daff4/download/asset/645d12670563860028412c91/fy23_invoicebatches.xlsx) (2.13mb)

Request ID: DTS23-107835

**Comment by ChristinaTremel** [comment]
Goal is to have these changes implemented starting the new FY. 

Split this request into 3 separate requests.

**Comment by dianamartin** [comment]
# 5/3
Christina and I synced and she's going to split the issue. I completed # 1 on the task list
- [x] Added a new menu page on Signs and Markings Invoice details page
- [x] Added an update form on each new page
- [x] Configured the form
- [x] Tested the form on both pages

**Comment by ChristinaTremel** [comment]
- Add Review Invoice option for "Approve with FDU or TK Change" 
   - Point directly to the TK and FDU field
- Turn `Sent to Finance` field into a trigger that captures a `Sent to Finance` date
- Stays into the `Approved` status until the invoice is `Approved by Finance`
- Might want to talk to finance to see if they would be open to changing the process of sending invoices

**Comment by ChristinaTremel** [comment]
Closing this epic because these initial changes to Ramona's part of the reimbursable process have been completed! 
- Working on additional enhancements to the finance process on #17228
