### ISSUE TITLE
Update "Service Request" page on DTS Portal with new TPW divisions and applications

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#12271]
Perform a large number of updates to the DTS Service Request workflow to reflect new+modified TPW [workgroups](https://docs.google.com/spreadsheets/d/1BsOklJsJiIIqdlmtNtr9peL3URS7Hdu9RVj4D97701k/edit#gid=968067157) and [applications](https://docs.google.com/spreadsheets/d/1BsOklJsJiIIqdlmtNtr9peL3URS7Hdu9RVj4D97701k/edit#gid=1546625311).

---
 _(Initial request)_
Need to update the applications list and divisions list

## New Divisions (missing from current list)

No | Divisions & Programs | Action | Comment
-- | -- | -- | -- |
1 | Active Transportation & Street Design | Already exists
2 | Arterial Management | Already exists
3 | Data & Technology Services | Already exists
4 | Finance & Administration | Already exists | Change to "Finance"
5 | Human Resources | Already exists
6 | Office of Special Events | Already exists
7 | Office of the Director | Already exists
8 | Parking Enterprise | Already exists
9 | Parking Meters | Already exists | Change to "Parking Services"
10 | Project Delivery | Already exists
11 | Public Information Office | Already exists
12 | Right-of-Way | Already exists
13 | Shared Mobility Services | Already exists | 
14 | Signs & Markings | Already exists
15 | Smart Mobility Office | Already exists
16 | Systems Development | Already exists
17 | Transportation Development Services (TDS) | Already exists
18 | Transportation Engineering | Already exists
19 | Vision Zero | Already exists
20 | Other | Already exists
21 | Architectural Project Management | REMOVE | 6/8: JW said this isn't a division
22 | Community Services  | New
23 | Office of the City Engineer | New
24 | Office of the Performance Management | New
25 | Safety Office | REMOVE |  6/8: JW said this isn't a division, but a part of HR
26 | Sidewalks & Special Projects | New 
27 | Street Bridge Operations | New
28 | Equity | REMOVE |  6/8: JW said this isn't a division
29 | Urban Forestry | New
30 | District Maintenance | New
31 | Utilities and Structures | New
32 | Pavement Operations | New
33 | Strategic Projects Program | New | 6/8: JW asked we add "Program" to the end
34 | Strategic Communications & Outreach Program | New | 6/8: JW asked we add "Program" to the end
35 | Corridor Program Development Program | New | 6/8: JW asked we add "Program" to the end
36 | Logistics | New
37 | Asset Management | REMOVE | 6/8: JW said this is still forming and won't be active for at least another year
38 | Mobility Services | New, bc we have Parking Meters and Shared Mobility Services
39 | Enforcement Services | New, bc we have Parking Meters and Shared Mobility Services
40 | Land Development Engineering |  | New division coming from DSD

### Name Changes
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/91af6c5c-3424-486f-95a1-c5be8efa4b69)

#### New Application Name additions
- [ ] Add `Maximo`
- [ ] Add `Smart Mobility Office Portal` (would include P3, Artbox, and MetroBike)
- [ ] Add `Traffic Register`
- [ ] Add `DTS Portal`

**Comment by amenity** [comment]
Thanks, @dianamartin! I don't know that our customers will realize when they're using "ATD Forms "or that the take-home equipment is on the "DTS Portal." & Let's talk IRL about "TPW Interview," since I have no idea what it is? 

We'll also want to add labels to the `atd-data-tech` repo for all these new workgroups and update the script to assign those labels. With that in mind, it would be good to get @maccallump's eye on this list to ensure it's as inclusive and stable as can be reasonably expected these days. 🙃

**Comment by amenity** [comment]
@amenity - update table to include labels

**Comment by amenity** [comment]
@amenity - we also need an issue to update the URGENT email recipients in the bot script.

**Comment by amenity** [comment]
We need a plan of action - step-by-step how to perform these updates while keeping the wheels on the train
- DTS Portal / Knack 
- [ATD Data & Tech Services Issues](https://data.austintexas.gov/Transportation-and-Mobility/ATD-Data-Tech-Services-Issues/rzwg-fyv8)
- DTS Website

**Comment by mddilley** [comment]
Dropping some notes and links that I gathered for the meeting on Monday.

**Code:**
1. Update divisions - [config](https://github.com/cityofaustin/atd-service-bot/blob/78f047bb5695e0ca09936ab6e34e759255e737f7/config/config.py#L93-L120)
4. Update and rename applications - [config](https://github.com/cityofaustin/atd-service-bot/blob/78f047bb5695e0ca09936ab6e34e759255e737f7/config/config.py#L172-L193)
5. Update urgent email recipients [config](https://github.com/cityofaustin/atd-service-bot/blob/78f047bb5695e0ca09936ab6e34e759255e737f7/config/config.py#L221-L234)

**Docs should cover:**
- diagrams of the three scripts and the tech they use
   - Intake (Knack service request records created through SR form -> Github issues)
   - Issues to Socrata (GitHub & Zenhub -> Socrata)
   - Create or update Index issues (GitHub -> Knack)
- coordinating updates

**Comment by dianamartin** [comment]
# 6/3
## Action Items
- @mddilley Will explore FormStack >GitHub
- @amenity Add new labels to GitHub (missing divisions)

**Comment by amenity** [comment]
@dianamartin - can you peep the latest org chart and/or touch base w/ Jennifer to see whether we can consider these the "final" divisions?

**Comment by dianamartin** [comment]
# 6/8
- Pinged Jennifer on teams
>DTS is working on updating their Service Request form and we were going to update the divisions, but then realize that it still might be inlfux. Can you take a look at this [issue](https://github.com/cityofaustin/atd-data-tech/issues/12271) to see if these are the right division names? It was from the original TPW Org Charts that we worked on (earlier version).

>We're just trying to get confirmation on division names and hope it's 80-90% finalized and those won't change before we make this huge effort

**Comment by amenity** [comment]
[Here's a Slack convo](https://austininnovation.slack.com/archives/CPGC2L4QZ/p1686319204536369) on what to do w/ _[Workgroup: ATD](https://github.com/cityofaustin/atd-data-tech/labels/Workgroup%3A%20ATD)_ and _[Workgroup: PWD](https://github.com/cityofaustin/atd-data-tech/labels/Workgroup%3A%20PWD)_ labels.

**Comment by amenity** [comment]
Scheduled a meeting for next Monday, 7/3, to create an implementation plan.

**Comment by amenity** [comment]
Prework: 
- [ ] Amenity update mappings [here](https://docs.google.com/spreadsheets/d/1BsOklJsJiIIqdlmtNtr9peL3URS7Hdu9RVj4D97701k/edit#gid=968067157)
- [ ] Amenity write a maintenance outage message for DTS Service Portal
- [ ] Amenity schedule meeting 
- [ ] Mike create PR 

Day-of:
- [ ] Apps add banner on Service Request page with ☝🏻 text and hide form
- [ ] Mike update code ([Applications](https://docs.google.com/spreadsheets/d/1BsOklJsJiIIqdlmtNtr9peL3URS7Hdu9RVj4D97701k/edit#gid=1546625311), [Divisions](https://docs.google.com/spreadsheets/d/1BsOklJsJiIIqdlmtNtr9peL3URS7Hdu9RVj4D97701k/edit#gid=968067157))
- [ ] Apps update choice values on Divisions ([Applications](https://docs.google.com/spreadsheets/d/1BsOklJsJiIIqdlmtNtr9peL3URS7Hdu9RVj4D97701k/edit#gid=1546625311), [Divisions](https://docs.google.com/spreadsheets/d/1BsOklJsJiIIqdlmtNtr9peL3URS7Hdu9RVj4D97701k/edit#gid=968067157))
- [ ] Amenity update Github labels ([Applications - Products](https://docs.google.com/spreadsheets/d/1BsOklJsJiIIqdlmtNtr9peL3URS7Hdu9RVj4D97701k/edit#gid=1546625311), [Divisions - Workgroups](https://docs.google.com/spreadsheets/d/1BsOklJsJiIIqdlmtNtr9peL3URS7Hdu9RVj4D97701k/edit#gid=968067157))

**Comment by dianamartin** [comment]
@amenity @mddilley 
@adry-martinez said that she saw that  "Pavement Operations" is missing from the workgroup list. @mddilley was that added to the script already? if so, can I just add the choice in Knack. Do we think it'll break?

**Comment by chiaberry** [comment]
it is in the script
https://github.com/cityofaustin/atd-service-bot/blob/production/config/config.py#L118

**Comment by amenity** [comment]
We have a label for it, too.
