### ISSUE TITLE
Finance App Review/Testing Meetin 5/17/23

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#12305]
### Meet and take notes
-

**Comment by ChristinaTremel** [comment]
### Create resulting issues/things to follow up on
**Admin Table View of Service Requests**
- [ ] Remove  `Search Service Requests Jobs` page and create new reporting page
- [x] Create `Advanced Search` page for the jobs information - Created issue #12310
- [x] Create `My Service Requests` page - Created issue #12311

**Admin View of Service Request Details**
- [ ] On "Change Status/Assignment" button, add rule where if assigned to is not blank, update `Status` to `In-Progress`.
- [ ] For Other Service Request types, Sharon needs to provide attachments. Noting that she could override attachments and that would work for Sharon. Would like to notify the Requester when attachments are replaced.
- [ ] Add a Button to `Complete` work orders when they are in `Waiting for Approval`

**Requester View of Service Request Details**
- [ ] Add information at the top of "Service Request Details" page, note that Requester should review information and click "Submit"

**New Service Request Page**
- [ ] Update Added Service Requests Jobs on the "Add Job" form from the "New Service Request"

**Updating Fields for SR Jobs**
- [ ] Rename `Parent FDU` field to `Parent FDU No.`
- [ ] Rename `Funding Source FDU` field to `Funding Source FDU No.`
- [ ] Add what section of the TK to the name
- [ ] Look at form rule for job type other (attachment still showing IET attachment)
- [ ] Check with Charlie if the `Existing Subproject No.` field is being automatically updated

**Email Notifications**
- [x] Update completed email sent to Requester for when the Service Requests are in the `Complete` status - Added this to #11672

**Comment by dianamartin** [comment]
# 5/17
## On Offs
- [ ] For Other Service Request types, Sharon needs to provide attachments. Noting that she could override attachments and that would work for Sharon. Would like to notify the Requester when attachments are replaced.
- [ ] Review the fields added for Finance to fill out (on Admin Details page) and ensure they all have modified date/modified by

## Requester Page
- [ ] Add information at the top of "Service Request Details" page, note that Requester should review information and click "Submit"
>Add "yellow" banner to instruct employees on what to do (reference: SMRT provider application or Street Banner application?)
- [ ] Add fields that Finance will fill out on to the Requester side for viewing purposes
>Customer SR Details page (add highlighted fields to the tables)
- [ ] Copy Service Requests Jobs tables on the "Add Service Request Job | Admin" form from the "New SR Job" Button
- Copy Service Requests Jobs tables on the "Add Service Request Job | Admin" form from the "New SR Job" Button
  - Copy all tables from the Customer "New Job" Page
  - remove "Delete" trigger, replace with default "Delete"
  - remove "Source filter" that is "is_deleted" field

- [ ] Do the same for ADMIN | New SR Job!!!!
- [ ] Field Updates #12312 
- [ ] Validation #11487
- [ ] Email Notifications #11612
