### ISSUE TITLE
Requested Modifications following Training Tracker Review on 5/18

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#12327]
Cathy's Requested Updates During #12318

### New Field Requested
- [ ] Current IMSA Credit Hours
   - IMSA needs to have 16 credits of training to be recertified in the last 3 year period
   - Any class after "Latest IMSA Certification Date", where attendance status is `Completed` and where "IMSA Eligible Hours" is `Yes`
   - Add this field to Participants Details Page and to a Reporting Page
   - Boolean to flag that a recertification has been reached
 
### Fields to be Renamed
- [ ] Rename Enrollment Status from `Cancelled` to `Unenrolled`

### [Participants Table](https://atd.knack.com/signs-markings#training-tracker/participants/)
- [ ] Add column that shows Current IMSA Credit Hours
- [ ] Change the IMSA Certification Expiry Date Colors from the text color to the background color

### [Participants Detail Page Changes](https://atd.knack.com/signs-markings#training-tracker/participants/participant-details/642b2d2c6538260027766614/)
- [ ] Filter only `Enrolled` and `Completed` trainings under the IMSA Eligible tab
- [ ] Remove "Last Modified By" on trainings table

### [Training Details Page](https://atd.knack.com/signs-markings#training-tracker/training-details/64667dfed0944d0028e693f2/)
- [ ] Add "IMSA Membership Number" and Participants List table

**Comment by KaroEngstrom** [comment]
# F 5/19/23 

- talked about the IMSA eligible hours completed count for current certification period during App Sync
- have that part built to the point of having an accurate ALL IMSA eligible hours completed count for the Participant but need to work on a solution to filter down to current cert period (since the last certification date; not a foolproof timeframe but should work for this build)

**Comment by KaroEngstrom** [comment]
# T 5/23/23

- final bit: updating the [My Trainings](https://atd.knack.com/signs-markings#my-trainings/) view to mirror the details the admin sees on the Participants page so that the users will be able to see the hours completed and accumulated towards their re-certification as well.

**Comment by KaroEngstrom** [comment]
@ChristinaTremel - putting this is QA
We have the asks completed here. There is no reporting page yet, though, as that's not been part of the MVP.
