### ISSUE TITLE
Create Asset Tracking Module in the DTS Portal

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#12335]
Matt M. 
DTS

We (Matt, Scott and I) all talked and thought this might be a good way to start tracking our assets that we track. 

Categories:
- PWD
- ATD
- CPO

We were going to replicate the MS Form that the SIM group used and import the asset list from FileMaker. 

# Form Requirements 
(formerly called PWD IT Inventory Update Form)

### LAPTOP
  - Computer Name
  - COA Tag
  - Service Tag
  - Model
  - Ship Date
  - Expiration Date
  - Previous User
 - Current User

### MIFI
 - Serial Number
 - IMEI
 - ICCID
 - Phone Number
 - WAP Name
 - Pin/MiFi Password
 - Previous User
 - Current User

### IPADS
 - COA Tag
 - Serial Number
 - IMEI
 - ICCID
 - Phone Number
 - User Pin

### Additional Equipment 
  - docking station,
  - keyboard/mouse, etc. 

### Permanent New/Loaner New/ PC Refresh - Replace on Failure
  - Permanent
  - Loaner (laptop, swapped out after PC refresh)
  - PC Refresh
  - Other - "open text"

### Location
- OTC
- BTC
- St. Elmo
- Kramer Ln
- Harold Ct
- Dalton Ln
- Other - "open text"

### Software Installed
- FileMaker
- Adobe DC
- Bluebeam
- MS Project
- Adobe Creative Suite
- MS Visio
- PowerBI
- AutoDesk/CAD
- Other - "open text"

### Additional Information
- Information/Notes

**Comment by dianamartin** [comment]
# 5/19 
- worked on this
- [x] Created new object `asset_management`
- [x] Created new page `Hardware Management`
- [x] Added a new asset form 
- [x] Created new page `Manage Hardware` - has table of assets

**Comment by dianamartin** [comment]
We've made some tweaks as Matt, Scott and Strange are testing. Closing, due to module being created and maintained now.
