### ISSUE TITLE
Fleet Management page creations for "Manage Vehicles" and "Add Vehicle Form"

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#12344]
## Page creation
- [x] Create new page called "Manage Vehicles" (Enable log in - only `System Administrator`, when building in Prod)
Remember to un-check this (when building in Prod)
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/176003c2-91fb-4b85-8e64-be1c1264e25a)
- [x] On this page, create new "menu", to create a new page `Add Vehicle`
   - Add Vehicle `fa-plus` icon button menu
- [x] This page, add a new form that allows you to add a new vehicle (reference this [page](https://builder.knack.com/atd/signs-markings/pages/scene_1246/views/view_3088/form/rules/submit) in SMD 
   - [x] Submit Rules - Redirect to Parent Page
![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/9bf33a28-02d7-4542-80cc-46c419c2402a)
- Include on form
- [x] Vehicle ID (required) (Must be unique)
- [x] Make (required)
- [x] Vehicle Name (required)
- [x] Year (required)
- [x] Work Group (required)
- [x] Category (required)
- [x] In Service Date (required)

![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/dd01fe5e-a5fc-4d73-a414-89324420df26)

## Table Creation
- [x] Add table that has the following field, see reference below
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/acb956b2-224c-41a0-a251-313e8ca09f1f)
- [x] Sort VEHICLE ID from A to Z

### Columns
- Details: Page to link to `View Fleet Vehicle Details`
- Vehicle ID: `VEHICLE_ID`
- Year: `VEHICLE YEAR`
- Model: `VEHICLE_MAKE`
- Name: `VEHICLE_NAME`
- Display Name: `VEHICLE_DISPLAY_NAME`
- Status: `VEHICLE_STATUS`
   - Display Rule
![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/d6d59bfb-96c2-4ca9-98b3-3a4989c291eb)
 
- Work Group: `Business Unit`
- Category: `Category`
- In Service Date: `IN SERVICE DATE`
- Edit: Page to link to `Edit Vehicle`

### Options
- Keyword Search
   - The fields being used by the view
- Record Exporting
- Hide empty columns
- Empty Grid Text: No Data

### Pagination
- Display 25 records by a time
- Let the User Change the amount
- Repeat pagination controls below the view 

### Filters
- Use a filter menu (All vehicles filter shown twice?) 
   - [x] VEHICLE ID is not Blank = All Vehicles
   - [x] Category is Vehicle = All Vehicles
   - [x] Category is Equipment = All Equipment
   - [x] VEHICLE STATUS does not contain In Service = Out of Service

### Title and Description
`<i class="fa fa-truck"></i> Vehicles`

**Comment by susannegov** [comment]
@dianamartin @ChristinaTremel This is ready for review/qa in the test environment. Currently not building in prod. If it looks good, when should I start building in Prod?

**Comment by susannegov** [comment]
# 5/31 
- Changed Add Vehicle form to be "show up in modal pop-up" similar to SMD app
- Added "Arterial Management" to filter menu where `BUSINESS UNIT IS ARTERIAL MANAGEMENT`

**Comment by dianamartin** [comment]
# 6/7

Showed users the prototype in Test, they had some minor changes under the "Manage Vehicles" table. Closing, will re-create for PROD build.
