### ISSUE TITLE
Update "Journal Voucher" info in AMD Data Tracker - Warehouse Inventory- June 2022

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#12348]
- [x] Spreadsheet emailed from Finance staff month of: June 21, 2023
- [x] Number of records being updated: 667
- [x] Format spreadsheet [(Review instructions)](https://atd-dts.gitbook.io/atd-knack-operations/warehouse-inventory-updating-journal-vouchers-jv-information)
- [x] Spot check Transaction IDs, no JV information before import
- [x] Import records
- [x] Spot check Transaction IDs, no JV information after import
- [x] Email Finance staff that update task complete

**Comment by ChrispinP** [comment]
667 records updated successfully without issue with a Journal Voucher Date of 06/21/2023.

Emailed finance, pending closure

**Comment by ChrispinP** [comment]
No further action, closing
