### ISSUE TITLE
Fleet Management "Edit Vehicle Form" page and "View Fleet Vehicle Details" page creation of new fleet menu

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#12345]
## Pages layout
![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/75e27454-24df-4138-bd60-9f1f724105e0)

## Build Edit Form
- [ ] Reference [page](https://builder.knack.com/atd/signs-markings/pages/scene_1229)
![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/53115e1f-ee95-4e1b-b1f6-5729ea825906)
- [x] `VEHICLE_ID` = Vehicle ID
   - Display the field value without a form input
- [x] `VEHICLE_MAKE` = Make
   - Allow users to add new options to choose.
- [x] `VEHICLE_NAME` = Name
    - Allow users to add new options to choose.
- [x] `VEHICLE_YEAR` = Year
- [x] `VEHICLE_STATUS` = Status
- [x] `BUSINESS_UNIT` = Work Group
- [x] `Category` = Category
- [x] `IN SERVICE DATE` = In Service Date
- [x] Submit Rule = Redirect to Parent page
- [x] Record Rules `MODIFIED BY` to the current logged in Account and `MODIFIED DATE` to the current date

## Build Details page
- [ ] Reference [page](https://builder.knack.com/atd/signs-markings/pages/scene_1421)
![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/462054b6-63fc-4f6b-8471-cd447f3ac768)

# Next Sprint
## Build Vehicle Log tracking
- [ ] Reference [page](https://builder.knack.com/atd/signs-markings/pages/scene_1422)

## Build Add Vehicle Note
- [ ] Reference [page](https://builder.knack.com/atd/signs-markings/pages/scene_1428)

**Comment by amenity** [comment]
#12345 😎 @ChristinaTremel 👏🏻

**Comment by ChristinaTremel** [comment]
# 5/31
Reviewed the work done on #12344 and we're ready to continue building out the vehicle details page and edit vehicle form in Test.

**Comment by susannegov** [comment]
# Build Notes - View Fleet Vehicle Details page
## Details view
![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/d451afd3-a81d-4baf-886e-a654f58cf4bc)
### Settings
- [ ] No, show all fields
- [ ] Left aligned
- [ ] Layout = box 
![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/c3baace4-5817-470b-8453-6c922880933b)
- [ ] Title =  View Fleet Vehicle Details

### Add Details
- [ ] `VEHICLE_STATUS` = Status
- [ ] `VEHICLE_ID` = Vehicle ID
- [ ] `VEHICLE_NAME` = Name
- [ ] `VEHICLE_MAKE` = Model
- [ ] `BUSINESS_UNIT` = Work Group
- [ ] `Category` = Category
- [ ] `Accounts > CREATED_BY` = Created By
   - [ ] Connection Link = No Link
- [ ] `CREATED_DATE` = Created

### Rules
None

## Menu View
![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/d937d779-6189-4b6d-b225-f445fd23eb61)

**Comment by susannegov** [comment]
# Add Vehicle Log Form page
Name: Add Vehicle Log
Page URL: add-vehicle-log
Display page in a modal popup
No page rules
## Form view
WIP
### Settings
### Add Inputs
### Rules
### Emails
# Add Vehicle Note Form page
Name: Add Vehicle Note
Page URL: add-vehicle-note
Display page in a modal popup
No page rules
## Form view
WIP
### Settings
### Add Inputs
### Rules
### Emails

**Comment by susannegov** [comment]
# 6/1 Build Notes (WIP)
- In Edit Vehicle form there ia an "Add a new option" for `Make` and `Name` but not for the Add Vehicle form. Should both of them have the "Add a new option"?

**Comment by susannegov** [comment]
# 6/5 
Reviewed AMD TEST environment w/ Diana 
- Add Vehicle Form > Options
   -  `Make`
      - Add a new option
   - `Vehicle Name`
      - Add a new option
- The display rules that are blank for `Add Vehicle Form` and `Add Vehicle Notes` are not in SMD app PROD so the blank display rules are not needed.
    - Let user change amount for Vehicle Logs table view in the detail page
    - Diana deleted `OUT - PM`, `OUT - UNSCHEDULED` and `IN SERVICE` are deleted in SMD production as not needed

**Comment by dianamartin** [comment]
# 6/7
Showed users the prototype in Test, they had some minor changes under the "Manage Vehicles" table. Closing, will re-create for PROD build.
