### ISSUE TITLE
Fleet Management object modification and creation of new object table: fleet_vehicle_tracking

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#12343]
### Modifying object `fleet_vehicles` object [(/object_73)](https://builder.knack.com/atd/amd/records/objects/object_73)
- Add Fields
- [x] `VEHICLE_YEAR` - _Number_
- [x] `VEHICLE_STATUS` - _Multiple Choice_ (Already exists)
  - Add/Change choices: examples
  - [x] In Service
  - [x] Out of Service - Preventative Maintenance
  - [x] Out of Service - Unscheduled Issue
  - [x] Out of Service - Retired
- [x] `IN SERVICE DATE` - _Date/Time_ (Ignore Time, Default Date None, Just Use Simple Date/Time)
- [x] `Category`
  - [x] Vehicle
  - [x] Equipment
- [x] `VEHICLE_MAKE` - _Multiple Choice_ (Already exists as "VEHICLE_MODEL" - short text)
  - Add/Change choices: From the SMD Test Options
```
Autocar
Chevrolet
Dodge
Downing
Ford
GMC
Graco
MB
Pace America
Peterbilt
Smith Comp
South West
Toyota
Trantex
Unknown
```
  - [x] All the choices on the drop down (export the `fleet_vehicles` list
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/e74afba3-dc2a-4ba4-86af-d7378113f1ab)

### Create new object table: `fleet_vehicle_tracking`
- [x] Create a new table using this reference
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/ceaebaaa-f1bf-4796-9428-0fb9f8f0a3d5)
- Add Fields
- [x] `fleet_log_ID` - _Auto Increment_
- [x] `fleet_vehicle` - _Connection_ (Each fleet_vehicle_tracking connects with one fleet_vehicle/Each fleet_vehicle connects with many vehicle_trackings)
- [x] `Created By` - _Connection_ to Account object
- [x] `Created Date` - _Date/Time_ (Ignore Time, Default Date None, Just Use Simple Date/Time)
- [x] `Modified By` - _Connection_ to Account object
- [x] `Modified Date` - _Date/Time_ (Ignore Time, Default Date None, Just Use Simple Date/Time)
- [x] `Action` - _Multiple Choice_ (Required, Sort Custom, Radio Buttons, Default Option Blank): Below is from SMD Test options
```
Dropping off vehicle
Picking up vehicle
Loaned vehicle/equipment
Fleet - Quick Fix 
```
In AMD Fleet excel it is:
```
Ready for Pickup
Request for Inspection
Picked up from Service Center
Dropped off at Service Center
Request turn-in (tail light/ repair?/key fob not workng)
Request for state inspection
Vehicle totalled
accident
Request for recall
Requested for PM (Preventative Maintenance
```
- [x] `Date of Action` - _Date/Time_ (Required,Ignore Time, Default Date None, Just Use Simple Date/Time)
- [x] `Service Center` - _Multiple Choice_ (Required, Sort Custom, Dropdown One Selection, Default Option Blank)
```
SC 01: 6301-A Harold Ct
SC 05: 714 E 8th St
SC 06: 1182 Hargrave St
SC 08: 4411-D Meinardus
SC 11: 6301-J Harold Ct
SC 12: 4108 Todd Ln
SC 13: 2412 Kramer Ln, Bldg A
```
In AMD Fleet sheet there were mostly SC 08, but some for SC 01 and once for SC 13 and SC 05
- [x] `Vehicle Status` -  _Multiple Choice_ (Required, Sort Custom, Radio Buttons, Default Option Blank)
```
In Service
Out of Service - Preventative Maintenance
Out of Service - Unscheduled Issue
```
- [x] `Vehicle Notes` - _Paragraph Text_ 
- [x] `Maintenance Issue Photo` - _Image_ (Upload Image files)
- [x] `IN SERVICE` - _Number_ (Conditional Rules 2 `In Service`)
![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/e99a8ee3-1886-45b1-aa5a-4ef948738efe)

- [x] `OUT - PM` - _Number_ (Conditional Rules 2 `Out of Service - Preventative Maitenance`)
![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/bdb87c33-66fd-44f7-978d-a7dba660bc79)

- [x] `OUT - UNSCHEDULED` - _Number_ (Conditional Rules 2 `Out of Service - Unscheduled Issue`)
![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/f93799c9-871c-489c-b8aa-19d3ff6f19e8)

- [x] `Loaned To` - _Multiple Choice_ (Required, Custom, Dropdown - One Selection)

```
Active Transportation & Street Design
Parking Enforcement
Parking Meters
Right of Way
Signs and Markings
Smart Mobility
Special Events
Transportation Engineering
```

**Comment by susannegov** [comment]
# To do 5/22
- [ ] Added fields
- [ ] Export `fleet_vehicles` as CSV to retrieve vehicle models multiple choice options and compared AMD Tracker

**Comment by susannegov** [comment]
# 5/23 
Added `Created By`, `Created Date`, `Modified By`, `Modified Date`, and `Action`
- [ ] Need to create multiple choice actions based on existing AMD Fleet sheet and SMD Fleet management

**Comment by susannegov** [comment]
Reviewed issue w/ @dianamartin  at 5/26. Ready to tackle the next issue which is creating pages.
