### ISSUE TITLE
Onboard Rebekka B. 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#12355]
## New team member
_Rebekka_ 
- [x] [Log in to your City of Austin email](https://outlook.office365.com/)
- [x] [Set up your email signature](https://docs.google.com/document/d/1OAoBll9rIl6XZq2uOShm5HCbHJboOt0SLP_wK6tjkEE/edit)
- [x] If you don't have one already, [create a Github account](https://github.com/join) and then ask your supervisor to add you to the City of Austin [Transportation Github Team](https://github.com/orgs/cityofaustin/teams/transportation/members). 
- [x] Enable [two-factor authentication for your Github account](https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa)
- [x] Install [Zenhub Browser Extension](https://www.zenhub.com/) 
- [x] [Create a Google account for your austintexas.gov email address](https://atd-dts.gitbook.io/atd-staff-resources/general/using-google-as-a-city-employee)
- [x] Install Slack desktop client: [Windows](https://slack.com/downloads/windows) | [Mac](https://slack.com/downloads/mac)
- [x] Post your [daily standup in Slack](https://atd-dts.gitbook.io/wiki/slack#daily-stand-up)
- [x] Install [1Password browser extension](https://1password.com/downloads/browser-extension/)
- [x] [Set yourself up for remote work](https://atd-dts.gitbook.io/atd-staff-resources/working-remotely/getting-started)
- [x] [Set up Cameron Road printer](https://app.gitbook.com/@atd-dts/s/dts-service-desk-knowledge-base/onboarding/printer-information) 
- [x] #12374
- [x] Upload a headshot [here](https://drive.google.com/drive/folders/1y_yhkZQE5uSRhLZAHJn2kFuXPBixVJ2G) and add your title and preferred pronouns [here](https://docs.google.com/document/d/1gRjTic8FD3s-t0sVZhErAidMIAktU-0Vn2GYPpPcUeg/edit) (Google Drive access must be set up first)
- [x] [Create a Github issue](https://github.com/cityofaustin/atd-data-tech/issues/new) for adding yourself to the [DTS "About Us" webpage](https://austinmobility.io/about) (labels: `Service: Dev`, `Type: Operations`, `Product: DTS Website`) including the link to your photo in Google Drive and preferred pronouns
- [x] #12375
- [x] [Open a service request ](https://atx.servicenowservices.com/sp?id=sc_cat_item&sys_id=02e490c6db7f1300a314e1c2ca9619e6)with Communications and Technology Management (CTM, the City's internal enterprise IT department) to request a Miro account
- [x] Familiarize yourself with the [DTS Resource Index](https://github.com/wiki/resource-index) --caveat: this page is overdue for an update!!
- [ ] Bonus: [Update this wiki](https://app.gitbook.com/@atd-dts/s/wiki/) if you find broken links or missing information!

## Supervisor
_@amenity_ 
- [x] Submit a [CTM New Employee Request Form](https://atx.servicenowservices.com/sp?id=sc_cat_item_guide&sys_id=b714eb12db7a3f0021ccef92ca961972) for a COA network account, eAccess PIN/HR Portal, and phone. Under "Network Account Information," write `Shared Mailbox: transportation.data@austintexas.gov` and provide the name of an existing team member whose privileges/access can be referenced
- [x] Ask Scott to add the employee to the distribution lists ATDDataTechnologyServices@austintexas.gov and TPWEmployees@austintexas.gov.
- [x] Coordinate hardware needs with Scott as soon as possible to ensure there is enough lead time to acquire equipment
- [x] Ask Amenity or Diana to add the new team member to [City of Austin Slack](https://austininnovation.slack.com/admin) - austininnovation.slack.com
- [x] Share the [DTS Google Drive](https://drive.google.com/drive/u/0/folders/1fNmU-czryk5wJsn1gmb4WYUJJdut8Me7) with the new team member
- [x] Add the new team member to the City of Austin [Transportation Github Team](https://github.com/orgs/cityofaustin/teams/transportation/members). This should automatically add them to the [City of Austin organization](https://github.com/orgs/cityofaustin/people) 
- [x] Add the new team member to [Gitbook](https://app.gitbook.com/@atd-dts/spaces)
- [x] Ask Amenity or Diana to [add the new team member to 1Password](https://my.1password.com/people). 
- [x] Add their [headshot](https://drive.google.com/drive/folders/1y_yhkZQE5uSRhLZAHJn2kFuXPBixVJ2G) to the [DTS Orientation presentation team slide](https://docs.google.com/presentation/d/1ByRWXmjHut88cTiPVOTgkwTJ2V5_m1Y_0j46FP_kdYw/edit#slide=id.gfd25a7f266_1_173), as well as the slide for the team the new employee is joining
- [x] Schedule a one-hour DTS Team Orientation including Peggy and all team leads
- [x] Ask Amenity to schedule DTS Product Ops training
- [x] Schedule Biweekly 1x1s
- [x] Ask Peggy to add new team member to DTS Team Meetings
- [x] Forward biweekly Sprint calendar events
- [x] Invite new team member to relevant agile ceremonies — Planning, Grooming, Retro
- [x] Invite new team member to other regular meetings — Syncs, Show & Tell

## Hardware
_@scottreedy_
- [x] Laptop
- [x] Monitors - There is currently 1 monitor there
- [x] Power supply
- [x] Keyboard
- [x] Mouse
- [x] Docking station
- [x] 4n1 adapter
- [x] Phone, if necessary

## Desk space 
_Supervisor to coordinate with @dianamartin_ 
- [x] Chair
- [x] Desk
- [ ] Standing desk

**Comment by amenity** [comment]
@rebekkabry - please close when you get your standing desk!

**Comment by rebekkabry** [comment]
Received standing desk. Installation in progress.
