### ISSUE TITLE
Project: TPW Data Ecosystem Map

### ISSUE THREAD

**Issue by rebekkabry** [cityofaustin/atd-data-tech#12427]
Ecosystem Map is an enterprise-wide view of the data sources that support our business dashboards and provide insight into operational performance. 

## Background

Prior to the TPW merger, PW and ATD respectively have developed a variety of datasets, data source locations, operational tools and dashboards that provide insight into business activities and consideration for business initiatives toward changes. Currently there is no standard data documentation or visibility into the data pipelines that support our major dashboards and tools. The ideal behind the Ecosystem map is to provide documentation to support current tools, provide standardized data mapping documentation standards, and to provide stakeholders with a centralized “themed” platform to access all dashboards, reports, resources related to a specific workgroup or tools. 

This map and documentation will be the backbone for current and upcoming projects. Such as: Dash, TPWStat, 311 integrations, etc.

## Scope & Deliverables

Due to the large, complex nature of this initiative, we are planning to address this initiative in 4 phases:

**Phase 1 – Collecting Start to End** 

- [x] List of all dashboards/tools/major reporting 
     - [Previous Issue containing notes](https://github.com/cityofaustin/atd-data-tech/issues/12488)
     - [Compiled List of Outputs](https://cityofaustin.sharepoint.com/:x:/r/sites/tpwDTS/Shared%20Documents/Projects/TPW%20Data%20Science%20NotePad/TPW%20DTS%20Data%20Ecosystem%20Project/DTS%20Ecosystem%20Compilation%20File%20via%20Sharepoint.xlsx?d=w1cd2cf1b608741efbeadeca9399a6d8a&csf=1&web=1&e=zCOGxA) (from PowerBI, ArcGIS Feature Service, Knack Web Applications, AustinTexas.gov, Data Mobility Projects, Others ***NOTE: Tab** **"Output Compiled"**
- [x] List of [workgroups supported](https://cityofaustin.sharepoint.com/:x:/r/sites/tpwDTS/Shared%20Documents/Projects/TPW%20Data%20Science%20NotePad/TPW%20DTS%20Data%20Ecosystem%20Project/DTS%20Ecosystem%20Compilation%20File%20via%20Sharepoint.xlsx?d=w1cd2cf1b608741efbeadeca9399a6d8a&csf=1&web=1&e=zCOGxA) by each tool  **NOTE: Tab "DTS Support Overview"**

**Phase 2 – Current State Mapping Dashboard/Tools Level**
- [ ] Map out on the diagram for major dashboards from Phase 1

![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/70b94a98-6ff6-452f-a699-ed283588467a)
![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/09b8be90-b362-4177-af7a-4510fb762873)

- [ ] Transpose maps into single line

 >  Signs and Markings Dashboard 
   >      Dataset 1 → AGOL (ArcGIS Online) → Analysis
   >      Dataset 1 → Open Data Portal → PowerBI 

               
**Phase 3 - High Level Data Relationships between the stakeholders**
- [ ] Enterprise Wide Excel Mapping 
![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/1379c83b-81e9-4a8d-8625-7540bf070436)

- [ ] Enterprise Wide Data Connections 
![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/350beb3b-c25c-41b3-832c-480a8f98ea2e)	 
 
**Phase 4 – Centralized Platform Build Out** 
- [ ] Draft prototype layouts for centralized landing
- [ ] Draft filtering and report grouping options..."themes"?

## Desired Outcomes

1.	Improve access to data and data related resources by providing a centralized platform linked to the appropriate workgroup or work function. 
2.	Improve stability of data pipelines by providing insights and documentation into the data paths, especially for dashboards and other reporting tools.
3.	Promote a culture of standardized data documentation by providing data documentation templates/examples. 

## Timebox

This is an iterative project that will accumulate data from different divisions as data owners become available to walk through the pipeline and variations of data collected. 

### **What is a data ecosystem map?**
A data ecosystem map illustrates the different actors in a data ecosystem, and how value is exchanged across it. A data ecosystem consists of data infrastructure, and the people, communities and organizations that benefit from the value created by it. Data infrastructure is made up of data assets, standards, technologies, policies and the organizations that steward and contribute to them.

**Why use the tool of an ecosystem map?**
Creating a data ecosystem map helps to understand how data creates value. It identifies the data, data stewards and data users; the different roles they play; and the relationships between them. You can use your map as a practical tool to plan and visualize a data ecosystem, or show opportunities for increasing value to particular parts of a data ecosystem. A data ecosystem map can be used to: 

- 	Collaborate directly with other stakeholders for organizational/ ecosystem change 
- 	Explore new sources of data to improve internal operations 
- 	Exploit existing data flows to drive new services or improve existing services
- 	Inform a project to build a data-enabled service 
- 	Identify where changes are needed, and what effects they might have 

### **Opportunities and Value** 
 - Understanding of the data and operational relationships. This gives the ability to process improve and find the most valuable areas of impact; better troubleshoot data breaks. 
 - Provide stakeholders with real-time accessibility awareness and direction to find applicable data and reporting resources to specific parts of the business. This gives them ability to be informed of the performance and insight into the performance and health of the business. 

## Request details
- Executive sponsor: DTS and future state product of TPWStat
- Date: June 2023 
- Meeting with Richard 6/29/23 was insightful for Executive expectations and desires. Metrics and insights into “city’s services…on time, quality and responsiveness”; excellent, efficient, responsive. Service that maintains infrastructure.  

https://atd-dts.gitbook.io/wiki/product-ops/dts-website#images
The first image will be used as the project's thumbnail image on the website.

---
This Github issue represents a project of Austin Transportation's [Data & Technology Services](https://austinmobility.io/) team. Project status is documented regularly in the comments below.

**Comment by rebekkabry** [comment]
We're building a high-level dashboard that synthesizes real-time data to visualize the work and goals of TPW and its divisions.
 
### **Milestones**

**Phase 1: Current State**

> [] gather ATD data sources
> [] gather PW data sources 
> [] link to organization divisions, departments and/or programs TPW
> [] investigate missing areas or gaps

 **Phase 2: Gap Investigation**

> [] TDB

### **Outcome:** 

> [] compiled list of TPW data sources 
> [] diagram that shows all our applications and how data flows between them and the open data portal

 **Outcome Additional Values:**

> [] find trends, relational concepts, commonality and story value


### **Opportunities**

> [] build standardized reporting or data sets needs across business function areas
> [] insight into overlaps and/or gaps
> [] insight into executive main interests and/or gaps

**Comment by rebekkabry** [comment]
Considering a survey to send out to all division managers inquiring about data and reporting current details. To include items such as: 

- Current applications and methods for inputting data and tracking activity 
- Current applications and methods for viewing data and reports (output)
- Are the above methods manually or happen automatically as part of business operations? 
- URL for department (public facing) 

Get feedback from Amenity on best approach and /or additional questions to include in survery

**Comment by rebekkabry** [comment]
Current Compiling Views: 
![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/a353b1a7-c65b-40a1-8ab5-0c441326b246)


7/6/23 - Meeting with Amenity to review MVP. 

- [ ] Build "themes" to link shared datasets and insights. 
- [ ] Map of applications/products (liked with data and workgroups supported) 
- [ ] From Applications/Products view - link datasets and detailed information including, if applicable: 
  - [ ]  Owners 
  - [ ] Frequency of Refresh or Updates 
  - [ ] Data points collected in original source vs data points viewed 
  - [ ] System of data - data pipeline 

Questions to Answer: 
- Where is data not connected? 
- Who owns the update/refresh and validation of the data? 
- What are the main "meaningful" business functions? (Ex: Workorders, Signals, Sensors,  Service Calls, etc) 
- Example: Application/Product: Data Tracker, Owners: ?, Updated: ?, Tables and Dataset Used: Signals WO, etc. 

Notes: 
- Use 311, Finance and Signs and Markings to build templates/framework.

**Comment by rebekkabry** [comment]
Status Notes: Map of applications/products
Meet with Michael and Paige. 
Started mapping the high level view data pipeline for OCE and Pavement. 
Need to follow up with MAXIMO reports and data fields. Charlie in progress to get MAXIMO integrated into Power BI. 
Meeting 7/11/23 with Michael and Paige to map SBO, Utilities and Structures, DM. 
Meeting with Diana 7/12/23 and data owners to understand ETLs and transformation data practices.

![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/84bafc5e-5b2c-4476-a894-7f48410f2ac5)
![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/d31f9eb4-8936-4f0f-b3fd-c67e0032aeed)

**Comment by rebekkabry** [comment]
### Working Documents 

[Miro Board ](https://miro.com/app/board/uXjVM1BWe3I=/#tpicker-content)
[Excel Mapping](https://cityofaustin-my.sharepoint.com/:x:/g/personal/rebekka_bryant_austintexas_gov/EfdqV8-zl9dGurtk6WoWq_UBGac0A9y-QteQpkHyNrHOiw?email=Rebekka.Bryant%40austintexas.gov&e=oe0Oiy) 
[PPT ](https://cityofaustin-my.sharepoint.com/:p:/g/personal/rebekka_bryant_austintexas_gov/Ee2IXo6tnQlAvhQe1JVru6gBMwI6No6VSVi2Y5KfFcfkjw?email=Rebekka.Bryant%40austintexas.gov&e=2SF2R0)

**Comment by rebekkabry** [comment]
Organization Function > Division > Output (in progress) 

![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/408b5b51-09f0-4530-8c63-1ea9ab399396)

**Comment by rebekkabry** [comment]
+ Investigating Star/Snowflake Scheme 

![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/03282df3-5582-4b99-acc8-32ad96715954)

**Comment by rebekkabry** [comment]
DTS | Data and Technology Services Portal Knack review and model build out - in progress. 

- [ ] Follow up meeting with Karo set after model, tentative 10/11/23

**Comment by rebekkabry** [comment]
**Applications Insight**s - based on the current "applications form"...  
-	Currently it contains more than “hosting ops applications.” (currently 79 records)
-	Find a way to group the current applications. (Source: Knack Applications, Storage, 3rd party Server, Not in Production, Outputs: Online Web Application, Map) 
-	Primary Source does not mean origin of source data, it means the start of the data process In Knacks records. 
-	Applications ideally should only contain active in use data collecting or storage applications

![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/f56c68e2-91d6-4c84-b1f0-1d965de8fb3b)

**Fields / Filters to Consider**
1.	 Environment: contains Production
>  What doesn’t make it to list show up on test or prototype list
2.	Application Class Clean Up/BreakDown
> For OPSDB or 3rd DB; filter Application Class: Enterprise, Database - Other,  Database Server, Web Application - Other, Device-Specific Firmware/Software, Enterprise Business System
> For OPSDB Local Fles; filter Application Class: Computer File
> For Knack Application Tool OPSDB; filter Application Class:  Knack Application
> For OutputAccess; Filter Application Class: ArcGIS Online Web App, ArcGIS Online Feature Service
> For OutputAccess: note ArcGIS Online Feature Service has layers URL, how to include, metadata export available?
 3. Note some databases may need to be added manually for instance
> Hanson - SBO 

Results/Impact 
1. Allows set up for Hierarchy/Levels/Nodes based on role 
> Roles: Operations Tools (3rd party, DTS Supported, CW), ETL in, Storage, Storage Access/Dataset Details, ETL out, Output, Output Access
2. Allows clarity at highest view of the role and type of asset

- [x] MVP Build Out in Work Session Progress in Knack TEST | 07 SEP 2023 | DTS | Data and Technology Services Portal > current focus on Applications Form 
- [ ] Next meeting will focus on Environments insights and Datasets Node scheduled week 11/5

**Comment by rebekkabry** [comment]
[Dataset Insight Deck](https://cityofaustin-my.sharepoint.com/:p:/g/personal/rebekka_bryant_austintexas_gov/EQuvxr49JH5Ctzp8ELN1aQ0BhTSt5g8tp2Xdg02sNt1Njg?email=Rebekka.Bryant%40austintexas.gov&e=mwD4GO)

**Comment by rebekkabry** [comment]
### Proposal 

current Knack connections 
![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/eac9e4ba-652e-49e4-afb1-336e2e361007)

proposed Knack connections
![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/27075807-d5a9-485a-9c64-f2769b258fef)

**Comment by rebekkabry** [comment]
**Current Support of TPW Departments and Programs**


Divisions |   | Power BI | PW Power BI | Knack | ArcGIS | TPW Stat | SD23/Pwstat
-- | -- | -- | -- | -- | -- | -- | --
Total Count   Supported |   | 6 |   | 16 |   | 17 |  
Total Count   Supported % |   | 19% |   | 50% |   | 53% |  
Department   Count (all) |   | 32 |   |  
Service   Departments (only) Count |   | 18 |   |  
Service Count   Supported |   | 5 |   | 7 |   | 14 |  
Service Count   Supported % |   | 28% |   | 39% |   | 78% |

**Comment by amenity** [comment]
Moving this out of "Ongoing" to "In Progress" since it is a project.

**Comment by rebekkabry** [comment]
Summary Report 1/11 with DTS Management:

- [ ] Review Report 
- [ ] Review current MVP state and needs 
- [ ] Needs steps (decide to close, Q/A, or icebox or remain in progress pending leadership direction)

**Comment by rebekkabry** [comment]
### **Updates:** 

- Presented DTS Ecosystem Summary Report and Recommendations 1/11/24 to DTS Leadership and Team Leads (Peggy, Amenity, Diana, Charlie and Karo) 
- Closing issues related to Ecosystem Project 
- Recommendations have been recorded #15414 
  - Supporting Issues will be created to per Diana to assist in guidance and scope when addressed as a project TBD. 
![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/91789c39-84bc-412d-801f-32bb789ed741)
