### ISSUE TITLE
Auto-generate Reimbursable record with new WOs (Test & Prod) & Create new “Approve Invoice” page in Test

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#12436]
### New “Approve Invoice” page and process for the Requesters
- If “Send Invoice to Requester” is yes, add to table of invoices to be approved by requester
   - Make table viewable to the list of Requesters that can approve (Ramona will follow up on who should review invoices)
- Table of invoices that have date
   - Table similar to what we see on the reimbursable side and have a link to invoice details and link to work order details

**Comment by dianamartin** [comment]
# 6/7
## Discovery & Build Plan
Finally got a chance to review this issue and see what the current pages look like
- Main page `reimbursements page`
  - [x] Renamed title of page to `Reimbursable Tracking` from `Reimburesable Trackings`
  - Menu button to `Signs | Reimbursements` and
  - Menu button to `Markings | Reimbursements`
- Where would requester want folks to approve, on "Signs | Reimbursements" and "Markings | Reimbursements"? or
- Create a new main page for requesters, `Reimbursement Approvals` with similar menu button 
  - `Signs | Reimbursement Approvals` and 
  - `Markings | Reimbursement Approvals`?

Christina mentions
_Table of invoices that have date
- Table similar to what we see on the reimbursable side and 
  - link to `invoice details` and 
  - link to `work order details`
  
Field Headings on table
- ATD Work Order Details (link)
- Bond
- Invoice Details
- Requester ID
- Location Name
- Task Order #.
- FDU #.
- Work Order Status
- Created
- Completed
- Edit (edit form)
_AFTER EDIT_
- Batch No.
- Bond?
- Materials
- COA Labor
- Contract Labor
- Invoice Amount
- Contract Labor Vendor
- Contract Labor Invoice No.
- Labor Invoice Date
- PE/PM for Approval
- Div/Dept Approval
- Submitted to Finance
- Processed by Finance FM Budget
- Comments

![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/389cda93-2fa7-4660-9f36-7bb945a8d0d2)

## To Do
- Follow up with Kati and Ramona?
- Where should the table be?
- Who are the authorized folks (List of requesters to "Approve") - Ramona to provide

**Comment by dianamartin** [comment]
# 6/16 SMD Feedback
## Admin Process
On (new) "Reimbursable Invoice" table
- [ ] Create new trigger button (email notification) 
- [ ] Updates "Sent to Requester" field to (Date that was sent)
   - [ ] Display Rule: hide on table when "Date" is populated

## Viewer side
- [ ] Tab: Review Invoices (square check icon)
- [ ] Invoice table (filtered by approver)
- Ability to change Approver to another person
  - ex. Was Maddie, need to be Kaz
  - edit button or trigger

**Comment by dianamartin** [comment]
# 6/27
## SMD Feedback about the Reimbursable pages

## Trigger button to mark as "Not Eligible for Reimbursement"
- Add trigger button reimbursement  table
>Add “Too Small for Reimbursement” column to DT. Intent of this field is to identify and mark any invoices that are too small to pursue reimbursement. Would be interested in what functionality there is to maybe grey out the line in the table if marked as too small. Or strikethrough? Something to help indicate that that work order/invoice will not be going forward in the process. 

## Email Enhancement 
User Story
- TLDR: When the invoice is with Approver for over a 1 week, email SMD Staff
- Allow SMD Staff to send follow-up email to Approver
- New field: "Due Date" attached to invoice?
>Once an invoice has been created by Johnny and reviewed and sent to the requester by Ramona, would there be the functionality to have Ramona pinged (email?) when the invoice has been with the requester for more than a certain amount of time. Maybe 5 business days? This would let her know to follow up with that requester to keep the invoice moving.

## Email Notification to Approver when put into "Waiting for Approval"
- Add language to email/page about “_please ensure there is sufficient funding in the FDU to cover the full amount of this invoice prior to approving_” 
>We occasionally have issues with funding that are not noticed until Finance is processing the invoices. Ideally, the requester would identify any lack of funding when review the invoice but sometimes they need a reminder. Looking to add language to the affect of “please ensure there is sufficient funding in the FDU to cover the full amount of this invoice prior to approving” somewhere in the process (email to requester letting them know their approval is needed, language on the review/approval page requester looks at, pop up box when approving?). Don’t need it everywhere, just curious on options and where the best place would be.

## Send Approvals to "Requester", no need to create a new field "Invoice Approver"
>Invoice approver will be the requester who submitted the work order. There is already a requester field in the table (ATSD, Safe Routs, V0, etc.), can another column be called Requester and say the person who submitted the work order (and therefore the person who will review and approve the invoice)? Or should we determine a different name for the invoice approver? Maybe Invoice Approver

## Updates to Reimbursement Pages
- [ ] Rename “Labor Invoice Date” column to “Contract Labor Invoice Date”
- [  ] Rename “PE/PM for Approval” date column to “Invoice Date” 
  - Use "Date" when the button "Prepare Invoice"
>Enhancement Request: have it auto populate when Johnny creates the invoice

## Remove In-line editing FDU table
- Ramona will not need to in-line edit the FDU in the table. She will need to go to the invoice page to update the FDU so that she can recreate the invoice with the updated FDU and PDF it

## What are all of these buttons? Opportunity to consolidate/clean up?
 - not recommended because there is a lot of change being requested

## BUG?
•	Ramona noted that she still sees the occasional issue where unit costs aren’t correct

## Remove Fields
•	Don’t need the `FM Budget` column in DT, can remove
•	Don’t need `CIP` Y/N column in DT
•	Don’t need another `Bond` Y/N column in DT, the existing “Bond?” Yes/No column serves this function

## Needs Scoping
- Semi-related question: Can the attached labor cost calculator be added to DT?

**Comment by dianamartin** [comment]
# 7/3
- [x] Update `reimburseable_tracking` object, field `Labor Invoice Date`, rename to `Contract Labor Invoice Date`
  - this will update the field name in the form

**Comment by dianamartin** [comment]
# 7/12
Reference from Chrispin 
INSERT
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/86b4766e-3d42-4574-96c2-ca53b0024425)

UPDATE RECORD 
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/4cf45d59-9909-478e-8677-72a28792bda1)

**Comment by dianamartin** [comment]
#7/14
- on the `work_order_markings` object
- Created a `SELF CONNECTION work_order_markings` - `work_order_markings`
- Created a `WO MARKINGS PARENT ID`

On the New Work Order form
- create record rule to set connection from parent ID

On the Attachment form

**Comment by dianamartin** [comment]
# 8/2 
- Diana to needs to check where we are on this project. I think the last bit of testing we did, it was working.

**Comment by dianamartin** [comment]
# 8/3
## Testing Markings Work Order
- Notes say that this was configured to create a reimbursement record when a new markings work order is created
-

**Comment by dianamartin** [comment]
# Need to create in PROD
- Ready to create issue to move to PROD
- Have to review what all needs to move to PROD from TEST

**Comment by ChristinaTremel** [comment]
# 8/21
- Reviewed this with the stakeholders during the SMD Sprint Review. They like the new process and would like to roll out the new approve invoice process in October.
- Focus on updating configuration to create a reimbursement record when a new markings work order is created first (notes above in the 8/3 comment)

**Comment by dianamartin** [comment]
# 8/21
Need to configure the changes from TEST to PROD

## Configure Object
- [ ] Created a SELF CONNECTION work_order_markings - work_order_markings - `SELF CONNECTION work_order_marking`
- [ ] Created field `WO MARKINGS PARENT ID` - short text

## Configure Form
- [ ] Created Record Rule
  - Rule 1: create record rule to set connection from parent ID
`SELF CONNECTION work order signs/markings` - set to reimbursable_tracking_work_order
  - Rule 2: insert a connected record - new reimbursable_tracking
When `FDU` is Yes
`Approver` - logged in Accounts

## Follow-up Testing of Markings Work Order
- [ ] Created a new markings work order (Will have Christina test this..)
- [ ] Created a new reimbursable record

**Comment by dianamartin** [comment]
@ChristinaTremel Do we need to configure this on the Signs Work Order too?

**Comment by dianamartin** [comment]
# 8/22
## Configure Object
- [x] Created a SELF CONNECTION work_order_signs - work_order_signs - `SELF CONNECTION work_order_signs`
- [x] Created field `WO SIGNS PARENT ID` - short text

## Configure Form
- [x] Created Record Rule
  - Rule 1: create record rule to set connection from parent ID
`SELF CONNECTION work order signs/markings` - set to reimbursable_tracking_work_order
  - Rule 2: insert a connected record - new reimbursable_tracking
When `FDU` is Yes
`Approver` - logged in Accounts

**Comment by ChristinaTremel** [comment]
# 8/22

## Follow-up Testing of Markings Work Order - Christina testing 8/22
 - [x] Created a new signs work order
   - Created test markings WO record: SGN23-161895
   - Added a test TK and test FDU
- [x] Created a new reimbursable record
   - Checked on the Reimbursable table and a reimbursable record was created for this test WO 🎉
   ![image](https://github.com/cityofaustin/atd-data-tech/assets/61209591/66783611-58db-471c-bab6-37f31d4103fc)
- [ ] Delete WO SGN23-161895 and associated reimbursable record.

**Comment by dianamartin** [comment]
Closing, as we separated the other feature in a new issue #13485
