### ISSUE TITLE
Issue Knack SSL SSO Certificates (2023) - Annual action

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#12430]
# Todo
- [ ] Generate a new cert and store the pub/private keys in 1Password. Use a 720 day expiration.
- [ ] Compile a list of all Knack apps with SSO
- [ ] Reach out to CTM and let them know we'd like to coordinate an update of our certs
- [ ] Schedule an app maintenance window for SSO change that works for CTM and us. It would probably be fine to do this late in the day during working hours. E.g. 3pm-5pm. Users who are already logged in will not be kicked out of the system.

During the maintenance window: 
- [ ] Install new certificates in Knack apps
- [ ] Send updated app metadata to CTM
- [ ] Confirm SSO is working

After maintenance is complete:
- [ ] Add two calendar reminders to remind us of the expiration. One reminder 30 days before the actual expiration, and one reminder the working day prior to the expiration.

**Comment by ChrispinP** [comment]
Reached out to John and Michael at CTM. Confirmed with Michael that we should be able to meet before June 20th. Pending calendar invite.

**Comment by ChrispinP** [comment]
Meeting with Michael setup from 10am to 12 on Thur June 15th.

Go Live Date set for Mon June 19th (holiday)

@dianamartin If you want to prepare a distro Whats Happening email for Friday (before) and Tuesday morning (after) that would be amazing 🥳

**Comment by ChrispinP** [comment]
New Certificates are stored in 1Password. Tested and now Live without any downtime. New certs expire on June 16th, 2025

We updated the Smart Mobility instance and saved the IP Cert in 1Password since it wasnt saved.

The IP Cert for ROW showed as expired so we needed to create a new one, activate it, then delete the old one. New IP Cert saved in 1Password.

The 2 instances for Moped have their certificates expiring in October 2023 so we removed Sergio's email and updated to Transportation Data inbox for their expiry. @amenity 

@dianamartin We no longer need a Distro email. 😎

**Comment by ChrispinP** [comment]
Created a calendar meeting for the 2025 expiry.

Complete.
