### ISSUE TITLE
Phase 1 – Collecting Legacy Start / End

### ISSUE THREAD

**Issue by rebekkabry** [cityofaustin/atd-data-tech#12488]
**Phase 1** will consist of creating a list of all dashboards and reporting tools used across the organization; and which work groups those tools provide insight into. 

A. Create List
- [x] List of Dashboards/Reports linked to organization division - [Legacy ATD](https://github.com/cityofaustin/atd-data-tech/issues/12868). Rebekka/Charlie
- [x] List of Dashboards/Reports linked to organization division - Legacy PW. Paige/Michael

B. Transpose list into Excel charts for mapping 
- [x] List into Excel for mapping - Dashboards 

C. Ensure A and B gathered for 
- [x] Legacy ATD 
- [x] Legacy PW

**Related Resources:** 
https://miro.com/app/board/uXjVMB3l8KY=/

**Comment by rebekkabry** [comment]
[] Link current datasets to ATD TPW departments, applications and mapping
[] List of all current external facing dashboards/data sources + link to TPW departments 
> [] any departments lacking visibility

https://miro.com/app/board/uXjVMB3l8KY=/

**Comment by rebekkabry** [comment]
**List of Legacy PW Dashboards and Reporting Tools**

- PWStat
- OpsStat
- SD23
- Power BI

**Comment by rebekkabry** [comment]
Sent list to each legacy stakeholder to confirm, support for moving into Phase 2. 



PW/OPM | .
-- | --
PWStat | 
OpStat | 
SD 23 Measures | 

ATD/DTS | .
-- | --
Power BI | 
Knack | 

Other Tools | Accessible (not mapping, for note/reference)
-- | -- 
Capital Projects Explorer | https://capitalprojects.austintexas.gov/projects
Austin Finance Online | https://financeonline.austintexas.gov/afo/finance/
Public City Records | https://cty-austintx.govqa.us/WEBAPP/_rs/(S(cgsb0gdzjls3z0y3uyapxl2j))/supporthome.aspx?sSessionID=13649168211Z[QDRISMTXJWXMJWUEOOBUIAHHNJI

**Comment by rebekkabry** [comment]
**ATD Power BI** | Notes
-- | --
Amanda_Special_Events |  
Vision Zero   Assignments Citations Warnings |  
O Data Feed   Census Commutes |  
ArcGIS_Issued_Building_Permits |  
Vision Zero   Officer Notes |  
VZA   Assignments Citations Warnings Notes |  
VZA   Assignments Citations Warnings Notes_1 |  
JDEdit_Monthly   WIG Report Power BI Draft_March 2021_v1 |  
AMD_trial |  
AMD_trial_2 |  
2021.03   Monthly WIG Report Dashboard_final |  
2021.04   Monthly WIG Report Dashboard_final |  
Vision Zero   Assignments Citations Warnings_PBI |  
High Level   Dashboard - Markings |  
MMC 2020   Annual Report |  
2021.05   Monthly WIG Report Dashboard_final |  
Signs  High Level Dashboard |  
2021.06   Monthly WIG Report Dashboard_final |  
Markings High   Level Dashboard |  
trial |  
AMD Asset   Dashboard |  
LMS365 COA   Required Course Progress |  
LMS365Volume |  
LMS365 Cross   Catalog Search |  
LMS365   Department Contacts |  
Report Usage   Metrics Report |  
Usage Metrics   Report |  
Austin COVID   Traffic Impacts |  
test-amd   traffic |  
animation ex |  
VZ Key Metrics |  
Report Usage   Metrics Report |  
VZ Bond   Locations & Emerging Hotspots |  
VZ Fatality   Review Board |  
VZ AMD |  
VZ High Injury   Roadways |  
VZ Corridor   Program |  
VZ   Construction Zone Analysis |  
VZ in Action |  
D4 Versions |  
MMC Calendar |  
AMD Device   Comm Status |  
parking pivot   tables |  
2021 Annual   Report |  
AMD inventory   value |  
Signs_Markings_Work_Orders |  
Road   Conditions_Weather Sensors |  
Road   Conditions |  
Event_Template |  
MMC Storm   Event Tracker |  
2020 bond |  
BRM Org Chart |  
MMC Top N   Events |  
MMC Actions |  
2020 bond   staging |  
Polygon   Crashes Analysis |  
Parking   dashboard v2 |  
Parking Open   datasets |  
Austin   Intersection Volumes |  
DETECTION_INTERSECTIONS_WIP |  
2020 bond v3 |  
Usage Metrics   Report |  
ASR 22 -   Burnet |  
parking   comparison |  
AMD Monthly   Metrics |  
Travis County   Analysis |  
Exec Dashboard |  
LMS365   System-Wide Reporting |  
Austin COVID   Traffic Impacts_V3_DTS |  
LMS365 COA   Calendar |  
Top N |  
Executive   Dashboard |  
LMS COA   Calendar |  
APD Sector   Analysis |  
microstrategy_test |  
Vision Zero   VIN Number Analysis |  
LPI Locations |  
Signs_Markings_DecisionTree |  
Road   Conditions v2 |  
ROW Dashboard   WIP |  
ASR 23v2 |  
Exec Dashboard   (5) |  
243 Cell Modem   Conversion |  
Bond Quarterly   Reporting |  
ASR Dashboard |  
Elock Tracking |  
moped_project_phases |  
CCTV   Cutover_V2 |  
BBS Deployment |  
Signal Areas |  
Dashboard   Build Out POW Weekly v2 |  
Austin Left   Turn Analysis |  
Sales Analysis |  
BBS_Upgrade_Tracking |  
Dashboard ROW   Weekly Applications and Requests |  
Signs_Markings_Performance_Measures |  
EIB Report |  
VZ District 2   Crash Analysis |  


** ATD Knack** | Notes 
-- | --
ADA   Parking Options - Austin Transportation
Affordable   Parking Program Web Map
AirWatch
All Ages and   Abilities Bicycle Network
AMANDA
AMANDA - GIS   Viewer
AMANDA -   Portal
AMD Data   Tracker
(ASMP) Austin   Strategic Mobility Plan Application \| PRODUCTION
ATD   Development Review Web Application
ATD Forms \|   PRODUCTION
ATD GIS   Reference Web App
ATD Land Use   and Parking Zone Map
ATD Vehicle   Form
ATD Visitor   Sign-In \| PRODUCTION
AWAM
Bike Parking   Hub
Business Needs   Assessments \| PRODUCTION
Chia's Sandbox
CMTA MetroLabs
CSR (311)
Dockless   Mobility Explorer
DTS \| Data and   Technology Services Portal \| PRODUCTION
Feature   Service
File   Geodatabase
Finance and   Purchasing Request System \| PRODUCTION
FME (SAFE   Feature Manipulation Engine)
GISDM
GISMAINT1
GISMAINTDEV
Gridsmart   Device Software
HR \| Human   Resources Manager \| PRODUCTION
IMMPACT
John's Test   App
KITS
Knack
Knackpy   Development \| PRODUCTION
Markings Work   Order Collection \| PRODUCTION
MAXIMO
Microsoft   Excel
Mobility   Project Database
Off Street   Parking
Online Bike   Map
Online Bike   Map Public Feedback
Open Data and   Performance Hub
Open Data   Portal (Socrata)
Parking   Inventory
PDF
PEP \| Parking   Enterprise Portal \| PRODUCTION
Preventative   Maintenance Tracking (Arterial Mangement)
Private   Vehicle Mileage Tracker
Public Testing   Environment
Road Markings   Work Orders Web Map Application
ROWPACT
ROW \| Right of   Way Portal \| PRODUCTION
RPP \|   Residential Parking Permits Portal
SharePoint
Signal   Preventative Maintenance (Fulcrum)
Signs and   Markings Operations \| PRODUCTION
Smart Commute   Rewards Program \| PRODUCTION
Smart Mobility   Office
SMRT \| Shared   Mobility Reporting Tracker \| PRODUCTION
Special Event   Permits
Street Banner   Program - Lamppost Banner Interactive Web Application
Street Banner   Program - Over-the-Street Interactive Web Application
Street Banner   Program Portal \| PRODUCTION
TDS \|   Transportation Development Services Portal \| PRODUCTION
Text File
Traffic   Register \| PRODUCTION
Traffic Signal   Assets Web App
Transportation   Data Warehouse / API
Transportation   Project Tracker
Vision Zero   Editor
Vision Zero in   Action \| PRODUCTION
Vision Zero   Input
Vision Zero   Viewer
Visitor   Sign-In
Wavetronix   Sensor Software


**OPM** | Notes
-- | --
PW   Stat
SD23 Measures
Op Stat

**Comment by rebekkabry** [comment]
![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/68320cf8-b196-4335-be28-89c270148c69)

**Comment by rebekkabry** [comment]
Closed. 

Summary: Although there are a variety of landing pages and resources. Most, if not all, associated dashboards and tools can be accessed back to points listed above. Phase 2 will go into detail of each dashboard access URL and the supporting datasets.
