### ISSUE TITLE
Madison F. First Day Checklist 

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#12493]
[Gitbook link](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-LzDGg7hKQ_fUjXnzGGx/onboarding/your-first-week)

- [x] Log in to your City of Austin email
- [x] [Set up your email signature](https://docs.google.com/document/d/1OAoBll9rIl6XZq2uOShm5HCbHJboOt0SLP_wK6tjkEE/edit)
- [x] If you don't have one already, [create a Github account](https://github.com/join) and then ask your supervisor to add you to the City of Austin [Transportation Github Team](https://github.com/orgs/cityofaustin/teams/transportation/members)
- [x] Enable [two-factor authentication for your Github account](https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa) 
- [x] Install [Zenhub Browser Extension](https://www.zenhub.com/extension)
- [x] [Create a Google account for your Austintexas.gov email address](https://atd-dts.gitbook.io/atd-staff-resources/general/using-google-as-a-city-employee)
- [x] Install Slack desktop client: [Windows](https://slack.com/downloads/windows) | [Mac](https://slack.com/downloads/mac)
- [x] Post your [daily standup in Slack](https://atd-dts.gitbook.io/wiki/slack#daily-stand-up)
- [x] Install [1Password browser extension](https://1password.com/downloads/browser-extension/)
- [x] Upload a headshot [here](https://drive.google.com/drive/folders/1y_yhkZQE5uSRhLZAHJn2kFuXPBixVJ2G) and add your title and preferred pronouns [here](https://docs.google.com/document/d/1gRjTic8FD3s-t0sVZhErAidMIAktU-0Vn2GYPpPcUeg/edit) (Google Drive access must be set up first)
- [x] [Create a Github issue](https://github.com/cityofaustin/atd-data-tech/issues/new) for adding yourself to the [DTS "About Us" webpage](https://austinmobility.io/about) (labels: Service: Dev, Type: Operations, Product: DTS Website) including the link to your photo and preferred pronouns
- [x] [Open a service request](https://atx.servicenowservices.com/sp?id=sc_cat_item&sys_id=02e490c6db7f1300a314e1c2ca9619e6) with Communication and Technology Management (CTM, the City's internal enterprise IT department) to request a Miro account.
- [x] Familiarize yourself with the [DTS Resource Index](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-LzDGg7hKQ_fUjXnzGGx/resource-index)

Ask questions! Be a sponge and absorb it all! 🧽💦🌈

**Comment by patrickm02L** [comment]
@patrickm02L hi this is a test

**Comment by madifan** [comment]
Completed everything, Patrick signed off
