### ISSUE TITLE
Phase 4: Self-Service, Centralized Access Point

### ISSUE THREAD

**Issue by rebekkabry** [cityofaustin/atd-data-tech#12491]
**Connect these resources to a centralized, self-service platform.** 

- [ ] Ability to access dashboards and tools, filter by themes, divisions, etc. Users should have the ability to filter type of report or dashboard, service area or division

- [ ] Consider Functionality: Users could create personalized views of the dashboards/reports most valuable to separate from the comprehensive list that will be available. (pic for reference, not exact layout. Visuals TBD) 

Included in [TPWStat](https://github.com/cityofaustin/atd-data-tech/issues/12597) as future state project of data-driven culture initiative.

**Comment by rebekkabry** [comment]
- [ ] Opportunities to find interdependent and operational linked divisions and/or services. For example: OCE provides yearly pre-planning schedule and assigns WOs to Pavement; 311 WOs and SRs.

**Comment by rebekkabry** [comment]
![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/7189e489-3c1a-44c4-a798-ee3e23e8c3f7)

**Comment by amenity** [comment]
I completely agree that Dash will now be the "self-service" access point. I think these are excellent notes to have on hand for Dash user stories/journey mapping/feature mapping, etc. cc/ @katelunceford 

No need
