### ISSUE TITLE
Phase 3: High Level Data Relationships between the stakeholders

### ISSUE THREAD

**Issue by rebekkabry** [cityofaustin/atd-data-tech#12490]
### Background 
There are places across the department where divisions connect, align, share operational responsibilities; however known those places are not clearly documented or easily visualized for understanding on data sharing, operational function and financial implications. This issue is to track what relationships the data and the stakeholder have.

**Comment by rebekkabry** [comment]
**Gaps and Opportunities**: 

Bring data outputs and data sources into alignment or cycle. For example: SMD has an alignment and cycle between custom applications and original data sources; there are opportunities for data tools and automation to replace Excel storage. OCE opportunity where data used for reporting is not linked to datasets other than Excel. 

![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/3b59d4fb-7417-4f7e-8dd2-c277a59ad99a)
![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/ce3bef83-2641-4f1d-9d6a-fb4adc829f9b)

**Comment by rebekkabry** [comment]
### Recommendations moving forward to stakeholders and executives 
1. Naming standard and renaming of tools and dashboards division_purpose_recurring Ex: ROW_ApplicationsActivity_Weekly
2. Metadata requirements: Division / DB used/ DS linked/ Reason Solution for Output

**Comment by rebekkabry** [comment]
### New Framework Model 

![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/be6920ff-4b67-4818-9196-928741ea7001)

**Comment by rebekkabry** [comment]
There are places across the department where divisions connect, align, share operational responsibilities; however known those places are not clearly documented or easily visualized for understanding on data sharing, operational function and financial implications.

**Comment by rebekkabry** [comment]
- [ ] Meeting 10/9 for SBO detailed discussion 
- [ ] Scheduling Follow up for Civil Engineering discussion with IT stakeholders, week of 10/16; Upal, Cole, Curtis, Kathleen, Michele 
- [ ] Scheduling Follow up for Transportation Services discussion with IT stakeholders, week of 10/16

**Comment by rebekkabry** [comment]
- [ ] Pending completion of meetings and documentation of connections 
- [ ] Build out of matrix and summary reports in progress

![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/5020d160-b5ba-4cc2-9cc2-7be0a2690ce5)

**Comment by rebekkabry** [comment]
### **Updates:** 

- Presented DTS Ecosystem Summary Report and Recommendations 1/11/24 to DTS Leadership and Team Leads (Peggy, Amenity, Diana, Charlie and Karo) 
- Closing issues related to Ecosystem Project 
- Recommendations have been recorded #15414 
  - Supporting Issues will be created to per Diana to assist in guidance and scope when addressed as a project TBD. 
![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/91789c39-84bc-412d-801f-32bb789ed741)
