### ISSUE TITLE
Build Fleet Management "Edit Vehicle Form" page and "View Fleet Vehicle Details" page creation of new fleet menu in PROD

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#12507]
# Build Notes - View Fleet Vehicle Details page
Page URL: `view-fleet-vehicle-details`
## Details view
![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/d451afd3-a81d-4baf-886e-a654f58cf4bc)
### Settings
- [x] No, show all fields
- [x] Left aligned
- [x] Layout = box 
![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/c3baace4-5817-470b-8453-6c922880933b)
- [x] Title =  View Fleet Vehicle Details

### Add Details
- [x] `VEHICLE_STATUS` = Status
- [x] `VEHICLE_ID` = Vehicle ID
- [x] `VEHICLE_NAME` = Name
- [x] `VEHICLE_MAKE` = Model
- [x] ~~`BUSINESS_UNIT` = Work Group~~
- [x] `VEHICLE_YEAR` = Year
- [x] `Category` = Category
- [x] `Accounts > CREATED_BY` = Created By
   - [x] Connection Link = No Link
- [x] `CREATED_DATE` = Created

### Rules
None

## Menu View
![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/d937d779-6189-4b6d-b225-f445fd23eb61)
- [x] Link to a new Page > Add Vehicle Log
- [x] Link to a new Page > Add Vehicle Note

## Grid view
![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/e5485504-368e-4db5-935d-31c1c9030891)
Tag: `fleet_vehicle_trackings`
### Source
- [x] Sort `fleet_log_ID` numerically from low to high
- [x] Limit: Use all available records
### Settings
- [x] Keyword Search: The fields being used by this view
- [x] Hide empty columns
- [x] Empty Grid Text: No vehicle logs
- [x] Pagination: Display 25 records at a time
   - Repeat Pagination. Let user change the amount.
- [x] Filter: Allow users to add custom filters - the fields being used by this view
- [x] Title: Vehicle Log
### Add Columns
- [x] `fleet_log_ID` = ID
- [x] `Date of Action` = Date
- [x] `Action` = Action
- [x] `Location` = Location
- [x] `Vehicle Notes` = Notes
- [x] `Vehicle Status` = Status
- [x] `Maintenance Issue Photo` = Issue Photo
- [x] `Created Date` = Created
- [x] `Accounts > Created By` = Created By
   - Connection Link: No Link
- [x] `Modified Date` = Modified
- [x] Actions > Delete record
   - Header: Remove
   - Icon: `fa-trash`

_Originally posted by @susannegov in https://github.com/cityofaustin/atd-data-tech/issues/12345#issuecomment-1570781590_

**Comment by susannegov** [comment]
# Add Vehicle Log Form page
Name: Add Vehicle Log
Page URL: add-vehicle-log
Display page in a modal popup
No page rules
## Form view
- [x] Tag: `Add_fleet_vehicle_tracking`
### Settings
- [x] Submit
- [x] Reload form
### Add Inputs
- [x] `Date of Action` = Date of Action
- [x] `Action` = Action
- [x] `Loaned To` = Loaned To
- [x] `Service Center` = Service Center
- [x] Divider
- [x] `Vehicle Status` = Vehicle Status
- [x] `Vehicle Notes` = Vehicle Notes
- [x] `Maintenance Issue Photo` = Maintenance Issue Photo
### Rules
- [x] Submit Rules: Redirect to parent page
- [x] Display Rules
   - [ ] If the following rules match, Hide/Show `Action`, Hide/Show `Vehicle Status`
   - [x] If the following rules match `Action` is `Loaned vehicle/equipment`, Show/Hide `Loaned To`, Hide/Show `Service Center`, Hide/Show `Vehicle Status`, Hide/Show `Maintenance Issue Photo`
- [x] Record Rules: 
   - [x] Update this Record > Values `Created By` to the Logged in Accounts, `Created Date` to the current date
   - [x] Update connected > The fleet_vehicle connected to this record > When `Vehicle Status` is `In Service` > `VEHICLE_STATUS` to a custom value `In Service`
  - [x] Update connected > The fleet_vehicle connected to this record > When `Vehicle Status` is `Out of Service - Preventative Maintenance` > `VEHICLE_STATUS` to a custom value `Out of Service - Preventative Maintenance`
  - [x] Update connected > The fleet_vehicle connected to this record > When `Vehicle Status` is `Out of Service - Unscheduled Issue` > `VEHICLE_STATUS` to a custom value `Out of Service - Unscheduled Issue`
### Emails
No rules
# Add Vehicle Note Form page
Name: Add Vehicle Note
Page URL: add-vehicle-note
Display page in a modal popup
No page rules
## Form view
Tag `Add fleet_vehicle_tracking`
### Settings
- [x] Submit
- [x] Reload form
### Add Inputs
- `Vehicle Notes` = Vehicle Notes
### Rules
- [x] Submit Rules: Show a confirmation message > `Vehicle log added.` 
   - Show a link to reload the form
- [ ] Display Rules: If the following rules match > Hide/Show `    `, Hide/Show `    `
    - What is the purpose of this display rule?
![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/ea06e0db-ce72-40c7-be01-6c1b80e32127)
- [x] Record Rule: Update this Record > Values `Created By` to the Logged in Accounts, `Created Date` to the current date
### Emails
No rules

**Comment by susannegov** [comment]
## Pages layout
![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/75e27454-24df-4138-bd60-9f1f724105e0)

## Build Edit Form
- [ ] Reference [page](https://builder.knack.com/atd/signs-markings/pages/scene_1229)
![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/53115e1f-ee95-4e1b-b1f6-5729ea825906)
- [x] `VEHICLE_ID` = Vehicle ID
   - Display the field value without a form input
- [x] `VEHICLE_MAKE` = Make
   - Allow users to add new options to choose.
- [x] `VEHICLE_NAME` = Name
    - Allow users to add new options to choose.
- [x] `VEHICLE_YEAR` = Year
- [x] `VEHICLE_STATUS` = Status
- [x] `BUSINESS_UNIT` = Work Group
- [x] `Category` = Category
- [x] `IN SERVICE DATE` = In Service Date
- [x] Submit Rule = Redirect to Parent page
- [x] Record Rules `MODIFIED BY` to the current logged in Account and `MODIFIED DATE` to the current date

**Comment by susannegov** [comment]
# 6/15
- Removed `BUSINESS_UNIT` (Work Group) from the forms and view

@dianamartin @ChristinaTremel Fleet Management has been recreated in Production. Ready for review/qa

**Comment by dianamartin** [comment]
# 6/30
We spoke to stakeholder on Fri, 6/30 and he was going to review and QC the vehicle list that was in Knack so we an prepare for go-live. Closing this.
