### ISSUE TITLE
 Fleet Management page creations for "Manage Vehicles" and "Add Vehicle Form" in PROD

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#12508]
## Page creation
- [x] Create new page called "Manage Vehicles" (Enable log in - only `System Administrator`, when building in Prod)
Remember to un-check "Include this page in the page menu" (when building in Prod) - done by Diana
- [x] On this page, create new "menu", to create a new page `Add Vehicle`
   - Add Vehicle `fa-plus` icon button menu
- [x] This page, add a new form that allows you to add a new vehicle (reference this [page](https://builder.knack.com/atd/signs-markings/pages/scene_1246/views/view_3088/form/rules/submit) in SMD 
   - [x] Settings > Display page in a modal pop-up 
   - [x] Submit Rules - Redirect to Parent Page
   - [x]  Record Rule to the `Add Vehicles` page similar to SMD app
      - [x] `CREATED_BY` to logged in Account
      - [x] `CREATED_DATE` to the current date
### Include on form
- [x] Vehicle ID (required) (Must be unique)
- [x] Make (required, Allow users to add new options to choose)
- [x] Vehicle Name (required, Allow users to add new options to choose)
- [x] Year (required)
- [x] ~~Work Group (required)~~
   - From the meeting it sounded like this field wouldn't be useful as it will only be Arterial Management vehicles
- [x] Category (required)
- [x] In Service Date (required)

## Table Creation
- [x] Add table that has the following field, see reference below
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/acb956b2-224c-41a0-a251-313e8ca09f1f)
- [x] Sort VEHICLE ID from A to Z

### Columns
- [x] Details: Page to link to `View Fleet Vehicle Details`
- [x] Vehicle ID: `VEHICLE_ID`
- [x] Year: `VEHICLE YEAR`
- [x] Model: `VEHICLE_MAKE`
- [x] Name: `VEHICLE_NAME`
- [x] Display Name: `VEHICLE_DISPLAY_NAME`
- [x] Status: `VEHICLE_STATUS`
   - [x] Display Rule
![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/d6d59bfb-96c2-4ca9-98b3-3a4989c291eb)
 
- [x] Category: `Category`
- [x] In Service Date: `IN SERVICE DATE`
- [x] Edit: Page to link to `Edit Vehicle`

### Options
- Keyword Search
   - The fields being used by the view
- Record Exporting
- Hide empty columns
- Empty Grid Text: No Data

### Pagination
- Display 25 records by a time
- Let the User Change the amount
- Repeat pagination controls below the view

## Filters
- Allow users to add custom filters
   - The fields being used by this view 

### Title and Description
`<i class="fa fa-truck"></i> Vehicles`
Created page for `Manage Vehicles`, `Add Vehicle`, and `View Fleet Vehicle Details` (for the table view)

_Originally posted by @susannegov in https://github.com/cityofaustin/atd-data-tech/issues/12344#issuecomment-1568714712_

**Comment by susannegov** [comment]
# 6/9 Notes
Completed this issue
- Work Group is not included in the table since in the meeting AMD says they will only be tracking their own vehicles/equipment

**Comment by dianamartin** [comment]
# 6/16 Notes
- [x] Added Business Unit to table
  - Renamed to Workgroup
- [ ] Add menu for Statuses (without removing filter ability for users)
  - [ ] In Service
  - [ ] Out of Service statuses
- [ ] Data clean-up on the vehicle list as best as you can
  - [ ] reference SMD naming convention
- [ ] Export for stakeholders

**Comment by dianamartin** [comment]
## 6/30
We spoke to stakeholder on Fri, 6/30 and he was going to review and QC the vehicle list that was in Knack so we an prepare for go-live. 

## Modifications
- Add status filters on "Manage Vehicle" page (the rest of the statuses)
- Apply "red text" to "Out of Service - Retired" status (like SMD)

**Comment by ChristinaTremel** [comment]
- Closing this out because feedback was addressed and we have issue #12510 open in Review/QA for when we show Billy.
