### ISSUE TITLE
Fleet Management Go-Live Checklist

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#12510]
When the AMD Fleet Management is build out
- Add link on "Home" page
- Switch user role from "System Admin" to "Supervisor" user roles for page
- Bulk update all vehicles to "In Service"
- Coordinate with Diana and make sure work order details "time log" filters are updated from Vehicles "ACTIVE" to "In Service"
  - Need to update in 3 places
- Remove Business Units that are not AMD
 - Markings: `44 records`
 - Remove the other selections
   - Signs
   - Parking Enterprise
   - Right of Way
   - Markings
- Update record rules for vehicle log on the Vehicle Details page
   - change the rules from updating the `UPDATE VEHICLE STATUS` to the `VEHICLE STATUS`
- Change `VEHICLE NAME` field type back to list

**Comment by susannegov** [comment]
Old list when `VEHICLE_NAME` switched from multi-choice to short text field
```
 Black Utility Trailer
2015 Chevy Equinox
2015 Dodge Pickup
5X8 Hawn Trailer
Black Utility Trailer
Black Utility Trailer 
Bucket Truck
Cable Reel / Tension/Fiber
Cable Reel No Tens
Cable Reel Trailer
Cable Truck
Chevy 4X4 Pickup
Dodge Flat Bed
Dodge Utility Truck
Equinox
Explorer - SUV
Ford Escape - SUV
Freightliner
Gas Card Loop Trail
Husqvarna Concrete saw
Line Lazer IV Ride Along Spray Rig
Line Lazer IV Ride long Spray Rig
Line Lazer Spray Rig
Long Line Paint Striper
Long Line Thermo Striper
Long line Paint Striper
Long line Thermo Striper
Lupe Alvarado
New Dodge Flat Bed
Old Push Cart
Old Thermo Trailer
Orange Fork Lift
Orange Grinder
RPM Trailer 
Red RPM Trailer
Service Van
Small Orange Grinder 
Small Tan Grinder
Small Yellow Grinder
Solar Arrow Board
Supervisor Truck
Thermo Push Cart
Thermo Push Cart 
Thermo Trailer 
Toyota Forklift
Toyota Prius Sedan
Trailer
Trailer Small
Truck Service 15K
White Cattle Truck 
White Dodge 4 Door Flat Bed 
White Dodge 4 Door Pick up 
White Dodge 4 Door Pick-Up 
White Dodge Truck 
White Doge truck 
White Equinox
White Ford 4 Door Pick-Up
White Ford Pick-Up
Yellow Grinder
Yellow RPM Push Cart
Yellow Thermo Trailer
```

**Comment by dianamartin** [comment]
# Next Steps
- [ ] Add link on "Home" page
- [ ] Switch user role from "System Admin" to "Supervisor" user roles for page
  - ask Billy who should have access to this page
- [x] Bulk update all vehicles to "In Service"
- Coordinate with Diana and make sure work order details "time log" filters are updated from Vehicles "ACTIVE" to "In Service"
  - [ ] Need to update in 3 places
- [x] Remove Business Units that are not AMD
 - Markings: `44 records`
 - Remove the other selections
   - Signs
   - Parking Enterprise
   - Right of Way
   - Markings
- [ ] Update record rules for vehicle log on the Vehicle Details page
   - change the rules from updating the `UPDATE VEHICLE STATUS` to the `VEHICLE STATUS`
- Change `VEHICLE NAME` field type back to list

**Comment by susannegov** [comment]
```
Pickup
F-150
Trailer
5X8 Hawn Trailer
Black Utility Trailer
Bucket Truck
Bucket Truck 550
Cable Reel/Tension/Fiber
Cable Reel No Tens
Cable Reel Trailer
Cable Truck
4X4 Pickup
Bolt
Flat Bed
Utility Truck
Equinox
Explorer - SUV
Flat Bed
Escape
Escape - SUV
F150
Freightliner
Gas Card Loop Trail
HercBucket Truck 550 Ford
Husqvarna Concrete saw
Niro PHEV
Line Lazer IV Ride Along Spray Rig
Line Lazer Spray Rig
Old Push Cart
Old Thermo Trailer
Orange Fork Lift
Orange Grinder
RPM Trailer 
Red RPM Trailer
Service Van
Sky Track Forklift
Small Orange Grinder 
Small Tan Grinder
Small Yellow Grinder
Solar Arrow Board
Supervisor Truck
Thermo Push Cart
Thermo Trailer 
Forklift
Prius Sedan
Trailer
Trailer Small
Truck Service 15K
White Cattle Truck 
4 Door Flat Bed 
Truck 
Equinox
4 Door Pick-Up
Yellow Grinder
Yellow RPM Push Cart
Yellow Thermo Trailer
Electric Forklift
Electric Order Picker
Single Axle Box Trailer
```

**Comment by susannegov** [comment]
# 7/25 
Mostly done with the next steps.
## To do
- [ ] Create the menu filter pages for out of service retired and out of service unscheduled issue

**Comment by susannegov** [comment]
# 7/26
- [ ] Remove `VEHICLE_STATUS` and rename `UPDATE_VEHICLE_STATUS` to `VEHICLE STATUS` (?)

**Comment by ChristinaTremel** [comment]
@susannegov when I was going through the Fleet Management issues I found this that was requested by Billy during our meeting on 6/30:


## Modifications
- [ ] Add status filters on "Manage Vehicle" page (the rest of the statuses)
   - ![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/c5c9d9af-e9a6-44fb-b5b8-cffbc7b5b7bd)
- [ ] Apply "red text" to "Out of Service - Retired" status (like SMD)

**Comment by susannegov** [comment]
@ChristinaTremel The rest of the status filter pages have been added as well as the "red text" to all status that is not "In Service" (similar to SMD rules)

https://atd.knack.com/amd#manage-vehicles/

**Comment by susannegov** [comment]
# To do
- [ ] Retire `Fleet Vehicle` button at home
- [ ] Move `Manage Vehicles` to Arterial Management Operations
- [ ] Set Workgroups to only `Arterial Management` not other business unit options

**Comment by ChristinaTremel** [comment]
@susannegov I think Diana just wanted us to remove the other Workgroup options on the `Business Unit` dropdown
![image](https://github.com/cityofaustin/atd-data-tech/assets/61209591/73606e57-8dc4-4abc-b38f-7fa0cba174c4)

That should be the last thing we need to do before closing out this issue!🤞🏼

**Comment by susannegov** [comment]
@ChristinaTremel Response from Billy regarding the Workgroup column:

> I’d like to leave it. We occasionally borrow from and loan to other divisions.

Currently the table is set to show only ARTERIAL MANAGEMENT vehicles.
- [x] Show all records so that AMD will be able to change that field as needed

Messaged Billy that I plan to close this out then.
