### ISSUE TITLE
TPW Technology Transition

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#12522]
# Background
- March 24, 2023 - Announcement of the Department mergers occurring citywide. ATD + PWD = TPW and the creation of a new department at CDS, Capital Delivery Services Department. 
- Transition date has yet to be announced
- Former PWD IT team, was SIM, Systems and Information Management. 4 team members were coming from that team. 

# Things that need to Merge/Transition
#### IT Admin
- [x] Scott requested access from Mike M. PWD workstation OU (move them from the client after they're imaged, change user descriptions, 
- [x] reset passwords
- [x] HRSE folder (HR Separated Employees)) 
  - John V. said he'd ask Kristi and Shelly to get approval
 - Need access to PWD tree access (Matt, Scott, Diana)
 - Matt needs access to ATD admin environments (Scott will put him in proper groups, in folder tree)
 - Need to get permission from Shelly/Kristi (HR) on HRSE access for Scott

### Distribution Lists
- [x] Azure Active Directory distribution lists
- [x] Creation of 19 Distribution list as of 6/8/2023
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/c834b393-fbb0-4fbd-824f-e931a4ac6d4c)

### IT Support (Technology Services)
- Have been meeting with SIM/CDS leadership to figure out locations

#### Identifying TPW Locations
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/e01fc2c5-12eb-4dc2-8245-da44f8a1320c)
- Identifying locations
  - 6/8: Submitted Badge access requests for Scott (PWD Sites) & Matt (ATD Sites)
- Identifying resources 
  - IN PROGRESS - IT Support Analyst hiring 
  - 6/8 and 6/9, looking to hire 2

### CTM SN Queues
- `PWD SIM Support`
- `ATD ID`
- Need to create a new on? `TPW IT` - Scott

### Network Drives 
NEED TO TEST/NEEDS FOLLOW-UP WITH CDS/CTM
DECISION REQUIRED - TPW Leadership
- Discuss merging this again?
- Benefit? Not really, there's a lot of files under "AMD/KITS"
- Ask John about PWD network (folder, groups)
- Request CTM to add people to those groups
- G:// test ("read" rights) to PWD file path

### Sites & SharePoint Sites
IN PROGRESS
- Meeting on 5/1/23
- Jeff & Lauren working on PIO sites, Twitter
- Karo, Jeff and I talked about renaming of ATDHub or creation of TPWHub #12154 
- We have 6 (former PWD) divisions that we need to reach out to and create new modern SharePoint sites and migrate content over
- [ ] Need to request a bulk rename for all other former ATD sites to TPW, e.g. `ATD-HR` to `TPW-HR`

### Hardware Inventory 
- Get hardware list from John V.?
  - Status: give list to Christi on Tues, 6/13
  - Mi-Fi's are delaying things
  - Still getting an inventory count, hoping to wait till Mon, 6/12
- Getting 1/2 of PWD Inventory
- Inventory: BOP, St. Elmo (no storage), Cameron (closet)
  - Order 20 more laptops
  - Saving 2-3 to image those laptops (for new hires)

### Servers

# BRM DISCUSSIONS
### OneDrive
- Need to discuss with CTM
- Need to ask Bethany/Jeanette

### MS Teams - administration
- Need to discuss with CTM
- Need to ask Bethany/Jeanette

**Comment by dianamartin** [comment]
# 7/6
Created a CTM Ticket to request `TPW IT` ServiceNow queue - `INC0306593`

![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/a76c75cf-aea8-4fb4-ab18-7fbe43ad9ff0)
