### ISSUE TITLE
[MetroBike] Import Benefit Codes into the Smart Mobility App

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#12542]
> What application are you using?

Data Tracker

> Describe the problem.

Please import these codes into the Bike Share Benefit Data Tracker in order for me to administer the MetroBike annual pass benefit for COA employees.

> How soon do you need this?

Soon — Within a week 

> Is there anything else we should know?

As soon as possible please, there is a backlog of 15 employee requests currently.

> Requested By
Eliza Y.

[Attachment](https://api.knack.com/v1/applications/595d00ebd315cc4cb98daff4/download/asset/64872c83e2935c0029bd5031/local365_bulkpromo_20230606_140103.csv) (3.79kb)

Request ID: DTS23-108150

**Comment by KaroEngstrom** [comment]
## M 6/12/23 
Checked with Eliza since we have two issues: 
- this one #12542 for immediate upload under the current system, and 
- https://github.com/cityofaustin/atd-data-tech/issues/12486 `to import under an update MetroBike functionality where the system no longer requires distinct codes for different tenants (user email addresses).` 
     - Currently COA general users, Austin Energy users, and Aviation users have specific codes for their tenant/email type. 
     - Per DTS meeting with Eliza and CapMetro last week,  they want to do away with this distinction and move to using a single general COA code for all users. 
     - This will require the following changes in Knack: 
          - Table filter updates to display everything accordingly 
          - Rule updates (display; record) on forms and page 
          - Object field updates (validation; conditional rules) 
     - This will require the following coordination: 
          - how will Eliza transition to assigning new general codes?
               1) Shift everything over (stop assigning distinct codes and fold in AE and ABIA to COA codes) 
                    ^ This should be easier and perhaps the unassigned codes can be repurposed by CapMetro.
               2) Assign all remaining codes to AE and ABIA, and then shift to general COA code

---

**Summary**: This current issue should be uploaded promptly under the old model. See #12486 for the next steps on the additional 200 codes.

**Comment by KaroEngstrom** [comment]
## M 6/12/23 
- [x] Added fields and populate fields `Created Date` (today's date) and `Promo Code Status` (Available) to the spreadsheet 
- [x] Exported back-ups of `program_bike_share_benefit` and `promo_code_bike_share_benefit` objects 
- [x] Imported the new codes and checked them in Builder and live app 
- [x] Notified Eliza via Teams 
- [x] Updated the change log in SMO Knack App
