### ISSUE TITLE
Add enhancement in SMD TRACKER, export button on My Work orders page (Technician)

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#12570]
Jesse R. 
SMD

Send in CTM SN Ticket `INC0300128`
>Within KNACK / DATA TRACKER , can we give our field staff accessibility to export the work tickets they closed . The same export function that supervisors and office staff have?

**Comment by ChristinaTremel** [comment]
I chatted Jesse yesterday and said:
> Hey Jesse! I think you might have accidentally submitted a service request to CTM instead of us, but they just sent the request to Diana and I! It's the request to allow technicians to export work tickets that they close! We can definitely add that option to their my work order page, but what fields would we want them to see? Trying to decide if we can just add that option to the my work orders page or if we need to give them some type of advanced reporting page
> The only fields they see right now on their table is details, status, requester ID, location, and requester

Jesse said:
> We’d like to see the function be able to send a summary of what work ticket was completed on that day. It sounds like adding it to their MY WO PAGE may work. Example: I want Carlos to send me a summary of the OT he completed on a Saturday. I also want Carlos to send me a summary of his daily work completed at the end of his shift. The summary should just show me the WO # , CSR# , maintenance ticket#, whatever the tech touched that day

**Comment by ChristinaTremel** [comment]
Based on what Jesse is wanting, we might want to create a button to the Advanced Search | Signs and the Advanced Search | Markings on the My Work Orders page that allows Technicians to search for work orders.

**Comment by dianamartin** [comment]
# Potential Build out
- [ ] Add `Advanced Search | Signs`
- [ ] Add `Advanced Search | Markings`
- [ ] Remove or Add user permissions for technicians
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/03586165-db01-4622-9b6c-1f5eef847ca8)

**Comment by susannegov** [comment]
# 6/15
- I added the Advanced Search buttons to the My Work Orders | Created page (account role is non-technician) and the My Work Order Page (technician and assigner role)

## My Work Order (Technician)
![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/a718b4c6-0b06-4f7f-a78f-cbbe472026c7)

## My Work Orders | Created (Non-technician)
![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/5e40b71e-9dd6-4311-bbc2-5f58e9846534)

Enabling Technician role on My Work Orders | Created would have lead to two different versions of the my work orders page viewable for the technician user so account roles were not modified (see below result of changing the account role)
![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/b191d279-0e6a-44a1-8f7b-ec4554d275da)

@dianamartin @ChristinaTremel This is ready for review/QA. I did not change the account rules for the pages but the buttons for advanced search have been added

**Comment by dianamartin** [comment]
# 6/16
- Susanne and I synced and the page for the technicians was functioning well, we just changed the advanced search page to remove a default selection of "need to be issued"
- Tested as technician
- Tested as supervisor
@ChristinaTremel this is ready for stakeholder review and can be closed once they've confirmed the changes.

**Comment by ChristinaTremel** [comment]
Messaged Jesse:
> Hey Jesse! We added the advanced search pages as buttons to the Technicians "My Work Order" page! Y'all will have to walk techs through how to look up their work orders completed (would need to set Assigned To to technician and completed date for the date y'all are wanting to run the report on). But that should allow them to export a summary report that has all the fields y'all would need!

Jesse responded: 
> Awesome! Field staff will appreciate it the most. Thank you

**Comment by ChristinaTremel** [comment]
@susannegov could you deactivate the Advanced Search buttons

**Comment by ChristinaTremel** [comment]
There are more discussions happening in SMD about moving the daily summary updates from a word doc to Knack. They will submit a new ticket if they decide to move forward with that new request. Closing this because as of now, SMD doesn't want the advanced search tabs to be on the My Work Orders page.
