### ISSUE TITLE
Auto Refresh the Finance Service Request form page when new jobs are added

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#12589]
When submitting new jobs on a Service Request, the job information shows up under all of the Service Request job tables until the page is refreshed. Can we auto refresh the page when a user clicks "Add Job"?

- [x]  NEED TO TEST: On Add job form, change form submission rules. Test go to parent or custom DEV work?

**Comment by ChristinaTremel** [comment]
@ChrispinP could you provide details on how you've addressed auto refreshing pages in the past?

**Comment by ChrispinP** [comment]
Sent code to Christina & Diana for review

**Comment by dianamartin** [comment]
# 7/31
- [x] Created Finance TEST environment
- [ ] Need to test code in TEST environment to see if it works on that page

**Comment by dianamartin** [comment]
# 9/11
We are testing the code that Chrispin shared with us and the Street Banners

**Comment by dianamartin** [comment]
## The Issue
- User creates a new job form and submits a record
- Form refreshes and it gets added to it's respective table (ex. TK)
- Have several tables on the page that the records appears on. 
  -  _Tables are filtered by category (ex. Subprojects, FDU, TK, JV, EIT, Other)_ 
- Additional step, manual refresh the browser so the page refreshes
- Several tables finally update and only appear on the respective table.

## Proposed
- User creates a new job form and submits a record (ex. TK)
- Form refreshes, the page is auto-refreshed 
- Records is added to it's respective table only (ex. TK)
  - The other tables don't show the record on all the tables (untouched)

## Steps to recreate 

![859F1DC0-2136-46F4-992D-BA702A852A18](https://github.com/cityofaustin/atd-data-tech/assets/21112975/f84b0b3b-6795-
4d7d-b5ca-2c6e464f5549)

**Comment by ChristinaTremel** [comment]
### John recommended we try this code: 

```
  $("#refresh-view_322").click(function (e) {
    e.preventdefault();
    Knack.views["view_322"].model.fetch();
  });
});
```

**Comment by johnclary** [comment]
I mentioned this grooming—if you want to try testing again by running this line in the javacsript console in your browser:

```javascript
Knack.views["<view_id>"].model.fetch();
```

You should replace `<view_id>` with the view ID of the table you want to refresh. Hopefully that works!

**Comment by dianamartin** [comment]
# 9/14
- In `TEST | JUL 25 2023 - Finance and Purchasing System`
- tested code

**Comment by chiaberry** [comment]
I have code in test app but this is what I found to work:

```
var viewsToFetch = ["view_1070", "view_1067", "view_1065", "view_1060", "view_1057"]
// When the form in view 1045 has been submitted, refetch the views
$(document).on("knack-form-submit.view_1045", function (event, view, data) {
    viewsToFetch.forEach(view => Knack.views[view].model.fetch())
})
```

**Comment by ChristinaTremel** [comment]
@chiaberry Thank you! I just tested that form in the test app and that code seems to be working. 🙏🏼 I'll sync with Diana early next week to test it out again/implement it in the prod app.

**Comment by dianamartin** [comment]
# 1/24/24

- Subprojects - `view_867`
- FDU - `view_865`
- TK - `view_870`
- BGEX - `view_857`
- JV - `view_1062`
- IET - `view_1061`
- Other - `view_1068`

## Updated Prod Code
``` 
var viewsToFetch = ["view_867", "view_865", "view_870", "view_857", "view_1062", "view_1061", "view_1068"]
// When the form in view 1045 has been submitted, refetch the views
$(document).on("knack-form-submit.view_1045", function (event, view, data) {
    viewsToFetch.forEach(view => Knack.views[view].model.fetch())
})

**Comment by dianamartin** [comment]
# 6/14/24
## Initial Creation - Add Job
Subprojects 1161
FDUs
TK
JV
IET
Other


## Requester Details - Add Job
867
865
870
857
1062
1061
1068

## Manage SRs - Add Job

**Comment by ChristinaTremel** [comment]
## Code for Requester Details - Add Job

> var viewsToFetch = ["view_867", "view_865", "view_870", "view_1062", "view_1061", "view_1068"]
// When the form in view 1181 has been submitted, refetch the views
$(document).on("knack-form-submit.view_1045", function (event, view, data) {
    viewsToFetch.forEach(view => Knack.views[view].model.fetch())
})

**Comment by ChristinaTremel** [comment]
Chia helped us fix the code by renaming the viewstofetch for each page we were refreshing. Diana and I tested and this works ✅ 

Still need to do PR @dianamartin

**Comment by dianamartin** [comment]
# 7/12/24
- [x] Created PR [159](https://github.com/cityofaustin/atd-knack/pull/159) on 7/11/24
- [x] Merged PR
