### ISSUE TITLE
Phase I: Hand-off Coordination Meetings

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#12624]
## By 6/30/2023
- [x]  [Email](https://docs.google.com/document/d/1cReL5OjNjEGORKcMHm_EOLJFqh9QWvi-kbhmkQtNfgA/edit#heading=h.gauhfaaq2bio) support service DMs @michael-santulli 
- [x] Have short calls with any DMs who would like hand-off meetings to find out who in the division should be in the hand-off meeting, find out what coordination has already happened, and discuss agenda items relevant to each division
    -  ~Finance~ Not needed per Michael's 6/20 conversation with Dan V.
    -  ~HR~ Not needed per 6/22 email from Jenn W.
    -  ~DTS~ Not needed per 6/21 email from Peggy M.
    -  ~PIO~ Not needed per Michael's conversation with Jeff S.
    - [x] Administration
- [x] Schedule hand-off meetings for divisions that want them
- [x] #12626 

## By 7/14/2023
Prep and hold in-person meetings with TPW divisions and any counterparts at CDS
- [x] Administration

**Comment by michael-santulli** [comment]
Sent a follow up email on 8/1 asking if the the Admin divisions needed additional assistance with hand-off coordination. Since we haven't received any more requests for additional assistance from them, closing out Phase 1 of the project for now.
