### ISSUE TITLE
Create Viewer for TED to Add/Edit New LATM Locations

### ISSUE THREAD

**Issue by andrewshensky** [cityofaustin/atd-data-tech#12689]
Create Viewer for TED to Add (perhaps edit) an extract of LATM Data

**Tasks:**

- [x] Take an extract of Maint LATM data (ATD_ADMIN.local_area_traffic_managment)
- [x] Publish to AGOL
- [x] Configure LATM Extract for editing in AGOL (enable editing, enable edit tracking)
- [x] Create/Configure map with 1) [Existing CTM AGOL DM LATM data](https://austin.maps.arcgis.com/home/item.html?id=37cda4749d264a8ea9676e2965018a02), 2) Extract of LATM data (Created in step 2)
- [x] Create/Configure web application for Adding/Editing LATM changes (Editing Widget)
- [x] Testing/Establish process to update LATM data in Maint with changes made in AGOL Extract

Future Steps
- [ ] Update LATMID once features append in Maint/Determine automated process if needed
