### ISSUE TITLE
Create TDS Task Board

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#12749]
### Create a task board for the TDS Portal to replace the current Reviewer Dashboard. 

- [x] Create new Task Board (TB) Page
- [x] Create TB menu, Links to 'My Tasks' page
**On My Tasks, create views per object**

    - [x] TIA
    - [x] TDR
    - [x] TDA
    - [x] SIF
    - [x] Determinations
    - [x] Vision Team comments
    - [x] TIA Submissions

- **On the task objects:**

    - [x] Link to record detail pages
    - [x] Filters on each views based on status
    - [x] Quick View feature

- [x] Remove Reviewer Dashboard top nav
- [x] Home Page: Remove old buttons (both dashboards) & add the TB button

**Comment by TracyLinder** [comment]
Meeting w/ Chrispin on 7/11 to sync on functional criteria.

**Comment by TracyLinder** [comment]
This has been prototyped. 

- [ ] Create new Task Board (TB) Page


- [ ] Create TB menu:

- [ ] Link to 'My Tasks' page

- [ ] On My Tasks, create views per object

- TIA
- TDR
- TDA
- SIF
- Determinations
- Vision Team comments
- TIA Submissions


- [ ] Remove Reviewer Dashboard top nav
- [ ] Home Page: Remove old buttons (both dashboards) & add the TB button


Link to record detail pages
Filters on each views based on status
Quick View feature


Case Load is moved to reporting; we don't need the feature on the TB.
⁉️Talk to stakeholders about the current 'Completed Work' page -- this can be accomplished via the advanced search or in the service landing page. What't the need? ⁉️





VISION TEAM DASHBOARD Conversation
- Include in the TB
- Talk to stakeholders about removing the Vision Team Dashboard.

Think/talk about a singular advanced search feature.

**Comment by TracyLinder** [comment]
### Update

Chrispin has built all the features for this. Should we go live & retire the dashboard later. Or should we get stakeholder approval before we switch over? 
- Lets inform them somehow before we make the switch. They've already given us approval.

**Comment by TracyLinder** [comment]
### Tracy & Chrispin Sync 8/10/23

**Tasks/Next Steps**

1. (T) Send notification email: let them know both reviewer dashboard & task board will be active for about a month. 
2. (C) Rollout wed 8/16 midday

**Comment by ChrispinP** [comment]
TDS Task Board page is now live.

- Code updated
- Permission & Display rules added
- Home Button added

![image](https://github.com/cityofaustin/atd-data-tech/assets/67915167/cd51c3fd-b3d9-48af-83ff-7425ad7ddff5)

**Comment by ChrispinP** [comment]
Tasks complete; Home buttons removed and Top Nav updated to hide Reviewer Dashboard & Vision Team Dashboard.

**Comment by ChrispinP** [comment]
Followup actions documented on #13677 . Closing
