### ISSUE TITLE
Fleet Management Feedback - 7/7

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#12778]
# Billy's Feedback

FLEET MANAGEMENT FEEDBACK
- [x] can we add a space for the "assigned driver"?
- [x] can we / should we add a space for "rental / owned / other"?
- [x] can we / should we add a space for "license plate"?
- [x] can we / should we add a space for "group"? ie. Timing, Inspectors (DCS), Inventory, etc. There are 5 or 6

**Comment by dianamartin** [comment]
# 6/30
Christina said
>CT says
I was thinking the work group might be nice! Then you could have buttons to filter the list based on work group! But totally up to y’all! Same with the license plate - signs and markings didn’t add that because the plate could be found from knowing the vehicle number and that was more important to them! But if AMD wants to see license plate numbers it could be added

**Comment by ChristinaTremel** [comment]
Scheduled meeting with Billy, Diana, Susanne and me for 7/10 to discuss the feedback.

**Comment by dianamartin** [comment]
# 7/12
## Build Steps
-  Add the following fields to object table `feleet_vehicle_tracking`
- `Assigned Driver` - connection field to "Accounts" (like Created By field)
- `Vehicle Type` - Multi-choice field 
  - Rental
  - Owned
  - Other
- `License Plate` - short text 
  - possible validation?
- `Workgroup` - Multi-choice field (on work orders) 
- "? ie. Timing, Inspectors (DCS), Inventory, etc. There are 5 or 6

**Comment by susannegov** [comment]
# 7/12
- [ ] Added fields in `fleet_vehicle_tracking` object
- [ ] Added `License Plate` in `fleet_vehicle` object (Must be unique)
   - [ ] Validation: Character Count lower than 3
   - [ ] Validation: Character Count higher than 8
   - [ ] Validation: does not match regex expression `^[A-Z0-9]{3,8}$`
- [ ] Added `License Plate` (from fleet_vehicle object) to Add Vehicle page
   - [ ] Instructions: License plate number should be all uppercase without special characters 
- [ ] Added `Vehicle Type` `Assigned Driver` and `Workgroup` to Add Vehicle Log` page

**Comment by susannegov** [comment]
# TO do
- [ ] Clean up duplicate vehicle name `TIME LOG | DUP Correction

**Comment by ChristinaTremel** [comment]
- Closing this out because feedback was addressed and we have issue #12510 open in Review/QA for when we show Billy.
