### ISSUE TITLE
[Data Tracker] Delete a PHB Study

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#12770]
> What application are you using?

Data Tracker

> Describe the problem.

Please delete the PHB study at Rundberg and Teasdale, Study ID # 347.

Thank you

> How soon do you need this?

Flexible  — An extended timeline is OK

> Requested By
Renee O.

Request ID: DTS23-108425

**Comment by ChristinaTremel** [comment]
@dianamartin could I assign this to someone on your team? And maybe I should watch the process so I could help with these issues in the future. 🙂

**Comment by KaroEngstrom** [comment]
# Tue 7/18/23 

- [x] Find the requested study to delete in `studies` object records 
- [x] Check the front end page https://atd.knack.com/amd#studies for the Study ID
![image](https://github.com/cityofaustin/atd-data-tech/assets/100615928/f5c660ba-c6d3-47c5-a3eb-fb6769d3a69e)
- [x] Delete record 
- [x] Check front end page again 
![image](https://github.com/cityofaustin/atd-data-tech/assets/100615928/9aee6a39-8592-4ee4-8ea8-7c5684bd4a58)
- [ ] Update requester 
- [x] Add issue to change log epic

**Comment by dianamartin** [comment]
@ChristinaTremel see Karo's steps above ☝🏽
