### ISSUE TITLE
Please delete signal study ID 54; LAKE CREEK PKWY / LAKE CREEK PKWY

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#12815]
> What application are you using?

AMD Data Tracker

> Describe the problem.

Please delete signal study ID 54; LAKE CREEK PKWY / LAKE CREEK PKWY (South of 620 at Walmart/Harmony School/Apt. entrances).  We have determined that this location is ineligible for study at this time.  

> Describe the outcome you'd like to see when this feature is implemented.

Clean up of study data.

> Describe any workarounds you currently have in place or alternative solutions you've considered.

We could mark it as cancelled.

> Is there anything else we should know?

Thank you

> Requested By
Renee O.

Request ID: DTS23-108490

**Comment by KaroEngstrom** [comment]
# Tue 7/18/23
- [ ] Find the requested study to delete in `studies` object records 
- [ ] Check the front end page https://atd.knack.com/amd#studies for the Study ID
- [ ] Delete record 
- [ ] Check front end page again 
- [ ] Filter if needed to share with requester
- [ ] Update requester 
- [ ] Add issue to change log epic
