### ISSUE TITLE
Migrate all ETLs to Airflow v2

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#12860]
## Airflow v1 ➡️  Airflow v2

If you complete one of these, convert the item to an issue and add it to this epic 🚢 

- [x] atd_knack_signals - #12864
- [x] atd_knack_signs_work_orders - #12864
- [x] atd_knack_signs_markings_time_logs - #12864
- [x] atd_knack_markings_work_orders_jobs - #12864
- [x] atd_knack_work_orders_markings - #12864
- [x] atd_knack_inventory_items_finance_to_data_tracker - #12864
- [x] atd_knack_signal_work_orders - #12864
- [x] atd_knack_metrobike_kiosks - #12864
- [x] atd_knack_cctv_cameras - #12864
- [x ] atd_knack_signs_markings_reimbursements - #12864
- [x] atd_knack_signs_work_order_materials - #12864
- [x] atd_knack_signs_work_order_attachments - #12864
- [x] atd_knack_signs_work_order_specifications - #12864
- [x] atd_knack_mmc_activities_to_s3_to_socrata - #12864
- [x] atd_knack_mmc_issues - #12864
- [x] atd_knack_markings_attachments - #12864
- [x] atd_knack_markings_materials - #12864
- [x] atd_knack_markings_specifications - #12864
- [x] atd_knack_school_beacons - #12864
- [x] atd_knack_inventory_items_nightly_snapshot - #12864
- [x] atd_knack_detectors - #12864
- [x] atd_knack_signal_cabinets - #12864
- [x] atd_knack_flashing_beacons - #12864
- [x] atd_knack_dms - #12864
- [x] atd_knack_arterial_managment - #12864
- [x] atd_knack_pole_attachments - will not migrate per [this slack thread](https://austininnovation.slack.com/archives/C026ZRP1TH8/p1689606626120099)
- [x] ~atd_knack_travel_sensors~ these devices are no longer maintained
- [x] atd_metrobike_trips - https://github.com/cityofaustin/atd-airflow/pull/121
- [x] #12882
- [x] #12889
- [x] #12897
- [x] https://github.com/cityofaustin/atd-data-tech/issues/12952
- [x] https://github.com/cityofaustin/atd-data-tech/issues/12495
- [x] atd_knack_signal_retiming
- [x] #12992
- [x] #13238
- [x] atd_knack_metadata_data_tracker_to_postgrest - JC: i don't think we should migrate this
- [x] #12993

## Prefect v2 ➡️ Airflow V2
- [x] trail counters - https://github.com/cityofaustin/atd-airflow/pull/118
- [x] ATD Knack Services: Artbox Signals - #12904
- [x] ATD Knack Services: Data Tracker Location Updater - #12904
- [x] Knack Services: Data Tracker Corridor Retiming - #12904
- [x] Knack Services: Data Tracker SR Assign Signals- #12904
- [x] Knack Services: ROW TCP Submissions to Socrata - #12904
- [x] Knack Services: Signs Markings Contractor Work Orders - #12904
- [x] Knack Services: Street Segment Updater - #12904
- [ ] traffic incident reports ([flow](https://github.com/cityofaustin/atd-prefect/blob/main/flows/atd-traffic-incident-reports/traffic-incident-reports.py))
- [x] Finance Data Publishing/Finance Data Publishing
- [x] #13084
- [ ] Bond reporting
- [ ] Parking data

**Comment by johnclary** [comment]
i am closing this! @Charlie-Henry those remaining prefects are complete right?
