### ISSUE TITLE
SMD Supervisors would like to receive an email when MMC Operators submit a request

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#12872]
> What application are you using?

SMD Data Tracker 

> Describe the problem.

When MMC Operators submit a request, SMD Supervisors would like to receive an email. 

Would like the email to go to Joe Michael, Chris, Ruben, and Anthony S.

> Describe the outcome you'd like to see when this feature is implemented.

Our team will be able to immediately issue urgent/priority work orders pertaining to the installation of signs in place of malfunctioning school zone beacons.

> Describe any workarounds you currently have in place or alternative solutions you've considered.

Someone from the MMC will call or email.

> Is there anything else we should know?

ASAP please.

> Requested By
Cathy K.

Request ID: DTS23-108590

**Comment by ChristinaTremel** [comment]
Spoke with Allyson and in the `Instructions/Comments` field, they will be including "Temporary school zone sign request" language.

### Need to test 2 scenarios to sending emails to Supervisors:
1. If `Instructions/Comments` contain "temporary school zone sign request", trigger email notifications
2. If work order is `Created By` a person with the `Title` "TMC Operator", trigger email notifications

**Comment by susannegov** [comment]
@dianamartin can you add test notes on what the process is?

**Comment by dianamartin** [comment]
# Test Process
## Configure Backend
- [ ] Create new SMD Tracker TEST Environment (run it so it does it overnight)
- [ ] Update App Inventory (in DTS portal) to deprecate TEST | 17 NOV 2022
- [ ] Update New Signs Work Order
- [ ] Add email rule
  - [ ] When user is "TMC Operator" title, set rule to email `your email address`
- [ ] Update Test Viewer - Title "TMC Operator" (or MMC Operator, whichever it is)
## Test Email Process
- [ ] Test Add New Signs Work Order 
- [ ] When user is "TMC Operator" title, set rule to email `Joe Michael, Chris, Ruben, and Anthony S.`

**Comment by dianamartin** [comment]
@ChristinaTremel @susannegov I added notes here ☝🏽

**Comment by susannegov** [comment]
# 08/02
- [x] Added `CREATED_BY_TITLE` text formula field in `work_orders_signs` object

**Comment by susannegov** [comment]
# 8/4
Recreated email rule in PROD but also added requirement that CREATED BY is Tester Viewer

Need to find a way to link to the new work order in the rule after MMC Operator creates work order. Maybe https://learn.knack.com/article/z36i2it02b-how-to-use-url-variables-to-pre-populate-a-form

**Comment by susannegov** [comment]
# 8/7
- Recreated link to url to work order details - thanks Chrispin 🙏 
- Resubmitted test email in production - sent email to SMD supervisors asking if they received an email

**Comment by susannegov** [comment]
Got confirmation from supervisors that they received the test email
- [x] Remove THIS IS A TEST from subject header
- [x] Remove myself on email send
- [ ] Remove test work orders
- [ ] Check w/ Cathy after she gets back 8/14 if there are any changes needed before closing out

**Comment by susannegov** [comment]
Confirmed with SMD that the emails are being sent and can close this issue out
