### ISSUE TITLE
Creating TPW ServiceNow queue & consolidated legacy queues

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#12873]
# 7/14
## Next Steps
- Talked to CTM to get guidance on how we should deprecate the queues and create a new queue

## Part 1
- [x[ Submit request to CTM to create "TPW IT" - `INC0306593`, `REQ0152625`
  - Determine who should be on queue

### Part 2
- [ ] Refresh knowledge base articles
  - [ ] [AUSTIN TRANSPORTATION: How to Submit/Process Request for IT Support](https://atx.servicenowservices.com/nav_to.do?uri=%2Fkb_view.do%3Fsys_kb_id%3Dcc5111201b4e99d0e8dfc844604bcbce%26sysparm_rank%3D1%26sysparm_tsqueryId%3Db268e65d878cf9d0287cb9d8cebb353c)
  - [ ] Google Doc space to edit - [20230714 - Service Now knowledge articles for DTS Service Request](https://docs.google.com/document/d/1x0-JCYK_4_RgMcRx0nrxAmckSLR39xUuoyd41vZQ_OU/edit?usp=drive_link)
### Part 3
- Move old tickets to new queue
- Submit request to CTM when we're ready to inactivate old queues

_Originally posted by @dianamartin in https://github.com/cityofaustin/atd-data-tech/issues/12671#issuecomment-1636188878_

**Comment by dianamartin** [comment]
# 8/2
- John V. said he talked to CTM and we can't use our new queues until after Oct 1, 2023
- Diana has updated assignment guidance for CTM, in Google Docs

**Comment by dianamartin** [comment]
# 1/2/25
This should have been closed a while back, we created a "TPW IT" work group in CTM ServiceNow.
