### ISSUE TITLE
Mapping of Data Tracker; AMD with Christina

### ISSUE THREAD

**Issue by rebekkabry** [cityofaustin/atd-data-tech#12890]
### Objective 
Map out the data pipeline and details for Data Tracker and other Arterial Management Dashboards. 

### Participants
Christina, Rebekka 
Optional: Diana/Charlie

### Agenda
Add agenda here or create agenda from [this template](https://docs.google.com/document/d/1d_49KW5C_vSz8Bs50v-cxyIJuTNJMwMrh7ypcxRHgZI/edit#) and add link. 

------
- [x] Schedule meeting 7/24/23, rescheduled due to Agile Training 7/20-7/21
- [x] Optional: Schedule debrief
- [ ] Meet and take notes
- [ ] Optional: Debrief with DTS team members
- [ ] Create resulting issues
