### ISSUE TITLE
Testing Feedback Meeting for Signal Engineer Work Orders 

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#13104]
### Agenda

------
- [x] Schedule meeting - scheduled for August 9th
- [x] Meet and take notes
- [x] Optional: Debrief with DTS team members
- [x] Create resulting issues

**Comment by ChristinaTremel** [comment]
First day of testing, Brian G sent this feedback:

> 1. I tried one of these today and my first bit of feedback is that the automatic time entry is not going to work well.  It automatically enters the time when you arrive (if you remember to start your tickets then) and then automatically inputs the time when you submit the ticket.  I cannot edit that after the fact nor do I think we will want to.  I recommend leaving those boxes open and having a link NOW that will autopopulate the box with the time.  This way if we start a work order and then close the form or lose it, it isn’t all gone. I am sure over time we will get used to clocking it when we first show up but there are certainly times we show up that there is a safety concern that should be addressed immediately and I think that has to be more important than these tickets.  Also we won’t know when we leave until we actually leave… so I am proposing having the tickets populate the time for when we are leaving and we can fill it out when we are finished at the site and we can put the time we arrived.  Usually, it will be pretty easy for us to estimate arrival time.

> 2. Second bit of feedback is to remove issue received unless that is imperative to have.  We will likely not have that information and it is tedious to go find and enter accurately.

Diana noted that work orders can be edited after being submitted and provided directions for how to edit the work orders. 

Brian followed up with: 
> Thanks Diana! I really believe it would be better to get them right the first time if we can for those days we go to sixteen places. Otherwise it's going to be homework to go back and fix them all and we will likely just be making them up anyway.

> Since it's just day one, why don't we wait and see what the team's experience with this is and whether they agree or disagree or have other ideas about it.

Will follow up on this feedback during this meeting!

**Comment by dianamartin** [comment]
# 7/20
Brian G. texted
>Ok I know how I think the time on the ticket would work best

>Have us do the ticket when we leave and put approximate duration on site. Then it can backfill the arrival time. That would awesome.

**Comment by ChristinaTremel** [comment]
### Feedback Notes:
- [x] Add function to record previous time
- [ ] Add 'Work Performed Signal Engineer'**
   - Detection Check
- [ ] Remove auto time stamp for submitting a leave work site time and allow Engineers to type it in
- [ ] Enhancement to AMD Data Tracker to not allow pop ups to close when clicking outside ??
