### ISSUE TITLE
Update "Journal Voucher" info in AMD Data Tracker - Warehouse Inventory- August 2023

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#13304]
- [x] Spreadsheet emailed from Finance staff month of: marked by Finance as "June 2023" (Transaction dates March 21- July 25 2023)
- [x] Number of records being updated: 1320
- [x] Format spreadsheet [(Review instructions)](https://atd-dts.gitbook.io/atd-knack-operations/warehouse-inventory-updating-journal-vouchers-jv-information)
- [x] Spot check Transaction IDs, no JV information before import: 28610; 24798
- [x] Import records
- [x] Spot check Transaction IDs, JV information exists after import: 28610; 24798
- [x] Email Finance staff that update task complete
