### ISSUE TITLE
Feature: Configure Signal Engineers Work Order/Service Request Form in Prod

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#13302]
# Build Notes

### Created `Work Orders Engineering` object table
- [x] Added details link
- [x] Added fields to table from Test
- [x] Add `New Work Order` button

### Add new field
- [x] `Work Performed` - multiple choice - 
   - `Research`
   - `New Signal Turn On`
   - `Signal Modification Activation`
   - `Signal Timing adjustment`
   - `Upgraded D4 software`
   - ASR - Annual Signal Retiming Corridor / Corridor Zones
   - `Other`

### Create New Work Order | Engineer - form 
> function: creates new work order, Work group: Timing Engineers
 -  [x] `record rule` for Work Order Form
 - [x] TECHNICIAN - logged in account
 - [x] ISSUE RECEIVED TIME - `current date`
 - [x] Add Time log
    - Add `Arrive Time/Date` and `Leave Work Site` to the top of work order form. Set arrive time to current date and leave time to current date, with the option to edit. 
     - Add `Time Log | Editable` table to the top of the Work Order Form page
>function: Opens into Work Order Engineer Details page with embedded form

### Add Time Log table to details page
  - [x] Technician(s)
  - [x] Vehicle(s)
  - [x] Issued Received
  - [x] Arrive at Work Site
  - [x] Leave Work Site 
  - [x] Return To Shop/Home
  - [x] Note

### Update Work Order form 
  - [x] Asset Type - `ASSET TYPE`
  - [x] Signal - `SIGNAL` 
  - [x] Location ID - `ATD_LOCATION_ID`
  - [x] Work Location | Other - if not an asset location - `WORK_LOCATION_OTHER`
  - [x] Work Performed 
  - [x] Work Performed Details - `JOB_DESCRIPTION`
 - [x] Add `Time Log | Non-Editable` table to Work Order Details page

## Record Rule
- Insert a new connected value
- [x] Set `Work Group`: Signal Engineers
- [x] Set `Action`
- [x] Set `Comment`: Work Performed Details

Work Performed | Completed Work | Comment | Action |
--- | --- | --- | -- | 
Research | Research | pull from "Work Performed Details" | This exists
New Signal Turn On | Turn On | "New Signal Turn On" | Added
Signal Modification Activation | Programmed | "Signal Modification Activation" | This exists
Signal Observation | Research | "Signal Observation" | This exists
Signal Timing adjustment | Programmed | "Signal Timing Adjustment" | This exists
Upgraded D4 software | Upgrade Software | "D4" | Added
Other | Signal Engineer Other | Comments section | Added

#### Function - on submittal
  - [x] Create record rule to move work order status to `CLOSED` and `SUBMITTED`

**Comment by ChristinaTremel** [comment]
- Build notes from test build can be found in issue #12122 
- Feedback notes can be found on #13104

**Comment by ChristinaTremel** [comment]
Next steps:
- Fix the `Completed Work

**Comment by dianamartin** [comment]
# 8/10
- `WRK23-197790`
- `WRK23-197800`

**Comment by ChristinaTremel** [comment]
Sent email to BC, Brian G, and the Signal Engineers to let them know that this is ready for Signal Engineers to start using. 🎉
