### ISSUE TITLE
Integrate Polygonizer

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#13414]
## Description

Complete the integration of the Polygonizer, [see repo](https://github.com/frankhereford/qgis-polygonizer)

### Must Haves

- [x] Ensuring that polygons created do not overlap with each other by finding intersections between them and trimming polygon area where needed
- [x] Intersection Leg snapping so that when intermediate segment lengths are sufficiently small, the legs of the intersections will extend to prevent tiny slivers of intersectional roadway polygons

### Nice to Haves

- [ ] Bringing along attributes from the input line network to allow for polygons to be traced back to the constituent line segments that influenced their shape
- [x] Ability to provide a typed-in, integer value to the process parameters
- [ ] Ability to designate a attribute of the input features which govern a set of presets for the polygon creation process parameters for that individual segment, such as street_level for example.

**Comment by frankhereford** [comment]
I want to link this previous issue to the new one, https://github.com/cityofaustin/atd-data-tech/issues/12399. 

Also, as part of this adoption plan, I'd like to have a 1 hour meeting with the dev team to show them around the code in detail and to work with everyone to download and install the QGIS software.

**Comment by patrickm02L** [comment]
## 9/19
- FH Demoed to Mike, Rose, Chia, Patrick
- We should update the Readme that spells out instructions for accessing and using to the main Repo

**Comment by frankhereford** [comment]
This project is going to be superseded by a custom solution being developed internally by the VZ team.
