### ISSUE TITLE
Create "Approve Invoice" page and Requester approval process in Test

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#13485]
In this page in TEST: https://atd.knack.com/test-01-aug-2023-signs-and-markings-operations#reimbursable-reporting/
In this page in PROD: https://atd.knack.com/signs-markings#reimbursable-reporting/
## Admin Process
On (new) "Reimbursable Invoice" table
- [x] Create new trigger button (email notification) 
- [x] Updates "Sent to Requester" field to (Date that was sent)
   - [x] Display Rule: hide on table when "Date" is populated
>Tried trigger, I didn't like it. Chose to do "edit form" instead. There is a record rule to set the date. 
   ![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/98df5df6-99f9-4e76-9ce4-14e7c050df29)

### Edit Form "Send Invoice to Requester"
- ![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/39fd571e-e638-431b-ab2a-5271f99a81cc)

### Email Notification
- ![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/e9665551-73bf-44c9-93da-fb352fccb634)

## Viewer side
- [x] Tab: Review Invoices (square check icon)
![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/4a2cce5e-02be-4d5d-a55c-be90c23af67d)
    - Roles: Viewer
- [ ] Invoice table (filtered by Approver)
- Ability to change Approver to another person
- Only approver that is logged in can see invoices ( similar to the My work orders | created tab)
  - ex. Was Maddie, need to be Kaz
  - Edit button or trigger (ability to click to approve or deny the invoice)
  - Need a link to the Invoice page ( Reimbursements > Signs reimbursements > Invoice Details > Invoice)
  - Need a link to the Invoice page ( Reimbursements > Markings reimbursements > Invoice Details > Invoice)
     - Created a details page and copied the views in markings/signs to the details page)
  ## Approval Process
- Create new field "Reimbursable Status" (multi-choice) on `reimburseable_tracking` 
   - Put this in the table view and in the approve/deny form

### Reimbursable Status
Add `Reimbursable Status` to `reimburseable_tracking`
- Needs Review
- Waiting for Approval
- Approve
  - [x] Add new field `Approver` - `Accounts - connection field` to `reimburseable_tracking`
  - [x] Add new field `Comments` - `paragraph text` to `reimburseable_tracking`
- Approve with FDU Change
- Approve with comments
- Reject with comments
- Closed 
  - [x] Staff to edit field `FM it hit Budget` - `01` (ex. Jan)
  - [x] Created new field "Re_Closed Date" field - `Date/Time` to `reimburseable_tracking`

_Originally posted by @dianamartin in https://github.com/cityofaustin/atd-data-tech/issues/12436#issuecomment-1594988834_

- Notes on Creating "Approve Invoice" page in test are on issue #12436

**Comment by ChristinaTremel** [comment]
Talked to Kati about this "Approve Invoice" Knack process during the SMD Sprint Review. She noted that they won't want to change the approval process until the start of the new fiscal year in October.

**Comment by susannegov** [comment]
# Reimbursable_tracking table
- [ ] Reimbursable Status type multiple choice custom sort, dropdown one selection
```
Needs Review
Waiting for Approval
Approve
Approve with FDU Change
Approve with comments
Reject with comments
Closed
```

**Comment by ChristinaTremel** [comment]
9/28
- On Invoice View, add a link the work order details page to that
- Create new field named `Approver_Comment`

**Comment by susannegov** [comment]
@ChristinaTremel ready for Review/QA.
- Changing from Approve and Reject column into Review column
![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/3f8e3e21-2c91-4d73-9239-c66cfed20b1e)
- Review Action
![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/6e1ec037-9dbe-4347-871a-b4661226fa6a)
- Review Invoice Detail
![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/bb8d3a5d-ef4a-40b0-b399-2e319199c128)

**Comment by ChristinaTremel** [comment]
## To ask Signs & Markings
- Do they want an `Approve Invoice` date field?
