### ISSUE TITLE
Importing data from Historical PM -> PM work orders object in AMD Data Tracker

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#13517]
- When working on #12707, we started exploring how we could bring Historical PM data into the EDP dataset that AMD is requesting. Realized the best path forward is to migrate data from `signals_preventative_maintenance_HISTORICAL` object to the current `preventative_maintenance_work_order` object. I looked into the fields from each table and most fields from the historical data does match the new preventative maintenance object. Creating this spike issue to migrate the data from the Historical object table to the Current object table.

_Originally posted by @ChristinaTremel in https://github.com/cityofaustin/atd-data-tech/issues/12707#issuecomment-1690533549_

**Comment by ChristinaTremel** [comment]
# 9/21 - Testing Import of Historical PM Records -> Preventative Maintenance Work Order object
- Cleaned up and imported 5 test records into the test application
   - Adjusted `Created Date` and `Modified By` field to emails instead of users names for importing purposes
- QC'd the test records and saw that they successfully imported into the new Preventative Maintenance table
   ![image](https://github.com/cityofaustin/atd-data-tech/assets/61209591/febb68d4-04b1-4492-880c-9cbe2dab9540)
- Also noticed that this import resolved an issue I didn't previously notice. With the current separation of Historical Preventative Maintenance, the work orders associated didn't have the PM records connected. When importing the historical PM records into the new PM object, records now show in the work order associated
  - **Before:**
      ![image](https://github.com/cityofaustin/atd-data-tech/assets/61209591/57943053-e820-4bc8-b4cb-b57eff01faa4)
   - **After:**
      ![image](https://github.com/cityofaustin/atd-data-tech/assets/61209591/5044a3a0-9136-435f-b30f-29c8a934bbc9)
- Pages and Tables that will need to be updated after importing historical records -> new PM
   - [Signal Details page](https://atd.knack.com/amd#signals/signal-details/58164b9af9195edb2a5e3a07/):
      - Remove `Preventative Maintenance | Historical` table because records will all exist on the `Preventative Maintenance` table
   - [Preventative Maintenance Page](https://atd.knack.com/amd#home/preventative-maintenance/):
      - Remove `PM Dates (Historical)` column because those dates will show up in the `Maintenance Date` column
         ![image](https://github.com/cityofaustin/atd-data-tech/assets/61209591/092aa9fe-9950-49be-91c9-7a02dc3ecf5f)

**Comment by ChristinaTremel** [comment]
Sync'd with MMC and Jorge to let them know that I'll be importing historical records into the PM work order object and gave them a heads up that they might notice some duplicate data while I'm doing the import. They confirmed that I won't be impacting any of their processes. ✅

**Comment by ChristinaTremel** [comment]
## 5/22 Import of Historical PM Records -> Preventative Maintenance WO object in prod
- Exported all `work_orders_preventative_maintenance` records into csv
   - `1012` work_orders_preventative_maintenance records 
- Exported all `signals_preventative_maintenance_HISTORICAL` records and cleaned up records
   -  Adjusted Created Date and Modified By field to emails instead of users names for importing purposes
   - Added `Message` field to track the imported records with this message 
      > These records were imported from the Historical Preventative Maintenance Table
   - `5014` signals_preventative_maintenance_HISTORICAL records to import

![image](https://github.com/cityofaustin/atd-data-tech/assets/61209591/c62f0fe7-de8c-4d48-9bc7-f160759ae94d)

**Comment by dianamartin** [comment]
# 1/25/24
On the `signals` dataset, I noticed three fields that related to PM
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/f77beac1-4212-47a0-ae4d-7d57ea5aa803)
- we might want to deprecate these fields in "red"

## Next Steps
- [x] Export a back up - `20240125_signals_preventative_maintenance_historical_5020_BACKUP`
- [x] Export a back up - `20240125_work_orders_preventative_maintenance_1377_BACKUP`
- [ ] Review import spreadsheet - `signals_preventative_maintenance_historical_240125`

**Comment by dianamartin** [comment]
# 1/26/24
Reviewed import, showed that it failed
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/e523bf46-4466-49ef-a0ca-55c7686c1249)
- `3100 records` imported in before the failure
- Before the import we were on PM_ID; `1592` 
- Filtered PM_ID higher than `1592`, it resulted in the `3100 records` 
- Figured out which record was last imported from the import spreadsheet
- `1920 records` left over
- reimporting `1920 records`

**Comment by ChristinaTremel** [comment]
- Checked records that had been imported in and everything looks great. 🎉
- Let Jorge and Blake know that we're removing the historical PM table: 
   > Hey y'all! I wanted to give y'all a heads up because I think y'all interact with Preventative Maintenance stuff in Data Tracker! But before, PMs were being tracked on two tables on the signal details page (one had the historical way of tracking and the other was tracking the PMs in the new process). Well Diana and I finally imported the historical stuff into the new PM record table so everything can be seen in one place ✨ That being said, I wanted to let y'all know what were going to remove the historical table from the Signals Details page (because now the historical stuff is in the new Preventative Maintenance table)
- Called Billy letting him know we're removing the historical PM table after hearing back from Jorge
- [x] Removed `Preventative Maintenance | Historical` table from the Signals Details page because that information can be found in the other preventative maintenance table now
![image](https://github.com/cityofaustin/atd-data-tech/assets/61209591/d4b3a7fe-f41e-4590-9232-4780afca17c8)
- Will need to create a tech debt issue to archive the `signals_preventative_maintenance_historical` object in Knack
