### ISSUE TITLE
Maximo, District Maintenance: Downtown Enhancement Business Process

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#13544]
Division manager is requesting a Sidewalk Maintenance report on:
- where the team is working each week and day 
           (once a week on Thursdays)
- a summary report (location, staff, materials, hours for power washers and cyclones for each night)
           (daily by 9 am, Mon-Fri)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc1JDIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--bf6535649523784a0334c33787fda0dbc2860995/Capture.png)
[Downtown Maintenance Clean-up copy.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc1ZDIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1f0c53685cca8d7585e16b1b2dc90bb821931b99/Downtown%20Maintenance%20Clean-up%20copy.xlsx)
[https://cityofaustin.sharepoint.com/:w:/r/sites/SIM-MaximoDiscussion/Shared%20Documents/Report%20Request.docx?d=wb654d6ccf96b40a1b73e78b29f119a46&csf=1&web=1&e=1EfOq1](url)

**Comment by adry-martinez** [comment]
[Outlook.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc2hDIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--81176aedbcdd9f89f8d0d03baba6f9eef9da8814/Outlook.pdf)

**Comment by adry-martinez** [comment]
- [ ] Update water usage report to filter by work group @YakshDipa 
- [ ] Design test report @YakshDipa 
- [ ] QRG for Sidewalk Cleaning @adry-martinez 
- [ ] Update report to include requirements from AD Hershaw @YakshDipa 
- [ ] Discuss and review with PC Chagoya and Supt Mendoza
- [ ] Execute recurring scheduled report to requested staff monthly @adry-martinez

**Comment by adry-martinez** [comment]
Work orders created and sent instructions to PC Chagoya and Supt. Mendoza. Training session scheduled for next week

**Comment by adry-martinez** [comment]
Create completion checklist for downtown enhancement

**Comment by adry-martinez** [comment]
Conversation with Superintendent Mendoza to discuss reducing # of parents/children due to change in operations

**Comment by adry-martinez** [comment]
Met with South District to discuss new process for Downtown Enhancement. Indicated no longer supporting multiple streets and will need to remove existing work orders. The Superintendent wanted to clarify the need for multiple work orders, I explained that previous request asked for a count of every time staff responded to cleaning. Superintendent indicated that may not be needed but will clarify with DM Girod on reporting needs for Downtown Enhancement. 

- [ ] remove streets from current list
- [ ] requesting to track Special Projects through Downtown Enhancement's Specifications @YakshDipa 
- [ ] find graffiti removal for street in Failure Reporting
- [ ] talk to @YakshDipa to ask if we can have sidewalk CLEANING added to Sidewalk Problem Codes
- [ ] compile document for Downtown Enhancement with the following:
                          - [ ] Mobility Trail Cleaning
                          - [ ] Special Projects Cleaning
                          - [ ] Paver Repairs/Replacement
                          - [ ] Graffiti Removal on Street and Sidewalk (not in Downtown)
                          - [ ] Marking a WO as Special Project

- [ ]  follow-up with Mendoza for Downtown Enhancement reporting

**Comment by adry-martinez** [comment]
Received PM training from CTM, PM in progress to be created today.

**Comment by adry-martinez** [comment]
DTE PM created. 
23-167381            October
23-167393            November
23-167404            December
Scheduled meeting for Thursday 12/21 for demo with Users

**Comment by dianamartin** [comment]
# 1/24/24
- Data was sent to CTM, waiting on report creation

**Comment by adry-martinez** [comment]
### 1/31/24
Discussed with CTM Nick O. on data requirements for creating BIRT report, currently in progress.

**Comment by adry-martinez** [comment]
**2/11/24**

DTS Maximo has a scheduled meeting with CTM for status updates.

**Comment by rebekkabry** [comment]
**Reporting Insights**
_Meeting with Adry and Rene_

- We are already capturing the data points requested 
- Process has been implemented
- Currently pending a report to show the work 
- Request ask from R
- We have a portlet but it is very high level, only shows a preview, not the detailed information that the report is given - has been asked to expand the data. 

Each Group 
 - North - more pavement support 
 - Central - more geared to CSR response and alley 
 - South - oversees guardrails and sidewalk cleaning = downtown enhancement
Connected to the TPW Stat -

**Comment by adry-martinez** [comment]
### Mon, May 6, 2024
This issue has been converted to an Epic due to the large number of parts that is part of this new group's process. Please see the issues attached above.

**Comment by rebekkabry** [comment]
# 5/20/24 Meeting with CTM

- CTM provided the numbers needed, so the queries can be ran. Not a formal report yet. 

@adry-martinez Are the queries enough to create the start centers needed for this request?

**Comment by rebekkabry** [comment]
# 6/13/2024 
Following  up with Adry to see if the queries provided can allow us to create a report or if CTM's support is still needed?

**Comment by rebekkabry** [comment]
# 7/14/2024 

Following up with CTM on query status.

**Comment by rebekkabry** [comment]
# 5/5/25 

TO DO 
- @rebekkabry - add all the Children tickets into May - Sept 2025 Parent work orders 
- 
Summary | Work Group
-- | --
Sidewalk Cleaning, East 6th St heading   west of Red River to Trinity | SBODTM
Sidewalk Cleaning, Trinity - Cesar Chavez   to 9th | SBODTM
Sidewalk Cleaning, East 6th St heading   west of IH-35 to Red River | SBODTM
Sidewalk Cleaning, Cartias | SBODTM
Sidewalk Cleaning, Red River - Cesar   Chavez to 9th | SBODTM
Sidewalk Cleaning, East 6th St heading   west of Trinity to Brazos | SBODTM
Sidewalk Cleaning, East 6th St heading   west from Brazos to Congress | SBODTM

- ![Image](https://github.com/user-attachments/assets/80fa3fe3-e942-4dc8-a3fd-51a63814b6f3)
- ![Image](https://github.com/user-attachments/assets/729258f2-d18e-4dce-bb5d-87a2dca05660)
-![Image](https://github.com/user-attachments/assets/baf8d474-c8b6-44e7-8103-4be442ca56e7)
- Complete. Advising stakeholders
- ![Image](https://github.com/user-attachments/assets/652c0a44-add8-45f9-af03-5a90060bb8a7)

**Comment by rebekkabry** [comment]
# 6/5/25 
- All work orders for FY25 have been created and added manually. Confirmed with DTE stakeholders (Eli and Vince) that work orders are in MAXIMO. They will continue to add data and or transfer data into Maximo. Closing this ticket.
