### ISSUE TITLE
New Features Requested to Finance Service Requests Following Usability Feedback Sessions 

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#13557]
### Cancel Requests
- [x] Add `Cancel` button if status is `Not Submitted` or `Submitted`. If submitted, user would reach out to Finance staff.
   - Added `Cancel Request` button to Requester Service Request Details page
   - Record rule to update Status to `Cancelled` and to update the `Modified By` and `Modified Date`
   - Added rule to not allow Requesters to cancel SRs in any status other than Submitted and Not Submitted

### Comments Function
- [x] Ronnie asked if we could request changes with a Comments feature on the SR Details
   - Added connection to `Comments` object with `Service Requests`
   - **Service Request | Requesters** `SR Details` page - Added comments table and configure based on how we have the comments configured for Purchase Requests. Also added the `Add Comments` button.
   - **Service Request | Admin** `SR Details` page - copied the comments table and added the `Add Comment` button
   - [ ] @dianamartin Need to update CSS for changing the color schema of the `Add Comment` button. 

### Work around to address requests for New FDU & New TK in same SR
- [x] Sometimes a Service Request will request a new FDU and TK to be set up. In these requests, Finance will be creating a new Unit and then will charge the new TK to the new Unit that’s being set up. In these situations, the Requester doesn’t know what the Unit will be for the new TK (but will know the Funding and Department information).
    - Requesters use `Encumbering FDU` and enter the known funding and department and use a `0000` placeholder in the FDU section
    - Updated Display Rules for Job Type `TK` and TK action is `New` to rename "Encumbering FDU" field to say "Encumbering FDU - enter "0000" if requesting a new Unit"
      - `Add Job` page
      - `New SR Job | Admin` page
      - `New SR Job | Requester` page

### Followed up with Sharon 9/6:
- [x] #13856
   - Going to add  `Job Subtype`
       - Change FDU, TK, or Subproject Name
       - Change FDU Subproject
       - Service Agreement
       - SeRF
       - Other

**Comment by ChristinaTremel** [comment]
Converted outstanding action item to a new issue. Closing this issue!
