### ISSUE TITLE
[URGENT] The public facing AMD Signal Evaluations page (https://data.mobility.austin.gov/signal-evaluations?x...

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#13719]
> What application are you using?

AMD Data Tracker

> Describe the problem.

The public facing AMD Signal Evaluations page (https://data.mobility.austin.gov/signal-evaluations?x=-97.711587&y=30.416074&z=14.86) is not updating.  I created a new PHB request at Amherst and Eton on 8/31/2023.  This request is not showing up on the Signal Evaluations page.  I have an idea why and explained below but feel free to contact me.  

> Is there anything else we should know?

I'm thinking this may be because we no longer create "Evaluations" for PHB requests because we don't evaluate them this way any more.  I am uploading some screen shots to show what is happening.

> Website Address

https://data.mobility.austin.gov/signal-evaluations?x=-97.753468&y=30.335596&z=13.55

Internet Browser: Chrome

> Requested By
Renee O.

[Attachment](https://api.knack.com/v1/applications/595d00ebd315cc4cb98daff4/download/asset/64f9df9e47da43002985fc07/requestmap.jpg) (161.42kb)

Request ID: DTS23-109610

**Comment by ChristinaTremel** [comment]
@chiaberry @johnclary - could y'all check on the Dev side whether the only location statuses that move to the [Signal Evaluations ](https://data.mobility.austin.gov/signal-evaluations?x=-97.711587&y=30.416074&z=14.86) map are: `Not recommended`, `Engineering study`, `Needs funding`, and `Ready for design`?

Renee and I noticed that the new PHB request that's not showing up on the map has a `Recently received` location status so I'm wondering if that's why it's not showing up on the map.

**Comment by johnclary** [comment]
@ChristinaTremel the public map only displays data from the new "Signal Studies" module. I did a quick check to confirm the location Renee is referring to is in the "Signal Requests" module. I don't know if it was ever clarified how the signal requests vs signal studies process was to be shared publicly under the new way the program is managed, but we no longer maintain a public-facing signal request map.

[This issue](https://github.com/cityofaustin/atd-data-tech/issues/13370#issuecomment-1684141088) appears related.

**Comment by ChristinaTremel** [comment]
Ahhh okay that was our other thought when we were looking at it. So we probably need to figure out how to address getting new "Signal Requests" onto the map because not all signal requests will have signal studies. 🫠

**Comment by ChristinaTremel** [comment]
## 9/7
- Let Renee know that the Signal Evaluation map only includes signal studies and that's why the most recent signal evaluation isn't showing up on the map. 
- We need to have a bigger discussion on how to communicate PHB data and signal evaluations to the public. Renee will be out of office over the next couple of weeks, but would like me to schedule a discussion for when she returns in early October. Asked to include her, Brian C, and Andres Z. 
- Asked her if this issue could wait until we figure out how to improve the Signal Evaluation map and Renee noted that these issues have probably been this way since before she left so hopefully it can wait another few weeks.
- Going to remove the urgent tag from this issue because it's something we're waiting a few weeks on.

**Comment by ChristinaTremel** [comment]
## 10/5 Meeting
**Attendees:** Renee, Andres, Brian C, Christina, and Peter

## Background Details 
- Problem: Map only brings in signal studies and it brings in the location status. AMD's process has changed and this means that not all the signal requests have signal studies

### PHBs Process:
   -[ PHB Ranking Criteria Web Map](https://austin.maps.arcgis.com/apps/webappviewer/index.html?id=8d74026477144dafba6c1634a5dc3ad5)
   - Top locations are determined and signal studies are created for PHBs when they meet with TED
   - Signal Studies are created from that point

### Signals Process: 
   - After the MMC CSR phase, they create the request
   - One thing that would help them a lot, is not to have to update the status everywhere. Would like that once a study is started, she doesn't need to update the Signal Request and focuses updates on only the Signal Study
      - Brian C was wondering if studies even needs to be a different object or could we just have the study part of the signal evaluation process
      - When someone requests a signal, not everything should be built so they do an evaluation to determine if a study is required
         - Review crashes
         - Look at traffic
         - Desire for peds to cross
         - Look at all the scores and determine which locations they're going to study
         - In a study, they collect a bunch of data

### How to create signal requests and signal studies
   - Create a location
   - Create a signal study on the `Location Details` page
   - Create a signal request on the `Location Details` page
   - Create a signal evaluation on the `Signal Request
![image](https://github.com/cityofaustin/atd-data-tech/assets/61209591/03993380-d273-4f41-8aad-9c8a1f67082d)

### What's the goal of the signals evaluations map?
   - A couple purposes of the map, internal within TPW and external
   - For Citizens Staff
      - Citizens that have taken time to submit want to know the status of their request
      - As simple as them knowing that it's not recommended. They either have closure or additional reaching out to do.
      - They like to see the timeline and would like to show the process from beginning to end.
      - For TPW staff: 
         - A place for them to look and see if there's an upcoming project here
         - Cost sharing opportunities

- To ensure the map meets the needs of citizens, we should direct the Traffic Signal Evaluations to the `Signal Requests` instead of `Signal Studies`
   - With the old map they wanted to show requests, if it's being studied, and what's under construction
   - Updated map needs to be: 
      - Signal Requests
      - Long term, they also want to add Signals Assets with the statuses:
         - Construction
         - Design
         - Ready for Construction
         - Ready for Design

- [Signal Projects](chrome-extension://efaidnbmnnnibpcajpcglclefindmkaj/https://www.austintexas.gov/sites/default/files/files/Transportation/Arterial%20Management_MMC/Signal_Projects_04-03-2023.pdf)
- Displayed on the AMD Website and manually updated as needed
- Some projects are from Developers
   - If they're from developers, they create signal assets but not always signal requests or signal studies. Thinking in the future, we could potentially capture these as signal requests through the project intake process.
      - BC would like to see developers submit their study and a memo of what they're responsible for.

- Traffic and Pedestrian Signals
   - Doesn't make sense to create assets with the status of `RECOMMENDED - NO FUNDING` when the asset is not going to be built out. Makes sense to create the asset when it appears that these are imminent

## ACTION ITEMS: 
- AMD would like to update the [Traffic signal evaluations dashboard](https://data.mobility.austin.gov/signal-evaluations?x=-97.711587&y=30.416074&z=14.86) from showing Signal Studies -> Showing Signal Requests
   - Will need to bring this to the next Dev + Product sync to scope this out

**Comment by ChristinaTremel** [comment]
- Met on 1/19 and 1/30 to work on streamlining AMDs process between Signal Requests, Signal Evaluation, and Signal Studies 
- Work flow can be found on [this Miro board](https://miro.com/app/board/o9J_kgqqLXE=/)
- They are wanting to do some major updates with statuses and set up record rules to update statuses as a request moves through the process

# Status Drop Down Updates
### Location Status
Knack object: locations 
Field: Location Status
- Existing to Update
   - [ ] Not recommended -> Rename to `Signal Not Recommended`
- Add Statuses
   - [ ] Under Evaluation
   - [ ] Void
   - [ ] Signal Recommended
- Delete Statuses
   - [ ] Evaluated
   - [ ] Ineligible
   - [ ] Recently Received
   - [ ] Recommended (funded)
   - [ ] Recommended (needs funding)

### Request Status
Knack object: signal_requests
Field: REQUEST_STATUS
- Add Statuses
   - [ ] SELECTED FOR STUDY
- Delete Statuses
   - [ ] CONSTRUCTED
   - [ ] CONSTRUCTION
   - [ ] DESIGN
   - [ ] INELIGIBLE
   - [ ] NOT RECOMMENDED
   - [ ] ON FLASH
   - [ ] PENDING_TAKEOVER
   - [ ] RECENTLY RECEIVED
   - [ ] RECOMMENDED
   - [ ] RECOMMENDED - NO FUNDING
   - [ ] REMOVED_PERMANENTLY
   - [ ] REMOVED_TEMPORARILY
   - [ ] TURNED_ON
   - [ ] UKNOWN - misspelled..keep?

## Study Status
Knack object: studies
Field: STUDY_STATUS
- Delete Statuses
   - NEW
   - ASSIGNED
   - DATA COLLECTION
   - FINAL/SIGNED SEAL

## Study Outcomes
Knack object: studies
Field: STUDY_STATUS
- Existing to Update
   - RECOMMENDED -> Rename to `Signal RECOMMENDED`
   - NOT RECOMMENDED -> Rename to `Signal NOT RECOMMENDED`

**Comment by ChristinaTremel** [comment]
### Original Github Issue: 



> What application are you using?

AMD Data Tracker

> Describe the problem.

The public facing AMD Signal Evaluations page (https://data.mobility.austin.gov/signal-evaluations?x=-97.711587&y=30.416074&z=14.86) is not updating.  I created a new PHB request at Amherst and Eton on 8/31/2023.  This request is not showing up on the Signal Evaluations page.  I have an idea why and explained below but feel free to contact me.  

> Is there anything else we should know?

I'm thinking this may be because we no longer create "Evaluations" for PHB requests because we don't evaluate them this way any more.  I am uploading some screen shots to show what is happening.

> Website Address

https://data.mobility.austin.gov/signal-evaluations?x=-97.753468&y=30.335596&z=13.55

Internet Browser: Chrome

> Requested By
Renee O.

[Attachment](https://api.knack.com/v1/applications/595d00ebd315cc4cb98daff4/download/asset/64f9df9e47da43002985fc07/requestmap.jpg) (161.42kb)

Request ID: DTS23-109610
