### ISSUE TITLE
Update "Journal Voucher" info in AMD Data Tracker - Warehouse Inventory- September 2022

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#13812]
- [x] Spreadsheet emailed from Finance 9/13/23 staff month of: July-August 7/19 - 8/29/23
- [x] Number of records being updated: 713
- [x] Format spreadsheet [(Review instructions)](https://atd-dts.gitbook.io/atd-knack-operations/warehouse-inventory-updating-journal-vouchers-jv-information)
- [x] Spot check Transaction IDs, no JV information before import: 29876 ✅ ; 18340 ✅ 
- [x] Import records
- [x] Spot check Transaction IDs, has JV information after import: 29876 ✅ ; 18340 ✅ 
- [x] Email Finance staff that update task complete
