### ISSUE TITLE
[AMD Data Tracker] Please add fields school zone beacon for table

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#13836]
> What application are you using?

Other / Not sure

> Describe the problem.

In Datatracker, please add:

In school zone beacon summary table, add field for "Source Power Pole Number" and Y/N field for "Source Pole". 

In school zone beacon summary table, for "Power Source- OH" clarify options to "OH -Aerial" or "OH - Underground"

In the school zone beacon detail table, add the above fields 

https://atd.knack.com/amd#school-zone-beacons/

> Describe the outcome you'd like to see when this feature is implemented.

In Datatracker, please add:

In school zone beacon summary table, add field for "Source Power Pole Number" and Y/N field for "Source Pole". 

In school zone beacon summary table, for "Power Source- OH" clarify options to "OH -Aerial" or "OH - Underground"

In the school zone beacon detail table, add the above fields 

https://atd.knack.com/amd#school-zone-beacons/

> Describe any workarounds you currently have in place or alternative solutions you've considered.

None

> Is there anything else we should know?

Ideally within the next month to begin a new project

> Requested By
Allyson R.

Request ID: DTS23-109790

**Comment by ChristinaTremel** [comment]
### AMD Sprint Review
- Discussed in sprint review and would like to have this done within a month.

**Comment by susannegov** [comment]
# Build Notes
In `school_beacon` object:
- [ ] Add `Source Power Pole Number` type Number
- [ ] Add `Source Pole` type Yes/No field
- [ ] Ask Allyson about  
   - "Power Source- OH" clarify options to "OH -Aerial" or "OH - Underground"


- [ ] add the above fields to school zone beacon detail table
- [ ] add the above fields to school zone beacon summary table

**Comment by ChristinaTremel** [comment]
Allyson checked in today, 9/21 and was asking us to add these new fields to the ODP [School Zone Beacons dataset](https://data.austintexas.gov/Transportation-and-Mobility/School-Zone-Beacons/v6kq-45cf). 

Will create a new issue. 

The request is to add the following fields to the API view and the [ODP dataset].(https://data.austintexas.gov/Transportation-and-Mobility/School-Zone-Beacons/v6kq-45cf)
- source_power_pole_number
- source_pole
- power_source-OH

**Comment by susannegov** [comment]
# To do
- [ ] Add fields to Add School Zone form: https://builder.knack.com/atd/amd/pages/scene_1252/views/view_3071/form/inputs
   - Source Power Pole Number
   - Source Pole
   - Power Source - OH
- [ ] Remove display rule for power_source_OH

**Comment by susannegov** [comment]
@ChristinaTremel this is good to close right?

**Comment by ChristinaTremel** [comment]
- Yes, we can close this issue! The work on adding the fields to the ODP will be completed on issue #13946.
