### ISSUE TITLE
[AMD Data Tracker] Will need to update the Fund drop down to remove the option for 5125 and add 5120

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#13917]
**Related to a problem?**
- This is related to the changes being made department wide and is connected to issue #13791

**Desired Outcome?**
- Eliminate Fund 5125 and add 5120

**Comment by dianamartin** [comment]
# 9/26
In current Purchase Request infrastructure the `purchase_request_items` object has multiple choice fields for `Fund` and `Department`. 
- Fund: 
  - 5125 | MOBILITY FUND
  - 5390 | TRANSPORTATION INVENTORY FUND
  - 5610 | PARKING MANAGEMENT FUND
  - 7026 | 1-35 PARKING PROGRAM FUND
  - 8112 | GCP TRANSPORTATION
  - 8400 | CIP IMPROVEMENTS FUND
  - 8950 | GCP GRANTS FUND
  - 8119 | GCP-MOBILITY P1/2016

- Department: 
  - 2400 | ATD
  - 2507 | CIP ATD
  - 6207 | CIP PWD

**Comment by ChristinaTremel** [comment]
- Discussed this in the Sprint Review and Brian said we should schedule a meeting with Ronnie. Will schedule meeting with me, Diana, BC, and Ronnie.

**Comment by ChristinaTremel** [comment]
- [ ] “Default” FDU needs to change from 5125 2400 3510 to 5120 6200 3510 for any new work orders/transactions
- [ ] Any current work orders/transactions that have 5125 2400 3510 need to have the FDU changed to 5120 6200 3510.  Is that to be manually done by AMD staff or a “behinds the scenes” batch update?
	- DTS will be able to batch update
	- Will update FDU from 5125 to 5120 IF FDU review has been completed and the current FDU is 5125
	- No change to capital FDUs
	- No changes to things that Ronnie will already do the FDU review on - that does mean that Ronnie will continue to see the no inventory used and he tries to put the correct FDU. We could probably replace that FDU?
	- Ronnie needs to find work orders that has some items that have been processed/some that haven’t 
- [ ] Need TKs to be pointing to the 6200 TKs
	- We can check all the task orders to confirm that we have the 6200 
	- Diana is confirming that the task orders have not been updated to bring in 6200. We need to figure out how we need to do that
	- Also saw in AMD Data Tracker that all the TKs are currently inactive because they are tied to 2400. Need to bring in the 6200 and then filter out inactive TKs in the Technicians drop down.

**Comment by dianamartin** [comment]
@ChristinaTremel should we tackle this next week?

**Comment by dianamartin** [comment]
# 11/1
Sync with Christina and dompleted the following tasks.

## Created new object - `financial_funds_numbers_FDU_FUNDS`
- [x] Created new object table `financial_funding_numbers_FDU_FUNDS`
- [x] Added new object fields (see below)
- [x] Connected `financial_funding_numbers_FDU_FUNDING` to `work_order_signals`

## Created new object - `financial_funds_numbers_FDU_DEPT`
- [x] Created new object table `financial_funding_numbers_FDU_DEPT`
- [x] Added new object fields (see below)
- [x] Connected `financial_funding_numbers_FDU_FUNDING` to `work_order_signals`

**Comment by dianamartin** [comment]
# 11/7
- Filtered Inventory Report
  - FY23 and JV Status = "Ready" - `30 records, but all "Adjustments" 
- # of work orders to change `87 records`

**Comment by ChristinaTremel** [comment]
## Fund and Department Changes:
- Work orders `Created Date` is after 9/30/2023 with Fund `5125` and Department `2400` - `816 records` to be updated
- Per Ronnie's JV ready email, `87 records` to be updated to new Fund and Department
- Work orders to be reviewed individually by Ronnie - `33 records`

**Comment by dianamartin** [comment]
# 11/7
## Update new work orders in FY24
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/2efeaa86-7365-4129-94ef-de2ab75c76e6)
- [x] Filtered records: Created Date - after - 9/30/2023, Fund - 5125, Dept - 2400 is `816 records`
- [ ] Update records: Created Date - after - 9/30/2023, Fund - 5125, Dept - 2400 is `816 records`
   - Fund 5125 --> 5120
   - Dept 2400 --> 6200

**Comment by dianamartin** [comment]
# 11/29
- Christina and I set up a work session to do this together
- We took Ronnie's email from 10/24, where he identified transactions and work orders that he needed to move the Fund to `5120`
- There were `87 records` affected
- Spot Checking some work orders

Work Order ID | Current Fund | Current Dept | Notes
-- | -- | -- | --
WRK23-204820 | 5125 | 2400
WRK23-205965 | 5120 | 6200 | we changed everything after 10/1/2023
WRK23-206050 | 5120 | 6200 
WRK23-207430 | 5120 | 6200 
- [ ] Updating spreadsheet with the exact information for import
  - [ ] `5120 | TPW MOBILITY FUND`
  - [ ] `6200 | TPW`

**Comment by ChristinaTremel** [comment]
- [x] Added `5120 | TPW MOBILITY FUND` to the `financial_funding_numbers_FDU_FUNDING` object

**Comment by dianamartin** [comment]
# 12/19
- [x] Backfilled records with Fund `5120` - `1855 records` and updated Dept to `6200`
- [ ]

**Comment by ChristinaTremel** [comment]
All of the updates have been completed! Let Ronnie know we are finished with this request.
