### ISSUE TITLE
Meeting to Review Reimbursable Enhancements

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#13924]
### Objective 
Review Reimbursable Invoice Reporting page with SMD

### Agenda
- Show SMD new table and structure
- Discuss these fields and identify who maintains each field
- Look at existing invoicing tables and clean up to reflect what Johnny updates vs what Ramona updates
- 

------
- [ ] Schedule meeting
- [ ] Optional: Schedule debrief
- [ ] Meet and take notes
- [ ] Optional: Debrief with DTS team members
- [ ] Create resulting issues

**Comment by ChristinaTremel** [comment]
# 10/12 Meeting Notes
### Reimbursable Process
- Do we want to send reminders for invoices that have been `Sent to Approver`? 
   - Can Ramona have a way with determining deadlines for certain invoices?
      - Could we send automated email 5 days after initial email was sent
   - Alternative to add button to send email reminder details
   - The follow up email could say "your approval is overdue" instead of just another "please review within 5 days" reminder email to make it more urgent 
- On the `Approve` and `Review for Approval`
   - Add link to invoice that printable 
- Add `Invoice Approved Date` for any invoices that are the `Approved`, `Approved with FDU Change`, and `Approve with Comments`
   - Remove the `Invoice Approved` yes/no field from Reimbursable Invoice table

###  Review Invoice Process
- For `Approve with FDU Change` 
   - Add the `Funding - FDU` field
   - Remove `Comments` field
- If approval status is `Rejected with Comments`, changes will need to be made and the invoice will need to be re-sent out
   - So email invoice should be an option on these and when clicking email invoice, it should revert the approval status to `Waiting for Review` 
### Fix invoice PDFs COA seal is broken
   - Update invoice doc to reflect TPW
   - Update name to Signs & Markings Division

**Comment by ChristinaTremel** [comment]
- Added these feedback notes to issue #14320 to be addressed when implementing the changes in Prod
