### ISSUE TITLE
Update "Journal Voucher" info in AMD Data Tracker - Warehouse Inventory- September 2022 v2

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#13936]
- [x] Spreadsheet emailed from Finance staff month of: Septermber, 8/15-9/15
- [x] Number of records being updated: 594
- [x] Format spreadsheet [(Review instructions)](https://atd-dts.gitbook.io/atd-knack-operations/warehouse-inventory-updating-journal-vouchers-jv-information)
- [x] Spot check Transaction IDs, no JV information before import: 29251 ✅ ; 18100 ✅  
- [x] Import records
- [x] Spot check Transaction IDs, has JV information after import: 29251 ✅ ; 18100 ✅
- [x] Email Finance staff that update task complete
