### ISSUE TITLE
Rebuild School Beacons Dataset as Internal (EDP) Asset with ETL (and Open Data PII Process)

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#13946]
Allyson is asking us to add these new fields to the ODP [School Zone Beacons dataset](https://data.austintexas.gov/Transportation-and-Mobility/School-Zone-Beacons/v6kq-45cf). 

The request is to add the following fields to the API view and the [ODP dataset](https://data.austintexas.gov/Transportation-and-Mobility/School-Zone-Beacons/v6kq-45cf).
- source_power_pole_number
- source_pole
- power_source-OH

_Originally posted by @ChristinaTremel in https://github.com/cityofaustin/atd-data-tech/issues/13836#issuecomment-1730117059_

**Comment by ChristinaTremel** [comment]
@KaroEngstrom here's the issue

**Comment by KaroEngstrom** [comment]
## Fri 10/13/23
- API table finding...
     - ~~https://builder.knack.com/atd/amd/pages/scene_418/views/view_1187/table~~ This is drawing from `school_beacons_OLD`
     - There doesn't appear to be an API table going into ODP at all; I found one table that looks to be using the old School Beacons object   
     [This is the API View page:](https://builder.knack.com/atd/amd/pages/scene_418/views/view_1187/table)   
     ![image](https://github.com/cityofaustin/atd-data-tech/assets/100615928/07b213f1-1911-4e1c-b156-ea52e775a89e)

- noticed the ODP asset only gets updated "as needed" and doesn't appear to have an ETL 
- the description of the dataset says it's updated daily but it has been six months since it was updated at all and years since the data was updated

![image](https://github.com/cityofaustin/atd-data-tech/assets/100615928/ec239b7a-5b23-4c78-a634-6de33de936bb)
![image](https://github.com/cityofaustin/atd-data-tech/assets/100615928/41e24a45-6a6b-42a8-84e0-9bf3b8b5d15b)

@ChristinaTremel I want to confirm: 
- the correct source table in Data Tracker: 
     ![image](https://github.com/cityofaustin/atd-data-tech/assets/100615928/51ca7e02-bb8f-49a8-9b98-b031af525a15)
          - Only the OLD object has an API table AFAIK and that goes into GIS (?) 
- should there be an API table for this dataset? I'm not finding one. 
- do we want to add the API table and export from there and manually update the ODP asset? 

I'm going to set up a time for us to look at this together.

**Comment by KaroEngstrom** [comment]
@chiaberry ❓ for devs
Is it possible to take a look and see what, if any, ETL history we have for this dataset? 
UID: v6kq-45cf
https://data.austintexas.gov/Transportation-and-Mobility/School-Zone-Beacons/v6kq-45cf

**Comment by KaroEngstrom** [comment]
## Mon 10/16/23 
- talking to Christina - we'll check in with devs (above) and Christina will check with Lance and Allyson to understand their use of this

**Comment by dianamartin** [comment]
# 10/16
After syncing with Karo, I'm remembering what the previous process was. Jaime had helped Charles Z. (former AMD tech) to update in AGOL GIS (I believe). He left AMD, process stopped? This dataset was not ever updated in ODP. We need to huddle to talk about this process. 

- Does the AMD Tech update in Knack AND in AGOL?
  - Should they be?
- Should they be only updating in AGOL --> to Knack?

**Comment by ChristinaTremel** [comment]
- Checked in with John and he confirmed that there is an active ETL that's pushing Knack `view_3086` (the new school beacons object) into AGOL. 
   - Also found that the `Modified By` and `Modified Date` fields are also pushing from Knack so those records are being updated directly in Knack, not AGOL.
- Called Jesse and confirmed with him that he is only editing data in Knack and is only using the AGOL map as a resource to find the school zone beacon locations.

With getting all these questions answered, I think rebuilding the ODP dataset and pointing to the new `school_beacon` object is what needs to happen!

**Comment by ChristinaTremel** [comment]
## 10/17 Meeting
**Attendees:** Allyson, Samir, Christina, Karo, Diana
- Asking specifically for all the fields that are included on the [School Zone Beacons](https://atd.knack.com/amd#school-zone-beacons/) Knack page.
- Also include the following fields:
   - `X` 
   - `Y` 
   - `Created By`
   - `Created Date`
   - `Modified By`
   - `Modified Date`
   - `Location ID`
   - `School Zone Status`

**Comment by KaroEngstrom** [comment]
## Tue 10/17/23 
- sent Excel to Allyson and Samir to review

**Next Steps**
- [ ] Remove old source API view from the Knack API page and replace with the correct source (`school_beacon`) per selected fields
- [ ] Update audience for the Socrata School Beacons dataset (rolling this to EDP/internal only for now due to PII in Created By and Modified By account connection fields) 
- [ ] Export `school_beacon` content from Knack and use to replace the existing dataset with the export 
- [ ] Request ETL from dev - this is a priority script for AMD 
- [ ] Update the metadata in City Data Hub

**Comment by KaroEngstrom** [comment]
@chiaberry and team - the source and target are here: 
For ETL
[Knack Source](https://atd.knack.com/amd#signal-queries/school-beacons-edp/): scene_1556; view_3898
[EDP Target](https://datahub.austintexas.gov/Transportation-and-Mobility/School-Zone-Beacons-Internal/8whb-sg4d): 8whb-sg4d

**Comment by KaroEngstrom** [comment]
@ChristinaTremel  I gave Samir the link to the new dataset so they can connect for now. I made sure to note that it's not yet automatically updated but they can hook it up to their dashboards now.

**Comment by chiaberry** [comment]
@KaroEngstrom @ChristinaTremel Setting the knack services part of the ETL and I noticed that "beacon_long_id" is empty, in knack the field is called School Zone Beacon ID
<img width="485" alt="Screenshot 2023-10-24 at 4 00 05 PM" src="https://github.com/cityofaustin/atd-data-tech/assets/12474808/ed280a87-2994-4b41-a48e-fe6621b63e7c">

**Comment by KaroEngstrom** [comment]
## Wed 10/25/23 
- updated the field to school_zone_beacon_id in the API table column
![image](https://github.com/cityofaustin/atd-data-tech/assets/100615928/9e754680-caf3-4144-8f8f-f6217cd6510e)
- updated the field name and API name in the EDP 
![image](https://github.com/cityofaustin/atd-data-tech/assets/100615928/c49b9e0b-f2b1-4e28-9e0b-787c56f851cd)

@chiaberry  will this roll as is or do you need to do anything else? 

@ChristinaTremel - still nothing from CTM about the account issue related to this; I'll keep you posted

**Comment by chiaberry** [comment]
@KaroEngstrom the column is being populated now! ty

**Comment by chiaberry** [comment]
@ChristinaTremel @KaroEngstrom should I update the knack -> agol ETL to use this new school beacons view?

**Comment by KaroEngstrom** [comment]
@chiaberry I don't think so; the original AGOL API table contains many more geo columns (related to intersection, street segment, jurisdiction, council district, landmark, etc.). I would hold off for now. 

I think these two versions have very different purposes, and combining the source table is more work and then we'd have to solve for the PII, but this brings up something else: 

@ChristinaTremel can you check if this table going to AGOL is already making PII public? Is AGOL public? If yes and yes, then maybe we don't need to solve for PII on the new table/dataset here. I'm talking about this source for the AGOL one: 
https://builder.knack.com/atd/amd/pages/scene_418/views/view_3086/table
It seems to contain account columns.

**Comment by johnclary** [comment]
since we don't have this kind of PII in any of our other asset datasets on the Open Data Portal, it would be really nice if we could get rid of it in this case. some possible work arounds for the stakeholders would be to use a user ID column instead, or we could generate a link a to the asset record in Knack in cases where they needed to see this PII.

another downside of making this dataset private is that we will no longer have any public school beacon dataset on the open data portal.

**Comment by ChristinaTremel** [comment]
Discussed the topic of how to move forward with publishing fields with peoples names during the sprint review. Went over 3 options. Lance said they would prefer to have a separate dataset with peoples names. 
- **Options:**
   - Having 2 datasets, one public and one private
   - Just keep dataset in EDP
   - Use a user ID for `assigned to` field

**Comment by KaroEngstrom** [comment]
## Wed 11/8/23
- having asked Tyler about this last week, they had mentioned hidden columns and derived views as solutions. I asked them more about how those would work with both ETL and the reporting out to PowerBI. Heard nothing back, so I nudged them again today. 
- last week, @johnclary mentioned in Slack that "in our Dev + Product sync we decided to try converting the names to first name + last initial via our Knack ETL script"

**Comment by KaroEngstrom** [comment]
## Mon 11/13/23 
- Tyler proposed a solution that I want to try on here (having our PII and sharing out without it)
- I'll read up on it and attempt to apply to the current dataset (with no ETL), and if that works, we can turn on the ETL to test

**Comment by KaroEngstrom** [comment]
## Week of 11/20/23 
- per dev product sync last week, checked with Nick at TT to see if the 4x4s could be swapped in cases where we needed to pull back an existing asset, add PII, and created a derived asset to share publicly; the answer was NO 
- he suggested the solution of hiding views again (which was a test fail last week) but asking him again if a draft view (and thus the hidden PII) can be accessed by an internal user or named collaborator via Power BI 
- in general, he's proposing that having the 4x4 (and thereby URL) change might not be that dire if the assets are no very popular; send the sample of [Traffic Signal Work Orders](https://data.austintexas.gov/Transportation-and-Mobility/Traffic-Signal-Work-Orders/hst3-hxcz) to what the likely level of engagement is with these assets 
- WAITING ON: final details on the hiding columns option, and then will re-check with devs

**Comment by ChristinaTremel** [comment]
Compared fields already available on [school_beacons>GIS](https://builder.knack.com/atd/amd/pages/scene_418/views/view_3086/table) API view on Knack with the new [School Beacons EDP ](https://builder.knack.com/atd/amd/pages/scene_1556/views/view_3898/table)API view we created that we want to combine. 

The following fields need to be added to the [school_beacons>GIS](https://builder.knack.com/atd/amd/pages/scene_418/views/view_3086/table) API view: 
- [ ] `school_zone_status`
- [ ] `school_name`
- [ ] `source_power_pole_number`
- [ ] `source_pole`
- [ ] `power_source_oh`

Then we need to rebuild the School Beacons Dataset on the City Datahub and point it to the school_beacons>GIS API view and add these fields to the dataset (formatting of field names is formatting as shown on API view table) 
- School Zone Beacon ID
- SCHOOL_BEACON_ZONE_ID
- Clock ID
- Beacon ID
- ZONE_NAME
- school_zone_status
- school_name
- Asset Type
- Direction
- AM Plan
- PM Plan
- PM 2 Plan
- source_power_pole_number
- source_pole
- Power Source
- power_source_oh
- Power Feed
- LOCATION_NAME
- location
- Approximate Address
- x
- y
- Created Date
- Created By
- Modified Date
- Modified By

**Comment by KaroEngstrom** [comment]
@ChristinaTremel  Reading your update above, does https://datahub.austintexas.gov/Transportation-and-Mobility/School-Zone-Beacons-Internal/8whb-sg4d need to be rebuilt again? It was the one created for this ask. 

I realize we want to combine the source API table into one (the existing GIS one) but I think the dataset could stay. The only thing we're waiting for a decision on is the PII solution (how to manage internal / external datasets; my previous comment).

**Comment by KaroEngstrom** [comment]
## Wed 11/29/23 
- updated the name so this will be easier to find as it's become the PII component load-bearing issue 

### Vendor
- the latest is that they cannot swap the 4x4s and their best suggestions for our ask are as follows (in their words): 
Option 1. Add the PII column(s) to the established EDP datasets, make those datasets private, and then create a derived view of the data that wouldn't have the PII columns and publish it publicly. This would keep the 4x4s the same for users with access and also means 4x4s would not have to be updated for Power BI however the downside is users who access the data via the ODP would no longer have access and would have to search through the data catalog to find the data they expect to find. With this option, the description of the ODP views could reference the previous dataset and explain to visitors that this is the new source for the related data. 
      - 🤷‍♀️   DTS comment: this is Karo's proposed model, or our current back-up plan

Option 2. Create new private datasets with the PII that are updated the same way their counterparts are updated. With this option, users would not notice any changes with the platform however new workflows and ingress methods would have to be created and Power BI users would then have to update the 4x4s in their workflows for Power BI. 
     - 🚫 DTS comment: this is the dual asset method that is the worst of both worlds for us, duplicates the assets AND the ETL; the benefit would be not touching existing datasets (and thereby not altering their 4x4s and URLs)

### Plan
- we'll check in with Charlie's proposed solution at dev sync Thu 11/30 with @ChristinaTremel

**Comment by KaroEngstrom** [comment]
## Wed 11/29/23 
- added the five additional columns for the [existing GIS API table ](https://builder.knack.com/atd/amd/pages/scene_418/views/view_3086/table)
- deleted the obsolete School Flashers API table that displayed the old school beacon records and was not connected to any ETL

**Note**
Once the PII process is decided, this API table should become the source of the School Zone Beacons Socrata dataset (currently pulling from the dedicated PII/internal table that was set up separately before we knew what all was up with this dataset).

**Comment by KaroEngstrom** [comment]
## Tue 12/12/23 
- double-checked that the fields in the [GIS API table here ](https://builder.knack.com/atd/amd/pages/scene_418/views/view_3086/table)correspond with the ones mapped out in the [to-be-deprecated EDP API table](https://builder.knack.com/atd/amd/pages/scene_1556/views/view_3898/table) 

**Summary of the plan for the internal PII/external non-PII datasets**
- ETL all data into the EDP dataset asset 
- create a derived view for the ODP dataset, save and publish to ODP 
- the two assets will have different 4x4 unique identifiers

- for this dataset, we had initially mapped from its own unique API table before realizing the GIS use one already existed
- we're now consolidating them into one so a few new fields have been added to that GIS one

**Next steps:** 
- [ ] Ask dev team to redirect the ETL from the new source to the same target (below) 
    - Source: https://builder.knack.com/atd/amd/pages/scene_418/views/view_3086/table
         - https://atd.knack.com/amd#signal-queries/school-flashers--gis/ 
    - Target: https://datahub.austintexas.gov/Transportation-and-Mobility/School-Zone-Beacons-Internal/8whb-sg4d/about_data
- [ ] Once ETL is in place, create derived view 
- [ ] Publish derived view 
- [ ] Update DTS Portal with the datasets 
- [ ] Notify MMC that the script is now running to keep this dataset updated

**Comment by KaroEngstrom** [comment]
@chiaberry 
The source for this dataset has been consolidated with the previously existing GIS API table. Could we update the source for this ETL only? The target dataset and the fields to push remain the same. 

Source: https://builder.knack.com/atd/amd/pages/scene_418/views/view_3086/table
Target:

**Comment by ChristinaTremel** [comment]
- Chia updated the source for the dataset!

**Comment by KaroEngstrom** [comment]
## Wed 1/31/24
- new public dataset here: https://datahub.austintexas.gov/Transportation-and-Mobility/School-Zone-Beacons/mzsm-hucz
- I'd love to get metadata from someone at MMC or maybe put it together with @ChristinaTremel

**Comment by ChristinaTremel** [comment]
Sent email and spreadsheet to Samir asking him to provide descriptions for all the fields on the School Zone Beacons Socrata dataset

**Comment by KaroEngstrom** [comment]
## Fri 2/16/24
- updated the metadata on both datasets
- notified Samir via email; three fields were still blank and I can update those whenever they have metadata for them.
