### ISSUE TITLE
Renew wildcard SSL/TLS cert for *.mobility.austin.gov

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#13995]
A wildcard cert used in one or more of our various applications is set to expire on October 26, 2023. It is imperative that this be renewed on time. Because this is issued from a commercial provider, there may be a cost involved.

Here's a starting-point on action items to consider:

 * [ ] Find all places this is used. Likely spots include netlify & AWS.
   * [ ] Are any services or redirects served by CTM machines? Coordinate with them?
 * [ ] Renew the certificate
   * [ ] Create a CSR using the same metadata as used in the previous cert (PM me for details)
   * [ ] Apply for the certificate to be signed
   * [ ] #14000
 * [ ] Install the new certificate
 * [ ] Create a calendar invite for the expiration of the cert

**Comment by frankhereford** [comment]
@chiaberry @amenity 👋 I wanted to tag you all on this because this wildcard cert may be being used to secure anything that matches the `*.mobility.austin.gov` pattern. I'm not sure off the top of my head what services that may include, but I have a feeling this isn't a deadline we want to miss at all. I'd be happy to look into the details of what needs to happen, and I believe Patrick is going to bring the sibling issue, #13994, to refinement tomorrow, which may be a good time to talk about this one too.

**Comment by amenity** [comment]
Thanks. I had no idea that cert renewals were so much work, but I agree we don't want to miss the deadline. Thanks, @frankhereford. 🙏🏻

**Comment by amenity** [comment]
> Pay for it, including whatever backend paperwork required
I'll go ahead and put in the PR for this. @frankhereford, when you get a chance please add a URL w/ pricing info or screenshot of the price [here](https://github.com/cityofaustin/atd-data-tech/issues/14000)?

**Comment by frankhereford** [comment]
@amenity 👋 Good news! I've learned more, and I don't think we'll need to do a PR or purchase anything thanks to CTM.

I was digging into this issue and trying to find our login in 1Password for Entrust.com who is the issuer of the certificate. I was unable to find one, and on further investigation, it turns out that this certificate has been renewed in the past in collaboration with CTM. I found records in my email archives of Mateo handling this two years back, and @johnclary took care of it last year. 

It looks like the process is for us to generate CSRs for this hostname pattern and similarly for [VZ](https://github.com/cityofaustin/atd-data-tech/issues/13994), and then get in touch to securely deliver those to Jason G. at CTM in their linux group. May I self assign on these two issues and get that in motion or would you like a different approach?

**Comment by amenity** [comment]
@frankhereford - sweet, glad this is looking smaller than it was at first glance! No need to break sprint, for sure! Looks like we can queue it up for next sprint or the one after and assign during that respective planning. cc/ @chiaberry

**Comment by johnclary** [comment]
just confirming what Mike mentioned in planning: we have a CloudFront distribution where this cert needs to be installed. (in addition to Netlify and potentially other places).

**Comment by frankhereford** [comment]
Thank you John & Mike. I noted some observations on the sibling issue, but long story short, we have these certs in AWS, but they are currently expired, so we may not need them anymore for AWS resources. This is confusing to me, but I also have not looked into anymore than to notice that while I was in the AWS cert manager.

Also, I got an email out to Jason G. at CTM as well as to the wider linux group with our CSRs. I'll report back anything I hear from them to y'all of course.

**Comment by johnclary** [comment]
@frankhereford i see both certs in AWS as active:
- [visionzero.austin.gov](https://us-east-1.console.aws.amazon.com/acm/home?region=us-east-1#/certificates/59e50d26-7841-4fe1-970e-31b76a37fc3a)

- [mobility.austin.gov](https://us-east-1.console.aws.amazon.com/acm/home?region=us-east-1#/certificates897c4900-3a77-4754-a636-2a79d1335b84)

**Comment by frankhereford** [comment]
Thank you for pointing that out John. I had been looking at `0795ef2b-de26-4a1f-9a15-400fdd491b69` for VZ and `8eb386ef-4825-4c35-8d8f-114661856407` for moped. Knowing that we have other, current certs in there makes a lot of sense to me and we will certainly be re-upping those when we get them back from CTM.

**Comment by frankhereford** [comment]
No word from CTM yet. I'm going to write them again on Wednesday afternoon which will have been 7 days from my original request. I'll follow up again on Friday after that and start with other methods of communication after that.

**Comment by frankhereford** [comment]
This was installed and tested. A zip file containing the key, certificate and other artifacts of the renewal process have been placed in 1Password.
