### ISSUE TITLE
Add `Backplates Installed` field to signals object and to the Signals Details page

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#14006]
> What application are you using?

AMD Data Tracker

> Describe the problem.

Do not currently have a place in the signal details page to track if an intersection has backplates or not.

> Describe the outcome you'd like to see when this feature is implemented.

Would like to have a subfield under the operations or component field labeled as "Backplates Installed" with a Y or N option for input value. See attached image for reference.

> Describe any workarounds you currently have in place or alternative solutions you've considered.

N/A

> Requested By
Jorge G.

[Attachment](https://api.knack.com/v1/applications/595d00ebd315cc4cb98daff4/download/asset/65144e78c60fb5002804fa33/capture.png) (15.08kb)

Request ID: DTS23-110005

**Comment by ChristinaTremel** [comment]
- Add `Backplate Installed` Y/N field to signals object
   - Set all of the records to `No` for now
- Add field to Signals Details page under Components 
- Add field to the edit signals details page

**Comment by ChristinaTremel** [comment]
Add to **Signals Details** page and to **Edit Signals** page
- Add `Backplates` field
   - No backplate
   - Retroreflective Backplate
   - Non-Retroreflective Backplate

- `Backplate Installation`
   - Partial
   - Complete
   - Hide if `Backplate` field = no backplate

- Will also need to add `Backplates` field to [Open Data Portal](https://datahub.austintexas.gov/Transportation-and-Mobility/Traffic-Signals-and-Pedestrian-Signals/p53x-x73x) and to [ArcGIS Online](https://austin.maps.arcgis.com/home/item.html?id=e6eb94d1e7cc45c2ac452af6ae6aa534)
   - Update Knack API table
   - Then update ETL

- Who will be maintaining this:
   - MMC noted they are happy to help, but aren't involved in the process with the contractor so that will be difficult to know the changes that are happening
   - Ivonne noted this field might be managed by a couple different processes. Jorge works with contractors, so he will be able to update those. New signal turn ons, the MMC might be able to assist. There might be things that Billy's team can update.

**Comment by susannegov** [comment]
Sent on 10/10:

> I have added the following fields to the signal details page and the edit signal page:
> -	Backplate Installed
> -	Backplate
> -	Backplate Installation
> If these field options look correct on the AMD data tracker, we can close this issue out and work on adding these fields on the open data portal.

**Comment by susannegov** [comment]
Talked w/ Jorge about it this morning:
- [x] Changed Display Rule to: If backplate installed is no, hide/show Backplate and Backplate Installation
- [x] Removed the No Backplate multiple choice option
- [x] Removed Display Rule: Hide if Backplate field = no backplate because the no backplate option was removed.
 
Jorge needs to talk to his team about what they want to rename `Backplate Installation Status` . Once that's done, I will rename that field.

**Comment by susannegov** [comment]
Field name changes
- `Backplate` to `Backplate Type`
- `Backplate Installation Status` to `Intesection Backplate Status`

Response:
> Looks good. We should be able to close this issue. Thanks Susanne!
