### ISSUE TITLE
Source and create design possibilities for Dash

### ISSUE THREAD

**Issue by katelunceford** [cityofaustin/atd-data-tech#14021]
**We're gathering ideas for the user interface design of Dash, a data dashboard that:** 
- **Includes levels of data or a reporting hierarchy**
- **Uses visual indicators for on or off track (actual, planned, goal, forecast)**
- **Features maps and geospatial data**
- **Standardizes various data into a common format, design, or theme**
- **Makes large, complex datasets easier to visualize, sort, compare, and analyze**
- **Communicates data so it's easy to understand and act upon**

We will discuss them during our "Share Dash design ideas" meeting on 11/6 at 11 AM.

## Background

The vision of Dash is to centralize the department's data and reporting in one place so that we can track, compare, analyze, and adjust our work toward important goals. The dashboards will be a visual representation of the overall health of the department, highlighting key metrics and offering a standardized format to represent various data across work groups. 

Dash will present data in various levels. The highest (department) level should include:
- Service delivery to residents - CSRs (customer service request)
- Increasing efficiencies 
- Maps/geo data

Another level to the data might be service area focused or it might be more focused on goals. And then even deeper is data at the division level. We want to link to data so the viewer can go down the rabbit hole wherever it allows.

The audience for the dashboard includes many people, from TPW staff, managers, and executives to city council members, Austin residents, and anyone who wants to see what TPW is working on.

## Deliverables

Add data dashboards or dashboard components to the [Dash miro board](https://miro.com/app/board/uXjVM1Z5trE=/)

### Sourcing design possibilities

Anyone can add a screenshot of a dashboard or dashboard component to the [miro board](https://miro.com/app/board/uXjVM1Z5trE=/?share_link_id=113602483825). Please include the source link and take note of what you like about it. 

### Creating design possibilities 

Some of us are also creating new designs. We'd love more input. If you're interested and there's time in your schedule, please join us! Design homework was given 9/27/23 during [this meeting](https://cityofaustin-my.sharepoint.com/:v:/g/personal/kate_lunceford_austintexas_gov/EUaMfBZzj-FAo8qE8MWEHRkBo17X0b5SzdemdXYzHUDdSQ) and is summarized here:

1. If you don't already have an idea in mind, review the data dashboard examples on the [miro board](https://miro.com/app/board/uXjVM1Z5trE=/?share_link_id=829879644555) to find inspiration. You can also refer to the product vision board (on the miro board) and the [Dash v1.0 project index](https://github.com/cityofaustin/atd-data-tech/issues/11078).

2. Put your design ideas "on paper" using the app of your choice (Figma, Exalidraw, Miro, Balsamiq, PowerPoint, Paint, etc.). Your ideas could range from a focused report or specific feature to an overall design that spans several layers or levels of reporting. Use these [TPW branding standards](https://cityofaustin.sharepoint.com/sites/tpwPIO/SitePages/ATD-Department-Branding.aspx) if possible.

3. Add your designs to the DESIGN IDEAS area of the [miro board](https://miro.com/app/board/uXjVM1Z5trE=/?share_link_id=113602483825). We'll look at them together during our next meeting.

### Tasks
- [x] Schedule next meeting: 1.5 hours week of 10/23 w/ Kate, Charlie, Rebekka, Susanne, optional: Amenity, Chia, Andrew @katelunceford - 10/24 at 10:30 AM --> 11/6 at 11 AM
- [x] Post on slack to get more participation
- [x] Add design ideas/notes to miro board before 11/6 @katelunceford 
- [x] Add design ideas/notes to miro board before 11/6 @Charlie-Henry 
- [x] Add design ideas/notes to miro board before 11/6 @rebekkabry 
- [x] Add design ideas/notes to miro board before 11/6 @susannegov

**Comment by katelunceford** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaWZzIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7fbdfe9ac579170b2564bac0240a5e8b32716f46/Screenshot%202023-09-28%20at%205.08.03%20PM.png)

**Comment by rebekkabry** [comment]
Added content ideas into [Miro ](https://miro.com/app/board/uXjVM1Z5trE=/?moveToWidget=3458764565205257833&cot=14)

**Comment by katelunceford** [comment]
### TPWstat slide decks

[TPWstat Meeting 10-25-23](https://cityofaustin.sharepoint.com/:p:/r/sites/TPWReorg/Shared%20Documents/General/PERFORMANCE%20MANAGEMENT%20PROGRAM/TPWstat%20Development/2023.10.25_TPWstat%20Meeting.pptx?d=w3b6ffe06cdac4fddb55acd102d124bae&csf=1&web=1&e=lqvmyN)

[TPWstat Executive Proposal](https://cityofaustin.sharepoint.com/:p:/r/sites/TPWReorg/Shared%20Documents/General/PERFORMANCE%20MANAGEMENT%20PROGRAM/TPWstat%20Development/2023.08.02%20TPWstat%20Executive%20Proposal.pptx?d=wc560a322d8b14e96a2e2f6d2652fb6da&csf=1&web=1&e=qZf7F1)

**Comment by katelunceford** [comment]
Considering this closed :)
