### ISSUE TITLE
Research, Locate, and Acquire specific Data sets to be used in the Prioritization Mapping

### ISSUE THREAD

**Issue by ATD-ZachB** [cityofaustin/atd-data-tech#14074]
- [x] Parks: Want safe connections to parks and other recreation areas 1000 ft buffer of parks polygons
- [x] Libraries: Want to connect people to amenities 2000 ft buffer of property
- [x] Rec Centers:  Want to connect people to amenities 2000 ft buffer of property
- [x] Schools (public, private, university, etc.):	Want to connect people to amenities 1000 ft buffer of property
- [x] Banks: Want to connect people to amenities 500 ft buffer of property
- [x] Post Offices: 500 ft buffer of property
- [x] Hospitals and urgent care: 1300 ft buffer of property #14123
- [x] Urban Trails: If we can provide missing connections that is great 1300 ft buffer
- [x] Transit Stops: Want to connect people to other modes 1300 ft buffer #14423
- [x] High comfort bike route: 800 ft buffer
- [x] AISD Bus Stops	Want to connect people to other modes 500 ft buffer #14422
- [x] Movie theaters Want to connect people to other modes: 1300 ft buffer of property #14093
- [x] Show Venues: 1300 ft buffer of property #14094
- [x] Museums: 2000 ft buffer of property #14095
- [x] Grocery stores: (1) 1300 ft buffer of property #14124

- [x] Equity Analysis Zones (EAZ): "EAZs are a combination of 9 different variables with different weights #14204

- [x] House hold size: want to encourage kids/families to play, census tracts within the top 20% of people below 12 and above 60 #14426

**Comment by ATD-ZachB** [comment]
Removed  Sidewalks: Want to prioritize streets that don’t have sidewalks: sidewalk % completion from list.
#14593 is now issue for this task of creating data.

**Comment by ATD-ZachB** [comment]
The follow tasks have been removed and tabled for a later iteration of this project.
- [ ] Corner stores : (1) 1300 ft buffer of property #14348
- [ ] Restaurants: (2) 200 ft buffer of property #14427
- [ ] Retail 200 ft buffer of property
- [ ] Bars (3) 200 ft buffer of property #14203

**Comment by ATD-ZachB** [comment]
The following task has been removed as a new task issue has been created for creating this data set
- [ ] Park Deficient Areas:  want to provide areas that don’t have parks a chance to recreate in the street areas not within 1 mile of a park
