### ISSUE TITLE
Tracking solution to improve communications between divisions in SBO

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#14108]
> Describe the problem.

We continually run into issues regarding communication. For example, We have a supervisor that ask for assistance from another division within SBO. The other supervisor might forget to respond or reschedules without letting the requesting supervisor know. 

> Describe the solution you have in mind.

 I would like a system that I can track where the breakdown happened. My thought was to use emails, but that be cumbersome. 

> How will we know that our solution is successful?

More stuff not following through the cracks.

> Users

SBO

> Sponsorship

Ryan Harding and Reiner Hershaw

> Which Strategic Direction 2023 “Mobility” indicators would this new application impact?

['System efficiency and congestion']

> Which Austin Strategic Mobility Plan goals would this new application support?

['Innovation — Draw inspiration from forward-looking cities around the world, change the way we think about what’s possible, and set an example for the rest of the country.']

> Describe any workarounds you currently have in place or alternative solutions you've considered.

The managers are supposed to come to my team. 

> How have other divisions/departments/cities addressed similar challenges? 

Unknown

> Requested By
Ryan H.

[Attachment](https://api.knack.com/v1/applications/595d00ebd315cc4cb98daff4/download/asset/651d6d35db7b9c00271add53/flowchartforrequest.docx) (42.1kb)

Request ID: DTS23-110170

**Comment by ChristinaTremel** [comment]
Scheduled scoping meeting with Ryan H and Diana on Monday 10/9.

**Comment by ChristinaTremel** [comment]
## 10/9 SBO Coordination Project
**Attendees:** Christina, Diana, Ryan, Jermaine

### Challenges
- Sometimes Supervisors don't tell the Superintendents
- Challenging time communicating across SBO Divisions for something else 
- Jermaine had something similar in Watershed. Might have been built off of Knack. 
   - If someone from Jermaine's group needs help or equipment, we want to move away from emails and spreadsheets. 
   - Streamline requests through some sort of computer program or software

### Current Process
- Diana shared [miro board](https://miro.com/app/board/uXjVNdt1r2s=/?share_link_id=772231515790)
- Ryan said each coordinator has been selected to help a Division Manager/Division
   - 3 Project Coordinators assigned to the 3 SBO Divisions
   - 2 Program Managers: Ryan H will be focused on coordination (so this process)
   - Things to Note:
      - Patty is taking Superintendent job
      - Mike G is helping the UER Division

 
### Fields to think about
- Created By
- Created Date
- Requested By
- Requested Date (from and to dates)
- Need By Date
- Requested Support:
   - Equipment Support
   - Workforce Support
   - Project
   - Overtime
   - Other
- Details 
- Decision (Approve/Deny)
- Denial Reason
- Status (Waiting for Approval, Needs Review - DM, Coordination In Progress, Completed, Closed)
- Approval Status

### Functionality
- **Solution:** Knack app for SBO Coordination
- **Users:** Program Manager, Project Coordinators, Division Managers, Superintendents, Supervisors
- Email Notification: Send email notification when assigned to is the person
- User (Supervisor or Superintendent) > Superintendent (if the user was a supervisor) > DM > Project Coordinator
- Most users have computers and are in their office
- Do we want the communications to be tied to work orders?
   - Not necessarily, but it'd be better to track requests by Work Order Number
- What should be tracked?
   - Financial
   - Work Order Numbers

### Timeline 
- No timeline
- Start of the 18th we could bring it on deck to scope it out.

**Comment by dianamartin** [comment]
# Diana's Notes

**Participants:** Ryan H., Christina T., Jermaine B., Reiner?
- Ryan H. - (6 months with SBO)
- Jermaine (WPD)
  - something similar in WPD
  - Build off of Knack

Ex. initiates a request

- piece of equipment, request

Could be financial, work order #

Overlay - receiving Money

## Project

SBO Coordination Requests? Commitments

- Single sign on?
- Simple approval process
- User>DM>
- Email notification when **Assigned To** - established
- Timeline: no timeline

## Users

4 DMs

3 Project Coordinators

- Pavement
- District
- Utilities & Structures

2 Program Manager (Ryan and Dave)

- Ryan - coordination

10 Superintendents

18 Supervisors

## Status

- Waiting for Approval
- Needs Review - DM
- Coordination In Progress
- Completed

## Fields Tracked

**Created By**

**Created Date**

**Requested By**

**Requested Dates**

Duration?

Need By Date

**Requested Support**

- workforce support
    - Overtime hours
- equipment support
    - ex. Milling machines

**Details**

**Decision**

**Denial Reason**

**Status**

**Comment by dianamartin** [comment]
# 10/9
- [x] Created prototype application
- [x] Added to Application Inventory in DTS Portal
- [x] Created new object table `sbo_coordination_requests`
- [x] Created new page `SBO Coordination Requests`
- [x] Created new page/form `New Coordination Request`

**Comment by ChristinaTremel** [comment]
## 10/30 Prototype Review

- Added `Support Subcategory` with the following options:
   - Dump Truck
   - Heavy Duty Truck
   - Light Duty Truck
   - Trailer
   - Miller
   - Pavor
   - Staff
   - Operator
   - Tandem
   - Bobcat
   - Gradall
   - Backhoe
   - Excavator
   - Mini-Excavator
   - Concrete Truck
   - Sweeper
   - Bucket Truck
   - Lift Truck
   - Hot-mix Truck
- Removed `Need By Date`
- Ryan will be testing out the SBO Coordination module this week. Scheduling a check in with Ryan and Diana next week.

**Comment by dianamartin** [comment]
# 2/23/24
@ChristinaTremel I think we need to schedule that tech review to test out the status workflow

**Comment by ChristinaTremel** [comment]
This was completed and users were trained on this `SBO Coordination Requests` on 4/30. Closing this epic!
