### ISSUE TITLE
Update "Journal Voucher" info in AMD Data Tracker - Warehouse Inventory- September 2023 v4

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#14158]
- [x] Spreadsheet emailed from Finance staff month of: September; transaction dates 9/8-9/25/23
- [x] Number of records being updated: 52
- [x] Format spreadsheet [(Review instructions)](https://atd-dts.gitbook.io/atd-knack-operations/warehouse-inventory-updating-journal-vouchers-jv-information)
- [x] Spot check Transaction IDs, no JV information before import: 18579 ✅ ; 19688 ✅ 
- [x] Import records
- [x] Spot check Transaction IDs, does have JV information after import: 18579 ✅ ; 19688 ✅
- [x] Email Finance staff that update task complete
