### ISSUE TITLE
Enhancement to the Training Tracker to allow me to add multiple attendees to a training class

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#14151]
> What application are you using?

SMD Data Tracker 

> Describe the problem.

Requesting an enhancement to the Training Tracker to allow me to add multiple attendees to the trainings all at once. Also update training outcomes for multiple attendees similarly.

> Describe the outcome you'd like to see when this feature is implemented.

Speed up the process for adding trainees to an event and updating attendance statuses. 

> Describe any workarounds you currently have in place or alternative solutions you've considered.

There's a process in place already so this is not urgent.

> Requested By
Cathy K.

Request ID: DTS23-110235

**Comment by ChristinaTremel** [comment]
In the November sprint review, Cathy noted that Chris W is planning a training in the near future and when that happens they will need to add multiple employees to the training. Just wants to ensure that this is still on our radar, but it's not highest priority.

**Comment by KaroEngstrom** [comment]
Need a short huddle to review internally our options here for adding attendees; I've discussed this with the Apps team already. The batch update for the outcomes exists already (updating event status rolls down to each attendance record as Completed unless the specific attendance is marked missed or unenrolled).

**Comment by KaroEngstrom** [comment]
## F 11/1723 
- synched with Christina and showed her the test solution 
- we agreed to build this out a bit more in test to demo for the next sprint review 12/1 and then transfer to Prod, pending stakeholder approval 

**Next steps for Sprint Review 12/1:** 
- [ ] Add 3 and 5 options to Add Participant buttons in TEST 
- [ ] Remove current single add/save view in TEST
- [ ] Get ready to demo adding training event and users with proposed method, closing out with training event update that flows into the attendance records

**Comment by KaroEngstrom** [comment]
### TESTING 
- the Add Participants update is behaving as expected when testing in PROD
- I spotted a multiplication on the My Trainings side of the portal (individual user tables); checked the records on the back-end and determined there's no duplication or multiplication of attendance records

**TO DO** 
- [ ] Find and eliminate the filter or other issue causing the display duplication

**Comment by KaroEngstrom** [comment]
## Thu 6/13/24 
- @ChristinaTremel  I know Cathy approved of our solution that was implemented. The remaining pieces we more of a "note to self" for me to test the IMSA items at some point. I'm creating a new issue for the backlog for that smaller follow-up piece so we can close this since the og request piece is completed.
