### ISSUE TITLE
Add `Switch Model` field to cabinet and signal details pages in AMD Data Tracker

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#14202]
> What application are you using?

AMD Data Tracker

> Describe the problem.

Under asset type "Cabinet", if we could add a field for "Switch Model" and have the following options:
- GEN 1 - 72102
- GEN 1 - 73240
- GEN 2 - 73931
- GEN 3 - 78934E

Under the "Signal Details" page, if we could add a field "Switch Model" and have the following options:
- GEN 1 - 72102
- GEN 1 - 73240
- GEN 2 - 73931
- GEN 3 - 78934E

> Describe the outcome you'd like to see when this feature is implemented.

Under asset type "Cabinet", if we could add a field for "Switch Model" and have the following options:
- GEN 1 - 72102
- GEN 1 - 73240
- GEN 2 - 73931
- GEN 3 - 78934E

Under the "Signal Details" page, if we could add a field "Switch Model" and have the following options:
- GEN 1 - 72102
- GEN 1 - 73240
- GEN 2 - 73931
- GEN 3 - 78934E

> Describe any workarounds you currently have in place or alternative solutions you've considered.

Management outside of Datatracker

> Requested By
Allyson R.

Request ID: DTS23-110290

**Comment by dianamartin** [comment]
# 10/10
So, she's asking for a new field `Switch Model`
- GEN 1 - 72102
- GEN 1 - 73240
- GEN 2 - 73931
- GEN 3 - 78934E

To be added to two object tables, right?
- `signals_cabinet`
- `signals`

**Comment by ChristinaTremel** [comment]
Yes, we would add these options to both objects!

**Comment by dianamartin** [comment]
# 1/3/24
Synced with Allyson on this. There is an initiative to figure out what kinds of switches there. 
- We think this should be in a `signal_cabinet` not in the `signal` object table

**Comment by ChristinaTremel** [comment]
- [x] Removed `Comm Type` from Signal Details view (because we are going to keep it solely within the signal cabinets asset, not on the signals asset)
- [x] Removed `Firmware', 'Firmware Status Date` and `Ped Signal` fields from Signal Details view
   - These are being tracked in the D4 software and is not kept up to date in Knack 
- [x] Under Cabinet Details view, removing the following fields:
   - Switch Sequence
   - Hub ID
   - Ring Switch ID
   - Ring Number ID
   - Circuit ID
   - Circuit Name
   - Group Number ID
      - These are being tracked in other places and data is not kept up to date in Knack
- [x] Add new options within the `Comm Type` field on the `signal_cabinets` object
    - Made 4 new types available and will depreciate other types once updates have been made by the MMC 
- [ ] Took an export of the `signal_cabinets` objects
- [ ] Took an export of the `signals` object
- [ ] On `signal_cabinets` object, delete the following fields:
   - Switch Sequence
   - Hub ID
   - Ring Switch ID
   - Ring Number ID
   - Circuit ID
   - Circuit Name
   - Group Number ID
- [ ] On `signal` object, delete the following fields:
   - Firmware
   - Firmware Status Date
   - Ped Signal

**Comment by ChristinaTremel** [comment]
Blocked while we're waiting for Allyson to provide an import spreadsheet for the new `Switch Model` field

**Comment by dianamartin** [comment]
# 2/6/2024
Allyson provided us a spreadsheet on 1/29/24, but we kicked it back due to formatting on 2/2/2024. She re-sent it on 2/5/2024. We will need to schedule this import.

**Comment by dianamartin** [comment]
# 2/7/2024
@ChristinaTremel is this related to this issue #1703
- [X] Created backup of `20240207_signals_cabinet_1080_BACKUP_ARCHIVE`
- Using spreadsheet that Ally provided `20240207_import_FiberV1`
- Filtered "Switch Model" - has `2 records`
  - 1356: GEN 3 -78934E
  - 1366: GEN 3 -78934E
- Filtered "Switch IP" - has `0 records`

**Comment by ChristinaTremel** [comment]
We resolved the import issue and this has been completed!
