### ISSUE TITLE
Prototype Build - OCE Inventory Tracking

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#14206]

**Comment by TracyLinder** [comment]
DTS prototype review is scheduled for Monday 10/23/23

**Comment by dianamartin** [comment]
# 10/23
- Producers page - form/inline
  - Plant & Plant Location with producers?
  - Should it be shared?
- Approved Mixes
  - Explain fields "Comments", "Cement Type", "Fly Ash Type"

**Comment by TracyLinder** [comment]
### Notes

**To-Do**
- [ ] Add SSO
- [ ] Add new banner
- [ ] 


**Producers Page**
Q: Inline editing or form for each? 
Q: Does Plant and Plant Location belong with the Producers table, or with the Approved Mixes table? 
Q: Do they want contact info? 



**Sharepoint**
- What else are they using SharePoint for mixes that we can/should move to KNACK?

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFZnQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--10c212af43bf7e06d5ce53b39cb1a80e7e5f891d/image.png)



**Approved Mixes - Admin**
OCE had a lot of comment fields, so Diana did the best she could based on how they're using them right now. 

**Approved Mixes **
- No sign-in required to view this data

**Comment by dianamartin** [comment]
# 10/23
- [ ] Created `plant_inventory` because of the HMAC producers/plants spreadsheet we found
- [ ] Imported approved mixes for HMAC

**Comment by TracyLinder** [comment]
### Closing - Complete

@dianamartin or @susannegov I'm not sure if you wanted to add notes from today's review. I'm closing this. We have an issue for tomorrow's meeting with OCE. #14207

**Comment by dianamartin** [comment]
> # 10/23
> * Producers page - form/inline
>   
>   * Plant & Plant Location with producers?
>   * Should it be shared?
> * Approved Mixes
>   
>   * Explain fields "Comments", "Cement Type", "Fly Ash Type"
> 
> I created a Miro Board showing the proposed workflow
> 
> * [OCE Mixes](https://miro.com/app/board/uXjVNXFdd5A=/)
> 
> Reference:
> 
> * [Approved Materials List - SharePoint page](https://cityofaustin.sharepoint.com/sites/PW/OCE_Standards)
>   
>   * Concrete Mixes
>   * Flexible Base Materials
>   * HMAC Mixes
> * [Stockpile Results - FlexibleBase](https://cityofaustin.sharepoint.com/:x:/r/sites/PWD_OfficeofTheCityEngineer/Shared%20Documents/Engineering%20Reviews/Stockpile%20Results-FlexibleBase.xlsx?d=w0a5b4b663dce4340a4a9b206ec16241e&csf=1&web=1&e=Qdf5iU) _- Excel Web Spreadsheet on OCE "Approved Mixes List" SharePoint_
>   
>   * Ask the stakeholders how this comes into play
> * Spreadsheet location - `TPW\PWD\Street & Bridge Division\Office_of_City_Engineer\Engin_Stndrds_Review\MATERIALS REVIEWS\`
>   
>   * HMAC Spreadsheet name: `preapprovedidiqhmacmixes`
@TracyLinder my notes are above your notes for today
