### ISSUE TITLE
Setup ATD/LIT Trello Development Board

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#1423]
### Objective:
Prepare the [ATD/LIT Trello Board](https://trello.com/b/2MZ7yNTv/atd-lit) for Launch IT (LIT).
- Example of a DSD card that went through this development process [here ](https://trello.com/c/oFReYzBl/672-ev-folder-updates)
- Cards need to be ready to pickup by LIT and do the dev with little to no questions for the PM

**Tasks:**

- [x] Add a card for each backlog issue rated priority 1
    * There are six priority 1 issues
- [x] Each card should have a user story
- [ ] Each card should have acceptance criteria

**Misc. Resources:**
- [Backlog Folder ](https://drive.google.com/drive/u/1/folders/1xXp0Hi3M6MEETLaTggPiwKUuXdROBa_o)
- [AMANDA Ops Strategy doc](https://docs.google.com/spreadsheets/d/12djLwekONVUvZRorp_pl4wDxhC8LsU-LV1henIIxOsg/edit?usp=sharing)

**Comment by TracyLinder** [comment]
## ATD/LIT Dev User Stories (Priority 1 Work)
_Current info we have for the 6 issues_


### #1
**Title:** Out-of-Process TCP Fees
**Audit Related:** Yes
**User Story:** As a Right-of-Way traffic control plan (TCP) reviewer, I need to be able to bill and collect payments for TCP Review Fees, in AMANDA, as needed. 
**Acceptance Criteria:**  Forthcoming

### #2
**Title:** Feature: Unpaid Fee Check & Flag on Permit Issuance 
**Audit Related:** Yes
**User Story:** As the COA, we need to be sure that permit applicants don't have outstanding invoices prior to issuing any permit for said applicant. 
**Acceptance Criteria:** 
- [ ] 

### #3
**Title:** Fee Update: Parking Permit Fee
**Audit Related:** No
**User Story:** As a permit analyst, I need to charge permit applicants the updated fee in AMANDA. (New fee is $2.00)
**Acceptance Criteria:** 
- [ ] 

### #4
**Title:** Feature: Create a GF folder subtype for ATD Use
**Audit Related:** No
**User Story:** Forthcoming
**Acceptance Criteria:** 
- [ ] 

### #5
**Title:** Feature: Add fees to ECV for TCI Investigation Fees
**Audit Related:** No
**User Stories:** 
- As a Traffic Control Inspector, I need to be able to add investigation fees to the related ECV folder. 
- As a contractor who has been assessed an investigation fee, I need the ability to pay those fees online. 
**Acceptance Criteria:** 
- [ ] 

### #6
**Title:** Feature: Create TIA Mitigation Fees
**Audit Related:** No
**User Story:** 
- As a TIA reviewer, I need to be able to invoice customers, and record payments for TIA Mitigation Fees in AMANDA. 
**Acceptance Criteria:** 
- [ ]
