### ISSUE TITLE
User Support: Arthur W Needs LM Permissions in TEST for UAT

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#1426]
### Overview:
- Arthur W. with ORES has been assigned to UAT for ROWMAN 3 - LM Self Assignment. 
- Melissa T with ORES reported this issue to Tracy L on 2/13/2020 by email

**Tasks**
- [ ] Create AMANDA New User Request Form (NERF) for this update
- [ ] Update permission in TEST
- [ ] Ask Arthur to confirm the permissions update is successful, and meets his requirements

**Comment by amenity** [comment]
@johnclary @SurbhiBakshi - do you have any idea who these people are? I couldn't find them in Outlook.

**Comment by SurbhiBakshi** [comment]
@amenity - Arthur Walston, and Melissa Torres with Office of Real Estate Services (ORES)

**Comment by amenity** [comment]
Thanks! Edited for Google-crawlers. ;) I will reach out to them and see if they still need accounts.

**Comment by amenity** [comment]
I gave Melissa the NERF and she copied me on her CTM request.

**Comment by amenity** [comment]
Emailed Melissa to make sure this is taken care of.

**Comment by amenity** [comment]
Done!
