### ISSUE TITLE
Create Approve Invoice page and Requester Approval Process in Prod

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#14320]
# To do
The following need to be done in production

# Reimbursable_tracking table
- [x] Reimbursable Status type multiple choice custom sort, drop down one selection
```
Not Ready
Needs Review
Waiting for Approval
Approve
Review Required for Approval
Closed

```
- [x] Approval Status - Multiple choice - radio buttons - use to limit status form options for reviewer
```
Approve
Approve with Comments
Approve with FDU Change
Reject with Comments
```
- [x] Set conditional rules to reimbursable status:
       - Approval Status is Approve = Approve
       - Approval Status is Approve with comments =  Review required for approval
       - Approval Status is Approve with FDU Change = Review required for approval
       - Approval Status is Reject with comments = Review required for approval
- [x] Approver - Accounts - connection field 
- [x] Location - Text Formula 
- [x] Comments - type paragraph text
- [x] Approver Comments - type paragraph text. Set it as required. Use it setup areimbursable status page
- [x] FDU Change - type yes/no field. Used to set reimbursable status to Approve with FDU Change if yes
   - Conditional rule:
      - Approval Status is Approve with FDU Change = Yes
- [x] Created By - Accounts - connection field 
- [x] Created Date - date/time

# Reimbursable_tracking record
Go to `New Work Orders (Signs)` page and `New Work Orders (Markings)` page for record rules when it comes to creating a reimbursable record.
- [x] Add or modify Record Rule for adding reimburseable_tracking record
   - Set Approver, Created By, Created Date, and Reimbursable Status 
   - Markings: When `Funding_Department_Unit_FDU` is Yes
   - Signs: When `Funding_Task_Order` is Yes 
![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/341f48b5-07f9-4710-b32f-14377e42f856)
Go to `Prepare Invoice` page and `Prepare Invoice` page for record rules when it comes to creating a reimbursable record.
- [x] Add record rule for Prepare Invoice for Signs and Markings
   - Set Reimbursable Status, Modified By, Modified Date
![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/8eec73b2-c5c7-409e-bc66-bc554ac0b1ed)

# Review Invoices Page
Add all `reimbursable_tracking` records. 
Source > Show records that match all of: Approver is the logged in Account
![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/07021dd1-2892-4241-9629-158d0c14e55b)
- [x] Add the following columns to the Grid view
   - [x] View - Child page
      - Background color:
      - This will go to a child page with Invoice details modal pop-up
      - Copy Details/Table view from Invoice page ( Reimbursements > Signs reimbursements > Invoice Details > Invoice)
      - Copy Details/Table view from Invoice page ( Reimbursements > Markings reimbursements > Invoice Details > Invoice) 
      - Add Review form:
         - Record rules: 
            - Modified By/ Modified Date run all 
            - Approval Status is rejected with comments: Invoice Approved = No
            - Approval Status is not rejected with comments: Invoice Approved = Yes
   - [x] Approver  - Child Page
      -  This will go to a child page modal pop-up to change approver
   - [x] Type - Work Type as Signs or Markings
   - [x] Status - Reimbursable Status
      - Set Display Rules:
         - Waiting for Approval: #377eb8
         - Review Required for Approval: #6a6565
         - Approve: #f5901f
   - [x] Requester ID - Text Formula
   - [x] Location - Text Formula
   - [x] FDU - Text Formula
   - [x] Invoice Received - Sent to Requester Date

_Originally posted by @susannegov in https://github.com/cityofaustin/atd-data-tech/issues/13485#issuecomment-1736233832_

**Comment by ChristinaTremel** [comment]
# 10/12 Meeting Notes for SMD Feedback 
### Reimbursable Process
- Do we want to send reminders for invoices that have been `Sent to Approver`? 
   - Can Ramona have a way with determining deadlines for certain invoices?
      - Could we send automated email 5 days after initial email was sent
   - Alternative to add button to send email reminder details
   - The follow up email could say "your approval is overdue" instead of just another "please review within 5 days" reminder email to make it more urgent 
- On the `Approve` and `Review for Approval`
   - Add link to invoice that printable 
- Add `Invoice Approved Date` for any invoices that are the `Approved`, `Approved with FDU Change`, and `Approve with Comments`
   - Remove the `Invoice Approved` yes/no field from Reimbursable Invoice table
- If Ramona sees something that Johnny needs to fix, she'll need to send it back to him. Maybe she can use the `Reject with Comments` and have a comments field (separate from Requester Comments field) that she can use to give him notes.

###  Review Invoice Process
- For `Approve with FDU Change` 
   - Add the `Funding - FDU` field
   - Remove `Comments` field
- If approval status is `Rejected with Comments`, changes will need to be made and the invoice will need to be re-sent out
   - So email invoice should be an option on these and when clicking email invoice, it should revert the approval status to `Waiting for Review` 

### Fix invoice PDFs COA seal is broken
   - Update invoice doc to reflect TPW
   - Update name to Signs & Markings Division

**Comment by susannegov** [comment]
# Notes for 11/14
- Review Invoice page has been completed in production. Will need to test it to make sure it is working as intended in production by creating test records
- Where is the link to the updated COA seal? 😅 
- Where is the `Approve` and `Review for Approval` page? Is that something I have to build for?
- Reimbursable Invoice table feels like there is way too many fields. Want to explore having some of the fields as a modal popup or having the editing fields as a form modal pop-up by subject instead of having all of them in the table
- the email reminders will need to ask apps team about if it is possible and how it works.

**Comment by ChristinaTremel** [comment]
- Need to schedule meeting to review this with Ramona and invite: Ramona, Kati, Cathy, Esteban, and Jenniffer from the SMD team

**Comment by susannegov** [comment]
# 2/09 
- There's a issue with `markings_work_orders' records not displaying info in review invoice page for
   - Inventory transactions
![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/f6c19263-c62e-4ffe-9b89-df707e2cc0e1)
- work orders signs marking specs actuals
![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/ba5c0778-4502-4b95-93b3-86a179495e58)
- Time logs
![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/c788656d-0c21-44df-8c3d-525b9fa9e88d)
- work orders markings specs actuals
![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/ddf9239b-6359-4217-a9a4-a8eccf6fdfa7)

**Comment by susannegov** [comment]
- Added `markings_work_orders` connection field to
   - `inventory transaction`
   - `work_orders_signs_markings_specifications_actuals`
   - `work_orders_signs_markings_time_logs`
- Added record rule to force update the record to `markings_work_orders`

# To do
- [ ] Batch update the three grandchildren records with markings work orders

**Comment by ChristinaTremel** [comment]
Closing this issue because we created the pages and are working on additional configuration in other issues.

**Comment by ChristinaTremel** [comment]
Noticed some inventory transactions records were missing and needed to do more batch updating:
- [x] `19084` inventory transaction records
   ![image](https://github.com/cityofaustin/atd-data-tech/assets/61209591/8abb1e41-e27d-4b50-bfef-551b0f11be6e)
