### ISSUE TITLE
Additional enhancements for `Manage Vehicles` page requested by AMD

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#14356]
Billy, Andrew, Edward, and Miles scheduled a meeting with me to discuss some additional things they'd like to change in the fleet management page for Arterial Management. The reason for these changes is because AMD's process for managing fleet differs from SMD. SMD has technicians tracking fleet activities and AMD is going to manage fleet from a Supervisor level.  
- [x] Add most recent Vehicle Log information on the table view of the vehicles
   - [x] Updated connected Record Rules 2-5 for when vehicle status changes, change `MODIFIED_BY` and `MODIFIED_DATE` to current date
   - [x] Sort `MODIFIED_DATE` chronologically from newest to oldest for `Vehicles` in Manage Vehicles page
   - [x] Sort `Date of Action` chronologically from newest to oldest for `Vehicle Log` in View Fleet Vehicle Details page
- [x] Update `Action` field to include (they will send an updated items if they think of additional drop down options)
```
Dropping off vehicle
Picking up vehicle
Loaned vehicle/equipment
Fleet - Quick Fix
Request for PM
Requested for Recall
Retire Vehicle
```
- [x] Set Action from Radio Button to One Selection - Dropdown
- [x] Retire Vehicle - If this action is selected, page rule to hide all fields except for `Vehicle Note` and when this action is selected, make record rule to update `Vehicle Status` to `Out of Service - Retired`
![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/4b3ce0e7-458a-4e5c-bc47-de616a46ebd1)
- [x] Make record rule to update `Vehicle Status` to `Out of Service - Retired` and `MODIFIED_DATE` and `MODIFIED_BY`
- [x] Make record rule to update `MODIFIED_DATE` and `MODIFIED_BY` for connected records of fleet_vehicles on all form submissions
- [x] Add `Vehicle Status` to `fleet_vehicle_trackings`
    - Out of Service - Diagnostic 
    - Out of Service - Retired
- [x] Add Record Rule for when Vehicle Status is set to Retire vehicle update this record
![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/68ba0336-7071-4b68-a2d2-4beb6d74c6ab)
- [x] `Manage Vehicles` page 
    - [x] Filter `VEHICLE_STATUS` is not Out of Service - Retired retired vehicles on the opening screen
    - [x] Add `Add Log` action column to the Manage Vehicles table so vehicle logs can quickly be added
    - [x] Display Rule for inline editing columns color to #faf18c and record rules for `MODIFIED_BY` and `MODIFIED_DATE` fields - Want to be able to update the `Assigned Driver` on the main page
- [x] For `Edit Vehicle`
   - [x] Change to modal pop-up and keep modal open until action
    - [x] ~~Delete~~ Retire the ROW vehicle record
        - The ROW record had 4 work orders associated to it so I set it to Retired status 
    - [x] Remove `Workgroup` from Manage Vehicle table
    - [x] Add `VIN Number` short text field
       - [x] Validation Rule when character count is not 17 characters:
       - `The VIN Number must be 17 characters long. Please enter a valid VIN Number.`
    - [x] Add `Current Driver` field
    - [x] Make `Assigned Driver` and `Current Driver` field editable.

**Comment by susannegov** [comment]
# Additional Changes
- Added `Current Driver` to log form, manage vehicle table, and vehicle log table and added record rules to parent/child
- Added `Out of Service - Diagnostic` to `fleet_vehicle` and added record rules to parent/child
- Added `Out of Service - Diagnostic` button to Manage Vehicles page
- Moved `Category` field from bottom to top of form
- Changed `Category` from drop-down to radio buttons since only 2 options
- Updated `In Service Date` when Vehicle log changes action to in-service

**Comment by ChristinaTremel** [comment]
## 11/17 Notes
**Attendees:** Billy, Susanne, Andrew, Edward Miles, Christina
- `Add Log` Form from the front table view
   - [x] Remove `Assigned Driver` and deleted associated record rule
   - [x] Remove `Current Driver` and deleted associated record rule
   - [x] Remove `Location` 
- `Vehicle Type` isn't important because we know which are rental and which are owned. 
   - [ ] To simplify, delete `Vehicle Type` entirely
      - From Table
      - From `Add Form`
- Manage Vehicle Table
   - [x] Billy doesn't need the `Year` so we can delete that field
   - Each vehicle is assigned to a specific service center that they are suppose to go to. They have been asked by fleet to go to a certain Service Center. 
      - [ ] Take `Location` field off of the fleet_vehicle_tracking object and add it to the `fleet_vehicles object 
      - [ ] Add `Location` to the Manage Vehicles table
- [x] Updated process for changing the `Current Driver` field so it inserts a vehicle log record capturing anytime the current driver is updated:  
   ![image](https://github.com/cityofaustin/atd-data-tech/assets/61209591/24be323b-037e-401f-81e1-a951d58b703b)
- [x] Made the same rule updates for `Assigned Driver`:
   ![image](https://github.com/cityofaustin/atd-data-tech/assets/61209591/c598098b-5685-4afd-9214-70bc120dd851)
- [x Same rules for updated `SC LOC` (service center location)
   ![image](https://github.com/cityofaustin/atd-data-tech/assets/61209591/2add7abd-7b44-40f1-97de-30f8b399ca81)

**Comment by susannegov** [comment]
Removed `Vehicle Type` from `fleet_vehicle_tracking` object table.

![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/783450fd-9e2e-4996-94c8-4738753047d6)
