### ISSUE TITLE
Project: Update DTS Service Request Workflow

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#14501]
We have some overdue updates to the DTS Service request.

**Features**
- New service request module in the DTS Portal 
  - Service desk triage interface to keep sensitive information out of GitHub
  - Service request configuration interface to give Product + Apps a simple way to update Division names, service request assignments to PMs and/or team leads

## Process
- [x] Configure triage interface in Knack - Diana
- [ ] Configure UI for Apps + Product to update automated issue assignments, division/application names, etc. without Dev support - Diana
- [ ] Provide specs for 👇 service request form and taxonomy updates
- [ ] Configure service request form updates in DTS Portal - Diana
   - [ ] [Update Applications](#26631) 
   - [ ] [Update Data Science service requests](https://github.com/cityofaustin/atd-data-tech/issues/14499)
   - [ ] [Update Geo service requests](https://docs.google.com/spreadsheets/d/1K9DVz7_wqD1773ABQYce5zoP32cNvBp2PModQRDxwrY/edit) based on - #14404
   - [ ] Update DTS Portal Divisions - needs issue [specs](https://docs.google.com/spreadsheets/d/1YstfW7rYZU13VKU2k--XrteOYHI7SADZU4KDm-XhYVQ/edit) - new divisions, new labels and the update from 'Workgroup:' to 'Division:" - Amenity needs to 
- [ ] Scope [atd-service-bot specs](https://github.com/cityofaustin/atd-data-tech/issues/29050) for Dev Team - Diana
- [ ] Update Knowledge Base service desk documentation as needed

**Comment by amenity** [comment]
@andrewshensky @Charlie-Henry @katelunceford - Did I seriously drop the ball this hard? It looks like we have specs to update both service requests in the subissues here. Want me to make it happen?

**Comment by amenity** [comment]
@TracyLinder - if you want to add your product here, that would be great

**Comment by dianamartin** [comment]
# 7/10/2026
Have been working with Frank for the last few weeks (Since 6/25/26) and syncing every few days on our progress and identifying any additional actions we need to take. 
- Met several times 7/2/26, `Sync about go-live for SR triage process changes`
- Impromptu syncs
  - 7/9/26
  - 7/10/26 am
  - 7/10/26 pm
- Have a scheduled go-live for Monday, 7/13/26 at 4 pm
- Plan to introduce the new process to the rest of th team at the DTS Monthly Meeting, will have a small presenation about the change

**Comment by amenity** [comment]
@frankhereford @dianamartin - y'all feel comfortable calling this complete as of July 14th-ish? 
And a start date around May 15th, Diana?

**Comment by frankhereford** [comment]
@amenity July 14th is 💯 -- that's the day Diana did the training in the team meeting. Thank you for documenting that.

**Comment by dianamartin** [comment]
@amenity we have record that we put Service Requests triage enhancmenet on the [Dev + Product Sync agenda](https://docs.google.com/document/d/1hWzg-qluRBrTetEGjg_eHrR9qT4IqenaUgk6FR6APbU/edit?tab=t.0) as of 1/14/26, so really I think we could say it started then.

**Comment by amenity** [comment]
Thanks, @dianamartin @frankhereford. And definitely feel free to update the start and completion dates for your projects directly in the future!
