### ISSUE TITLE
Email SMB Data Tracker users about Maintanence Outage (2/21) @ 2:30 pm

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#1453]
- [x] Drafted an email, showing to SMB to see if there's anything else to add. 
- [x] Downloaded list of users to know which ones were active/inactive
- [x] Adding users to email
- [x] Sending email

**Comment by dianamartin** [comment]
- [x] The first email was sent out on 2/21 @ 11:02 am
- [x] Maintenance started email sent out @ 2:02 pm
- [x] Maintenance completed email sent out @ 3:57 pm
