### ISSUE TITLE
Update "Close Work Order" record rules to newest `work_orders_preventative_maintenance` object.

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#14552]
Ran across this, noticed it while I was documenting hub cabinet asset steps. 

Need to update `signals_preventative_maintenance_HISTORICAL` to use the newest PM object `work_orders_preventative_maintenance` object.

- Need to run this by Billy, to see if this is an issue

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzZpQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c4f6608563dddc1384f954f0fa2e832b30cb4df1/image.png)

**Comment by ChristinaTremel** [comment]
@dianamartin this has to be how users are creating Historical Preventative Maintenance records occasionally!! We definitely want this pointing to the new object! 🙏🏼

**Comment by ChristinaTremel** [comment]
- Brought this up in sprint review and we do need to deprecate the historical rule (number 5)
- Get rid of record rules that include PM HISTORICAL association
- Jorge brought up issue where a work order that's for preventative maintenance is reopened and when it's closed again, it duplicates the preventative maintenance record on the signal details page (create new issue)

**Comment by dianamartin** [comment]
# 1/24/24
## Build Notes
- [ ] Remove Record Rule # 5
- [ ] Export back up of WO PM Historical
- [ ] Import records into WO PM (New)

**Comment by dianamartin** [comment]
# 1/25/24
- WO Technicians>Close Work Order form
- [x] Removed Record Rule # 5
