### ISSUE TITLE
Project: TPW GIS Emergency Management Support

### ISSUE THREAD

**Issue by andrewshensky** [cityofaustin/atd-data-tech#14602]
## Background

This project is a collaborative effort between Transportation Public Works’s Data and Technology Services division, Street and Bridge Operations, and the Emergency Operations Center with the goal of improving the city’s ability to respond effectively and efficiently during emergency events. This project is currently focused on identifying critical infrastructure (hospitals, fire stations, water treatment plants, etc.) across the city, determining the ideal routes for road clearing within the first 48 hours of a winter storm event, and serving this dataset in a web format that can be used during emergencies.

## Scope & Deliverables

- Identify and geocode primary and secondary critical infrastructure
- Review existing critical arterial data and update according to new critical infrastructure and capacity for road clearing
- Develop internal review and editing process for engineers to update arterials
- Create an event dashboard to be used by emergency personal, both at an operations center and in the field, during a winter storm event

 
## Desired Outcomes

Provide operations and field personnel with streamlined data platforms and dashboards for effective winter storm roadway clearing.
 
## Timebox

By the end of December 2023, complete the geocoding of all critical infrastructure and generate a preliminary revision of critical arterials to prepare for winter storm events in February.

By the end of January 2024, establish a user-friendly web application, accessible on both desktop and mobile devices, providing operations and field staff with immediate access to updated data for efficient decision-making during winter storm roadway clearing.

Long-Term Goal (by the end of 2024): Enhance the web application with real-time data integration, incorporating truck locations, citizen service requests via 311, operations center work orders, and additional datasets identified by stakeholders to further improve citywide responsiveness and decision-making capabilities.

![EM_Project_Image](https://github.com/cityofaustin/atd-data-tech/assets/80716478/665bdf4f-3731-4258-b663-e5cfab522bd6)

---
This Github issue represents a project of Austin Transportation's [Data & Technology Services](https://austinmobility.io/) team. Project status is documented regularly in the comments below.

**Comment by amenity** [comment]
I'm removing the `Project Index` label since this is missing the necessary information and is in the "Ongoing" pipeline.

**Comment by GimnichD** [comment]
[Link to the 2025-04-23 notes](https://docs.google.com/document/d/1EWn5GOzisJEmiLF1M7fpQiIiyoudQfZjIxFHBbwfhpo/edit?tab=t.0)

**Comment by GimnichD** [comment]
[Link to the 2025-05-15 meeting notes](https://docs.google.com/document/d/19YDji1bK3iFuxNIj__Oc0gFLI49EVXOUECnj7IxycOA/edit?tab=t.w4v4md2b5pq8#heading=h.5e068usyqwk)
Action items:

- [ ] David - set up meeting with the four of us and Dave A
- [ ] David - reschedule meeting with Urban Forestry
- [ ] David - convert meeting to 1.5 hours
- [ ] Everyone - review data dictionary descriptions
- [ ] Everyone - review list of action items
- [ ] Will - adding to data dictionary for Critical Facilities
- [ ] Grant - FME for intersections with Andrew
- [ ] Grant - message Braniff and Christian
- [ ] Owen - prepare to present bounding and treatment relation
