### ISSUE TITLE
FME to add `Work Date` from contractor and in-house work orders to short_line_dates table in EDP/ODP

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#14706]
Made updates to the FME to update `MarkingsDateTablestoSocrata`. Before, we didn't have anything updating the `short_line_dates` table in the EDP/ODP with actual work dates. 

We wanted to use the Roadway Markings Contractor Work Order and Roadway Markings Work Orders (in-house) to add `Work Dates` to the short line dates table in the EDP and ODP. This is so dates are captured easily in the PowerBI dashboard.

**Comment by ChristinaTremel** [comment]
Had 4 work sessions to work on this: 
- 10/23/23
- 10/25/23
- 10/30/23
- 11/21/23

Had quite a few issues with the date formatting that we had to troubleshoot, but this FME work flow successfully updated the work dates for contractor and in-house work orders: 
![image](https://github.com/cityofaustin/atd-data-tech/assets/61209591/aaa376bf-89bf-492d-bfa4-98571b7a5ff1)

**Comment by ChristinaTremel** [comment]
11/21 Progress Updates
- Can run from the workbench successfully and publish on City Datahub
- Having issues publishing to the FME server. This errors are happening because the Reader is not being recognized by FME server. 
   - ![image](https://github.com/cityofaustin/atd-data-tech/assets/61209591/a4f39465-9b15-4f9e-897c-34768850fa13)
   - Susanne reached out to Anthony S (Austin Code) and he was able to use the updated Writer, but doesn't user Socrata Reader
- **Next Steps:** Submit CTM ticket and ask to add the new Socrata package into FME Server.  
   - Andrew is planning to submit a ServiceNow ticket

**Comment by susannegov** [comment]
Meet on 11/30 with Kevin S.
- Issue resolved with FME Server upgraded to FME fFlow in the test environment from CTM
- No errors

**Comment by susannegov** [comment]
Met on 12/21 to resolve issue with new socrata writer not publishing dates

**Comment by susannegov** [comment]
# 1/22
- [x] Updated Work Date for markings_specialty_line_dates
- [ ] Submitted ticket to add WORK_ORIGIN to GISDM for markings_specialty_point_dates in ServiceNow
   - [ ] Once WORK_ORIGIN has been added, will need to update the conditional rules for Work Date in markings_specialty_point_dates

**Comment by susannegov** [comment]
Updated column metadata and Andrew updated FME server with work origin field yesterday. Closing issue.
