### ISSUE TITLE
Redirect page to Communications Work Order Details page when new work order is submitted

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#14750]
> What application are you using?

AMD Data Tracker

> Describe the problem.

When creating new "Communications" work order, need to direct to the "Communications Work Order Details" page instead of the "My Work Order Details" page (where it's going now). This is happening when a new work order is submitted. 

> Website Address

https://atd.knack.com/amd#work-orders-communications/workorder-details/65663e1c21603d00277cb8de/

Internet Browser: Chrome

> Requested By
Harrell M.

Request ID: DTS23-111160

**Comment by ChristinaTremel** [comment]
## Notes from Updates in Test
Used `TEST | AMD Data Tracker | 11 May 2023` environment
- [x] On Trouble Call work order form, I expanded the submit rules to direct to: 
   - My Work Order Details when work group is not communications
   - Communication Work Order Details when work group is communications
   - Defaul tto My Work Order Details
- [x] Created `WRK24-186260` and `WRK24-186270` for the communications work group and was navigated to the Communications Work Order Details page
- [x] Created `WRK24-186265` for the technician work group and was navigated to the My Work Order Details page

**Comment by ChristinaTremel** [comment]
Reviewed and tested this in refinement and we are good to implement these rules into production: 
- Add rules to Scheduled Work and Trouble Call work order forms
![image](https://github.com/cityofaustin/atd-data-tech/assets/61209591/7ef22b40-1a6e-430f-b0ae-1e2fbf37b4c7)

**Comment by ChristinaTremel** [comment]
Implemented these submit rules to the Trouble Call new work order form and the `Save and Continue` form on the Scheduled Work task form. Ready for review!

**Comment by ChristinaTremel** [comment]
This was completed and reviewed with AMD during their sprint review in June!
