### ISSUE TITLE
Prototype Project Intake WO form and review cycles

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#14764]
## 11/20 Meeting
- **Attendees**: Brian C, Christina, Ivonne, Erin, Jorge, and Scott 
- **Goal**: Identified fields and process outline to prototype initial work order form and review cycles

### New Project Intake Work Order Form Fields
- `Requester Type`
   - Internal (example: TPW Staff, Capital Project Delivery)
   - External  (example: Consultant, Contractor, Developer, Travis County, TxDOT, Williamson County)
- If internal, automatically capture:
   - `Created By` (based on user logged in)
   - `Division`
- If external, capture
   - `Name` (in open text field)
   - `Phone Number`
   - `Email`
- `Project Point of Contact/PM`
- `Additional Point of Contacts` (open text field)
- Moped Project ID (link)
- `Request for new or existing asset?`
   - New
   - Existing
-  If existing: `Is this request for an existing signal/PHB?` (yes/no)
   - If yes: 
      - `Signal` dropdown field (name `Signal/PHB Asset`)
   - If no: 
      - `Address`
      - `Primary Street`
      - `Cross Street`  
- If existing: `Is this request for a signal modification` (yes/no)
   - If yes: `Categories of Modifications` (multiselect field)
      - APS
      - Q Jumps
      - Lane Assignments
      - Backplates
      - Ped Reconfigurations
      - Bike Signals
      - Detection Improvements
      - New Approach
      - Art Boxes
      - Special Event Assistance
      - Leading Pedestrian Integrals (LPI)
      - Pilot Project
      - Other - open text field to explain
- If new: `Asset Type`
   - Signal
   - PHB
   - RRFB
- If new: `Categories of New Signal Support`
   - Design Review
   - Construction Support
   - Implement Project Construction
   - Site Feasibility
   - Study
   - Other - open text field to explain
- If new: `Has a signal study been performed and reviewed by the Arterial Management Division?` (yes/no) 
- `Project Timeline`
- `Request Timeline`
- `Funding Info`

### Fields for Ivonne's team to fill out when project intake occurs
- `Signal Engineering Due Date`
 
### Features on Work Order Details Page
- Attachments
   - Attachment Types:
      - Plans
      - Signal Study
      - Project Website (link)
      - Photo
      - Other
- Table for Review Records with button to add Reviewer:
   - `Review Cycle` (selected by Ivonne's team)
      - Signal Engineering Concurrence
      - Infrastructure/Constructibility Assessment
      - Operations/Inventory
      - Draft Cost Estimate/Cost Estimate Review
   -  For Review Cycle: `Signal Engineering Concurrence`
      - `Due Date` (selected by Ivonne's team)
      - `Assigned To` (selected by Ivonne's team)
      - `Reviewer`
      - `Date`
      - `Approved` (yes/no)
      - Signal Engineering `Assessment Notes` (open text field)
   - For Review Cycle: `Infrastructure/Constructibility Assessment`
      - `Due Date` (selected by Ivonne's team)
      - `Assigned To` (selected by Ivonne's team)
      - `Reviewer`
      - `Date`
      - `Approved` (yes/no)
      - `Schematic Ready` (yes/no)
      - Constructibility `Assessment Notes` (open text field)
   - For Review Cycle: `Operations/Inventory`
      - `Due Date` (selected by Ivonne's team)
      - `Assigned To` (selected by Ivonne's team)
      - `Reviewer`
      - `Date`
      - AMD Field Work/Inventory `Assessment Notes`
   - For Review Cycle: Draft Cost Estimate/Cost Estimate Review

**Comment by dianamartin** [comment]
# 1/16/2024
Prototype Goals are:
- [ ] Form for requesters to submit project intake request
- [ ] Main table for "Projects Requests"
- [ ] Project Request Details page
  - [ ] Related table of "Reviews"
  - [ ] "Attachment" tables

## Build Notes
### Object Table
- [ ] Create `project_requests` 
- [ ] Fields
- Requester Type
- Created By
- Division
- Requester Name (ext)
- Phone Number (ext)
- Email (ext)
- Project Point of Contact/PM
- Additional Point of Contacts (Long Text)
- Moped Project ID - connection? (We have 322 records, right now)
- Request for new or existing asset (Y/N)

### EXISTING
#### Record Rule: 
- [ ] Yes: show `Signal` - connection field
- [ ] No: fill out new fields
  - `Address`
  - `Primary Street`
  - `Cross Street`
#### MOD: 
Request for signal modification (Y/N)
- [ ] Yes: show new field `Mod Categories` 
  - [ ] Q Jumps
  - [ ] Lane Assignments
  - [ ] Backplates
  - [ ] Ped Reconfigurations
  - [ ] Bike Signals
  - [ ] Detection Improvements
   - [ ] New Approach
   - [ ] Art Boxes
   - [ ] Special Event Assistance
   - [ ] Leading Pedestrian Integrals (LPI)Pilot Project
   - [ ] Other - open text field to explain
    - [ ] Need to add a new field `Other - explain`
    - [ ] No: fill out new fields
### NEW
If new `Asset Type`
 - Signal
 - PHB
 - RRFB 
- [ ] Categories of New Signal Support
- Design Review
- Construction Support
- Implement Project Construction
- Site Feasibility
- Study
- Other - open text field to explain
 - [ ] Need to add a new field `Other - explain`

### Additional Fields
- [ ] Has a signal study been performed and reviewed by the Arterial Management Division? (yes/no)
- [ ] Project Timeline
- [ ] Request Timeline
- [ ] Funding Info - Long paragraph
- [ ] Signal Engineering Due Date

**Comment by dianamartin** [comment]
# 1/17/2024
Using AMD's existing object table
- `work_order_signals_images`
- [x] Create connection to `project_requests`
 - [x] Added "Attachment Description" - Short text
 - [x] Added "Attachment Link" - Link
- [x] Added new field "Attachment Type" - Multi-choice
  - [x] Choices
  - Plans 
  - Signal Study
  - Project Website (link)
  - Photo
  - Other
 - [ ] Adding Record Rule for when "Project Website (link)" is selected that "Attachment Link" shows up as well

**Comment by ChristinaTremel** [comment]
- [x] Added `Project Request Status` to `project_requests` object
- [x] Added `Review Status` to `project_reviews` object
- [x] Updated Reviews table and forms with new fields

**Comment by dianamartin** [comment]
# 1/23/24 
@ChristinaTremel Ready for review?

**Comment by ChristinaTremel** [comment]
Questions to ask during review 2/5:
### Project Intake Request Form: 
- Preference on how to identify location for a `New` asset request type
   - OPTION 1: Primary Street and Cross Street
   - OPTION 2: Full Address
- How to identify location for an Existing RRFB asset request type
   - Currently nothing shows up
   - Do we want to use Primary Street/Cross Street or have a drop down of locations for RRFBs 
- Are we missing any fields for the request form
- Currently `Internal` request types have the Moped Project ID field showing up. Is that correct or should it be showing for both internal and external

### Project Intake Review Process
- Currently have 3 reviewer types, but when we met previously we briefly touched on adding:  `Draft Cost Estimate/Cost Estimate Review` as a type
   - The other reviewer types are all subgroups of AMD, but this is a type of review. Should we add a new field for what type of action the reviewers need to take? 
- We are missing the `Communications` work group here and potentially some others. Should we add those? 
   <img src="https://github.com/cityofaustin/atd-data-tech/assets/61209591/6ef6e154-24a5-4d0b-8989-aad0f9bd445e" width="300" />

**Comment by dianamartin** [comment]
# 2/5/2024
## Diana's Notes

- Using the word "asset" v. "component"

New Asset selection
- radio selection "Address" v. "Primary/Secondary fields"
- [ ] Add new field "Location Type"
- Intersection - "Primary/Secondary fields"
- Section of Road 
- Specific Location - "Address"

**Reference**
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/536403e1-396c-4c93-bb9b-440a6476e159)

**Comment by ChristinaTremel** [comment]
## To Do from Review 2/5
### FORM: New Project Intake Request
- [ ] Add radio button for `Location Type` 
   - include Specific (actual address), intersection (primary street/cross street), or Section of Road
   - Reference Traffic Count 
- [ ] Change `Asset Type` drop down to radio buttons
- [ ] Add question with radio button to select `Single Location` or `Multiple Locations`
   - If single, keep structure of asset information the same (might need to set up a rule to insert a record into a related table of assets)
   - If multiple, hide asset fields from first page. Create secondary page with a related table for the Requester to add multiple assets to the request
- [ ] Add `Requested Task` field to the related table of assets
- [ ] Also include a space for Requesters to include attachments on the request  

### PAGE: Project Intake Details
 - [ ] Add comments table where AMD can add logs of emails they've sent to users (have the ability to send email from Knack) and to track the initial part of the request where Ivonne's team is clarifying the details of the request
 - [ ] Schematic Ready -> turn into an attachment that's included, not just the yes no field?
 - [ ] Set up record rules for the Project Reviews `Status` updating and show the status on the Project Reviews table

**Comment by dianamartin** [comment]
# 2/5/2024
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/80a96ec0-85a6-4b15-a6b2-9b90804722e8)

**Comment by dianamartin** [comment]
Created new issue for updated feedback requests # 15650, closing.
