### ISSUE TITLE
Data Collection Requests table field restrictions

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#14794]
> What application are you using?

AMD Data Tracker

> Describe the problem.

I want to discuss the possibility of making some fields of the Data Collection Requests table to be locked.

> Describe the outcome you'd like to see when this feature is implemented.

Only certain fields can be edited by others.

> Describe any workarounds you currently have in place or alternative solutions you've considered.

N/A

> Requested By
Shelby S.

Request ID: DTS23-111240

**Comment by ChristinaTremel** [comment]
Scheduled check in with Shelby to collect more information on 1/3/2024.

**Comment by ChristinaTremel** [comment]
### Current process & what's happening now:
- Data Collectors came back to TED from AMD and through learning how their side of the world works, what Shelby ended up doing was meet with them every week and decide who has capacity and Shelby will assign based on location, work load, requester. That has all worked well, but what's started happening is Jaime or Ray are coming in and they will reassign from one person to another or put something on hold
### What should they be doing?
- Go into the details page, review, add attachments and add special instructions

### Proposed Solution:
- Within the `Manage Request Details Page` we would like to add the `Special Instructions` and `Attachment` fields to a single form to be filled out by Ray and Jaime. 
   - Add button to `Upload & Complete`
   - When form is submitted, would like to set up a rule to update the status to "Completed"
- Lock down the [Manage Requests ](https://atd.knack.com/amd#traffic-count-traffic-data-requests/manage-requests/) table to only be editable by Shelby and limit the use of the `Edit Request` button within the details page (should only be edited by Shelby or Requester)

- Preferred timeline: no rush, but maybe within the next 4-6 weeks would be good.

**Comment by ChristinaTremel** [comment]
### Manage Requests
- Within the Manage Request Details Page we would like to add the Special Instructions and Attachment fields to a single form to be filled out by Ray and Jaime.
   - Add button to Upload & Complete
   - When form is submitted, would like to set up a rule to update the status to "Completed"
- Lock down the [Manage Requests ](https://atd.knack.com/amd#traffic-count-traffic-data-requests/manage-requests/)table to only be editable by Shelby and limit the use of the Edit Request button within the details page (should only be edited by Shelby or Requester)
### Statuses of Data Collection Requests
- `Unscheduled`: When there's no assigned date 
- `Scheduled`: Update Assigned Date and change it to Scheduled
- `Installed`: When Jaime and Ray update their form but don't check `Completed`, update status to installed. 
- `Completed`: Add completed date
- `Rescheduled`: Never use this - remove this
- `Cancelled`: Don't use this - delete and add notes - remove this if there's no historical records
- `On Hold`: Use this but is manually updated. Is used if it's under construction or if the requester asks for it to stay on hold

### Attachments 
- Allow 5 attachments at a time to be added to the table (similar to TDS)
- Blank attachments records get added and allow users to add:
   - Attachment Type
   - Attachment
- Add attachment types on the drop down:
   - 24HR | 24 Hour Count
   - SPD & VOL | Speed & Volume

**Comment by ChristinaTremel** [comment]
## Manage Requests
- Lock down the [Manage Requests ](https://atd.knack.com/amd#traffic-count-traffic-data-requests/manage-requests/)table to only be editable by Shelby and limit the use of the Edit Request button within the details page (should only be edited by Shelby or Requester)

### Within the Manage Request Details Page we would like to create a new form for Ray and Jaime to use: 
- [x] Updated `Edit Traffic Count Request` and included a form for Jaime and Ray that includes the `Special Instructions` and `# of Setups` from [traffic_counts](https://builder.knack.com/atd/amd/schema/list/objects/object_161/fields) object
- [x] Attachment table and button to add 1, 3, and 5 attachment records to the table
   - Allow 5 attachments at a time to be added to the table (similar to TDS)
   - Blank attachments records get added and allow users to add:
      - Attachment Type
      - Attachment
- [ ] Add additional multichoice [attachment types](https://builder.knack.com/atd/amd/schema/list/objects/object_174/fields/field_3174/settings) on the drop down:
    - 24HR | 24 Hour Count
    - SPD & VOL | Speed & Volume
- [ ] Add new `Upload Completed` checkbox to flag if the data upload is is complete or only partial
- [ ] Button at bottom of form to `Save`
- [ ] When the form is submitted and the `Upload Completed` is unchecked, would like to set up a rule to update the status to `Installed`
- [ ] When form is submitted and the `Upload Completed` is checked, would like to set up a rule to update the status to `Completed`

### Statuses of Data Collection Requests
- `Unscheduled`: When there's no assigned date 
- `Scheduled`: Update Assigned Date and change it to Scheduled
- `Installed`: When Jaime and Ray update their form but don't check `Completed`, update status to installed. 
- `Completed`: Add completed date
- `Rescheduled`: Never use this - remove this
- `Cancelled`: Don't use this - delete and add notes - remove this if there's no historical records
- `On Hold`: Use this but is manually updated. Is used if it's under construction or if the requester asks for it to stay on hold

**Comment by dianamartin** [comment]
# 7/22/24
- [x] Created a second table view on "Manage Requests" - 1 for the Data Collection team and 1 for the Program Manager
- [x] Created a new "Edit Work Order | Traffic Count" page (`edit-traffic-count-wo`)

**Comment by dianamartin** [comment]
# 7/23/24
- Jamie pinged me and said he he couldn't "Close" a work order
- I worked with him and we created a button "Upload Complete" 
  - we added "Completed Date" and "Upload Completed Date" (both required) - this button is used to "Close" a Work Order
  - Using the "Edit Work Order" to trigger the record rule "Installed" (new field), to determine it's in an "Installed" status
- I updated the "Status" field and added conditional rules
![image](https://github.com/user-attachments/assets/6e7eb7c1-baae-426c-9bb8-711e13853fc7)

**Comment by dianamartin** [comment]
# 7/24/24
FYI @ChristinaTremel 

- Jamie called me to say that he sees a change in the statuses
- I told him it was from the changes we made together yesterday
- I suggested he export the work orders and keep the "ID" and change the status and I can update the records based on what they should be.

**Comment by dianamartin** [comment]
# 7/30/24
- Jamie messaged
>still having issues in data tracker on closing requests
 
I looked at the Status rules and there were a few missing rules
- [x] Updated `Status` conditional rules
![image](https://github.com/user-attachments/assets/cc799475-eaae-4760-af47-dbc0e95cc3e4)
- [x] Jamie checked the work order he was trying to close and it looked like it updated to the correct status

I also noticed the "Edit Work Order" button still showing for him even though it's supposed to be hidden. 
- [x] Updated page rule on "Traffic Count Request Details" 
>The wrong menu was selected
![image](https://github.com/user-attachments/assets/3b685ebc-c3f9-42df-a5df-03098cb89b42)

**Comment by ChristinaTremel** [comment]
## 7/30 Check-In Meeting
**Attendees:** Christina, Diana, Shelby, Ray, Jaime
- Added record rules to Shelby's form because she wasn't able to complete requests! Tested the new process and she was able to complete requests as expected
- Reviewed new process that Ray and Jaime are already using - they noted that everything seems to work well for them and adding attachments is easier
- Closing out this issue 🎉
