### ISSUE TITLE
[BUG] Attachments broken within CSR Flex Notes for SMD

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#14792]
**Describe the bug**
When clicking `View Flex Notes` and then selecting `View Attachment`, the attachment link is broken. SMD needs to be able to see attachments for collecting more details about what the citizen is requesting.

**Screenshots**
   Mac users see:
   ![image](https://github.com/cityofaustin/atd-data-tech/assets/61209591/b4477d67-8091-40ee-a6cf-32c69c67fe24)

   Windows users see: 
   ![image](https://github.com/cityofaustin/atd-data-tech/assets/61209591/5dfcd34a-015a-4e4f-8bf6-8dcf70a2dff0)

**How would you rate the impact of this issue?**
- [ ] Severe — cannot perform work, no workaround
- [x] Major — can only perform work using a workaround
- [ ] Minor  — can perform work, but could be easier or faster
- [ ] Does not affect work performance
- [ ] Unsure

**Comment by ChristinaTremel** [comment]
Looked into this during the sprint review and it looks like 311 changed the link for the photos

**Comment by dianamartin** [comment]
# 12/1
Ex. 
[Old Link](https://311.austintexas.gov/media/austin/report/photos/64f6db6fe8964652f669bbd9/report.jpg)
[New Link](https://spot-moto-res.cloudinary.com/image/upload/v1696888228/austin/production/vdnznyktytqxjfmuply8.jpg)

**Comment by ChristinaTremel** [comment]
Sent Carrie an email on 12/13 asking about this issue and she had to follow up with Motorola and this is the details she provided.

> We reported this issue to Motorola and here is our finding:
For all SRs where a picture was submitted prior to the go live, November 28th, the paths have changed and departments will not be able to see those pictures in the interface. They will have to look in CSR or a report can be created with all the new links.

She also sent the open CSRs that were affected (and have broken attachment links) to SMD and DTS. I checked new SRs and confirmed that the attachments are working now and directing to the new URL.
