### ISSUE TITLE
Enhance our Signal Monitor page to include DARK signals

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#14912]
> What application are you using?

AMD Data Tracker

> Describe the problem.

Jim D. has requested we enhance our Signal Monitor page (https://data.mobility.austin.gov/signal-monitor?x=-97.749457&y=30.258698&z=11.91) and feed to Waze to not only show flashing signals (as it does now), but also include DARK signals. We currently track those during a storm or large outage event using a SharePoint excel. We need a way to either enhance the Signal Monitor datafeed (which is automated and comes from KITS SQL) with the SharePoint data or a new tool to track dark signals in real time.

> Describe the outcome you'd like to see when this feature is implemented.

See above

> Describe any workarounds you currently have in place or alternative solutions you've considered.

previously added a banner to the signal monitor page with a list of dark signals. Currently using a SharePoint excel to manually track dark signals.

> Is there anything else we should know?

Mid January for winter weather preparedness per Jim D.

> Requested By
Lance B.

Request ID: DTS23-111415

**Comment by dianamartin** [comment]
# 12/11
## Option 1
Signal Monitor data feed (which is automated and comes from KITS SQL) with the SharePoint data
- Level of effort: Very Difficult
This process is pulling data from a system (KITS) in order to create a the Signal Monitor data feed. The purpose of the map was not to pull a new source data into this map and this may be difficult, as this hasn't been done in the past. 
- Taking on this project may lead us into a longer timeline because of the complexity of this approach
- This data is authoritative from the KITS system and we'd be manipulating it with a manually managed spreadsheet by doing this 

## Option 2
New tool to track dark signals in real time
- Level of effort: Medium
- In the 2023 Winter Weather Exercise a lot of the feedback was on GIS and mapping emergency management assets/tasks. I have already talk to the GIS team about creating a new field map, web map, web application that would be a quick solution for any emergency management situation. We could easily create a new feature class for dark signals and all the MMC staff to update the GIS feature layer. We can then overlay the dark signals information on this map and look into seeing how much of a lift it is to create a new AGOL feature layer from the Signal Monitor dataset. 

### Phase 1: Creation of AGOL feature layer & map for Dark Signals
- GIS team can do this quickly and allow editing for MMC staff 
- We can create a public map and an operations map as needed

### Phase 2: Creation of AGOL feature layer for Signal Monitor
- We have to inquire with the Dev team to see what the level of effort for this is, what the complexity is

**Comment by ChristinaTremel** [comment]
@johnclary do you have any thoughts on this request/how difficult it would be to implement? Diana has her proposed thought above because the initial ask of updating this [Signal Monitor dashboard ](https://data.mobility.austin.gov/signal-monitor) with a spreadsheet seemed pretty complicated.

**Comment by johnclary** [comment]
This is similar to a request we had sometime in the recent past about being able to override the status we get from KITS with a status in the Data Tracker. Am I remembering that correctly? And that's why we now have a signal status in the data tracker for "On flash":

<img width="553" alt="Screenshot 2023-12-12 at 12 51 46 PM" src="https://github.com/cityofaustin/atd-data-tech/assets/14793120/0fe13f21-f405-4a59-98ee-edc604615411">

But AFAIK we didn't actually implement these overrides in the signal status dataset?

In any case, my short answer is that this would be much more feasible of AMD tracked "dark" signals in the Data Tracker or KITS.

**Comment by johnclary** [comment]
Ii think the ideal solution would be to:
- track dark signals in the Data Tracker
- update the Signal Monitor ETL to override the KITS statuses when the Data Tracker has a “dark” status
- update the existing signal monitor dashboard to show “dark” statuses

A dev could probably make the ETL enhancements in 8 hours. and there’s probably another day or two of work to get dashboard updated. we would need a PM to mock up the dashboard changes.

**Comment by dianamartin** [comment]
@johnclary We also need an estimate for conversion of Signal Monitor dataset into AGOL feature. Is this easy, medium, difficult?

**Comment by johnclary** [comment]
@dianamartin i would say "medium", but that task would probably require us to first do what i described in my last comment. probably this discussion needs to come to the dev refinement meeting.

**Comment by ChristinaTremel** [comment]
- Get with Lance to find out what color and icon for Dark Signals.

**Comment by patrickm02L** [comment]
@ChristinaTremel [here's](https://react-icons.github.io/react-icons/search/#q=light) where you can find the icons for the "dark" filter. 

I would recommend one of these purples which are out of the box --bs-indigo: #6610f2
    --bs-purple: #6f42c1

**Comment by chiaberry** [comment]
the other icons we use are in the font awesome category, in case you want to stick with the same category: https://react-icons.github.io/react-icons/icons/fa/

**Comment by ChristinaTremel** [comment]
Reached out to Lance and asked him to choose an icon and color for symbolizing the dark signal status!

**Comment by ChristinaTremel** [comment]
### Build Notes for Apps
(@dianamartin want to sync with you when you get back to make sure this makes sense)
- [ ] Add `FLAG_DARK_SIGNAL` yes/no field to `signals` object
- [ ] Create page for the MMC to easily flag dark signals in emergency situations
   - ![image](https://github.com/cityofaustin/atd-data-tech/assets/61209591/901fdf23-8478-4a86-951a-2bb42d3b3fd0)
- [ ] Add new field to `signals` API view (or create new API view for the Dev team to pull from?)

### Build Notes for Devs
- [ ] Update the Signal Monitor ETL to override the KITS statuses when the Data Tracker has a “dark” status
- [ ] Update the existing signal monitor dashboard to show “dark” statuses

**Comment by johnclary** [comment]
@ChristinaTremel @dianamartin just a reminder that when you create the knack form(s) to edit the dark status, make sure to configure a submit rule that updates the modified date of the signal so that it gets picked up by the ETL.

**Comment by ChristinaTremel** [comment]
-  Notes from #11435 

## Next Steps
In order for there to be a "manual override" like Lance describes, we would need to add a new column to the signal_assets object table in the Data Tracker where MMC staff can set the override status

### APPS
   - Add field status_override (Multichoice field type)
   - Options from existing Operation State field (and ensure Dark Signal is an option)

### DEV
   - Update the [signal status ETL](https://github.com/cityofaustin/atd-kits/blob/production/atd-kits/signal_status_publisher.py) to incorporate this override column

**Comment by dianamartin** [comment]
# 1/4/24
### Build Notes
- [ ] Add `FLAG_DARK_SIGNAL` field to `signals` object
- [ ] Add Record Rule to update Modified Date
- [ ] Create page for the MMC to easily flag dark signals in emergency situations
    ![image](https://github.com/cityofaustin/atd-data-tech/assets/61209591/901fdf23-8478-4a86-951a-2bb42d3b3fd0)
- [ ] Add new field to `signals` API view (or create new API view for the Dev team to pull from?)

### Build Notes for Devs
- [ ] Update the Signal Monitor ETL to override the KITS statuses when the Data Tracker has a “dark” status
- [ ] Update the existing signal monitor dashboard to show “dark” statuses

**Comment by ChristinaTremel** [comment]
Questions for MMC: 
- Should we filter the list of signals to only those with status `TURNED_ON`?

**Comment by ChristinaTremel** [comment]
@johnclary should we add the new dark signal override field to the existing `signals` API table so the dev team can pull from it? We just don't want to break anything!

**Comment by ChristinaTremel** [comment]
## Build Notes - Devs
- Metadata refresh and update refresh frequency to every 5 minutes for the [Traffic Signals and Pedestrian Signals](https://datahub.austintexas.gov/Transportation-and-Mobility/Traffic-Signals-and-Pedestrian-Signals/p53x-x73x/about_data) Socrata dataset
- Add Dark Signal Status into the [Traffic Signals Status](https://data.austintexas.gov/Transportation-and-Mobility/Traffic-Signals-Status/5zpr-dehc/about_data) Socrata dataset as an additional status that supersedes the KITS status
- Update the Signal Monitor ETL to override the KITS statuses when the Data Tracker has a “dark” status
   - https://github.com/cityofaustin/atd-kits/blob/production/atd-kits/signal_status_publisher.py- 
- Update the existing signal monitor dashboard to show “dark” statuses with: 
   - This icon: 
        <img src="https://github.com/cityofaustin/atd-data-tech/assets/61209591/fb4f1979-c4ac-460e-af0c-a6e42e12dfeb" width="150">
   - And this symbol color: black #000000

**Comment by ChristinaTremel** [comment]
Closing because dark signals are now included in the signal monitor page and we removed comm outages to make the signal monitor page more clear to the public.
