### ISSUE TITLE
Page development for temporary stop sign deployment as part of emergency operations/winter storm pre...

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#14913]
> What application are you using?

AMD Data Tracker

> Describe the problem.

Page development for temporary stop sign deployment as part of emergency operations/winter storm preparedness

> Describe the outcome you'd like to see when this feature is implemented.

Simplified deployment of signs & markings staff to deploy and return temporary stop signs

> Describe any workarounds you currently have in place or alternative solutions you've considered.

None-emails and calls

> Is there anything else we should know?

By end of December 2023

> Requested By
Allyson R.

Request ID: DTS23-111420

**Comment by susannegov** [comment]
# Create Work Order (Emergency Response) Form
- [ ] Location 
- [ ] Primary Street
- [ ] Cross Street
- [ ] Timestamp field from when the sign technician deployment

**Comment by ChristinaTremel** [comment]
## Statuses and Fields Associated
- Fields
   - `ID`
   - `Primary Street`
   - `Cross Street` 
   - `Area`
   - `Assigned To`
   - `Sign Deployed` (yes/no)
   - `Sign Deployed By`
   - `Sign Deployed Date`
   - `Count of Signs Deployed`
   - `Signals on Flash` (yes/no)
   - `Ready for Pick-Up` (yes/no)
   - `Sign Pick-Up By`
   - `Sign Pick-Up Date`
   - `Completed` (yes/no)

## Work Flow
- Sign Requested
   - Fields
      - `ID` (autogenerated in Knack)
      - `Primary Street`
      - `Cross Street`
      - `Area` (north, central, south)
      - Populate notes that say "Install temporary stop signs at all sides of the intersection"
       - `Assigned To` field (for Supervisors to fill out)
- Sign Deployed 
   - Edit Form
   - Fields
      - `Sign Deployed By` (autocapture)
      - `Sign Deployed Date` (autocapture)
      - `Count of Signs Deployed`
      - `Signals on Flash` (yes/no)
- Requested for Pick-Up
   - Button to `Ready for Pick-Up`
      - `Sign Pick-Up By`
      - `Sign Pick-Up Date`
- Complete

## Email Notifications:
- When request moves to `Sign Deployed` status, trigger email to MMC
- When request is `Sign Requested`, email Signs Supervisors

## Add Link to MMC Page
- Add button on the `Mobility Management Center` page

**Comment by ChristinaTremel** [comment]
- Created `emergency_sign_deployment` object
- Created fields:
   - [x] `Deployment ID` - auto increment 
   - [x] `Primary Street` - connected to street_names
   - [x] `Cross Street`  - connected to street_names
   - [x] `Area`
   - [x] `Status`
   - [x] `Assigned To`
   - [x] `Deployed By`
   - [x] `Deployed Date`
   - [x] `Number of set-ups`
   - [x] `Put signal into flash` (yes/no)
   - [x] `Ready for Pick-Up` (yes/no)
   - [x] `Completed Date`
   - [x] `Created By`
   - [x] `Created Date`
   - [x] `Modified By`
   - [x] `Modified Date`
   - [x] `Comments`
- Build page for `Emergency Sign Deployments` and table for requests - MMC Staff
   - Built form for requesting emergency temporary stop sign
- Build page for `Emergency Sign Deployments` and table for requests - Technicians
   - Built edit page for `Deploy Temporary Stop Sign(s)` 
- Set up trigger buttons for:
   - Request Pick-Up
   - Pick-Up?

**Comment by ChristinaTremel** [comment]
### Actions still needed:
- [ ] Display rules for statuses on the `Emergency Sign Deployment` page for Signs Supervisors and MMC Staff
- [ ] Update permissions to menu with `Emergency Sign Deployment` to include MMC Operators

**Comment by susannegov** [comment]
@ChristinaTremel Ready to demo

**Comment by susannegov** [comment]
On 12/18:
> note for knack form - adding # deployed baseline at 'source' location (N/S/C)
> could toggle by the N/S/C keyoff for signal location. maybe auto toggle if logged total #

- Added field `# of setups` to form
- Added display rule
![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/fcf319ff-ccf2-4633-aa5f-dae0513d4b60)

**Comment by susannegov** [comment]
From 12/18 meeting:
- Added Pivot Chart view of `emergency signs_deployment` to https://atd.knack.com/signs-markings#work-order-signs/emergency-sign-deployment
Table Rows : By Area choices
Pivot Calculation: The number of set-ups Sum
Column Summaries: Sum

**Comment by ChristinaTremel** [comment]
Meeting scheduled on 1/3/24 to review this with Allyson and Lauren.

**Comment by ChristinaTremel** [comment]
### Follow-Ups from meeting on 1/3
- [ ] Add `Signal ID` field to request form and table
- [ ] Update `Deployed Date` to include time
- [ ] Update the signal on flash field to say “Is the signal cabinet switch set to "FLASH?”
    - Note for when we train that when the sign is up, the signal must be on flash 
- [ ] When deployment is completed, add field to track:
    - `COMPLETED BY` and `COMPLETED DATE` and capture those when the field “Picked Up” is clicked
- [ ] When `COMPLETE’ is clicked, add pop-up to say something along the lines of “If you see something wrong with the signal, please contact the MMC at 512-000-0000”
- [ ] For the Emergency Response Reporting, filter it out for only active and filter out the “COMPLETED”

**Comment by ChristinaTremel** [comment]
Showed this feature to AMD during their Sprint Review! Also let SMD know about this feature during the sprint review and Kati is going to follow up with Lauren to schedule a training.
