### ISSUE TITLE
Adding new `Beacon Name` field to include Glance PID

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#14925]
> What application are you using?

AMD Data Tracker

> Describe the problem.

Adding a new asset for school zone beacons. Two main items to solve: 
- How to track history of changes to the new asset
- How to add a new Beacon ID/name to the SZF knack page and to work orders without breaking preexisting connections/links

> Describe the outcome you'd like to see when this feature is implemented.

The new naming convention for school zone beacons:

Clock ID (from existing Datatracker field) – Approximate Address – Direction – Power Type – Glance PID 

EX: 290 – 1800 Wheeless – WB – A – 36058

Would also like to see a log of changes made to the Glance PID field once it has been added as an asset in DT (or however we decide to add it into DT)

> Describe any workarounds you currently have in place or alternative solutions you've considered.

Currently our "work around" is that we are using the existing beacon ID to assign WOs. This will need to change once Paradigm (the distributor of Glance Beacons) sends us the new beacons.

> Is there anything else we should know?

I think if we could get these changes made to DT as soon as possible that would be great. We will install the new beacons at the beginning of 2024.

> Requested By
Samir S.

Request ID: DTS23-111460

**Comment by ChristinaTremel** [comment]
- [ ] Create new `Glance_PID` ID field for the MMC to use
- [ ] Add field to:
   - [Edit form ](https://atd.knack.com/amd#school-zone-beacons/school-zone-beacon-details/6169fb6eb1eda807217a6091/edit-school-zone-beacon/6169fb6eb1eda807217a6091/)
   - [New form](https://atd.knack.com/amd#locations/view-location-details/58164923407769ce2a14c33d/add-school-zone-beacon/58164923407769ce2a14c33d/)
      - Form exists within the Locations Details page
   - [School Zone Beacon Details page](https://atd.knack.com/amd#school-zone-beacons/school-zone-beacon-details/6169fb6eb1eda807217a6091/)
- Create `Beacon Name` field that is a calculated field including the following:
   - Clock ID – Approximate Address – Direction – Power Type – Glance PID
   - EX: 290 – 1800 Wheeless – WB – A – 36058
- [ ] Add `Beacon Name` field to:
   - [School Zone Beacon Details page](https://atd.knack.com/amd#school-zone-beacons/school-zone-beacon-details/6169fb6eb1eda807217a6091/)
   - [School Zone Beacons Table](https://atd.knack.com/amd#school-zone-beacons/)
   - [School Zone Beacons Table on the Locations Details Page](https://atd.knack.com/amd#locations/view-location-details/6176cf6ef904b807249332bf/)
   - Checking with Samir to confirm that we need to replace the current `School Beacon` field with new `Beacon Name` field on work orders or if we should wait until the Glance ID is populated by the MMC

**Comment by ChristinaTremel** [comment]
- Showed Samir the updates and he's happy with the new fields and the updates!
- Won't add this in the EDP/ODP until the Glance PID is populated.
