### ISSUE TITLE
Update "Journal Voucher" info in AMD Data Tracker - Warehouse Inventory- December 2023

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#14939]
- [x] Spreadsheet emailed from Finance staff month of: October-November; 10/13/2023 through 11/30/2023
- [x] Number of records being updated: 573
- [x] Format spreadsheet [(Review instructions)](https://atd-dts.gitbook.io/atd-knack-operations/warehouse-inventory-updating-journal-vouchers-jv-information)
- [x] Spot check Transaction IDs, no JV information before import: 33705/ 32484
- [x] Import records
- [x] Spot check Transaction IDs, has JV information after import
- [x] Email Finance staff that update task complete
