### ISSUE TITLE
Enhancement to simplify reimbursable table following check-in meeting

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#14979]
- Met with SMD to discuss simplifying the reimbursable tracking table 
- Took notes on this [miro board](https://miro.com/app/board/uXjVM6noGLU=/)
- High level feedback:
   - Will be hiding/showing certain columns depending on the Reimbursable status
   - Adding additional details to make Ramona's review process easier

**Comment by ChristinaTremel** [comment]
- Created pop up for simplify process of referencing time logs:
   - [x] Added 2 grids in the pop up to reference Signs Time Logs and Markings Time Logs
   - [x] Added these fields to time log table:
      - `ATD_WORK_LOG_ID`
      - `TECHNICIAN`
      - `Employee_Status`
      - `COUNT_TECHNICIAN`
      - `HOURS_WORKED`
      - `MINUTES_WORKS`
      - `SUM_TECH_HOURS`
      - `DATE_WORKED`
   - [x] Set rule to hide/show tables based on Work Type

**Comment by susannegov** [comment]
See https://github.com/cityofaustin/atd-data-tech/issues/14320#issuecomment-1936548791

Resolved connection issue, but need to update reimbursable status either by:
- only conditional rules
- only record rules
- one field of only conditional rules and another field of only record rules (so two fields)

**Comment by ChristinaTremel** [comment]
Updates on this issue has been completed!
