### ISSUE TITLE
Notes from meeting series `Discovery Workshop: Incorporating Sign Data into Work Orders`

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#15008]
## Current Process
- The Mapbox/Leaflet webmap used in the SMD Tracker allows a technician to add a location by panning on the map and dropping a point
- That point has a latitude/longitude (X,Y) location and it is then populated in a Knack form field in hidden to the user
- This process only allows technicians to add new locations
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/33ae556c-caff-45c9-b765-6fd523e6252d)

## Proposed Process
- Factors: we had a vendor called RAS do GIS data collection on all signs in the City of Austin, the Geo team has been QC'ing this dataset
- We are hoping utilize this sign data so that we can have users select existing locations and assets

## Goals of Discovery Workshop
- The goal is to look through our options of how to address incorporating the sign data and to work alongside the dev team to determine the best process.
   - 4/18 meeting: Prepare for the series with the dev team to start discussions of incorporating existing sign data into the signs work order process.
   - 5/3 meeting: Discuss preferred option (option 1) with the dev team to determine feasibility
   - 5/30 meeting: Check in on progress and feasibility updates (tentatively)

**Comment by amenity** [comment]
@dianamartin - please add context 🗺️ 🚏

**Comment by dianamartin** [comment]
# 12/19 
Current process

**Comment by dianamartin** [comment]
# 12/19
@ChristinaTremel @andrewshensky add anything else you think I missed on this. 

## Current Process
- The Mapbox/Leaflet webmap used in the SMD Tracker allows a technician to add a location by panning on the map and dropping a point
- That point has a latitude/longitude (X,Y) location and it is then populated in a Knack form field in hidden to the user
- This process only allows technicians to add new locations
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/33ae556c-caff-45c9-b765-6fd523e6252d)

## Proposed Process
- Factors: we had a vendor called RAS do GIS data collection on all signs in the City of Austin, the Geo team has been QC'ing this dataset
- We are hoping utilize this sign data so that we can have users select existing locations and assets

### Option 1:  Utilize the EXISTING mapbox map, add the GIS layers "signs locations/sign assets"
- [ ] EXISTING: an it still allow users to create new locations
- [ ] NEW: Can it allow users to click on a sign location/asset and capture the "ID" and put it into a field in Knack 

### Option 2: Create a NEW map (mapbox), add the GIS layers "signs locations/sign assets"
- [ ] NEW: Can it allow users to create new locations
- [ ] NEW: Can it allow users to click on a sign location/asset and capture the "ID" and put it into a field in Knack 

### Option 3: Create a new map (ArcGIS Online), add the GIS layers "signs locations/sign assets"
- [ ] NEW: Can it allow users to create new locations
- [ ] NEW: Can it allow users to click on a sign location/asset and capture the "ID" and put it into a field in Knack

**Comment by chiaberry** [comment]
link to the react app: https://github.com/cityofaustin/atd-knack-signs-markings

**Comment by chiaberry** [comment]
@frankhereford & @mddilley

**Comment by ChristinaTremel** [comment]
## 5/2 Notes from Discovery Workshop: Incorporating Sign Data into Work Orders
Attendees: Christina, Mike, Frank, Susanne, Cole, Cathy, Jordan, Kati, Andrew, Lauren, Daniel, Diana

- Proposed option 1 and walked Mike and Frank through what our preferred process will look like
- Mike and Frank both thought it seems like adding the sign locations to the mapbox map is definitely feasible and allowing technicians to select those and grab the location ID
- Talk through this solution with John because Mike is hearing similarities to the discussion around Moped
    - Christina will bring it to a dev sync
- For any maintenance right now it’s hard to capture at this point
- Sign Locations:
    - Pushed from GISMAINT -> AGOL right now
        - Frank would be more excited to pull the data from AGOL first
        - Pulled data into Moped the same way
        - Already have a Javascript to use to pull this data
            - Code pulls in from the Feature Service
    - Sign Assets do exist in Data Hub as an alternative option
- If we have an opinion on how we want the symbology of the locations to look like that would be helpful - Christina will talk through this with SMD
- Write up a punch list of the features we would like to see - can be found in #17314
- There’s tech debt on this issue so Mike is asking about the timeline
    - We make changes on the Knack side which is talking to the React application so there’s coordination there
    - Lauren said there is no specific timeline on this, we just want to keep the communication going on the expectations and what the dev team thinks diving into this
