### ISSUE TITLE
SMD Dashboard Management Transition

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#15032]
> What application are you using?

SMD Data Tracker 

> Describe the problem.

SMD Dashboard Management Transition - SMD would love to take over management of the SMD Power BI Dashboard to free up some DTS bandwidth. 
1) Finalize all performance measures in the Dashboard and ensure they are automatically updating regularly
2) Fully document each dashboard element to indicate where the data is coming from and any calculations/modifications being made to the data to arrive at the performance measure 

> How soon do you need this?

Flexible  — An extended timeline is OK

> Requested By
Kati C.

Request ID: DTS23-111605

**Comment by ChristinaTremel** [comment]
# Dashboard Management Transition Check-List
- [ ] Christina to create documentation for how performance measures are calculated

## Semantic Model Handover
- [ ] Identify who will support this semantic model & how
- [ ] Set up version control / source control
- [ ] Addressed BPA messages; documented ignored rules / objects
- [ ] Check if a field / data dictionary exists; if not, start one
- [ ] Test cases, queries, methods & results are documented
- [ ] Training & Adoption material / methods have been made / shared

## Report Handover
- [ ] Identify who will support the report & how
- [ ] Set up version control for the .pbix
- [ ] Training & Adoption material / methods have been made / shared
- [ ] Group visual (and re-name groups) in the selection pane
- [ ] Save custom themes, images and visual files

**Comment by ChristinaTremel** [comment]
The transition of the dashboard to Jordan and walk through of the documentation created was completed on 5/2. Closing this issue!
