### ISSUE TITLE
IT Support: Rename `Solar` option to `DC` in the "Power Source" drop down for School Beacons

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#15098]
Samir asked us to rename a drop down option on the **Power Source** field for School Beacons. The drop down is currently AC, SOLAR, and OH.
<img src="https://github.com/cityofaustin/atd-data-tech/assets/61209591/76d5cf2b-c007-4aee-b414-3d9638b93328" width="500">

- [x] They would like to rename `SOLAR` to `DC` and update all the school beacon records that are currently `SOLAR`

**Comment by susannegov** [comment]
- [x] `school_beacon` the field `Power Source` added `DC` option
- [ ] Rename all `SOLAR` records to `DC`
- [ ] Check if any rules in `Power Source` field in edit/add form
- [ ] Remove `SOLAR` option

**Comment by susannegov** [comment]
@ChristinaTremel ready for review/QA

**Comment by ChristinaTremel** [comment]
Messaged Samir on 1/12 letting him know that this was completed!
