### ISSUE TITLE
Viewing `Contractor Work Orders` needing inspection

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#15123]
> What application are you using?

SMD Data Tracker 

> Describe the problem.

Needing a way to view all contractor work orders that need inspection. Thinking we'll need a scoping meeting to define needs and chat about options (new inspector view? just another status tab? report enhancement?)

There are 2 scenarios that would put a contract work order into a needs inspection category 1) all work is completed on the work order and contractor has submitted for a final review (status is FINAL REVIEW at this point), 2) contractor performs work on a work order but it is not complete so they submit for a mid project review (status is ISSUED, In Progress at this point) and an additional check would need to occur to determine if the date of the latest inspection on the work order is before or after the date of the latest mid project inspection.

> Describe the outcome you'd like to see when this feature is implemented.

Quick an accessible (across multiple staff members) way to view what contractor work orders currently need an inspection. 

> Describe any workarounds you currently have in place or alternative solutions you've considered.

Joe Mike (our inspector) gets an email when inspection requests are submitted by the contractor but this doesn't allow for other staff to fill in for him if he is out. Also doesn't allow for a quick way to see a full list of what needs inspection. 

> Requested By
Kati C.

Request ID: DTS24-111765

**Comment by ChristinaTremel** [comment]
### Christina / Karo's proposed 
- Organize by `Reference ID`
- Show a table of Inspection records with link 
- For mid-project inspections, a comment is added saying `Mid-project inspection request submitted`
   - To make these viewable to JM, we would need to insert a record a record into the `inspection log date` object.

### Kati's proposed solution:
- Could we create a view of Contractor Work Orders where a `work log record` date is after the last `inspection log date`? This would be a little cleaner to see.

### Next Steps
- We will test out Kati's proposed solution first to see if we can get this to show the work orders needing inspections.

**Comment by dianamartin** [comment]
# 1/8/2024
Talking about spike/build steps with Karo, Susanne

## Quick Flow Summary
Contractor WO created (parent)
Issued to contractor
Contractor requests mid-inspection (created a comment automatically)
Inspector does inspection (creates an inspection log, w/ status)

## New Enhancement
On Contractor WO (parent)
- [ ] Create New Field "DATE 1": LAST INSPECTION DATE <> `connection from log`
  - [ ] Add record rule to set Date and update Contractor WO
- [ ] Created New Field "DATE 2": REQUESTED DATE <> `connection from comment`
  - [ ] Add record rule to set Date and update Contractor WO
- [ ] Created New Field: "CALC Date" (Equation: `DATE 2-DATE 1= NUM OF DAYS APART`)

Think about text formula field to capture Status on Contractor WO (parent). If Calc Date is a certain number, then a status could be on the Contractor WO (parent) indicated an inspection is needed. 
   or
 - Inspection Record - child record date (STATUS)<>rolled up to WO

**Comment by ChristinaTremel** [comment]
- Need to try option 2 in test

**Comment by ChristinaTremel** [comment]
- Completed this request in #25761 ✨
