### ISSUE TITLE
Refinements after RPP Technical Review

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#1512]
@moorerst The work flow scenario is something we should discuss in our Sprint Review meeting
WORKFLOW SCENARIOS 
Decals and vehicles (Number of decals should match the number of vehicles)
`What if you add decal at review page ?`
- Currently there is no validation on vehicle numbers, not requiring you to add another vehicle
- Currently there is no add vehicle button

### Tasks for Diana
CHECK PAGE RULES
Require Documents after submission, `Continue` button still shows. 
- [x]  Fix this
Vehicle banner still shows along with "This application has already been submitted" 
- [x] Remove banner

BUG/CODE ISSUE
- [x] Removed lines 159-160
- [x] Reconfigure the Page menu to have `Home` button
- [x] Remove all Home button JS

BACKLOG ISSUES _(Maybe create these)_
- [ ] Edit Button for bread crumb trail 
- [ ] Create edit pages for all application pages (depends on outcome of workflow discussion)
- [x] Have `Continue` button disappear on the Required Documents page (Dev - issue)
