### ISSUE TITLE
Update "Journal Voucher" info in AMD Data Tracker - Warehouse Inventory- December 2023

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#15138]
- [x] Spreadsheet emailed from Finance staff month of: December 2023; 12/1/23-12/22/23 transaction dates
- [x] Number of records being updated: 447
- [x] Format spreadsheet [(Review instructions)](https://atd-dts.gitbook.io/atd-knack-operations/warehouse-inventory-updating-journal-vouchers-jv-information)
- [x] Spot check Transaction IDs, no JV information before import: 34444 ✅  33742 ✅ 
- [x] Import records
- [x] Spot check Transaction IDs, has JV information after import: 34444 ✅  33742 ✅ 
- [x] Email Finance staff that update task complete
