### ISSUE TITLE
ATD AMANDA Backlog — Unisys

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#1515]
Work on the [ATD AMANDA Backlog](https://github.com/cityofaustin/atd-data-tech/issues/432) delivered by Unisys. 

- [x] Sync w/ Stacey Wuest regarding proper process for this engagement 
- [x] Sync w/ Peggy from finance 
- [x] Add this to CMGB portfolio
- [x] Send documentation to Unisys; requesting estimate
- [x] Sync w/ Peggy on estimate; get finance approval for estimate & work
- [x] Request spending authority from CMGB

*Migrated from [atd-amanda #11](https://github.com/cityofaustin/atd-amanda/issues/11)*

**Comment by atdservicebot** [comment]
*From johnclary on 2019-06-12*:

@TracyLinder would you update Ryan W with the latest on this? He didn't seem to know this was in progress.

**Comment by atdservicebot** [comment]
*From TracyLinder on 2019-06-12*:

@johnclary I gave him an update at the audit meeting earlier today.

**Comment by atdservicebot** [comment]
*From johnclary on 2019-07-20*:

@TracyLinder pinging you to make sure this is moving forward. do you need help?

**Comment by amenity** [comment]
Per conversations with Ram, Unisys will not be working on our backlog for the time being.
