### ISSUE TITLE
Please make Utility Cuts a "Requester", as opposed to a sub-type.

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#15171]
> What application are you using?

SMD Data Tracker 

> Describe the problem.

Please make Utility Cuts a "Requester", as opposed to a sub-type. This will enable us to differentiate the work orders from one another. We are currently going to have it noted in the Instructions section. This enhancement is important to the team as we are called upon to report to upper management regarding whereabouts. Further explanation will be provided at our meeting with Christina T. on 1/12.

> Describe the outcome you'd like to see when this feature is implemented.

Clear differentiation between utility cuts and whereabouts.

> Describe any workarounds you currently have in place or alternative solutions you've considered.

We are currently going to have it noted in the Instructions section, which is time-consuming.

> Requested By
Cathy K.

Request ID: DTS24-111840

**Comment by ChristinaTremel** [comment]
Meeting with Cathy, Jenniffer, and Esteban on 1/12/24 to decide how to address this request.

**Comment by ChristinaTremel** [comment]
## Meeting 1/12
- **Attendees**: Esteban, Cathy, Jenniffer, Christina
- There's been confusion with including Utility Cuts with the `SBO / WHEREABOUTS` requester
- Utility Cuts are not considered Whereabouts
- Executive team is looking at SBO / Whereabouts and it's not clear when you look at those work orders what is a whereabout and what is a utility cut
- Also would benefit the Supervisors with scheduling
- ![image](https://github.com/cityofaustin/atd-data-tech/assets/61209591/df67eb45-1d88-4298-9a4f-803c200db117)

### Asks: 
- Create new requester `SBO / UTILITY AND CONCRETE REPAIR`
- Update work orders with Subtype = `Utility Cut`, `Pothole Repair` and `Concrete Work` to the new requester type `SBO / UTILITY AND CONCRETE REPAIR`

**Comment by susannegov** [comment]
# 2/8
- [x] Added in `REQUESTER` multi-choice field: `SBO / UTILITY AND CONCRETE REPAIR`
- [ ]

**Comment by susannegov** [comment]
# 2/14
## Display Rules
- [x] Update the blank requester Rule 3,10: `REQUESTER is not SIGNS AND MARKINGS - MAINTENANCE PLAN`
- [x] Duplicate Rule 11. New Rule 12 Replace When `REQUESTER is SBO/ UTILITY AND CONCRETE REPAIR`
- [x] Modified Rule 13. Added When `REQUESTER is not SBO/ UTILITY AND CONCRETE REPAIR`
- [ ] Duplicate Rule 15-18

**Comment by susannegov** [comment]
Ready for Review/QA

**Comment by ChristinaTremel** [comment]
This was completed and we let SMD know during the last sprint!
