### ISSUE TITLE
Add `Dark Signal Override` field to the Signal Socrata dataset

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#15211]
## Build Notes - Apps
- [x] Add new `Dark Signal` field to `signals` API view 
- [x] Add new field to ODP [Traffic Signals and Pedestrian Signals](https://datahub.austintexas.gov/Transportation-and-Mobility/Traffic-Signals-and-Pedestrian-Signals/p53x-x73x/about_data) dataset
   - Currently only scheduled for daily refreshes, but we'll need to update frequency to every 5 minutes

## Build Notes - Devs
- [x] Metadata refresh and update refresh frequency to every 5 minutes for the [Traffic Signals and Pedestrian Signals](https://datahub.austintexas.gov/Transportation-and-Mobility/Traffic-Signals-and-Pedestrian-Signals/p53x-x73x/about_data) Socrata dataset

_Originally posted by @ChristinaTremel in https://github.com/cityofaustin/atd-data-tech/issues/14912#issuecomment-1885741266_

**Comment by ChristinaTremel** [comment]
Scheduled time to meet with Karo and Chia on 1/11 to complete this.

**Comment by ChristinaTremel** [comment]
- Karo, Chia and I were able to meet about this on 1/11 and add the `Dark Signal` field to the Socrata dataset. 
- Chia had to do some troubleshooting, but was able to update the frequency to refresh every 5 minutes. 🪩
