### ISSUE TITLE
Build `Manage Dark Signals` feature in AMD Data Tracker

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#15213]
### Build Notes for Apps
- Add `DARK_SIGNAL_OVERRIDE` field to `signals` object
- Create page for the MMC to easily flag dark signals in emergency situations
   - ![image](https://github.com/cityofaustin/atd-data-tech/assets/61209591/901fdf23-8478-4a86-951a-2bb42d3b3fd0)

**Comment by ChristinaTremel** [comment]
Notes from Work Session with Diana:
- [Original Comment](https://github.com/cityofaustin/atd-data-tech/issues/14912#issuecomment-1877825621)

# 1/4/24
### Build Notes - Apps
- [x] Added `DARK SIGNAL OVERRIDE` field to `signals` object
- [x] Updated `signals` records to `DARK SIGNAL OVERRIDE` is "No"
- [x] Create new page `Dark Signal Management`
   - [x] Copied `Signals` table and kept only necessary fields. Also added  `DARK SIGNAL OVERRIDE` field to the table and highlighted it yellow
  - [x] Add Record Rule to update `Modified Date` and `Modified By` when field has changed
- [x] Created button on MMC page 
   ![image](https://github.com/cityofaustin/atd-data-tech/assets/61209591/5156e7da-7c9c-455d-9723-befc58b274e4)

**Comment by ChristinaTremel** [comment]
This was completed on 1/4.
