### ISSUE TITLE
Add new "CABINET_ID" field on "signals_cabinet" object table

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#15376]
Ally R. 
AMD

Synced with Allyson, she said there is a desire to have the Cabinet ID match the Signal ID. 

Currently, the `Cabinet ID` does not match the `Signal ID`
Proposing, to make the `Cabinet ID` more of an auto-populated field. Create a new field to reflect the "Signal ID" on the cabinet table.

**Comment by dianamartin** [comment]
# 1/23/24
- [x] Added a new field `CABINET_ID`, set up conditional rule
- [x] When "signals" is not blank, set field value to "Signal IDs"
- [x] Added that new field to the "Signal Cabinets" page

## Before
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/bc6669ea-9707-4ebc-b47b-59883f8f0300)

## After
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/34a9be49-7d11-40cc-a271-fcd9cebbf396)

I asked Allyson to submit a new DTS SR for the updated changes to be on ODP and ArcGIS Online
