### ISSUE TITLE
Add Dash items to DTS Portal Knack app

### ISSUE THREAD

**Issue by katelunceford** [cityofaustin/atd-data-tech#15433]
[DTS Portal Knack app](https://atd.knack.com/test--07-sep-2023--data-and-technology-services-portal#tpw-data-visualizations/edit-visualization/65d64c171e02e9002673b6d3/)

- [x] [#15699](https://github.com/cityofaustin/atd-data-tech/issues/15699) Source TPW reports, data visualizations (including maps), and datasets - what's already out there and is authoritative
- [x] [#15701](https://github.com/cityofaustin/atd-data-tech/issues/15701) Write title & explainer text & source image for each Dash item
- [x] [#15940](https://github.com/cityofaustin/atd-data-tech/issues/15940) Source, edit, & upload refined image for each Dash item to DTS portal Knack app
- [ ] [#16161](https://github.com/cityofaustin/atd-data-tech/issues/16161) Add more Dash items to DTS Portal Knack app

For each item, we must enter/upload its:
- URL
- Title
- Description
- Thumbnail image
- Thumbnail image alt text
- Level of accessibility (if it is not publicly accessible, a lock icon will appear after the title)

**Comment by rebekkabry** [comment]
Met with @katelunceford  last week to discuss resources that could be used to support the DASH 1st MVP. Details of meeting discussion and resources can be found at #15460. 

Topics Included: 
- What portions of Ecosystem Assets could be used for DASH MVP? Details and PPT provided 
- DASH MVP Visual Recommendations (includes filtering considerations) 
- List of Possible Dashboards/Reports/Maps that could be used for MVP. Pending criteria to provide specific resources.

**Comment by katelunceford** [comment]
We've uploaded 6 items so far. I will add the rest from Charlie's [list](https://docs.google.com/spreadsheets/d/1mXfizj6g00fMhNZkd7wDmOFH1EJEYOW5pCJb6yuvo_M/edit#gid=0) and we will continue to upload more as they're identified.

**Comment by katelunceford** [comment]
**Guidelines for the title**
Keep it very short; use title case

**Guidelines for the description**
Use this loose formula with a data and reporting perspective:
- This [app/platform type] [dashboard, report, map, or dataset] [does x, y, and z]

**Guidelines for the thumbnail image**
Follow [these guidelines](https://atd-dts.gitbook.io/wiki/product-ops/index-issue-specifications#index-issue-images) but with a 16:9 aspect ratio. Also:
- For this landing page, images could help tell the story better than a screenshot of a dashboard/data viz. Find something that relates to the content, such as
   - TPW staff doing the work
   - Residents the work impacts
   - Assets or equipment in the community
   - Newly implemented project/program/improvement
   - Austin or one of its many zones/neighborhoods/pockets
- Keep in mind that not all images make great thumbnails. Here are a few best practices to help choose:
   - Simple images are easier to view as a thumbnail, so find an image with a distinct focal point and without too much going on in the background
   - Clear/sharp images are easier to view as a thumbnail, so fine an image that's not blurry (unless the blur is intentional/stylized)
   - Try 2-3 different options to see which one works best

**Comment by katelunceford** [comment]
Closing this out - work will continue in #16161
