### ISSUE TITLE
[Tech Debt] Archive the `signals_preventative_maintenance_historical` object in AMD Data Tracker

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#15448]
- Archive the `signals_preventative_maintenance_historical` object in Knack
- We migrated the historical preventative maintenance records to the `work_orders_preventative_maintenance` object in Knack and can now archive the historical records

_Originally posted by @ChristinaTremel in https://github.com/cityofaustin/atd-data-tech/issues/13517#issuecomment-1915244129_

**Comment by dianamartin** [comment]
# 6/12/25
- [x] Created archive folder on G:// drive - `ARCHIVE_Object_Table` 
- [x] Export `signals_preventative_maintenance_HISTORICAL` and save it on the G drive - `5020 records`
- [x] Renamed csv to `20250612_signals_preventative_maintenance_historical_5020_records`
- [x] Moved csv to `ARCHIVE_Object_Table` 
- [ ] Delete object - `signals_preventative_maintenance_HISTORICAL`
