### ISSUE TITLE
Remove duplicate Data Tracker project records and finish Moped project sync

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-data-tech#15550]
When deploying the Data Tracker sync ETL, I switched on the DAG just before 5pm on 2/01/24. Since the DAG runs hourly, the 5pm run kicked off shortly after. Both DAG runs queried the production Moped DB project table and found the same projects to sync to the production Knack Data Tracker project table. This created two Knack projects table rows for some Moped project IDs. There should only be one row in the Knack projects table per Moped project.

Example:
- In the Moped DB `moped_project` table, `project_id` 1002 has a `knack_project_id` of `65bc24f29db0160028ce6e53`
- In the Knack Data Tracker `projects` table, two rows are associated with Moped `project_id` 1002 - `65bc24f29db0160028ce6e53` AND `65bc24d70ffd690028c57bdc`.

Duplicate rows in Knack Data Tracker `projects` table:
<img width="463" alt="Screenshot 2024-02-02 at 11 26 03 AM" src="https://github.com/cityofaustin/atd-data-tech/assets/37249039/d1344e2f-c8c4-4058-8c20-84a1a6f6fdd2">

To fix:
- [x] Write a script to list all Knack IDs stored in the `knack_project_id` columns of all Moped `moped_project` table rows
- [x] Collect a list of Knack record IDs from the `projects` table that are not in this list. These will be possible deletions.
   - [x] Check this list to make sure that none of these records have work orders associated with them
   - [x] If any of these records have connections, remove them from the possible deletions list and keep their IDs to look at later
- [x] Delete the Knack records left in the delete list
- [x] This time, manually trigger the first production Data Tracker sync **locally with a longer timeout AND a date flag that will cover previous updates that the normal schedule would not cover**. This will avoid the issue of the scheduled runs intersecting and capture updates to previously synced project.
- [x] Now, toggle on the Data Tracker sync DAG in the production Airflow dashboard which will sync and future creates or updates between Moped and Data Tracker.

See https://austininnovation.slack.com/archives/CNUEPKLB1/p1706831106503149 for more details.

**Comment by mddilley** [comment]
I wrote up a script to do everything above EXCEPT any deletes. I ran the script with production Moped data in the local stack and checked against production Data Tracker and found 2093 `projects` records that are duplicates (no Moped project record associated with the Knack ID) and 0 projects connected to `work_order_signals` records.

Going to wrap up on Monday morning and loop in Apps before proceeding with any deletes.

**Comment by johnclary** [comment]
sounds great—thanks @mddilley!

**Comment by mddilley** [comment]
[Slack thread](https://austininnovation.slack.com/archives/C026ZRP1TH8/p1707152724689649) with more info but read-only test and spot check is ✅

The script is running but takes a while. I'll keep it going tonight and then take care of the ETL startup steps later tonight or in the morning.

**Comment by mddilley** [comment]
@johnclary The three crashes in the last comment are blocking a run that would capture all previous updates. The script breaks when it finds a Knack id in the Moped project table that doesn't match a row in Data Trackers projects. I see a few paths forward:
- remove the values in the `knack_project_id` of those 2 projects and let the ETL sync them
- add more code to the ETL to not break when Moped stores non-existent Knack records
- do both?

What do you think? I can turn on the ETL either way, but the Data Tracker projects table won't be fully up to date until we resolve this.

**Comment by johnclary** [comment]
If it sounds ok to you, I think we should clear out the `knack_project_id` and let those projects fall back into sync.

I'm glad you mentioned that these were test projects. I did not at all consider that we are going to need to sync project status to the Data tracker as well, so that we can filter out canceled projects within the Data Tracker. I may have a backlog issue somewhere related to that—that's for sure outside the scope of this though.

Thanks for working on this!

**Comment by mddilley** [comment]
Clearing those `knack_project_id` sounds great to me and very doable - thanks for the input 🙏 Really appreciate it because I was feeling stuck on getting this completed after all the hiccups 🫠. I'll get this all tied up so we can have the ETL ready for that next issue. 💪 🚀

**Comment by mddilley** [comment]
Last update, Airflow has executed 3 successes in a row. Last success date is working as expected and one update has been captured so far. Closing this out and will keep monitoring. 👀

```
[2024-02-07, 18:00:15 CST] {docker.py:391} INFO - moped-knack-sync.INFO: Starting sync. Creating Knack records for Moped projects not synced and updating synced Knack records with latest project data from Moped since 2024-02-07T23:00:00.374342+00:00.
[2024-02-07, 18:00:15 CST] {docker.py:391} INFO - moped-knack-sync.INFO: Found 0 unsynced projects
[2024-02-07, 18:00:15 CST] {docker.py:391} INFO - moped-knack-sync.INFO: Found 1 synced projects
[2024-02-07, 18:00:17 CST] {docker.py:391} INFO - moped-knack-sync.INFO: Done syncing.
[2024-02-07, 18:00:17 CST] {docker.py:391} INFO - moped-knack-sync.INFO: Created 0 new Knack records
 moped-knack-sync.INFO: Updated 1 existing Knack records
```
