### ISSUE TITLE
[DOCUMENTATION] Configure New AMD Asset in Data Tracker

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#15569]
Developed template documentation for the steps that need to be taken when creating a new asset in AMD Data Tracker. 

[Link to Gitbook Documentation](https://atd-dts.gitbook.io/atd-knack-operations/data-tracker/builder-notes/configure-new-amd-asset-in-data-tracker)

**Comment by dianamartin** [comment]
IN AMD Data Tracker - TEST
# 1. Created NEW asset (new object table)

- [ ] Created New Asset object
- [ ] Created fields needed to test connection
- ATD_LOCATION_ID
- New Asset_NAME
- New_Asset_ID

# 2. Connect asset to objects
### `tmc_issues` object
- [ ] Added connection field to New_Asset
- [ ] Add "New_Asset" to ASSET_TYPE field
- [ ] Update validation rule to ASSET_TYPE field
- ASSET_TYPE is New_Asset and New_Asset is blank
- Message shows "Message type does not match asset selected"

tmc_activities object
Added connection field to New_Asset
Add "New_Asset" to ASSET_TYPE field
Update validation rule to ASSET_TYPE field
ASSET_TYPE is New_Asset and New_Asset is blank
Message shows "Message type does not match asset selected"
work_order_signals object
Add "hub cabinet" to ASSET_TYPE field
Added connection field to New_Asset
Add validation to new field
New_Asset is not blank
Message shows "You must select a hub cabinet when asset type is hub cabinet."
Added New_Asset_ID field to work_order_signals object
Update validation rule on ASSET_ID where ASSET_TYPE is "hub cabinet" set to a field object New_Asset_ID
3. MMC - Form, Display, and Record Rules
MMC Details Display & Record Rule Updates
Added "New_Asset" to the MMC Details page
FORM: "Assign Asset - API | Systems Admin ONLY" form (hidden)
Add "New_Asset" field to form
DISPLAY RULE
Create new rule for ASSET_TYPE is "New_Asset"
show - New_Asset
hide - signal
hide - school beacon zone
hide - dsdd
hide - dm
hide - hazard flasher
hide - signal request
hide - school beacon
All ASSET_TYPE not "New_Asset"
hide - New_Asset
RECORD RULE
Updated record rule 2 for Identify Asset
New_Asset to field New_Asset
Update connected records - tmc_issue (tmc_issue>tmc_issue)
New_Asset is not blank
location to a connected value (New_Asset>ATD LOCATION ID)
FORM: "Add mmc activity" form - START HERE
Add "New_Asset" field to form
DISPLAY RULE
Create new rule for ASSET_TYPE is "New_Asset"
show - New_Asset
hide - signal
hide - school beacon zone
hide - dsdd
hide - dm
hide - hazard flasher
hide - signal request
hide - school beacon
All ASSET_TYPE not "New_Asset"
hide - New_Asset
RECORD RULE
Updated record rule 2 for Identify Asset
Add additional New_Asset to field New_Asset
Update connected records - tmc_issue (tmc_issue > tmc_issue)
New_Asset is not blank
location to a connected value (New_Asset>ATD LOCATION ID)
FORM: "add_work_orders" (embedded form)
Record Rule
Add to Record Rule 1
New_Asset to a connected value (tmc_issues > New_Asset)
4. Work Orders - Form, Display, and Record Rules
FORM: New Work Orders | Trouble Call
Add New_Asset to the form
DISPLAY RULE
Asset Type is "New_Asset" - Show/Hide
RECORD RULE
Asset Type is "New_Asset"
ATD LOCATION ID - connected value - New_Asset>ATD LOCATION ID
FORM: New Work Orders | Schedule Work
Add New_Asset to the form
DISPLAY RULE
Asset Type is "New_Asset" - Show/Hide
RECORD RULE
Asset Type is "New_Asset"
ATD LOCATION ID - connected value - New_Asset>ATD LOCATION ID
FORM: My Work Orders - "Edit Work Order" button
Add New_Asset to the form
DISPLAY RULE
Asset Type is "New_Asset" - Show/Hide
RECORD RULE
Asset Type is "New_Asset"
ATD LOCATION ID - connected value - New_Asset>ATD LOCATION ID
Work Orders (Signals) - "Edit Work Order" button
Add New_Asset to the form
DISPLAY RULE
Asset Type is "New_Asset" - Show/Hide
RECORD RULE
Asset Type is "New_Asset"
ATD LOCATION ID - connected value - New_Asset>ATD LOCATION ID

Update pages/forms/rules for AMD Communications only if it affects the AMD Communications group (ex. hub cabinet)
Work Orders (Communications) - "Edit Work Order" button
Add New_Asset to the form
Added "ASSET_TYPE" to the form
DISPLAY RULE
ASSET_TYPE is "New_Asset" - show/hide - New_Asset
ASSET_TYPE is "signal" - show/hide - signal
RECORD RULE
Signal (split record rule 1 so this is it's own rule)
When Asset Type is "Signal"
ATD Location ID - connected value - signal>ATD LOCATION ID
New_Asset
Asset Type is "New_Asset"
ATD LOCATION ID - connected value - New_Asset>ATD LOCATION ID
5. Details Pages
PAGE: My Work Orders Details
Add "New_Asset" to Related Assets section
PAGE: Work Orders - Technician Details
Add "New_Asset" to Related Assets section

Update pages/forms/rules for AMD Communications only if it affects the AMD Communications group (ex. hub cabinet)
PAGE: Work Orders (Communications) Details
Add "New_Asset" below Signal ID
