### ISSUE TITLE
Preliminary research

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#156]
### Candidates
[Wasp Inventory Control](https://www.waspbarcode.com/inventory-control)
- [x] Form submitted
- [x] Phone call #173 
- [x] Evaluate trial account #174 

[Finale Inventory](https://www.finaleinventory.com/)
- [x] Email inquiry with basic requirements & demo request
- [x] [Talk with sales rep](https://github.com/cityofaustin/atd-data-tech/issues/156#issuecomment-499175173) 
- [x] Evaluate trial account #176

[Asset Panda](https://www.assetpanda.com/asset-tracking-government-2/)
- [x] Form submitted
- [x] [Talk with sales rep](https://github.com/cityofaustin/atd-data-tech/issues/156#issuecomment-499284953)
- [x] Evaluate trial account #178 

[Dude Solutions](https://www.dudesolutions.com/solutions/work-asset)
- [x] Call with sales rep
- [x] Demo #233 

------
### Ruled out
[Cin7](https://www.cin7.com/) — Expensive, too tailored to ecommerce
[SKU Vault](https://www.skuvault.com/) — Expensive, too tailored to ecommerce
[Infoplus](https://www.infopluscommerce.com/) — Expensive, too tailored to ecommerce
[Grainger](https://www.grainger.com/content/keepstock) — Only tracks Grainger products

**Comment by amenity** [comment]
| Activity | Need | Type | Technician | Engineer | Materials Manager | Finance Staff | [Wasp Inventory Control](https://www.waspbarcode.com/inventory-control) | [Cin7](https://www.cin7.com/) | [Finale Inventory](https://www.finaleinventory.com/) | [SKU Vault](https://www.skuvault.com/) | [Asset Panda](https://www.assetpanda.com/asset-tracking-government-2/) | [Infoplus](https://www.infopluscommerce.com/) |
| Submit an inventory request online | Must have | Order management | x | x |  |  |  |  |  |  |  |  |
| Submit an inventory request from work order | Should have | Order management | x |  |  |  |  |  |  |  |  |  |
| Submit an inventory request in-person | Must have | Order management | x |  |  |  |  |  |  |  |  |  |
| Return an inventory item to the warehouse | Must have | Order management | x |  | x |  |  |  |  |  |  |  |
| Fulfill an inventory request | Must have | Order management |  |  | x |  |  |  |  |  |  |  |
| Search inventory requests by status, requester, item, date | Should have | Order management | x | x | x | x |  |  |  |  |  |  |
| Issue inventory to a staging area | Could have | Order management |  |  | x |  |  |  |  |  |  |  |
| Track person to whom an item is issued | Must have | Order management |  |  | x |  |  |  |  |  |  |  |
| Bill inventory items to one or more task orders | Must have | Order management |  |  |  |  |  |  |  |  |  |  |
| Search inventory orders by status, requester, item, date | Should have | Purchasing/Receiving |  |  | x | x |  |  |  |  |  |  |
| Return an inventory item to a vendor | Could have | Purchasing/Receiving |  |  | x | x |  |  |  |  |  |  |
| Create a new inventory item | Should have | Purchasing/Receiving |  |  | x |  |  |  |  |  |  |  |
| Receive an inventory shipment | Must have | Purchasing/Receiving |  |  | x |  |  |  |  |  |  |  |
| Track shipment receipt date | Should have | Purchasing/Receiving |  |  | x |  |  |  |  |  |  |  |
| Tracking warranties | Should have | Purchasing/Receiving |  |  | x |  |  |  |  |  |  |  |
| Restock Inventory Items | Must have | Purchasing/Receiving |  |  | x |  |  |  |  |  |  |  |
| Create a purchase request | Could have | Purchasing/Receiving |  |  | x | x |  |  |  |  |  |  |
| Create/Print barcode labels | Must have | Purchasing/Receiving |  |  | x |  |  |  |  |  |  |  |
| Alert staff when stock levels are low | Should have | Purchasing/Receiving | x | x | x | x |  |  |  |  |  |  |
| Set stock level thresholds for replenishment | Should have | Purchasing/Receiving |  |  | x |  |  |  |  |  |  |  |
| Modifiy item unit cost | Should have | Purchasing/Receiving |  |  | x |  |  |  |  |  |  |  |
| Tracking item unit costs over time | Could have | Purchasing/Receiving |  |  | x |  |  |  |  |  |  |  |
| Manually adjust inventory levels to reconcile discrepancies | Must have | Purchasing/Receiving |  |  |  | x |  |  |  |  |  |  |
| Pulling inventory levels from AIMS | Should have | Purchasing/Receiving |  |  | x | x |  |  |  |  |  |  |
| Assign inventory item to warehouse location (shelf, bay, etc) | Should have | Purchasing/Receiving |  |  | x |  |  |  |  |  |  |  |
| Manage multiple warehouse locations | Should have | Purchasing/Receiving |  |  | x |  |  |  |  |  |  |  |
| Export inventory requests to spreadsheet | Must have | Reporting and admin | x | x | x | x |  |  |  |  |  |  |
| Create, modify, and remove users | Must have | Reporting and admin |  |  | x |  |  |  |  |  |  |  |
| Generate report of inventory levels | Must have | Reporting and admin | x | x | x | x |  |  |  |  |  |  |
| User roles and permissions - technicians can sumbit only | Must have | Reporting and admin | x | x | x | x |  |  |  |  |  |  |
| Scan barcode | Must have |  | x |  | x |  |  |  |  |  |  |  |
| Track items by serial numbers | Could have |  |  |  |  |  |  |  |  |  |  |  |
| Tracking where an item was installed | Could have |  |  |  |  |  |  |  |  |  |  |  |
| Ability to set required field | Could have |  |  |  |  |  |  |  |  |  |  |  |
| Image catalog | Could have |  |  |  |  |  |  |  |  |  |  |  |
| RESTful API --- create inventory requests | Must have | Non-functional |  |  |  |  |  |  |  |  |  |  |
| Ability to access application on mobile device | Must have | Non-functional | x |  |  |  |  |  |  |  |  |  |
| Database backup and recovery | Must have | Non-functional |  |  |  |  |  |  |  |  |  |  |

**Comment by amenity** [comment]
Wasp InventoryCloud Call 6/4

John, Amenity, Diana

### Resources
-   [Wasp product overview](https://www.waspbarcode.com/inventory-control)
-   [Pricing](https://www.waspbarcode.com/inventory-control/pricing) 
-   [Vendor site ](https://www.barcodeshack.com/index.php?p=home)(?) - purchase hardware and licenses
-   [AMD/DTS comparison matrix](https://docs.google.com/spreadsheets/d/1r2l_KFgjygCCp1E4oaBa5lyK2QzkVcP5qCu2u85UwcY/edit#gid=2118741241)

### InventoryCloud features

-   RESTful APIs
-   SSO
-   Stores "What, where, from whom to you buy it"
-   Manufacturing - putting together multiple parts into an item
-   Notifications of low stock
-   Receive against a PO, history of all transactions
-   Create purchase orders
-   Pick order - e.g. group of items to a customer
-   Bulk import - can import with spreadsheet or API
-   Custom categories
-   Reporting
-   Check in and check out:
  -   Do not have UI for person to request materials/borrow items; in the product backlog
  -   Can set due date, see who something is checked out to
  -   Get alerted when someone is delinquent
-   Can add unlimited custom fields to items
-   Print receipt

@dianamartin - please add anything I missed! 🙏

**Comment by amenity** [comment]
Finale Inventory call 6/5

_Amenity --- Chinh/Finale_

### Resources
-   [Product overview](https://www.finaleinventory.com/cloud-inventory-management-2)
-   [Pricing](https://www.finaleinventory.com/pricing-signup) 

### Notes
Finale Inventory

- No checkout system; would have a warehouse that represents the field or each of the workgroups

- [API](https://support.finaleinventory.com/hc/en-us/categories/115001160947-API-Documentation)
- [Pricing](https://www.finaleinventory.com/pricing-signup) 
  - Inventory and order management functionality the same accross all plans
  - Platinum ($649/mo 😬) is the one where you get the API and barcoding
  - All fees include training and consulting
  - No set-up fees
- [Barcoding](https://www.finaleinventory.com/feature-turnkey-mobile-barcode-scanner-solution)
  - Windows scanner or Android app
- 14-day trial
  - Training support available during this time
  - [Help docs](https://support.finaleinventory.com/hc/en-us)

**Comment by amenity** [comment]
Asset Panda call 6/5
_Amenity --- Eric/Asset Panda_

### Resources
- [Product overview](https://www.assetpanda.com/asset-tracking-government-2/)
- [Prerecorded demonstration video](https://www.assetpanda.com/ap-demo-video/)

### Notes
Basics
- Cloud-hosted 
- Open API
- Unlimited users
- Track fixed equipment (assets) in addition to consumables (inventory)
- Scan barcodes with mobile app - look at everything about an item
- Biggest advantage is level of customization: 
     - Fields
          - Every single field is a custom field
          - Fields can display conditionally, based on item type
          - Basically, Knack 😆
     - Custom actions and workflows

App
  - Android or iOS
  - Can do everything doable from desktop except for building out content model and workflows
  - Use phone as scanner

Pricing 
  - Annual subscription 
  - $1500 Up to 500 asset types
  - $500 for training and configuration

14 day trial
  - Can download app on phone and use app from there as well
  - Trial account is set up with tool-tracking template
  - Make changes *Configuration > Group Settings*
  - API docs *Configuration > API Configuration*
