### ISSUE TITLE
Features for AMD Project Tracking - To Do from Review 2/5/24

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#15650]
### FORM: New Project Intake Request
- [x] Add radio button for `Location Type` 
   - include Specific (actual address), intersection (primary street/cross street), or Section of Road
   - Reference Traffic Count 
- [x] Change `Asset Type` drop down to radio buttons - _updated during the 2/5/24 meeting_
- [x] #15715
   - If single, keep structure of asset information the same (might need to set up a rule to insert a record into a related table of assets)
   - If multiple, hide asset fields from first page. Create secondary page with a related table for the Requester to add multiple assets to the request
- [x] ~Add `Requested Task` field to the related table of assets~ need to think through this more
- [x] Also include a space for Requesters to include attachments on the request  

### PAGE: Project Intake Details
 - [x] #16692
 - [x] #16693
 - [x] #16694

_Originally posted by @ChristinaTremel in https://github.com/cityofaustin/atd-data-tech/issues/14764#issuecomment-1927470001_

## AMD Feedback Reference
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/dba0c327-6489-49f3-af66-3a042e1d0319)

**Comment by dianamartin** [comment]
## Discussion Points
- Using the word "asset" v. "component"

## Enhancements
- [ ] Add a new field "Location Type"
- Intersection - "Primary/Secondary fields"
- Section of Road
- Specific Location - "Address"
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/a02e1ded-0c12-482a-b93a-755ce3e0bfa1)

### Number of Project Locations
  - [ ] Single
  - [ ] Multiple

### Add more Reviewers to "Reviewer List"
-  [ ] Add AMD Management
-  [ ] Add Communications

## Project & Request Timeline 
- Convert from short text and make into radio button choices
  - 3 months or earlier
  - 3 months to 6 months
  - 6 months to 12 months
  - Other

# Features
- [ ] 1. Ability for users to "Add Attachments" during submission
- [ ] 2. Ability for user to "Add Comments" 
- [ ] 2. Add "Requested Task" to the field of related assets

**Comment by dianamartin** [comment]
# 2/6/2024
## Updates to AMD Project Prototype
- [x] Changed "Requester Type" - from multi choice to radio
- [x] Updated "Name " to "Requester Name"
- [x] Updated "Phone" to "Requester Phone"
- [x] Updated "Email" to "Requester Email"
- [x] Changed "Requesting for New or Existing asset" - from multi choice to radio
  - [x] renamed field on form - "Requesting for New or Existing asset/component"
- [x] Changed "Asset Type" - from multi choice to radio
- [x] Updated field "Project Timeline" - from short to multi choice
- [x] Updated field "Request Timeline" - from short to multi choice

**Comment by ChristinaTremel** [comment]
### Updated to AMD Project Prototype 2/7
- [x] Added `Attachments` feature on the secondary Project Request page 

### Question for AMD
- Single vs Multiple locations
   - If a Requester selects location type `Specific Location` or `Intersection`, they shouldn't be able to add multiple locations should they? (Because a specific location and intersection is just a single location)
   - Should we only have them choose the "Number of Requested Locations" if the location type is `Section of Road`? Do we want them to also have to add a brief location description to the Locations table?

**Comment by ChristinaTremel** [comment]
## 2/26 AMD Check-In for Single vs Multiple Locations
### Discussions: 
- Add additional question - `Is your request associated to a larger project?`
   - If yes, ask project timeline
   - If no, just ask request timeline
- Update Moped field to  `Existing Moped Project ID` and ask if the requester says the request is associated with a larger project
- Have one form for New requests and one form for Existing requests on the `Locations` page
   - One table for New Requests
   - One table for Existing Requests
- Requesting a new signal, ask if there's a study (on the locations table)
  - Move study field to the locations table
- Internal AMD Users:
   - AMD would like us to autopopulate the Points of Contact
- As part of the intake process, Ivonne's team can fill out the location type and general location of the parent project because AMD will need to create a Moped project anyways
   - There will be a processing form used by Ivonne's team in the details page and we can include that location information there.


### Question Answered by AMD
- Single vs Multiple locations
   - Should we only have them choose the "Number of Requested Locations" if the location type is `Section of Road`? Do we want them to also have to add a brief location description to the Locations table?
      - Take away location information from the first page and only include the second page 
- New vs Existing locations
   - Confirm that we would expect Requesters to submit separate request for new and existing location modifications
      - We will have new and existing on the same request, but will have 2 tables and 2 forms to keep the page clean
- Do we want Requesters to have to verify with a Digital Signature or confirmation statement (example from Banners)
   ![image](https://github.com/cityofaustin/atd-data-tech/assets/61209591/a84ad4df-4351-48c2-9443-71d350c14a6c)
   - AMD is going to discuss internally when this would be needed. Might be needed for certain types of projects. 
   - Would be useful for confirming that this has been reviewed by Area Engineers
   - External users should have a case development project 
   - Separate confirmations for internal and external

**Comment by ChristinaTremel** [comment]
Completed the follow up requests from the review on 2/5 & created additional issues.
