### ISSUE TITLE
Enhance location tracking for project intake requests

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#15674]
- While adding the new field `Location Type`, Diana and I noticed that several fields were missing for using this structure of having several different formats for location.

## New Fields
- Primary Street Block (PRIMARY_STREET_BLK)
- Primary Street - needs to be a connected field
- ` Cross Street`-> RENAME to `Cross Street 1 Name` (CROSS_ST_1_NAME) - needs to be a connected field
- Cross Street 1 Block (CROSS_ST_1_BLOCK)
- Cross Street 2 Name (CROSS_ST_2_NAME) - needs to be a connected field
- Cross Street 2 Block (CROSS_ST_2_BLOCK)
 - Location Name Intersection 
   - {PRIMARY_STREET_BLK} {Primary Street.STREET_NAME} / {CROSS_ST_1_NAME.STREET_NAME}
- Location Name Section of Road
   - {PRIMARY_STREET_BLK}  {Primary Street.STREET_NAME} from {CROSS_ST_1_NAME.STREET_NAME} to {CROSS_ST_2_NAME.STREET_NAME} - [ ] Location Name Specific Location
   - {PRIMARY_STREET_BLK} {Primary Street.STREET_NAME} 
- Location Name
   - CONDITIONAL RULES:
      - LOCATION_TYPE is `Intersection` - set to field value `LOCATION_NAME_INTERSECTION`
      - LOCATION_TYPE is `Section of Road` - set to field value `LOCATION_NAME_SECTION_OF_ROAD`
      - LOCATION_TYPE is `Specific Location` - set to field value `LOCATION_NAME_SPECIFIC_LOCATION`

_Originally posted by @dianamartin in https://github.com/cityofaustin/atd-data-tech/issues/15650#issuecomment-1930123861_

**Comment by dianamartin** [comment]
# 2/6/2024
## Updates
- Renamed "Primary Street" - to "PRIMARY_STREET"
- - [ ] Primary Street Block (PRIMARY_STREET_BLK)
- [ ] Primary Street - needs to be a connected field
- [ ] ` Cross Street`-> RENAME to `Cross Street 1 Name` (CROSS_ST_1_NAME) - needs to be a connected field
- [ ] Cross Street 1 Block (CROSS_ST_1_BLOCK)
- [ ] Cross Street 2 Name (CROSS_ST_2_NAME) - needs to be a connected field
- [ ] Cross Street 2 Block (CROSS_ST_2_BLOCK)
 - [ ] Location Name Intersection 
   - {PRIMARY_STREET_BLK} {Primary Street.STREET_NAME} / {CROSS_ST_1_NAME.STREET_NAME}
- [ ] Location Name Section of Road
   - {PRIMARY_STREET_BLK}  {Primary Street.STREET_NAME} from {CROSS_ST_1_NAME.STREET_NAME} to {CROSS_ST_2_NAME.STREET_NAME} - [ ] Location Name Specific Location
   - {PRIMARY_STREET_BLK} {Primary Street.STREET_NAME} 
- [ ] Location Name
   - CONDITIONAL RULES:
      - LOCATION_TYPE is `Intersection` - set to field value `LOCATION_NAME_INTERSECTION`
      - LOCATION_TYPE is `Section of Road` - set to field value `LOCATION_NAME_SECTION_OF_ROAD`
      - LOCATION_TYPE is `Specific Location` - set to field value `LOCATION_NAME_SPECIFIC_LOCATION`

## Field Reference
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/61c32d88-892a-4220-a8e1-cfff422cfa1d)

**Comment by ChristinaTremel** [comment]
The locations have been restructured, but this was completed!
