### ISSUE TITLE
Create banner fields to an `Employees` object in TPW HiRe

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#15686]
### Field to be included on the `Accounts` object in TPW Hire
- [x] Name
- [x] Email
- [x] Employee ID
- [x] Position Number
- [x] Department
- [x] Division
- [x] Class
- [x] Class Description

### Research
- Need to check if these fields are available. If not - find out steps for reaching out to see if we can pull these from Banner
   - Division number 
   - Location code
   - Salary Grade
   - PCN Labor Distribution -  Where the position is budgeted from

**Comment by ChristinaTremel** [comment]
Need to decide if we want to include these new fields on a new PCN tracking object or on the Accounts object.

**Comment by dianamartin** [comment]
# 2/9/2024
Fields to be included | Accounts | PCN
-- | -- | --
 Name | X | X
 Email | X | X 
 Employee ID | 
 Position Number
 Department
 Division | X | X
 Class
 Class Description

**Comment by dianamartin** [comment]
# 2/26/2024
## Background
- Christina and I had brainstormed on what the structure would be for the `PCN Management` table when we automate the Employee and PCN information from the HR Portal (via Banner feed). 
- Showed it to HR at last sprint review and Jennifer expressed that they ultimately want to track the PCN and think the PCN information isn't so good from BANNER. 
- She thought they could upload what they have into the TPW Hire Portal

## Reference
- In the HR Interview Mgmt [Miro board ](https://miro.com/app/board/uXjVPpGwiwA=/)
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/646b22e5-50b9-4970-a5dd-76ab81a70d61)
- We thought that we should add a new "Employee" table in TPW Hire and connect it to the "PCN Management" table because the Banner feed data won't have the most accurate PCN information, but will have the list of employees we want to associate to a PCN. 
- We all decided we don't want the Banner feed to populate "Accounts" automatically like the HR Portal, but we want the option to connect "Employees" to the "Accounts" for the purposes of Panel Members for interviews and for Hiring Managers to have access to the PCN tracking information.

## Build Steps
- [ ] Export and Download `Accounts` table from HR Portal (as a test)
- [ ] Create `Employee` Table
- Field headings
  - [ ] Name
  - [ ] Email
  - [ ] Employee ID
  - [ ] Position Number 
  - [ ] Department 
  - [ ] Division
  - [ ] Class 
  - [ ] Class Description 
- [ ] New Connect `Previous Employee` table to `PCN Management`
- [ ] New Connect `New Internal Employee Name` table to `PCN Management`
- [ ] New Connect `Employee Name` table to `Accounts`
- [ ] Add Text Formula `Email Address` - to build the account

## Test
- [ ] Add `Previous Employee` to PCN record
- [ ] Add `New Internal Employee Name` to PCN record
- [ ] Create new Account for Employee (connection), bring in email and then test

**Comment by dianamartin** [comment]
# 4/16/2024 
Forgot to document that we completed this. 

On 3/22/24, Charlie asked if we could create the TPW Hire API page for the "Employee" table
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/9b83a27b-23ab-4370-b04b-9d528c20801b)
