### ISSUE TITLE
Create Communication `Hub Cabinet` asset type in production

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#15691]
- Implement changes from #10209 into production
- `Hub Cabinet` object and fields have already been created
- Follow steps in the comment to set up connections and add fields/record rules/display rules as detailed

**Comment by ChristinaTremel** [comment]
## Builder Steps
# IN AMD Data Tracker - PROD

## 1. Created Hub Cabinet asset (new object table)
- [x] Created `hub_cabinets` object
- [x] Created fields needed to test connection
   - `ATD_LOCATION_ID`
   - `HUB_NAME`
   - `HUB_ID`
## 2. Connect asset to objects

### `tmc_issues` object
- [x] Added connection field to `hub_cabinet`
- [x] Add "hub_cabinet" to `ASSET_TYPE` field
- [x] Update validation rule to `ASSET_TYPE` field
   - ASSET_TYPE is `hub_cabinet` and `hub_cabinet` is blank
   - Message shows "Message type does not match asset selected"

### `tmc_activities` object
- [x] Added connection field to `hub_cabinet`
- [x] Add "hub_cabinet" to `ASSET_TYPE` field
- [x] Update validation rule to `ASSET_TYPE` field
   - ASSET_TYPE is `hub_cabinet` and `hub_cabinet` is blank
   - Message shows "Message type does not match asset selected"

###  `work_order_signals` object
- [x] Add "hub cabinet" to `ASSET_TYPE` field
- [x] Added connection field to `hub_cabinet`
   - [x] Add validation to new field
      - hub_cabinet is not blank
      - Message shows "You must select a hub cabinet when asset type is hub cabinet."
- [x] Added `HUB_ID` field to `work_order_signals` object
- [x] Update validation rule on `ASSET_ID` where `ASSET_TYPE` is "hub cabinet" set to a field object `HUB ID`

## 3. MMC - Form, Display, and Record Rules

### MMC Details Display & Record Rule Updates
- [x] Added "Hub Cabinet" to the MMC Details page

### FORM: "Assign Asset - API | Systems Admin ONLY" form (hidden)
- [x] Add "hub cabinet" field to form
- [x] DISPLAY RULE
  - Create new rule for ASSET_TYPE is "hub cabinet"
     - `show` - hub cabinet
     - hide - signal
     - hide - school beacon zone
     - hide - dsdd
     - hide - dm
     - hide - hazard flasher
     - hide - signal request
     - hide - school beacon
   - All ASSET_TYPE not "hub cabinet"
      - hide - hub cabinet
- [x] RECORD RULE
  - Updated record rule 2 for Identify Asset 
    - `hub_cabinet` to field `hub_cabinet`
  - Update connected records - tmc_issue (tmc_issue>tmc_issue)
    - hub_cabinet is `not blank`
    - location to a connected value (hub cabinet>ATD LOCATION ID)

### FORM: "Add mmc activity" form - **START HERE**
- [x] Add "hub cabinet" field to form
- [x] DISPLAY RULE
  - Create new rule for ASSET_TYPE is "hub cabinet"
     - `show` - hub cabinet
     - hide - signal
     - hide - school beacon zone
     - hide - dsdd
     - hide - dm
     - hide - hazard flasher
     - hide - signal request
     - hide - school beacon
   - All ASSET_TYPE not "hub cabinet"
      - hide - hub cabinet
- [x] RECORD RULE
   - Updated record rule 2 for Identify Asset 
      - Add additional `hub_cabinet` to field `hub_cabinet`
   - Update connected records - tmc_issue (tmc_issue > tmc_issue)
       - hub_cabinet is `not blank`
       - location to a connected value (hub cabinet>ATD LOCATION ID)

### FORM: "add_work_orders" (embedded form)
- [x] **Record Rule**
   - Add to Record Rule 1 
      - hub_cabinet to a connected value (tmc_issues > hub_cabinet)
   
## 4. Work Orders - Form, Display, and Record Rules
### FORM: New Work Orders | Trouble Call 
- [x] Add `Hub Cabinet` to the form
- [x] DISPLAY RULE
  - Asset Type is "hub cabinet" - `Show/Hide`
- [x] RECORD RULE
  - Asset Type is "hub cabinet" 
  - ATD LOCATION ID - connected value - hub cabinet>ATD LOCATION ID

### FORM: New Work Orders | Schedule Work
- [x] Add `Hub Cabinet` to the form
- [x] DISPLAY RULE
   - Asset Type is "hub cabinet" - `Show/Hide`
- [x] RECORD RULE
   - Asset Type is "hub cabinet" 
   - ATD LOCATION ID - connected value - hub cabinet>ATD LOCATION ID
   
### FORM: My Work Orders - "Edit Work Order" button
- [x] Add `Hub Cabinet` to the form 
- [x] DISPLAY RULE
   - Asset Type is "hub cabinet" - `Show/Hide`
- [x] RECORD RULE
   - Asset Type is "hub cabinet" 
   - ATD LOCATION ID - connected value - hub cabinet>ATD LOCATION ID

### Work Orders (Signals) - "Edit Work Order" button
- [x] Add `Hub Cabinet` to the form  
- [x] DISPLAY RULE
   - Asset Type is "hub cabinet" - `Show/Hide`
- [x] RECORD RULE
   - Asset Type is "hub cabinet" 
   - ATD LOCATION ID - connected value - hub cabinet>ATD LOCATION ID

### Work Orders (Communications) - "Edit Work Order" button
- [x] Add `Hub Cabinet` to the form 
- [x] Added "ASSET_TYPE" to the form
- [X] DISPLAY RULE
    - ASSET_TYPE is "hub cabinet" - show/hide - hub cabinet
    - ASSET_TYPE is "signal" - show/hide - signal
- [x] RECORD RULE
    - Signal (split record rule 1 so this is it's own rule)
       - When Asset Type is "Signal"
       - ATD Location ID - connected value - signal>ATD LOCATION ID 
   - Hub Cabinet
      - Asset Type is "hub cabinet" 
      - ATD LOCATION ID - connected value - hub cabinet>ATD LOCATION ID

## 5. Details Pages
### PAGE: `My Work Orders` Details
- [x] Add "Hub Cabinet" to Related Assets section

### PAGE: `Work Orders - Technician` Details
- [x] Add "Hub Cabinet" to Related Assets section

### PAGE: `Work Orders (Communications)` Details
- [x] Add "Hub Cabinet" below Signal ID

**Comment by ChristinaTremel** [comment]
Made all the changes in production! Need to review with AMD.

**Comment by ChristinaTremel** [comment]
Harrell was shown how to create the hub cabinet asset in Data Tracker. Closing this!
