### ISSUE TITLE
Maximo Discussions, Project Coordination

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#15705]
### Objective
Discuss ongoing Maximo projects and enhancements to business processes as it pertains to Maximo and the project coordinators' respective work groups.

**Comment by adry-martinez** [comment]
Test

**Comment by adry-martinez** [comment]
## February 7, 2024

### Participants
Areli C., Michael D., Andre E., Adriana M., Rene V. 
_Ryan H. (did not attend)_

### Agenda

- Discuss update on report designs
 - Downtown Enhancement
 - Pavement Operations Prep Performance Measure
- Dive into UER's current process using Excel and how to implement in Maximo
- Review GitHub issues:
  -  #13939 
  -  #13985 
  -  #14872 
- Discuss future/potential project of improving Specifications organization and requiring fields prior to close out
- Review data quality review

### Meeting notes: [SBO Project Coordinator Meeting](https://docs.google.com/document/d/1FmvUz6jQ1Wlvh2Tdr16WGaLCiNnb4qck6xBNrW7lzUE/edit#heading=h.mgpotw6slfvw)

------

### Action Items
_**Maximo Team**_
- [ ] Schedule meeting with Floyd and OCE regarding new process 
- [ ] Create Sweeping portlet for Sweeping WOs in 2-, 3-, 4-status

_**Project Coordinators**_
- Chat with work groups regarding organization of the attributes in Specifications tab
- Review data quality report to see if anything needs to be omitted or updated

**Comment by adry-martinez** [comment]
## DATE

### Participants

### Agenda
- Discuss any needs for #13888 
- Discuss any needs for #13729 
- ITEM

### Meeting notes: [SBO Project Coordinator Meeting](https://docs.google.com/document/d/1FmvUz6jQ1Wlvh2Tdr16WGaLCiNnb4qck6xBNrW7lzUE/edit#heading=h.mgpotw6slfvw)

------

### Action Items
_**Maximo Team**_
- [ ] Task
- [ ] Task

_**Project Coordinators**_
- Item
- Item

**Comment by adry-martinez** [comment]
## Feb. 29, 2024

### Participant(s): 

### Agenda

#13939 
#16008 
#16007 
#15750 
#16040 
#13985 
#16042 
#15826, #15824 

- Adry OOO starting 2/29 - 3/15, will be back on 3/18 but will be a short week due to medical reasons. 
- Maximo Booking link

### Meeting Notes

### Action Item/s

**Comment by adry-martinez** [comment]
## Mar. 18, 2024 

**Participant(s):**
Mike D., Adriana G.

**Agenda:**

Discuss Scofield project:
  - Will be done in Phases
  - Parent (For the entire Project)
  - Child (for each phase)

**Comment by adry-martinez** [comment]
### Apr. 3, 2024

Participant(s):

Agenda:
#16040 
#16510 
#16403 
#16376 
#16110 
#13939 
#16509 
#15824 

Meeting Notes:

**Comment by adry-martinez** [comment]
## April 17, 2024

### 🙋🏼 Participant(s)


### 📄 Agenda

- Discuss items on GitHub board
- Discuss training efforts
- Update start centers: District Maintenance and Project Coordinator

### 📓 Meeting Notes


### ✅ Action Item/s
**DTS Maximo**

**Project Coordinators**

**Comment by rebekkabry** [comment]
## 📆 June 6, 2024

### 🙋🏼 Participant(s)


### 📄 Agenda
- [x] General Updates - _(bulletin board)_
      - New Training Resources and Link Access - [Maximo Sharepoint Landing Page URL](https://cityofaustin.sharepoint.com/sites/MaximoResources)
- [ ] Last Meeting Updates 
- [ ] Issues Review, Recap, Insights (review updates and discuss specs, when applicable)

**Comment by rebekkabry** [comment]
SBO 

- Maximo Updates
- [ ] email about unhappy with service done to the sidewalk. attempting to figure out how to handle the ticket. order 24-178905 

- request for reorder of specs

**Comment by rebekkabry** [comment]
## 📆 Septermber 5, 2024

### 🙋🏼 Participant(s)


### 📄 Agenda
- [ ] General Updates - _(bulletin board)_
- [ ] Last Meeting Updates 
- [ ] #17351 Q/A Report @ReneVarg25
- [ ] Issues Review, Recap, Insights (review updates and discuss specs, when applicable)
  - **In Progress:** 
     - #17580 and #17669 by SI and SV
- [ ] Work Group Q/A Concerns 
- [ ] Stakeholder Updates 
   - Next Roundtable? 


### ✅ ACTION
**DTS Team** 
- [ ] Discuss sending to Project Coordinators in addition to the SI when we send out reports.

**Project Coordinators** 
- [ ] Forward Markings Whereabouts meeting to Rene, Rebekka, and Christina
- [ ] Upload forms used to [Sharepoint Folder](https://cityofaustin.sharepoint.com/sites/MaximoResources/Maximo%20Reference/Forms/AllItems.aspx?ovuser=5c5e19f6%2Da6ab%2D4b45%2Db1d0%2Dbe4608a9a67f%2CRebekka%2EBryant%40austintexas%2Egov&OR=Teams%2DHL&CT=1714741773715&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiI0OS8yNDAzMzEwMTgxNyIsIkhhc0ZlZGVyYXRlZFVzZXIiOmZhbHNlfQ%3D%3D&id=%2Fsites%2FMaximoResources%2FMaximo%20Reference%2FStakeholder%20Materials%2FDaily%20Work%20Logs&viewid=3c78a351%2D813f%2D4ed0%2D8510%2D57c8cfb5e8a2)

**Comment by rebekkabry** [comment]
# 11/7/24 

+ Work Log: 
- ryan sent an email to myself and 311, confirmation from them that nothing would get messed up. 
- reviewed email from ryan. 
- Q: does 311 or tech responsbile for text? A: tech. 
- Andre: they had to have an agreement with 311 what information needs to go back, as a request from director level that we are not providing enough text. The messages where done by the Maximo team and 311. 
- Rene: recent issue: one of them was not mapped to the 311 response.
- Q: Andre: wants the process when we tell someoone to call back, if we close it and they call back. New order or Austin 311 contact for more information? A: they need to consider.  Risk: workorders not attached to CSR for the same issue. 

.311 mapping review
.dispatch workorder handling guides and workflows from coordinators.  
.work log template upgrade to include: 
scheduled meeting with Carrie and team

+ rene: has already left message. ctm says issue has been resolved. but we are confirming. 

+ weather prep: 
- possibly loaded bridges into maximo? meeting with dave.
- are we using CSR? refer to Dave. who is responsbile for entry of data...appears to be SBO project coordinators.  

+ start centers:
-reviewed test and prod

**Comment by rebekkabry** [comment]
# 1/2/24 

- 311 work order mapping - on deck within DTS Maximo TBD 
- account clean up and update to staff in Maximo - in progress 
- Updates from SI for DIST is complete - update in Maximo on staff 
- Any Weather Preparation updates? 


- Coordinator Updates Regarding 
-  Work Log Notes Process:

**Comment by rebekkabry** [comment]
# 2/6/25 
- 311 Meeting
  - OPM, Junior and Andrew - MAXIMO Initiative Porject. 

**SCOPES** 
- Areli - DIST all and (Downtown) 
- Michael - USD / UER 
- Andre - Pavement

@ReneVarg25 and @GaneshKamarapu how is the report going for account clean up? Please advise and/or link ticket.

**Comment by rebekkabry** [comment]
# 6/22/26 
_Attendees: Colton, Ryan, Andre, Cierra, Michael_ 

Questions regarding updates on MAS 9 
- Service Address 

Upset - weeks without resolution, knocking out limitations, 


**Limitation concerns:** 
- SLAs - Districts, all those are going to count against them with they do the performance reporting (pot holes) - the process with Knack and transfering them over. They are all caught up with those. 
- The main problems have been fixed - Colton 
- The SRs that were caught, would show up on the overdue report. 


**Still Happening:** 
- Returning to main page (biggest issue) (comes and goes; not for everyone to the same degree; or certain times of the day)
- Service Address 


**Status Updates:** 
- Fog Seal Service Plan work orders status? 
- Marking Tabs a required field. need to have that implemented. (email Diana,

**Comment by rebekkabry** [comment]
# 8/24/26 

- Added new member, Kaylan, T
- Service Address: is there an ETA? not yet. Gave the updates on datasets needed to Q/A on the new solves. 
- Check box for the stripping? / ATD Marking 
   - Markings is in progress. 
- SP27 - Work Orders not sent yet but will be soon. 

- Updates: Rumors about meeting with Directors/Jim with meeting with Christina, any updates on the meeting. 
- Updates: Centralizing the DTS team, no answers at the moment.
