### ISSUE TITLE
Update Project Intake form structure for requested locations and type of request

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#15715]
### Decisions made by AMD during 2/26 check in
- Single vs Multiple locations
   - Should we only have them choose the "Number of Requested Locations" if the location type is `Section of Road`? Do we want them to also have to add a brief location description to the Locations table?
      - Take away location information from the first page and only include the second page 
- New vs Existing locations
   - Confirm that we would expect Requesters to submit separate request for new and existing location modifications
      - We will have new and existing on the same request, but will have 2 tables and 2 forms to keep the page clean
- Have one form for New requests and one form for Existing requests on the `Locations` page
   - One table for New Requests
   - One table for Existing Requests

**Comment by ChristinaTremel** [comment]
## Notes 
- Created secondary form page for New Project Requests called `Requested Locations` 
- Created a form for adding locations/assets at the location
   <img src="https://github.com/cityofaustin/atd-data-tech/assets/61209591/19631bf0-cc22-46ba-aba7-1e921f6d7a43" width="400">
- Created a table for tracking the added locations/assets
   ![image](https://github.com/cityofaustin/atd-data-tech/assets/61209591/dd102611-59bf-4939-92f5-6265e5aaaa52)

- Hid location information on the first New Project Request form if `Number of Locations` = Multiple

**Comment by dianamartin** [comment]
# 3/22/24
Synced with Christina
- [x] Removed location fields from the first part of the form
- [x] Recreated a second part of the form `Project Locations`
- [x] Added a details section
- [x] Added menu buttons for "Existing Location" and "New Location"
- Added new fields to `project_locations`
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/84a380e3-fe30-406a-af39-eddfb49664ff)
- [ ] Configured "Existing Location" form
- [ ] Configured "New Location" form

**Comment by ChristinaTremel** [comment]
We updated display rules and the forms are working as expected. Closing this issue!

**Comment by ChristinaTremel** [comment]
Reviewed this with AMD during a review meeting on 4/12.
