### ISSUE TITLE
Copy of SBO Project Coordinator Discussions

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#15723]
### Discuss ongoing Maximo projects and enhancements to business processes as it pertains to Maximo and the project coordinators' respective work groups.

Use the template below to compile agenda, notes, and tasks:

### Agenda
- ITEM
- ITEM
- ITEM

### Meeting notes: [SBO Project Coordinator Meeting](https://docs.google.com/document/d/1FmvUz6jQ1Wlvh2Tdr16WGaLCiNnb4qck6xBNrW7lzUE/edit#heading=h.mgpotw6slfvw)

------

### Action Items
_**Maximo Team**_
- [ ] Task
- [ ] Task

_**Project Coordinators**_
- Item
- Item

**Comment by adry-martinez** [comment]
**Feb. 7, 2024**
@ReneVarg25 may you please update our notes from our last meeting with CTM? The link is listed above. Please tag me once this is done, thanks!

**Comment by adry-martinez** [comment]
## Feb. 5 2024 Meeting 

- [ ] Meet with A. Collins re: multiplication symbol use
- [ ] Provide sample of using map to add asset and location (Send recording to Mike)
- [ ] Provide a classification example and attributes to require before 4-status
- [ ] Add Sealcoat portlet to Start Center

**Comment by adry-martinez** [comment]
## Feb. 7
Met with A. Collins and confirmed he's using X not the symbol when entering log notes.

**Comment by adry-martinez** [comment]
### Feb. 26, 2024
Reviewed CTM labelled issues and closed several.
Notified team of my OOO. Rene will be on standby for support.

**Comment by adry-martinez** [comment]
### Apr. 1, 2024 
Discussed #16509 
#15749

**Comment by adry-martinez** [comment]
## Apr. 14, 2024

### 🤝  Particpants 

### 📑  Agenda 
Discuss planner board on TEAMS channel

- #15749 Use the District Maintenance Completion Checklist and review the Specifications section.
  - requiring fields in the specifications tab prior to 4-status change.
- Lane miles represented on the Pavement Operations start center
- #16516 - any updates on updating the report to reflect the WO total instead of line item total?
- #16509 - @ReneVarg25 please provide the logs used for the following log types: NO_ACTION_FOUND, TEMP_REPAIR, NONCOA_JURISD
- #14110 any updates on this request?
- Updating meeting to **TPW <> CTM bi-weekly meeting**
- Discuss Maximo new hire onboarding and requirements #16787 

### 📓  Meeting Notes 

### ☑️  Action Item/s

**Comment by adry-martinez** [comment]
## April 29, 2024

### 🤝 Participants
CTM: Erin, Mario, Mike, Denise
TPW: Adriana, Diana

### 📝 Agenda 
Discuss pending items
Discuss new hire

### 📓 Meeting Notes 

**Kurve**
will update to collect lane miles, there will be an update for users to be able to create reports via Kurve

**Reports**
**Guardrail Report** updated by Erin, need to verify
**Downtown Enhancement Sidewalk Report** in progress by Nick
**District Maintenance Data Quality Report** in Test but is completed.

**Specifications Attribute Requirement** Nick has not started yet.
 
**Work Log Auto-Fill** Erin will have it ready in Test and then move to PROD.

** #14110  ** the script is completed. 

### New Hire Ganesh K.
- Diana sent e-mail address to CTM to set up Maximo account. 
- Adry asked re: checklist for tools
   - have a dB2 tool, not oracle. 
   - confirm if Ganesh that he has a dB2. 
   - will need an IBM ID to be able to add him to get access to get query database
   - Erin will do checklist BIRT reporting/Maximo access

### ✅ Action Items
**District Maintenance Data Quality Report** in Test, Maximo team will verify and then notify CTM to move to PROD.
**Guardrail Report** updated by Erin, need to verify in PROD.

**Comment by adry-martinez** [comment]
## April 29, 2024

### 🤝 Participants
CTM: Erin, Nick
TPW: Adriana, Ganesh

### 📝 Agenda 

1. Introductions 
2. Discuss access to database and Open VPN 
3. Get added to IBM self-service


### 📓 Meeting Notes 

2. Will get instructions on the database connection. We are dB2. Erin uses Squirrel. Nick uses Oracle SQL. It's been a long time but will be able to set up. 
4. 

### New Hire Ganesh K.


### ✅ Action Items

**Comment by adry-martinez** [comment]
Completed 14110 
Review 15749 - 
Attributes Requirements before 4COMP - Nick is running some tests 
Auto-populate log notes - Nick will work on this 
GIS EzMaxMobile - Mike will chat with team re: map manager.

**Comment by rebekkabry** [comment]
Update from CTM - placeholder to build out notes 

- Kurve - update ability to apply SQL filter, embed into Start Center, able to allow multi 1:1 related relationships. More to come per Aaron

**Comment by rebekkabry** [comment]
# 8/19/24
- Projects 
- [ ] KURVE upgrades - done, will have a report to look at.

**Comment by rebekkabry** [comment]
Upcoming Meeting to Discuss 
**DTS Maximo** 
- [ ] #18275 
- [ ] How to add Specification? 
- [ ] Job Plan Rights?

**Comment by rebekkabry** [comment]
# 8/19/24
** Projects** 
- [x] KURVE upgrades - done, will have a report to look at. To get a KURVE dashboard. New platform to create reports, and can embed into the start center. not replacing BIRT. expands users ability to create adhoc reports. 
- [x] Auto Initiate the Wokrflow for SBO-SR - should be able to test after the back flow. ETA later this week to test. EZMAX mobile.  #17782  
     - New Build in EZMAZ is in test, but the back fill over ride the test. So they are putting back in TEST> 
     - ETA 9/6/24 to test in mobile. 
- [x] Related SRs - Testing works with MAXIMO. ETL testing needs to happen before we see any changes in PROD. #17700 
- [x] Specs Requirements: pending Nick updates - for SEALCOAT_WORK classification. SBO Maximo to get more data on specs needs. Complete.  
![image](https://github.com/user-attachments/assets/f25cd314-0867-442d-b075-61e0a9c9b429)
 - Test and Communicate to Stakeholders make sure classification, change status and be sure it requires status before. @rebekkabry 
- [ ] GIS SBO Lat Long Assets- working, have 7 tables that need to be looked at and verified. Pending @ReneVarg25 examples. 
- [ ] FLEET - @dianamartin do we need new account or other provisions? 
- [ ] Urban Forestry Transfer - mini reorg. Other ways to transfer 311 Feedback or FlexField 2? Are they still under TPW? Yes. Per Erin: bc typically TPW could continue to use MAXIMO as it, without too much. May need a new start center. Per Diana: not considered under SBO, more like SMD in relationship to SBO. Per Erin: talk with 311, training could be needed.
- [ ] [SN Request Link ](https://atx.servicenowservices.com/sp)
- [ ] Spec Re Order - request to have ATD Markings moved up.

**Comment by rebekkabry** [comment]
# 9/16/24
_Erin is out._ 
** Projects** 
- [ ] KURVE upgrades - done, will have a report to look at. To get a KURVE dashboard. New platform to create reports, and can embed into the start center. not replacing BIRT. expands users ability to create adhoc reports. 
- [ ] Auto Initiate the Wokrflow for SBO-SR - should be able to test after the back flow. ETA later this week to test. EZMAX mobile.  #17782  
     - New Build in EZMAZ is in test, but the back fill over ride the test. So they are putting back in TEST> 
     - ETA 9/6/24 to test in mobile. 
- [ ] Related SRs - Testing works with MAXIMO. ETL testing needs to happen before we see any changes in PROD. #17700 
    - They have the message structure and process for 311. no change for 311. ESB team needs to change configu on. 
    - ETA a few weeks. 
    - CTM will reach out to Carrie before moving to PROD
    - #15771 being impacted due to this. 
- [ ] #15731 Specs Requirements: pending Nick updates - for SEALCOAT_WORK classification. SBO Maximo to get more data on specs needs. Complete.  
![image](https://github.com/user-attachments/assets/f25cd314-0867-442d-b075-61e0a9c9b429)
    - Test and Communicate to Stakeholders make sure classification, change status and be sure it requires status before. @rebekkabry 
    - Need to confirm in PROD
- [ ] GIS SBO Lat Long Assets- working, have 7 tables that need to be looked at and verified. Pending @ReneVarg25 examples.
   - A few have been added over the weekend. 
   - Need to check ROW Trees now. Have 3 more tables that need to be verified. 
   - ETA 9/16/24 or next time we meet. 
- [ ] FLEET - @dianamartin do we need new account or other provisions? 
   - We can do either per Rick. If easier to share they are fine but if one is needed we can create. 
   - Christina will send email about using CTM credientials for now. If issues arise we could request own later. 
   - Christina schedule a meeting with data science on the coordination. @ChristinaTremel 
- [ ] Urban Forestry Transfer - mini reorg. Other ways to transfer 311 Feedback or FlexField 2? Are they still under TPW? Yes. Per Erin: bc typically TPW could continue to use MAXIMO as it, without too much. May need a new start center. Per Diana: not considered under SBO, more like SMD in relationship to SBO. Per Erin: talk with 311, training could be needed.
- [x] Spec Re Order - request to have ATD Markings moved up. 
   - Training has been complete. 
   - Pending stakeholder scoping. 
- [ ] Lane Miles - new object needed in KURVE. Currently all queries are written to the SBO structure screen, so the KURVE reporting mirrors the out of box. So we may need to create a custom objects. Erin is going to create map and add it. ETA next meeting  9/16/24
- [ ] Back Load Complete 9/1/24 with CTM (goal for 2 times a year) 
- [ ] Duplication issue has been complete? @ReneVarg25

**Comment by rebekkabry** [comment]
# 10/28/24 

- Rene has tested and confirme sidwalks working 
- 311 Testing on Thursday, pending live push. will communicate with us after Thursday 
- EzMaxMobile - use the links, into URL.

**Comment by rebekkabry** [comment]
# 12/16/24 

- Close rotating assets, complete 
- 311 SR work orders, they are working on.

**Comment by rebekkabry** [comment]
# 2/3/25 Agenda for upcoming meeting 
- Rotating Assets: https://github.com/cityofaustin/atd-data-tech/issues/20478 and https://github.com/cityofaustin/atd-data-tech/issues/20701
- Assets Schema Updates

**Comment by rebekkabry** [comment]
# 5/5/25 Sync

- Once we move over to Mass 9 they may not be able to change work orders manually in the database. 
-

**Comment by rebekkabry** [comment]
# 2/23/26  

- EzMax Start Center - notification to trigger from CTM to see. Requested by Mark, done by @ReneVarg25 
- General time line for Mas 9. Mark informed same target date of March 23rd

**Comment by ChristinaTremel** [comment]
# 4/22/26
Check in on the following issues:
- Mapping feature in Maximo not working (since Mas9 migration)
- UER work orders not coming into Maximo (since Monday 4/20)
- UER work order descriptions missing cut type (since Mas9 migration)
- Frequent issues today with the system refreshing and returning users to the main page (issue today but has been reoccurring randomly
- SR to WO creation and also search of WO is taking me to main page (issue today)

**Comment by rebekkabry** [comment]
# Update from Past Meetings

**Comment by rebekkabry** [comment]
# 9/18/26 
- Reviewed open tickets 
- Next week TEST on start center / list EzMax mobile regarding IBMs ability to have charts on desktop and lists on mobile app 
- Missing work orders from report presented by Rene working with Nick and ATS. 

> - UER26-2376991, UER26-2376968, UER26-2376919, UER26-2376916 - These were from 8/15 which was a missing report date

- Review PVMT Completed Lane Miles report, not currently showing Fog Seal work orders. Queries of report. 

> - parentwoline =  "\n	AND  (wo.parent in ('14-20751', '15-32302', '16-289137', 'SP18-0005','SP19-0006') or (wo.parent like 'SP%-OVL') or (wo.parent like 'FY%-OVL')) " ;
> 1 Heart reaction.

and 

>   wo.SITEID='SBO' and  WO.PERSONGROUP IN ('SBOOVL','SBOIMG')  and wo.CLASSSTRUCTUREID like '%OVERLAY_WORK%' and  	WO.CSR311NUMBER is null "
