### ISSUE TITLE
District Maintenance Maximo Monthly Discussion

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#15771]
### Objective 
This meeting is to discuss any ongoing Maximo projects and support for District Maintenance.

### Agenda
- Provide updates on reports: 
  - issue #
  - issue #
  - issue #
 - Provide updates on portlets:
   - issue #
   - issue #
   - issue #
- Discuss data quality review
- Discuss Maximo team support to District Maintenance
------
### Action Items: 
_Maximo Team:_
- [ ] task
- [ ] task

_District Maintenance:_
-  item
-  item

**Comment by adry-martinez** [comment]
### April 8, 2024 

**Participants**:
Baldomero R., Diana M., Rene V., Adriana M.

**Meeting Notes**:
Portlet attachments - include all Districts omit prior 2022
Scheduled reports 311 was discussed
Overlay support, using identify, Crew DISTN1
South doing Milling, Eli will need to QA
North doing Paving, Jr will need to QA
Completed 2, tomorrow will be 3rd.
Keep an eye on report surface repair report
Also doing work for sealcoat, duplicate WO with naming convention  - DISTN
Made emphasis on training needs
Trying to find notes

**Comment by adry-martinez** [comment]
## May 9, 2024
### 🤝 Participants

### 📝 Agenda

1. Introductions
2. Completed requests:
    #16933 completed
    #16901 completed
3. Discuss SBODIST needs


### 📓 Meeting Notes

### ✅ Action Items
**DTS Maximo**

**District Maintenance**

**Comment by adry-martinez** [comment]
## Date

### :handshake: Participants
**SBO**:
**DTS**:

### :memo: Agenda
1. 
2. 
3.

### :notebook: Meeting Notes
1.
2.
3.

### :white_check_mark: Action Items
**DTS Maximo**

**District Maintenance**

### :calendar: Next meeting scheduled for DATE

**Comment by rebekkabry** [comment]
## DATE May 20, 2024

### 🙋🏼 Participant(s)


### 📄 Agenda


### 📓 Meeting Notes


### ✅ Action Item/s
**DTS Maximo**

**District Maintenance**

**Comment by rebekkabry** [comment]
## 📆 June 17, 2024

### 🙋🏼 Participant(s)


### 📄 Agenda
- [ ] General Updates - _(bulletin board)_
      - New Training Resources and Link Access - [Maximo Sharepoint Landing Page URL](https://cityofaustin.sharepoint.com/sites/MaximoResources)
      - DTS Maximo POC Direction 
      - DTS Request Form 
- [x] Issues Review, Recap, Insights _(review updates and discuss specs, when applicable)_
- **Q/A and Closed**
  - [x] #17145
  - [ ] #16509 
- **In Progress/Needs Scoping:** 
  - [ ] #17858 - solution expected to be resolved by CTM by EOD. Currently added select users to Dispatch Start Center. Pending SBO DM TEMP start center if not resolved by EOD. 
  - [ ] #17147 - Can you invite Vincent to next meeting or discuss this topics and provide insight? 
  - [ ] #17712 - in progress, not complete, updates to follow. 
  - [ ] #17351 @ReneVarg25 
  - [ ]  #13858 in progress, updates to follow
      - On Deck: (Will be our focus during the upcoming Sprint)
  - [ ]  #15637
  - [ ]  #17146
  - [ ]  #13544
- [ ] Quality Report Concerns - Rene _(backlogs, review Maximo)_
- [ ] Stakeholder Feedback and Updates 
- [ ] DTS Focus Areas _(if applicable and if time permits)_ 
      - MAXIMO Training Materials
      - Reporting Efforts

**Comment by rebekkabry** [comment]
create a new agenda 

q/a review needed by stakeholders 
#13858

**Comment by rebekkabry** [comment]
## 📆 August 15, 2024

### 🙋🏼 Participant(s)


### 📄 Agenda
- [x] General Updates - _(bulletin board)_
- [x] Issues Review, Recap, Insights _(review updates and discuss specs, when applicable)_
- [x] Last Meeting Action Items Updates
- **Q/A or Closed*
  - [x]  
- **In Progress/Needs Scoping:** 
  - [ ] #14658 what is the Q/A process in detail? Who are the players today? 

- **On Deck**: (Will be our focus during the upcoming Sprint)
  - [ ]  #15637
  - [ ]  #17146
  - [ ]  #13544
- [ ] Quality Report Concerns - Rene _(backlogs, review Maximo)_
- [ ] Stakeholder Feedback and Updates 
- [ ] DTS Focus Areas _(if applicable and if time permits)_ 
      - MAXIMO Training Materials
      - Reporting Efforts


### 📓 Meeting Notes

   
### ✅ Action Item/s
**DTS Maximo**

**District Maintenance**

**Comment by rebekkabry** [comment]
- Forestry Handoff - per Rene CTM, 311 and Urban Forestry has replied - there are no changes in how operates in MAXIMO. As of now and as of Oct 1, will still use Flex Field 2 to communicate any work to Urban Forestry. 
- SBO Project Work Order / CSR request by Areli. Any work that needs to be done within the CBD, looking for new. Want to do a DT refresh. IN the past, we did a maintainence plan for the CBD, to see what needs. After you load them, you can associate the street segments and create maximo work orders against them and we can load them in. 

![image](https://github.com/user-attachments/assets/07061e21-98b4-47d4-8eee-05a7f04897e6)

**Comment by rebekkabry** [comment]
Upcoming Meeting Items 
- https://github.com/cityofaustin/atd-data-tech/issues/19025
- https://github.com/cityofaustin/atd-data-tech/issues/18642
- Any PREP Storm Work Order Needs? 
- https://github.com/cityofaustin/atd-data-tech/issues/17146

**Comment by rebekkabry** [comment]
# 10/7/24 

## Meeting Topics Discussed 
- https://github.com/cityofaustin/atd-data-tech/issues/18360
- https://github.com/cityofaustin/atd-data-tech/issues/17146
- https://github.com/cityofaustin/atd-data-tech/issues/17147
- https://github.com/cityofaustin/atd-data-tech/issues/19136

**Comment by rebekkabry** [comment]
# 11/4/2024 

## Meeting Topics Discussed 
### New 
- https://github.com/cityofaustin/atd-data-tech/issues/19728

### In Progress 
- https://github.com/cityofaustin/atd-data-tech/issues/19639

### Need to Discuss and TO 
- Cleaning / Sidewalk FY25 Hierarchy, set meeting with VIncent and Eli @rebekkabry 
- @ReneVarg25 AMA meeting schedule details

**Comment by rebekkabry** [comment]
# 12/29/24 

+ sidewalks updates
  = worksession after 9th - has been scheduled. 1/20/24
  = added sidewalks assets they are able to add into work orders now
    = asset / address. 
+ end fy24 - no needs mentioned. 
+ begin fy25 
  = colony park/5CANCEL; Ryan follow up - DTS ticket being submitted. 

+ DTS weather: SBO will follow up with Dave on any needs and communicate to Maximo as needed.

**Comment by rebekkabry** [comment]
# 1/13/25 
- what is the status of report for https://github.com/cityofaustin/atd-data-tech/issues/20064 
- working on work log notes for COLONY park close request - ETA Tuesday

**Comment by rebekkabry** [comment]
# 2/25
- will sync notes 

#3/25
- will sync notes 
-
# 4/25 
- will sync notes

**Comment by rebekkabry** [comment]
# 6/16/25 
Discussions 
- Flex Field 2 SUTD options, still pending CTM completion and feedback 
- Materials/Cost Report - Data Science just made the first step in building dash 
- Residential vs Non Residential Request for Addresses 
- 311 Updates - addressing issues with WORKLOG type
   - from 60 to 12, DIST has been completing, correcting them to the right work log.

**Comment by rebekkabry** [comment]
# 7/20/26 

- review #15771 request and complete. 
- any 2027FY work orders needed.

**Comment by rebekkabry** [comment]
# Meeting Updates

**Comment by rebekkabry** [comment]
# 9/21/26 
Attendees: Rebekka, Rene, Junior, Lara, Shon, 

- Requirements of Work Order Discussion
> Junior: DIST (all NSC) a Photo included, ATD Markings, 
>   - ACTUALS? - DIST will discuss and let DTS know. 
> Shon: owner/lead before 4Comp

- Reviewed Q/A report, follow up next time and support clean up 🗒️ 
- Start Center Request: 

>  Lara: add Pothole portlets (can match report) maybe add 2. one for all overdue, 1 for all priority 4 regardless of status. Will be submitting an DTS tickets
