### ISSUE TITLE
IMG Maximo Monthly Discussion

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#15772]
### Agenda
Add agenda here or create agenda from [this template](https://docs.google.com/document/d/1d_49KW5C_vSz8Bs50v-cxyIJuTNJMwMrh7ypcxRHgZI/edit#) and add link. 

------
- [ ] Schedule meeting
- [ ] Optional: Schedule debrief
- [ ] Meet and take notes
- [ ] Optional: Debrief with DTS team members
- [ ] Create resulting issues

**Comment by adry-martinez** [comment]
## March 25, 2024

### Participants

### Agenda
Discuss Maximo items
Discuss OCE items

### Meeting Notes
EzMaxMobile Training
  - Ron is tentative for training
  - Reza already received training 
Reports
  - Requests for reports 
Rapid Response (Rudy)
 - were responding once a week, recently got reactivated due to issue from mayor. 
 - cannot service sites with 4 or more areas 
 - will be increase in requests for Manchaca, etc. 
 - starting to be spread out to N, C, and S with small homeless encampments and are daily
 - certain bridges are supplemental who were assisting SBO but will no longer be complete full support
 - Maximo: wanted better documentation, current process: Ben White/S Congress, if they confirm that this is one of our sites, they will provide dates based on schedules, will update SR with log notes. 
 - consideration to have District Maintenance for support. If not within normally schedule sites, to get either Adrian or Rudy. If not part of the sites, will be forwarded over to District Maintenance. Lisa and Rudy are testing this process within Maximo. 
 - Rudy would like to get training for EzMaxMobile, set up a portlet for Homeless Encampment. 
 - 

------

### Action Items:
**_Maximo team:_**
- [ ] item
- [ ] item

**_OCE/IMG:_**
- item
- item

**Comment by adry-martinez** [comment]
## May 13, 2024

### :handshake: Participants
**OCE**:
**DTS**:

### :memo: Agenda
1. Introductions
2. Share Meeting Handoff
3. Any Maximo needs

### :notebook: Meeting Notes
1.
2.
3.

### :white_check_mark: Action Items
**DTS Maximo**

- [ ] Task 1
- [ ] Task 2

**OCE**

- Task 1
- Task 2

#### :calendar: Next meeting scheduled for DATE

**Comment by rebekkabry** [comment]
## June 6, 2024

### :handshake: Participants
**OCE**: 
**DTS**: 

### 📄 Agenda
- [x] General Updates - _(bulletin board)_
      - New Training Resources and Link Access - [Maximo Sharepoint Landing Page URL](https://cityofaustin.sharepoint.com/sites/MaximoResources)
- [ ] Last Meeting Updates 
- [ ] Issues Review, Recap, Insights _(review updates and discuss specs, when applicable)_
   - Pavement/Milling Request for Separate Service Plans status #16886
   - Sidewalk or CONC Service Plan status 
- [ ] Q/A Status and Needs @ReneVarg25 
- [ ] Stakeholder Updates 
- [ ] DTS Focus Areas 
   - Report backlog clean up and completion within DTS Maximo team 

### :notebook: Meeting Notes


### :white_check_mark: Action Items
**DTS Maximo**

**OCE**

#### :calendar: Next meeting scheduled for July 2024.

**Comment by rebekkabry** [comment]
## July 8, 2024

### :handshake: Participants
**OCE**:  
**DTS**:  

### 📄 Agenda
- [ ] General Updates - _(bulletin board)_
- [ ] Issues Review, Recap, Insights _(review updates and discuss specs, when applicable)_
 - **SBO Ops Discussions and In Progress**
       -  #16886 conversations in progress with OCE and DTS to create a proposal to have presented for approval prior. 
       - #17467 confirm if all open work orders should be updated for FRED as SI? 
- [ ] Q/A Status and Needs @ReneVarg25 
- [ ] Stakeholder Updates 
- [ ] DTS Focus Areas 
   - Processing Mapping  #17037

### :notebook: Meeting Notes
`see above or issue links`

### :white_check_mark: Action Items
**DTS Maximo**

**OCE**

**Comment by rebekkabry** [comment]
## August 12, 2024

### :handshake: Participants
**OCE**:  
**DTS**:  

### 📄 Agenda
- [ ] General Updates - _(bulletin board)_
- [ ] Issues Review, Recap, Insights _(review updates and discuss specs, when applicable)_
- [ ]   **Q/A or Completed**
     - [ ] #17467 confirm if all open work orders should be updated for FRED as SI? 
     - [ ] #18079
      - [ ] #18191
     - [ ] #18249 (same as above) on DECK this week
 - **SBO Ops Discussions and In Progress**
     - [ ] #17951
     - [ ] What is needed or how does the Service Plan for FY25 need to be prepped for uploading? 
- [ ] Q/A Status and Needs @ReneVarg25 
- [ ] Stakeholder Updates 
- [ ] DTS Focus Areas 
   - Processing Mapping  #17037

### :notebook: Meeting Notes
`see above or issue links`

### :white_check_mark: Action Items
**DTS Maximo**
- [x] see if we need to reschedule to accommodate schedules. 

**OCE**

**Comment by rebekkabry** [comment]
# Service Plans FY25 Preparation Conversation

**Service Plan Crack Seal** - the report is not pulling parent, pulling children of seal coat. The projects are mapped wrong. Reporting for progress report for CS, each SC work order has a children for PREP for SC > we dont want those. only the work orders for PM, not PREP. Prep and PM need to be separate. 
- these are all connected to Service plans 
   - PM crack seal - stand alone service plan 
   - PREP crack seal - child of Seal Coat (not counted as Service Plan) it is required for Crack Seal (we need to be able to track differently) 

**Date Time Format Changing** 
Date format has changed. 
Report: current report for performance; MM/DD/YYYY previous > Mmm Dd, YYYY 12:00 now

CHange in user interface?
![image](https://github.com/user-attachments/assets/1d1aced9-ab8b-4a9e-9122-b75aac587244)


**TO DO:** get with Dave to understand PREP and PM reporting process.

**Comment by rebekkabry** [comment]
## September 9, 2024

### :handshake: Participants
**OCE**:  
**DTS**:  

### 📄 Agenda
- [x] General Updates - _(bulletin board)_
- [x] Issues Review, Recap, Insights _(review updates and discuss specs, when applicable)_
- [x]   **Q/A or Completed**
 - **SBO Ops Discussions and In Progress**
     - [x] #17951
     - [ ] #18349 
     - [ ] #18894 `(connected to above requested)`
 - **Needs Scoping**
     - [ ] #17951
 - **On Deck for DTS Team**
     - [ ] #18651 
  - **IceBox on Hold or Blocked**
     - [ ] #18079
     - [ ] #17798 
   - **Q/A or questions**
      - [ ]  Review Gitbook Specs areas 
      - [ ] What happens if an asset or service address not foud in Maximo? 
- [ ] Q/A Status and Needs @ReneVarg25 
- [ ] Stakeholder Updates 
- [ ] DTS Focus Areas 
   - Processing Mapping  #17037

### :notebook: Meeting Notes
`see above or issue links`

### :white_check_mark: Action Items
**DTS Maximo**

**OCE**

**Comment by rebekkabry** [comment]
# 10/14/24 

Meeting Topics: 
- https://github.com/cityofaustin/atd-data-tech/issues/19010
- OCE classification for SBO routed needs? 
![image](https://github.com/user-attachments/assets/238dc46f-55ce-40f4-aee6-0cfc23a5c8ca)
###    - What happens when SBO needs to reroute back to OCE to investigate or other needs? 
   - OCE says they do not because they typically handle the workgroup that will handle the operation. 
   - In Maximo? -> not sure at this point 
   - OCE typically will delete from Service Plan (in Seal Coat example) 
   - They may put in a future year. Not sure what happens to MAXIMO
   - May use `"INV_IMG/Engineering Investigation" ` to get back to OCE



TO DO 
- [ ] @rebekkabry may need to add NV_IMG/Engineering Investigation ALL portlet for IMG/OCE

**Comment by rebekkabry** [comment]
# 6/8/26 

-  Discuss: completed  Maximo WO not in  SBOPVMT Completed Lane Mile Report  
- Which WO# as example: 26-208776


<img width="1146" height="826" alt="Image" src="https://github.com/user-attachments/assets/0dc075e6-983f-48ed-b873-d34fc8491b93" />

<img width="798" height="404" alt="Image" src="https://github.com/user-attachments/assets/405b51fe-7315-4c0d-b9d5-78b41e739e08" />


- After reviewing, appears that the address 26-208976 for 9206 BRIGADOON CV
