### ISSUE TITLE
Pavement Operation Maximo Discussion, Monthly

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#15814]
### Objective 
To discuss ongoing Maximo projects and requests for Pavement Operations

### Agenda

------
- [ ] Schedule meeting
- [ ] Optional: Schedule debrief
- [ ] Meet and take notes
- [ ] Optional: Debrief with DTS team members
- [ ] Create resulting issues

**Comment by adry-martinez** [comment]
## April 10, 2024

### 🙋🏼 Participant(s)

### 📄 Agenda

- Discuss items on Pavement Ops board
- Brief on training plan
- Review Data Quality report
- Assess stakeholder needs

### 📓 Meeting Notes

### ✅ Action Item/s
**DTS Maximo**

**Pavement Ops**

**Comment by adry-martinez** [comment]
## DATE

### 🙋🏼 Participant(s)


### 📄 Agenda

- Discuss items on Pavement Ops board


### 📓 Meeting Notes


### ✅ Action Item/s
**DTS Maximo**

**Pavement Ops**

**Comment by adry-martinez** [comment]
## May 8, 2024

### 🙋🏼 Participant(s)


### 📄 Agenda

1. Introduction - Ganesh, Maximo Report Developer
2. Discuss items on Pavement Ops board
    - #16403 
    - #17070  
3. Review Data Quality report
4. Assess stakeholder needs

### 📓 Meeting Notes

1. 

### ✅ Action Item/s
**DTS Maximo**

**Pavement Ops**
none at this time

**Comment by rebekkabry** [comment]
## 📆 May 20, 2024

### 🙋🏼 Participant(s)


### 📄 Agenda
- [ ] General Updates - _(bulletin board)_
      - New Training Resources and Link Access
- [ ] Issues Review, Recap, Insights _(review updates and discuss specs, when applicable)_
- [ ] Q/A Report Concerns - Rene _(backlogs, review Maximo)_
- [ ] Stakeholder Feedback and Updates 
- [ ] DTS Focus Areas _(if applicable and if time permits)_ 
      - MAXIMO Training Materials
      - Reporting Efforts 

### 📓 Meeting Notes
- notes 
- notes

### ✅ Action Item/s
**DTS Maximo**

**Pavement Ops**

**Comment by rebekkabry** [comment]
## 📆 June 5, 2024

### 🙋🏼 Participant(s)

### 📄 Agenda
- [ ] General Updates
- [ ] Last Meeting Updates / Open Issues that Need Discussion 
  - **On Deck** 
     - Communicate Expectation of Data Entry to be Logged As Actuals: Labor #17669
  - **In Progress** 
     - Tech III Training Plan for Maximo/ Training Curriculum for Pavement Ops #16721 / #16720 📅 _Pending Meeting Set Up_
   - **Needs Scoping**
     - currently none 
- [ ] Updates on Scoping Issues / Need feedback from Stakeholders
     - Insights for Removing Parent/Child to have standalone WO #16886 _(need to discuss internally will have updates in upcoming discussions)_ 
     - Modification of Report (to see PREP, LU) for now #17659
     - Start Centers and Portlets to aid Staff Management #14546
     - Reporting (in next session with updates) #17659
- [ ] Work Order Status Discussions 
    - Do we need to discuss the 1000k ticket status? @ReneVarg25 can you advise on the current state of those tickets? 
- [ ] Stakeholder Feedback and Updates 
 - ❓ any special dates, seasonal events, etc


### ✅ Action Item/s
**DTS Maximo**
- [ ] Maximo 101 Training Plan @adry-martinez @rebekkabry - could we use the videos created to build out a self service resource and check in through the MAXIMO build that was used in last training? 
- [ ] #16928 Set up meeting to review discover, on-boarding PPT, sign off on process flow with stakeholders _(current in progress issues)_
    - Seal Coat #16928
    - CrackSeal 
    - Fog Seal
    - Overlay #17303
- [ ] MVP for Level Up Reporting (if approved) 
- [ ] Start on MAXIMO Test Page Start Center for demo 

**Pavement Ops**

**Comment by rebekkabry** [comment]
## 📆 July 3, 2024


### 🙋🏼 Participant(s)

### 📄 Agenda
- [ ] General Updates
- Last Meeting Cont. of Agenda
  -  [ ] In **Q/A** `ready for use, do you need a date? `Work Order Status Discussions? #17659 
- Last Meeting Updates / Open Issues that Need Discussion 
  -  [ ] #16886 `scope has been updated, working with OCE to prep for FY25 plans. proposal will be developed and shared for approval before implementation. meetings in progress. ` #17961 
  -  [ ] In **Q/A**  #17659 `Do they open Workorders need to be updated to reflect current SI?`
  -  [ ] #14546 `We allow Dave A. to make the final decision on the report approvals, if stakeholders do not have any input. `
 - On Deck, Upcoming Sprint Cycle. 
  -  [ ]  #17806 and #17805 ` Start Centers are still in progress, updates next meeting`.

**Comment by rebekkabry** [comment]
## 📆 July 31, 2024


### 🙋🏼 Participant(s)

### 📄 Agenda
- [ ] General Updates
- Completed or Q/A
   - [ ]  Updated Fred to Bryon,` updates needed?` #17467
- Last Meeting Cont. of Agenda / Last Meeting Updates / Open Issues that Need Discussion 
  -  [x] #16886 `scope has been updated, working with OCE to prep for FY25 plans. proposal will be developed and shared for approval before implementation. meetings in progress. ` #17961 
        `- on deck for upcoming sprint `
  -  [ ] #18191 
  -  [ ] #17659 `Follow up with Dave A on requestor and communication to team of spec requirements`
  -  [ ] #14546 `NOTE 1: We allow Dave A. to make the final decision on the report approvals, if stakeholders do not have any input. 
  NOTE 2: Similiar request for PAVEMENT/MILLING for OVERLAY Service Plan report `
  - [x] #16737 @ReneVarg25 
 - On Deck, Upcoming Sprint Cycle. 
  -  [ ]  #17806 `in progress for current sprint`
  -  [ ]  #17805  
  -  [ ] #17843
- [ ] Stakeholder Feedback and Updates 
 - ❓ any special dates, seasonal events, etc
- [ ] Upcoming Focus Areas 
   - Review [PPT for Ops Work Order](https://docs.google.com/presentation/d/1BdvP3_FHF_htyoxhL301b496JfUaxqmvLY-SrULDIqM/edit#slide=id.g2dbfd5ee5e4_0_114) Hierarchy 
   - Review [Work Order Completion ](https://github.com/cityofaustin/atd-data-tech/issues/16771)Requirements.


### ✅ Action Item/s
**DTS Maximo**
- [x] add Andre into the OCE, feel free to forward. 
**Pavement**

**Comment by rebekkabry** [comment]
# 10/29/24 

-  Discussed previously Seal Coat concerning their Specifiation has been completed. Currently we only have level up? 
- They want to capture level up, they are not capturing cut outs? 
- advised them to consult with ops team to know exactly which specifications are needed. 
-

**Comment by rebekkabry** [comment]
# 12/30/24 - OCE PMIS Review and Discussion 

### Goals
**We would like to do a full demo of you showing:** 
- How you are updating system to report number? 
   - PMIS system and what gets sent to Maximo for bulk imports. 
   - PMIS LM data and what is reported out of PMIS system
   - Maximo to PMIS updates, where are the gaps? 
**We would like to compare the data pull process between OCE with PMIS and Dave with Maximo.**

### Note
Also,  we  did not provide the 2023 numbers, those  were  taken in 2023   by others from MAXIMO and were not verified as to location – or   date. (MAXIMO should not be relied on  for  FY LM data ) 
“cool seal “ was a contracted test material fog seal …not necessarily in  Council District Two , and  not  repeated in 2024 


**PMIS poweruser:** 
- scheduling, is coordinated with SBO. 


**Issues:** 
service plan is what going to be done in the 12 month of the budget. 
Q: district, at the end of the year, what was odone in that distric as part of the serioi plan 

### CONCERN: 
- pavement manager - may not have the district lines correct, so could be a question about if the street is listed in the correct district, should not be listed twice. 
- what is the cut off date? we know the service plan is 12 month, oct 1 - sept 30. 
  - if we on sept 30 how much gets done and counted. 
***need to be sure the reporting standards are corrected and decided upon, both sysetems need to show the same cut off date. 

***distrcits that cross multiple, if more than 50% is on the distric,t they will assign

***have boundaries been changed for districts, they have updaged regarding each segment.

**PMIS**  
segment id - is tied to maximo id

**Comment by rebekkabry** [comment]
# 1/15/25 

- Review workgroup and crew assignments 
- Review management needed for those assignments 

**Previos notes from week 11/18/24**

> The crack seal update, for last year is what is coming back. 
> 
> Completed lane miles report? 
> need to be sure we are clling for FY25 year data, currently not showing up. 
> 
> Checking to make sure all the SEALCOAT work orders were assigned to CLEVELAND. 
> 
> and fog seal to BRYON CARTER. 
> 
> Seal Coat = Fred Cleveland 
> 11568 - SLC1/SCL2
> 
> Fog Seal = Byron Carter

**Comment by rebekkabry** [comment]
# 1/15/25 Notes

# Fog Seal Start Center 
![image](https://github.com/user-attachments/assets/4b75edd8-b1c5-4ab9-b3d1-56483e42fa3f)
![image](https://github.com/user-attachments/assets/1d95c513-48ea-44b9-a7ce-d920f61143da)
different than what DTS MAXIMO has in PROD

- requested to hold workgroup/crew until DM meeting next week. 

Start Center: 
- SBO Pavement Ops 
- SBO Fog Seal (Alfred LeDay - SBOsupervisors start); crew using: not sure  
- SBO Seal Coat (Jonathon/John Ford): good to go
- SBO Crack Seal (Leday, Ford)  

(Managment) 

Training - they use Maximo, how to put in the data. 


TO DO: 
- schedule meeting iwht leday and expert maximo user to review user views. 

Management: 
Crack Seal PM - Bryon Carter ///when put in jOb changes to fcleveland 
@rene - SLCT2, will update and a request will be sent in. the default on the job plan is showing FCleveland. 


flex field 2 
SP24-135024

-they will create a new one, per Andre; will provide the documentation.

**Comment by rebekkabry** [comment]
# 2/6/25 Agenda 
- 5Canceled Status - get worklog note confirmation. Pending CTM updates to account. 
- Upcoming Service Plans or Service Needs
- Q/A work order report

**Comment by rebekkabry** [comment]
# 5/7/2025 Sync

**Comment by rebekkabry** [comment]
# 5/21/25 

_John, David, Jonathon, Rene, Rebekka, Fred_

**FOGSEAL** 
- Updated monthly report access to Pavement workgroup - Jonathon confirmed he can see the report now 
- Report reading SLCT1 and SLCT2 
![Image](https://github.com/user-attachments/assets/53111b7b-4088-4591-9dac-252801e44729)

**SEALCOAT** 
- Unable to add actuals and David was receiving errors. 
- We confirmed they added to PLANS and not ACTUALS. 
- Was unable to duplicate issues when added to ACTUALS. 
- Confirmed data was not on OPD data for ACTUALS prior to investigating. 
- David will add and let us know if any further support is needed. 

**OTHER** 
- following up on request for 3 new users sent this week.

**Comment by rebekkabry** [comment]
# 4/20/26

Shon - crew having a issue printing work orders. From the reports page, not at to print. No abilities to print. Reports that is it was working but now not working. 

- COA Work Order Details report. - INC0565524  
-  confirmed able print from the new COA installed printers,not working for report. 

<img width="1069" height="583" alt="Image" src="https://github.com/user-attachments/assets/157d7a6b-1118-4d8f-a13d-605a829874ef" />

<img width="1312" height="931" alt="Image" src="https://github.com/user-attachments/assets/a379a2b1-a881-4002-81be-9114db8422c2" />


- EZ Max Mobile pics not loading on the desktop. 
  -  when team has loaded pics into the mobile app and unable to see on the DESKTOP. can see it on the mobile app. 
  - MANUAL - team is going back via Desktop to add them. 

- EZ Max Mobile portals not showing for crew.

**Comment by rebekkabry** [comment]
# 7/15/26 
- [x] additional FY26 SP have been added. 
- still working on specifications and service addresses. 
- [x] added FOG SEAL report to start center per John F. request.
- Chris B. overlay access. the link currently only has lane miles and totals. Pavement. Needs supervisor and superinternet. 
- @ChristinaTremel do you know where we are with being able to share the Service Plan dashboard. Looking to have insights into the FOGSEAL completed lane miles report. Curious if we should explore Power BI or if the Dashboard will be ready soon to provide to stakeholders. 
  - Report Name Issue with ATS: 
  - Power BI Query: 
- GOAL: Run Overlay Monthly Operational or FogSeal to see completed lane miles/progress report. 
- [x] Create a Service Now Incident: Please confirm the query pull for "SBO FOG SEAL Lane Miles Progress Report Monthly Operational Performance " does it include ability for FY2026 and include Workgroups (SLCT1, SLCT2, FGSL work orders?) - INC0583612

<img width="226" height="199" alt="Image" src="https://github.com/user-attachments/assets/e8043ffe-2e70-4109-a033-3b6dbb0c0c46" />

<img width="345" height="209" alt="Image" src="https://github.com/user-attachments/assets/c7dc5ce5-23c8-4e88-9c6b-51d55b8b5c02" />

<img width="997" height="693" alt="Image" src="https://github.com/user-attachments/assets/f1fed3a5-8ebd-4085-81aa-22cc242cc2a9" />

**Comment by rebekkabry** [comment]
# Early August Meetings.

**Comment by rebekkabry** [comment]
# 8/26/26 
- no one from SBO PVMT joined. 
- intended to discuss: 
   - SP27. Ensuring the crew/project/workgroup alignments. 
   - any SP26 needs before closing
   - confirm required fields for all PVMT workgroup workorders. Any would like to add, now is the time.

**Comment by rebekkabry** [comment]
# 9/9/26 
Attendees; Rebekka and Rene ONLY. 
-  to discuss 
   - FY27 prep 
   - TREE WORK Seal Coat work orders 
   - Requirement Specifications 
   - FY26 needs before EOY 
      - email Reza the report data for - we are getting results as he refers to only receiving 2 work orders on the report he is running. Asked him to confirm the report name he is running. 

<img width="492" height="263" alt="Image" src="https://github.com/user-attachments/assets/8cfd2280-7cc2-4185-83cd-86990aa248d6" />

   - Confirm EZMax Mobile usage regarding portlets.

**Comment by rebekkabry** [comment]
# 9/23/26 

- Discussed: 
   - Work order requirement recommendation - pictures 
   - SP26 - Close Out Efforts with Project Coordinator 
    - Requirements - pictures only for now. 

- Open Items: Report and FY27 
	Job Title Changes (Bobby, Dave A, Aaron E) - @ReneVarg25 Investigation in progress. 

- In Progress 
   - Fog Seal PVMT report 
   - SP26 close out 
   - SP27 prep
