### ISSUE TITLE
Open Data: Add `Beacon Name` and `Glance PID` field to School Zone Beacon Socrata dataset

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#15857]
Requested By: Samir

AMD is requesting that we add the newly created `Beacon Name` and `Glance PID` fields to Socrata dataset so they can report on the progress of the project to implement the Glance PIDs. 
- #14925 was the original issue for creating these fields  
---
### Apps Steps 
[API View](https://builder.knack.com/atd/amd/pages/scene_418/views/view_3086/table)
   - [x] Add `Beacon Name`
   - [x] Add `Glance PID`
  - [x] Refresh dataset - set Modified Date to today's date on the 'school_beacons' object 
  
[EDP Dataset](https://datahub.austintexas.gov/Transportation-and-Mobility/School-Zone-Beacons-COA/8whb-sg4d/about_data) 
   - [x] Add `Beacon Name`
   - [x] Add `Glance PID`
   - [x] Push updates to [Socrata ODP Dataset](https://datahub.austintexas.gov/Transportation-and-Mobility/School-Zone-Beacons/mzsm-hucz/about_data)

ETL Follow-Up 
- [x] Check datasets Friday morning 2/16/24 
     - [x] [EDP](https://datahub.austintexas.gov/Transportation-and-Mobility/School-Zone-Beacons-COA/8whb-sg4d/about_data) 
     - [x] [ODP](https://datahub.austintexas.gov/Transportation-and-Mobility/School-Zone-Beacons/mzsm-hucz/about_data)

**Comment by KaroEngstrom** [comment]
## Fri 2/16 
- @ChristinaTremel despite refreshing the dataset, this morning's ETL did. not bring these over to Socrata. Need dev help after all on this.

**Comment by ChristinaTremel** [comment]
Chia will update the metadata!

**Comment by chiaberry** [comment]
I see the beacon name populated in the ODP, but not the glance PID. I took a quick _glance_ at the glance pid in knack and didnt see any data in it, so i think its working?

**Comment by ChristinaTremel** [comment]
- Checked the Socrata dataset and the data avilable in Data Tracker is showing up in the ODP 🎉
- Let Samir know that these fields are available
