### ISSUE TITLE
Create ODP dataset for the "School Zone Beacon Zones"

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#15896]
> What application are you using?

AMD Data Tracker

> Describe the problem.

Create a Open Data Portal dataset for the "School Zone Beacon Zones" Data Tracker page. Here is the URL: https://atd.knack.com/amd#school-zone-beacons/school-zone-beacon-zones/

Include as fields listed as columns on that page. 

> Describe the outcome you'd like to see when this feature is implemented.

MMC and ATD more generally will have access to School Zone Beacons Zone DT page information. MMC will be able to link ODP to a Power BI dashboard enabling that will aid in the prioritization of School Zones throughout the Glance Deployment project. The page includes WebIO and System fields that help us filter groups of school zones to be deployed together or before one another. The page also has a field that links a school zone to the engineering "area" it falls under.

> Describe any workarounds you currently have in place or alternative solutions you've considered.

One alternative I've considered is to grab an export of the School Zone Beacon Zone page, however, this would be an extra step/spreadsheet and we would like to consolidate as much as possible in an attempt to keep our updates on Data Tracker.

> Is there anything else we should know?

My hope is that this can be done as soon as possible. I think we have time to push it but the sooner the better. I am available all week if coordination is needed to get this done sooner. One question you may have is whether we can provide all info on this page as public access. I am talking to Edward right now to get that answer.

> Requested By
Samir S.

Request ID: DTS24-112800

**Comment by KaroEngstrom** [comment]
## Tue 2/20/24 
- talked about this a bit during sprint review
- I checked and there's no existing dataset
- from Samir, add these fields in addition to the summary table of School Zone Beacon Zones 
![image](https://github.com/cityofaustin/atd-data-tech/assets/100615928/cc1ccbc6-626b-4eda-a898-e302dc8d67dc)

@ChristinaTremel - 
Do you think we want to create a public dataset as well as a private one for this? I can look at the summary table and see if it involves any PII that would even need to be removed.

**Comment by ChristinaTremel** [comment]
## Fields to add to API table & Socrata Dataset: 
- [ ] Location ID
- [ ] WebIO
- [ ] Zone ID
- [ ] Zone Name
- [ ] School Name
- [ ] ISD Name
- [ ] Area
- [ ] System
- [ ] Number of Beacons
- [ ] Zone Note
- [ ] Modified Date

**Comment by KaroEngstrom** [comment]
## Wed 2/21/24
- [ ] Create API table from `school_beacon_zone` records and add 
     - [ ] WebIO (web_io connection > web_io)
     - [ ] Zone ID (school_beacon_zone_id)
     - [ ] Zone Name (zone_name) 
     - [ ] School Name (school_name) 
     - [ ] ISD Name (isd_name) 
     - [ ] Area (geo_area)
     - [ ] System (system) 
     - [ ] Status (zone_status) 
     -  Number of Beacons | OLD (sum num_of_beacons) - listed but should not be added 
     - [ ]  Number of Beacons (sum num_of_szb) 
     - [ ] Zone Note (zone_note)
     - [ ] Modified Date (modified_date) 
     - [ ] Modified By (modified_by) - waiting to hear if this is needed

**Comment by ChristinaTremel** [comment]
@KaroEngstrom just heard back from Allyson and she would like the Modified By field to be included! So we have that PII component in this request.

**Comment by KaroEngstrom** [comment]
## Wed 2/21/24
- added the Modified By field 
- created the EDP target dataset: https://datahub.austintexas.gov/Transportation-and-Mobility/School-Zone-Beacon-Zones-COA/vz34-kwdc
- created the ODP public view dataset:

**Comment by ChristinaTremel** [comment]
The apps side of the request has been completed!

**Comment by ChristinaTremel** [comment]
The School Zone Beacon Zone dataset has been created and I sent the link to Samir!
