### ISSUE TITLE
Maximo User Resources Redesign

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#15944]
## STEPS
Planning the training workflow in [Miro](https://miro.com/app/board/uXjVN7sxj9I=/)
- [x] Create GitBook Maximo Resources - @dianamartin 
  - To improve Maximo user's UX for Maximo training/reference information
- [x] To improve Maximo Account Requests - @dianamartin 
  - provide Maximo team "Employee List" view to see Employee ID
  - to improve Maximo team's process
- [ ] NEW issue: Improve [Maximo Resources SharePoint](https://cityofaustin.sharepoint.com/sites/MaximoResources/SitePages/Home.aspx) - Karo/Diana
  - to improve the self service process for any TPW employee that needs Maximo information

_Originally posted by @dianamartin in https://github.com/cityofaustin/atd-data-tech/issues/14962#issuecomment-1939465440_

**Comment by dianamartin** [comment]
# 2/15/2024
- [x] Created Maximo [GitBook Page](https://open.gitbook.com/~space/QMuMrK3UWgrwcodLRmTg) - WORK IN PROGRESS
- [x] Tested out different ways to embed, best way was to use file embed in GitBook

I messaged Chrispin bc we were talking about GitBook updates and enhancements
>I've been testing the maximo helpguide page with the various attempts at embed.
- It one that is simple is the direct file one - ***BEST RESULT***
- the one connected to a google account prevents non-users to sign into Google workspace
- the knack embedded page shows up dark on the phone
- direct embed that shows the thumbnail up on desktop, from PIO, takes a minute to load and isn't showing up yet until I refresh

**Comment by dianamartin** [comment]
# 2/21/2024
Had Maximo SharePoint Usability Workshop and these are the actionable things that came from that

## DTS Service Request tasks
- [ ] Create link for Maximo where "Application" field is pre-populated

## GitBook Tasks
- [x] Delete test embeds
- [x] Create earmarked pages for training materials (PDFs) - [Maximo Help Guide GitBook](https://open.gitbook.com/~space/QMuMrK3UWgrwcodLRmTg)

## SharePoint Tasks
- [x] Labeling "Page Type" on all Site Contents
- [ ] Create Workgroup pages
  - [ ] District Maintenance
  - [ ] Pavement Operations
  - [ ] Utilities & Structure
  - [ ] Bridges
  - [ ] Concrete Repair
  - [ ] Urban Forestry
  - [ ] Office of the Engineer
- [ ] Enhance the "Map & Tools page"
- [ ] Enhance the QRS Page - user friendly for training
- [ ] Enhance "Basic Navigation Page" - user friendly for training

**Comment by dianamartin** [comment]
# 3/5/2024
- [x] Worked on enhancing the "Map & Tools page"
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/b6e94663-afe7-48ee-86e4-0a8a04b0803e)

- [x] Created "Basic-Navigation" page, organized in sections what areas they would be like
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/0215e15f-e7e5-4aa9-85a1-542566efd86c)

**Comment by dianamartin** [comment]
# 1/14/2026
Will close this one as we have the Maximo GitBook wiki space created and updated.
