### ISSUE TITLE
Update rules for SMD reimbursable status field

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#15964]
Replace Conditional Rules in Reimburseable Status field in `reimburseable_tracking` with record rules on the `Reimbursable Reporting` page.

### Existing Condition Rules for Reimbursable Status
![MicrosoftTeams-image](https://github.com/cityofaustin/atd-data-tech/assets/61209591/f0563893-e0a9-4373-bef6-0c1f960df2cb)
![MicrosoftTeams-image (1)](https://github.com/cityofaustin/atd-data-tech/assets/61209591/19641c4f-14ce-4d47-935c-f350886908ea)

_Originally posted by @susannegov in https://github.com/cityofaustin/atd-data-tech/issues/14320#issuecomment-1936548791_

**Comment by ChristinaTremel** [comment]
### Reimbursable Status: Not Ready
- [x] On `New Work Order | Markings` form
   - Add record rule to set `Reimbursable Status` to "Not Ready"
- [x] On `New Work Order | Signs` form
   - Add record rule to set `Reimbursable Status` to "Not Ready"

### Reimbursable Status: Ready to Invoice
- [x] On `Close Work Order` form for signs
   - Add record rule to update connected reimbursable record and set `Reimbursable Status` to "Ready to Invoice"
- [x] On `Close Work Order` form for markings
   - Add record rule to update connected reimbursable record and set `Reimbursable Status` to "Ready to Invoice" 

### Reimbursable Status: Needs Review
- [x] On `Edit Reimbursable Markings` form
   - When `Submitted_PE_PM_for_Review` is not blank, Set `Reimbursable Status` to **Needs Review**
- [x]  On `Edit Reimbursable Signs` form
   - When `Submitted_PE_PM_for_Review` is not blank, Set `Reimbursable Status` to **Needs Review**
 
### Reimbursable Status: Waiting for Requester Approval
- [x] Renamed "Waiting for Approval" to "Waiting for Requester Approval" 
- [x] On `Email Invoice` form
   - Add record rule to update `Reimbursable Status` to "Waiting for Requester Approval"

### Reimbursable Status: Approve
- [x] Add additional value to record rule for `Approval Status` is not "Reject with Comments"
   - Update `Reimbursable Status` to "Approve"
- [x] Added record rule to update FDU if `Approval Status` is "Approve with FDU Change"
   - Update `Funding_FDU_Number` (on work order) to a field value `Funding - FDU`

### Reimbursable Status: Review Required for Approval
- [x] Add additional value to record rule for `Approval Status` is "Reject with Comments"
   - Update `Reimbursable Status` to "Review Required for Approval"
   
### Reimbursable Status: Closed

**Comment by ChristinaTremel** [comment]
This is ready to review with SMD.

**Comment by ChristinaTremel** [comment]
These changes were reviewed with SMD on 2/29
