### ISSUE TITLE
[Tech Services] New Hire Onboarding Checklist - [START DATE: Manuel A.] 

### ISSUE THREAD

**Issue by JBStrange** [cityofaustin/atd-data-tech#16022]
## Steps
Supervisor: Cesar M. 
User: Manuel A. 
Division: AMD

Reference - [ManuelA Checklist document](https://cityofaustin.sharepoint.com/:w:/r/sites/tpwDTS/_layouts/15/Doc.aspx?sourcedoc=%7B81512810-B700-448C-8200-38B343CB257D%7D&file=New%20Hire.docx&action=default&mobileredirect=true)
- [x] Check if NERF was submitted?
- [x] Set up password/Reset password (Ask Scott & Matt, if available, else ask CTM help desk (512-974-HELP)

## Software Checklist
Ask Supervisor what the new hire will need
- [ ]  Adobe
- [ ]  ArcGIS 
- [ ]  AutoCAD/AutoCAD 3D
- [ ]  BlueBeam 
>if user wants both (Adobe & BlueBeam), ask why?
- [ ]  SketchUp 
- [ ]  MS Project
- [ ]  MS Visio
Order software from CTM [here](https://cityofaustin.sharepoint.com/sites/CTM/TEAMSITES/AS/MSELA/Lists/MicrosoftFY24DepartmentTransactions/Customer%20View.aspx?xsdata=MDV8MDJ8fDdjMTg4OTBjMDViZDRmNjY0Y2EyMDhkYzM0OGViODBhfDVjNWUxOWY2YTZhYjRiNDViMWQwYmU0NjA4YTlhNjdmfDB8MHw2Mzg0NDMwMzQ3NTc0NTA5MTR8VW5rbm93bnxWR1ZoYlhOVFpXTjFjbWwwZVZObGNuWnBZMlY4ZXlKV0lqb2lNQzR3TGpBd01EQWlMQ0pRSWpvaVYybHVNeklpTENKQlRpSTZJazkwYUdWeUlpd2lWMVFpT2pFeGZRPT18MXxMMk5vWVhSekx6RTVPbTFsWlhScGJtZGZXV3BzYUUxNlNtMU5WMDEwV1cxV2JVOVRNREJaYlUwMVRGUm5kMDVIVlhSUFZFazFXV3BGTlZscVZYcFpWR2N5UUhSb2NtVmhaQzUyTWk5dFpYTnpZV2RsY3k4eE56QTROekEyTmpjMU1qTTN8NGU3MDdjMDEyMTcxNDNkMDRjYTIwOGRjMzQ4ZWI4MGF8ZjQxNzZkZThmNTFkNGM4YmJhODM1NzhhYmZkNWFkODg%3D&sdata=WlNGR0ZyRU9JVHNCcUJXSDloTVEyMm1ocGhNM0tVN21Pc2hCZUkrV0Mzcz0%3D&ovuser=5c5e19f6-a6ab-4b45-b1d0-be4608a9a67f%2CDiana.Martin%40austintexas.gov&OR=Teams-HL&CT=1708706699063&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiIyNy8yNDAxMDQxNzUwMyIsIkhhc0ZlZGVyYXRlZFVzZXIiOmZhbHNlfQ%3D%3D)

## Hardware Checklist
>Does the user need a GIS Modeling computer?
- [ ]  GIS Laptop w/ specialist docking station
- [X ]  Laptop
- [X ]  Power supply
- [X ]  Docking station
- [X ]  Monitors
- [X ]  Keyboard (hardwired)
- [X ]  Mouse (hardwired)
- [ ]  MiFi (must be request by the supervisor)

**Comment by JBStrange** [comment]
This PC was issue to the End User and there are no other issues reported.

**Comment by dianamartin** [comment]
@JBStrange can you please update the title on this issue with the employee name and last initial

**Comment by dianamartin** [comment]
@JBStrange if this is done please close it. Also, add their "Start Date" to the title of the issue.
