### ISSUE TITLE
Utilities and Structures Monthly Discussion

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#16035]
### Objective 
to discuss stakeholder needs as it related to Maximo for Utilities and Structures division. 

### Agenda

------
- [ ] Schedule meeting
- [ ] Optional: Schedule debrief
- [ ] Meet and take notes
- [ ] Optional: Debrief with DTS team members
- [ ] Create resulting issues

**Comment by adry-martinez** [comment]
### Feb. 27, 2024 
### Participants

### Agenda
Review #15609 

------
_**Maximo Team**_

_**Utilities and Structures**_

**Comment by ReneVarg25** [comment]
### 2/27/2024
Review https://github.com/cityofaustin/atd-data-tech/issues/15609
Updated issue with notes

### Meeting Notes
What does a role in UER do in Maximo?
Techs 1-3
Leads
Supervisors
Superintendent
Project Coordinator

All roles have some responsibility
1-3 techs task them with Maximo entries within the field, entering information needed to close out WO (1new, 2apr, 2okts,3inprog, response complete) and supervisor/lead (4COMP) to review
Parents (Above) child stay in 1NEW the whole time and then 4COMP
What’s the purpose of 3FRCOMP? Is that because concrete is done and is pending asphalt? Yes, if it is a single asset then they will 4 comp it. Want to ensure everyone sees it.
Lead ensure that WO information is correct, Techs 1-3 and Leads focus is on specifications and ensuring everything is needed for the job while Supervisors review the information and 4comping it
They want to train everyone to do Maximo, not just supervisors/leads
Superintendent – 2APRS are assigned to him to schedule outwork, and final review 4comp closing
Coordinator - controlling from 1-4, either him or inspector are taking from 1new to 2apr
After putting in 2APR for inspector, goes back for review then placed in 2OKTS, then after it's ready to go it's handed to the crew for work
How does the inspector send it back? Are y’all still using 2APRHOLD? Yes
Are you still marking things by priority level? No, Austin Water handles that unless directed otherwise. Used to apply when they had a large backlog
- portlet exists for priority; mostly from office of director, but not used as much
Are you still looking at conflict portlets? Ryan Harding looks at it, still needed for use

**Comment by adry-martinez** [comment]
## Maximo Discussion about UER Road Map
### April 12, 2024 

Clay would like to improve CRC and Bridges process. 
Currently, CRC is using spreadsheets to track work orders. UER is set up to tell staff project statuses. 
His objective is to know project statuses: what's incoming, pending, completed and what is the cost-driver. 

CRC should be broken up to smaller issues/phases, currently they are recording on ONE work order to track a several months long projects. 

Target Finish may be considered. 
Out of 20, 2-3 child work orders/day. 
Wants to set up performance measure 

Parent - PROJECT (all Phases) by using Location, or Multiple Locations (Location 1 - 4) Actual Project Charter, Admin Costs, Inspections

Child - Phase 1 - Location 1 and multiple assets 
Child - Phase 2 - Location 2 and multiple assets
Child - Phase 3 - Location 3 and multiple assets
Child - Phase 4 - Location 4 and multiple assets

Wants report similar to UER to tell story about backlog 
will need to define what a backlog is.

Same roles and responsibilities as UER
Superintendent - conducts QA 
Supervisor - reviews and NFR 
Lead - data entry and COMP 

Brad gets work from e-mails, meetings, requests. There is no singular place to track all requests. Requesting to be done by Knack, to gather all project requirements and figure out how to move that to Maximo.

**Comment by adry-martinez** [comment]
## May 2, 2024

### 🤝 Participants
Mike D., Rene V., Rebekka, Diana

### 📄 Agenda

1. Introduce Rebekka
2. Discuss training session at end of month with Joe.
3. Any updates on Scofield Ridge

### 📓 Meeting Notes

1. Rebekka will be supporting and lead Maximo teams. Rebekka 
2. Issues with changing status. Striping not familiar. DTS PPT high level overview of USD, Rene will work with Mike D. 
3. None at this time

### ✅ Action Items

@rebekkabry will create new meeting series with same cadence.

**Comment by rebekkabry** [comment]
Agenda Prep: 
- Discuss Start Center Design #16532 - can we start by mirroring another workgroup or do we need to consider specifics?

**Comment by rebekkabry** [comment]
## 📆 June 6, 2024

### 🙋🏼 Participant(s)


### 📄 Agenda
- [ ] General Updates - _(bulletin board)_
      - New Training Resources and Link Access - [Maximo Sharepoint Landing Page URL](https://cityofaustin.sharepoint.com/sites/MaximoResources)
- [ ] Last Meeting Updates 
- [ ] SBO Ops Discussions 
  - Do you have a start center or do you share with other work group? #16534
- [ ] Issues Review, Recap, Insights (review updates and discuss specs, when applicable) 
  - Icebox 
    - #16954 - what start center to add to? CONC?
  - In Progress 
     - #17309 _in queue with Ganesh_
     - #16781 _What further actions are needed here?_ 
 - [ ] Q/A Report @ReneVarg25 
   -  #13764

**Comment by rebekkabry** [comment]
## 📆 Date

### 🙋🏼 Participant(s)


### 📄 Agenda
- [ ] General Updates - _(bulletin board)_
      - New Training Resources and Link Access - [Maximo Sharepoint Landing Page URL](https://cityofaustin.sharepoint.com/sites/MaximoResources)
- [x] Last Meeting Updates 
- [x] SBO Ops Discussions 
- [x] Issues Review, Recap, Insights (review updates and discuss specs, when applicable) 
   - In Q/A 
      -  #16534 
      - #17309
      - #17580
        - [ ] #17669 Discuss which workgroups this needs to be communicated to? And who will send out communication?  ❓ 
    - Completed/Resolved
      -  #16954 
     - In Progress 
        - none currently 
   - Icebox 
      - #16781
 - [ ] Q/A Report @ReneVarg25 
   -  #13764


### ✅ Action Item/s
**DTS Maximo**

**USD Ops**

**Comment by rebekkabry** [comment]
## 📆 August 1, 2024

### 🙋🏼 Participant(s)


### 📄 Agenda
- [ ] General Updates - _(bulletin board)_
   `- what would be useful information in a recurring monthly newsletter, if any?`
- [ ] Last Meeting Updates 
- [ ] SBO UER Ops Discussions 
- [ ] Issues Review, Recap, Insights (review updates and discuss specs, when applicable) 
   - In Q/A or completed 
        - [ ] #17309
        - [ ] #17669 Discuss which workgroups this needs to be communicated to? And who will send out communication?  ❓ 
    - Completed/Resolved
      -  #16954 
     - In Progress 
        - none currently 
   - Icebox 
      - #16781
 - [ ] Q/A Report @ReneVarg25 
   -  #13764


### ✅ Action Item/s
**DTS Maximo**

**USD Ops**

**Comment by rebekkabry** [comment]
## 📆 August 1, 2024

### 🙋🏼 Participant(s)


### 📄 Agenda
- [ ] General Updates - _(bulletin board)_
- [ ] Last Meeting Updates 
- [ ] SBO UER Ops Discussions 
      -   FY25 Preparation Needed? 
      - #18276 Discussion with Brad on how UER handles work orders when sent to SBOCON. What are the data points for each service type? How does your crew handle large projects with multiple assets?
- [ ] Issues Review, Recap, Insights (review updates and discuss specs, when applicable) 
   - In Q/A or completed 
        - [x] #17309 `(completed)`
        - [x] #17669 `Discuss which workgroups this needs to be communicated to? And who will send out communication?  ❓` 
        - [x] #16954 `(complete)`
     - In Progress or New
        - [ ] #18899 - GIS Solution of CONC Work Order statuses
   - Icebox / Backlog (pending mapping and CONC/Sidewalk documentation)
        - [ ] are you currently using a start center? `workgroup, crew, etc?`
        - [ ] #16781 `any follow ups needed`
 - [ ] Q/A Report @ReneVarg25 
   -  #13764


### ✅ Action Item/s
**DTS Maximo**

**USD Ops**

**Comment by rebekkabry** [comment]
# October 3, 2024 

- Reviewed issues in Github, currently only 1 open pending project builder huddle with DTS 
- Reviewed Data Quality Work Order Report 🎆 have 0 work orders on any page in the report 🩵

**Comment by rebekkabry** [comment]
# 1/2/24 


- **Any Updates from USD?** 
- Any EOY, BOY needs? 
- Flex Field 2 review?

**Comment by rebekkabry** [comment]
# 1/7/26 
- review the current Power BI [Link](report https://app.powerbigov.us/groups/c78e625c-c676-4727-9d5b-b5f0565ee975/reports/864c4d66-0ded-4d1a-b456-2620e22daa81/ReportSection3b681fe1d6377c66798b?ctid=5c5e19f6-a6ab-4b45-b1d0-be4608a9a67f )
- worked with Nick in ATS to review the number variations. Appears the day counts by the hour are slightly different. Only about ~5 work order difference today on total. 
Current: 
ATS    DTS
875    880
467    472
* most differences found in Oct 2025 COACreate Date count 

Query from Maximo per Nick: 
```

SELECT DISTINCT 

    parentwo.altref,

    parentwo.coa_createdate AS woincomingdate,

    wospeccont.alnvalue AS contractor,

    woaddr.DESCRIPTION AS serviceaddress,

    wospeczone.alnvalue AS zone,

    NVL(LOCSPEC.alnvalue, 'NOT ENTERED') AS mapsco_grid,

    parentwo.wonum AS bklogwonum,

    parentwo.DESCRIPTION AS description,

    parentwo.status,

    parentwo.statusdate AS statusdate,

    parentwo.reportdate AS woreportdate,

    parentwo.wopriority AS wopriority,

    parentwo.worktype AS worktype

FROM maximo.workorder parentwo

LEFT OUTER JOIN maximo.LOCATIONSPEC LOCSPEC 

       ON LOCSPEC.LOCATION = parentwo.LOCATION 

      AND LOCSPEC.ASSETATTRID = 'MAPSCO_GRID'

LEFT OUTER JOIN maximo.WORKORDERSPEC wospeczone 

       ON parentwo.wonum = wospeczone.wonum 

      AND wospeczone.assetattrid = 'ISSUES_FOUND'

LEFT OUTER JOIN maximo.WORKORDERSPEC wospeccont 

       ON parentwo.wonum = wospeccont.wonum 

      AND wospeccont.assetattrid = 'SUGGESTED_REPAIR'

LEFT OUTER JOIN maximo.woserviceaddress woaddr 

       ON parentwo.wonum = woaddr.wonum

WHERE parentwo.ALTREF IS NOT NULL

  AND parentwo.coa_createdate BETWEEN DATE('2025-10-02') AND DATE('2025-12-31')   -- 90-day window

  AND parentwo.persongroup = 'SBOUTIL'

  AND parentwo.siteid = 'SBO'

  AND parentwo.CLASSSTRUCTUREID LIKE 'INV_UTILITY_EXCAVATI%'

  AND parentwo.parent IS NULL

  AND parentwo.altref NOT IN (

        SELECT DISTINCT parentwo.ALTREF AS completedwobeforeenddt

        FROM maximo.workorder parentwo

        INNER JOIN maximo.wostatus wost 

                ON parentwo.wonum = wost.wonum

               AND wost.SITEID = 'SBO'

               AND wost.status IN ('5CLOSED','4QACOMP','4COMP-ND','5CANCEL')

               AND parentwo.SITEID = 'SBO'

        LEFT OUTER JOIN maximo.workorder childwo 

               ON parentwo.wonum = childwo.parent

        WHERE parentwo.coa_createdate BETWEEN DATE('2025-10-02') AND DATE('2025-12-31')   -- 90-day window

          AND parentwo.STATUS IN ('5CLOSED','4QACOMP','4COMP-ND','5CANCEL')

          AND (0 = (

                SELECT COUNT(*) 

                FROM maximo.workorder childwo1

                WHERE childwo1.status IN (

                      '1NEW','2APR','2APRHOLD','2OKTS','2PMSKIP','2RTA','2RTW',

                      '3FR','3FRCOMP','3INPR','3INPRSR','3WRKHOLD','4COMP',

                      '4COMP-NFR','4QAREJ')

                  AND childwo1.parent = parentwo.wonum

                  AND childwo1.siteid = parentwo.siteid

              ))

          AND parentwo.SITEID = 'SBO'

          AND parentwo.persongroup = 'SBOUTIL'

          AND parentwo.CLASSSTRUCTUREID LIKE 'INV_UTILITY_EXCAVATI%'

          AND parentwo.parent IS NULL

          AND parentwo.ALTREF IS NOT NULL

          AND parentwo.wonum IN (

                SELECT DISTINCT wonum

                FROM maximo.wostatus wost1

                WHERE wost1.SITEID = 'SBO'

                  AND wost1.STATUS IN ('5CLOSED','4QACOMP','4COMP-ND','5CANCEL')

                GROUP BY wost1.wonum

                HAVING MAX(wost1.changedate) BETWEEN DATE('2025-10-02') AND DATE('2025-12-31')   -- 90-day window

          )

  )

ORDER BY parentwo.coa_createdate;
```

**Comment by rebekkabry** [comment]
# 4/1/26 

- reviewed the auto naming of children work orders, ATS resolution in progress 
- Open Data Portal - AWU needs to be refreshed. 
- update Power BI to have the filters as - have a meeting today at 1PM, will update and share.  
  - 0-30 day
  - 31-90
  - 91-180
  - 181 and above
- Reviewing Map Q/A
  - in progress with John and team
  - request to meet before next Thursday 
    - ER: can not see the queries of the work orders selected. 
    - Christina set mid Q/A with John to see what other scoping notes can be provided (in attempts of building a TEST schedule)
