### ISSUE TITLE
Maximo Discussions, USD Bridge 

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#16069]
### Objective 
This meeting is to discuss any ongoing Maximo projects and support for the Bridges work group.

**Comment by adry-martinez** [comment]
## Feb. 28, 2024

### Participants
Patti M., Rene V., Adriana M.

### Agenda
- Introduction to Maximo discussion meeting
- Discuss group's need from the Maximo team
- Adry OOO from 2/29 - 3/15
- Shared Maximo Bookings link

### Meeting Notes
_see Agenda_
- preference to keep Concrete and Bridges separate
- [ ] Potential Project: Figuring out how to classify large vs small bridges projects in Maximo

------

### Action Items:
**_Maximo team:_**
- [ ] review **Meeting Notes** for any issues to be created.

**_Bridges:_**
none at this time. 

Next meeting scheduled for **March 27, 2024**.

**Comment by adry-martinez** [comment]
### March 28, 2024

Participants 
Patti M., Clay R., Adriana M.

Meeting Notes 
Work Group assignment to reflect MORENOP and ELLISONJ for SBOBRIDGE and for SBOMOBTRL
Previously discussed when District Maintenance received a work order, a call from WPD cleaning out a culvert in the creek. Called in the broken bridge rail, no one has fixed it, forwarded over to Patti, District had been out there, put a cone and closed it; not forwarded to Bridge. Demo'd flex field 2. 

Calls received by different channels 
Want to have those calls counted using requesting agency 

Clay wanted a Concrete start center. Team to schedule meeting with Clay and Brad to discuss design. 
Clay needed assistance to update UER start center to see updated report list.

**Comment by adry-martinez** [comment]
## DATE

### 🙋🏼 Participant(s)


### 📄 Agenda


### 📓 Meeting Notes


### ✅ Action Item/s
**DTS Maximo**

**Bridge**

**Comment by adry-martinez** [comment]
## Date

### :handshake: Participants
**SBO**:
**DTS**:

### :memo: Agenda
1. 
2. 
3.

### :notebook: Meeting Notes
1.
2.
3.

### :white_check_mark: Action Items
**DTS Maximo**

- [ ] Task 1
- [ ] Task 2

**District Maintenance**

- Task 1
- Task 2

#### :calendar: Next meeting scheduled for DATE

**Comment by rebekkabry** [comment]
## May 29, 2024

### 🙋🏼 Participant(s)


### 📄 Agenda
- [ ] General Updates - _(bulletin board)_
- [ ] Last Meeting Updates 
    - Confirm combining Concrete/Asphalt meetings with Bridges or kept separate? _with Clay_
    - Review Large vs Small Details _with Patti_ #16070; show sample rating graphs. 
    - Review Needs for Start Center CONC _with Clay and Adry_; _meeting scheduled **6/4**_
    - Documenting Updates: PPT #17039; Schedule Documenting Meeting for Bridges #13542 
- [x] New Issues Review, Recap, Insights _(review updates and discuss specs, when applicable)_
  - no new issues
  - What groups should be included in our scope here: Bridges, CRC (concrete), ???)
- [x] Q/A Report Concerns - Rene _(backlogs, review Maximo)_
  - none reported by Rene
- [x] Stakeholder Feedback and Updates 
- [x] DTS Focus Areas _(if applicable and if time permits)_ 
      - MAXIMO Training Materials
      - Reporting Efforts 
      - Process Documentation 
- [x] Business Process Documentation Review DTS Records
     - MAXIMO User Process Discovery #16121 
     - [DTS Ecosystem Discovery Notes ](https://github.com/cityofaustin/atd-data-tech/issues/12893#issuecomment-1977142499)#12893 
     - New Training Resources and Link Access - [Maximo Sharepoint Landing Page URL](https://cityofaustin.sharepoint.com/sites/MaximoResources)
  

### 📓 Meeting Notes

    📝 Please see each above reference link for additional notes 📝 


### ✅ Action Item/s
**DTS Maximo**
- [ ] add Brad (SI over Concrete) and John P (UER) get them added to invite @rebekkabry - Discuss with DTS team on combining USD Discussions (Concrete, Bridges, CRC)
- [ ] Bridge Stakeholder Process Review and Discussion schedule 6/4? @rebekkabry

**Comment by rebekkabry** [comment]
## June 12, 2024

### 🙋🏼 Participant(s)


### 📄 Agenda
- [ ] General Updates - _(bulletin board)_
- [ ] Last Meeting Updates 
    - Review Large vs Small Details _with Patti_ #16070; show sample rating graphs. 
    - Documenting Updates: PPT #17039; Schedule Documenting Meeting for Bridges #13542 
- [ ] New Issues Review, Recap, Insights _(review updates and discuss specs, when applicable)_
  - no new issues
- [ ] Q/A Report Concerns - Rene _(backlogs, review Maximo)_
- [ ] Discussions
- [ ] Discussions 
   - Look at performance measure list
   - What performance measures currently reported up from BRIG?
   - BRIG data points that reflect long term project (mentioned by Dave last week)
- []  Stakeholder Feedback and Updates 
- [x] DTS Focus Areas _(if applicable and if time permits)_ 
      - MAXIMO Training Materials
      - Reporting Efforts 
      - Process Documentation 
- [x] Business Process Documentation Review DTS Records
     - MAXIMO User Process Discovery #16121 
     - [DTS Ecosystem Discovery Notes ](https://github.com/cityofaustin/atd-data-tech/issues/12893#issuecomment-1977142499)#12893 
     - New Training Resources and Link Access - [Maximo Sharepoint Landing Page URL](https://cityofaustin.sharepoint.com/sites/MaximoResources)
  

### 📓 Meeting Notes

    📝 Please see each above reference link for additional notes 📝 


### ✅ Action Item/s
**DTS Maximo**
- [ ] Bridge Stakeholder Process Review and Discussion schedule @rebekkabry 
- [ ] Update Performance Measures list for BRIG @rebekkabry [(on internal doc) ](https://cityofaustin-my.sharepoint.com/:x:/g/personal/rebekka_bryant_austintexas_gov/EUgLh3PSWQRBn5XU5H9gt4sBsTmUEobQf772JRnbTrYs9w?email=Rebekka.Bryant%40austintexas.gov&e=ntjJCb)

**Comment by rebekkabry** [comment]
## June 27, 2024

### 🙋🏼 Participant(s)


### 📄 Agenda
- [ ] General Updates 
- [ ] Last Meeting Updates 
    - [ ] none, need to focus on mapping process and understanding tracking tools. 
- [ ] In Progress/Focus Topics 
  - Bridge[ Mapping Questions](https://miro.com/app/board/uXjVK6yPCkM=/): 
     - What forms / tools used from pre create maximo work order? 
     - What do you get to notify you of a new bridge work? 
     - Can we walk through that process? 
     - Review Permitting Process
     - Review Priority Process (where do you find and notate these points) 
 - [ ] Business Process Documentation Review DTS Records
     - MAXIMO User Process Discovery #16121 
     - [DTS Ecosystem Discovery Notes ](https://github.com/cityofaustin/atd-data-tech/issues/12893#issuecomment-1977142499)#12893 
     - New Training Resources and Link Access - [Maximo Sharepoint Landing Page URL](https://cityofaustin.sharepoint.com/sites/MaximoResources)


### 📓 Meeting Notes

    📝 Please see each above reference link for additional notes 📝 


### ✅ Action Item/s
**DTS Maximo**
***USD: Bridge***

**Comment by rebekkabry** [comment]
Currently not using forms for tracking 
Create own work orders (some times through 311, or OCE - moving forward they will not be creating 
OCE - report from TXDOT bridges; moving forward BRD will review and decide which are made priority 
Work Group: 
Priority determined? - Ah Yong follow up
Large and Small currently determined by dolloar amount (not sure how we get there now, maybe over 5K  over a week)

**Comment by rebekkabry** [comment]
## August 7, 2024

### 🙋🏼 Participant(s)


### 📄 Agenda
- [x] General Updates 
- [ } Last Meeting Updates 
    - [ ] Review action items
- [ ] In Progress/Focus Topics - [SBO Discovery Map](https://miro.com/app/board/uXjVN7sxj9I=/)
  - Bridge[ Mapping Questions](https://miro.com/app/board/uXjVK6yPCkM=/): 
     - What forms / tools used from pre create maximo work order? 
     - What do you get to notify you of a new bridge work? 
     - Can we walk through that process? 
     - Review Permitting Process
     - Review Priority Process (where do you find and notate these points) 
 - [ ] Business Process Documentation Review DTS Records
     - MAXIMO User Process Discovery #16121 
     - [DTS Ecosystem Discovery Notes ](https://github.com/cityofaustin/atd-data-tech/issues/12893#issuecomment-1977142499)#12893 
     - New Training Resources and Link Access - [Maximo Sharepoint Landing Page URL](https://cityofaustin.sharepoint.com/sites/MaximoResources)


### 📓 Meeting Notes

    📝 Please see each above reference link for additional notes 📝 


### ✅ Action Item/s
**DTS Maximo**
***USD: Bridge***

**Comment by rebekkabry** [comment]
MIRO MAPPING OF CURRENT BRIDGE PROCESS 

https://miro.com/app/board/uXjVKksGZEo=/

**Comment by rebekkabry** [comment]
## September 4, 2024

### 🙋🏼 Participant(s)


### 📄 Agenda
- [x] General Updates 
- Last Meeting Updates 
    - [ ] Review action items
- [x] In Progress/Focus Topics - [SBO Discovery Map](https://miro.com/app/board/uXjVN7sxj9I=/)
  - [Bridge Miro Board Mapping ](https://miro.com/app/board/uXjVKksGZEo=/)
 - [ ] Review to add to Gitbook Business Process Documentation Review DTS Records
     - [ ] specifications tab. 
     - [ ] Any internal documents would like added? 
     - MAXIMO User Process Discovery #16121 
     - [DTS Ecosystem Discovery Notes ](https://github.com/cityofaustin/atd-data-tech/issues/12893#issuecomment-1977142499)#12893 
     - New Training Resources and Link Access - [Maximo Sharepoint Landing Page URL](https://cityofaustin.sharepoint.com/sites/MaximoResources)


### 📓 Meeting Notes

    📝 Please see each above reference link for additional notes 📝 

**Additional Questions**
BRIDGE_WORK - classification 
Types of Service Types: Materials required, specifications known for each? = what is being reported on for Bridges? 


### ✅ Action Item/s
**DTS Maximo**
- [ ] additional meeting with Patti for scoping and discussion of process. 
- [ ] Compare reporting to Q/A next meeting 

***USD: Bridge***

**Comment by rebekkabry** [comment]
# Meeting 11/21/24

- DIST to SBOBRIG to Flex Field 2
- Review Demo 
- Create Child in Demo

**Comment by rebekkabry** [comment]
# Discuss with Team
- confirm change wanted at problem or failure level: https://github.com/cityofaustin/atd-data-tech/issues/20322
- advised Colby of updates https://github.com/cityofaustin/atd-data-tech/issues/20192
![image](https://github.com/user-attachments/assets/3a7be549-1d3d-455c-ae9a-3cb3cea18a96)
- Review Start Center 
- Discuss Clean Up into Standardization 

```
Clay and Patti, 

We are beginning to document the clean up efforts of the SBOBRIG / OCE work ordering handling process. As a demo work order, we are using 22-141397, please advise if SBOBRIG has: 
-	Accepted work order for service – creation of child work order 
o	If you have created work on this work order for service. 
o	23-155602 appears to be another request submitted for BRIG work needed. 
-	Pending investigation completion – change in status
-	Needs to be closed and updated – change in status
-	Needs to be redirected back to OCE – change in status 


Please be advised we are still in the process of gathering the proper system to data capturing of: 
-	Bridge Asset ID (in progress with DTS and CTM) 
-	Specifications (pending by DTS to have added) 
```

**Comment by rebekkabry** [comment]
# 1/15/25 

### week of 1/2/25
- Together we reviewed and corrected the work order 
- [Recorded process ](https://cityofaustin-my.sharepoint.com/:v:/r/personal/rebekka_bryant_austintexas_gov/Documents/Media%20Files/Bridge%20Team%20for%20SBO_OCE%20Maximo%20WO-20250108_140302-Meeting%20Recording.mp4?csf=1&web=1&e=1fw7AT&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D)


TO DO: 
- [ ] work on scribing the process @rebekkabry

**Comment by rebekkabry** [comment]
# Notes until 12/6/25 
- see here https://github.com/cityofaustin/atd-data-tech/issues/13542

**Comment by rebekkabry** [comment]
# Notes up until 12/6/24
- see here https://github.com/cityofaustin/atd-data-tech/issues/13542

**Comment by rebekkabry** [comment]
# Notes until 12/6/24

**Comment by rebekkabry** [comment]
# 1/16/2025

OCE/Bridge


1.	Could you please update the “CLEAN UP (OCE or SBO Past Created)” portlet to only include WOs with the Work Group “SBOBRDGE”? It’s currently showing other SBO work groups, like our SBOIMG work orders.
- leave as is for now, 22-145920 in case they are meant for OCE/SBOBRIGE
- this portlet will not be used after the clean up efforts.

 
2.	The parent WOs that you made to denote Reactive vs Service Plan work are currently in the “SBOBRDGE” Work Group. I’m thinking of changing those work groups to “SBOIMG” so they don’t show up in the SBO bridge group’s to-dos. Thoughts on that before I make any changes?
- updating, edit workgroup

-----


1.	We should copy the “Favorite Applications” portlet/widget with two useful query links from the “SBO Bridge” dashboard to the new dashboard.
added these to the BRM dashboard. 
Favorite Applications
SBO Service Requests
SBO Work Order Tracking
 

2.	We should also add these three portlets copied from the “SBO Bridge” dashboard to the new dashboard:

Active Work Orders Owned by Me (I am OWNER)
Open Work assigned to me as Superintendent
Open Work that I Supervise
 
 

3.	After we finish clean-up for the current work orders, we should delete the two clean-up portlets on the new dashboard.
- yes, this will happen. 


4.	Once those changes are made, I think we’ll need to make an exact copy of this new dashboard and rename it “SBO BMMT.” The main reason is because we’ll need an additional portlet that only the OCE BMMT team can see. See numbers 5 & 6 below for more info.
-BMMT - Bridge Maintainence Management Team (apart of OCE/IMG)
-Portlet: shows workorders that are assigned to this new workgroup
SBOBRIG/SBOBMMT _ 
- added as a placeholder for now, until we start get 


5.	The SBOIMG work group is limiting for us, as it’s used by the OCE pavement team as well. For work requests like the ones that come through 311, we’ll need a new work group named SBOBMMT. This is the work group we’ll tell 311 and other teams to assign when they need bridge work. Then, we can review their requests and pass the work along to the SBO Bridge team if needed. It should end up looking like this:


- requesting to create a new work group
- previous BRIDGE/OCE Work orders will need to be updated? may not effect SBO and their reporting, bc it will still be tagged to SBOBRIG. 

 

6.	To go along with that new work group, we’ll need to add a portlet to the new “SBO BMMT” dashboard that shows any work orders assigned to the new “SBOBMMT” Work Group mentioned in item #
- already created a placeholder, pending workgroup creation for the query 


7.	When we’re very close to implementation, or shortly after, we’ll need to setup a few reports in the Report List for the new dashboard with the correct filters to help SBO & OCE run regular reports on our open & closed work orders. We can discuss this in more detail when it comes.
SBOBRDG Dash Board
SBOBRDG Repair Completed
SBOUTIL Concrete Crews Unit 8000 (Monthly Operational Performance Measures)


8.	For implementation, we’ll need documentation that detail our new workflows, which you’ve mentioned that you’re planning on starting soon Rebekka. Maybe we can start with a quick flowchart or outline first to make sure we’re on the same page about the workflows and various statuses?


TO DO: create an issues 
9*: still appearing in the clean up: 
- edit the query to remove any work orders that have the parent assigned as: 24-183241 for INVESTIGATION and 24-183240 for SERVICE  (@ganesh) 

2. copy the queries from SBOBRIG to BRM for the following portlets. 
Active Work Orders Owned by Me (I am OWNER)
Open Work assigned to me as Superintendent
Open Work that I Supervise

10* Update startcenter naming
BRUTM
Utrail work will come through John Eastmans group. Need to create a start center. 

4* - create an issue with CTM for creating a new persongroup: 
SBOIMG_BMMT --> Bridge Maintainence Management Team within OCE/IMG
Crew: n/a

5* Once new persongroup is created, create a query for the SBOIMG_BMMT Assigned Work Orders (OCE ONLY)

11*: OCE will communicate to 311/SBOTREE for the handling and usage of BMMT workgroup. 


24-174548

UER; ASPHALT STREET CUT INVESTIGATION 4510 BUCKS RUN AUSTIN
FUA  WESTLAKE DR @BEE CREEK (142270B01545002) (2) Guardrail repairs INV

INV BRIDGE NAME - SERVICE ADDRESS 
REPAIR BRM - REPAIR TYPE

**Comment by rebekkabry** [comment]
# To Do Updates - 
- CTM My Request - INC0464241 for new person group

**Comment by rebekkabry** [comment]
# Discuss Upcoming Meeting 
- how are tickets or will tickets be tagged from John Eastmans team for Urban Trails - portlet view? Do we need to set meeting to build out? 
-

**Comment by rebekkabry** [comment]
4/8/26 
- . We are still waiting on ATS MAS9 fixes for them to pick up the TXDOT specifications portlet. But they do have the placeholder portlet in place, reading all TXDOT workorders regardless of originator at the moment. Would like to know if that is working for them in the meantime? If not, we can schedule an scoping meeting to build out further insights support while we wait on ATS.

**Comment by rebekkabry** [comment]
# 6/10/26 
Attendees: Rebekka, Rene, Michael D, Patti

Topics: 
- ATS MAS9 issues still preventing upgrades
- Any 311 work orders typically come in? Yes they do get 311 orders. Do we need to see which work orders are not getting to the groups. Yes have not gotten anything from Monika or 311 for a few days. 
    -   311 - does typically send to SBO BRIG
- Any thing to look into for SBO side: not at the moment.

**Comment by rebekkabry** [comment]
# 7/7/26 

- consider "maintainence" for failure code GOAL: clear failure code error. Keep size;  CAUSE = MAIN 
- add to match >20'ft Bridge type option 
- service address / locations = request to clear pass 200 to clean manually. 

<img width="544" height="317" alt="Image" src="https://github.com/user-attachments/assets/f7f2ad1a-feea-4706-89a8-4556e2258dac" />

<img width="397" height="234" alt="Image" src="https://github.com/user-attachments/assets/2486c64c-3cc9-4936-ad24-f4211c921910" />


26-213436 test and removed

**Comment by rebekkabry** [comment]
# 7/15/26 
- ATS ticket submitted https://github.com/cityofaustin/atd-data-tech/issues/29369
