### ISSUE TITLE
[Enhancement] Build manual Service Request entry in SMRT

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#16074]
## Description
Build out the functionality in SMRT to allow for manual entry of micromobility service requests.

#### Tasks
- Create build notes
- Review existing PEP service request fields to determine what should be included in SMRT

**Comment by dianamartin** [comment]
# 2/29/24

## New Meters Issue Type
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/1cbc99bb-5898-40f5-8c93-6c3d2ef27849)

## New SR (Enforcement Services)
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/30f6ecef-0d7d-4702-a20e-8b4fd1bed715)

### Complaint Type - drop down
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/ca42bdea-13c0-4021-98ed-330109081ca9)

**Comment by dianamartin** [comment]
# 3/1/2024
- [x] Added a link on the PEP "My Assignments" page, can only be seen by me and Shavyvonne for now
- [x] Added a "Back to My Assignments" button so PEO can go back quickly

**Comment by dianamartin** [comment]
# 3/4/2024
- Synced with Patrick and I showed him this new form
- [x] Submitted a test SR, there were a few kinks I had to address
- [x] Added the field that needed to be showing, removed a duplicate field
- [x] Created "Details" page
- [ ] Configure "Details" page
- [ ] Need to have "ID/SR" field populate

**Comment by dianamartin** [comment]
# 3/5/24
- [x] Configure "Details" page
- [x] Create "Activity" form
- [x] Need to have "ID/SR" field populate

**Comment by dianamartin** [comment]
# 3/20/24
- [x] Configured Email for Provider
- [x] Added "Provider Email" on the `provider` table
- [x] Populated with my email address
- [x] Tested email notification
- [x] Email worked!
- [x] Updated "Activity" form with 3 record rules
- [x] Added link to Service Requests (SRs assigned to a Provider)
- [x] Updated "Status" colors of Service Requests table (for Provider)

**Comment by dianamartin** [comment]
# 3/21/2024
Showed stakeholders updates at `Micromobility SR process improvement` meeting, then created feedback updates here #16381.
