### ISSUE TITLE
Update SMD Reimbursables Socrata Dataset with new fields

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#16089]
- Discussed with SMD that once we finish the enhancements from this reimbursable process revamp, we will need to add/remove fields from the Reimbursables socrata dataset and republish

**Comment by ChristinaTremel** [comment]
- Moved this to the epic #17228 because additional fields are being added for this process enhancement as well. Will update the Socrata dataset when all changes have been made to the process.

**Comment by ChristinaTremel** [comment]
After looking at the API views, I realized it would be easier to merge two API views into a single one
### API clean-up
- Rename to `reimburseable_trackings - Markings` API view ([view_3527](https://builder.knack.com/atd/signs-markings/pages/scene_1249/views/view_3527/table)) to `reimbursable trackings`
   - Remove filter for `work_order_markings` is not blank
- Delete  `reimburseable_trackings - Signs` API view ([view_3526](https://builder.knack.com/atd/signs-markings/pages/scene_1249/views/view_3526/table))

### Fields to Keep on API View
- RT_ID
- Materials
- COA_Labor
- Contract_Labor
- Invoice_Amount
- Bond
- Submitted_Div_Dept_Approval
- Reimbursement_Processed_by_Finance
- Disassociated From
- Modified Date

### Fields to Remove 
(Note: source is from signs work orders but now exists on reimbursable object)
- [ ] ATD_WORK_ORDER_ID (SIGNS)
- [ ] WORK_TYPE
- [ ] LOCATION_NAME

### Fields to Add
- [ ] work_orders_sign
- [ ] work_orders_markings
- [ ] Work Order ID
- [ ] Requester ID
- [ ] Work Order Status
- [ ] Work Type 
- [ ] Location
- [ ] CIP
- [ ] TK
- [ ] FDU
- [ ] Is this Reimbursable
- [ ] Too Small
- [ ] Reimbursable Status
- [ ] Invoice Date
- [ ] Submitted for SMD Review
- [ ] Contract Labor Vendor
- [ ] Contractor Labor Invoice and Date
- [ ] Labor Invoice Date
- [ ] Sent to Requester Date
- [ ] Approval Status
- [ ] Finance Approval Status
- [ ] Invoice Approved Date
- [ ] Date Sent to Finance
- [ ] JV Number
- [ ] Comments

**Comment by KaroEngstrom** [comment]
## Mon 3/17/25
* made the updates indicate above 
* added a notice to the EDP asset description and we need to remove this when everything is ready: 
![Image](https://github.com/user-attachments/assets/ea4595ef-36cc-4be0-9ff9-11e16531220f)
* this is ready for the schema changes updates by dev

**Comment by KaroEngstrom** [comment]
Also, I'm not sure who created the original column level metadata but now there are new fields that need descriptions: 
![Image](https://github.com/user-attachments/assets/bbd3d4b1-bac2-4e0a-a9a9-d766a8149544)

Maybe @susannegov can help? :)

**Comment by KaroEngstrom** [comment]
## Tue 3/18/25 
- planning to move this to its own scene (page) today and we want to move forward with individual pages like in AMD. This helps the builders not have to locate the correct table after every save, reducing build time and potential for errors.

**Comment by ChristinaTremel** [comment]
Closing this out as complete and will schedule the dev work on this socrata dataset!
