### ISSUE TITLE
Updates to `Edit Reimbursable` and process for sending invoice to "Needs Review"

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#16091]
### Create fields on `reimbursable_tracking` object: 
- [x] `Not Reimbursable` yes/no field to flag if it’s not a reimbursable
- [x] `Under 30` Yes/No field
- [x] `Submitted for SMD Review` date field
   - Populate with dates from `Submitted_PE_PM_for_Approval`
   - Any additional info should move to Comments field
   - At that point we can delete `Submitted_PE_PM_for_Apprval` field
- [x] Created field for Johnny to capture if it is a reimbursable, not a reimbursable, or under the $30 threshold for invoicing
   - Default to `Yes, this is a reimbursable` 

### Record rules on `Edit Reimbursable` form
- [x] Record rule populate `Under 30` field with Yes if `Invoice Amount` is less than $30
- [x] Record rule to capture current date on `Submitted for SMD Review` when form is filled out and submitted

### [Invoice Details](https://atd.knack.com/signs-markings#reimbursements/signs-reimbursements/invoice-details-signs/65cd3e6651e02a00293d3545/) page changes
- [x] Add method for Johnny to update the status of the reimbursable record by capturing:
   - Yes, this is a reimbursable
   - No, this is not a reimbursable
   - No, the Invoice Amount is under $30

**Comment by ChristinaTremel** [comment]
- Susanne and I will work on this 3/7

**Comment by ChristinaTremel** [comment]
### Create fields on `reimbursable_tracking` object: 
- [x] `Not Reimbursable` field to flag if it’s not a reimbursable
   - Created yes/no field with checkbox input
- [x] `Under 30` Yes/No field - field called `Too Small` already exists
   - Conditional rule is if Invoice Amount is is lower than $30.01, mark as yes
- [x] Add `Reimbursable Status` for "Not Reimbursable"
   - If `Under 30` is yes
   - If `Not Reimbursable` is yes
- [ ] `Submitted for SMD Review` date field
   - Populate with dates from `Submitted_PE_PM_for_Approval`
   - Any additional info should move to Comments field
   - At that point we can delete `Submitted_PE_PM_for_Apprval` field

![image](https://github.com/cityofaustin/atd-data-tech/assets/61209591/2c858ba1-54c5-4bda-b21b-7e4368058f9b)

### Record rules on `Edit Reimbursable` form
- [x] Record rule populate `Under 30` field with Yes if `Invoice Amount` is less than $30
- [ ] Record rule to capture current date on `Submitted for SMD Review` when form is filled out and submitted

### [Invoice Details](https://atd.knack.com/signs-markings#reimbursements/signs-reimbursements/invoice-details-signs/65cd3e6651e02a00293d3545/) page changes
- [ ] Add button and form for `Not Reimbursable`
   - `Not Reimbursable` check box and `Comments` field to show on the form to capture notes about why this isn't a reimbursable
   - If `Not Reimbursable` is yes, we will need to create a status that removes this from the reimbursable process

### Additional Testing
- Need to figure out how to change a record from Not Reimbursable to Needs Review if the cost increases

**Comment by ChristinaTremel** [comment]
# Work Session 3/25

**Comment by susannegov** [comment]
Test work order: SGN22-100180

**Comment by susannegov** [comment]
# Bug note
When updating the material and it is a whole number. the record rule gets ignored. However if you submit it twice, the materials cost adds a decimal and the record rule goes through

**Comment by susannegov** [comment]
# 4/4
- Changed `Not Reimbursable` yes/no to `Is this reimbursable` multichoice
- Changed record rules
- Changed display rules

**Comment by ChristinaTremel** [comment]
## Work Session with Susanne
- We tested the process using the multiple choice options on the Edit Reimbursable form and everything was updating correctly
   - multichoice options
      - Yes, this is a reimbursable
      - No, this is not a reimbursable
      - No, the Invoice Amount is under $30
- [x] Create `Submitted for SMD Review` date field
   - [] Populate with dates from `Submitted_PE_PM_for_Approval`
   - [ ] Clean up additional info and move to Comments field
   - [ ] At that point we can delete `Submitted_PE_PM_for_Apprval` field
- Updated links on reporting pages to direct to `Reimbursable Tracking` page

**Comment by susannegov** [comment]
@ChristinaTremel we can close this right?

**Comment by ChristinaTremel** [comment]
This was completed and reviewed with SMD!
