### ISSUE TITLE
[Tech Services] TPW PC Refresh Checklist - [Anne, Milne]

### ISSUE THREAD

**Issue by JBStrange** [cityofaustin/atd-data-tech#16118]
## Steps
- [x] Talking to user about backing up their computers
- [x] Recommend user to export all bookmarks and store on OneDrive>Documents folder
- [ ] Recommend user to screen shot their ex, Quick Access favorites folder, desktop files layouts, pinned applications on desktop 
- [x] Store other OneDrive>Documents folder
- [x] Check their Absolute/NetMotion profile (they need to be in TRN SAML profile)
>Ask if they access AMD traffic cameras?

## Software Checklist
- [x ] Avaya one-X phone 
- [x ] Adobe
- [x ] ArcGIS 
- [x ] AutoCAD/AutoCAD Lite
- [x ] BlueBeam 
>if user wants both (Adobe & BlueBeam), ask why?
- [ ] SketchUp 
- [ ] MS Project
- [ ] MS Visio

## Hardware Checklist
Check these devices for outdated models, change their mobile power adapter (round --> USB-C)
>Does the user need a GIS Modeling computer?
- [ ]  GIS Laptop w/ specialist docking station
- [x ]  Laptop
- [x]  Power supply
- [ ]  Docking station

**Comment by JBStrange** [comment]
End User was having issues with software upgrades off older PC freezing and clicking sounds was fix once given a new PC.
