### ISSUE TITLE
Update "Journal Voucher" info in AMD Data Tracker - Warehouse Inventory- March 2023

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#16148]
- [x] Spreadsheet emailed from Finance staff month of: February, 10/2/23 through 2/27/24
- [x] Number of records being updated: 597
- [x] Format spreadsheet [(Review instructions)](https://atd-dts.gitbook.io/atd-knack-operations/warehouse-inventory-updating-journal-vouchers-jv-information)
- [x] Spot check Transaction IDs, no JV information before import: 35767 ✅ 
- [x] Import records
- [x] Spot check Transaction IDs, does have JV information after import: 35767
- [x] Email Finance staff that update task complete
