### ISSUE TITLE
Assist with Bulk AMD Inventory Requests PDF creation for CAMPO

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#16177]
### Request Info
- Brian C talked to Diana about PDF export and emailed her today: 
> As I mentioned yesterday. I am looking for an easy way to bulk print hundreds of PDF of the Request Details. We have a list of all of the Work Tickets. For each work ticket we want to print the Request Details page. For WRK22-148180

> This would be the attached which is from the following page: https://atd.knack.com/amd#inventory/inventory-request-details/629776c1cba2190021c3467a/

> I am hoping we can find away to make this as easy as possible since it will be very repetitive.
Campo is now saying that they need this info by March 12th. In addition to the CommTickets we also have one for CCTV and Detection though not quite as large.

 ### Action Items
- Brian provided a list of work orders that he's needing to export - `460` records
- Export copy of `work_order_signals` object as backup
- We will create a new field called `CAMPO PDF`
   - Populate with "Yes" if it's a work order included on the spreadsheet
- Copy the `Inventory Request` table on a new page for this process
   - Filter for `CAMPO PDF` is Yes

**Comment by ChristinaTremel** [comment]
### Notes
- [x] Export copy of work_order_signals object as backup
- [x] Create new field called `CAMPO PDF`
- [x] Created new page called `Bulk Export Campo PDF`
- [x] Copy the Inventory Request table onto  `Bulk Export Campo PDF` page for this process
- [ ] Import and update `CAMPO PDF` with "Yes" if it's a work order included on the spreadsheet
- [ ] Filter for `CAMPO PDF` is "Yes"

**Comment by dianamartin** [comment]
# 3/7/24
- [x] Emailed Brian
>Hi Brian, 

>I worked on the page for the “[Bulk Export Campo PDFs](https://atd.knack.com/amd#bulk-export-campo-pdf/?view_4031_filters=%5B%7B%22field%22%3A%22field_4734%22%2C%22operator%22%3A%22is%20not%22%2C%22value%22%3Atrue%7D%5D)” and was able to import in the spreadsheet you provided. I tagged the work orders that were on your list to be “CampoPDF” is “Yes” and then filtered the table that way. You’ll see a “PDF QC” field that is inline editable to track what you’ve PDF’d. 

>Here are the best steps to do this efficiently: 
### Steps to Instruct Users
>- Navigate to [Bulk Export Campo PDFs](https://atd.knack.com/amd#bulk-export-campo-pdf/?view_4031_filters=%5B%7B%22field%22%3A%22field_4734%22%2C%22operator%22%3A%22is%20not%22%2C%22value%22%3Atrue%7D%5D) (Viewer permission level required)
>- Click into “Work Order Details” page on table
>- Copy large “Work Order ID”
>- Click “Print”, update destination to "Save as PDF", and update Zoom settings to "75%" (portrait)
>- Click “Save”
>- Paste “Work Order ID” as the file name
>- After saving, update the “PDF QC” field on the table to "Yes"
>  - Once that field is updated, it will filter out of the list 

>_Let me know if you have any access problems with this._

**Comment by dianamartin** [comment]
# 3/8/24
Brian emailed back and asked
>Thanks Diana. Is it possible to modify it so that when I double click on the  work order that it selects the entire Name. right now it selects either the WRK part , the “-“ part or the numbers at the end. For the PDF name, we can certainly do with out the hyphen it that helps at all.

**Comment by dianamartin** [comment]
# 3/11/2024
BC emailed
>Diana,
I believe this is the final list of work tickets. Please upload to the “Bulk Data Module list”. 
>- It would help if I included the spreadsheet. 
- [x] Downloaded spreadsheet
- [x] Renamed `20240311_WorkTickets` from `WorkTickets`
- [x] Reviewed spreadsheet, there were `544 records`
- [x] Confirmed with BC that they were different WOs, so to clear out the old tagged ones an reimport
- [ ]

**Comment by ChristinaTremel** [comment]
We reviewed this with AMD during a previous sprint review. Closing this!
