### ISSUE TITLE
Please add privileges to myself and Lance Ballard and Samir Slee to this link: 

https://atd.knack.c...

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#16207]
> What application are you using?

AMD Data Tracker

> Describe the problem.

Please add privileges to myself and Lance B. and Samir S. to this link: 

https://atd.knack.com/amd#inventory/?view_2698_filters=%5B%5D

> Describe the outcome you'd like to see when this feature is implemented.

Able to use personal Data Tracker link: https://atd.knack.com/amd#inventory/?view_2698_filters=%5B%5D

> Describe any workarounds you currently have in place or alternative solutions you've considered.

None

> Is there anything else we should know?

ASAP

> Requested By
Allyson R.

Request ID: DTS24-113320

#### Initially Requested Users
- [x] Allyson
- [x] Lance
- [x] Samir

#### Add Additional Users
- [ ] Erin B. - _already has "Inventory Editor"_
- [x] Gus C.  
- [ ] Blake D. - _already has "Inventory Editor"_
- [ ] Jorge G - _already has "Inventory Editor"_
- [ ] Harrell M. - _already has "Inventory Editor"_
- [ ] Jonathan P. - _already has "Inventory Editor"_
- [x] Chris R. 
- [x] Markus R. 
- [x] Faith T. 
- [ ] Toby T. - _already has "Inventory Editor"_

**Comment by dianamartin** [comment]
# 3/12/2024
BC messaged me
>I was trying to adjust Allyson's permission so she can help with the tickets, but I don't see an option to adjust. I think it is inventory editor that is needed to see the Inventory Request page. 

I said
>I can adjust it
