### ISSUE TITLE
[SMD] Update Hardware backend

### ISSUE THREAD

**Issue by susannegov** [cityofaustin/atd-data-tech#16222]
- [x] Add `modified By` and `Modified Date` to `hardware` object
- [x] Update record rule when adding new hardware
- [x] Change `Work Group` multi-choice "SMB" to "SMD"
- [x] Batch load the 6 iPads
