### ISSUE TITLE
Labor rates restructure in the Test SMD Data Tracker

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#16243]
### Builder Huddle Findings: 
- AMD Example: Need to create something similar to [`inventory_item_unit_costs`](https://builder.knack.com/atd/amd/schema/list/objects/object_197/fields) (call it `asset_item_unit_costs`) for labor costs tracking
- RPP Example: they locked in the value. When an invoice was generated you can have a separate field to lock in the value. 

### Testing
- Created `asset_item_unit_costs` object
- Added fields: 
   - `UnitCostHistory_ID`
   - `Unit Costs`
   - `Employee Type`
   - `Status`
   - `Created Date`
   - `Display Name`
 - Created new `Hourly Rate` field in the `invoice_items` object
 - Need to finish testing but we determined that we want to move forward with structuring this similarly to AMD Data Tracker to prepare for inventory in the future.
 
### Labor rates existing previously in the SMD Data Tracker:
- Technician – Direct: `$41.47`
- Technician – Direct OT: `$62.21`
- Technician – Indirect: `$90.43`
- Technician – Indirect OT: `$135.65`
- Superintendent/Engineer/Division Manager – Direct: `$62.38`
- Superintendent/Engineer/Division Manager – Direct OT: `$93.57`
- Superintendent/Engineer/Division Manager – Indirect: `$140.24`
- Superintendent/Engineer/Division Manager – Indirect OT: `$210.36`

### Labor rates to update in the SMD Data Tracker:
- Technician – Direct: `$44.94`
- Technician – Direct OT: `$56.65`
- Technician – Indirect: `$104.58`
- Technician – Indirect OT: `$146.11`
- Superintendent/Engineer/Division Manager – Direct: `$67.23`
- Superintendent/Engineer/Division Manager – Direct OT: `$90.08`
- Superintendent/Engineer/Division Manager – Indirect: `$162.07`
- Superintendent/Engineer/Division Manager – Indirect OT: `$232.34`

**Comment by ChristinaTremel** [comment]
### Testing
- [ ] Created `asset_item_unit_costs` object
- Added fields: 
   - [ ] `UnitCostHistory_ID`
   - [ ] `Unit Costs`
   - [ ] `Employee Type`
   - [ ] `Status`
   - [ ] `Created Date`
   - [ ] `Display Name`
 - [ ] Created new `Hourly Rate` field in the `invoice_items` object
 - [ ] Need to finish testing but we determined that we want to move forward with structuring this similarly to AMD Data Tracker to prepare for inventory in the future.

**Comment by ChristinaTremel** [comment]
## 6/28
### `inventory_item_unit_cost` object creation
- [ ] Created `inventory_item_unit_costs` object
- Added fields: 
   - [ ] `UnitCostHistory_ID`
   - [ ] `Unit Costs` - number
   - [ ] `Employee Type` - mult-choice
   - [ ] `Status` - mult-choice
   - [ ] `Created Date` - datettime
   - [ ] `Display Name` - (Unit Cost) | [(FY) | (Employee Type) - field calculation
   - [ ] FY - multi-choice
- [ ] Added new labor rates and previous labor rates to the `asset_item_unit_costs` object
   - PREVIOUS prices
      - Technician – Direct: `$41.47`
      - Technician – Direct OT: `$62.21`
      - Technician – Indirect: `$90.43`
      - Technician – Indirect OT: `$135.65`
      - Superintendent/Engineer/Division Manager – Direct: `$62.38`
      - Superintendent/Engineer/Division Manager – Direct OT: `$93.57`
      - Superintendent/Engineer/Division Manager – Indirect: `$140.24`
      - Superintendent/Engineer/Division Manager – Indirect OT: `$210.36`
   - NEW prices
      - Technician – Direct: `$44.94`
      - Technician – Direct OT: `$56.65`
      - Technician – Indirect: `$104.58`
      - Technician – Indirect OT: `$146.11`
      - Superintendent/Engineer/Division Manager – Direct: `$67.23`
      - Superintendent/Engineer/Division Manager – Direct OT: `$90.08`
      - Superintendent/Engineer/Division Manager – Indirect: `$162.07`
      - Superintendent/Engineer/Division Manager – Indirect OT: `$232.34`
#### `invoice_items` object updates
- [ ] Created connection field `asset_item_unit_cost`
- [ ] Created `Hourly Rate NEW` field in the invoice_items object
- [ ] Create the `Hourly Rate Currency Field`
- [ ] Create `Hourly Rate Decimal Field 

#### Add Invoice Item Form updates
- [ ] Added `asset_item_unit_cost` field and added filter for FY
   ![image](https://github.com/cityofaustin/atd-data-tech/assets/61209591/27fb46e3-11f0-4c6d-ab97-2f2a4b750c6c)

**Comment by ChristinaTremel** [comment]
This was completed and reviewed with SMD during their sprint review in July!
