### ISSUE TITLE
[SMD] Duplicate "Section of Road" and "NORTH" when creating new markings work orders

### ISSUE THREAD

**Issue by susannegov** [cityofaustin/atd-data-tech#16281]
**Describe the bug**
![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/398fda13-cbaf-4490-9663-c0c0c988fd1d)

**URL**

**What steps can we follow to reproduce the bug you are seeing?**
1. Go to https://atd.knack.com/signs-markings#new-work-order-markings/
2. Click on `Location Type` and `Area`

**Screenshots**
![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/e3428bfb-2e38-45b8-a96b-2d7af40f4728)

![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/6b496998-91be-48cd-91bd-5fe03bdd6d8a)

**Device**
All devices

**Browser**

**How would you rate the impact of this issue?**
- [x] Minor  — can perform work, but could be easier or faster

**Additional context**
I found this when trying to make test work order record.

**Comment by susannegov** [comment]
# To  do
- [ ] Update `Section of road` to `Section of Road` (55 records)
- [ ] Remove `Section of road` option in `LOCATION_TYPE`

**Comment by susannegov** [comment]
Confirmed that creating new work orders no longer have duplicate options. It is good to close.
