### ISSUE TITLE
Find Model WO per Work Group in MAXIMO

### ISSUE THREAD

**Issue by rebekkabry** [cityofaustin/atd-data-tech#16288]
**Background** 
As we review the MAXIMO training materials, we would like to reference examples of ideal "model" work orders per each work group. 

**Objective** 
Find Model Examples of work orders for each work group, that can be added into the training material. The result of operational tracking is the completed work order that will detail the happenings of the activity.  Currently work order modeling is not used, mostly training on the expectations of how to complete the workorder/ticket. 

**Plan** 
Review MAXIMO records to find examples of completed work orders for each work group. 
These WOs will be included into the training material and library. 

**Resources** 
MAXIMO database 

**MVP Versions and Templates**
- 4/1/24 - [Sample Model WO Quick Guides](https://cityofaustin.sharepoint.com/:p:/s/tpwDTS/ETJM8Rye6FBMvrvsJGZyYYEBeeYOlrBhkWtkoUF0m7yx7A?email=Rebekka.Bryant%40austintexas.gov&e=PvRKhJ) 
![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/19cea02c-c0c8-43a4-a91b-db87c1971f57)

**Comment by rebekkabry** [comment]
- [ ] Find Work Order each work group 
- [ ] First 5 tabs are the same (WO, Plans, Actuals, Related WO) 
  - Naming convention: WO/Description/Location
  - Location and Service Addressed pulled from WO Name
  - Alt Reference: if work order comes from CSR from 311 
  - When Work Group is filled in (other tabs are prepopulated) 
  -  All other information in Responsibility comes from CSR
  -  Start and Finish - auto populated 
  -  Job Plan: or could be entered in PLANS tabs
       - Falls for the ACTUALS
       - All Work Order need labor material and tools 
       -  Different groups can set up a job plan: it is a controlled enviroment of resources and allocations for a particular team or project. 
  -   Specifications tab is different. 



Meeting Notes:

**Comment by rebekkabry** [comment]
Model Work Orders 

[SBO Maximo QRS Work Order Completion Checklist - District Maintenance.pdf](https://cityofaustin.sharepoint.com/:b:/r/sites/MaximoResources/Shared%20Documents/Quick%20Reference%20Sheets%20(QRS)/5%20-%20District%20Maintenance%20Maximo/SBO%20Maximo%20QRS%20Work%20Order%20Completion%20Checklist%20-%20District%20Maintenance.pdf?csf=1&web=1&e=k6zGGo&isSPOFile=1)

**Comment by rebekkabry** [comment]
**Question for next meeting/Next Meeting** Scheduled: 4/2 : Does the work order process operate the same for the mobile application? Should we consider reviewing the mobile application process for District Maintenance to gather the same documentation?

**Comment by adry-martinez** [comment]
> **Question for next meeting/Next Meeting** Scheduled: 4/2 : Does the work order process operate the same for the mobile application? Should we consider reviewing the mobile application process for District Maintenance to gather the same documentation?

@rebekkabry Yes! It is all the same between the desktop and mobile application

**Comment by rebekkabry** [comment]
**4/11/24 - Work Session** 

- [ ] Work on Pavement Model Work Orders 
- [ ] Look into the differences for each Pavement Sub Group (if applicable) (like Seal Coat, Level Ups, etc)

**Comment by rebekkabry** [comment]
### Pavement - Overlay _WO SP24-137272_

**Work Order Tab**

![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/83562e1c-66eb-4b6f-8198-4d7fccb07abe)

![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/2ac7af72-f7f4-4b67-bebb-d6e1847205d7)

**Actuals Tab**

![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/483f7c6d-6ec1-4931-9983-508de4d86354)

_Job Plan Used_ 
![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/7115299a-dd3b-4052-9492-8cacb71d8eb8)

_Labor_
![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/46a9ca39-054f-41bb-9553-575bc3b74882)

_Material_ 
![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/1128b461-7c49-47f1-9c9a-39b37e791249)

_Tools_ 
![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/d1080680-8faf-4906-833c-ac681a243a65)

**Specifications**
![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/be5dec09-5b13-40c8-bac5-72c883e1cc22)

![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/51dacfb2-b2ca-43e8-b778-1639aa139368)

![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/6fe0bbb4-0fb7-4764-95f4-cee3324ce92b)

![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/b3a8d776-584b-4008-9926-91ff6c91c7a8)


**Change Status** 

![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/59025e17-47a0-43a9-a631-574351475aa9)

![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/b01a0d45-adeb-40d3-9b16-8a6cc9eb5e3b)

**Comment by rebekkabry** [comment]
CSR Process 
- When citizen sees an issue on the street, they call it into 311 
- 311 then generates CSR to SR 
- SR goes into MAXIMO 
- in MAXIMO the Dispatch Team review and triage to appropriate Work Group 
- Dispatch assigns Work Order to Pavement Ops (for this example) 
- Pavement Start Centers shows a WO for triage 
   - Flex Field 2: used to generate work to another group, from being assigned to a group that does not support that asset. 
   - CSR: the process being defined here 
![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/04293337-cb39-4af8-8191-bcb940f57865)

**Comment by rebekkabry** [comment]
### Seal Coat 

**Operations** 

Work Order Tab
![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/739f6c79-a36a-4e49-91db-fcde4d1e8286)


**Actuals** 
![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/a3d8b50b-f1fe-4c7a-8686-23ffc5a20516)

**Specifications**
![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/6bf8a6ea-32c5-45db-bb8d-20ae040903f4)

**Comment by rebekkabry** [comment]
Failure Reporting - usually already populated for seal coat 
Log Note - not populated, need a manual by the user. 
 Q: Log Note Requirements; _Currently not listed on checklist_ @adry-martinez @rebekkabry follow up staff to see what needs to be in log notes 
![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/68e5b7a1-c0c1-422f-954d-6adaaf6a15c2)



![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/8981319b-163f-45f0-bbc9-05baf6fcef23)

**Comment by rebekkabry** [comment]
# 4/25/24

- Completed the CSR Work Order Completion Discussion 
- [Updated notes into Miro ](https://miro.com/app/board/uXjVN7sxj9I=/?moveToWidget=3458764587013797318&cot=14)


- [ ] Drafting new CSR Work Order - Dispatch Checklist 
- [ ] Meetings scheduled to complete Pavement Ops Work Order Updates

**Comment by rebekkabry** [comment]
Closing. 
We are working with each work order to establish work order handling needs for each service type and asset.
