### ISSUE TITLE
[SMD] Knack conditional rules showing blank custom/field values

### ISSUE THREAD

**Issue by susannegov** [cityofaustin/atd-data-tech#16290]
**Describe the bug**
The condition rule does not apply when the "Custom Value" or "Field Value" is showing blank, 

**URL**

**What steps can we follow to reproduce the bug you are seeing?**
1. Go to conditional rule

**Screenshots**
![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/870f43fc-448c-465b-89ef-3a439cc1ac82)

**How would you rate the impact of this issue?**
- [x] Major — can only perform work using a workaround

**Additional context**
See https://github.com/cityofaustin/atd-data-tech/issues/16277 where app behavior first noted

# To do
- [x] Checked `work_orders` related object tables
- [x] Checked `training` related object tables (they are not affected as far as I know)

# ON HOLD - do not do
- [ ] Check `csr issues` related object tables
- [ ] Check everything

**Comment by susannegov** [comment]
Closing this
