### ISSUE TITLE
[Tech Services] TPW PC Refresh Checklist - [Frank, G]

### ISSUE THREAD

**Issue by JBStrange** [cityofaustin/atd-data-tech#16321]
## Steps
- [ X] Talking to user about backing up their computers
- [X ] Recommend user to export all bookmarks and store on OneDrive>Documents folder
- [ X] Recommend user to screen shot their ex, Quick Access favorites folder, desktop files layouts, pinned applications on desktop 
- [x] Store other OneDrive>Documents folder
- [x] Check their Absolute/NetMotion profile (they need to be in TRN SAML profile)
>Ask if they access AMD traffic cameras?

## Software Checklist
- [X ] Avaya one-X phone 
- [ X] Adobe
- [ ] ArcGIS 
- [ ] AutoCAD/AutoCAD 3D
- [X ] BlueBeam 
>if user wants both (Adobe & BlueBeam), ask why?
- [ ] SketchUp 
- [ ] MS Project
- [ ] MS Visio

## Hardware Checklist
Check these devices for outdated models, change their mobile power adapter (round --> USB-C)
>Does the user need a GIS Modeling computer?
- [ ]  GIS Laptop w/ specialist docking station
- [X ]  Laptop
- [X ]  Power supply
- [ ]  Docking station

**Comment by JBStrange** [comment]
End User recieved there no PC with no more new issues.
