### ISSUE TITLE
SBOCONC Start Center Request

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#16532]
Division Manager Rivers requesting a meeting to discuss design and requirements for a new start center for SBO CONCRETE.

**Comment by rebekkabry** [comment]
#5/22/24 
_Meeting with Clay and Patti_

- Clay believe he already has it. checking start center.
- under BRDG
- currently sees the report.
- [ ] follow ollow up with Adyr to close out if applicable

@adry-martinez Clay believes he sees this on his start center now. He advised we could close and he could let us know if there is more needed. Please advise if we should close or keep open. Thank you.

**Comment by rebekkabry** [comment]
# 5/29/24 
Meeting with Clay and DTS Team 

Start Center for CONC
- converstaion with Brad needed. 
- what portlets are needed for BRADs crew (start center) 
- they have pain points in maximo and trrying to find work. 
- start center to help design 
- add to agenda for brads first workgroup meeting.
- duplication of a start center (minus  the bridge work order initiated by district). 
   - level of effect: same query and same modifications (MVP1) 
   - do we need to see parent + child work orders for the team (MVP2)  

- [ ] add to agenda for Brad Workgroup discussions 


![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/288551ab-604f-4772-ad7c-26880a41d9ab)

**Comment by rebekkabry** [comment]
# 6/5/24 
_Meeting with Stakeholders_ 

# GOAL of Start Center: 
  1. Assist with work order prioritization for teams in the field 
  2. Assist with view of status of work orders (what is in progress, completed, pending)
  3. Remove paper tracking out of process, rely on MAXIMO data

**Insights:** 
- Staff uses phone to take pics and notes. not to enter data or track data. 
- CONC Maximo Start Center is definitely needed. 
- Season - all year. 
- Related to Sidewalk; discussions about using a Service Plan from OCE is in place. 
- Maximo Description Tag: REHAB ❓ 

# To Do  List for MVP CONC Start Center 
- [ ] Duplicate Bridges Start Center 
- Report List 
  - [ ] Add SBO Concrete Sidewalk Repair to list 
  - [ ] Remove anything "bridges" report and replace with "conc" if report available. 
  - [ ] Keep SBO 8000 concrete crew report  
  - [ ] Remove Initiated by District 
  - [ ] Add Initiated by Sidewalk/Urban Trails (if able) [pending stakeholder discovery, as initiated by multi-work groups

# Current Work Order Intake Process
-  they create the work order, and we take it from there. 
- [ ] Check with Justin on the process. 

# Stakeholder Tools Used 
- Reports to see CONC - only using unit 8000 (not accurate to ops because not standard for ops to be entered into MAXIMO yet. 
- **Question: What is the process for data capturing?** 
   - Performance Measures are: 🎯  
     - not pulling from Maximo, 
     - manual tracking by Brad and sent to Dave for reporting when needed
     - **_TRACKED IN ACTUALS VERSUS SPECIFICATIONS_** 

# Current SBO CONC Performance Measures 
- Current Concrete SBO measures:
- Count of ADA Ramps Replaced/ Constructed
- Linear Feet of Curb/Gutters Replaced/Constructed
- Square Feet of Sidewalks Repaired/Constructed
- Square Feet of Driveways Repaired/Constructed
- Linear Feet of Retaining Walls Repaired/Constructed


 ✅ ACTION ITEMS
**DTS Team**
- [ ] MVP start center
- [ ] Review brads document and process 

**CONC Team**
- [ ] Brad - send manual tracking tools and previous documentation on field mapping to MAXIMO

**Comment by rebekkabry** [comment]
MVP1 Build in Progress

**Comment by rebekkabry** [comment]
Start Center has been created. Working with OCE SUTD to get hierarchy structured. Working with GIS to get ASSETNUM IDs to support work order creation. 

https://github.com/cityofaustin/atd-data-tech/issues/16532
