### ISSUE TITLE
Maximo Training, Pavement Operations

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#16536]
- [ ] Discuss training requirements with Project Coordinator, Inspector, and Division Manager (possibly Superintendents)
- [ ] Discuss timeline/scheduling
- [ ] Discuss resources
    - location
    -  equipment
    -  account access
    -  guides
    -  powerpoint presentation
- [ ] Schedule training
- [ ] Test location, equipment, and verify account access
- [ ] Gather/print necessary guides
- [ ] Commence training
- [ ] Gather training feedback
- [ ] Discuss AAR

**Comment by adry-martinez** [comment]
see #16720
