### ISSUE TITLE
Service contracts are having price increases and we need to reflect these in SMD Data Tracker

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#16649]
> What application are you using?

SMD Data Tracker 

> Describe the problem.

Service contracts with DIJ and TRP are having price increases with their term extensions. Work Assignments prior to the price increase will be paid out at the old pricing. Work Assignments after the price increase will be paid out at the new pricing. Need a way in DT to address different contract term pricing on different Work Assignments. 

> Describe the outcome you'd like to see when this feature is implemented.

Ability to have different contract  term pricing assigned to different work assignments. 

> Describe any workarounds you currently have in place or alternative solutions you've considered.

Currently, I will have to run the contractor report, export it into excel, and manually change all unit pricing.

> Is there anything else we should know?

I leave for parental leave mid May and Johnny Padron will be taking over my role with these contracts. I would be nice to have a solution prior to me being out so he doesn't have to perform the work around as he will be less familiar with this work.

> Requested By
Kati C.

Request ID: DTS24-113940

**Comment by ChristinaTremel** [comment]
Discussed this during backlog refinement and decided that the most straightforward way of increasing the pricing is going to be to:
- Add a new [contract_vendor](https://builder.knack.com/atd/signs-markings/records/objects/object_194) for both TRP and DIJs contracts with an identifier in the `Vendor Display Name` to distinguish that one is the old pricing and one is the new pricing.
- Add new bid items and the updated prices to the [contractor_bid_items](https://builder.knack.com/atd/signs-markings/records/objects/object_193) and use the new `contract_vendor` added.
- This will give Signs & Markings the ability to choose which pricing to use on a per work order basis

**Comment by ChristinaTremel** [comment]
## Build Notes
- Add a new [contract_vendor](https://builder.knack.com/atd/signs-markings/records/objects/object_194) for both TRP and DIJs contracts with an identifier in the `Vendor Display Name` to distinguish that one is the old pricing and one is the new pricing.
   - [x] Add new `Year` field to object 
   - [x] Export and save copy of the contractor_work_order records 
      - File Name: 20240518_contractor_work_order_BACKUP 
      - File Location: G:/ATD/ATD/ATD_GIS/02_ENT_APPLICATIONS/app_Signs_and_Markings/export
   - [x] Add year to the `Vendor Display Name` to look like: {Vendor Code} | {Contractor Name} - {Year}
   - [x] Add new records to the object for:
      - 885 | DIJ - 2024
      - 886 | TRP - 2024
- Import new bid items and the updated prices to the [contractor_bid_items](https://builder.knack.com/atd/signs-markings/records/objects/object_193) and use the new `contract_vendor` added. 
   - [x] Importing `174` records into contractor_bid_items
   - [x] QC'ed and everything populated correctly
- This will give Signs & Markings the ability to choose which pricing to use on a per work order basis

Will discuss this with SMD during the sprint review

**Comment by ChristinaTremel** [comment]
This has been reviewed with SMD in previous sprint reviews. We also had a meeting with TRP to ensure that the contractor pricing changes were being reflected on the contractor side.
