### ISSUE TITLE
[Tech Services] TPW PC Refresh Checklist - [Ramon, G.]

### ISSUE THREAD

**Issue by JBStrange** [cityofaustin/atd-data-tech#16655]
## Steps
- [ ] Talking to user about backing up their computers
- [ ] Recommend user to export all bookmarks and store on OneDrive>Documents folder
- [ ] Recommend user to screen shot their ex, Quick Access favorites folder, desktop files layouts, pinned applications on desktop 
- [ ] Store other OneDrive>Documents folder
- [ ] Check their Absolute/NetMotion profile (they need to be in TRN SAML profile)
>Ask if they access AMD traffic cameras?

## Software Checklist
- [X ] Avaya one-X phone 
- [ ] Adobe
- [ ] ArcGIS 
- [ ] AutoCAD/AutoCAD 3D
- [ ] BlueBeam 
>if user wants both (Adobe & BlueBeam), ask why?
- [ ] SketchUp 
- [ ] MS Project
- [ ] MS Visio

## Hardware Checklist
Check these devices for outdated models, change their mobile power adapter (round --> USB-C)
>Does the user need a GIS Modeling computer?
- [ ]  GIS Laptop w/ specialist docking station
- [X ]  Laptop
- [X ]  Power supply
- [ ]  Docking station

**Comment by JBStrange** [comment]
Completed the refresh of the PC and there no new issues.
