### ISSUE TITLE
Add comments table and form (with ability to email Requesters) to project intake details page

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#16692]
- Add comments table to AMD Project Intake Details page
- Give AMD the ability to send comments to requesters via email from the comments in Knack
   - This will be used to track the initial part of the request where Ivonne's team is clarifying the details of the request

**Comment by dianamartin** [comment]
# 4/12/24
- [x] On `work_order_comments` created connection to `project_rrequest`
- [x] On "Project Request details" page, add `comment` table
- [x] Add "New Comment" form

**Comment by dianamartin** [comment]
# 4/12/24
Just before the AMD Sprint Review, I added the email ability to the comment. 

## 1st Draft 
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/17845cc2-d904-4322-8ef8-c823ed50ced4)

**Comment by ChristinaTremel** [comment]
Reviewed this with AMD during a review meeting on 4/12.
