### ISSUE TITLE
Prototype SBO Inventory Tracking module

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#16697]
# 4/8/2024
Synced with Christina when we were testing SBO Overtime, I said I had some time and if I could started to prototype out the SBO Inventory Tracking since the SBO Coordination roll out won't happen until May 2024. 

Used references that Richard emailed to us on 3/18/24
- `South District - Equipment Inventory Form 2024.03.13.docx`
- `SBO Sample Equipment Inventory - March 2023.xlsx`

**Comment by dianamartin** [comment]
# 4/8/2024
## Created object tables
  - [x] `asset inventory`
  - [x] Created fields
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/ff50d6ad-db9b-40c8-92c5-f4acfc59430b)
  - [x] `inventory_reviews`
  - [x] Created fields
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/e1600cfe-f213-4199-97d2-2f55fb0a7165)

## Imported Data
- [x] Reformatted sample excel into importable format
- [x] Imported `42 records` - District Maintenance, North District, Power Tools & Radios (March 2024)

## Created Pages
- [x] renamed "Tools" page to "Manage Assets"
- [x] removed banner saying "Under Construction"
- [x] added "Asset Inventory" table to page
- [x] added a Details view
- [x] added an Edit page, removed Edit form for "asset_inventory" and added "add new record form for asset review"
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/e21f7d80-e1fa-47ad-a838-a94718ec806c)
- [x] added another table "Asset Inventory Reviews | AIR"
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/5360b8d2-59a1-4089-b80c-3f9b27f88416)

**Comment by dianamartin** [comment]
@ChristinaTremel check out the first pass prototype

**Comment by ChristinaTremel** [comment]
## Check-In 5/31
- Attendees: Richard, Diana, and Christina
- Everything in there is for north district - Richard received the final work group inventory. He needs to update the spreadsheet in SharePoint and he can send us the list
- Diana exported the power tools list and gave Robert that list along with Domains so he can add the data to this spreadsheet so we can import that
- Adding `Review Date` and `Last Status` to `Manage Inventory` list
   - [ ] Talk to Diana about creating these fields on the power tools object and having it update when new reviews are created (so there's only one last status and review date)
- Updated the Inventory Review table to make it more usable for the staff reviewing
   - Reorganized the field order
   - Brought the review buttons towards the front of the table
   - Added an `Edit Review` button to the table so staff could edit the review if they made a mistake

**Comment by ChristinaTremel** [comment]
@dianamartin I'm thinking we're probably done with the prototype right? I created a new issue #17779 for importing the latest spreadsheet from Richard! And we made all of the changes that he requested during the check in with him.

**Comment by ChristinaTremel** [comment]
The prototype was completed in April and was presented to Greg and Richard! We have follow-up issues that we've worked on with them since the prototype.
