### ISSUE TITLE
🧑‍🚀 Discovery Day - May 3rd, 2024

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#16723]
Discovery Day is upon us again! 🎉 This will be the issue we use to track getting everything ready, and it will become the epic that we house everyone's issues under on May 2nd. Thanks!

* [x] Schedule opening meeting
* [x] Prepare opening meeting content
* [x] Schedule discovery day proper
* [x] Make lunch plans
* [x] Schedule debrief meeting

cc/ @chiaberry @amenity @dianamartin

**Comment by frankhereford** [comment]
Thanks everyone for a great Discovery Day!
