### ISSUE TITLE
[Tech Services] TPW PC Refresh Checklist - [Preston S

### ISSUE THREAD

**Issue by Matthew-M-TPW** [cityofaustin/atd-data-tech#16758]
Latitude 7400

## Steps
- [x] Talking to user about backing up their computers
- [x] Recommend user to export all bookmarks and store on OneDrive>Documents folder
- [x] Recommend user to screen shot their ex, Quick Access favorites folder, desktop files layouts, pinned applications on desktop 
- [x] Store other OneDrive>Documents folder
- [x] Check their Absolute/NetMotion profile (they need to be in TRN SAML profile)
>Ask if they access AMD traffic cameras?

## Software Checklist
- [ ] Avaya one-X phone 
- [ ] Adobe
- [ ] ArcGIS 
- [ ] AutoCAD/AutoCAD 3D
- [ ] BlueBeam 
>if user wants both (Adobe & BlueBeam), ask why?
- [ ] SketchUp 
- [ ] MS Project
- [ ] MS Visio

## Hardware Checklist
Check these devices for outdated models, change their mobile power adapter (round --> USB-C)
>Does the user need a GIS Modeling computer?
- [ ]  GIS Laptop w/ specialist docking station
- [ ]  Laptop
- [ ]  Power supply
- [ ]  Docking station

**Comment by Matthew-M-TPW** [comment]
Reached out to user via teams

**Comment by Vaishnav1397** [comment]
Reached user via teams and waiting for response.

**Comment by Vaishnav1397** [comment]
Contacted user and will be scheduling sometime next week for the PC refresh. User mentioned he need Arc-Gis and Acrobat proto be updated in system.

**Comment by Vaishnav1397** [comment]
Reached out back to user via teams, called him and waiting for response on availabilities.

**Comment by Vaishnav1397** [comment]
Scheduled sometime for Thursday to swap out the laptop.

**Comment by Vaishnav1397** [comment]
@Matthew-M-TPW User mentioned he would be available at 10am tmrw.

**Comment by Vaishnav1397** [comment]
Swapped out user with a new laptop by matt today.
