### ISSUE TITLE
[Tech Services] TPW PC Refresh Checklist - Coleen, G

### ISSUE THREAD

**Issue by Matthew-M-TPW** [cityofaustin/atd-data-tech#16756]
OptiPlex 7060

## Steps
- [x] Talking to user about backing up their computers
- [ ] Recommend user to export all bookmarks and store on OneDrive>Documents folder
- [x] Recommend user to screen shot their ex, Quick Access favorites folder, desktop files layouts, pinned applications on desktop 
- [x] Store other OneDrive>Documents folder
- [x] Check their Absolute/NetMotion profile (they need to be in TRN SAML profile)
>Ask if they access AMD traffic cameras?

## Software Checklist
- [ ] Avaya one-X phone 
- [x] Adobe
- [ ] ArcGIS 
- [ ] AutoCAD/AutoCAD 3D
- [ ] BlueBeam 
>if user wants both (Adobe & BlueBeam), ask why?
- [ ] SketchUp 
- [ ] MS Project
- [ ] MS Visio

## Hardware Checklist
Check these devices for outdated models, change their mobile power adapter (round --> USB-C)
>Does the user need a GIS Modeling computer?
- [x]  GIS Laptop w/ specialist docking station
- [ ]  Laptop
- [ ]  Power supply
- [ ]  Docking station

**Comment by Vaishnav1397** [comment]
Laptop "Ready to Go"

**Comment by Matthew-M-TPW** [comment]
Talked to user she wants a desktop. 

Just finished prepping laptop. 

User scheduled Swap out on 5-22 at 2PM

**Comment by Matthew-M-TPW** [comment]
@Craigjacobs-ATX swapped users machine out
