### ISSUE TITLE
Pavement: Updated Work Order Checklist 

### ISSUE THREAD

**Issue by rebekkabry** [cityofaustin/atd-data-tech#16771]
# Background
In preparation for Pavement Training - we found a few updates that could be used on the work order completion checklist. 
#16288 

![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/b92e92bf-f266-4de7-880a-0cbfbbdfec93)

### NEW
- [ ] Create Fog Crack Completion 
- [x] Seal Coat Work Order Completion List with all phases (Level Up, Sweeping, Crack Seal) Scheduled 4/28 week
  - [Reference Notes](https://github.com/cityofaustin/atd-data-tech/issues/16288#issuecomment-2049763548) 

### MODIFICATIONS
- [ ] Update for requirement for picture, remove "if applicable". Pictures are now required. 
  - [Reference Notes](https://github.com/cityofaustin/atd-data-tech/issues/16288#issuecomment-2049791414)
- [x] Add Log Notes Requirements on all Pavement Sub Group Work Order Completion Lists. 
  - [Reference Notes](https://github.com/cityofaustin/atd-data-tech/issues/16288#issuecomment-2049809715)
- [x] Confirm the requirements for CSR Log Notes (see Model work order notes)

**Comment by rebekkabry** [comment]
# 4/25/24

- Completed the CSR Work Order Completion Discussion 
- [Updated notes into Miro ](https://miro.com/app/board/uXjVN7sxj9I=/?moveToWidget=3458764587013797318&cot=14)
- [ ] Drafting new CSR Work Order - Dispatch Checklist 
- [x] Meetings scheduled to complete Pavement Ops Work Order Updates (Fog and Crack Seal; Seal Coat with Phases)

**Comment by rebekkabry** [comment]
# 5/13/24 
_**Work session to discuss Seal Coat prep and post children work order completion needs.**_ 

**NOTE:** All Parent Work Orders are imported with 3 related children workorders (`Prep:LU, Prep:SW, Prep:CS`)

**NOTE:** All specification needs and requirements are different. Currently no work order checklist or documentation for phases. 

**1. Level Ups Phase**
- Inspector (john ga) will access visit all locations to determine if  `PARENT Seal Coat Work Order` will need Level Up, Crack Seal or Both.
  - If NO `Level Up` is needed - inspector update time and say no work order needed in LU workorder. Complete Child Work. Next step, crack seal, needed? If yes, step crack seal. If no, on to seal coat. 
  - If YES `Level Up` is needed - inspector will make note, Level Up technician will go to site to investigate- the complete the level up specifications `ACT_LEVEL_UPS `
 - [ ] @adry-martinez follow up with CTM on updating SQFT to EACH or appropriate value metric. 
![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/b92ff2fc-e9a9-4975-9568-2954a0adbbb0)

**2. Crack Seal Phase**
**_performed by Crack Seal team_** 
**NOTE:** there is no measurement for this. they have not come to a point of what is being used, maybe gallons; but not there yet. 

- for assessment for both will be during the inspector
- Only recording labor, materials for completion of work order. 

**3. Seal Coat Phase**
**NOTE:** Parent work order can not be closed at completion, because sweeping child must be completed first. 
Once above complete, the Parent work order is now worked on by the Seal Coat team. Following the original work order completion checklist 
- [ ] Update picture to be required. 

**4. Sweeping Phase**

**Comment by rebekkabry** [comment]
**Next Steps:** 
- [ ] - complete notes from todays meeting
- [ ] - create draft of new material (goal 5/18)
- [ ] - review with team for feedback and modifications (goal by 5/20)
- [ ] - next workgroup within pavement reviewed.

**Comment by rebekkabry** [comment]
# 11/15/24 

- Discussions in progress regarding required specifications and work order handling. 
- Also an SBO FY25 initative, see Dave A. for more details.

**Comment by rebekkabry** [comment]
# 12/31/24 

- This will be added during the newly established SBO Maximo Leadership discussions. 
https://github.com/cityofaustin/atd-data-tech/issues/17783
