### ISSUE TITLE
Refine project reviews process for AMD project intake

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#16844]
### Project Reviews changes determined during the 4/12 review
- Add `Decision` options: 
   - Approved with Decision
   - No Comment
- Add 5 project review lines for each reviewer group with the option to delete it if it’s not needed
   - Reviewer field at front of the table
   - Once it’s `Assigned To` someone, don’t allow delete

**Comment by dianamartin** [comment]
# 4/19/2024
## To Do's
- [ ] Add Decision options:
- `Approved with Decision`
- `No Comment`
- [ ] Ability click a button (auto generate five `project_review` records for each work group
>Add 5 project review lines for each reviewer group with the option to delete it if it’s not needed
- [ ] Add `Reviewer` field at front of the table
- [ ] Add display rule, when `Assigned To` is not blank, hide `delete` field

**Comment by dianamartin** [comment]
# 4/23/2024
- Reviewing configuration in the TDS application for the Vision team reviews
## Ability click a button (auto generate five project_review records for each work group
- [x] Created record rules on the "Edit Project Request" form, to generate one connected project review for each workgroup
- [x] Made the "delete" button more permanent
- [x] Removed some inline editing to fields that didn't make sense
- [x] Tested that auto-creation of "Project Reviews" was working
- [x] Cleaned up the table upon set-up

**Comment by dianamartin** [comment]
# 4/29/24
@ChristinaTremel This is ready for review

**Comment by ChristinaTremel** [comment]
This is amazing!! We can review this during the AMD Sprint Review today 🙌

**Comment by ChristinaTremel** [comment]
## Feedback Completed from Sprint Review 5/1:
- [x] Move the record rules to New Project Review form and add rules to populate `Assigned To`
   - AMD Management - leave blank and they can populate if needed
   - Communications - Harrell
   - Signal Engineering - Brian G
   - Operations/Inventory - Billy
   - Infrastructure/Construction Services - Scott F
   - Add Assigned Date to the current date
