### ISSUE TITLE
Updates to project comments after 4/12 review

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#16845]
### Project Comment
- Update comment to rich text format
- Add note that an email was sent on the comment table
- Could we make the email from PMT email inbox so it's easier for Requesters to respond to? Or include it as a CC?
    * [AMDProjectRequest@austintexas.gov](mailto:AMDProjectRequest@austintexas.gov)

**Comment by dianamartin** [comment]
# 4/19/2024
## To Do's
re: Project Comment
- [ ] Update `Comment` to rich text format
- [ ] Add field to table `Created Date` (Sent Date) and other email fields
>Add note that an email was sent on the comment table
- [ ] Add another email for PMT inbox
>Could we make the email from PMT email inbox so it's easier for Requesters to respond to? Or include it as a CC?
 [AMDProjectRequest](mailto:AMDProjectRequest@austintexas.gov)

**Comment by dianamartin** [comment]
# 4/29/24
Need to make configuring email part of the "Go-live" tasks

**Comment by ChristinaTremel** [comment]
Created a new issue for configuring the email when we go live. Closing this issue!
