### ISSUE TITLE
Signal Status "Contractor Controlled" + date taken by contractor

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#1686]
Ben Plett
TMC

Requesting
>In the TMC, it would be very helpful to us if we had a Signal status of "Contractor Controlled" and then a field showing the date that it was taken over by the contractor. It would also be good to have date that we took it back. 

Proposing 
- [ ] Asking for a new choice on `Signal Status` field - "Contractor Controlled"
- [ ] New field `Contractor Controlled Date`
- [ ] New field `Take back Date`?

*Migrated from [atd-knack-data-tracker #153](https://github.com/cityofaustin/atd-knack-data-tracker/issues/153)*

**Comment by dianamartin** [comment]
Messaged Lance and Allyson
>Sorry to keep messaging you both, but is this [one ](https://app.zenhub.com/workspaces/data--technology-services-5caf7dc6ecad11531cc418ef/issues/cityofaustin/atd-data-tech/1686)also still relevant?  New "Signal Status" - "Contractor Controlled", Date taken back by contractor

**Comment by dianamartin** [comment]
Received response on this from Lance and Allyson

Allyson
> I would say the third would be the most important of the three, if we're prioritizing. I feel somewhat indifferent about the previous two.

Lance
>- agree. the first two can be closed. third one is important to us
- i would add to the third one that we would like a field to populate "Contractor Contact" with person, phone, email. open to how that looks, but would be helpful for us

Diana
>Don't forget the request about a new activity for School Beacons too, is this request priority above or below the requested Contractor fields?

Allyson
>probably slightly below, but both important

_In reference to the order of issues I talked about, this was part of the first two issues I brought to their attention_

**Comment by johnclary** [comment]
- Add a "Contractor Controlled" Yes/no field
- Add a "Contractor Control Notes" paragraph text field that should include details about the contractor name and takeover date
- Add fields to signal details in middle column near "Owner"

**Comment by dianamartin** [comment]
Added to `signals` object table: 
- [x] `Contractor Controlled` - Y/N
- [x] `Contractor Control Notes`

Added `Contractor Controlled` and `Contractor Control Notes` to Signal Details
Added `Contractor Controlled` and `Contractor Control Notes` to Edit Signal Form

**Comment by dianamartin** [comment]
Messaged Allyson and Lance
>Another update, I added the "Contractor Controlled?" and "Contractor Control Notes" field to the Signal Details page. It should also be seen on the "Edit Signal" form. Let me know if you have questions.
