### ISSUE TITLE
Clean up reimbursable records for go live

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#16874]
## Required clean up to go live on Reimbursable Tracking feature
- Updating `Submitted for SMD Review` with `Submitted_PE_PM_for_Approval` data
   - Populate with dates from `Submitted_PE_PM_for_Approval`
   - Clean up additional info and move to Comments field
   - At that point we can delete `Submitted_PE_PM_for_Apprval` field
- Updating Reimbursable records with proper statuses

_Originally posted by @ChristinaTremel in https://github.com/cityofaustin/atd-data-tech/issues/16091#issuecomment-2064095903_
            ](https://github.com/cityofaustin/atd-data-tech/issues/16091)

**Comment by ChristinaTremel** [comment]
## Notes from 4/9 and 4/10
- [x] Cleaned up spreadsheet provided by Ramona that included some additional dates and details about the invoice batch, vendor, vendor invoice number and date, and finance processing dates and split the reimbursable records into two batches
   - Other batch used the `Work Order ID` - 495 records
      - [x] Imported first batch of 495 records
   - One batch used the `Requester ID` - 238 records
      - [x] Imported second batch of 238 records

- [x] Updating Submitted for SMD Review with `Submitted_PE_PM_for_Approval` data
   - [x] Clean up additional info and move to Comments field
   - [ ] Deleted the `Submitted_PE_PM_for_Approval` field

- [x] Then exported the `reimbursable_tracking` object with `1773` records and updated `Reimbursable Status`, `Is this Reimbursable`, and `Approval Status` fields based on these rules:
   - If `Reimbursement_Processed_by_Finance` is not blank
      - Reimbursable Status is `Closed`, Approval Status is `Approve`, and Is This Reimbursable is `Yes, this is a reimbursable`
   - If `Date Sent to Finance` is not blank and `Reimbursement_Processed_by_Finance` is blank
      - Reimbursable Status is `Approved`, Approval Status is `Approve`, and Is This Reimbursable is `Yes, this is a reimbursable`
   - If `Submitted_Div_Dept_Approval` is not blank and `Reimbursement_Processed_by_Finance` and `Date Sent to Finance` is blank
      - Reimbursable status is `Waiting for Requester Approval` and Is This Reimbursable is `Yes, this is a reimbursable`
   - If `Submitted for SMD Review` is not blank and `Submitted_Div_Dept_Approval`, `Reimbursement_Processed_by_Finance` and `Date Sent to Finance` is blank
       - Reimbursable Status is `Needs Review` and  Is This Reimbursable is `Yes, this is a reimbursable`
   - If Work Order Status is `CANCELLED`
      - Reimbursable Status is `Not Reimbursable` and  Is This Reimbursable is `No, this is not a reimbursable`
   - If Work Order Status is not `CLOSED` or `CANCELLED`
      - Reimbursable Status is `Not Ready`
   - If `Too Small` is yes and `Work Order Status` is CLOSED
      - Reimbursable Status is `Not Reimbursable` and  Is This Reimbursable is `No, the Invoice Amount is under $30`

**Comment by ChristinaTremel** [comment]
This was completed in April and May. I have met a couple times with Ramona since then to help clean up additional records.
