### ISSUE TITLE
[Power BI] SMD dashboard Best Practice Checklist

### ISSUE THREAD

**Issue by susannegov** [cityofaustin/atd-data-tech#16880]
Addressed [best practices analyzer](https://powerbi.microsoft.com/en-my/blog/best-practice-rules-to-improve-your-models-performance/) messages; documented ignored rules / objects
Will provide this [documentation](https://cityofaustin.sharepoint.com/:w:/r/sites/tpwDTS/_layouts/15/Doc.aspx?sourcedoc=%7BEF888CC8-4590-4402-9182-609C8588424F%7D&file=Best%20Practice%20Checklist.docx&action=default&mobileredirect=true) to Jordan during the transition

# Rules
## DAX Expressions
- [x] Use the [DIVIDE](https://dax.guide/divide/) function for division
- [x] Avoid using the [IFERROR](https://dax.guide/iferror/) function
   - There are no measures using IFERROR
- [x] [Column references should be fully qualified](https://learn.microsoft.com/en-us/dax/best-practices/dax-column-measure-references)
- [x] [Measure references should be unqualified](https://learn.microsoft.com/en-us/dax/best-practices/dax-column-measure-references)
- [x] Measures should not be direct references of other measures
- [x] No two measures should have the same definition
- [x] Use the [TREATAS](https://dax.guide/treatas/) function instead of [INTERSECT](https://dax.guide/intersect/) for virtual relationships

## Error Prevention
- [x] Data columns must have a source column
- [x] Calculated columns must have an expression

## Formatting
- [ ] Add data category for columns
   - 'Roadway Sign Assets'[latitude]
   - 'Roadway Sign Assets'[longitude]
- [x] Do not summarize numeric columns
- [x] First letter of objects must be capitalized
- [ ] Hide fact table columns
   - 'Short Line Dates'[Markings Short Line ID]
   - 'Specialty Point Dates'[Markings Specialty Point ID]
- [ ] Hide foreign keys
   - 'Short Line Dates'[Markings Short Line ID]
   - 'Short Line'[Markings Short Line ID]
- [x] Mark primary keys
- [x] Month (as a string) must be sorted
- [x] Objects should not start or end with a space
- [x] Percentages should be formatted with thousands separators and one decimal
- [x] Format flag columns as Yes/No value strings
- [x] Provide format string for “Date” columns
- [x] Provide format string for “Month” columns
- [x] Provide format string for measures
- [ ] Relationship columns should be of integer data type
   - Short Line Dates
   - Contractor Markings Work Orders
   - In House Markings Work Orders
   - Specialty Line Dates
   - Specialty Point Dates
- [x] Whole numbers should be formatted with thousands separators and no decimals

## Maintenance
- [ ] Ensure tables have relationships
   - Selection Value
   - Roadway Sign Assets
   - Last Refreshed Date
   - Selection Long Line
   - Asset Time Condition Inventory
   - Fair or Better Condition Guidelines
-  [x] Add descriptions to objects (200+ fields)

## Objects with no description
- [x] Remove data sources not referenced by any partitions
- [x] Remove roles with no members
- [x] Remove unnecessary columns
- [x] Remove unnecessary measures
- [x] Naming Conventions
- [x] Use CamelCase for hidden columns
- [ ] Partition name should match table name for single partition tables
   - Short Line Dates
   - Contractor Markings Work Dates
   - In House Markings Work Orders
   - Short Line
   - Selection Value
- [x] Object names must not contain special characters

## Performance
- [x] Avoid bi-directional relationships against high-cardinality columns *
- [x] Avoid excessive bi-directional or many-to-many relationships
- [x] Avoid snowflake schema architecture
- [x] Do not use floating point data types
- [x] Large tables should be partitioned *
- [x] Limit row level security (RLS) logic
- [x] Many-to-many relationships should be single direction
- [ ] Check if bi-directional and many to many relationships are valid
   - 'Long Line Dates'[CTN Segment ID] --> 'Long Line'[CTN Segment ID]
- [ ] Minimize Power Query transformations (12 objects)
   - Short Line Dates
   - Contractor Work Orders
   - In House Work Orders
   - Short Line
   - Selection Value
   - Specialty Line Dates
   - Specialty Point
   - Specialty Point Dates
   - Specialty Line
   - Roadway Sign Assets
   - 311 TPW CSRs
- [x] Model should have a date table
- [x] Model using Direct Query and no aggregations
- [x] Reduce number of calculated columns
- [x] Reduce usage of calculated columns that use the [RELATED](https://dax.guide/related/) function
- [ ] Reduce usage of calculated tables
   - Date
   - Selection Long Line
   - Asset Time Condition Inventory
   - Fair or Better Condition Guidelines
- [x] Reduce usage of long-length columns with high cardinality **
- [x] Remove auto-date table
- [ ] Remove redundant columns in related tables
   - 'Short Line Dates'[Asset Condition]	
   - 'Short Line Dates'[Months Past Work]
   - 'Specialty Line Dates'[Asset Condition]
   - 'Specialty Line Dates'[Months Past Work]	
   - 'Specialty Point Dates'[Months Past Work]
- [x] Set IsAvailableInMdx to false on non-attribute columns
- [x] Split date and time ***
- [ ] Date/calendar tables should be marked as a date table
   - Short Line Dates
   - Specialty Line Dates
   - Specialty Point Dates
   - Long Line Dates
- [x] Unpivot pivoted (month) data

**Comment by susannegov** [comment]
All BPA rules with notes in a [word document](https://cityofaustin.sharepoint.com/:w:/r/sites/tpwDTS/_layouts/15/Doc.aspx?sourcedoc=%7BEF888CC8-4590-4402-9182-609C8588424F%7D&file=Best%20Practice%20Checklist.docx&action=default&mobileredirect=true)
