### ISSUE TITLE
Update the pedestrian scores for traffic signal requests in Data Tracker

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#16917]
> What application are you using?

AMD Data Tracker

> Describe the problem.

Please update the pedestrian scores for traffic signal requests in data tracker.  These requests should have a request status of "Under Evaluation".  The pedestrian scores come from the data driven PHB analysis, located at:  G:\ATD\ATD_GIS\Arterial_Management\56_Pedestrian_Hybrid_Beacon_PHB\Data_Driven_PHB_Ranking\DTS

> How soon do you need this?

Flexible  — An extended timeline is OK

> Is there anything else we should know?

It would be preferable to have this data uploaded by mid-May.

Thank you!

> Requested By
Renee O.

Request ID: DTS24-114330

**Comment by ChristinaTremel** [comment]
Scheduled meeting with Renee on 5/16 to discuss this.

**Comment by ChristinaTremel** [comment]
Reference #11983 for steps to import.

**Comment by ChristinaTremel** [comment]
Discussed this with Renee when meeting on 5/16 and realized I first need to reach out to @andrewshensky to get the GIS data exported into a spreadsheet. 

Once I receive the spreadsheet, I'll verify it with Renee and do the following to complete the import (notes from reference issue):
## Importing Steps
### Test Import
- [ ] Import Test record
  - Note: change Field Heading from "Total_Score" to "PED_SCORE_RAW"
- [ ] Spot Check  - ` 1 record` 
>The REQ-----, had no PED SCORE before and now it shows as `x`
- [ ] Field `Total_Score` Rename 'PED_SCORE_RAW`

### Pre-Import
Spot Check - BEFORE
- [ ] `REQ-----` - blank
- [ ] `REQ-----` - blank
- [ ] `REQ-----` - blank
- [ ] `REQ-----` - blank
- [ ] `REQ-----` - blank

### Importing
- [ ] Import the rest of the records - `-- records`
>Pre-import there were `-- records with PED SCORE RAW`, I added import one on 4/17, equaling to `35`

### Post-Import
Spot Check - AFTER
- [ ] `REQ-----` - x (ped score should be populated for the requests checked before)
- [ ] `REQ-----` - x
- [ ] `REQ-----` - x
- [ ] `REQ-----` - x
- [ ] `REQ-----` - x

**Comment by andrewshensky** [comment]
@ChristinaTremel are the TOTAL_SCORE values needed for all Signals Requests with a status of "Under Evaluation" or only those with that status after a certain date?

**Comment by andrewshensky** [comment]
@ChristinaTremel attached is an excel table with the Total Score for each Request ID that had a status of UNDER EVALUATION in the AGOL data. I believe this is the same workflow we followed last time. For each location we captured the Max Total Score value from the nearest feature in the GIS data. Of the 157 records with a status of UNDER EVALUATION 4 still contain a null values as they were not located near scored streets. Let me know if you have any questions.

[RequestID_With_TotalScore.xls](https://github.com/cityofaustin/atd-data-tech/files/15378155/RequestID_With_TotalScore.xls)


For reference source data for scoring below:
<!-- G:\ATD\ATD_GIS\Arterial_Management\56_Pedestrian_Hybrid_Beacon_PHB\Data_Driven_PHB_Ranking\AMD\PHB_Data.gdb\Street_Select\PHB --!>

**Comment by ChristinaTremel** [comment]
On object `signal_requests_traffic_eval`
### Pre-Import Spot Check PED_SCORE_RAW
- `REQ24-005195`- blank
- `REQ23-004995`- blank
- `REQ23-005150`- blank
- `REQ20-003945` - blank

### Data Clean Up
I asked Renee if there's any statuses I should filter out of the import and she noted: 
> Yes, please update the Pedestrian Score for any traffic signal request with a status of Under Evaluation that has a Traffic Signal Evaluation that is not "Complete".  See clip attached.  Please let me know if you have any questions.  Thanks! 

There were several of these ped scores exported that had completed evaluations so I first had to clean those up from the export.
- exported `signal_requests_traffic_eval` and found 37 records that were `In-Progress` and `Under Evaluation`
  - used xlookup to populate the `PED_SCORE_RAW` and kept the Auto Increment field to ensure I'm importing only the scores for evaluations that are in progress
  - Results gave me `37` records missing the `PED_SCORE_RAW` and I spot checked the scores to confirm they were accurate
  - New spreadsheet to import: [RequestID_With_TotalScore.xls](https://github.com/user-attachments/files/15811545/RequestID_With_TotalScore.xls)

### Import
- Imported 37 `PED_SCORE_RAW` records

### Post Import
Checked the records I spot checked previously:
- `REQ24-005195`- 34
- `REQ23-004995`- 35
- `REQ23-005150`- 30
- `REQ20-003945` - 43

Let Renee know that I've imported the pedestrian scores!
