### ISSUE TITLE
[Tech Services] TPW PC Refresh Checklist - Keyes C

### ISSUE THREAD

**Issue by Matthew-M-TPW** [cityofaustin/atd-data-tech#16948]
## Steps
- [ ] Talking to user about backing up their computers
- [ ] #16973
- [ ] Recommend user to screen shot their ex, Quick Access favorites folder, desktop files layouts, pinned applications on desktop 
- [ ] Store other OneDrive>Documents folder
- [ ] Check their Absolute/NetMotion profile (they need to be in TRN SAML profile)
>Ask if they access AMD traffic cameras?

## Software Checklist
- [ ] Avaya one-X phone 
- [ ] Adobe
- [ ] ArcGIS 
- [ ] AutoCAD/AutoCAD 3D
- [ ] BlueBeam 
>if user wants both (Adobe & BlueBeam), ask why?
- [ ] SketchUp 
- [ ] MS Project
- [ ] MS Visio

## Hardware Checklist
Check these devices for outdated models, change their mobile power adapter (round --> USB-C)
>Does the user need a GIS Modeling computer?
- [ ]  GIS Laptop w/ specialist docking station
- [ ]  Laptop
- [ ]  Power supply
- [ ]  Docking station

**Comment by Vaishnav1397** [comment]
Checked with user and he is using 7490 and mentioned he would be at Ben white tmrw, can deploy a new one accordingly.

**Comment by Vaishnav1397** [comment]
User provided availabilities and need to deploy with new laptop.

**Comment by Vaishnav1397** [comment]
New Laptop has been deployed to user by Matt.
