### ISSUE TITLE
Meeting for transition of ownership of the SMD Performance Measure Dashboard 4/26

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#16960]
# Dashboard Management Transition Check-List
Link to materials in [DTS SharePoint](https://cityofaustin.sharepoint.com/sites/tpwDTS/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FtpwDTS%2FShared%20Documents%2FProjects%2FDASH%2FSMD%5FSigns%5FMarkings&viewid=2958c37f%2Dbe1b%2D4ca8%2Db045%2Ddc17d145a4ba)

## Semantic Model Handover
- [x] Transfer ownership to Jordan  
- [x] Address [best practices analyzer](https://powerbi.microsoft.com/en-my/blog/best-practice-rules-to-improve-your-models-performance/) messages; documented ignored rules / objects
   - See #16880
- [x] [Data Dictionary](https://cityofaustin.sharepoint.com/:x:/r/sites/tpwDTS/Shared%20Documents/Projects/DASH/SMD_Signs_Markings/Data%20Dictionary.xlsx?d=w2371a08ad5b54adc8d03998a0597a681&csf=1&web=1&e=EQwvaP) Resource
   - Data dictionary created see #16898
- [x] Review [SMD Performance Dashboard Documentation](https://cityofaustin.sharepoint.com/:w:/r/sites/tpwDTS/_layouts/15/doc.aspx?sourcedoc=%7B8a464e03-4e03-4239-ae2a-cee7da9137fe%7D&action=edit)- documentation of queries, methods & results
- [x] Training & Adoption material / methods have been made / shared
   - Will transfer [`SMD_Signs_Markings`](https://cityofaustin.sharepoint.com/sites/tpwDTS/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FtpwDTS%2FShared%20Documents%2FProjects%2FDASH%2FSMD%5FSigns%5FMarkings&viewid=2958c37f%2Dbe1b%2D4ca8%2Db045%2Ddc17d145a4ba) dashboard folder to SMD 
- [x] Check Jordan's PowerBI desktop settings
- [ ] Issue with `TPW - 311 CSRs dataflow permissions` 
- [ ] Set up schedule refresh on Jordan's cloud connection

## Report Handover
- [x] Transfer ownership to Jordan 
- [x] Share Training & Adoption material
   - Link to [PowerBI SharePoint](https://cityofaustin.sharepoint.com/sites/PowerBIUsersInternalOnly/SitePages/Power-BI-Training-Resources.aspx)
   - Link to [PowerBI Gitbook](https://atd-dts.gitbook.io/atd-staff-resources/power-bi/access-power-bi-web-interface)
- [x] Walk Jordan through how to export the json of the theme (custom themes, images and visual files) created to align with TPW branding.

**Comment by susannegov** [comment]
We were able to transfer the dashboard onto Jordan's laptop. He currently does not have access to edit the SMD sharepoint so it is currently stored in the user folder.

# To do 
- [ ] Issue with TPW - 311 CSRs dataflow permissions
 - [ ] Set up schedule refresh on Jordan's cloud connection

**Comment by susannegov** [comment]
Schedule refresh has been set up
- Added 311 CSRs dataflow to the report
- Setup manage relationships in 311 CSRs between it and dates table
- Published report
- Jordan take over semantic model
- Setup Data Gateway and Data Sources
- Tested refresh ✅
