### ISSUE TITLE
Additional drop down options for Detector Events and Detector Statuses

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#16983]
> What application are you using?

AMD Data Tracker

> Describe the problem.

Please add the following Detector Events and Detector Statuses to the Detection Page:

REPLACE
LVL 1 INVESTIGATION
LVL 2 INVESTIGATION

> Describe the outcome you'd like to see when this feature is implemented.

Please add the following Detector Events and Detector Statuses to the Detection Page:

REPLACE
LVL 1 INVESTIGATION
LVL 2 INVESTIGATION

> Describe any workarounds you currently have in place or alternative solutions you've considered.

NONE

> Is there anything else we should know?

Within next couple of weeks 

> Requested By
Allyson R.

Request ID: DTS24-114410

**Comment by ChristinaTremel** [comment]
## Notes 5/3
- Talked to Allyson and she noted that she would like these options to be added to both the detector status and the detector event fields. She'd like the status to be updated whenever an event it added. Checked the rules on the backend and saw that  the `Add Signal Detector Events` form has rules to update the DETECTOR_STATUS with the EVENT statuses.

**Reference:**
<img src="https://github.com/cityofaustin/atd-data-tech/assets/61209591/16c97968-0c98-4bdc-b0f6-21857fc5e6d2" width="400"/>



### Object: `signals_detectors`
Field: `DETECTOR_STATUS`
- [ ] Add `REPLACE`
- [ ] Add `LVL 1 INVESTIGATION`
- [ ] Add `LVL 2 INVESTIGATION`

### Object: `signals_detection_status_log`
Field: `EVENT`
- [ ] Add `REPLACE`
- [ ] Add `LVL 1 INVESTIGATION`
- [ ]  Add `LVL 2 INVESTIGATION`

### Form Page: `Add Signal Detector Events`
Rules to add:
- [ ] When EVENT is `REPLACE` update values DETECTOR_STATUS to a custom value `REPLACE`
- [ ] When EVENT is `LVL 1 INVESTIGATION` update values DETECTOR_STATUS to a custom value `LVL 1 INVESTIGATION`
- [ ] When EVENT is `LVL 2 INVESTIGATION` update values DETECTOR_STATUS to a custom value `LVL 2 INVESTIGATION`

**Comment by ChristinaTremel** [comment]
Multi-choice options have been added to the EVENT and DETECTOR_STATUS fields and the record rules have been aded to the `Add Signal Detector Events`. Let Allyson know via email that this has been completed!
