### ISSUE TITLE
Draft Updated MAXIMO CSR Work Order Completion Checklist

### ISSUE THREAD

**Issue by rebekkabry** [cityofaustin/atd-data-tech#17007]
#Background 
Updated processes are required modifications to the CSR work order completion document. 
Previous worksessions with Adry and Rene have been performed to confirm the new CSR process. 

[Worksession Notes for Updated Process in Miro](https://miro.com/app/board/uXjVN7sxj9I=/?moveToWidget=3458764587013797318&cot=14)

#Goal 
- [x] Complete discovery meetings 
- [ ] Draft a new layout that could be used a template for the updating work order documents and work order process changes. 
- [ ] Create CSR updated document 
- [ ] Present to Maximo Support team for feedback 
- [ ] Update final document to support site (if approved)

**Comment by rebekkabry** [comment]
@ReneVarg25 Created documents. Can be found on[ Issue 17275](https://github.com/cityofaustin/atd-data-tech/issues/17275)
