### ISSUE TITLE
Enhancement: Add Supervisor Comment & Contractor Pick-Up fields to Comm Work Order

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#17067]
Requested by: Harrell 

**Related to a problem?**
- The communications teams issues work orders out to Contractors regularly

**Desired Outcome?**
- To see these fields on the `Scheduled Work` new work order form 
![image](https://github.com/cityofaustin/atd-data-tech/assets/61209591/0fda012d-30eb-410c-beef-632af1e2c284)
- Add `Supervisor Comment` field to the New Work Order form for `Scheduled Work` and `Trouble Call` and the edit form

**Comment by ChristinaTremel** [comment]
## Notes
- [x] Added `SUPERVISOR COMMENT` to Trouble Call Work Order form
- [x] Added display rule and tested the form to ensure that the field was showing only for Communications and hiding for the rest of the work groups
  <img src="https://github.com/cityofaustin/atd-data-tech/assets/61209591/9e4e3407-90ae-4991-954a-54c04eea6f32" width="400">
- [x] Added the following fields to Scheduled Work Work Order form
   - `SUPERVISOR COMMENT`
   - `Contractor Pickup`
   - `Contractor Company`
   - `Contractor Contact Name`
   - `Contractor Contact Phone Number`
- [x] Added display rule and tested the form to ensure that these fields were showing only for Communications and hiding for the rest of the work groups
   <img src="https://github.com/cityofaustin/atd-data-tech/assets/61209591/de21a75c-5b20-4b1d-a0fa-3df3d05b08d5" width="400">
- [x] Added additional display rule to hide the contractor details if `Contractor Pickup` is no
   <img src="https://github.com/cityofaustin/atd-data-tech/assets/61209591/c2e0da11-b7e8-4bc2-87ac-f10f6372c173" width="400">
