### ISSUE TITLE
Filter Out Financials TKs Not Active in eCAPRIS

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#17078]
> What application are you using?

AMD Data Tracker

> Describe the problem.

Need to Filter out TK's that show as non active in ecapris from work orders.

> Describe the outcome you'd like to see when this feature is implemented.

Employees will no longer be able to select inactive TK's when creating work orders causing financial problems.

> Describe any workarounds you currently have in place or alternative solutions you've considered.

Ronnie Bell

> Is there anything else we should know?

Next two weeks.

> Requested By
Jorge G.

Request ID: DTS24-114515

**Comment by KaroEngstrom** [comment]
### Wed 5/1/24
- Jorge came by to ask about this and we took a preliminary look with Christina
     - specific task order form we looked at is [Signals | New Work Order (Scheduled Work)](https://builder.knack.com/atd/amd/pages/scene_1311/views/view_3210/form/inputs)
   ![image](https://github.com/cityofaustin/atd-data-tech/assets/100615928/c9594456-951e-4a32-8fd9-090cd6cb873c)

- [`financials_task_order` ](https://builder.knack.com/atd/amd/schema/list/objects/object_86/fields)
![image](https://github.com/cityofaustin/atd-data-tech/assets/100615928/d1edef6f-7c9c-4272-a247-04115aa733e2)

- Deactivate? MC field has conditional If Blank > No
     - This field hasn't been updated in records since 2023  
- TK_TYPE MC field actually showed changes from today and more consistently in 2024

**Comment by ChristinaTremel** [comment]
## Notes
- [ ] Update Task Order filters on the Scheduled Work and Trouble Call Work Order forms to filter `STATUS` is `Active`
- [ ] Find other forms that use the Task Order field and filter out that detail

**Comment by ChristinaTremel** [comment]
- [x] Charlie worked on updating the task orders #18017, so task orders are accurately showing as `Active`
- [x] Updated Task Order filters on the Scheduled Work and Trouble Call Work Order forms to filter STATUS is Active
   - ![image](https://github.com/user-attachments/assets/35542a22-1739-47ff-b1a7-4cc152eec8d0)
- [x] Added filter to task order field on Project Intake pages as well
- [x] Went through various pages and didn't see any other places to add the filter.

**Comment by ChristinaTremel** [comment]
Reviewed this during the AMD sprint review last week!
