### ISSUE TITLE
Looking for a new process/technology solution for time and attendance in Street and Bridge (SBO)

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#17133]
> Describe the problem.

The current system of tracking attendance in SBO is antiquated and cumbersome. It requires ten superintendents across four locations printing multiple sign-in sheets every day and having their line staff write down: time in, time out, total hours, time code, and a signature.

These superintendents are responsible for reviewing the sign-in sheets and filling in any missing information. They scan a total of eighteen sign-in sheets and send them to Operations Consulting, where the sheets are again reviewed for accuracy and completion. Once Operations Consulting has assessed the status of each sign-in sheet (On time, complete, incomplete, or missing), they then either contact the superintendent to get the sheet completed, or they file the document into a database for storage. 

This process has many steps and requires all parties to be punctual and steadfast in their participation. When the process is not executed as intended, accurate attendance tracking begins to drop. 

> Describe the solution you have in mind.

Operations Consulting began searching for a solution that would incorporate the positive aspects of the UER Compumatic trial (See workarounds section below) while replacing the infrastructure and staff needed to maintain it on a larger scale. A cloud-based timeclock system is the solution identified. 

The solution should contain the following parameters:
•	Painless punch in/ punch out process for end users, preferably using an RFID or COA badge.
•	Adjustable user interface for employees and managers.
•	Vendor-provided back-end support for cloud storage and cloud application(s).
•	Attendance information that is easily comparable with UKG.
•	A function for managers to pull multiple types of attendance reports.
•	Transparent, secure data collection that must be provided and destroyed at contract termination.

> How will we know that our solution is successful?

The solution will be considered successful once a better solution is implemented, and sign-in sheets are no longer needed.

> Users

Everyone in SBO (250+ People). 
That will consist of roughly 20 people in a managerial role and 230 people in an employee role.

> Sponsorship

David Andersen

> Which Strategic Direction 2023 “Mobility” indicators would this new application impact?

['None']

> Which Austin Strategic Mobility Plan goals would this new application support?

['None']

> Describe the outcome you'd like to see when this feature is implemented.

1. When employees record their attendance, a time stamp is created.
2. Attendance tracking becomes digital. Sign-in sheets are no longer used.
3. Managers in SBO will have the ability to access their employees' attendance from an application and be able to pull reports from said application.

> Describe any workarounds you currently have in place or alternative solutions you've considered.

Operations Consulting implemented a trial run of an electronic timeclock with the UER work group to investigate replacing the use of sign-in sheets. This timeclock, the Compumatic XLS 21 v2, requires a power source and an ethernet cable attached to a computer running the CompuTime 101 database software. To use this device, each employee retrieves an RFID badge from their supervisor’s office and swipes the badge across the time clock to punch in or out. Afterwards, the employee replaces the badge in the supervisor’s office. This process requires the employee to interact with the supervisor and makes a time stamp at an exact time. Towards the end of the work week, Operations Consulting analyzes all the time punches and highlights missed punches and/or double punches for supervisors. They then create attendance reports using the time clock software and send them to UER’s superintendent and supervisors. UER’s management can then use the reports to audit their crew’s attendance and UKG time entries. 
    This trial run of the Compumatic time clock system has been considered a success after receiving overwhelmingly positive feedback from UER’s management team. 

Ops Consulting did however discover several detractors when considering implementation on a larger scale. While the timeclock is Wi-Fi capable, Ops Consulting was never able to utilize the Wi-Fi. Even after whitelisting the device, the timeclock still would not wirelessly connect to the local network. When considering the size of SBO, a minimum of nine timeclocks would be needed, and those clocks would be installed across several different buildings and networks. SBO does not have the support staff necessary to maintain such a system, especially if these systems have to use individual databases. Beyond the networking, infrastructure, and coordination necessary to connect these different systems together, it would also require staff to create reports and audit punch accuracy. 

TLDR: The timeclock trial worked great at a work group scale (35 people in one building) but hit a roadblock at a larger implementation.

> Is there anything else we should know?

Identifying a solution and implementing it at a brisk pace would be ideal, but as long as steady progress is made, we are flexible.

> How have other divisions/departments/cities addressed similar challenges? 

To my knowledge, other departments use systems that have been developed by DTS or they only use UKG (which records hours worked but not attendance). 

> Requested By
Greg G.

[Attachment](https://api.knack.com/v1/applications/595d00ebd315cc4cb98daff4/download/asset/66351d330cdf0c00280ac0c4/3cloudbasedtimeclocks.docx) (13.96kb)

Request ID: DTS24-114610

**Comment by dianamartin** [comment]
# 5/6/24
- [x] Emailed Ben E. (BSD), Chief Admin Officer, he put me in touch with Christopher A. (BSD)
- [x] Called Christopher and synced on what our stakeholders were trying to do

## Meeting Notes
HID I class reader 

(non-RFID)

- ability to read by different card readers

26 bit badge with bar code on the back

Badge Reports

- Normally reports provided only if HR has an escalation
- Investigation going on
- 

AE/AW - not standardized

- Library
- Aviation
- That is a project they’re working on now to standardize those readers

Building Services - 70% of badges that work throughout the city

Discussed talking to the vendor to see if there’s a way to get the reports (remotely for stakeholders)

- Initial thought: badge reader affixed to a wall and get badges to scan at those locations
- I told him SBO was interested in 9 locations around the city
- He’d talk to the vendor to see what the cost to do something like that is
- They had an internal process where they have security officers needing to go to specific doors at night and they do a similar process.
- He’ll get back with me in a couple of days

**Comment by dianamartin** [comment]
# 5/9/2024
## Peggy's Findings on Field Ops Time & Attendance around COA
## AE Process
- Paper 
- Go back from field and enter into Maximo
- individual responsible for entering their time
- They're implementing it now
- Use tablets to capture their work and time

## WPD Process
- Paper sign in process
- Enter time into Maximo
- Use tablets to capture their work and time

**Comment by dianamartin** [comment]
# 5/9/2024
## Cloud Vendors
### uAttend
- This choice has the best built website and the most information available. 
  - $179 per clock x 9 clocks = $1,611
- Monthly pricing is $174 for unlimited employees + $12 for each clock over the first two = $258/month.
- First year cost estimate: $4,707. Reoccurring annual cost estimate: $3,096.
- Time Clock: [Touch Tablet WiFi Time Clock – JR2000 - uAttend](https://uattend.com/product/touch-tablet-wifi-time-clock-jr2000/)
- Software: [Cloud Software - uAttend](https://uattend.com/cloud-software/)
- Walkthrough Video: [uAttend Sales Demo - 3.24 update (youtube.com)](https://www.youtube.com/watch?v=n0QDN_Gy5Jw)

### Lathem PCPROX Time Clock + PayClock Online Software
- Pricing is only available with a quote. They require scheduling a meeting with them to learn more. 
  - Companies that use Lathem: DQ, Holiday Inn, and State Farm.
- Time Clock: [RFID Proximity Badge Time Clock System | Lathem](https://www.lathem.com/time-clocks/time-clocks-for-payclock-online/pcprox-proximity-badge-touchscreen-time-clock)
- Software: [Online Time Clock Software for Employee Time Tracking | Lathem](https://www.lathem.com/payclock-online/payclock-online-time-clock-software)
- Product Video: [Lathem PCPROX Product Video - YouTube](https://www.youtube.com/watch?v=a1tNrY3ApU8)

### Allied Time USA
- Cheapest option. This company sells competitors’ brands (including Lathem), but this choice is their own in-house time clock. They offer government contracts. Free lifetime support and warranty.
- Each clock is $199 x 9 clocks = $1,791
- Monthly Pricing is $100 for 100 to 250 employees + $10 per time clock beyond the first = $180/month.
- First year cost estimate: $3,951. Reoccurring annual cost estimate: $2,160.
- Time Clock: [Web-Based Multi-Scan Biometric Time Clock - Allied Time](https://www.alliedtime.com/Web-Based-WiFi-Badge-Biometric-Time-Clock-System-p/alliedtime-cb4100.htm)
- Software: [cloud based employee time tracking software (alliedtime.com)](https://www.alliedtime.com/Cloud-Bio-Web-Based-Time-Clock-Software-p/alliedtime-cloudbio.htm)
- Video: [Online Employee Time Clock for Businesses ⏰ | Affordable Web Based Time Keeping Solution & Reporting (youtube.com)](https://www.youtube.com/watch?v=tV2YY44PGL4)

**Comment by dianamartin** [comment]
# 5/17/24
Recapping for Dave what was discussed in the last meeting

## Follow-up Actions (from last meeting)
### Set up meeting with Nikki F. (WPD HR)
- to ask more questions about process

### Inventory Android tablets
- formerly SMD devices
- Ask Scott/Cathy K. /Jordan G.

### Assess UKG Training level of effort
- Several in-person sessions with hardware device
- Overtime/TKs
- UKG Development Environment

## Do more discovery Punch In/Out functionality
- Might need to ask CTM UKG training team about this
- Continue to follow up with Christopher A. (BSD)
- followed up on 5/9/24, continue to follow up with him

--------------------------------------------------------------

# Option 1 - Re-establish UKG Training in SBO 
- [ ] Sourcing hardware (AMD/SMD Android tablets)
  - [ ] follow-up on tablet utilization Scott/Billy B.- Diana
  - [ ] potentially 29?
- [ ] Talk Jennifer/Adan about UKG training effort
- [ ] Time frame 
- [ ] Training audience

# Option 2 - Identify technology solution that uses current badges
Features
- [ ] non-RFID reader
- [ ] cloud hosted database
- [ ] simple installation complexity 
- [ ] reports (API feature)

Access
- accessible to (supervisors and superintendents) for timesheet sign off
- overall time and attendance monitoring, OT tracking - Greg G. 

# Option 3 - BSD Solution - badge readers 
- (COA hardware)
- [ ] Submit CTM Ticket BSD - Assign to Christopher A. 
- [ ] Price?
- [ ] How many readers: 9
- [ ] How does reporting work? Badge ID<>Employee ID
  - know who their supervisor is
- [ ] How can people access? 

## Validating Timesheets per CompuTime 
- Greg sends 2 reports (excel spreadsheet) per week to supervisors, on Thursday AM. and on Monday AM
- Supervisors can review those and reconcile them to UKG timesheets
- List: Big list of employees Time In/Out 
- accidentally punched DUPS
- skipped punches
- Supervisor's Actions
  - follow up with employee on discrepancies
  - forget to badge in?
  - badged in twice?
- Would like to ideally have supervisors have the ability to access that information (read only)
- daily basis

**Comment by dianamartin** [comment]
# 5/29/24 
- Diana submitted CTM ticket in ServiceNow
- BSD commented on 05-22-2024 11:56:55 CDT - Letisha S. Additional comments
>An email has been sent to Chris Adams for further assistance. Thank you.

**Comment by ChristinaTremel** [comment]
### Updates on UKG Test
- Messaged Armelle and asked whether the test environment was still available for us to use
- She looked into it and said: 
   > Christina, the test environment is being used for workday testing  and is not available at this time. I will bring it up in our core team call on Tuesday to see what can be done

**Comment by dianamartin** [comment]
# 6/14/24
I luckily was on a email thread with one of the BSD Directors and asked about my CTM Ticket I put into BSD. `INC0394268`.

Received a call from Christopher A. (BSD), he said
- They'll be on a call with a vendor technician 
- Right now, the only way to access a report is to be given "Administrative" privileges
- going to see if a report can be run & emailed to an email, will be able to get me answer by tomorrow. 
- I also asked him about how much the badge readers are
  - $300/device (9) - $ 2700
  - $500/software license seat per device (9) - $4500

So I'm guessing...
- $7200 implementation
- $4500 yearly

**Comment by maccallump** [comment]
6/17/2024:

Questions: What is the current path to a solution?

**Comment by dianamartin** [comment]
# 7/8/24
- Reiner emailed requesting a project status update. Jennifer and Dave also cc'd, messaged me asking about an update. 
- I replied and gave them and update
>I had reached out to BSD, Christopher . and he was supposed to get back to me about whether the vendor could do scheduled reports with the badge reader system. I need to follow-up with him again. 
- I told Dave A. more about the pricing I had been given from BSD as well, part of my 6/14/24 update.
- I called my BSD contact, Christopher A., to ask if he was able to ask the vendor about the functionality for a scheduled report.

**Comment by ChristinaTremel** [comment]
- This was the initial epic we used to track the progress of this request, but this has now turned into a project. 
- Created project index #18454
- Closing this out because in our discovery of potential solutions, we've decided to move forward with using a Knack-based solution.
