### ISSUE TITLE
Bug: TCI Inspection Attempt Type 'Return To Work' (TL)

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#1713]
### As the system, when a 'Return to Work' attempt is saved on  50685 Traffic Control Inspection, I need to update the folder status to be whatever was in place when the 'Project Suspension' attempt was saved. 

**Stakeholders:** Paloma, Ryan M., Kim
**DTS Manager:** Tracy Linder

**Further Info:**
- 'Return to Work' is only used by staff when 'Project Suspension' has previously been saved
- When 'Project Suspension' attempt is saved, the folder could be in any valid status
- When 'Project Suspension' attempt is saved, the folder status updates to 'Suspended'
- When 'Return to Work' is saved, staff expects the folder status to update to whatever folder status was in place when the 'Project Suspension' attempt was saved
    - Currently the system updates folder status to 'Active', which creates issues for staff, and customers. This is problematic for any scenario in which the folder was not 'Active' when the Project Suspension took place. 

**Acceptance Criteria:**
- 'Return to Work' attempt on 50685 Traffic Control Inspection will not save if 'Project Suspension' attempt does not already exist.
- Saving the 'Return to Work' attempt will update the folder status back to what is was when 'Project Suspension' was saved
    - Exception: The folder status should not update to 'Active' if the folder expiration date is in the past. Instead, it should update to 'Expired.
- These features work on the following folder types: DS, EX, RW, ECV
- These features work not just once, but as many times as needed on the same process

![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/2e334d87-635f-4a8a-ac72-578bfee679ec)

*Migrated from [atd-amanda #217](https://github.com/cityofaustin/atd-amanda/issues/217)*

**Comment by amenity** [comment]
Need to clarify if this is still broken.

**Comment by SurbhiBakshi** [comment]
- [ ] Contact Paloma to see who could show me process and and give me more details. 
- [ ] Set up meeting to see process and get more details
- [ ] put in a Help Desk ticket

**Comment by SurbhiBakshi** [comment]
[Email Correspondance - TCI_Inspection_Attempt](https://app.zenhub.com/files/140626918/027c8327-7a23-464e-8c6d-7fe3ce865b67/download)

**Comment by amenity** [comment]
@TracyLinder  - this might need to be broken up before submitting to CTM.

**Comment by TracyLinder** [comment]
@Sreelatha-BlazeKannan  can you please add an estimate to this?

**Comment by TracyLinder** [comment]
Subha sent a demo, it looks great, and I asked her to promote it.

**Comment by TracyLinder** [comment]
**Status:** Currently promoting to Dev

**Comment by SubhaShroff** [comment]
Dev Deployment Request is submitted on ServiceNow: SCTASK0079148

**Comment by SubhaShroff** [comment]
Status:
Promoted to Dev, I tested it on Dev and its working as expected. Ready for Dev Testing.

**Comment by TracyLinder** [comment]
I cannot test this; my DEV permissions need to be updated. #3206

**Comment by TracyLinder** [comment]
**Status:** Pending UAT in Dev (me). Updating to Sprint 29.

**Comment by TracyLinder** [comment]
### Tracy's DEV Testing Notes:


ROW ID | Pass or Fail | Folder Type | Notes
-- | -- | -- | --
11889620 | Passed current Requirements | RW | Will need to update requirements to allow for other attempts between   Project Suspension & Return to Work
11890050 | Passed current Requirements | DS | Same ⬆
11890036 | Passed current Requirements | EX | Same ⬆
11890757 | Passed current Requirements | ECV | Same ⬆


See t[his video](https://web.microsoftstream.com/video/9880904c-8a98-4831-81e7-4101f32714e1) recording explaining why we need to update the requirements to allow for other attempts to be made between Project Suspension and Return to Work.
@SubhaShroff @Sreelatha-BlazeKannan please let me know if you're able to view the video linked in this comment. Thank you.

**Comment by SubhaShroff** [comment]
Yes @TracyLinder, I could access the video and I totally get your point.
 
AMANDA should allow the Inspector to add other attempts in between 'Project Suspension'  & 'Return to Work'  and when Inspector tries to add 'Return to Work', the system should be looking for the recent 'Project Suspension' attempt. 

Since these two attempts can take place multiple times, I will have to look into technical details and see how I can implement it logically and will get back to you. Please let me know, if there is any detail I am missing here.

If necessary, we can discuss over a call.

**Comment by TracyLinder** [comment]
**Status:** Work in progress. Updating to sprint 30. Currently in DEV.

**Comment by SubhaShroff** [comment]
@TracyLinder  I have sent you a demo in email with subject '#1713 - Requirement UPdate - Demo'  about allowing other attempts to be made between Project Suspension and Return to Work.  Kindly let me know your views, accordingly I will proceed. Thanks.

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder , @Nadin-Nader  - Completed and submitted the changes on 07/29  and sent a demo by Subha. Waiting on feedback.

**Comment by TracyLinder** [comment]
@Sreelatha-BlazeKannan @SubhaShroff I just watched the demo & it looks great. 

### Approved to promote to DEV 🎉

**Comment by SubhaShroff** [comment]
DEV deployment request is submitted: SCTASK0089602.

**Comment by SubhaShroff** [comment]
@TracyLinder @Nadin-Nader  #1713 is DEV deployed. I tested it for the updated functionality. Its ready for your testing.

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder , @Nadin-Nader  - Completed by Subha and sent the Demo on 08/25/2020

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @SubhaShroff I have reviewed the demo from the 25th and it looks to be good to go.

**Comment by TracyLinder** [comment]
@Sreelatha-BlazeKannan @SubhaShroff 
### This is approved to promote to DEV

**Comment by Nadin-Nader** [comment]
Approved Commit ef2298fb1d60 for the move to DEV

**Comment by shroffjs** [comment]
Thank you @Nadin-Nader. 
SCTASK0096074: Dev Deployment Request is submitted.(9/17/2020)

**Comment by shroffjs** [comment]
@Nadin-Nader @TracyLinder   The new exception change is successfully depolyed in DEV. I have tested it for the entire Acceptance Criteria. Its ready for you testing.
@Sreelatha-BlazeKannan @vschandramouli

**Comment by Sreelatha-BlazeKannan** [comment]
**Status**
@Nadin-Nader @TracyLinder - Ready for DEV UAT

**Comment by TracyLinder** [comment]
@Sreelatha-BlazeKannan @SubhaShroff 

I did as much UAT in DEV as I could, but ran into a permissions issue. I think we should go ahead to test though. 

### Approved for Test 🎉

**Comment by shroffjs** [comment]
Thank you @TracyLinder.
@TracyLinder, @Nadin-Nader @Sreelatha-BlazeKannan TEST deployment request is submitted : **SCTASK0099061**

**Comment by shroffjs** [comment]
@TracyLinder @Nadin-Nader @Sreelatha-BlazeKannan tested in TEST. Its ready for your testing.

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder @Nadin-Nader - Ready for UAT in TEST.

**Comment by TracyLinder** [comment]
### Approved for PROD 🎉

**Comment by shroffjs** [comment]
@TracyLinder @Nadin-Nader @Sreelatha-BlazeKannan PROD deployment Request is submitted: SCTASK0102055.

**Comment by shroffjs** [comment]
@TracyLinder @Nadin-Nader @Sreelatha-BlazeKannan PROD deployment is done. SCTASK0102055 is closed.

**Comment by TracyLinder** [comment]
Awesome work! I have informed stakeholders; closing ticket.
