### ISSUE TITLE
OCE Mixes Light Usability Testing 5/7/24

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#17159]
### DTS will observe OCE staff perform certain tasks in the new app.
_The meeting recording is [here](https://cityofaustin-my.sharepoint.com/:v:/g/personal/tracy_linder_austintexas_gov/EYMMwdMUh7dDqH3O9pXa9o4BF9fbKeP_oOt003HLjXHp7g?referrer=Teams.TEAMS-ELECTRON&referrerScenario=MeetingChicletGetLink.view.view)._

**Tasks:**
- [x] Create a new producer
- [x] Add a new mix from the producer page
- [x] Add mix attachments
- [x] Create expiration notification for the mix

**Comment by dianamartin** [comment]
# 5/7/2024
## Observe the Usability of the system
### Diana's Notes
- Include notes on using Chrome
- Remove "Sign up?"

### Create a new producer
- went to Producer page
- clicked "Add Producer" button
- Adding Producer 
- Category "Concrete Mixes"
- Added fake Primary Contact
- Add tester's email
- Clicked Submit
- Was able to see Producer in the Producer list
- Clicked "Details" page, saw primary contact 

MK response
>Seems easy, user friendly

Clicked on another details button, saw it in more details

### Input a new mix design
- Want to have plant location listed for all types
- Used calendar picker, needed to quickly go a year out
  - plant is required error coming
  - Concrete: does not require a "plant"
    - need a selection for "All Plants"
    - Clicked "Add Plant"
      - Added Plant Name
      - Certification Date
      - Plant Address St
      - Add Misc. Comment on Plant
      >like this feature
      - [ ] Need to add "Plant Number"
- Mix ID 
- Class: CLSM
- Cement Type: (Open text) Short Text
- Fly Ash Type: (Open text) Short Text
- Like that you can add miscellaneous comments

**Comment by susannegov** [comment]
# General
Separate Concrete Mix and Hot Mix Plant

- Maybe we should separate into `View Concrete Mix Producer` page and a `View Asphalt Mix Producer` page
- A producer that is doing HMAC or Concrete Mix will only do mixes for that type
- There is scenario for a single company cretaed HMAC and concrete mix
- `Edit` change to `Edit producer profile` to make it specific
![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/87550213-2915-418e-adf1-38f3a43ff323)

# Add Approved Mix
- Need a select all option for plants in concrete mix
- Need a selection for HMAC mix type
- Make plant field select multiple plant options instead of single selection
- `Class` is only for Concrete. `Type` is for HMAC (field does not exist currently)
    - `Cement Type` and `Asphalt Type` field for Cement and HMAC mix type
    - `Type` list of options specific for HMAC
    - Fly Ash is not viewable in
- Mix ID

# Add Plant
- Add a custom Plant ID field

# Add notification
- Add a field to select who to CC to we can hard code it to [`[pwdocematerialreview@austintexas.gov](mailto:pwdocematerialreview@austintexas.gov)`](mailto:pwdocematerialreview@austintexas.gov)

**Comment by TracyLinder** [comment]
### Notes

- Create new rule when clicking submit on add new producer; system should open the producer record for the user vs sending the user to the list of producers.
- Min 15:45 Plant shouldn't be required
- 19:50 Confusion over plant ID
- 22:39 Allow multiple plants?
- 23:50 Separate mix from concrete
- 26: Class selection vs type. HMAC needs different filed/data/form
- 31 Approved mix table review
- 35 Notification - update to copy OCE pwdocematerialreview@austintexas.gov
- What does the notification email instruct the producer to do?
- 46 Group producer field by type

**Comment by TracyLinder** [comment]
**DTS internal debrief scheduled for Wed (tomorrow) at 3pm**

**Comment by TracyLinder** [comment]
### Debrief Notes


New rules when creating a producer
- [ ] Open producer record after creating
- [ ] Create "All Plants" record on the plant object if the type is Concrete Mix


Update Logic on Add Mix & Add Plant forms

**Comment by TracyLinder** [comment]
@susannegov a reminder of the outstanding tasks on this issue. TY

**Comment by susannegov** [comment]
@TracyLinder This is done and good to close out. Turns out I did some of it already but forgot to write notes on it

**Comment by TracyLinder** [comment]
Good to close.
