### ISSUE TITLE
[Tech Services] TPW PC Refresh Checklist - Roy C

### ISSUE THREAD

**Issue by Matthew-M-TPW** [cityofaustin/atd-data-tech#17189]
## Steps
- [x] Talking to user about backing up their computers
- [x] Recommend user to export all bookmarks and store on OneDrive>Documents folder
- [x] Recommend user to screen shot their ex, Quick Access favorites folder, desktop files layouts, pinned applications on desktop 
- [x] Store other OneDrive>Documents folder
- [x] Check their Absolute/NetMotion profile (they need to be in TRN SAML profile)
>Ask if they access AMD traffic cameras?

## Software Checklist
- [ ] Avaya one-X phone 
- [x] Adobe
- [ ] ArcGIS 
- [ ] AutoCAD/AutoCAD 3D
- [ ] BlueBeam 
>if user wants both (Adobe & BlueBeam), ask why?
- [ ] SketchUp 
- [ ] MS Project
- [ ] MS Visio

## Hardware Checklist
Check these devices for outdated models, change their mobile power adapter (round --> USB-C)
>Does the user need a GIS Modeling computer?
- [ ]  GIS Laptop w/ specialist docking station
- [x]  Laptop
- [x]  Power supply
- [ ]  Docking station

**Comment by Matthew-M-TPW** [comment]
@Vaishnav1397 I was talking to the user he can do the swap out this Friday 5-10

**Comment by Vaishnav1397** [comment]
Checked with the user he is out on South Park location, and he would be available tmrw, day after. I mentioned we would deploy him sometime tmrw. @Matthew-M-TPW I have laptop ready we can deploy him in the morning first hour.

**Comment by Vaishnav1397** [comment]
Requested user for availability in the morning for deployement

**Comment by Vaishnav1397** [comment]
Have deployed user new laptop.
