### ISSUE TITLE
[Enhancement] Update UI of Pizza tracker in app form

### ISSUE THREAD

**Issue by susannegov** [cityofaustin/atd-data-tech#17193]
![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/5a791a18-2e55-4a5a-95a9-298ecbf2903d)

Also https://designsystem.digital.gov/how-to-use-uswds/
Called a step indicator: https://designsystem.digital.gov/components/step-indicator/
# To do
- [x] Make the current page selection a different color
- [x] match it to knack styling guidelines (nice to have)

**Comment by susannegov** [comment]
# Header
` <h1><i class="fa fa-car"></i> Chauffeur Permit Application</h1>`

# Rich Text
```
<div class="container">
	<ul class="progressbar">
		<li class="inactive">Application Information</li>
		<li class="active">Background Information</li>
		<li>Attach Documents</li>
		<li>Review &amp; Submit</li>
	</ul>
</div>
```

**Comment by susannegov** [comment]
# To do
- [ ] make the pizza cutter ui margin left
- [ ] smaller

**Comment by susannegov** [comment]
# Result 
![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/00d5e304-aa68-481a-b558-a748e67ac132)

**Comment by susannegov** [comment]
- [ ] Change to `Review` instead of `Review and Submit`

**Comment by susannegov** [comment]
# 5/14 changes
- Change to `Review Application` 
   -  `Review` felt a bit vague
- Added `margin-right: 20px` after `sub-label-step-indicator` (The 1 `of 4`)
- Increased `font-size`, `width`, `height`, and `line-height` of label to `1.5em`

**Comment by susannegov** [comment]
![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/a3599683-6652-4852-a06b-88eb1b66f2d3)
- [ ] 1 pixel misalignment

**Comment by patrickm02L** [comment]
This UI is really nice. The CSS code is pretty solid too!

```
/***************************/
/****Step Indicator *******/
/***************************/
.stepindicator {
    width: 100%;
    display: flex;
    justify-content: flex-start;
}

.progressbar {
    counter-reset: step;
    list-style: none;
    padding: 0;
    margin: 0;
    width: 100%;
    display: flex;
    justify-content: space-between;
}

.progressbar li {
    position: relative;
    text-align: left;
    width: 25%;
}

.progressbar li::before {
    content: counter(step);
    counter-increment: step;
    width: 30px;
    height: 30px;
    border: 2px solid #bebebe;
    display: block;
    border-radius: 50%;
    line-height: 27px;
    background: white;
    color: #bebebe;
    text-align: center;
    font-weight: bold;
    margin: 0 auto 10px;
}

.progressbar li::after {
    content: '';
    position: absolute;
    width: 100%;
    height: 9px;
    background: #979797;
    top: 10px;
    left: -50%;
    z-index: -1;
}

.progressbar li:first-child::after {
    content: none;
}

.progressbar li.active::before {
    border-color: white;
    background: #005EA2;
    color: white;
}

.progressbar li.active + li::after {
    background: #005EA2;
}

.progressbar li.active {
    font-weight: bold;
    color: #005EA2;
}

/***************************/
/****Label Indicators *******/
/***************************/
.label-stepindicator {
    display: inline-block;
    width: 1.5em;
    height: 1.5em;
    background: #005EA2;
    border-radius: 50%;
    text-align: center;
    font-weight: bold;
    color: white;
    line-height: 1.5em;
    font-size: 1.5em;
}

.sub-label-stepindicator {
    color: #005EA2;
    font-weight: bold;
    font-size: 1.5em;
}

.active-label-stepindicator {
    font-weight: bold;
    font-size: 1.5em;
    margin-left: 20px;
}
```

**Comment by patrickm02L** [comment]
## 5/16/24 
Reviewed this with Susanne. We discussed fixing the styling on a mobile view because the text get squished on anything less than and iPhone 12. Susanne to spend 1-3 hours working on styling afterwhich we'll make it a new enhancement to fix the mobile view.

**Comment by susannegov** [comment]
# 5/17 Tech Review
- [x] Comment out margin line 36-39 in css
```
/* .stepindicator ul{
  margin-left: 0em;
  margin-top: 0em;
} */
```
- [x] Removed `3 of 4 Attach Documents` in View Application page

**Comment by susannegov** [comment]
Was talking to charlie in my 1:1 and we found out that knack's built-in has margin-top in li +li in the css
![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/296c8d3b-638d-4b02-b558-ed0947588703)
I fixed it by doing
```
.progressbar li + li {
  margin-top: unset;
}
```

**Comment by patrickm02L** [comment]
## 5/31/24
Susanne and I chatted about this today, discussed the UI discrepancies and how it was solved.
