### ISSUE TITLE
Enhancement: Add Vacancy Report Milestone for `RECLASS - PRF Sent to Manager`

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#17237]
Requested by: 
- [x] Tina with HR requested an additional milestone to be added to the Vacancy Report: `RECLASS - PRF Sent to Manager`
- [x] Renamed `RECLASS - Request to TPW HR Date` to `RECLASS - Request to TPW HR`
  - Diana was able to add this during the sprint review

## Follow-up to do
Update these milestone options to `Other` & remove from dropdown
- Recruitment Meeting to discuss Recruitment
- HM Submitted Rec Docs for Review
- HM Signed TCSS_Identified TC
- Response from HM
- Posting Draft
- HM requested to hold off
- Approved for later posting 

Update the `Follow Up with HM` milestone: 
- Rename to `FOLLOW UP - With Hiring Manager` and move to the top of the list

**Comment by dianamartin** [comment]
# 5/10/24
- [x] Added new choice `RECLASS - PRF Sent to Manager` on `Milestone Type` field, on `pcn_date_tracking` object table
- [x] Removed "Allow users to add new options to choose"

**Comment by stephaniemoorer** [comment]
This looks to be complete. Can it be closed or does it need to be reviewed with HR team at sprint review?

**Comment by dianamartin** [comment]
# 6/26/24
I think this was reviewed at our last meeting. @ChristinaTremel do you remember if we mentioned it?
