### ISSUE TITLE
Update "Journal Voucher" info in AMD Data Tracker - Warehouse Inventory- MAY 2024

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#17302]
- [ ] Spreadsheet emailed from Finance staff month of: 12/28/23-5/13/24
- [ ] Number of records being updated: 11
- [ ] Format spreadsheet [(Review instructions)](https://atd-dts.gitbook.io/atd-knack-operations/warehouse-inventory-updating-journal-vouchers-jv-information)
- [ ] Spot check Transaction IDs, no JV information before import
- [ ] Import records
- [ ] Spot check Transaction IDs, nhas JV information after import
- [ ] Email Finance staff that update task complete
