### ISSUE TITLE
Spike: Assess current condition of the sign locations map

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#17314]
Would like to assess the level of effort to make changes to the mapbox map and consider the potential tech debt required to update this map since we haven't made any major changes since it was first implemented: 
   - [Link to Signs Work Order Details page with map](https://builder.knack.com/atd/signs-markings/pages/scene_1028) 
   - [Link to Add Locations form](https://builder.knack.com/atd/signs-markings/pages/scene_1028/views/view_2607/form)

#### Steps
- [ ] Run app locally or a test version of the app
- [ ] Scope out the current state of the map and code
- [ ] Communicate back to the dev team

**Comment by ChristinaTremel** [comment]
- [ ] Run app locally or a test version of the app
- [ ] Scope out the current state of the map and code
- [ ] Communicate back to the dev team

**Comment by chiaberry** [comment]
@ChristinaTremel I mentioned this in dev + product sync, but just wanted to document that the "populateIntersection" feature  (where someone could specify a location by inputting the cross streets) does not currently work and I don't know how long since it has worked.
