### ISSUE TITLE
Maximo Work Group Training: How to complete a USD Work Order [USD]

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#17389]
### Supervisor Hernandez requested a work group training session for staff on how to complete a USD work order. 
Training is scheduled and set for May 22, 2024 at 8900 Cameron Rd, training room

Maximo User Level: already using Maximo, Tech 2s, 3s, and Leads

## 📝 Checklist
- [x] Schedule training consultation
scheduled and completed 5/1/2024
- [x] Draft and publish #17274 
- [x] Scheduled preliminary meeting #17382 
- [x] Book training room for date and time
- [x] Create sign in sheet
Knack created: [DTS Maximo Training Sign-in Sheet](https://tinyurl.com/DTSMaximoTRN0522)
- [x] Schedule out agenda including break(s)
Google Docs created: [DTS Maximo Training Agenda](https://docs.google.com/document/d/1xYmxXDqhYwaiqBS32G0EsflZMxdvGwK9D5_ch8AlIhA/edit?usp=drive_link)
- [x] Design and publish quiz for retention via Microsoft Forms - [Course Quiz](https://tinyurl.com/DTSMaximoQuizUSDHTCWO)
- [x] Design and publish training experience survey via Microsoft Forms - [DTS Maximo Training Experience Survey](https://tinyurl.com/DTSMaximoSurvey)
- [ ] Forward meeting invite to users 
_pending Supervisor's e-mail on Monday for list of users and work orders to use_
- [x] #17440
- [x] #17439
- [x] Verify and set up Chromebooks (8 are needed)
- [x] Set up training room with snacks and bottled drinks
- [x] Complete training
- [x] Forward sign in sheet to Supervisor
- [x] Retro on training experience
