### ISSUE TITLE
Request for a Maximo Training Tracker in Knack

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#17398]
I would like for our DTS Maximo team to have a training tracker for the courses we provide for SBO staff. 

We would like to have the training tracker mirror similarly to SMD Training Tracker

**Comment by dianamartin** [comment]
# 5/21/2024
## Build Notes for SBO App
- [ ] Export list of participants in SBO - Diana
- [ ] Create new object tables, see image below
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/ad4fa4e6-e86f-4872-ba76-0d7c460e4589)
- Training Type table
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/b8849758-4d32-4d10-80ca-0e87c0033e89)
- Training Event table
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/fa0fce8c-03f7-429a-9f40-45fc885e1d5b)
- Training Attendance
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/fab5850d-c68f-47ba-9880-94f357cda62f)

**Comment by susannegov** [comment]
- [x] Added tables training attendance, training event, training type
- [x] Added Training Tracker and My Trainings Pages
- [x] Added pages 
   - Add Training Event
   - Add Participants
   - View Participants
   - View Training Event Details

**Comment by dianamartin** [comment]
# 5/21/24
- [x] Export list of participants in SBO - Diana
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/3cf3d094-c049-4324-b5a4-88792a73049e)
- [ ] Removed Supervisors/Superintendents/DMs from each Division
  - [ ] District
  - [ ] Pavement
  - [ ] Utilities

**Comment by dianamartin** [comment]
# 5/21/24
Adriana replied
>I LOVE IT! Thank you!! I also wanted to see if the Training Event Name could be a drop down? Like this?
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/d3ffd658-e131-4460-a564-64f79bf791f1)
This is amazing, thank you again for putting it together so quickly!

I replied
>I added it
