### ISSUE TITLE
Batch upload of TRP contractor work orders

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#17529]
> What application are you using?

Other / Not sure

> Describe the problem.

Batch upload of contractor work orders.

> How soon do you need this?

Soon — Within a week 

> Is there anything else we should know?

Would like to get work orders uploaded to Knack so TRP Contractors can continue working without interruption. 

> Requested By
Jordan G.

[Attachment](https://api.knack.com/v1/applications/595d00ebd315cc4cb98daff4/download/asset/66551eee11e6f8027610602e/trpcontractorworkordersbatch23.xlsx) (52.24kb)

Request ID: DTS24-115085

**Comment by ChristinaTremel** [comment]
### Batch 3 
- [ ] Batch loaded `255` records by following steps from issue #11882 and used `Created Date` 5/31/24 because no records were created that date
- [ ] Successfully batch loaded and confirmed that there were 255 work orders in the `NEED TO BE ISSUED` status on the front end ✅
- Had to manually update Street Name, From Street, To Street on some records: 
   - [ ] `Street Name` is blank = 1 record
   - [ ] `From Street` is blank = 5 records
   - [ ] `To Street` is blank = 5 records
- [ ] Updated all 255 records created today - `Assigned Contractor` and `Assigned to` to set to TRP
- [ ] QC'd the `NEED TO BE ISSUED` work orders on the front end and looked to be configured correctly
   - Ref ID: 2416
   - Ref ID: 2326
- [ ] Batch updated all 255 records to be `ISSUED` to TRP
![image](https://github.com/cityofaustin/atd-data-tech/assets/61209591/ffea66ae-6b6f-46d9-8c47-12f61de7e44c)
- [ ] QC'd same reference IDs above and they are showing up correctly in the `ISSUED` status
- [ ] Message Jordan and Cole letting him know this has been completed

**Comment by ChristinaTremel** [comment]
This was completed and Jordan was notified June 6th. Closing this!
