### ISSUE TITLE
Build out Daily Vehicles & Tools Checklist

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#17557]
# Build Notes for the first form

## Form 1 - Daily Vehicle & Tools Checklist 
- [fleet_vehicles](https://builder.knack.com/atd/amd/schema/list/objects/object_73/fields)
   - `VEHICLE_DISPLAY_NAME`
- New Object: `fleet_vehicles_tools_inspection`
   - Inspected By (Created By field)
   - Inspected Date (Created Date field)
   - Fields for inspecting - multi-choice fields (Choices `OK` or `NO`)    
      - HEADLIGHTS
      - FRONT BLINKERS
      - WINDSHIELD
      - WIPERS
      - MIRRORS
      - REAR BLINKERS
      - BRAKE LIGHTS
      - TIRES
      - BUCKET LANDED PROPERLY
      - BUCKET COVERED
      - BED CLEAN &   ORGANIZED
   - Tool Options (reference [Unit Option 1 field](https://builder.knack.com/atd/signs-markings/schema/list/objects/object_203/fields/field_4151/settings) in SMD Data Tracker
      - MILWAUKEE HAMMER DRILL
      - MILWAUKEE SAWZALL
      - MILWAUKEE COMPACT BLOWER
      - MILWAUKEE 5.0 AH BATTERY
      - MILWAUKEE 4.0   AH BATTERY
      - MILWAUKEE CORDLESS DRILL
      - FIRE EXTINGUISHER
      - BUCKET COVER

**Comment by dianamartin** [comment]
# 6/12/24
- [x] Create new object table `fleet_vehicles_tools_inspection`
- [x] Created Field Headings
  - [x] Inspected By (Created By field)
  - [x] Inspected Date (Created Date field)
  - [ ] Inspection List

Fields for inspecting - multi-choice fields (Choices OK or NO)
- HEADLIGHTS
- FRONT BLINKERS
- WINDSHIELD
- WIPERS
- MIRRORS
- REAR BLINKERS
- BRAKE LIGHTS
- TIRES
- BUCKET LANDED PROPERLY
- BUCKET COVERED
- BED CLEAN & ORGANIZED

Tool Options (reference [Unit Option 1 field](https://builder.knack.com/atd/signs-markings/schema/list/objects/object_203/fields/field_4151/settings) in SMD Data Tracker
- MILWAUKEE HAMMER DRILL
- MILWAUKEE SAWZALL
- MILWAUKEE COMPACT BLOWER
- MILWAUKEE 5.0 AH BATTERY
- MILWAUKEE 4.0 AH BATTERY
- MILWAUKEE CORDLESS DRILL
- FIRE EXTINGUISHER
- BUCKET COVER

**Comment by dianamartin** [comment]
# 7/15/24
Synced with stakeholders and received feedback from them 

## Create email notification 
Billy/Andrew - Admin details page - Delete record
- [ ] create email notifications
- "No" answer
- Missing tools
- Concerns and Observations

## Add more criteria
- [x] Bucket Damage Y/N
- [x] Body Damage Y/N
- [x] Fluids Correct Y/N
- [x] un-require Concerns and Observations field

## Add table and details pages 
- [ ] My Work Orders
- Create Details page

Add to Manage Vehicles
- [ ] Create Details
- Add more fields 
- Create Details page

Add Manage Inspections page
- [ ] Add table 
- [ ] Add Details page

**Comment by ChristinaTremel** [comment]
- Created tool tracking yes/no field to flag when a tool is present and missing from the check boxes
- Created fields for flagging issues to create the email notifications:
   - TOOLS MISSING
   - CONCERNS NOTED
   - PROBLEMS REPORTED

**Comment by ChristinaTremel** [comment]
Billy's team is currently testing the daily vehicle and tools inspection form. Will follow up with him during the AMD sprint review to determine when we can collect feedback.

**Comment by ChristinaTremel** [comment]
This has been completed and AMD is currently using the daily vehicle check-list. It's working great and has brought up issues for them to address with the vehicles. Closing this out and will have AMD submit a new request if there additional enhancements needed.
