### ISSUE TITLE
Maximo Daily Task List - Internal Documentation

### ISSUE THREAD

**Issue by rebekkabry** [cityofaustin/atd-data-tech#17576]
# Background 
- Prepare a repository for internal processes of Maximo Common Tasks. 
- If already documented, link here. 
- Document via video record, where needed 

# Tasks
- Create Account (include communication needed, etc) 
- Modify Account 
- [Security Group Authorization Process](https://github.com/cityofaustin/atd-data-tech/issues/17579)
- [Create Start Center](https://cityofaustin-my.sharepoint.com/personal/adriana_martinez_austintexas_gov/_layouts/15/stream.aspx?id=%2Fpersonal%2Fadriana%5Fmartinez%5Faustintexas%5Fgov%2FDocuments%2FRecordings%2FMaximo%20Walk%2Dthrough%5F%20How%20to%20add%20portlets%20to%20a%20Start%20Center%2D20240603%5F133340%2DMeeting%20Recording%2Emp4&referrer=StreamWebApp%2EWeb&referrerScenario=AddressBarCopied%2Eview%2E1fea0ed8%2D87c9%2D4b06%2Daf06%2D305361f4ed68&ga=1)
   - Add Portlet 
   - [Change Portlet](https://scribehow.com/shared/Edit_Start_Center_Reports_List__fIrYheQHQwSR72JYlt6-2Q) - (How to add to Report List)
- [Escalation Process Documentation ](https://github.com/cityofaustin/atd-data-tech/issues/17352)
- [Update Work Order SI for all WO](https://github.com/cityofaustin/atd-data-tech/issues/17467)
- [Update User Rights for Domains (updating Asset Management)](https://github.com/cityofaustin/atd-data-tech/issues/17610#issuecomment-2142780245)
- Change Rights to Reports and Start Center
- Start Center Administration 
- Job Plans 
       - [How to Update and Add New Labor](https://scribehow.com/shared/Edit_Job_Plan_and_Add_New_Labor_User__TZmSrkOBTkqRX7hZyfuCSA)
       - Add Job Plan [Issue Example](https://github.com/cityofaustin/atd-data-tech/issues/16403)
- Update Failure Reporting Hierarchy  [Issue Example](https://github.com/cityofaustin/atd-data-tech/issues/17148)
- All Reporting Process
- Specification Not Captured - Grandparent Missing [Example Issue](https://github.com/cityofaustin/atd-data-tech/issues/17070)
- Training 
- Report Management 
- [Call for Query without speciifications](https://cityofaustin-my.sharepoint.com/personal/rebekka_bryant_austintexas_gov/_layouts/15/stream.aspx?id=%2Fpersonal%2Frebekka%5Fbryant%5Faustintexas%5Fgov%2FDocuments%2FMedia%20Files%2F1%5F1%2D20240612%5F153637%2DMeeting%20Recording%2Emp4&referrer=StreamWebApp%2EWeb&referrerScenario=AddressBarCopied%2Eview%2Eb4b404e8%2D3c9c%2D4c98%2Db943%2D501647d5cb01&ga=1)
- [Assign Attributes for Classifications Scribe](https://scribehow.com/shared/Updating_Attributes_for_Classifications_in_Maximo__ay2UJw9aSlu3RkL80E40DQ)
- [Bulk Work Order creation or change](https://github.com/cityofaustin/atd-data-tech/issues/17964)
- [How to call for query in search fields option](https://cityofaustin-my.sharepoint.com/personal/rebekka_bryant_austintexas_gov/_layouts/15/stream.aspx?id=%2Fpersonal%2Frebekka%5Fbryant%5Faustintexas%5Fgov%2FDocuments%2FMedia%20Files%2F1%5F1%2D20240612%5F153637%2DMeeting%20Recording%2Emp4&referrer=StreamWebApp%2EWeb&referrerScenario=AddressBarCopied%2Eview%2E8e792014%2D4ac1%2D4a27%2Db5f4%2D57d6fc492252&ga=1)
- [DT PM Monthly Report ](https://cityofaustin-my.sharepoint.com/personal/adriana_martinez_austintexas_gov/_layouts/15/stream.aspx?id=%2Fpersonal%2Fadriana%5Fmartinez%5Faustintexas%5Fgov%2FDocuments%2FRecordings%2F1%5F1%2D20240606%5F145754%2DMeeting%20Recording%2Emp4&referrer=StreamWebApp%2EWeb&referrerScenario=AddressBarCopied%2Eview%2E1049d488%2Debd9%2D4fbd%2Dbaf0%2Dc86e54283bdc&ga=1)

**Monday**
- [x] Send 311 Overdue Report
   - Work with @ReneVarg25 to see process for absence. 
- [x] Review pending reports with CTM
   - Already taken care with Ganesh - backlog clean up 
   - Reports - will be working with Ganesh 
   - Bi-Weekly meetings with CTM - they will keep us in the loop about ESB (communication with AW,311), outages, MAXIMO moving slow, SR issues in the system. 
- [x] ~Prepare agenda for Maximo sync~
- [x] Schedule Mini - Syncs to continue with Ganesh and Rene 
   - We are doing as a team 
   - Mini Sync - need to have a space to discuss individual projects and scoping (Bi-Weekly) 
        - Bi-Weekly 1:1 for scoping
   - Maximo Sync - higher level of projects, not a great space for individual issues. 
- [x] PM Downtown Maintenance WO per Month Data Load Needed (speaking with Ganesh about automation)  - PM creating WOs at the end of the month. _(see recording)_ 
  - performances on how often, what is used, etc. 
   - @adry-martinez will follow up with Ganesh on the status of these automated reports? 
     - Preventative Maintenance Tab in MAXIMO 
       - PM - `SBODTE`
       - Generate Work Order (uncheck frequencies) 
       - Add the name of the month to the report (after the report creates) 
       - go back into SBO Work Order Tracking screen 
       - Reported Date: type `TODAY`
       - Description `PARENT`
       - Look for the grandparent for the parent 
       - Add the Parent Work Order 
       - "Sidewalk Cleaning, Month, Parent FYYY
       - Send email that says here are the work orders for the month of X. 
       - POC = Vincent G. 
 
   
**Tuesday**
- [x] ~Utilities and Structures Data QR~
  - Do not worry, these are being sent out weekly. 
  - Will also discuss during stakeholder meetings.
- [x] Follow up with AWU re: monthly data consolidation report by Rene 
   - SBO AWU report for month
   - Report: SBO AWU Locations Response 
   - Pull report and send. No changes needed. POC Casey, get emailed report and if something breaks. 
   - Get added to the email from Casey
- [x] Complete 311 Data Quality by Rene 

**Wednesday**
- [x]  District Maintenance Data QR
   -  Continue to discuss during stakeholder meetings 

**Thursday**
- [x] Pavement Ops Data QR 
   -  Continue to discuss during stakeholder meetings 
- [x] Draft Maximo Newsletter
   - Quarterly - Rene has been spearheaded this 
   - Last One: 
- [x] Check in with PCs to see if they need Maximo support
   - We are already working with them on stakeholder recurring meetings. 

**Friday**
- [x] ~Review 16111 Austin 311/SBO~
- [x] 311 Data Quality by Rene 

**When Maximo is Down Process**
[Maximo Outage Notification Process Document](https://docs.google.com/document/d/1eUo6dOUTOrpj98hLMy5u5Z8jqwBK3LkIvMKBywWV5No/edit?usp=drive_link)

**Comment by rebekkabry** [comment]
# 6/6/24 

- Worked with Adry to map out daily tasks. 
- Still building on support

**Comment by rebekkabry** [comment]
# End of Month Deliverables and Notes 

![image](https://github.com/user-attachments/assets/a1597b22-d131-4d37-8466-549f2cea37f6)

**Comment by ReneVarg25** [comment]
@rebekkabry @dianamartin is this effort still needed?

**Comment by dianamartin** [comment]
# 6/22/2026
- This issue was used to track and identify Maximo admin tasks when Adry was transitioning away. We've moved all this information into our GitBook docs.
