### ISSUE TITLE
[Tech Services] TPW PC Refresh Checklist - Michael K

### ISSUE THREAD

**Issue by Matthew-M-TPW** [cityofaustin/atd-data-tech#17654]
Michael K 

## Steps
- [x] Talking to user about backing up their computers
- [x] Recommend user to export all bookmarks and store on OneDrive>Documents folder
- [x] Recommend user to screen shot their ex, Quick Access favorites folder, desktop files layouts, pinned applications on desktop 
- [x] Store other OneDrive>Documents folder
- [x] Check their Absolute/NetMotion profile (they need to be in TRN SAML profile)
>Ask if they access AMD traffic cameras?

## Software Checklist
- [ ] Avaya one-X phone 
- [x] Adobe
- [ ] ArcGIS 
- [ ] AutoCAD/AutoCAD 3D
- [ ] BlueBeam 
>if user wants both (Adobe & BlueBeam), ask why?
- [ ] SketchUp 
- [ ] MS Project
- [ ] MS Visio

## Hardware Checklist
Check these devices for outdated models, change their mobile power adapter (round --> USB-C)
>Does the user need a GIS Modeling computer?
- [ ]  GIS Laptop w/ specialist docking station
- [x]  Laptop
- [ ]  Power supply
- [ ]  Docking station

**Comment by Matthew-M-TPW** [comment]
@JBStrange is going to meet user at PDC on Friday to swap the computer out

**Comment by Matthew-M-TPW** [comment]
@JBStrange deployed the computer to user

**Comment by Matthew-M-TPW** [comment]
The user called me asking for assistance with Teams, One Drive, and Amanda. 

Helped user with One drive but was unable to help with Teams. 

Going to meet the user on Monday

Moving ticket to in progress

**Comment by Matthew-M-TPW** [comment]
Assisted user

**Comment by Vaishnav1397** [comment]
Do not delete

Michael K
