### ISSUE TITLE
Update "Journal Voucher" info in AMD Data Tracker - Warehouse Inventory- June 2022

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#17667]
- [x] Spreadsheet emailed from Finance staff month of: June, 12/28/23-5/30/24
- [x] Number of records being updated: 299
- [x] Format spreadsheet [(Review instructions)](https://atd-dts.gitbook.io/atd-knack-operations/warehouse-inventory-updating-journal-vouchers-jv-information)
- [x] Spot check Transaction IDs, no JV information before import: 39035 ✅ 
- [x] Import records
- [x] Spot check Transaction IDs, has JV information after import 39035 ✅ 
- [x] Email Finance staff that update task complete
