### ISSUE TITLE
Feature: MMC Situational Awareness Dashboard

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#1767]
_**Requested By**: Lance B., MMC_

**How would you rate the impact of this issue?**
- [ ] 0 - No Data Available 
- [ ] 1 - Severe Impact to Services
- [ ] 2 - Major Impact to Services
- [ ] 3 - Minor Loss of Services
- [x] 4 - Does Not Affect Services

**Is your feature request related to a problem? Please describe.**
- Sometimes MMC Operators are handling multiple issues and don't have time to specifically pass off an issue to another operator although it is important
- Flashing signals are important to attend to, but they get lost in the list. Can come in as “Signal on Flash” (if created by MMC) or “Signal Maintenance” + “Flashing” (from a 311 SR)
- When managers and decision makers arrive at the MMC, there is no quick way for them to assess system status and see high-priority issues

**Describe the solution you'd like**
First pass:
- A Data Tracker page that shows high priority information on system status. 
   - List of all currently flashing signals
- Display to have 👆visible in the room at all times

Next: 
- Next, ability to flag other issues as "major" and have them appear

*Migrated from [atd-knack-data-tracker #258](https://github.com/cityofaustin/atd-knack-data-tracker/issues/258)*
