### ISSUE TITLE
Olivia L first day checklist

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#17755]
[Gitbook link](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-LzDGg7hKQ_fUjXnzGGx/onboarding/welcome-to-dts#day-1)

- [x] Log in to your City of Austin email
- [x] Install [Microsoft Authenticator app](https://atx.servicenowservices.com/sp?id=kb_article&sys_id=b46a964d1b5a35d0e8dfc844604bcb01)
- [x] [Set up your email signature](https://docs.google.com/document/d/1OAoBll9rIl6XZq2uOShm5HCbHJboOt0SLP_wK6tjkEE/edit)
- [x] If you don't have one already, [create a Github account](https://github.com/join) and then ask your supervisor to add you to the City of Austin [Transportation Github Team](https://github.com/orgs/cityofaustin/teams/transportation/members)
- [x] Enable [two-factor authentication for your Github account](https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa) 
- [x] Install [Zenhub Browser Extension](https://www.zenhub.com/extension)
- [x] [Create a Google account for your Austintexas.gov email address](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-LzDGg7hKQ_fUjXnzGGx/basics/document-storage/using-google-as-a-city-employee)
- [x] Install Slack desktop client: [Windows](https://slack.com/downloads/windows) | [Mac](https://slack.com/downloads/mac)
- [x] Post your [daily standup in Slack](https://atd-dts.gitbook.io/wiki/slack#daily-stand-up)
- [x] Install [1Password browser extension](https://1password.com/downloads/browser-extension/)
- [x] Upload a headshot [here](https://drive.google.com/drive/folders/1y_yhkZQE5uSRhLZAHJn2kFuXPBixVJ2G) and add your title and preferred pronouns [here](https://docs.google.com/document/d/1gRjTic8FD3s-t0sVZhErAidMIAktU-0Vn2GYPpPcUeg/edit) (Google Drive access must be set up first)
- [x] [Create a Github issue](https://github.com/cityofaustin/atd-data-tech/issues/new) for adding yourself to the [DTS "About Us" webpage](https://austinmobility.io/about) (labels: Service: Dev, Type: Operations, Product: DTS Website) including the link to your photo and preferred pronouns
- [x] [Open a service request](https://atx.servicenowservices.com/sp?id=sc_cat_item&sys_id=02e490c6db7f1300a314e1c2ca9619e6) with Communication and Technology Management (CTM, the City's internal enterprise IT department) to request a Miro account. (Patrick)
- [x] Familiarize yourself with the [DTS Resource Index](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-LzDGg7hKQ_fUjXnzGGx/resource-index)

Ask questions! Be a sponge and absorb it all! 🧽💦🌈

**Comment by patrickm02L** [comment]
## 6/13/24

When you get to making a github Issue to be added to the DTS website following these instructions:


Create a Github issue to add yourself to the DTS "About Us" webpage:
- Title: Add [First name] [First initial of last name] to DTS website
- Labels: Service: Dev, Type: Communications, Product: DTS Website
- Assignee: Chia Berry
- Include: 
     - Link to your photo in Google Drive 
     - Full preferred name
     - Title
     - Preferred pronouns

**Comment by patrickm02L** [comment]
## 6/17
Request miro access. SR#: INC0403082
