### ISSUE TITLE
PMT Activity Tracking Module

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#17754]

**Comment by ChristinaTremel** [comment]
# Notes from Erin
## On a separate “page” for the PMT only:
Purpose of the page
   1. track activities completed by PMT for tracking of the overall project timeline (including official place to record funding agreements) 
   2. ability to add additional activities - like several iterations of cost estimates, or change of scope
   3. wrap-up project intake by issuing AMD NTP for project

## Table with PMT internal steps / tracking:

“Activity” + Radio Butto/Toggle + Open Text Box (automatic day/time stamp?) (see photo below)
- Activity: Draft cost estimate
   - Goes back to main tab for internal review and approval = final cost estimate (posted on main project page)
- Activity: Funding Authorization
   - Open form to add FDUs and distribution of funds (see photo)
- Activity: TK – can it link to upcoming TPW Finance module to initiate request?
- Activity: DO Request
   - DO executed
- Activity: Send NTP (Summary Email)- Form autofills from existing info in project record (ex: TK, FDU, Scope, etc.) and can send an email from this dashboard.  *We will need to continue scoping this
   - Creates a Scheduled Work Ticket (with basic project info and AMD scope- then inspector finishes it by adding equipment, etc. and submit.  This is potentially an enhancement to the existing Scheduled Work module in DT- see screenshot below). WRK # will be posted with the NTP for Billy and Inspectors to find??
   - Once checked, opens the Project Closeout section?

### Additional Project Activities (+ button to add the Activity (from a drop down), + radio button for completion + open text box for notes) for each of the following:  (see photo below)
- Scope Change
- Obtain new schematics
- Cost estimate revision and review
- Funding approval
- DO Increase
- TK Increase or Decrease
- Change Order items (obtaining quotes/approval)
- Permit Status (with open text box)
- AE payment
- CMTA payment
- ROW/DSD payment

Project Closeout – opens up when NTP Summary Email is sent; opens at the bottom of our PMT Internal Tracking page (same as above- has toggle for completion + open text box)
- SOS Received
- SOS signed internally
- Invoice(s) received
- Invoice(s) paid
- TK Closed
- DO Closed

*Project closed out in dashboard once all of these are selected.

 

 

 

We also have one request for the main page:

Cost Estimate Review- add another identical table to the Project Reviews (on the main page), underneath, called Cost Estimate Reviews. We will attach the cost estimate under the Attachments, and reviewers will go there to see the estimate, or it will be sent as an attachment to the review request??

**Comment by ChristinaTremel** [comment]
### Completed 6/10
- [x] Create `project_requests_PMT_activities` object with connection to the `project_requests` and create fields: 
   - project_request connection
   - Created By - connection to accounts
   - Created Date - datetime
   - Modified By - connection to accounts
   - Modified Date - datetime
   - Activity Type - multichoice
   - Activity Notes - Rich text
   - Completed By -  connection to accounts
   - Completed Date - datetime
- [x] Create `PMT Activity Tracking` page
- [x] Create table for PMT Activity Tracking 
- [x] Create button to `Add Activity` to PMT Activity Tracking table
- [x] Add record rules to the [Submit Request](https://builder.knack.com/atd/amd/pages/scene_1623/views/view_4056/form/rules/record) form to insert the standard PMT activities and set activity status to `Not Complete` which are:
    - Draft Cost Estimate
    - Funding Authorization
    - Submit TK Request
    - DO Request
    - Send Notice to Proceed
   
### Left to do
- [ ] Create button to `Close Project Activities` and add record rules to insert the standard closing PMT activities
    - SOS Received
    - SOS signed internally
    - Invoice(s) received
    - Invoice(s) paid
    - TK Closed
    - DO Closed
- [ ] Schedule work session to review the activity categories provided by Erin and miro board out what outcomes they would like to see from the activities (i.e. attach cost estimates, submit finance SR, etc)

**Comment by ChristinaTremel** [comment]
- Closing this because the rest of the changes to the Activity Tracker is on #18015
