### ISSUE TITLE
Import SBO May Inventory into the tracking module

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#17779]
Richard sent over the May inventory list following their count. 
- File: [SBO_asset_inventory_MAY.csv](https://github.com/user-attachments/files/15805989/SBO_asset_inventory_MAY.csv)
- Delete existing records from [asset_inventory](https://builder.knack.com/atd/sbo/records/objects/object_13) object
- Import the file into [asset_inventory](https://builder.knack.com/atd/sbo/records/objects/object_13) object in the Street & Bridge Operations Knack Application

**Comment by dianamartin** [comment]
# 6/14/24

**Comment by dianamartin** [comment]
# 6/25/24
- [x] Reviewed import table `SBO_asset_inventory_MAY`
- [x] Removed the last two columns (Status, Notes)
- [ ] Importing `460 records` from spreadsheet `SBO_asset_inventory_MAY`
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/e9ca88bf-cabe-4bb2-a144-a1d28a6479a7)
- [ ] Spot Check records

**Comment by ChristinaTremel** [comment]
Schedule meeting to go through the inventory that was imported.

**Comment by dianamartin** [comment]
# 7/8/24
- Met with stakeholders on 7/1/24
- Talked about normalizing several fields:
  - Divisions
  - Asset Location
  - Brand
- Richard emailed letting us know he's finished updating the "SUBCATEGORY" domains
- [ ] Cleaning up records using - [SBO_Inventory_Domains.xlsx](https://cityofaustin.sharepoint.com/:x:/r/sites/tpwDTS/_layouts/15/Doc.aspx?sourcedoc=%7BFA7EF95E-5730-4BA7-85B9-433828812B4A%7D&file=SBO_Inventory_Domains.xlsx&action=default&mobileredirect=true&wdsle=0)

**Comment by dianamartin** [comment]
# 7/9/24
- Updated filters on "SBO Workgroups" page
- [ ] Update Seal Coat 1 - `Seal Coat` - all records
- [ ] Update Seal Coat 2 - `Fog Seal` - all records

**Comment by ChristinaTremel** [comment]
Created new issue for updating filters on "SBO Workgroups" page. The May inventory import is complete.
