### ISSUE TITLE
Work Zone Data Exchange Release 1.0

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#17799]
### Create & publish a work zone data feed, and post it to the [Work Zone Data Exchange (WZDx) Feed Registry](https://datahub.transportation.gov/Roadways-and-Bridges/Work-Zone-Data-Exchange-WZDx-Feed-Registry/69qe-yiui/about_data)

**Deliverables:**

- [data feed](https://data.austintexas.gov/dataset/Work-Zone-Data-Exchange-WZDx-JSON-Feed/d9mm-cjw9/about_data)
- [tabular version](https://data.austintexas.gov/Transportation-and-Mobility/Roadway-Work-Zones/qyfh-gwei/about_data)
- [map](https://data.austintexas.gov/Transportation-and-Mobility/AMANDA-Roadway-Work-Zones/m39r-fuyi)

**Resources:**
1. TPW's [WZDX repo](https://github.com/cityofaustin/dts-work-zone-data-feed)
2. USDOT's [WZDX repo](https://github.com/usdot-jpo-ode/wzdx)

**Comment by TracyLinder** [comment]
Write AMANDA Query for ROW permits
- For start/end dates select the extension start/end unless it's null, then select the start/end
- Active status only
- Folder type RW, Subtype 50500
- Only include free-form rows related to these types of closures: alley, sidewalk, traffic lane
Setup ETL to convert into JSON format
Turn on the ETL?
Get data owner (ROW) approval
Notify interested parties
Register WZDX registry 
Gap Analysis
Roadmap




![image](https://github.com/cityofaustin/atd-data-tech/assets/49930868/85abb81d-c37b-4b55-8fd3-1aa97869a9c2)

**Comment by TracyLinder** [comment]
### Update
1. I created new issues based off of today's refinement conversation (notes above)
2. I renamed this epic and began using the name "WZDX Release 1.0"

**Comment by TracyLinder** [comment]
We are considering creating an AGOL feature service for this data. TBD

**Comment by TracyLinder** [comment]
### Update
- We have completed the AMANDA query, ETL setup


- [ ] Setup ETL to convert into JSON format
- [ ] Turn on the ETL?
- [ ] Get data owner (ROW) approval
- [ ] Notify interested parties
- [ ] Register WZDX registry
- [ ] Gap Analysis
- [ ] Roadmap
