### ISSUE TITLE
Micromobility SR Go-Live Checklist

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#17809]
## Description
This is a running list of things that we'll need to for go-live

### To DOs:
- [x] Change the provider emails as the default for incoming service requests and subsequent emails
- [x] Find out a date to launch - Monday, 8/26/24
- [x] What to do with test records
  - Asked Shavyvonne 8/21/24
  >Good morning, for now we would like to keep the records so that the leadership team can retrieve the records. Once this is successful completed on all shifts I will let you know when you can delete them.
- [x] Coordinate with vendors for go live, change out vendor emails
  - [x] Met with vendors on 8/19/24
- [x] Add PE users from PEP to SMRT
  >We had added users previously, but they were "inactive"
  - [x] Changed all `peo-officer` user status to "active"
  - [x] Reviewing PEP accounts and comparing SMRT "peo-officer" accounts
- [x] Move the PE folks who have full admin access as new user type - PE Admins

**Comment by patrickm02L** [comment]
## 8/21/24 - PE SR training for launch
@dianamartin adding PE Officers from PEP to SMRT, see check box above.

**Comment by patrickm02L** [comment]
## 8/21/24 Planning
- We discussed specifying user roles and decided that the PE folks should be reasssigned as PE Admins.

**Comment by dianamartin** [comment]
# 8/26/24
## Configure Emails - New Micro Modal Sr
- [ ] 1. Providers - New Micro Modal SR
- [ ] 2. SMS - Impoundment
- [ ] 3. Dispatcher - Impoundment
- [ ] 4. Provider - Impoundment

## Configure Emails - (Modify) Impoundment New Micro Modal Sr
- [ ] 5. SMS - Impoundment
- [ ] 6. Dispatcher - Impoundment
- [ ] 7. Provider - Impoundment

**Comment by patrickm02L** [comment]
## 8/26/24 

- Made .csv backups of SR and Impoundments
- Deleted 213 activities table
- updated emails to SMS, PE, and provider emails
-

**Comment by patrickm02L** [comment]
# 8/29
Angel from Bird emailed us about permissions

> I'm having trouble adding new operator contacts under our account. When I use the '+ add contacts' button, the new contact doesn't appear in the list view. I receive an error message stating the email must be unique when trying to re-add. Where do I find the newly added contacts/confirm they have access to the Service Request Editor? I've also attached pictures for reference.

**Comment by patrickm02L** [comment]
# 8/29 
We met with Angel from Bird on Teams

- She was having issues adding contacts to the company' page. It was determined that the contacts needed to be associated with Bird. (see above comment)
- Assisted her in logging in and resetting her password so she could access her account with her own credentials
- Added Angel as a "provider contact", who was initially only a "service request editor" 
- Diana added a separate button "service request editor" to keep separation from the "provider contact"
- Diana added a filter to differentiate "service request editor" role
- Tested with Angel to ensure that she could add new "providers contacts" and "service request editors" in the pop-up screen and they would populate in the Provider table

**Comment by dianamartin** [comment]
# 8/30/24
- Angel emailed back and said another colleague she had set up had the same error she did
- I looked into it and it looked like she used the "Add Service Request Editor" rather that the "Add Provide Contact" 
- I emailed her back
>I changed Christina’s user role to “provider contact”. 

>As a best practice: 
When you add contacts, you’ll want to make sure if they need to see application/license items that you use the “Add provider contact” button first and then the trigger button to enable them as an “SR Editor”. 

>If you use the “Add Service Request Editor” button first, it will only give them “service request editor” roles and nothing else. (You won’t be able to change their role to “provider contact” and will have to contact us to make the changes).

>Then, if you need to separate someone from the company. You’ll want to use the “inactivate user” button.
![image](https://github.com/user-attachments/assets/60328262-45e1-48a6-a23c-3e9db556bc86)

**Comment by patrickm02L** [comment]
Launched 8/19/24, we've made some slight adjustments to user roles, and discontinued monitoring service request emails 9/11/24. Considering this closed
