### ISSUE TITLE
Test Cases - TCP Upgrade

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#17890]
### Documenting features/functionality that must be tested.

**Comment by TracyLinder** [comment]
## Customer Portal

- [ ] Create new account
- [ ] Login to approved account
- [ ] Attempt login to rejected account


## Staff Side
- [ ] Approve new account connection; make the connection
- [ ] Reject new account connection

**Comment by TracyLinder** [comment]
**Tasks we should add to testing:**

- Customer needs to update their email address and phone number.
