### ISSUE TITLE
When I look at a signal study that has a study attached, the attachment is not showing up in the "de...

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#17896]
> What application are you using?

AMD Data Tracker

> Describe the problem.

When I look at a signal study that has a study attached, the attachment is not showing up in the "detail" view.  You can see the attachment on the "edit" page.

> Is there anything else we should know?

Sorry I cannot upload a screenshot of both the signal study details and edit pages, but hopefully this gives you enough information to confirm what is happening.  Thanks

Internet Browser: Chrome

> Requested By
Renee O.

[Attachment](https://api.knack.com/v1/applications/595d00ebd315cc4cb98daff4/download/asset/66719cfa3fe2050028a61dd4/gb_details.jpg) (85.66kb)

Request ID: DTS24-115655

**Comment by ChristinaTremel** [comment]
### Existing Fields
Looked into this issue and realized there are several Study Attachment fields: 
![image](https://github.com/cityofaustin/atd-data-tech/assets/61209591/bf6c1608-9495-4429-a153-bd1accea8da5)

- STUDY_ATTACHMENT_file
- STUDY_ATTACHMENT: LINK
- STUDY_ATTACHMENT
   - Multiple choice options look like this: <a class="kn-view-asset" href="https://api.knack.com/v1/applications/5815f29f7f7252cc2ca91c4f/download/asset/5970ec6ca0b8454f9474049f/tsiwebberville_oaksprings_final_sealed.pdf">tsiwebberville_oaksprings_final_sealed.pdf</a>
- STUDY_ATTACHMENT: URL

### Findings: 
- Older studies attached have the `STUDY_ATTACHMENT: LINK`, `STUDY_ATTACHMENT`, and `STUDY_ATTACHMENT: URL` populated. 
   - `STUDY_ATTACHMENT` and `STUDY_ATTACHMENT: URL` were both already available on the `View Studies Details` page and on the `Edit Studies` page, but are not editable on that page
- Newer studies attached have the `STUDY_ATTACHMENT_file` populated and this exists/is editable from the `Edit Studies` page. Did not exist on the `View Studies Details` page
   - [x] Added  `STUDY_ATTACHMENT_file` to the details page and renamed it `Study Attachment - New` temporarily
- Count of Records with fields populated - total of 439 records
   - STUDY_ATTACHMENT_file is not blank and STUDY_ATTACHMENT: LINK is blank - `130 records`
   - STUDY_ATTACHMENT: LINK is not blank and STUDY_ATTACHMENT_file is blank - `125 records`
   - STUDY_ATTACHMENT_file is not blank and STUDY_ATTACHMENT: LINK is not blank - `2 records`
   - STUDY_ATTACHMENT_file is blank and STUDY_ATTACHMENT: LINK is blank - `182 records`


### Additional Questions
Tagging @johnclary & @dianamartin because I'm hoping y'all might have some historical context!
- Was there a change in process for attaching signal studies at some point? From attaching a study attachment and that creating a URL so the attachment was visible to just simply attaching a file? I was thinking this could have been a work around if Knack didn't have an easy way to do this when this was initially built. 
- If there was a change in process/to make things less confusing, I'm wondering if we should migrate the documents using these 3 fields (`STUDY_ATTACHMENT`, and `STUDY_ATTACHMENT: URL`) to the other attachment format?

**Comment by johnclary** [comment]
sorry @ChristinaTremel — i don't know 🤷 @dianamartin might have some recollection of this though 😅

**Comment by dianamartin** [comment]
# 7/9/24
- [x] Synced with Renee to understand what the initial issue was
- [x] Reviewed **Edit Form**
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/bdba1003-2da8-420d-aa9b-06b5b4ee4f98)
  - Includes:
    - `STUDY_ATTACHMENT_file` - file
    - "STUDY_ATTACHMENT: LINK" - URL Link <-- Not on the Edit form
      - conditional rule: set to `STUDY_ATTACHMENT: URL`
    - `STUDY_ATTACHMENT` - Multiple Choice
    - `STUDY_ATTACHMENT: URL` - Multiple Choice
- [x] Reviewed **Details Page**
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/a65dfd12-7440-42a9-84d7-d465bf4464ca)
- Includes:
    - `STUDY_ATTACHMENT_file` - file - renamed to "Study Attachment - New"
    - `STUDY_ATTACHMENT: LINK` - URL Link 
       - conditional rule: set to `STUDY_ATTACHMENT: URL`
    >Shows but is blank
    - `STUDY_ATTACHMENT` - Multiple Choice
    >Shows but is blank
    - "STUDY_ATTACHMENT: URL" - Multiple Choice <-- Not on the Details page
