### ISSUE TITLE
TDS Portal | SIF Assessment: Features for internal review distribution

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#17917]
## Build internal review features for the SIF Assessment mod, to allow SIF reviewers to gather review feedback from other reviewers. Currently this is being done in Outlook.

> What application are you using?

Transportation Development Services Portal

> Describe the problem.

We would like to have a very simple Final SIF Assessment module under the "Assessments" tab in TDS Knack portal for our internal coordination within TDS - we need internal staff to be able to enter the following information, assign the case to other staff, and set the due date:

SIF Folder: 
PR Folder:
Related Case: 
Parent ID:
Address: 
Units:
SIF Service Area (drop down menu with all service areas): 
Council District (drop down menu with all council districts):
Review Area: North, Central, or South
Case Type: SP, ZC, or Subdivision
Due Date:
Case Status: Needs Review, Review Complete, or Pending Customer Action
Attachment:

After being assigned the case, the review should be able to upload an attachment and change the case status.

> Describe the outcome you'd like to see when this feature is implemented.

Our senior leadership wants to be able to track our tasks, and this will help us to do this tracking. Our team will also be able to coordinate the final SIF assessment more efficiently.

> Describe any workarounds you currently have in place or alternative solutions you've considered.

We are currently assigning/completing the review via email.

> Is there anything else we should know?

We would like this to be completed within 2-4 weeks given the leadership priorities.

> Requested By
Kaylie C.

[Attachment](https://api.knack.com/v1/applications/595d00ebd315cc4cb98daff4/download/asset/6671ef3f01f43600284da241/ticketattachment.jpg) (45.7kb)

Request ID: DTS24-115675

**Comment by TracyLinder** [comment]
Right now they are using outlook to distribute and cannot track those interactions. 
Enhancements:
- [ ] Can assign a review task to internal employees.
- [ ] Send automated emails.
- [ ] Send attachment in automated email.

**Comment by TracyLinder** [comment]
Scoping scheduled for 7/9

**Comment by TracyLinder** [comment]
### Status

- Current state is functional, however TDS user feedback has been about simplifying the features. 
- They'd like to meet with Chrispin to discuss options.

**Comment by TracyLinder** [comment]
### Status
TDS is still testing this internally as of 11/5/24. I will ping Matiur for an update.
