### ISSUE TITLE
[Python] Connect Work Orders to Flex Notes

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#1795]
In order to meet #279, we need to connect markings work orders to their connected SR's flex notes.

Todo:
- [x] Add one-to-many connection field on `csr_flex_notes` to `work_orders_markings` (`field_3629`)
- [x] Add `COUNT_FLEX_NOTES` field to markings_work orders (`field_3632`)
- [x] Create Knack API view of markings flex notes (`scene_1271`, `view_3169`)
- [x] Create Knack API view of markings_work_orders that have an SR but no flex notes (`scene_1271`, `view_3170`)
- [x] Write script that fetches unattached SR flex notes, fetches related work order, and updates the flex note record connection  
- [ ] text with more records
- [ ] update deployment config / deploy

*Migrated from [atd-knack-signs-markings #287](https://github.com/cityofaustin/atd-knack-signs-markings/issues/287)*

**Comment by atdservicebot** [comment]
*From johnclary on 2019-12-10*:

@dianamartin i ran the script and have flex notes connected to work order `MRK19-009590`. You should be able to build your flex notes table on the job details now. You add a table that shows "records connected to the parent work order" > "csr_flex_notes" (or something like that).

**Comment by atdservicebot** [comment]
*From dianamartin on 2019-12-10*:

@johnclary Tried looking at this. Did you configure this on test or prod? I unfortunately can't see a related table for "csr_flex_notes".

**Comment by atdservicebot** [comment]
*From johnclary on 2019-12-11*:

@dianamartin i ran the script once in prod. When you're adding the table you can find the choice under "Records further connected to this page's work_orders_markings_job". Screenshot attached.

<img width="750" alt="Screen Shot 2019-12-10 at 6 42 29 PM" src="https://user-images.githubusercontent.com/14793120/70581473-e92a9c80-1b7c-11ea-8038-789d898517d6.png">

**Comment by atdservicebot** [comment]
*From johnclary on 2019-12-11*:

I can run the script again in test or prod if you create more work orders from SRs.

**Comment by atdservicebot** [comment]
*From dianamartin on 2019-12-11*:

@johnclary thanks! I was only looking at it on Test that’s probably why.

**Comment by atdservicebot** [comment]
*From dianamartin on 2019-12-11*:

@johnclary Confirmed I was able to see the flex note connection on the jobs page in Signs & Marking Prod. Wasn't able to configure the Test environment bc it doesn't exist there that I saw.

**Comment by atdservicebot** [comment]
*From dianamartin on 2019-12-12*:

@johnclary I have 3 work orders in PROD now, if you wanted to run the script in PROD again.

**Comment by atdservicebot** [comment]
*From johnclary on 2020-01-10*:

Ended up deploying this through the `atd-knack-api`: https://github.com/cityofaustin/atd-knack-api/pull/5

Which also required a change to the Knack custom js:
https://github.com/cityofaustin/atd-knack-signs-markings/pull/308

**Comment by atdservicebot** [comment]
*From johnclary on 2020-01-10*:

will finalize testing with @dianamartin on Monday.

**Comment by dianamartin** [comment]
@johnclary Following-up: did you end up completing the job flex notes code you were working on last week? I wanted to what the status of this was so I that I can either test next week and let Christina know.

**Comment by johnclary** [comment]
sorry, @dianamartin i keep failing to get to this. will block off time on my calendar this week.

**Comment by dianamartin** [comment]
@johnclary I'm looking forwarding to closing #885 soonish 😉

**Comment by amenity** [comment]
Bumping to Sprint 22. 🐍

**Comment by johnclary** [comment]
Working from [this branch](https://github.com/cityofaustin/atd-knack-api/tree/jc-flex-notes-url).

@dianamartin I created a "Flex Notes URL" field on the markings work order object. This gets populated by a script, and it links to the flex notes page of the connected service request.

I also created a "Flex Note Url" field on the markings job object, which populates from a text formula that pulls from the parent work order.

So, you should now be able to add a link to the job details page that opens up the flex notes.

Would you give that a try and let me know? I have not deployed this script yet.

**Comment by dianamartin** [comment]
@johnclary I tested this in the marking jobs details and going to tweak this so that we rename the URL. Going to make a new issue.

**Comment by johnclary** [comment]
@dianamartin script is deployed. i tested in production and it worked. closing.
