### ISSUE TITLE
PMT Activity Outcomes and After Actions

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#18015]
- Ivonne and Erin's team met and discussed the tracking that they'd like to see on Project Intake Requests because there are internal activities they are tracking along the process. 
- Based on the activities documented, there are going to be various outcomes that can be as simple as them tracking notes in an open text field to having actions that they need to take (i.e. creating cost estimates, submitting finance service request in other application, creating work orders, etc)
- Christina will be meeting with Erin, David, and Jorge on 6/27 to determine the high level outcomes that should come from activities and will document those on this [miro board](https://miro.com/app/board/uXjVMj5M860=/).

**Comment by ChristinaTremel** [comment]
# Activities Mapping
## Activities requiring attachments
#### Draft Cost Estimate
- Attach `Cost Estimate` - user can include "Draft" in the description
   - (they will want to see this attachment on the `View Project Request details` pages attachment table as well)
- `Activity Notes` field for staff to track progress

## Activities with only notes to track progress 
#### Scope Approved
- [x] `Activity Notes` field for staff to track progress

#### AE Payment
- [x] `Activity Notes` field for staff to track progress

#### CTMA Payment
- [x] `Activity Notes` field for staff to track progress

#### ROW/DSD payment
- [x] `Activity Notes` field for staff to track progress

#### SOS Received
- [x] `Activity Notes` field for staff to track progress

#### SOS signed internally
- [x] `Activity Notes` field for staff to track progress

#### Invoice(s) received
- [x] `Activity Notes` field for staff to track progress

#### Final Invoice(s) paid
- [x] `Activity Notes` field for staff to track progress

#### DO Closed
- [x] `Activity Notes` field for staff to track progress

#### Permit Status
- [x] `Activity Notes` field for staff to track progress

## Scope Change Sub-Activities
- [ ] Add `Sub Activities` field to `project_requests_PMT_activities` object to include:
   - Obtain New Schematics
   - Cost Estimate Revision and Review
   - Funding Approval
   - DO Increase
   - TK Increase or Decrease
- [ ] Add `Sub Activity` field to [Add Activity form](https://builder.knack.com/atd/amd/pages/scene_1632) and only viewable if user selects `Scope Change` as the activity type

#### Obtain New Schematics
- Space to add Attachment Type `Schematics` 
   - (they will want to see this attachment on the `View Project Request details` pages attachment table as well)

#### Cost Estimate Revision and Review
- Attach `Cost Estimate` - user can add revision and date to the description
   - (they will want to see this attachment on the `View Project Request details` pages attachment table as well)

#### Funding Approval
- [x] `Activity Notes` field for staff to track progress

#### DO Increase
- [x] `Activity Notes` field for staff to track progress

#### TK Increase or Decrease
- [ ] `Action Required` includes link to [Submit Finance SR](https://atd.knack.com/finance-purchasing#new-service-request/))
- [x] `Activity Notes` field for staff to track progress

## Other Actions
#### Funding Authorization
- [ ] Users would like to track FDUs on a table because there are going to be multiple FDUs. 
   - FDU table should be visible from 
- [ ] Would like to have a form on this activity where they can add lines of FDUs

#### Submit TK Request
- [x] `Action Required` includes link to [Submit Finance SR](https://atd.knack.com/finance-purchasing#new-service-request/))
- [x] `Activity Notes` field for staff to track progress

#### DO Request
- `DO Number` field to capture DO
- `Activity Notes` field for staff to track progress

#### Send Notice to Proceed
- 

#### Change Order Items
- Add `Status - Change Order` field with options: "Requested" and "Approved"
- `Activity Notes` field for staff to track progress

#### Inventory JV
- 

#### TK Closed
- `Action Required` includes link to [Submit Finance SR](https://atd.knack.com/finance-purchasing#new-service-request/))
- `Activity Notes` field for staff to track progress

**Comment by ChristinaTremel** [comment]
## `project_requests_PMT_activities` object
- Created new fields required for the activities with customized actions that need to happen. Added these fields:
   - `DO Number` - short text
   - `task_order` - connection to financials_task_orders
   - `work_orders_signals_images` - connection
   - `Attachment` - file
   - `Attachment Description` - short text
   - `Action Links` - link
 
## Close Project Activities Button
- Created button to Close Project Activities and add record rules to insert the standard closing PMT activities
- Added `PMT Activities - Close` multiple choice field to `project_request`  object with the 4 closing activities
   - Final Invoice(s) paid
   - DO Closed
   - Inventory JV
   - TK Closed
- Added form that updates a project_request record - updates Modified By and Modified Date
   <img width="380" alt="image" src="https://github.com/user-attachments/assets/2ffc44c8-316f-4658-ac60-9577e780923f">
   <img width="380" alt="image" src="https://github.com/user-attachments/assets/623f1587-0766-4a59-b1fe-eba6aba9e455">
- Added additional record rules to insert new project_request_PMT_activities if the specific activity was checked off by user
   <img width="380" alt="image" src="https://github.com/user-attachments/assets/c966927b-76a7-4e33-90ce-c647b952e635">
- Tested this form and it did exactly what I was hoping 🙌 created the records that were checked off on the form

## New Project Activities button
- Used the same format as the close project activities! 
- The `PMT Activities - New` multichoice field created on the project_request object include the following options: 
   -  Draft Cost Estimate
   -  Funding Authorization
   -  Submit TK Request
   -  DO Request
   - Send Notice to Proceed
- Added the following record rules: 
<img width="382" alt="image" src="https://github.com/user-attachments/assets/f67af60a-adb9-45ed-8532-1bfce939543d">
- Tested this form as well and it's working as expected! 🎉

## Add Activity Form
- During the review of PMT activities, the team noted that

**Comment by ChristinaTremel** [comment]
# Left to do
- Review all functionality with Diana on 8/13
- Look into the activities that I have not worked on because they seem more complex in what actions should follow:
   - Funding Authorization
   - Inventory JV

**Comment by ChristinaTremel** [comment]
This has been completed and was reviewed with Ivonne and Erin.
