### ISSUE TITLE
VZV | Mobile responsive audit

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#1811]
### Tasks needed to optimize mobile performance
- [ ] Determine which devices that we need to test on. This should be informed by devices that are currently viewing the City of Austin website. @amenity can help provide this list
- [ ] Determine which browsers we need to test on. This should be informed by browsers currently accessing the City of Austin website. @amenity 
- [ ] Find someone that has a BrowserStack account that can help us test mobile performance/responsiveness
- [ ] List actionable steps we need to to take to improve the performance of VZV on mobile

### Known issues
- [ ] VZ logo in header responsiveness does not behave consistently between Chrome, Safari, and Firefox (to reproduce move window width through desktop to mobile and logo overflows/disappears in some viewports)
- [ ] Summary widgets could use whitespace better on small mobile devices (see https://github.com/cityofaustin/atd-vz-data/pull/739#pullrequestreview-392574071)
- [ ] In Summary view desktop viewport header, give logo and nav same margins as the content below so they align with cards and visualizations below and snap out to take full width at the same breakpoint as the content and banner (see XD file)

---
**OLD ISSUE DESCRIPTION**
We need to audit VZV for ways to enhance the experience on mobile. Particularly the summary page visualizations and controls on the map page need attention. 

Use browser stack to test? See if we can get an account from ODD

*Migrated from [atd-vz-data #696](https://github.com/cityofaustin/atd-vz-data/issues/696)*

**Comment by JaceDeloney** [comment]
Updated the description for this issue. Once completed, we should have a list of new issues to enhance the performance of VZV on mobile devices.

**Comment by amenity** [comment]
ODD still uses [this list](https://github.com/cityofaustin/janis#browser-compatibility), which we compiled two years ago. Here's a quick stab at an updated report: 
[Austintexas.gov - External Traffic - Browser & OS 20190421-20200427.pdf](https://github.com/cityofaustin/atd-data-tech/files/4547617/Austintexas.gov.-.External.Traffic.-.Browser.OS.20190421-20200427.pdf)

Happy to pull data with different dimensions/data-range, just lmk what you want. 

@JaceDeloney - if you would like access to the City's Google Analytics, you can request that from CPIO [here](https://cpio.typeform.com/to/kuwa3V).

**Comment by JaceDeloney** [comment]
Thanks to @sergiogcx for all of the great mobile UX/performance analysis that he did for this.
