### ISSUE TITLE
Imported other drivers and license plates

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#18156]
# 7/8/24
When we met with Shavyonne on 7/3/24 and asked her to follow-up with Jasmine/Rodrigo for the license plate list.

**Comment by dianamartin** [comment]
# 7/8/24
## Tasks
- [x] Started importing OSE and SMO driver accounts into the system (from Miro board)
- [x] Received list from stakeholder
- [x] Manually updated vehicle license plates
- [x] Messaged stakeholder
>Hi Shavyvonne, 
I've imported in the License Plates from the vehicle list that Percyna sent over. I've also checked the eFleet site to get the missing LP's and filled in the Service Dates in the PEP system too. 

>I've finished adding the Office of Special Events and Smart Mobility drivers into the system as well.
