### ISSUE TITLE
Meeting to demo prototype 7/10

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#18195]
#### Attendees: Diana, Christina, Reiner, Jennifer, Greg, Peggy, Adan, David
- Demo of prototype
- Discussion of additional needs for the tracker

**Comment by ChristinaTremel** [comment]
# Notes:
- Dave and Reiner should be decision makers on this
- Jennifer noted concern for missed punches:
   - Option 1: Supervisor reviews daily and checks for anyone still signed in
   - **Option 2: The user immediately signs out and signs back in if they missed their sign out
      - Notifies supervisor and supervisor can do a manual override that requires a comment box
      - Reiner prefers this option
      - Identifiable factor when the time is entered manually
- Add log in date and time on the `Log Entries` table
- For supervisor/manager
   - Show list of employees for their division and show last punched in and last punched out
   - Flag to note if late punch in
      - Flag anyone punching in 7-10 minutes late
   - Will need to have table to track and modify schedules based on specific teams/seasons other than call back.
   - 6am start, 30 minute lunch, some staff stop at 2:30 and some staff stop at 4:30

**Comment by dianamartin** [comment]
# 7/10/24
Participants: 

- Jennifer, Adan, Reiner, Dave
- Peggy, Christina, Diana

## Project Champion

- Reiner

## Context:

Missed Punch - Jennifer brought up

- Someone forgot to punch in for the day
    - Process: Ability to add a comment box verification
        - “manual” identified

## Features

### Employee Sign In/Out

- [ ] Ability for user to see Log Date w/ Time


### Reporting - Employee Logs

- [ ] Ability to view reports
    - HR, SBO superintendents, supervisor, director, AD
- [ ] Ability to see “late” punch in (7 - 10 minutes) - not occurrence
- [ ] Ability supervisor to see their division, similar to “[Maximo-sbo-user-verification”](https://atd.knack.com/hr#manage-accounts/maximo-sbo-user-verification/%E2%80%9D) page
- [ ] Ability to add a comment box verification
    - For missed punches

## Hardware

- computers - older model
- tablet - older model
- barcode scanner - $20
- adapters - $10
    - usb B - usb C
    - usb B - micro USB

## Owner/Location

- Assign devices to superintendents

## Badges

- assess who has barcodes and not
- If not,
    - sticker
    - BSD re-issue?

**Comment by dianamartin** [comment]
# 7/11/24 - Aggregated Feedback
## Reporting - Employee Logs
- [ ] Ability to see “late” punch in (7 - 10 minutes) - not occurrence 

>Similar to SMRT Service Requests "Overdue" field, reference that
- Ability to view reports
- [ ] HR
- [ ] SBO superintendents,
- [ ] supervisor, 
- [ ] director?
- [ ] AD?
- [ ] Ability supervisor to see their division, similar to “[Maximo-sbo-user-verification”](https://atd.knack.com/hr#manage-accounts/maximo-sbo-user-verification/%E2%80%9D) page

**Comment by ChristinaTremel** [comment]
Closing this because we demoed the prototype and had an additional scoping meeting to gather more details on reporting needs and functionality of the feature.
