### ISSUE TITLE
Scoping Meeting on Time & Attendance Tracker (7/16/24)

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#18271]
Participants: Reiner, Dave, Greg, Jennifer, Christina, Stephanie, Diana

**Comment by ChristinaTremel** [comment]
## Meeting Notes
Identify the following aspects of this request:
#### Scope and Deliverables
- Feature for staff to quickly scan badges as they are arriving and leaving daily
- Field to flag if a Technician arrives 10 minutes past expected start time
   - How are the technicians assigned their work schedule?
      - All staff is on 8 hour schedule starting at 6am
      - Utilities and Structures is on 10 hour shift (only Division different) 
      - 6am start time for all staff, might shift during daylight savings
      - 1 crew comes in at 4 or 4:30am for downtown maintenance (8 hour shift)
      - New user role for Greg to manage the schedules of staff
   - How often do work schedules change?
      - Work schedules might shift with daylight savings
   - Who would manage all staffs schedule?
      - Greg 
   - How do special schedules work (early start time or special projects)
      - If there's an emergency activation, they go from a normal schedule to a 12 hour shift (Day:6am-6pm and Night:6pm-6am)
   - Overtime Request:
      - If they are approved for overtime, if they have submitted a request to the overtime process, we could just do a correction with a note that they did overtime
- Missed Punches:
   - Who should have the authority to do the correction
   - Make edit function for missed punches
- Time & Attendance Reporting:
   - Counts of "Missed Punches"
   - Modified By
   - Reiner would like to have a flag if there are 5 missed punches and 5 late occurrences within 90 days
      - 5 unresolved late punches
      - No call no show needs to be a unique flag as well
      - Late occurrences would be flagged similar to "MP", but in a separate fields
      - Missed punches count as performance deficiencies with aligned SSPR priority
      - We don't care about including sick or vacation in the system
- How long do we need to keep these timelog records? 
   -  Potentially only one month to quarterly but will need to have further discussion

#### Desired Outcomes
- MVP: Greg can see in and out times and verify that it matches the UKG

#### Preferred Roll Out Timeline
- Would want to get testers to use this sometime this summer after we've prototyped to get feedback
- UER is using timeclocks are already great at entering their time. Should use pavement or fogseal as a testing crew to test the system
   - Proposing using Fogseal for testing
- October 1 as the preferred full roll out would be great 
- Pilot in September
- Start training at the end of September

#### SBO to start planning: 
- Where will these devices be around each of the buildings
- Count of laptops/scanners that we are going to need
- Christina & Diana can plan to do a site visit at all of the SBO locations to check out where these could go

**Comment by dianamartin** [comment]
# 7/16/24
## Changes completed during the meeting
- [x] Removed "Summary of totals" on Manage Employee Logs page 
- [x] Made all tables "hide empty fields"
>This cleaned up the visibility of the page

## Diana's Meeting Notes
QUESTIONS
How are people assigned 8 or 10 hour shifts?
All staff - at 8 hours
Execpt UER - 10 hr shifts

6 AM start time
except

Downtown Maintenance
- 4 AM *8 hrs*

***New Enhancements**
SBO Administrative Time Page

Greg G./Dave A. (backup)
- New user role in HR
- New page: Employee
  - 2 new fields:
  "Schedule Start"
  "Shift" (8, 10)

Reporting - 5 Occurences
- MP - Performance deficiencies
- 5 lates?
- No call/No Show

***Modifications***
- Add Edit form on "Manage Employee Logs"

*** Data Retention ***
90 days

- Pavement
- Fog Seal
Byron, Fred, Jermaine

**Comment by dianamartin** [comment]
# Things to do
## New User Roles
- [ ] Create "SBO Time Administrator" - user role
  - [ ] Add Greg (primary), Dave (backup)
  - [ ] 

## New Page
- [ ] Create "Manage SBO Time" - management page
  - ability for user to add Missed Punches
  - page for all sign ins/outs (Editable)
  - Ability for admin to add/edit "Schedule Start", "Shift"
- [ ] Update "Manage Employee Logs" (for supervisors)
  - this page is for flagged missed punches that supervisor needs to address
  - page for all sign ins/outs (Read Only)
- [ ] Add "Edit form" on Manage Employee Logs

## New Fields
- [ ] Added new fields to "accounts" table
  - [ ] "Schedule Start"- Date/Time
  - [ ] "Shift" - (8, 10) - Multi-choice
  - [ ] "Shift CALC" - (8, 10) - Number
>All staff - at 8 hours, except for UER - 10 hr shifts. Everyone starts at 6AM, excepts 6 AM Downtown Maintenance staff, Start at 4 AM, 8 hr duration.

## Update Overdue fields
- Once you add start time, then -re-do calculations

## New Report
- 5 occurrences (late, missed punches)

**Comment by dianamartin** [comment]
# 7/23/24
- Reviewed the fields I created for the "Late" function and it was weird. I started over
- Created several fields
  - `LOG TIME` - consolidates the "Sign In" and "Sign Out" fields into one (for easier calculation) (TxtForm)
  - `LOG TIME  DATE` - converts from Text Formula to Date (Date/Time)
  - `LOG TIME DATE EXTRACT` - extracts the time out (TxtForm)
  - `LT TIME EXTRACT DATE` - coverts the time back into a date (Date/Time)
  - `Schedule Start TXT` - pulls "Schedule Start" data from `accounts` (TxtForm)
  - `SCHEDULE START TIME DATE`  - coverts the time back into a date (Date/Time)
  - `OVERDUE DIFF` - takes `LT TIME EXTRACT DATE`- `SCHEDULE START TIME DATE` = to get seconds
  - `DIFF MINUTES` - divides seconds by `60` to get minutes
 ![image](https://github.com/user-attachments/assets/12344f9b-2b25-431f-a6c9-ff1f4c7494f6)
- [x] Created new field `LOG STATUS`
  - [ ] Set to `Late` or `On Time` - depending on `DIFF MINUTES`
- [x] Tested on the Admin Employee Logs page and it works!!!
![image](https://github.com/user-attachments/assets/b4785c36-ebe1-41b4-b13e-9951defaf1b0)

**Comment by ChristinaTremel** [comment]
- Created #18456 to address additional features in the attendance tracker. Closing out this scoping meeting issue!
