### ISSUE TITLE
Create indices for current DTS projects

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#183]
We're creating index issues so that there is a central place we can see all the information about our projects. 

1.  [Create a new project index in `atd-data-tech`](https://github.com/cityofaustin/atd-data-tech/issues/new?assignees=&labels=Index&template=project-index.md&title=Project+Index%3A+). The issue name should be `Project: [Your Project Name in Title Case]`.
2.  [Add a new `Project:` label](https://github.com/cityofaustin/atd-data-tech/wiki/Project-Management%3A-Github-and-ZenHub-Basics#project-labels) and apply it to all relevant issues. Hex code is `#86B1C6`. 👨‍🎨
---
Alan
- [x] B-Cycle Station Planning #393 
- [x] CTN #394

Amenity
- [x] Warehouse Inventory #20 
- [x] Residential Parking Permits #389 
- [x] Mobility Project Database #307 
- [x] Vision Zero in Action Citation App #145 

Diana
- [x] Traffic Counts - #410
- [x] Signs Work Order & Asset Management Migration - #412
- [x] Street Banner Request Intake & Management - #409

Jaime
- [x] Parking Data Overhaul - #254
- [x] AGOL Audit - #253

John
- [x] Data Lake - John
- [x] Dockless Data Management - John
- [x] Traffic Registry - John

Mateo
- [x] C2C #144 
- [x] Mobile Signal Work Orders #251 
- [x] Vision Zero Data Management #255
- [x] Updates to Dockless Data Tracker #256

Tracy
- [x] ROWMAN — Phases 3 (#421), 4 (#422), (There is no 5 & 6 right now)
- [x] Right-of-Way Permit Inspection Prioritization #423
- [x] ATD AMANDA Backlog
- [x] BI Discovery #65

**Comment by amenity** [comment]
@johnclary - can you add names next to these and I'll break up into individual issues for each person?

**Comment by johnclary** [comment]
@amenity done.

**Comment by johnclary** [comment]
@amenity cards should exist for most of these, so if you don't want to create separate issues we can assign this issue to all and have them check the boxes above. your call.

**Comment by amenity** [comment]
@mateoclarke @dianamartin @TracyLinder @johnclary @jaime-mckeown - it's probably better to wait for the Project Index template to be solidified (#193) before starting on these.🙏

**Comment by amenity** [comment]
@alan-deanda - Can you take a look at [this](https://github.com/cityofaustin/atd-data-tech/wiki/Project-Management%3A-Github-and-ZenHub-Basics#project-labels) and see if it works for you? Thanks!

**Comment by TracyLinder** [comment]
**Missing Projects**

- ROWMAN (All Phases) - Tracy
- ATD AMANDA Backlog - Tracy
- Warehouse Inventory - @amenity 
- Updates to Dockless Data Tracker - @mateoclarke (Tyler)

@dianamartin Make sure to include any projects of yours that you feel are missing.

**Comment by TracyLinder** [comment]
**Other Notes**

- When updating an index issue, update the issue body (vs adding updates as a comment)
- The index card's status is sufficient, the body of the index card does not need to say anything additional about the project status.

**Comment by mateoclarke** [comment]
Many of our projects have existing descriptions from John's newsletters: https://github.com/cityofaustin/atd-data-tech/tree/master/newsletters

Maybe worth wordsmithing those further, maybe not...

**Comment by jaime-mckeown** [comment]
When creating the Project Index, do you want the title to keep "Project Index:" or just the name of the project?

**Comment by amenity** [comment]
I think just the name of the project is fine. I’ll update the template so that’s clearer.

Sent from my phone

On Jun 21, 2019, at 9:12 AM, Jaime Mckeown <notifications@github.com<mailto:notifications@github.com>> wrote:


When creating the Project Index, do you want the title to keep "Project Index:" or just the name of the project?

**Comment by amenity** [comment]
@alan-deanda - I can't find yours. Would you please add links up there, 🙏?

**Comment by alan-deanda** [comment]
@amenity  - how can I add my issues in the same format as above if they're from another repo? For example, atd-geospatial issue #31 is for tracking progress on the CTN documentation, but the popup is for issue #31 in atd-data-tech.
Thanks!!
PS: I added other project labels as needed, including the online bike map and the print bike map.

**Comment by amenity** [comment]
@alan-deanda - all the project indices should be in atd-data-tech. If you have it in another repo, you can move it using the _Move Issue_ button at the bottom of the righthand sidebar. Thanks!!

**Comment by amenity** [comment]
~~I think just the name of the project is fine. I’ll update the template so that’s clearer.~~
It's actually helpful to have a title-pattern for indices when looking at the board. Let's do `Project:`. (Updating the ones that exist and adding to template and instructions above.)

**Comment by amenity** [comment]
@alan-deanda - can you please link to your project indices above? Thanks!

**Comment by alan-deanda** [comment]
@amenity my project indices are in! Sorry for the long delay on this.

**Comment by amenity** [comment]
Wonderful, thanks, @alan-deanda! @johnclary @dianamartin @TracyLinder - let me know if you need any help getting yours up. As Mateo pointed out, the [descriptions John has in the newsletters](https://github.com/cityofaustin/atd-data-tech/tree/master/newsletters) are super helpful.

**Comment by johnclary** [comment]
@TracyLinder @dianamartin would ya'll get these done early this week? Need to send the newsletter. I'll do mine too ;)

**Comment by dianamartin** [comment]
😕 I feel like I need to get with someone on this..I'm lost. I guess I've been in project land that I missed what this is.

**Comment by amenity** [comment]
@dianamartin I got ya. Let’s sync tomorrow.

**Comment by johnclary** [comment]
Well I'm the last one to do this, so I get to close it! ;)
