### ISSUE TITLE
Enhancements requested after initial review of Inventory Tracking Module (7/19/24)

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#18318]
**Attendees:** Greg, Richard, Diana, and Christina

### High Priority Items (sent from Richard): 
1. Can present be check boxes or dropdowns with one submit button at the bottom to reduced the number of times the page resets
2. When viewing any work group’s inventory (doesn’t matter which), if you click the Radios or Power Tools button, it takes you to North District Maintenance.
   - (See pictures below: Viewing Urban Forestry inventory > click Radios or Power Tools > takes you to North District)
3. Move last reviewed column to after the present button column
4. Status column only updates when review is clicked rather than the present button
5. South District inventory does not show up on their workgroup, it is all mixed in with Central District

**Comment by ChristinaTremel** [comment]
1. Can present be check boxes or dropdowns with one submit button at the bottom to reduced the number of times the page resets
   - [x] Update the structure and instead of a trigger, make the field editable and add record rule to insert a new record in the cycle count object to create a log that the status has changed. 
   - [x] Going to create a table with the same structure as `Manage Power Tools & Radio Inventory` table to do this tracking because of this change
   - [ ] Add filters for all of the work groups for the `Manage Power Tools & Radio Inventory` table 
   - [ ] Add object for tracking `Reviews` completed by Greg that just captures a review record and which work group he was reviewing. Would also be nice to track the inventory `Last Review Date` from this review object
![image](https://github.com/user-attachments/assets/611589bb-7525-4cac-b019-19ebe2e7a4ab)

2. When viewing any work group’s inventory (doesn’t matter which), if you click the Radios or Power Tools button, it takes you to North District Maintenance.
   - With the solution to the 1st issue, we don't need to make any changes to address this!
   
3. Move last reviewed column to after the present button column
   - With the solution to the 1st issue, we don't need to make any changes to address this.
   
4. Status column only updates when review is clicked rather than the present button
   - With the solution to the 1st issue, we don't need to make any changes to address this!
   
5. South District inventory does not show up on their workgroup, it is all mixed in with Central District
   - Diana exported the list of Central District items and requested that Greg and Richard flag the items that need to be moved to South District. Will batch update these when they review the list.

**Comment by ChristinaTremel** [comment]
@dianamartin I believe most of these changes were made during our meeting with Richard and Greg! Can you confirm that this is ready to close?

**Comment by dianamartin** [comment]
@ChristinaTremel I thought so to, but maybe we need to check in with Richard?

**Comment by ChristinaTremel** [comment]
- Closing this because all the outstanding updates are being completed in #21172
