### ISSUE TITLE
Add "new school beacon" feature on the school beacon page in data tracker

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#1841]
Description: school flasher page doesn't have a function to add a new school flasher.

Request Date: 2018-08-15 11:40:00

Request ID: DTS18-100805

Status: In Progress

Customer Priority: 2.2

Level of Effort: Small Project

DTS URL: https://atd.knack.com/dts#service-requests/view-issue-details/5b745764cc0182285330095c

*Migrated from [atd-knack-data-tracker #37](https://github.com/cityofaustin/atd-knack-data-tracker/issues/37)*

**Comment by atdservicebot** [comment]
*From atdservicebot on 2019-05-10*:

Hi, Willard,

Attached please find the screenshot that shows the new add school_beacon_zone and school_beacon button. These are not available in the production yet. Please feel free to send me the school zone/beacon information if you need me to enter them. 

Created By: Joey Liang
Created Date: 2018-08-15 12:32:00

**Comment by atdservicebot** [comment]
*From atdservicebot on 2019-05-10*:

Currently on hold due to business process consideration. I will resume development after we figured out what the final business process is. 

Created By: Joey Liang
Created Date: 2018-10-22 01:34:00

**Comment by amenity** [comment]
@jaime-mckeown - we couldn't track down the "training" issue — will you make this one dependent on that? Thanks!

**Comment by jaime-mckeown** [comment]
@amenity the training issue has been closed, so technically it's not blocking anything. At this point they should be working in the Web App verifying the data. By the way, all Issues I have created related to SZB should be in the same Epic as this.

**Comment by amenity** [comment]
@jaime-mckeown thanks 🙏...
@dianamartin @johnclary — does this mean it's time to add it to Knack?

**Comment by johnclary** [comment]
Let's hold off on any Knack development until they've completely audited the data. At that point we'll shut down the AGOL app and move the data into the Data Tracker. @jaime-mckeown would you set a reminder to follow-up with the technician(s) in two weeks to check on progress?

**Comment by jaime-mckeown** [comment]
Checked in with AMD, Billy said that Charles is the only person working on the project at this time. He's hoping they will be able to get more people working on it in the future. It's going to be a long road if they don't put more people on this.

**Comment by dianamartin** [comment]
Tested
- [ ] Creating add form SZB asset in Location Details page
- [ ] Added Text Formula on SZB to bring in "Zone Name" as current is short text to be populated
- [ ]

**Comment by dianamartin** [comment]
@dianamartin Need to test this in Test Environment
- [ ] Test School Beacon Creation
- [ ] School Beacon configuration - TMC Issue
- [ ] School Beacon configuation - Work Order

**Comment by dianamartin** [comment]
# TMC Activity Configuration
- [ ] Add `school_beacon` field to "Assign Asset" form

**Comment by dianamartin** [comment]
Had to add `School Beacon Zone` as a choice on the "Asset_Type" fields in the `tmc_activities` and `tmc_issues`. The "Assign Asset" form for the Sys Admin was giving an error.

**Comment by dianamartin** [comment]
Sync'd with Allyson and MMC needed to add new school zone and beacon records. I explained to her what to do: 
- Create SZ in school zone page
- Create SZB in locations details
