### ISSUE TITLE
Consolidate S3 buckets

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#18448]
Consolidate our various S3 buckets down to a single bucket: `atd-vision-zero`.

- `-website`
  - Current home for crash diagrams. Used by VZE. Can be deleted after go-live.
- `website-data`
  - Is clearly not actively used can can be deleted after go-live.
- `-editor`:
  - Current home for CR3 pdfs. used by the CR3 api. Can be deleted after go-live
- `-database`: 
  - Can be archived. Holds the db backups that used to be created via cron job. Used to hold cris extracts but no longer does as of May 2024
- `cris-exports`
  - Current home for CRIS extract delivery. Can be deleted after go-live.
- `-new-data-model-dev`
  - used by new data model stack. Can be deleted after go-live.

## Todo
- [x] create new bucket
- [x] update IAM role permissions to grant access to new bucket
- [x] request 10 years of extracts for delivery (done on 7/31)
- [x] configure getobject/read permissions for crash diagram subdirs (dev/staging/prod)
- [x] update CRIS import ETL env vars (see https://github.com/cityofaustin/atd-vz-data/pull/1497)
- [x] backfill entire catalog of PDFs and diagrams: https://github.com/cityofaustin/atd-data-tech/issues/18457
- [x] update zappa settings
- [x] update VZE env settings

**Comment by johnclary** [comment]
We're all set—we can archive and delete all the buckets except `atd-vz-data` once we go live ⏳

**Comment by johnclary** [comment]
i created `atd-vision-zero-historical-archive` and am moving all the old buckets' contents into subdirectories of this archive bucket, where the subdirectory name is the name of the old bucket
