### ISSUE TITLE
Enhancements & Changes to the Markings Work Orders view.

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#18460]
> What application are you using?

SMD Data Tracker 

> Describe the problem.

Enhancements & Changes to the Markings Work Orders view.

> Describe the outcome you'd like to see when this feature is implemented.

Increased efficiency of use by staff and better notification of upcoming deadlines. 

> Describe any workarounds you currently have in place or alternative solutions you've considered.

All details are in the attached Word doc but open to other suggestions!

> Requested By
Cole H.

[Attachment](https://api.knack.com/v1/applications/595d00ebd315cc4cb98daff4/download/asset/66aba3bf99d7980029c14154/dtsticketmarkingsworkorderview.docx) (615.24kb)

Request ID: DTS24-116520

**Comment by Cole-Hubbard** [comment]
I'm going to meet with Lauren this week and will upload a new version of this document with more details before our SMD Sprint Meeting. Thanks!

**Comment by Cole-Hubbard** [comment]
[DTS Ticket Markings Work Order View_updated.docx](https://github.com/user-attachments/files/16588466/DTS.Ticket.Markings.Work.Order.View_updated.docx)

**Comment by Cole-Hubbard** [comment]
Small addition to this ticket - we would like to update the Signs Work Order page to include the column "Completed" similar to Markings. Thank you!

Signs Work Order view
<img width="831" alt="image" src="https://github.com/user-attachments/assets/48ba7396-361c-4366-b69e-df740fae62e5">

Markings Work Order view w/ "Completed" column
![image](https://github.com/user-attachments/assets/a11a7248-dbf2-4442-8cf5-366e57485999)

**Comment by ChristinaTremel** [comment]
## SMD Sprint Review 10/14
- Added `Completed` to the markings work orders
- @Cole-Hubbard will be following up with additional fields they would like to see on the main work order page.

**Comment by Cole-Hubbard** [comment]
This extends beyond the main work order page, but the requests are largely adding columns similar to the above request. Happy to discuss in more detail! 

[Updates to Exported Reports from Knack.docx](https://github.com/user-attachments/files/17366088/Updates.to.Exported.Reports.from.Knack.docx)

**Comment by Cole-Hubbard** [comment]
Moving forward, Esteban Gongora can provide more specifications on what would be most useful for implementation of this ticket! He likely can only do 1 hour work sessions at a time due to his schedule/work load. 

The second addition, "Updates to Exported Reports from Knack", was to support a Power BI project Cole was working on. It is not as essential as the first part of this ticket but would still be useful to implement in terms of bringing uniformity to the worksheet exports.

**Comment by Cole-Hubbard** [comment]
Esteban has also asked that the Markings work order view include the column "Area" which shows North, South, or Central fields.

**Comment by ChristinaTremel** [comment]
### Markings Work Order Table updates
- [ ] Add Columns – “Due Date” with a date field. (once created in #19668
- [ ] Update status filters to those that users can add additional filters with. This is to resolve for the initial request of: 
   - Can we make the different work group sections collapsable? That is, can we add a feature to click on the work group and all of their entries collapse under the banner title? (e.g. Active Transportation and Street Design, Arterial Management, etc.) Open to other suggestions on how to accomplish this one. 
- [ ] Coordination – when “Coordination” is yes, can we highlight this cell to stand out?

### Work Order Details View
- **Needs Discussion**: Version history of ticket – is there a way we can add a feature that allows us to see previous versions of a ticket? There’s a feature in AMANDA that is similar which allows the user to toggle through to see what was changed, by who, and on what date. Likely tied to the “Modified Date”?
    - The goal is to see if we can see who last edited the ticket to see who closed it out.
- [ ] Comments – can we add an “Edit” button to this feature? Only option to go back and edit a comment is to completely delete it and start over. Apparently this isn’t mobile/iPad friendly, so the Edit feature was requested.

###Job Details view
- [ ] Edit button for Time, Specifications, Materials - similar to Comments, can we add an “Edit” feature for the Materials log? Currently, the only option is to delete and start over.

###Mobile View
- [ ] “Jobs” Mobile view – Can we move the buttons from the bottom to the top? Vehicles, Schedule, etc. Staff currently must scroll through all Work Orders to get to these buttons and they say it is time-consuming/repetitive.
