### ISSUE TITLE
Adding finance review to the existing SMD reimbursable process

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#18536]
### Reimbursable Tracking Page Updates 
- Button to trigger, send invoice to finance (similar to `Email Invoice`)
   - Add record rules to update:
      - Reimbursable Status is `Waiting for Finance Approval`
      - `Sent to Finance` is yes
      - `Date Sent to Finance` is current date
      - `Modified Date` is current date
      - `Modified By` is current user

### New Review table for Finance to process invoices
- Create new table on [Review Invoices ](https://atd.knack.com/signs-markings#review-invoices/) that's only visible to Finance user role
    - Link to invoice details
   - Link to work order
   - Confirmation Button to open form
      - Field for them to populate JV number (already exists)
      - `Finance Approval Status` field for them to either Approve or Deny the invoice (create new)
      - `Finance Notes` field for them to comment if they deny the invoice (create new)
- Create `Finance Staff` user role
   - Include: Erin W, Melissa B, and Crystal T
   - Give them Finance + Viewer user roles
   - Finance user role should only have access to these additional pages: 
      - The new table on the [Review Invoices ](https://atd.knack.com/signs-markings#review-invoices/) page
      - [Sign Fabrication Work Orders](https://atd.knack.com/signs-markings#work-orders-sign-fabrication/)

**Comment by susannegov** [comment]
# 8/16
## Reimbursable table
- [x] Created new column `Send Invoice Finance`
- [x] Created form `Do you wish to send invoice to finance?`
- [x] Added record rules

**Comment by susannegov** [comment]
# 8/19
- [x] Created new Review Invoice table in review invoice
   - Filter all reimbursable records where `Sent to Finance` is Yes

**Comment by ChristinaTremel** [comment]
Synced with Susanne to review these enhancements! We made the following changes during the work session: 
- Added `Finance Approved Date` date field to replace the `Reimbursement_Processed_by_Finance` short text field
   - Populated new finance approved date with data in the old field and deleted the `Reimbursement_Processed_by_Finance` 
- Added `Finance Approved By` field to capture the approver
- Formatted the All | Reimburseable Invoice table to make the field organization consistent between the requester approval and the finance approval 
- Tested finance approval process with test work order: SGN20-054960 and the process was working as expected 🎉
