### ISSUE TITLE
I would like to start the process of creating an inventory system to track SMD inventory.  We need t...

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#18554]
> What application are you using?

SMD Data Tracker 

> Describe the problem.

I would like to start the process of creating an inventory system to track SMD inventory.  We need to add all inventory items to the system, keep track of inventory and issue out when orders are created. 

> How soon do you need this?

Soon — Within a week 

> Is there anything else we should know?

Would like to start this project as soon as possible. What do you need from me and my team for us to start. 

> Requested By
Cesar M.

Request ID: DTS24-116690

**Comment by ChristinaTremel** [comment]
Discussed this with Cesar and he asked to include himself and Abby H from his team on these meeting invites. He said he would reach out to SMD to determine who should be involved in the project on their side.

**Comment by ChristinaTremel** [comment]
Discussed this during the sprint review and SMD would like to include: Lauren, Joe Michael, Supervisors, Cathy, Cole, Jordan, and Johnny.

**Comment by ChristinaTremel** [comment]
#### Vision: Track everything in SMD inventory through Knack 
- Goal: Want to be able to check out inventory in orders and the amount that's currently in stock 
- Not all items will be inventory items
- SMD will want to know how much we're fabricating, how much material we're using, trends for spending
   
#### Warehouse: 
- Organized warehouse and assigned commodity codes to items
- Put items together (signs together, poles together, specialty makings together, etc)
- ATSD has a separate space for their inventory and they track their own inventory
   - ATSD will ask the inventory team for counts but doesn't include the inventory in the counts for SMD
      
#### Criteria for identifying item as inventory: 
- Inventory items on the inventory master list that Cesar provided
- Tracking small tools? It's a nice to have
- For raw materials for sign fabs, when sheeting/plates are removed from inventory to go into the sign shop those would become working stock
- Signs fabricated in the sign shop are out of inventory and typically won't go back on the shelf
- Working stock: Cesar would like to have bolts and stuff tracked

#### Project Phases
- Material (phase 1) 
   - Technicians pulling the inventory on a daily basis
   - [ ] Compare [SMD Inventory List](https://cityofaustin-my.sharepoint.com/:x:/r/personal/christina_tremel_austintexas_gov/_layouts/15/Doc.aspx?sourcedoc=%7B49D6D410-7FDE-4983-B585-11E0B73EEA70%7D&file=SMD%20Inventory%20Master%20List.xlsx&action=default&mobileredirect=true) with the materials that exist in Knack
   - [ ] Look at cycle counts in AMD data tracker to sync up SMDs
   - [ ] Review AMD Data Tracker [inventory item details]{https://atd.knack.com/amd#inventory-items/inventory-item-details/5dfa6ac72057600ac95e7990/) and try to replicate similarly in SMD Data Tracker
- Sign Shop (phase 2)
   - Pulling raw materials into the sign shop
   - First step will be to create work tickets for sign shop to track what they are fabricating

#### Next Steps: 
- DTS complete project evaluation
- Complete full scoping meeting from the phases that we've discussed
