### ISSUE TITLE
Go Live Checklist for Chauffeur's permit

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#18637]
## Description

Things to do on go live day, 8/19

- [x] Clear all the test records
- [x] Send email to Paul & Jacob indicating it's ready to go live with links to the Reviewer and Cashier pages.

**Comment by patrickm02L** [comment]
## 8/19
Sent email to Paul and Jacob letting them know that everythings ready for them to start using the platform.

**Comment by susannegov** [comment]
# 8/19 
- Updated user roles to people listed in email for reviewer/cashier

**Comment by susannegov** [comment]
# 8/20
- Change record rule for add attachment for reviewer
![image](https://github.com/user-attachments/assets/e9497ae2-37e1-4f33-bdee-e59961ed8237)

**Comment by susannegov** [comment]
# Feedback
- [ ] Add an add attachment for the cashier for a copy of a receipt
- [ ] Add a $6 fee for a copy of the background for the cashier

**Comment by patrickm02L** [comment]
@dianamartin in case you wanted to add anything from today's meeting.

**Comment by susannegov** [comment]
- [ ] Added `Has SSN` multiple choice field
- [ ] Added it to form
   - App Info
   - Edit App Info
   - Edit App Info (Reviewer)

**Comment by susannegov** [comment]
# 8/23
- [x] Added Delete attachments menu button to new page

**Comment by dianamartin** [comment]
# 8/23/24
- These were my notes from 8/22

## Enhancement Requests

- [ ]  **Attachments for cashier**
    - After “Paid”
- [ ]  **Add new drop down**
- $6.00 Request for background check
1. $25 App fee
2. $6 notary
3. $6 copy of background
- [ ]  **Social Security background field - Need whole social, but capture last 4 digits**
    - [ ]  Need to keep SSN box (optional), but required
    - [ ]  Need to add new qualifying field “Do you have the a SSN?”
    - [ ]  City Code - provide city code, provide on application
    - [ ]  We don’t have have to add an attachment
    - [ ]  Work towards - software: Gard Card - permit system
        - [ ]  When “Approved”
        - [ ]  Change SSN to 4 digits
- [ ]  **DPS - driving record**
- Bold or highlight URL
- [ ]  **Application Expiration - 30 days**
    - [ ]  Banner to say call Mobility Services to “re-open”
    - [ ]  Roll back to “Not Submitted” (or whatever beginning status)

**Comment by patrickm02L** [comment]
## 9/3/24 MSP check-in
Confirmed in the meeting that we've officially made it through launch and all improvements have been made that were needed.
