### ISSUE TITLE
EX, RW & DS Permit Template Update (NN)

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#1893]
Description: The "Conditions" field from the Folder Tab is renamed as "Instructions" on printed/e-mailed versions of the EX folders and as "Comments" on printed/e-mailed versions of the DS folders.

We would like for the print template for both of these folder types to instead state "Conditions".

Also, The location description portion prints on a 3rd page (EX permits, this is a bug). 

https://trello.com/c/iMdk9cf0/19-print-permit-template

Request Date: 2018-11-29 16:21:00

Request ID: DTS18-102995

Status: Backlog

Customer Priority: 0

Level of Effort: Minor

DTS URL: https://atd.knack.com/dts#service-requests/view-issue-details/5c006664cf5d5d4b2af64ac3

*Migrated from [atd-amanda #29](https://github.com/cityofaustin/atd-amanda/issues/29)*

**Comment by atdservicebot** [comment]
*From johnclary on 2020-02-27*:

![2018-10-03_165816](https://user-images.githubusercontent.com/14793120/75458791-0da84080-5944-11ea-8cb5-605daea3a4ab.jpg)
[EX_Print.pdf](https://github.com/cityofaustin/atd-amanda/files/4262383/EX_Print.pdf)
[DS_Print.pdf](https://github.com/cityofaustin/atd-amanda/files/4262384/DS_Print.pdf)

**Comment by atdservicebot** [comment]
*From johnclary on 2020-02-27*:

Comment from Paloma on Trello:

> The "Conditions" field from the Folder Tab is renamed as "Instructions" on printed/e-mailed versions of the EX folders and as "Comments" on printed/e-mailed versions of the DS folders.
>
> We would like for the print template for both of these folder types to instead state "Conditions".

**Comment by SurbhiBakshi** [comment]
- @Nadin-Nader and I met with Paloma and Sreelatha to go over the permit templates. 
- Meeting notes documented in #2453 
- Video [here](https://drive.google.com/file/d/1reWYS0PRYxVqr4a4FsLuYOYa0haA5l3S/view?usp=sharing)

**Comment by amenity** [comment]
From #2453 
----Permit Templates Meeting 4/24/2020---- LIT IS WORKING ON THIS ----
Sreelatha, Surbhi, Paloma

DS Folder, year 20 Random folder
Residential or Commercial
Print Button > select 50506
DS: 
- [ ] No issues with Header, Legal description field (needs to verify to see if needed or what its for) 
- [ ] Proposed Occupancy should say Description;
- [ ] Needs Wording changed to something more structured
- [ ] Comments renamed to Conditions
- [ ] Canned verbiage at the bottom needs of template changing
- [ ] Page to be added as last page with the outline of all Standard Permit Conditions (link takes you to document with Standard Conditions; remove link)

EX Permit - 
All changes on EX template, Sree confirmed that with Paloma. EX template has been shared by Paloma with us and Launch IT.

- [ ] Add a page to EX permit to show conditions. Like DS Permit??
- [ ] Also make sure Est Completion date pulls from the Expiration Date.

RW Folder, year 20 Random folder
TURP Private Long Term SubType
Print Button > select 50511
RW: 
- [ ] Header is different on screen vs print out (one has COA and department) need to make it, add box frame to all of the fields, 
- [ ] Remove ROW Seal, Change Original End Date to Original Expiration Date, 
- [ ] Change Extension End Date to Extension Expiration Date, Abbreviate Extension to "Extn", 
- [ ] Add a comments field at the end of the Permit Details table

RW Folder, year 20 Random Folder
Film Parking 
Print Button > select(50509) 
- [ ] Need Start and End date

RW Folder, year 20 Random Folder
Parking Spaces 
Print Button > select(50512)
- [ ] Make uniform and neat, Comments Column is not populating, , Change End Date to Expiration Date
- [ ] EX and RW DO NOT HAVE FEE Description section on DS Permit
- [ ] Alignment issues on RW TURP and some DS

**Comment by TracyLinder** [comment]
Currently in LIT's backlog

**Comment by TracyLinder** [comment]
From Sree:
Hi Tracy/Nadin,

I have updated 50511 report, please find attached pdf sample report for your reference. 

Here are the updates that I made on Report – 

1.	Division heading ‘Austin Transportation’ Removed
2.	Made similar heading changes like 50506
3.	Extension updated as Extn.
4.	Extension End date updated as ‘Extn. Expiration Date’
5.	Original End date updated as ‘Original Expiration Date’
6.	Over all report Alignment
7.	Added Status to the report to be in sync with 50506
8.	QR Code with FolderRSN added

**Comment by Nadin-Nader** [comment]
From: Nader, Nadin 
Sent: Monday, May 11, 2020 11:18 AM
To: Amayo-Ryan, Paloma <Paloma.Amayo-Ryan@austintexas.gov>; Perez, Kimberly <Kimberly.Perez@austintexas.gov>
Cc: Linder, Tracy <Tracy.Linder@austintexas.gov>
Subject: Report 50511 Update and Needs Testing

Good Morning,

Hope you two are doing well. I was reaching out to you regarding your request to have report 50511 updated. Sree from LIT has completed the following updates to 50511:
1.	Division heading ‘Austin Transportation’ Removed
2.	Made similar heading changes like 50506
3.	Extension updated as Extn.
4.	Extension End date updated as ‘Extn. Expiration Date’
5.	Original End date updated as ‘Original Expiration Date’
6.	Over all report Alignment
7.	Added Status to the report to be in sync with 50506
8.	QR Code with FolderRSN added

Could you please check to see if the form is correct and let me know if any other adjustments are needed (I have attached the form).

Once we get the feedback, we will have Sree update/upload the new Form and either set up time to test it with you or have you test it independently.

Respectfully,

Nadin A. Nader 
IT Business Systems Analyst
Data and Technology Services 
Austin Transportation Department
[new_50511_RW_Print ins.pdf](https://github.com/cityofaustin/atd-data-tech/files/4610782/new_50511_RW_Print.ins.pdf)

**Comment by TracyLinder** [comment]
Currently pending customer approval.

**Comment by Nadin-Nader** [comment]
Email from Kim to Paloma with suggestions on the report;

> Paloma, 
> 
> My suggestion for the parking permit is to remove one of the issue date sections, since it is already captured in one location. I was also wondering if it is possible to expand the comment section so that it will capture all of our comments. If you look at the AMANDA Test Parking Print that I attached, that permit in AMANDA Test has lots of comments that do not transfer over to the print.
> 
> My suggestion for the film permit is to remove on of the issue date sections as well. I also think adding a start date is beneficial as the start date could be different then the issue date.
> 
> Let us know what you think. 
> 
> Thanks,
> 
> Kimberly Perez
> Training Specialist
> 512-974-2450

I will send the email to Sree with the attachments
[https://app.zenhub.com/files/140626918/44ed21dd-a2a0-41bd-8f71-1d318104695e/download](https://app.zenhub.com/files/140626918/44ed21dd-a2a0-41bd-8f71-1d318104695e/download)

**Comment by TracyLinder** [comment]
Per Sree: Still awaiting stakeholder feedback. Prelim testing still in progress. 

Nate: Stakeholder UAT pending; our stakeholder resources are spread thin right now.

**Comment by Nadin-Nader** [comment]
Sent another email to see if Kim and Paloma agree on the changes mentioned in Kim's email or if they arew going to give the go ahead to promote to PROD:

Hi Kim and Paloma,

Reaching out to see if you have looked over the updates and come to a consensus on the changes mentioned in Kim’s last email or if Sree can go ahead and promote the changes to PROD.

Please let me know as soon as you can, Sree is waiting on the go ahead to promote this to Prod or make any last changes.

Respectfully,

Nadin A. Nader 
IT Business Systems Analyst
Data and Technology Services 
Austin Transportation Department

**Comment by TracyLinder** [comment]
**Status:** Currently in Dev Ops, trying to get to Dev & Prod

**Comment by Sreelatha-BlazeKannan** [comment]
SCTASK0075453  Service ticket to the View from DEV to TEST Created.

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan  @TracyLinder  #3058 has been closed by the DevOps CM Team and the views were added. I have created the TASK for AMANDA Tango to deploy the forms to DEV, TEST and PROD (SCTASK0075639)

**Comment by Nadin-Nader** [comment]
**Status:**

Waiting for deployment by Team TANGO at CTM

**Comment by Nadin-Nader** [comment]
Sent email to CM Team asking for update:

> Hi Team,
> 
> Hope everyone is doing well. I was wondering if I could get a status on SCTASK0075639? I have attached the new forms to it and the views should now be on TEST and PROD for the forms to work. Please let me know as soon as you can so I can update the stakeholders.
> 
> Respectfully,
> 
> Nadin A. Nader 
> IT Business Systems Analyst
> Data and Technology Services 
> Austin Transportation Department
> 
>

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder Surya will be deploying this all the way to PROD today.

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder 
Deployment has been halted due to the heading being cut off on some of the forms and to see where this font file needs to be ran or placed in order for the barcodes to come out.
Surya messaged and will be closing the task because this deployment is incomplete and we now need approval from Gita and Jenice to run the file or place it on the appserver.

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan Surya has placed the files on DEV and TEST. Once you approve and test it she will copy the file to PROD. Then we can deploy the forms to all 3 environments.

**Comment by Nadin-Nader** [comment]
All necessary Views and Files have been placed on all servers for AMANDA.
Next Step:

- [ ] Create Task for Surya to deploy forms to all 3 environments (DEV TEST and PROD)
- [ ] UAT

**Comment by Nadin-Nader** [comment]
**Status**
CTM TASK number SCTASK0079585. Waiting on Deployment of forms to all 3 environments

**Comment by Nadin-Nader** [comment]
Updated #3244 with status saying: Triaged by CTM Tango on 7/7/2020. Should be deployed by 7/10/2020. Waiting on Deployment by CTM Tango

**Comment by Nadin-Nader** [comment]
@TracyLinder @Sreelatha-BlazeKannan @SubhaShroff  This is ready for UAT on PROD

**Comment by TracyLinder** [comment]
Customers are reporting issues with the TURP permit, see attachment. @Nadin-Nader will be rolling that update back. 
[TURP Permit Email.pdf](https://github.com/cityofaustin/atd-data-tech/files/4962704/TURP.Permit.Email.pdf)

**Comment by Sreelatha-BlazeKannan** [comment]
The Sections misplaced in 50511 TURP Report and fixed this issue. and Sending the new Report with sample on 07/24/2020.

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan The Deployment for the rollback was sent to CTM on task SCTASK0083905 and it has been deployed.

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan New deployment task for the corrected TURP for is SCTASK0084421.

**Status:**
Waiting on CTM to deploy to PROD. I will deploy to DEV and TEST

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan I have placed the file on both DEV and TEST. Waiting on CTM for deployment to PROD (SCTASK0084421)

**Comment by Nadin-Nader** [comment]
The new file has been deployed to PROD by Robert on 7/28/2020. Sent email to Paloma, Ryan and Kim to TEST:

> Hi Everyone,
> 
> Hope you are doing well. I wanted to inform you that the New TURP with the revisions has been deployed to PROD. Please log on when you can and test it out. Let me know the outcome.
> 
> Respectfully,
> 
> Nadin A. Nader 
> IT Business Systems Analyst
> Data and Technology Services 
> Austin Transportation Department
>
