### ISSUE TITLE
Update "Journal Voucher" info in AMD Data Tracker - Warehouse Inventory- September 2024

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#18947]
- [x] Spreadsheet emailed from Finance staff month of: August (10/19/23-8/29/24)
- [x] Number of records being updated: 895
- [x] Format spreadsheet [(Review instructions)](https://atd-dts.gitbook.io/atd-knack-operations/warehouse-inventory-updating-journal-vouchers-jv-information)
- [x] Spot check Transaction IDs, no JV information before import: 36500 ✅ 
- [x] Import records
- [x] Spot check Transaction IDs, has JV information after import: 36500 ✅ 
- [x] Email Finance staff that update task complete
