### ISSUE TITLE
Needing 2 - iPad Pro 13in w/ 1TB storage. 2TB if possible. 

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#19017]
> What application are you using?

AMD Data Tracker

> Describe the problem.

Needing 2 - iPad Pro 13in w/ 1TB storage. 2TB if possible. Nano-Texture glass (works better in direct sunlight). Wi-Fi + Cellular enable for portability.

Justification:
*Thousands of photos and videos having to be stored on personal devices. Would be helpful if having a work ipad that has maximum storage for work applications.
*Adobe pro constantly freezing
*Portability - taking notes for meetings, taking pictures/videos for job research and job completion, among other things.
*iPad mini screen is to small for editing. 

Both ipad's will be for myself Andrew C and Miles M as we are both are editing/note managing/taking photos and videos.

If possible we are requesting also:
Apple Pencil Pro
Magic Keyboard for iPad Pro

> How soon do you need this?

Urgently — Critical that this is addressed today

> Requested By
Andrew C.

[Attachment](https://api.knack.com/v1/applications/595d00ebd315cc4cb98daff4/download/asset/66e2e5289d9d090304168458/ipadpro.png) (241.92kb)

Request ID: DTS24-117450

**Comment by scottreedy** [comment]
REQ0200632 - SCTASK0457058 - 2 iPad Pros for Billy Bolander 09/24/2024

**Comment by ChrispinP** [comment]
@scottreedy @dianamartin Has the stakeholder received these 2 devices? Do we know if they need to be tracked in AirWatch? Need to determine next steps, Thanks

**Comment by dianamartin** [comment]
@ChrispinP these would be going to AMD Supervisors, yes they need to be tracked.

**Comment by scottreedy** [comment]
@ChrispinP @susannegov 
The iPad Pro's are in for Andrew Costilla and Miles McGarrahan. They are on my desk.

Andrew Costilla
iPad Pro - 11"
s/n L1PYMP2GHF
(512) 925-8958
IMEI: 358314368499052

Miles McGarrahan
iPad Pro - 11"
s/n JQFL27P2Q0
(512) 939-6361
IMEI: 358314360898707

**Comment by susannegov** [comment]
# 10/21
Received iPads from Scott.
- [ ] Check tablet in DTS Portal
- [ ] Label tablets
- [ ] Add devices/users to AirWatch
- [ ] Give iPads

**Comment by ChrispinP** [comment]
Removed Devices from ATD OG in AirWatch, submitted CTM ticket INC0441289 to move to TPW OG

**Comment by ChrispinP** [comment]
Users added to TPW OG, Devices created, ready for setup

**Comment by susannegov** [comment]
- [x] Gave both iPads to Miles M.
- [x] Sent PDF to setup iPad tablet devices

**Comment by JBStrangenew** [comment]
Do Not Delete:



> What application are you using?

AMD Data Tracker

> Describe the problem.

Needing 2 - iPad Pro 13in w/ 1TB storage. 2TB if possible. Nano-Texture glass (works better in direct sunlight). Wi-Fi + Cellular enable for portability.

Justification:
*Thousands of photos and videos having to be stored on personal devices. Would be helpful if having a work ipad that has maximum storage for work applications.
*Adobe pro constantly freezing
*Portability - taking notes for meetings, taking pictures/videos for job research and job completion, among other things.
*iPad mini screen is to small for editing. 

Both ipad's will be for myself Andrew C and Miles M as we are both are editing/note managing/taking photos and videos.

If possible we are requesting also:
Apple Pencil Pro
Magic Keyboard for iPad Pro

> How soon do you need this?

Urgently — Critical that this is addressed today

> Requested By
Andrew C.

[Attachment](https://api.knack.com/v1/applications/595d00ebd315cc4cb98daff4/download/asset/66e2e5289d9d090304168458/ipadpro.png) (241.92kb)

Request ID: DTS24-117450
