### ISSUE TITLE
Install hardware for attendance tracker at Townview

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#19088]
Install 4 tablets with mounts, barcode scanner, and barcode scanner mount at Townview. Configure tablet for user and add shortcut to navigate to the Time & Attendance page on the HR Portal application
- [x] Central District Maintenance
- [x] UER Meeting Room
- [x] Overlay Meeting Area
- [x] Pavement Ops
