### ISSUE TITLE
Update DS Permit Workflow for Performance Measure Tracking(TL)

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#1909]
### As a ROW Permit Manager, I need to accurately report on performance metrics on the DS folder.
**Currently, we're unable to do this because the DS folder doesn't capture when we receive the permit request, or how long it take us to perform a review.**
**- To be scoped with #1994**

**Stakeholders:** Paloma, Kim
**DTS Manager:** Tracy

**Acceptance Criteria**
- When a DS folder is created, system should automatically insert a new process "DS Permitting Review"
- User should be able to make the following attempts on the DS Permitting Review Process: Start Review, Complete
- Attempt date should automatically be recorded when user makes an attempt in DS Permitting Review Process (this is a default AMANDA feature)
- Process status of DS Permitting Review process should be updated to Start Review when Start Review attempt is made
- Process status of DS Permitting Review process should be updated to Complete when Complete attempt is made
- System should insert the process Ended Date in DS Permitting Review process when attempt Complete is made
- DS Permitting Review Process should be mandatory for folder Issuance

Note: New Folder process to be created for DS review. List to be used “ROW INTAKE GROUP” 
 - Changes should not affect Post payment process. 

### Current Workflow
_As explained by Tracy_

1. DS permits are primarily created as part of the DSD development process, and are children of a parent BP folder
2. DS child permits, when created, default to folder status 'Pending'
3. DS customer may not initiate contact with ROW to get the permit until many months/year after the folder was created
    - For this reason, the folder In Date does not represent when the customer initiated permitting with ROW
4. When the customer initiates permitting with ROW, the permit analyst updates the folder tab, the people tab, the info tab, and the fee tab. No folder processes are used in the current workflow. 
5. When permit review is complete/approved, fees are billed and paid. 
6. The permit is issued after payment of fees
7. Due to this workflow, ROW is unable to answer these questions:
    - When did the customer initiate permitting with ROW?
    - How long did it take ROW to perform the DS review?

------

Description: Currently the DS folder is not configured to capture when the PLA receives a request to process the permit, so performance measure tracking is not possible. 

Request Date: 2018-11-29 17:09:00

Request ID: DTS18-103070

Status: Backlog

Customer Priority: 0

Level of Effort: Small Project

DTS URL: https://atd.knack.com/dts#service-requests/view-issue-details/5c0071b59ef08153aab1a076

*Migrated from [atd-amanda #44](https://github.com/cityofaustin/atd-amanda/issues/44)*

**Comment by SurbhiBakshi** [comment]
- DSD owns the DS folder
- PR creation auto generates trade permits including DS
- Since information is pulled from PR, indate is from PR
- Applicant may start work related to DS much later (sometimes a year), usually last in the trade permit phasing
- This gives the appearance of a much longer time needed to process a DS (In Date - Applicant comes to RW review team - review team processes DS) than the actual time needed
- Would like this date to be stored in the Folder Process tab, so a more accurate time reporting can be done for performance measures

**Comment by johnclary** [comment]
Per Paloma, this is a "nice to have" and may be difficult to solve. Could be dropped from Unisys backlog if there's a more important issue. Probably leave this one until Tracy's back.

**Comment by amenity** [comment]
Might be a BI workflow for this.

**Comment by amenity** [comment]
LIT has developer working on the folder for DSD who can answer questions.

**Comment by TracyLinder** [comment]
@kaarthym5 please schedule time with me & Robert this week so I can demo this folder for you.

**Comment by TracyLinder** [comment]
### Meeting Notes 8/11/20 w/ Kaarthy & Robert

- Tracy gave an overview of current DS workflow (when DS folder is created as a child of the BP instead of portal application)
- Discussed the Need/Ask:  a process that allows users to document when customer action was initiated, and when the review is complete
- Kaarthy is working on a DS workflow to help guide DS development

**Next Step(s):** 
- Kaarthy to schedule scoping w/ stakeholders, invite Tracy & Robert
- We need to make sure the reporting requirements in the issue description are still accurate, and that a new folder process is an acceptable solution

**Comment by TracyLinder** [comment]
### Current Workflow
_As explained by Tracy_

1. DS permits are primarily created as part of the DSD development process, and are children of a parent BP folder
2. DS child permits, when created, default to folder status 'Pending'
3. DS customer may not initiate contact with ROW to get the permit until many months/year after the folder was created
    - For this reason, the folder In Date does not represent when the customer initiated permitting with ROW
4. When the customer initiates permitting with ROW, the permit analyst updates the folder tab, the people tab, the info tab, and the fee tab. No folder processes are used in the current workflow. 
5. When permit review is complete/approved, fees are billed and paid. 
6. The permit is issued after payment of fees
7. Due to this workflow, ROW is unable to answer these questions:
    - When did the customer initiate permitting with ROW?
    - How long did it take ROW to perform the DS review?

_I will add this workflow to the issue description._

**Comment by TracyLinder** [comment]
[Here is a link](https://web.microsoftstream.com/video/d05abf28-cc58-493a-944d-612fac8889d9) to the meeting recording

**Comment by TracyLinder** [comment]
Possible Solution:  50075 Right-Of-Way Admin: Add new attempt 'Start Review'

**Comment by kaarthym5** [comment]
@tracyLinder @licarir meeting with Stakeholders Paloma and Kim is complete. Stakeholders agreed to the solution we presented. As discussed a new process will be created, list to refer here will be from “Row Intake Group”. Will update AC and move the story to backlog.

**Comment by kaarthym5** [comment]
@tracylinder @licarir this requirement scoping is complete, ready to start work.

**Comment by TracyLinder** [comment]
@vschandramouli will work on re-writing the acceptance criteria on this issue.

**Comment by vschandramouli** [comment]
Updated acceptance criteria for this ticket. The acceptance criteria that was removed is provided below for reference: 

- User should be able to start a review process on DS permit workflow 
- User should be able to approve a permit 
- User should be able to complete a permit 
- System should be able to capture start and end time of the review for report 

Questions needing answers for scoping to be complete: 

- What actions should the attempt results do to folder and process statuses?
- Are creating reports using the newly recorded metrics also part of ticket scope?
- Per Tracy's comment: Should these attempts be required for folder issuance?
- If no processes are currently used, would it help improving workflow to add payment procedure to Complete attempt of DS Permitting Review process?
- Any other workflow improvements needed for the new process?

**Comment by vschandramouli** [comment]
Updated acceptance criteria after meeting with Kim and Paloma on 9/18 - added that the process will be mandatory for folder issuance. 

Acceptance criteria definition is complete.

**Comment by Nadin-Nader** [comment]
@vschandramouli Great Job on this. Looks Backlog ready.

@TracyLinder Moving to Backlog for next available sprint

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder, @Nadin-Nader - Subha is working on this card.

**Comment by TracyLinder** [comment]
Thanks Sree, I just moved it to In Progress.

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @SubhaShroff @TracyLinder @vschandramouli I have looked over the demo and found that this has met the acceptance criteria.

## **Approved for TEST!!🎉**

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder, @Nadin-Nader  - Subha will be sending the TEST Deployment plan

**Comment by shroffjs** [comment]
@TracyLinder @Nadin-Nader @Sreelatha-BlazeKannan DEV/TEST Promotion Requests are submitted: SCTASK0100400, SCTASK0100404.

**Comment by shroffjs** [comment]
@TracyLinder @Nadin-Nader @Sreelatha-BlazeKannan The change is deployed in DEV/TEST and tested on both instances for BO and Portal sides. Its ready for your testing.

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder @SubhaShroff I have UATd this on DEV and TEST and found that the acceptance criteria has been met.

**Next Step is to UAT with Stakeholder on TEST for approval to move to PROD**

**Comment by TracyLinder** [comment]
Let's test this w/ ROW during our weekly meeting on 10/23

**Comment by TracyLinder** [comment]
### UAT Acceptance Criteria

- [ ] When a DS folder is created, system should automatically insert a new process "DS Permitting Review"
    - Note: New Folder process to be created for DS review. List to be used “ROW INTAKE GROUP”
- [ ] User should be able to make the following attempts on the DS Permitting Review Process: Start Review, Complete
- [ ] Attempt date should automatically be recorded when user makes an attempt in DS Permitting Review Process (this is a default AMANDA feature)
- [ ] Process status of DS Permitting Review process should be updated to Start Review when Start Review attempt is made
- [ ] Process status of DS Permitting Review process should be updated to Complete when Complete attempt is made
- [ ] System should insert the process Ended Date in DS Permitting Review process when attempt Complete is made
- [ ] DS Permitting Review Process should be mandatory for folder Issuance

- [ ] Changes should not affect Post payment process.

**Comment by TracyLinder** [comment]
This is approved for Prod, however the customer wants to schedule deployment for 11/3/20. 

### Approved for Prod deployment on 11/3/20 🎉

@SubhaShroff please confirm you see the 11/3 schedule for this one. Thank you.

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder, @Nadin-Nader - Subha will be sending the PROD DP to move on 11/3/2020

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder, @Nadin-Nader - PROD deployed by tomorrow. Subha just need confirmation from Tracy if I can go ahead for deployment for tomorrow, so that request can be submitted today

**Comment by TracyLinder** [comment]
@Sreelatha-BlazeKannan @SubhaShroff Yes please, submit for prod deployent for 11/3

**Comment by shroffjs** [comment]
@TracyLinder @Nadin-Nader @Sreelatha-BlazeKannan A PROD deployment request is submitted: **SCTASK0103257**

**Comment by TracyLinder** [comment]
Per Nate, it hasn't deployed due to the election code freeze. Deployment scheduled for tomorrow 11/5 after 5pm. 
@TracyLinder follow-up w/ stakeholders.

**Comment by TracyLinder** [comment]
Per Nate, the prod deployments were buggy last night. The promote has been scheduled for Monday 11/9

**Comment by shroffjs** [comment]
@TracyLinder @Nadin-Nader @Sreelatha-BlazeKannan SCTASK0103257 is closed and this ticket is PROD deployed.

**Comment by TracyLinder** [comment]
Awesome!!! I will inform stakeholders today!
