### ISSUE TITLE
Project: 2019 Print Bike Map

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#1911]
## Description
The City of Austin publishes a print version of the bike map every year. The bike map shows the recommended routes for bicycling, and it displays them by level of comfort so that they may be useful for people of all ages and abilities. The bike map is a collaboration between Active Transportation & Street Design, Public Information Office and the Data & Technology Services Team at Austin Transportation Department.
The map is currently being printed and will be distributed for free through ATD, libraries, and bike shops.

### Resources

[cityofaustin/atd-geospatial/issues/73](https://github.com/cityofaustin/atd-geospatial/issues/73)
[Mapping Comfort](https://peopleforbikes.org/blog/mapping-comfort-how-psychological-stress-influences-bike-maps/)
[Four Types of Cyclists](https://www.portlandoregon.gov/transportation/44597?a=237507)

*Migrated from [atd-geospatial #73](https://github.com/cityofaustin/atd-geospatial/issues/73)*

**Comment by atdservicebot** [comment]
*From alan-deanda on 2019-06-10*:

• Learned that many new subdivisions and streets are missing from bike map (last GIS import seems to be mine from 2014).
• Started querying data to import new streets and created templates for import into AI
• Refine streets template for import into AI - it doesn't align perfectly well despite following scale levels and document size conventions found in bike map folder in G Drive.
• Simplify street geometry once in AI
• Update missing streets
• Work on simpler symbology to potentially combine stroke and shadow into single line. The fact that they are split into separate geometries causes several issues:
    1. The map is hard to work on due to all the overlapping lines (especially for new people)
    2. We end up with duplicate geometries that make the map messy
    3. The map loads more slowly

__Sophia Benner may need to leave project to focus on other work, and I may need to update the front of the map as well the as the back.__

**Comment by atdservicebot** [comment]
*From alan-deanda on 2019-10-02*:

### _Updates:_ ###
* Still working on basemap issues
* Sophia Benner will concentrate on infographics, and I will continue to update the map itself
### Upcoming tasks: ###

- [x] Finish updating missing streets and labels
- [ ] Define symbology for trails on which dockless mobility devices are not allowed on
- [x] Simplify document (this will be a long task that may need to happen post  current update)

**Comment by atdservicebot** [comment]
*From johnclary on 2019-08-21*:

@alan-deanda i added the `Index` label to this project. would you update the description to match our project template?

**Comment by atdservicebot** [comment]
*From alan-deanda on 2019-08-21*:

@johnclary I've updated the description to match the project template. Would it be more to spec to create a Project Index issue in the atd-datatech repo that cites this issue (currently in geospatial) as a reference?

**Comment by atdservicebot** [comment]
*From johnclary on 2019-08-21*:

@alan-deanda good catch. Yes, please do exactly that!

**Comment by alan-deanda** [comment]
The 2020 Edition of Austin's Print Bike Map has been completed and it will be printed, proofed and published / released in the near future.

**Comment by alan-deanda** [comment]
The 2020 Edition of the Austin Print Bike Map has been delivered to ATD! Sophia and ATSD will begin distributing the map to bike shops this week.

**Comment by johnclary** [comment]
@alan-deanda amazing. I want one! We'll keep my eye's peeled at CycleEast
