### ISSUE TITLE
Rename repo to `vision-zero`

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#19146]
It would be valuable to have the Vision Zero repo name clearly connect with the national/global Vision Zero project. We should rename it from `atd-vz-data` to `vision-zero`.

### Todo

- [x] Update netlify configs
- [x] Vision zero footer link to **Code**
- [x] Gitbook links
- [x] Search readmes and other places which may reference the repo name 
- [x] Product index issue: https://github.com/cityofaustin/atd-data-tech/issues/255
