### ISSUE TITLE
Feature - Digital Interview Ability to Import Applicants from external source (EasyCSV)

### ISSUE THREAD

**Issue by stephaniemoorer** [cityofaustin/atd-data-tech#19180]
Ability to import Applicants from the eCareer Applicant List (excel spreadsheet)  to Edit Applicants page in Knack TPW Hire/Hiring Management/ Edit Applicants.

## Current Process 
- HR recruiters used to maintain a centralized spreadsheet per PCN position. 
- They download the eCareer Report
- They copy & paste from the eCareer spreadsheet to the `HR.Digital.Interview.Hiring.Packet.-.Sample.1`

## Future Process
We are developing a TPW Hire application that is a centralized place to manage job posting information, that replaces the spreadsheet. 

## Requested enhancement
However, HR recruiters download a report from the eCareer website and need the ability to import a spreadsheet into a Knack table `job_applicants` as a front-end user.

### Old Interview Packet - `HR.Digital.Interview.Hiring.Packet.-.Sample.1`
![image](https://github.com/user-attachments/assets/3d063203-38c4-485a-91ed-786c3d2875b5)

### Knack - job_applicants
- [job_applicants.csv](https://github.com/user-attachments/files/17236361/job_applicants.csv)

### TPW Hire - Candidate Matrix
![image](https://github.com/user-attachments/assets/0ad762d7-8ecb-433c-9aee-3dba794af2f7)

**Comment by dianamartin** [comment]
# 10/24/24
Worked on this a little yesterday with Patrick
- [x] Went to EasyCSV, signed in using Google work account
- [x] Created "Job Applicant" template spreadsheet
- Tried to configure, but needed to configure a few things before

## Configure first
- [ ] Create API table view (TPW Hire, the Job Applicant table is in TEST)
- [ ] Create new TPW Hire Environment (that has Job Applicant table)

## Testing Steps
- [ ] Log back into EasyCSV
- [ ] Have API URL
- [ ] Test process

**Comment by dianamartin** [comment]
# 10/29/24
## Import Data Flow
- Send via email
- Configure columns
- Configure API URL 
  - `https://api.knack.com/v1/objects/object_XX/records`
  - Select JSON
- Add Custom Headers
Key: X-Knack-REST-API-KEY

Value: `ENTER API KEY` (Knack)

Key: X-Knack-Application-Id
Value: `ENTER APP ID` (Knack)

**Comment by dianamartin** [comment]
@ChrispinP 
Tried to do embed only works on like w3schools.com
![image](https://github.com/user-attachments/assets/079f24f3-7611-49cc-ada3-c25a75dc935f)

**Comment by dianamartin** [comment]
# 10/30/24
This JSON is working correctly
```
{
  "field_334": {
    "first": "{{ FIRST }}",
    "last": "{{ LAST }}"
  },
  "field_328": "{{ PHONE }}",
  "field_376": {
    "email": "{{ EMAIL_ADDRESS }}",
    "label": "{{ EMAIL_ADDRESS }}"
  }
}

**Comment by dianamartin** [comment]
# 10/31/24
Max from EasyCSV point me to a Knack API article: https://docs.knack.com/docs/working-with-fields. This is probably my issue, I need to have the corresponding `Knack record id`.

**Comment by dianamartin** [comment]
# 11/15/24
- Looking at the article an read 
## Connection

Connections are stored as arrays of record IDs (strings), even when there is only one connected record. Each of these is the ID of a record of the object to which this field connects.

JSON
// More than one connected record
["4fea069e9e8246001d000698", "4fea069e9e8246001d000699"]

// One connected record
["4fea069e9e8246001d000699"]

- I found another article [Finding Record IDs] - backend: https://docs.knack.com/docs/finding-record-ids
- Tested just doing this on the front end

## Steps to finding Record ID on the front end
- Went to "Hiring Management" table/page
- Put cursor near the "Edit Button", right click "Inspect" 
- The row above "<tr id=XXXXXXXXXXXXXXXXXXXXXXXXX"> - is the record ID

**Comment by dianamartin** [comment]
# 11/18/2024
Stephanie and I synced and we decided to do some usability tests on three different methods. 
## Option 1: Manual Entry
- Have a list of 6 applicants
- Have the user type them in using the manual knack form entry
- This process automatically associates the users to the hiring record

## Option 2: Copy & Paste Entry
- Have a list of 6 applicants
- Have the user copy and paste from another spreadsheet (looks like eCareer) using the manual knack form entry
- This process automatically associates the users to the hiring record

## Option 3: EasyCSV import process
- Have a list of 6 applicants
- Have the set up 2 spreadsheets (bc of testing limitations)
- User has to copy & paste PCN ID
- User has to go to "Import Applicants" find the 6 applicants and associate them to the PCN ID
- This process automatically imports users to the "Job Applicants" list and then the user must relate them to the hiring record

### Dependency
- have to purchase EasyCSV 
- Start off with $9/month = $108.00 year (test for a year?)

**Comment by dianamartin** [comment]
# 11/18/24
json that works

```{
  "field_334": {
    "first": "{{ FIRST_NAME }}",
    "last": "{{ LAST_NAME }}"
  },
  "field_328": "{{ PHONE }}",
  "field_376": {
    "email": "{{ EMAIL_ADDRESS }}",
    "label": "{{ EMAIL_ADDRESS }}"
  },
  "field_227":"{{ JOB_POSTING_MANAGEMENT }}"
}

**Comment by dianamartin** [comment]
# 12/9/24
Gave Chrispin the spike to see if he can associate connected records when importing in

**Comment by dianamartin** [comment]
# 3/18/25
- 2/7/25: Integrated EasyCSV with TPW Hire - Test during discovery day
- 2/14/25: EasyCSV was procured Feb 2025
- 2/22/22: Integrated EasyCSV with TPW Hire - Production during discovery day
