### ISSUE TITLE
Updates to supervisor attendance tracker page

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#19198]
- Greg has requested that we update the Supervisors page for the Attendance Tracker so they can start flagging Missed Punches and Late occurrences while District Maintenance is testing

**Comment by dianamartin** [comment]
# 9/25/24
The "Manage Employee Logs" page used to have multiple tables on them separated by Division. 

## Version 1
![image](https://github.com/user-attachments/assets/d5c31291-afc6-4366-a167-8b8f75f4d467)

## Version 2
- [x] Added JS code for big buttons
- [x] Updated the tables to include the Division and Review Status "Needs Review"
![image](https://github.com/user-attachments/assets/cf1cacab-8d81-4350-9782-f703cc1c9fa4)

**Comment by dianamartin** [comment]
@ChristinaTremel I think this is ready to show Greg, I know we worked on it together last week.

**Comment by dianamartin** [comment]
# 10/16/2024
- [x] Reconnected the filtered tables to the "Employee Log | Dashboard" buttons

**Comment by dianamartin** [comment]
# 1/2/25
Still need to create big button for "Logistics" for Tyler S.

**Comment by ChristinaTremel** [comment]
@dianamartin I think this issue could be closed out because I created #20442 for adding the logistics big button!
