### ISSUE TITLE
Please adjust CSR summary table on Signal details page to not stretch the whole table with links

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#19360]
> What application are you using?

AMD Data Tracker

> Describe the problem.

Please adjust CSR summary table on Signal details page to not stretch the whole table with links from "https://base64.spotutil.com/d..."

Example: Signal details page for 630: Southwest Parkway and Encino Trace

> Describe the outcome you'd like to see when this feature is implemented.

The CSR summary table not being stretched with links from "https://base64.spotutil.com/d..."

Example: Signal details page for 630: Southwest Parkway and Encino Trace

> Describe any workarounds you currently have in place or alternative solutions you've considered.

Scrolling repeatedly 

> Is there anything else we should know?

N/A

> Requested By
Allyson R.

Request ID: DTS24-118100

**Comment by ChristinaTremel** [comment]
Example provided by Allyson: 
- https://atd.knack.com/amd#signals/signal-details/5817c08ee052e0422be6c79a/
![image](https://github.com/user-attachments/assets/09985eca-90f1-4cde-97c9-b05a4a5cddfd)

- Need to restrict column width limits

**Comment by dianamartin** [comment]
# 10/30/24
Signals>Signal Details>Service Requests table

## Before
"Details" field is currently set to Column Width "Default", Align "Left"
![image](https://github.com/user-attachments/assets/41fca006-8cc6-44b6-8a25-cac4e73dfaf0)

## Testing
- [ ] Changed fields to percentages
- [ ] Changed fields to pixels
- Seemed like it's not working because the 311 auto translated text entered in the "Details" is a long web URL

**Comment by dianamartin** [comment]
# 11/8/2024
- looked at Signal `630`
- The URL is very long, it's just a repeat of what's in the cell. It's not really useful..
- Will search to see how many other records are coming in this way - `224 records..` 🙄 
- Added to a "Character Counter" online and the URL was `462` characters
- Wondering if I can reach out to Carrie about if we should still be receiving translation logs if the origin context is in english. 
ex. 
![image](https://github.com/user-attachments/assets/6facc18b-572f-4745-8761-27ae26d9ffd5)

Why does this need a translation?

**Comment by dianamartin** [comment]
# 11/25/24
Synced with Christina and tried a tip from Chrispin. 
- [x] We updated the "Detail" field on the table and clicked "truncate text"

## Details configuration
![image](https://github.com/user-attachments/assets/02a2b6cc-74ad-4e84-9b4a-42748dd9bceb)

## Service Requests table
![image](https://github.com/user-attachments/assets/9cc98af0-d79b-4656-afcf-a62a1e8eb117)
