### ISSUE TITLE
AMD Data Tracker - set up additional record rules for 311 Feedback outcome code changes

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#19409]
John and I synced about updating the outcome codes and he expressed some concerns about the 311 Feedback & Closed (Resolved) outcome codes overriding each other. He proposed the idea of updating the outcome code for 311 Feedback to close out the CSR at that point instead of requiring users to add the Closed (Resolved) activity. 

We tested the outcome code in Data Tracker test and it successfully closed the 311 SR as we expected. To fully implement this into production, we need to update record action rules on the [Add Activity](https://builder.knack.com/atd/amd/pages/scene_428/views/view_1437/form) form. 

Need to duplicate these rules and update the "when" criteria for the new rules to be When `TMC_ACTIVITY` is `311 Feedback`
   
   <img src="https://github.com/user-attachments/assets/5b78a67d-38f8-4179-a394-9cb7cbf73572" height="400" />
   <img src="https://github.com/user-attachments/assets/e0b88545-8a80-456b-a9d1-25dc5b909337" height="600" />

Then need to remove this rule: 
   <img src="https://github.com/user-attachments/assets/2fa61ac4-8665-4eca-9edb-90860f46505a" height="400" />

Christina will coordinate with AMD and SMD about the process change for 311 feedback and let them know that if they use 311 feedback with this new structure, they no longer need to add the Closed (Resolved) activity.

**Comment by susannegov** [comment]
# 1/28
- [ ] Remove Record Rule 17
- [ ] Duplicate Record Rule 11 but for when 311 Feedback
- [ ] Duplicate Record Rule 12 but for when 311 Feedback

**Comment by ChristinaTremel** [comment]
Tested outcome codes and they are populating in the MMC issue and in 311 correctly. 🎉
