### ISSUE TITLE
Make TRANSPORTATION_markings_long_line and TRANSPORTATION_markings_long_line_dates datasets public in City Datahub

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#19451]
### Steps to take
- Add metadata to [`TRANSPORTATION_markings_long_line`](https://datahub.austintexas.gov/dataset/TRANSPORTATION_markings_long_line/nxkm-x3yr/about_data) and [`TRANSPORTATION_markings_long_line_dates`](https://datahub.austintexas.gov/dataset/TRANSPORTATION_marking_long_line_dates/m49j-isdy/about_data) datasets
- Andrew to change FME flow from private to public
- Change from private to public on City Datahub

**Comment by susannegov** [comment]
# To Do
- [ ] Update metadata for markings_long_line_dates
- [ ] Make the ArcGIS Online long line dataset public
- [ ] Link to that AGOL feature service layer on the description for ODP
- [ ] Review the metadata for both datasets with Karo
- [ ] Set EDP -> ODP to Public in FME and the datahub

**Comment by ChristinaTremel** [comment]
- Updated the metadata on the [TRANSPORTATION_marking_long_line_dates](https://datahub.austintexas.gov/Transportation-and-Mobility/TRANSPORTATION_marking_long_line_dates/m49j-isdy) dataset
- Let Susanne know this has been completed! We will check in with Karo today to confirm that the metadata is updated as it should be.

**Comment by andrewshensky** [comment]
- AGOL data has been made public
- AGOL URLs have been added to EDP descriptions
- FME processes have been updated to push data to EDP publicly 

Let me know if anything else is needed on the geo side for this

**Comment by susannegov** [comment]
Verified that both datasets are public as expected. Closing issue.
