### ISSUE TITLE
Add SLA Due Date field to Markings Work Orders

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#19668]
- Add an `SLA due date` for the following requesters
   - Set record rules for these due dates
      - SBO Whereabouts (SLA due date 60 days after SBO Completed Date)
      - 311 (SLA due date 60 days after 311 SR created date)

- Email notifications for due dates: 
   - Please add an auto-email notification when this due date field is within 2 weeks of being due. Is it possible to make these emails weekly as opposed to receiving individual emails for each item? So, we would in theory receive a weekly email that lets us know all open jobs that have a 311/SBO due date that falls within 2 weeks of the notification being sent out.
      - Address 311 email bug #18724

_Originally posted by @ChristinaTremel in https://github.com/cityofaustin/atd-data-tech/issues/15870#issuecomment-2411445191_

**Comment by susannegov** [comment]
# 11/01
- [x] Added `SLA Due Date`
-

**Comment by susannegov** [comment]
@ChristinaTremel who are the email addresses?

**Comment by susannegov** [comment]
# 11/07
- [x] Added `CALCULATE SLA Notification Date
- [x] Added `SLA Notification Date`
- [ ] Add task for custom email

**Comment by susannegov** [comment]
# 11/08
- Fixed URL link
- Removed myself from task
- Added additional if work order status is not cancelled and work order status is not closed for email task

**Comment by ChristinaTremel** [comment]
Thanks for these updates Susanne! These emails should be sent to Joseph B, Stephen B, and Esteban G.
