### ISSUE TITLE
I am entering a new inventory item and entered the incorrect stock number.

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#19847]
> What application are you using?

Finance & Purchasing Portal

> Describe the problem.

I am entering a new inventory item and entered the incorrect stock number. I need to re enter without the dash, i entered with dash

> How soon do you need this?

Soon — Within a week 

> Is there anything else we should know?

Trying to prevent any issues 

> Requested By
Cesar M.

[Attachment](https://api.knack.com/v1/applications/595d00ebd315cc4cb98daff4/download/asset/672e6a9c8adc3402ab462790/55081845818.png) (32.99kb)

Request ID: DTS24-119090

**Comment by dianamartin** [comment]
# 11/13/2024
Cesar entered the Stock Number with dashes and we already have a field that auto inserts dashes. 
- [x] Updated Stock Number to `55081845818`, rather than `550-81-845818`
![image](https://github.com/user-attachments/assets/df008cd0-5c56-47df-b216-d0a1a0d028c8)

- [x] Updated Stock Number to `55085570001`, rather than `550-85-570001`
![image](https://github.com/user-attachments/assets/0b2e25a6-6ee1-4700-a6dc-55019df32b61)

**Comment by stephaniemoorer** [comment]
This is complete

**Comment by dianamartin** [comment]
# 11/27/24
Cesar messaged 
>Hi Diana, I was working with Stephanie M. on a ticket i opened up and wondering if she is out of the office. I opened a ticked because i entered two commodities incorrect in the system, i entered them with dashes when it should have been without. The commodities are 55085570001 and 55081845818. She said she fixed them in the system but when i look at them in AMD Knack they still show incorrect. I know you and i corrected a similar issue about 4-6 months ago and wanted to see if you can give some input. Thanks 

I replied
>Hi Cesar, I'm not sure if she's online today, but it sounds like we corrected the issue on the Finance system. There is an integration to the AMD Data Tracker. I speculate that bc we changed the Stock Number that it's not syncing. So I'll have to change it in the Data Tracker also.

**Comment by dianamartin** [comment]
# 11/27/24
- [x] Updated Stock Number to `55081845818`, rather than `550-81-845818`
### Before
![image](https://github.com/user-attachments/assets/b0ec9b70-0a8b-4a9a-af42-d53621a38d91)

### After 
![image](https://github.com/user-attachments/assets/77dd04b6-70ac-40cb-b2da-894d8d631283)

- [x] Updated Stock Number to `55085570001`, rather than `550-85-570001`
### After
![image](https://github.com/user-attachments/assets/571df49c-bed7-4787-9392-ab894a2f2e18)
