### ISSUE TITLE
Scope building a TPW 311 CSR SharePoint site

### ISSUE THREAD

**Issue by katelunceford** [cityofaustin/atd-data-tech#19886]
Research possible solutions, identify requirements, how DTS can help, and maintenance plan

- [x] Research possible solutions
- [x] Hold project intake meeting with stakeholders #20513
- [x] Get sponsorship, review what we have so far, fill in the blanks #20694
- [x] Discuss recommended approach & assess effort with builders #19888
- [x] Assess value with product team + stakeholders #20520
- [x] Prioritize among other DTS projects
- [x] Sync with Dan after scope expanded with workflows #21638 

## Background 

A recommendation in the [Executive Summary](https://cityofaustin.sharepoint.com/:w:/r/sites/TPWOPM/_layouts/15/doc2.aspx?sourcedoc=%7B1DB32871-8B8A-4AFE-938F-2311AC2EB4DE%7D&file=2024.10_CSR%20Public%20Communication%20Project_Executive%20Summary.docx&wdLOR=c2CCB43BB-4230-6148-B44B-A4AF964C3D88&action=default&mobileredirect=true) for the [311 CSR Public Communication Discovery project](https://github.com/cityofaustin/atd-data-tech/issues/18136) is to develop and maintain a TPW 3-1-1 CSR dictionary: 

> Standard definitions that all divisions agree upon for CSR terms, processes, and tools is currently missing from TPW. This foundation of shared language among TPW’s various work groups would help provide a positive, consistent experience to residents who submit a CSR, as well as align data and reporting across all levels of TPW and the COA. For example, what is the TPW definition of response, closed, or completed? 

## References
- [311 CSR Public Communication Discovery project](https://github.com/cityofaustin/atd-data-tech/issues/18136)
- [311 CSR Public Communication Project: Executive Summary](https://cityofaustin.sharepoint.com/:w:/r/sites/TPWOPM/_layouts/15/doc2.aspx?sourcedoc=%7B1DB32871-8B8A-4AFE-938F-2311AC2EB4DE%7D&file=2024.10_CSR%20Public%20Communication%20Project_Executive%20Summary.docx&wdLOR=c2CCB43BB-4230-6148-B44B-A4AF964C3D88&action=default&mobileredirect=true)
- Placeholder for drive folder where project materials are stored

## Request details
- Requested by: Jim Dale
- Executive sponsor: 
- Date: 10/30/24

**Comment by katelunceford** [comment]
Product/apps sync 1-8-25
- We don't want to build another app that then also has to be maintained, when a simpler solution with enterprise software we already have is doable
- If all we need is a simple, searchable table, we could build a list in SharePoint
   - APWA progress tracker 
   - https://cityofaustin.sharepoint.com/sites/CTMITServiceCatalog/Lists/CTM%20Supported%20Software/AllItems.aspx
- We don't need an entire project to create this list, but building a SharePoint page for all things 311 CSRs could be the project with the glossary as one component
   - We build the page, OPM maintains content

**Comment by katelunceford** [comment]
### Prep huddle with Karo 1-16-25

- See this as a standalone site - not inside some group's 
- Who will need to access it? It's easy if they have an austintexas.gov email. If not, we can still invite them but it's more work
   - Likely TPW staff, will check during project intake
- Two SharePoint site options: communication site or teams site
   - Communication site
      - One-way, this is the information
      - Has a top header of links
      - Just the site (no group, calendar, or email account)
      - Has site owners and folders to organize
      - Easier to maintain, update
      - Example: [PIO page](https://cityofaustin.sharepoint.com/sites/tpwPIO)
   - Teams site
      - Meant for group collaboration
      - Has a sidebar of links (can hide this if we want)
      - Comes with a Microsoft group, calendar, and email account
      - More to manage
      - Example: CTM's [Enterprise Open Data Portal Program page](https://cityofaustin.sharepoint.com/sites/CTM/TEAMSITES/EADS/EODP/SitePages/City-Data-Hub.aspx?xsdata=MDV8MDJ8fGFjZTY4YmJmYTE2ODQ4ZmVkOWJkMDhkZDM1YTFhMmM3fDVjNWUxOWY2YTZhYjRiNDViMWQwYmU0NjA4YTlhNjdmfDB8MHw2Mzg3MjU2OTA0OTM0OTE2NDV8VW5rbm93bnxWR1ZoYlhOVFpXTjFjbWwwZVZObGNuWnBZMlY4ZXlKV0lqb2lNQzR3TGpBd01EQWlMQ0pRSWpvaVYybHVNeklpTENKQlRpSTZJazkwYUdWeUlpd2lWMVFpT2pFeGZRPT18MXxMMk5vWVhSekx6RTVPbTFsWlhScGJtZGZXVmRSZUZwdFdtaFpla0YwV1hwWk0wNVRNREJaYWtab1RGZEpNVTB5VFhSWlZHaHBUMWRaTlUxdFdYbFpNa2sxUUhSb2NtVmhaQzUyTWk5dFpYTnpZV2RsY3k4eE56TTJPVGN4T1Rrek5ETXd8ZmEyNDg4Mjc3NDlhNGZlMWQ5YmQwOGRkMzVhMWEyYzd8Yzk0NTg5MWI0NzZmNGMxZDgyZmFiYmE4YjRhMDMxZTA%3D&sdata=QngvNVozeVc3eFhvdFdnZjZ3UDdicGhMZzdLdDY5WUZpbElrbXZIOHJwWT0%3D&ovuser=5c5e19f6-a6ab-4b45-b1d0-be4608a9a67f%2CKate.Lunceford%40austintexas.gov&OR=Teams-HL&CT=1737045860085&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiI1MC8yNDA4MDIxMjAwOCIsIkhhc0ZlZGVyYXRlZFVzZXIiOmZhbHNlfQ%3D%3D)
- Need to decide the URL - this is hard to change later on 
   - TPWHub for our main site
   - tpwDTS, tpwFinance, etc for group/program/other sites
   - tpw____, maybe tpw311

**Comment by katelunceford** [comment]
Project is scoped
