### ISSUE TITLE
Feature: Create accounts for individual SBO tablets being used to badge in/out

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#19892]
For the SBO Time & Attendance tracking, we need the ability in the Human Resources Knack application to create accounts for individual tablets to track the locations that users are badging in at.
- Need to check in with the Dev team to understand how we can do this without these accounts being inactivated every the banners ETL runs.

**Comment by ChristinaTremel** [comment]
- Add field for `Tablet Account` yes/no and if it's flagged as yes exclude from the ETL updates
- @chiaberry will check the code

**Comment by chiaberry** [comment]
@ChristinaTremel 
We skip marking Contractors as inactive, since they will never be found in Banner
https://github.com/cityofaustin/atd-knack-banner/blob/production/update_employees.py#L302
You could mark Tablet Accounts as contractors, or add a Tablet Acccount option to the class field (field_95) and we can add a line to skip those from being deactivated.

**Comment by ChristinaTremel** [comment]
@dianamartin would we be okay with creating the tablet accounts and marking them as `Contractor` temporarily? And we could create a Tablet account and eventually change the type to that! 

The accounts we need to create are the following: 
- [ ] Townview - Conference Room
- [ ] Townview - Districts (by water cooler and printers)
- [ ] Townview - Fog seal (next to big TV)
- [ ] Townview - Overlay (up the hill)
- [ ] Dalton - Main Entrance (Vending Machine)
- [ ] Dalton - Interior (next to uniforms)
- [ ] Dalton - Bridges (Patty’s building)
- [ ] Kramer - Break Room
- [ ] Kramer - Hallway (near Supervisor/Superintendent offices)
- [ ] St Elmo - South District (interior meeting room)
- [ ] St Elmo - Sealcoat (first smaller meeting room)

**Comment by dianamartin** [comment]
@ChristinaTremel I think that's fine, I think we can put the information in `( )` in a different field under "notes"?

**Comment by ChristinaTremel** [comment]
- [x] Created `Notes` short text field to include additional information about tablet accounts
- Creating 10 accounts, with "Class" flagged as `Contract`
   - [x] Townview - Conference Room
   - [x] Townview - Districts (by water cooler and printers)
   - [ ] Townview - Fog seal (next to big TV)
   - [ ] Townview - Overlay (up the hill)
   - [ ] Dalton - Main Entrance (Vending Machine)
   - [ ] Dalton - Interior (next to uniforms)
   - [ ] Dalton - Bridges (Patty’s building)
   - [ ] Kramer - Break Room
   - [ ] Kramer - Hallway (near Supervisor/Superintendent offices)
   - [ ] St Elmo - South District (interior meeting room)
   - [ ] St Elmo - Sealcoat (first smaller meeting room)
 - All emails start with `SBOtimelog-` so these can be filtered out of account views that HR staff uses
    - [x] Added filter to Employees page to exclude emails containing `SBOtimelog-`

**Comment by ChristinaTremel** [comment]
- Messaged Greg to let him know that I was able to create the accounts. He logged on to test from the Townview - Fog Seal tablet. We had to troubleshoot a little because he logged in from Chrome and tried using the bookmark, but the bookmark wasn't logged in. We are going to have to log into the tablet accounts through Chrome and re-save the bookmark to ensure we are capturing the location. 

- Added the `Created By` field to Greg's Employee Log page and renamed `Location` to confirm that the created by was capturing. 

- I logged into Kramer - Break Room and when I added a timelog, it captured my location as expected
![image](https://github.com/user-attachments/assets/219879d3-3c24-43fd-b3be-dc29c068d2b5)

- Greg logged into the Townview - Fog Seal account and resaved the bookmark on that tablet. He added timelogs and that also captured the location as expected! 🎉
![image](https://github.com/user-attachments/assets/e709c3b2-80eb-4559-80ce-cd308b623929)

### Next steps
- Greg will be logging into the tablets at Townview, St Elmo, and Dalton by next week
- Christina will be log into the tablets at Kramer next week
- When logging into the tablets, we will: 
   - Delete existing bookmark
   - Log in using Chrome
   - Resave bookmark
   - Test badge in to confirm location is captured

**Comment by ChristinaTremel** [comment]
This was completed in early January.
