### ISSUE TITLE
Work with 311 to update their Check Service Status website

### ISSUE THREAD

**Issue by katelunceford** [cityofaustin/atd-data-tech#19890]
Request 311 to update their Check Service Status website to include all CSRs. 

- [ ] Meeting: Follow up with Carrie
- [ ] Consolidate TPW's requests for 311 from the [public communication discovery project](https://github.com/cityofaustin/atd-data-tech/issues/18136)
- [ ] Coordinate with other DTS groups 
- [ ] Identify short vs. long term requests

## Background 

A recommendation in the [Executive Summary](https://cityofaustin.sharepoint.com/:w:/r/sites/TPWOPM/_layouts/15/doc2.aspx?sourcedoc=%7B1DB32871-8B8A-4AFE-938F-2311AC2EB4DE%7D&file=2024.10_CSR%20Public%20Communication%20Project_Executive%20Summary.docx&wdLOR=c2CCB43BB-4230-6148-B44B-A4AF964C3D88&action=default&mobileredirect=true) for the [311 CSR Public Communication Discovery project](https://github.com/cityofaustin/atd-data-tech/issues/18136) is to update the [Check Service Status website](https://austin-cwiprod.motorolasolutions.com/cwi/search) to include all CSRs: 

> The public should have easy, on-demand access to their CSR updates via 3-1-1’s website. However, the site currently does not include CSRs if an activity has not been posted in the last 30 days or if the CSR type is “Traffic Sign Emergency” or “Parking Machine Issue.” 
> 
> Executive conversations with 3-1-1 may be required to include CSRs with activity updates more than 30 days ago. This may be a limitation of the Motorola technology, or it might be an internal 3-1-1 setting that could be changed.  
> 
> “Traffic Sign Emergency” and “Parking Machine Issue” CSRs are not accessible on the site because they are intentionally not included on the Request Service page (of the same site) so residents cannot self-select emergencies. 3-1-1 is currently investigating if the Motorola technology allows a CSR type to be included on one side (Check Service Status) and not the other (Request Service).

## References
- [311 CSR Public Communication Discovery project](https://github.com/cityofaustin/atd-data-tech/issues/18136)
- [311 CSR Public Communication Project: Executive Summary](https://cityofaustin.sharepoint.com/:w:/r/sites/TPWOPM/_layouts/15/doc2.aspx?sourcedoc=%7B1DB32871-8B8A-4AFE-938F-2311AC2EB4DE%7D&file=2024.10_CSR%20Public%20Communication%20Project_Executive%20Summary.docx&wdLOR=c2CCB43BB-4230-6148-B44B-A4AF964C3D88&action=default&mobileredirect=true)
- Placeholder for drive folder where project materials are stored

## Request details
- Requested by: Jim Dale
- Executive sponsor: 
- Date: 10/30/24
