### ISSUE TITLE
For MMC created issues, need to add additional issue type for "Power Outage (All Bulbs Out)"

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#19953]
> What application are you using?

AMD Data Tracker

> Describe the problem.

For MMC created issues, need to add additional issue type for "Power Outage (All Bulbs Out)"
 
Then we need a field that can report on if an issue is a "Signal On Flash" issue or a "Dark Signal" issue. And this new field needs to be added to the MMC Issues datahub dataset.
 
https://datahub.austintexas.gov/Transportation-and-Mobility/Mobility-Management-Center-Issues/v7vh-gbi6/about_data

We've synced with Christina, Diana, and Charlie on this already and they have the field mapping documented in Miro.

> Describe the outcome you'd like to see when this feature is implemented.

For MMC created issues, need to add additional issue type for "Power Outage (All Bulbs Out)"
 
Then we need a field that can report on if an issue is a "Signal On Flash" issue or a "Dark Signal" issue. And this new field needs to be added to the MMC Issues datahub dataset.

https://datahub.austintexas.gov/Transportation-and-Mobility/Mobility-Management-Center-Issues/v7vh-gbi6/about_data

We've synced with Christina, Diana, and Charlie on this already and they have the field mapping documented in Miro.

> Describe any workarounds you currently have in place or alternative solutions you've considered.

Utilizing various other activities 

> Is there anything else we should know?

BC Request - as soon as we can

> Requested By
Allyson R.

Request ID: DTS24-119345

**Comment by dianamartin** [comment]
# 1/15/25
## MMC Table View 
- Issue - CSR Issue Type
- Issue Reported - Coming from 311 Flex Note (what is the problem with the signal)
![image](https://github.com/user-attachments/assets/21a39fa2-f991-48e2-aa5d-d9f609259576)

## Issue Type Manual
![image](https://github.com/user-attachments/assets/ed395c4e-0aaf-4903-93ef-9c3e97410560)
- [ ] Add option for `Power Outage (All Bulbs Out`

## Creating a new field - `Outage Type`?
This new field needs to be added to the API to go into ODP
- If Source is TMC + Power Outage (All Bulbs Out) = `Dark Signal`
- If Source is 311 + Power Outage (All Bulbs Out) = `Dark Signal`
- If Source is 311 + Single Bulbs Out = `Signal On Flash`

**Comment by dianamartin** [comment]
# 2/10/25
- [x] Add option for `Power Outage (All Bulbs Out` on `ISSUE_TYPE_MANUAL_CREATE` field
- [ ] Added Field `Outage Type` (short text)
  - Conditional Rules
![Image](https://github.com/user-attachments/assets/695eb0bb-e9cf-4146-99b3-18b3344431bd)
-  Updating Outage Types
- [ ] If Source is TMC + Power Outage (All Bulbs Out) = Dark Signal
- [ ] If Source is 311 + Power Outage (All Bulbs Out) = Dark Signal
- [ ] If Source is 311 + Single Bulbs Out = Signal On Flash

**Comment by dianamartin** [comment]
# 2/10/25
## New field "Outage Type" added to the MMC Table
![Image](https://github.com/user-attachments/assets/b54684bf-2dbe-488c-afd0-372212a7a3cb)

## New MMC Issue
- "Power Outage (All Bulbs Out)" Choice added to Issue Type
![Image](https://github.com/user-attachments/assets/c7b8993e-b734-401f-abd2-495558ce263e)

**Comment by dianamartin** [comment]
# 2/10/25
cc @ChristinaTremel 
Synced with Allyson and showed her the results to ensure the enhancement updates were what she expected. She has a call with BC at 2 pm, they will show him and determine if they have an additional enhancement to update the ODP data set.
