### ISSUE TITLE
Discovery Day - February 7th, 2025

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#20000]
This is the epic for Discovery Day. Everyone is encouraged to create an issue under this epic to document their work and to record their findings.

* [x] Schedule opening meeting
* [x] Prepare opening meeting content
* [x] Schedule discovery day proper
* [x] Make lunch plans
* [x] Schedule debrief meeting

**Comment by Charlie-Henry** [comment]
please escalate
