### ISSUE TITLE
I need PM records to duplicate onto the secondary signal records. Previously this was happening with...

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#20025]
> What application are you using?

AMD Data Tracker

> Describe the problem.

I need PM records to duplicate onto the secondary signal records. Previously this was happening with our old PM process but after that process was updated these records aren't showing up on the secondary.

> Describe the outcome you'd like to see when this feature is implemented.

I need PM records to duplicate onto the secondary signal records.

> Describe any workarounds you currently have in place or alternative solutions you've considered.

Manually updating secondary signal in a spreadsheet.

> Requested By
Jorge G.

Request ID: DTS24-119440

**Comment by ChristinaTremel** [comment]
## Notes 12/11 and 12/13
- To migrate the PM copier script (reference #16171), we need to add fields from the API [view](https://builder.knack.com/atd/amd/pages/scene_416/views/view_1182/table) of the historic PM records. 

### Fields to add to `work_orders_preventative_maintenance` object
- [x] SECONDARY_SIGNALS_COUNT
   - Text formula pulling the `SECONDARY_SIGNAS_COUNT` from signals object

- [x] SECONDARY_SIGNAL_COUNT_NUMBER
   - Number field
   - Conditional Rule: 
      ![image](https://github.com/user-attachments/assets/71f390e7-5041-455e-a3c2-f5756a3ce234)

- [x] COPIED_TO_SECONDARY
   - Yes/No field
   - Default: No
   - Drop down

### Create new PM Copier API view with the following fields: 
Created [new view](https://builder.knack.com/atd/amd/pages/scene_416/views/view_4284/table?confirmNewView=view_4284) on existing `Signals PM Copier` API page
- [ ] PM_ID
- [ ] PM_COMPLETED_DATE
- [ ] WORK_ORDER 
   - Field connection to `WORK_ORDER` in the work_order_signals object
- [ ] PM_STATUS 
- [ ] CONTROL -> missing
   - Field connection to `CONTROL` in signal object
- [ ] PRIMARY_SIGNAL -> missing from API view (doesn't exist in the `signals_preventative_maintenance_HISTORICAL` object)
   - Field connection to `PRIMARY SIGNAL` in signal object
- [ ] COPIED_TO_SECONDARY
- [ ] SIGNAL
   - Field connection to `SIGNAL` in the signals object
- [ ] SECONDARY_SIGNAL_COUNT
- [ ] MODIFIED_DATE

**Comment by ChristinaTremel** [comment]
Created the new API view and need to sync with Charlie next week to confirm everything is configured correctly for migrating the PM copier script.

**Comment by ChristinaTremel** [comment]
This has been completed.
