### ISSUE TITLE
Simplify 'Manage Vehicles' tab by removing unnecessary columns and adding latest log date

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#20108]
> What application are you using?

AMD Data Tracker

> Describe the problem.

"Manage Vehicles" Tab
simplify landing page by:
- removing columns:
-- VIN Number
-- Name
-- Category
-- In Service Date

- add column:
-- "latest date in log"
--- currently displays "last in service date" see unit 15A675

 

> Describe the outcome you'd like to see when this feature is implemented.

clearer, simpler dashboard

> Describe any workarounds you currently have in place or alternative solutions you've considered.

none

> Is there anything else we should know?

TBD

> Requested By
Billy B.

[Attachment](https://api.knack.com/v1/applications/595d00ebd315cc4cb98daff4/download/asset/6747211c9e3f4a02f3a0bfc2/screenshot2024112715a675.png) (6.45kb)

Request ID: DTS24-119600

**Comment by dianamartin** [comment]
## Remove fields on "Manage Vehicles" table view
![image](https://github.com/user-attachments/assets/3c501026-a2c3-44e2-ba0d-3b0b876d06d3)
Removing columns:
- [ ] VIN Number
- [ ] Model
- [ ] Name
- [ ] Category
- [ ] In Service Date

**Comment by ChristinaTremel** [comment]
Create field: 
- Latest Log Notes: Add `Notes` from the vehicle log object to the vehicle tracking table
- Latest Log Date: Date from vehicle log object (Latest Date of Action)

**Comment by susannegov** [comment]
# 12/12
- [ ] Removed columns  VIN Number, Name, Category, In Service Date from table view
- [ ] Created fields `Latest Log Notes` and `Latest Log Date`
- [ ] Added field to table grid and vehicle details page
- [ ] Added record rule to update the connected record `fleet vehicle` object for the two fields in:
   - Add Vehicle Log
   - Add Vehicle Note
- Tested it on retired vehicle.

**Comment by ChristinaTremel** [comment]
@susannegov if you think it's easy enough to update the previous records, that would be helpful to Billy!

**Comment by susannegov** [comment]
Updates 79 records of last log date of action and vehicle notes

**Comment by susannegov** [comment]
Demo'd log functionality with Billy at 0114. works as expected
