### ISSUE TITLE
Write project status updates for DTS 12/10 Newsletter

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#20115]
We are shooting to send out an issue of the DTS Newsletter on 12/10. Product Managers should write short status updates, following [these guidelines](https://docs.google.com/document/d/1Kb2dCDWhzupuCo2YZFTTHArWPN207DicxXUK6jTF0eM/edit?tab=t.0#heading=h.vogj4gt6ap0z), for all [in-progress projects](https://atd.knack.com/dts#current-projects/?view_416_filters=%5B%7B%22field%22%3A%22field_649%22%2C%22operator%22%3A%22is%22%2C%22value%22%3A%22In%20Progress%22%7D%5D&view_416_sort=field_676|asc). 

**Due 12/5/24**. 

## To-do
- [x] [Knack and 311 Standardization](https://github.com/cityofaustin/atd-data-tech/issues/15852) - @ChristinaTremel
- [x] [AMD Inspector Work Orders](https://github.com/cityofaustin/atd-data-tech/issues/15962) - @ChristinaTremel
- [x] [Standardize Maximo SBO Start Centers](https://github.com/cityofaustin/atd-data-tech/issues/17913) - @ChristinaTremel
- [x] [SBO Attendance Tracker](https://github.com/cityofaustin/atd-data-tech/issues/18454) - @ChristinaTremel
- [x] [Urban Forestry contractor work order management](https://github.com/cityofaustin/atd-data-tech/issues/18918) - @ChristinaTremel
- [x] [Austin Water Emergency Permit Automation](https://github.com/cityofaustin/atd-data-tech/issues/16607) - @pgentyandrade 
- [x] [Maximo Work Order System Discovery](https://github.com/cityofaustin/atd-data-tech/issues/15174) @ChristinaTremel
- [x] [AMD Project Intake Work Orders](https://github.com/cityofaustin/atd-data-tech/issues/12555) - @ChristinaTremel
- [x] [Traffic Register 2.0](https://github.com/cityofaustin/atd-data-tech/issues/130) - @ChristinaTremel
- [x] [311 CSR Public Communication Discovery](https://github.com/cityofaustin/atd-data-tech/issues/18136) - @katelunceford
- [x] [Coordinate Software Implementation](https://github.com/cityofaustin/atd-data-tech/issues/14585) - @TracyLinder
- [x] [Enterprise Case Management Software Procurement](https://github.com/cityofaustin/atd-data-tech/issues/10420) - @TracyLinder
- [x] [Right-of-Way CRM Procurement](https://github.com/cityofaustin/atd-data-tech/issues/15823) - @TracyLinder
- [x] [Mobility Services Portal](https://github.com/cityofaustin/atd-data-tech/issues/16232) - @patrickm02L
- [x] [Dash v1.0](https://github.com/cityofaustin/atd-data-tech/issues/11078) - @katelunceford
- [x] [FY25 AMANDA Fee Updates](https://github.com/cityofaustin/atd-data-tech/issues/18303) - @TracyLinder
- [x] [Mobility Project Impact Analysis](https://github.com/cityofaustin/atd-data-tech/issues/15552) - @johnclary
- [x] [TCP Case Management Upgrade](https://github.com/cityofaustin/atd-data-tech/issues/9819) - @TracyLinder
- [x] [Inspector Prioritization Automation](https://github.com/cityofaustin/atd-data-tech/issues/423) - @TracyLinder
- [x] [Project: Digitize Interview Management Process](https://github.com/cityofaustin/atd-data-tech/issues/15955) - @stephaniemoorer 
- [x] [Project: Request For Council Action (RCA) Approval System](https://github.com/cityofaustin/atd-data-tech/issues/19689) @stephaniemoorer

**Comment by amenity** [comment]
@stephaniemoorer @mddilley @andrewshensky -- If you have any current work you'd like to consider a project, I'm happy to help make a quick, clean project index.

**Comment by stephaniemoorer** [comment]
@amenity  I have 2 projects I'm working on
19689 - RCA Approval Process / Office of Director
15955 - Digital Interview Process / HR

**Comment by TracyLinder** [comment]
I think I'm done. 🫰🏼

**Comment by amenity** [comment]
@johnclary - ping. 🔔

**Comment by johnclary** [comment]
@amenity no dashboard yet, but definitely will share that once it's ready. Here's my update https://github.com/cityofaustin/atd-data-tech/issues/15552#issuecomment-2532001992 🙏

**Comment by amenity** [comment]
@ReneVarg25 @ChristinaTremel - ping. 🔔 I'd like to get the Maximo Start Centers in since we put the Maximo report in the last newsletter and it's nice to see an action item from that already in progress. 

In addition to an update, please modify the [project description ](https://github.com/cityofaustin/atd-data-tech/issues/17913) so it's easier for someone outside SBO/Maximo to understand. I.e. someone who doesn't know what a "Start Center" or "portlet" is.

**Comment by ChristinaTremel** [comment]
@amenity @katelunceford Rene and I made the updates to the Maximo Start Center project and added that to the DTS Newsletter doc as well! Rebekka is definitely involved, but is OOO this week. 🙂 We also updated the project description to hopefully make it easier for someone outside of SBO/Maximo to understand!

**Comment by katelunceford** [comment]
All updates were posted and the [newsletter](https://mailchi.mp/austintexas/tpw-data-technology-services-news?e=078d82abc0) was sent.
