### ISSUE TITLE
Documentation: SBO Attendance Knack application - Gitbook for end users to troubleshoot common problems

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#20112]
> What application are you using?

Human Resources Portal

> Describe the problem.

Following up from a discussion with Diana M.:

The SBO Attendance Knack application would benefit greatly from having a Gitbook for end users to troubleshoot common problems. We would also like a QR code that links to the Gitbook so users can scan the code when they encounter issues. 

> Describe the outcome you'd like to see when this feature is implemented.

SBO will have a QR code near every attendance iPad that links to a troubleshooting Gitbook so that users can fix any issues they encounter. This will provide more accurate and efficient attendance tracking.

> Describe any workarounds you currently have in place or alternative solutions you've considered.

Currently, when users encounter an issue, I have to come in person to fix it or describe over the phone how to solve the issue. 

Some Examples:
How to clear the Chrome search cache
How to turn off and on an iPad
How to close an iOS application

> Is there anything else we should know?

No timeline in mind. January perhaps. 

> Requested By
Greg G.

Request ID: DTS24-119620

**Comment by dianamartin** [comment]
# 11/27/24
On the SBO Portal GitBook
- [x] Created new group section "SBO ATTENDANCE HARDWARE"
- [ ] Created pages for:
  - [ ] How to clear browser cache
  - [ ] How to turn iPad device on/off
  - [ ] How to close iOS application
