### ISSUE TITLE
Split Braker into an East and West corridor in Data Tracker

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#2018]
> Describe the problem.

If you look at Braker's corridor timing details in data tracker (https://data.mobility.austin.gov/data-tracker/#sync-corridors/corridor-details/582e29b1bac74ffc2aedaa66/), the corridor splits between NW area and NE area. The NW section of Braker is retimed for FY2020, and the NE section retiming is about to be completed. Is it possible to split Braker into 2 corridors as Braker West and Braker East or something similar to it? I have the data for NW Braker saved so don't worry about deleting the FY2020 retiming if you have to. 

> How soon do you need this?

Flexible  — An extended timeline is OK

> Is there anything else we should know?

I would prefer to have it done in a couple of months, but I'm flexible if you are busy as I can pull the retiming data and upload it anytime. 

[Attachment](https://api.knack.com/v1/applications/595d00ebd315cc4cb98daff4/download/asset/5e5fe7d29006cc0015cd2371/brakerdetails.png) (77.16kb)

---
Request ID: DTS20-100500
Requested by: Jenny L., AMD

**Comment by amenity** [comment]
@dianamartin @johnclary - I'm interested to learn how it might affect bond corridor performance analysis to divide a corridor into two in Data Tracker.

**Comment by dianamartin** [comment]
@amenity we've split corridors before, I'm not sure how the analysis is affected. I think they change fiscal year to fiscal year.

**Comment by amenity** [comment]
Okay, thanks. Seems like this is a reasonable request, then. Would you please size, @dianamartin? And should we have Jared W. (Data Tracker Product Owner) give it his blessing?

**Comment by dianamartin** [comment]
Giving Jared a heads up and get his approval seems fine to me

**Comment by dianamartin** [comment]
@amenity I don't have an estimate button for some reason

**Comment by amenity** [comment]
@dianamartin - no need to do this during this sprint unless you're short on tasks. She said within a couple months would be great.😆

**Comment by dianamartin** [comment]
Jenny came by and and asked to split a few more corridors:
- [ ] `US 183 S` :remove all of Northeast
- [x] US 183 - East: add all of Northwest

- `Pleasant Valley`
- [ ] Pleasant Valley - North - Central engineer area
- [ ] Pleasant Valley - South - Southwest engineer area
delete

**Comment by dianamartin** [comment]
Emailed user
>I’ve update the US 183 corridor and the Pleasant Valley corridor. I ended up removing the ear marking timing record under the old Pleasant Valley corridor since there was no data there.

**Comment by dianamartin** [comment]
I will change it to ‘inactive’. My note said that Jenny was going to add the signals from the front end since I showed her how to do that.

**Comment by dianamartin** [comment]
I retired `Braker` and `Pleasant Valley` per your request
