### ISSUE TITLE
Complete project intake & scoping

### ISSUE THREAD

**Issue by katelunceford** [cityofaustin/atd-data-tech#20282]
- [x] Schedule in January - 1/23/25
- [x] Reschedule in June - 6/26/25
- [x] Prepare [project intake & scoping doc](https://docs.google.com/document/d/1YxBg7MCLRSz4jr8LmLZ_BLiaxKHRjtlPOebifUhgOVo/edit?tab=t.0#heading=h.yhzk4wlhvntm)
- [x] Host meeting & take notes
- [x] Complete project intake & scoping doc during [OPM Sprint Review](https://docs.google.com/document/d/1ZnyRrIshduq80l6eiC05xLMGFWLJOfhA0QOUWFvw6HE/edit?usp=sharing) on 7/7/25

Attendees
- DTS - Kate, Diana, Charlie; Optional: Christina, Susanne
- OPM - Jewelee, Adriana, Rachel
