### ISSUE TITLE
Enhancements from 12/3 review - restructure project name, fix form rules, simplify table

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#20309]
AMD PM team rolled out the project intake portal to all requesters and the AMD Division mid November. We have scheduled reoccurring bi-weekly meetings to discuss modifications requested during the initial roll out as they are receiving feedback from AMD staff. 

### Enhancement requests from 12/3 meeting
- On `Edit Work Request form` on the PMT Review page, need to add the OTHER field when asset type other is not selected.
   ![image](https://github.com/user-attachments/assets/dddd380e-77c4-48e5-a3ac-d4a83a2bba65)
- In PMT review I think we **do not** want to point to "Parent Moped Project ID" -- need to point to primary name of AMD Moped
    - Needs to include the secondary name on Moped (called full name on Moped)
    - Find out if we can add the `Full Name` to the data we push from Moped → Data Tracker
- `Schematic Ready` doesn’t need to be in the approval now that we allow to include attachment in the approval pop-up
   ![image](https://github.com/user-attachments/assets/3793a3f8-895f-4be4-8142-d757769a03b7)
    
- Delete PMT activity #183 (TK for Radam) - Ivonne successfully "split" project #94 in #94 and #140
- Limit character limit for `Link` field in the Attachments table
   ![image](https://github.com/user-attachments/assets/b93b5b20-632e-492f-a382-fbc234fd6caa)  
- Close button is not changing the status of the projects and they remain open.
   ![image](https://github.com/user-attachments/assets/faf2cd2e-76fe-4590-8b9c-04d05b137959)
- Create field for overall project type. Combine Project Types New and Project Types Existing to the same field and add that field to the Project Request table for “Open”
- Create field for overall other project type. Add Other fields to the same field (for new and existing) and add that field to the Project Request table
- Type of Project Name
    - Restructure for “Asset”, “Moped Project”, “Project Location”, and “AMD Project Name”
    - Add additional option for “Asset” that include these assets
        - Signal/PHB
        - School Beacon
        - Flashing Beacon
        - For the “Asset” option, want to add a secondary name to the end of the asset name
            - Example: 757: SLAUGHTER LN / BARSTOW AVE Signal Mod
    - If Project Location is flagged, this will need to be an asset eventually so we might want a field to flag that
    - Add “On Hold Reason” to the on hold button

**Comment by ChristinaTremel** [comment]
- [x] On `Add New Location` and `Add Existing Location` on the PMT Review page, need to add the OTHER field when asset type other is not selected.
   - Updated display rules to include showing/hiding `OTHER - Asset Type` 
   - Renamed the buttons to match the `New Project Request` form
      - Add New Location -> Work Request for New Asset
      - Add Existing Location -> Work Request for Existing Asset

- [x] In PMT review I think we **do not** want to point to "Parent Moped Project ID" -- need to point to primary name of AMD Moped
    - Needs to include the secondary name on Moped (called full name on Moped)
       - Updated rule for Project Name to use the AMD Moped Project ID if AMD selects to use the Moped name
          ![image](https://github.com/user-attachments/assets/b4ff14e7-60a1-44c8-81af-51b5c03f75d7)
    - Find out if we can add the `Full Name` to the data we push from Moped → Data Tracker

- [x] `Schematic Ready` doesn’t need to be in the approval now that we allow to include attachment in the approval pop-up
   - Deleted `Schematic Ready` field 
    
- [x] Delete PMT activity #183 (TK for Radam) - Ivonne successfully "split" project #94 in #94 and #140
   - Deleted TK 24ENG01177 associated to Project 94 (was created with activity 183)
   - Deleted Activity 183 (Ivonne created new activity on new project

- [ ] Limit character limit for `Link` field in the Attachments table

- [x] Close button is not changing the status of the projects and they remain open.
   - Fixed rules associated to closing project and tested the functionality with Erin and Ivonne

- [ ] Create field for overall project type. Combine Project Types New and Project Types Existing to the same field and add that field to the Project Request table for “Open”

- [ ] Create field for overall other project type. Add Other fields to the same field (for new and existing) and add that field to the Project Request table

- [ ] Type of Project Name
    - Restructure for “Asset”, “Moped Project”, “Project Location”, and “AMD Project Name”
    - Add additional option for “Asset” that include these assets
        - Signal/PHB
        - School Beacon
        - Flashing Beacon
        - For the “Asset” option, want to add a secondary name to the end of the asset name
            - Example: 757: SLAUGHTER LN / BARSTOW AVE Signal Mod
    - If Project Location is flagged, this will need to be an asset eventually so we might want a field to flag that
    - Add “On Hold Reason” to the on hold button

**Comment by ChristinaTremel** [comment]
Reviewed these updates with Ivonne and Erin on 12/19 and everything looked good!
