### ISSUE TITLE
[TCP Case Management Upgrade] Builder Updates from UAT 

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#20379]
## Tasks from UAT Sessions 
* **Remove Prelim Org Creator fields from Verify Account form** (was causing confusion at this stage) ✅ 
* The field “Which TCP will be used” is displayed on the project details page, but this field wasn’t collected on the project creation workflow. Should this be shown or added to the creation project form(s)? ✅- **this should only show for Shared**; this is now fixed to be hidden for Conflict
* The customer noted several times that the **red asterisks at the end of fields are wrapping to the next line**. - ✅ Abbreviated some of the lines and moved some help text into the instructions blurb instead
* Submission Cycle confirmation email is not counting submission cycle correctly --> We were unable to replicate/see this issue - counting submissions and attachments correctly - **Hiding Submission ID number from the emails to avoid confusion** ✅
*** Remove the word "approved" from the customer emails.** 
     * "Approved" not the preferred language - opt for review complete, etc. language instead from reviewed
     * Updated language to “Once completed…” ✅
* **Submitting Party Phone # not required** -Unrequired both in CSWZ and Submitter phone in TCP ✅
* **Add Request Status to the end of the request name on Request Details (modeled after TCP)** ✅
* **Customer Contact and Contact Name redundancy** on Request / Project Details - Removed one ✅
* Bug: **CSWZ attachments aren't showing on the cycle** - Cycle 1 - submitted - attachments not showing up on the cycle - We corrected the missing CSWZ Request connection on both the Applicant and Reviewer portals ✅
* **Add ability to include attachment commen**t when the Reviewer is adding an attachment or editing one ✅ 
- [x] **Include Message content in the outgoing New Message notification emails** 
- [x] **Add review comment to TCP Complete Review form**
     - [x] Include this comment in the outgoing decision email to Applicant 
- [x] **Confirm/configure behavior when a Submission is archived** - sorted out, will get rid of the conditionals that currently set the status when we go live with the CMU

## Tasks from ROW Review of UAT Notes 
* **Add Other as a multichoice option for the Attachment Owner field on the CSWZ Submission Content/Attachment**
- [x] Added separate MC selection for Reviewer ✅
- [x] Applicant 
     - [x] Current Application Form 
          - [x] Add Attachments ✅
          - [x] Edit Attachments ✅
     - [x] Portal - Filter Attachments table 
          - [x] Edit Attachments tables ✅
          - [x] View Attachments tables ✅
- [x] Reviewer 
     - [x] Current Add Attachments ✅
     - [x] New Portal Add Attachments ✅
- [x] Applicant value changed to Submitting Party in Attachment Owner field ✅

* **Don’t allow Archiving if the cycle determination is Complete or Returned** ✅
     * [x] Chrispin added view and functionality for Submission management 
     * [x] Added Archived tab (restore button function) 
     * [x] On the Active tab - Archive button 

* **Remove AMANDA Bill #** ✅ 

* **Pass AB+C Credentials from Org to Project** 
     - [x] Pull from Org account when available (optional so may not be populated ✅ 
     - limitation: if not filled in at Account Creation or later edit Org Details, this value will not be available to pre-fill
     - Function Note - On Edit Org Details form, when the Customer updates the AB+C credentials, they will update across the board on any connected projects
     - Added clarifying language to the Edit Org Details as well as Account Creation AB+C fields

**Comment by ChrispinP** [comment]
Review Comment field added to TCP:
![image](https://github.com/user-attachments/assets/8d812309-b714-4954-a812-0ebdc4b0df71)

Emails updated to include Review Comment:
![image](https://github.com/user-attachments/assets/92de191b-24ff-475c-85a0-9141b005c6b0)
