### ISSUE TITLE
Project: Winter Weather Emergency Response Maps

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#20385]
We're designing a set of paper maps for Street and Bridge Operations field staff to use while performing winter weather emergency response activities. 

## Background 
Since Winter Storm Uri hit Austin in 2021, followed by Winter Storm Mara in 2023, the City of Austin has been working to improve its readiness to respond to extreme cold, snow, and ice. Transportation Public Works ensures that Austin's road network can be used in severe weather conditions to maintain core services, with Street and Bridge Operations field staff executing much of that on-the-ground work by clearing snow, debris, and ice from roads. SBO crews also perform preventative treatments that lower the surface freezing temperature to prevent ice formation.

SBO has divided Austin's most critical roads and bridges into districts. Crews dispatched from service centers across town are each assigned a group and need a map of the infrastructure they're responsible for to refer to as they work. These maps must have enough detail to serve as staff's only reference in case of a communication blackout where mobile devices and radios aren't functioning. 

Along with the map, field staff will need a paper work log for each route: work log provides a place for crews to record information as they complete tasks on their route, and provides us with a backup source of information in case there's a problem on radio transmission of progress information and findings.

## Scope & Deliverables
- 14 maps to be delivered as PDFs that staff can print in service centers:
  - 8.5" x 11"
  - Double-sided
  - Full color

- 14 printable work logs - ideally, we can fit these on the back of the maps. This will depend on how many inset maps each route requires. We have the go-ahead to deliver these as a second sheet of paper if necessary.  

## Timeframe
- **12/18/24** - Planning work session 
- **12/20/24** - Internal review of draft map designs; determine specifications for map templates
- **12/23/24** - Template work session to finalize templates
- **12/30/24** - Stakeholder review and feedback on the first set of maps 
- **1/8/25** - Bridge map delivery
- **1/10/25** - Road map delivery

## Resources
- [Zenhub Board](https://github.com/cityofaustin/atd-data-tech/issues#workspaces/data--technology-services-5caf7dc6ecad11531cc418ef/board?epics=Z2lkOi8vcmFwdG9yL0VwaWMvMTE3MTgzMA&repos=140626918)
- [TPW GIS Emergency Management Teams Channel](https://teams.microsoft.com/l/channel/19%3A9e0f57232fd34b8cb2911e9f1c24cdd0%40thread.tacv2/Emergency%20Management?groupId=1ba40f1f-732f-4279-bd41-2eb65303615f&tenantId=5c5e19f6-a6ab-4b45-b1d0-be4608a9a67f)
- [Google Drive folder](https://drive.google.com/drive/folders/1EUzhUHlqze-AxpNkMP99xDCESc82-Xyl) - docs & artifacts to share with stakeholders during meetings or archive for future reference
- DTS GIS G Drive folder: `20241216_EM_bridge_and_road_treatment_maps` - GIS files
- [Meeting notes](https://docs.google.com/document/d/1FnbQyysYq4JtrboOjuxfn8znASnOwatWuATVdJ9_Ww8/edit?tab=t.0)
- [TPW GIS Sharepoint Folder](https://cityofaustin.sharepoint.com/:f:/r/sites/tpwDTS/Shared%20Documents/DTS_GIS/2025-01%20--%20Winter%20Weather%20Emergency%20Response%20Maps?csf=1&web=1&e=0emUxd)
- [SBO's Work Logs](https://cityofaustin.sharepoint.com/sites/TPWSBO/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FTPWSBO%2FShared%20Documents%2FSBO%20Emergency%20Management%2F03%5FOperations%2F%2EWinter%20Weather%20Response%20Routes%20%2D%20Current%20Versions) 

## Stakeholders 
Street and Bridge Operations
- Reiner H - Division Manager
- Dave A. - SBO Consultant Lead
- Baldomero (Junior) R. - District DM 
- Shon J., Eli M., Jorge L. - District Superintendents

Emergency Management
Kimmi M. - Program Manager
Arabella W. - EM Emergency Plans Officer

## Request details
- Requested by: Dave A. 
- Executive sponsor: Reiner H.

![Looking north on Congress Avenue, with Texas State Capitol in the background. It is snowing, and the foreground, cars and pedestrians drive and walk on salted streets with snow on the sides.](https://github.com/user-attachments/assets/81e6bb8e-f546-499b-a6e2-ed0dab100540)

---
This Github issue represents a project of Transportation Public Work's [Data & Technology Services](https://austinmobility.io/) team. Project status is documented regularly in the comments below.

**Comment by amenity** [comment]
@GimnichD - please fix my broken link to the G Drive folder in the issue body above. 🙏🏻 🔗

**Comment by amenity** [comment]
Kickoff meeting on 12/18: 
![2024-12-18 | SBO ER Maps Work Session](https://github.com/user-attachments/assets/f5687cd5-5e25-4c98-86ed-b2943079922e)
![3C45BC7E-88F5-4894-9993-AFE6B5280D2E_1_105_c](https://github.com/user-attachments/assets/3561fb55-16b2-46f7-b347-865a99faf1a8)

**Comment by amenity** [comment]
# 2024-12-30 | Sprint Review

*SBO: Dave, Junior, Shon, Reiner 	EM: Arabella, Kimmi* 	  
*DTS: David, Amenity* 

## **Map Review**

[Roads](https://drive.google.com/file/d/1DpHW1uxeDRXXl9PTjFy34SEW2P3vSQq2/view?usp=drive_link)| [Bridges](https://drive.google.com/file/d/1JkTn5OuY4Iidw5mUhbBB5RnKaZFFzH22/view?usp=drive_link)

**Notes**

- Bridges  
- Creeks labeled  
- Road  
- Subset of roads are labeled \- major roads and roads in work log  
- All other routes’ critical roads are symbolized as yellow

**Feedback**

- Bridges  
  - Junior \- like the general map, then broken to A B C insets  
  - Shon \- is there a reason to label TxDOT bridges?   
    - Historically have treated them    
  - Prepend bridge names with the letter of the route, e.g. D3  
  - Roman numerals for inset maps?  
- Roads  
  - Add an arrow to show where route roads are 1-way

**Questions**

- Should the map show the ID?   
  - Discussion of ordinality; will pick up looking at tables

## **Work logs**

Examples: [PDF](https://drive.google.com/file/d/1oPKeRL8TtlXTd9zl1r_q4osQoddjx7ao/view?usp=sharing) | [Print comparison](https://drive.google.com/file/d/1k9g2W-43agmohlxkJduLupRnr-sA5Llu/view?usp=sharing)

**Feedback**

- Add “Status Post Treatment”  
- Bridge “Locations”  
  - What’s there, e.g. “0.14 MI S OF CESAR CHAVEZ,”  isn’t useful \- was confusing during run-throughs  
  - Dave: Bit.ly wouldn’t be usable in Apple Maps  
  - Reiner: Keep it simple for this year, no Bit.ly  
  - Junior: Why not address? Use for CSRs all the time  
  - Shon: The most useful thing will be practicing route; does not see crew typing lat/long or URL in phone; most useful would be photos of each bridge  
  - Consensus: Since we have the space, use Long/Lat \- hopefully won’t need but lo-fi and flexible   
- Add TxDOT yes/no to table  
- Add latitude/longitude to the table   
- Indicate that “Status” is post-treatment  
- Dave’s take on data reporting and spreadsheets  
  - “Frontend” \= DTS-designed spreadsheets, maximize legibility and simplicity for ease of use by field staff entering data with pen and paper  
  - “Backend” is the single master spreadsheet where all data is input by backend staff via radio as each bridge/road is completed; checked or from the paper after handoff  
  - “In-stride reporting” aka all data communicated over radio in real-time

**Questions**

- Location option \- leaving lat/long  
  - **Latitude/Longitude ← Going with this**  
    	30.3025, \-97.6530  
  - Bit.ly \- e.g. ([setup](https://app.bitly.com/Bi7ukdiDkgx/links/bit.ly/bridge34/details))	  
    	[bit.ly/bridge34](https://bit.ly/bridge34)  
  - QR code for table in Sharepoint with hyperlinks

## **Project logistics**

- Final deliverables format: Sharepoint folder with   
  - 14 x 2-page PDFs of each map w/ its work log  
  - 3 x Excel files with each district’s tables

## **Project schedule**

- 12/18		Planning work session   
- 12/20		Internal review of draft map designs  
  		Determine specifications for map templates  
- 12/26		Internal review of templates and example maps  
  		Map template finalization  
- ~~12/27~~ 12/30	Stakeholder review and feedback on the first set of maps   
- ~~1/8~~ 1/10	Map delivery

## **Action Items**

David 
- [ ] Coordinate with Dave to get Amenity final spreadsheets with **lat/long** and **length** and **TxDOT** (yes/no)  
- [ ] Add arrows to maps to show one-way streets \- add to Owen’s per-map task list  
- [x] ~~Post maps w/ Roman numerals to meeting chat~~

Amenity
- [x] ~~Ask about labeling “D14” instead of just “14” on the map~~   
Changes to tables:   
- Add “Status Post-Treatment”  
- Change Location values to latitude longitude  
- Label TxDOT roads

**Comment by amenity** [comment]
**After Action Review 1/16/25**
_Run by Dave A. at Townview
DTS attendees: Peggy, Diana, David, and Amenity_

Notes relevant to this project: 
[get GIS request in first mentimeter]
- Amenity requested more info 
- Nearest address wasn't perfect for bridges since they don't have addresses
  - Junior still thinks it's the best info for the work log locations, used for CSRS; also emphasizes the importance of training
  - When directing field staff remotely, sending them a photo of a Google Map worked quickly
       - Amenity suggested they have a second paper printout (or third page in the map/work log PDF) w/ street view of each bridge
       -

**Comment by amenity** [comment]
This work was delivered on time and at an amazing level of quality. These maps will be hugely helpful to TPW's emergency response operations this winter, and we received a ton of gratitude and positive feedback from SBO. 

Fantastic work, @OwenAMyers @grantstatton @GravesW1 @GimnichD!! 🎉
 
[1/17/25 Team Retro Miro Board](https://miro.com/app/board/uXjVLsTychE=/?share_link_id=502715110206)


<img width="539" alt="Image" src="https://github.com/user-attachments/assets/a8f5f1bf-986d-4863-94d7-8e77fc3f80f8" />
