### ISSUE TITLE
Create ❄️ ER map: Roads Route B

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#20402]
**Tasks**
- [x] Map author move this issue to the _In Progress_ pipeline when you begin working on it. 
- [x] Map author completes map, save as both Layout and Map files, and provide the G drive path (in `20241216_EM_bridge_and_road_treatment_maps`) as a comment below
- [x] Add @OwenAMyers as an assignee to this issue
- [x] @OwenAMyers add labels to the map and upload the proposed final map PDF as a comment below
- [x] @OwenAMyers move this issue to the _Review/QA_ Zenhub pipeline
- [x] @OwenAMyers add @GravesW1  and @GimnichD as assignees to this issue and notify them and the map author that the map is ready for final review in a comment below

**Review**
   - If **_must-have_** or **_quick-to-implement_** corrections/changes are required, move the issue back to the _In Progress_ Zenhub pipeline with a task list of changes as a comment below, and notify the map author.
   - If **_nice to have_** or **_time-consuming_** corrections/changes are required, consolidate as a task list in a comment below, and notify @amenity, who will create a backlog issue for a v2 version of the map. 
- [x] Map author review proposed final map; add comments below as needed
- [x] @GravesW1 review proposed final map; add comments below as needed
- [x] @GimnichD review proposed final map; add comments below as needed and assign to @amenity. 

**Delivery**
- [x] @amenity create a PDF that includes the work log table on the second page
- [x] @amenity upload the PDF of the final map to Sharepoint 
- [x] @amenity add an image of the final map and link to the file in Sharepoint as a Github comment and close the issue

**Comment by GravesW1** [comment]
Layout:
G:\ATD\ATD_GIS\DTS_GIS_Projects\2024\20241216_EM_bridge_and_road_treatment_maps\01_Working_Data\Layouts_and_Maps_Files\EM_Critical_Roads_Map_Templates

Map file:
G:\ATD\ATD_GIS\DTS_GIS_Projects\2024\20241216_EM_bridge_and_road_treatment_maps\03_Pro_Projects\Graves\route_B

**Comment by OwenAMyers** [comment]
@amenity @GravesW1 @GimnichD 
Here is the draft of the Critical Roads Route B map, ready for your review.

[20250109_EM_CriticalRoads_RouteB_Map.pdf](https://github.com/user-attachments/files/18366858/20250109_EM_CriticalRoads_RouteB_Map.pdf)

**Comment by GravesW1** [comment]
Not a necessary edit:

the Spicewood Ln call out seems to be cut off.

**Comment by GimnichD** [comment]
@OwenAMyers This is great. No edits. @amenity this is ready for PDF merger

**Comment by OwenAMyers** [comment]
> @OwenAMyers This is great. No edits. @amenity this is ready for PDF merger

@GimnichD @amenity 
If this hasn't been merged yet, let me get a new version. The Spicewood ln callout did not fully load and is missing a top half (just a rendering issue) it will be very quick to fix.

**Comment by OwenAMyers** [comment]
[20250109_EM_CriticalRoads_RouteB_Map.pdf](https://github.com/user-attachments/files/18368054/20250109_EM_CriticalRoads_RouteB_Map.pdf)
@amenity

**Comment by amenity** [comment]
To deliver 1/9/25: [WW ER Print - Road Route B - 2025-01-09 2.pdf](https://github.com/user-attachments/files/18369680/WW.ER.Print.-.Road.Route.B.-.2025-01-09.2.pdf) | [Sharepoint](https://cityofaustin.sharepoint.com/:b:/r/sites/tpwDTS/Shared%20Documents/DTS_GIS/2025-01%20--%20Winter%20Weather%20Emergency%20Response%20Maps/WW%20ER%20Print%20-%20Road%20Route%20B%20-%202025-01-09%202.pdf?csf=1&web=1&e=4MkGi0)

![WW ER Print - Road Route B - 2025-01-09 2](https://github.com/user-attachments/assets/c10fb877-a5ce-4ffe-a68e-8e30883cb572)

**Comment by OwenAMyers** [comment]
Here is map B with correct symbology for the Secondary Criticality and Other Critical Routes:
[20250110_EM_CriticalRoads_RouteB.pdf](https://github.com/user-attachments/files/18379611/20250110_EM_CriticalRoads_RouteB.pdf)

**Comment by GimnichD** [comment]
@amenity @OwenAMyers I have given this map a final look and it is ready for deployment

**Comment by amenity** [comment]
Sharepoint: [2025-01 -- Winter Weather Emergency Response Maps](https://cityofaustin.sharepoint.com/sites/tpwDTS/Shared%20Documents/Forms/AllItems.aspx?csf=1&web=1&e=15Ph79&CID=891a78a1%2Dc009%2D7000%2D7e32%2Dd86156587790&FolderCTID=0x0120001B9845F0F9BFA94DBB7EA7D76E548F20&id=%2Fsites%2FtpwDTS%2FShared%20Documents%2FDTS%5FGIS%2F2025%2D01%20%2D%2D%20Winter%20Weather%20Emergency%20Response%20Maps)

[WW ER Print - Road Route B - 2025-01-10.pdf](https://github.com/user-attachments/files/18447844/WW.ER.Print.-.Road.Route.B.-.2025-01-10.pdf)
