### ISSUE TITLE
Create ❄️ ER map: Roads Route A

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#20400]
**Tasks**
- [x] Map author move this issue to the _In Progress_ pipeline when you begin working on it. 
- [x] Map author completes map, save as both Layout and Map files, and provide the G drive path (in `20241216_EM_bridge_and_road_treatment_maps`) as a comment below
- [x] Add @OwenAMyers as an assignee to this issue
- [x] @OwenAMyers add labels to the map and upload the proposed final map PDF as a comment below
- [x] @OwenAMyers move this issue to the _Review/QA_ Zenhub pipeline
- [x] @OwenAMyers add @GravesW1  and @GimnichD as assignees to this issue and notify them and the map author that the map is ready for final review in a comment below

**Review**
- [x] Map author review proposed final map; add comments below as needed
- [x] @GravesW1 review proposed final map; add comments below as needed
- [x] @GimnichD review proposed final map; add comments below as needed and assign to @amenity. 
   - If **_very minor_** or **_must-have_** corrections/changes are required, move the issue back to the _In Progress_ Zenhub pipeline with a task list of changes as a comment below, and notify the map author.
   - If **_major_** or **_nice to have_** corrections/changes are required, consolidate as a task list in a comment below, and notify @amenity, who will create a backlog issue for a v2 version of the map. 

**Delivery**
- [ ] @amenity create a PDF that includes the work log table on the second page
- [ ] @amenity upload the PDF of the final map to Sharepoint 
- [ ] @amenity add an image of the final map and link to the file in Sharepoint as a Github comment and close the issue

**Comment by OwenAMyers** [comment]
Here is the Critical Roads Route A map, labeled and ready for review. @amenity @GimnichD 

[20250108_EM_CriticalRoads_RouteA_Map.pdf](https://github.com/user-attachments/files/18354264/20250108_EM_CriticalRoads_RouteA_Map.pdf)

**Comment by OwenAMyers** [comment]
I made some personal revisions I felt were necessary for this map, so choose between what version you feel is best. This version has a label for Texas HWY 45, and some call outs for end points (Pearson Ranch, FM 620, Lyndhurst).

[20250109_EM_CriticalRoads_RouteA_Map.pdf](https://github.com/user-attachments/files/18365031/20250109_EM_CriticalRoads_RouteA_Map.pdf)

**Comment by GimnichD** [comment]
@OwenAMyers in Inset b, please label E St John Ave, the northern stopping point of Berkman

**Comment by OwenAMyers** [comment]
@GimnichD The data must be off because that line doesn't end at St Johns, it ends somewhat arbitrarily about 50 ft short of Reagan Hill. You want me to fix it and redo the inset?

**Comment by GimnichD** [comment]
@OwenAMyers let's not mess with it, it's good enough. We can address this later.

**Comment by GimnichD** [comment]
@OwenAMyers this is great, no additional notes at this time. @amenity ready for PDF merge

**Comment by amenity** [comment]
To deliver 1/10/25: [WW ER Print - Road Route A - 2025-01-09.pdf](https://github.com/user-attachments/files/18369612/WW.ER.Print.-.Road.Route.A.-.2025-01-09.pdf) | [Sharepoint](https://cityofaustin.sharepoint.com/:b:/r/sites/tpwDTS/Shared%20Documents/DTS_GIS/2025-01%20--%20Winter%20Weather%20Emergency%20Response%20Maps/WW%20ER%20Print%20-%20Road%20Route%20A%20-%202025-01-09.pdf?csf=1&web=1&e=Knd2d0)

![WW ER Map - Roads Route A - 2025-01-09](https://github.com/user-attachments/assets/9582cbf9-0f0b-418c-8bfe-c00bf97956f1)

**Comment by OwenAMyers** [comment]
Here is map A with correct symbology for the Secondary Criticality and Other Critical Routes:
[20250110_EM_CriticalRoads_RouteA.pdf](https://github.com/user-attachments/files/18379605/20250110_EM_CriticalRoads_RouteA.pdf)

**Comment by OwenAMyers** [comment]
Here is the same file as above, with correct naming convention @amenity 
[WW ER Map - Road Route A - 2025-01-10.pdf](https://github.com/user-attachments/files/18380584/WW.ER.Map.-.Road.Route.A.-.2025-01-10.pdf)

**Comment by GimnichD** [comment]
@amenity @OwenAMyers I have given this map a final look and it is ready for deployment

**Comment by amenity** [comment]
Sharepoint: [2025-01 -- Winter Weather Emergency Response Maps](https://cityofaustin.sharepoint.com/sites/tpwDTS/Shared%20Documents/Forms/AllItems.aspx?csf=1&web=1&e=15Ph79&CID=891a78a1%2Dc009%2D7000%2D7e32%2Dd86156587790&FolderCTID=0x0120001B9845F0F9BFA94DBB7EA7D76E548F20&id=%2Fsites%2FtpwDTS%2FShared%20Documents%2FDTS%5FGIS%2F2025%2D01%20%2D%2D%20Winter%20Weather%20Emergency%20Response%20Maps)

[WW ER Print - Road Route A - 2025-01-10.pdf](https://github.com/user-attachments/files/18447841/WW.ER.Print.-.Road.Route.A.-.2025-01-10.pdf)
