### ISSUE TITLE
Create ❄️ ER map: Roads Route H

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#20413]
**Tasks**
- [x] Map author move this issue to the _In Progress_ pipeline when you begin working on it. 
- [x] Map author completes map, save as both Layout and Map files, and provide the G drive path (in `20241216_EM_bridge_and_road_treatment_maps`) as a comment below
- [x] Add @OwenAMyers as an assignee to this issue
- [x] @OwenAMyers add labels to the map and upload the proposed final map PDF as a comment below
- [x] @OwenAMyers move this issue to the _Review/QA_ Zenhub pipeline
- [x] @OwenAMyers add @GravesW1  and @GimnichD as assignees to this issue and notify them and the map author that the map is ready for final review in a comment below

**Review**
- [x] Map author review proposed final map; add comments below as needed
- [x] @GravesW1 review proposed final map; add comments below as needed
- [ ] @GimnichD review proposed final map; add comments below as needed and assign to @amenity. 
   - If **_very minor_** or **_must-have_** corrections/changes are required, move the issue back to the _In Progress_ Zenhub pipeline with a task list of changes as a comment below, and notify the map author.
   - If **_major_** or **_nice to have_** corrections/changes are required, consolidate as a task list in a comment below, and notify @amenity, who will create a backlog issue for a v2 version of the map. 

**Delivery**
- [ ] @amenity create a PDF that includes the work log table on the second page
- [ ] @amenity upload the PDF of the final map to Sharepoint 
- [ ] @amenity add an image of the final map and link to the file in Sharepoint as a Github comment and close the issue

**Comment by GravesW1** [comment]
ArcGIS Project:
G:\ATD\ATD_GIS\DTS_GIS_Projects\2024\20241216_EM_bridge_and_road_treatment_maps\03_Pro_Projects\Graves\route_H

Layout:
G:\ATD\ATD_GIS\DTS_GIS_Projects\2024\20241216_EM_bridge_and_road_treatment_maps\01_Working_Data\Layouts_and_Maps_Files\EM_Critical_Roads_Map_Templates

**Comment by grantstatton** [comment]
Route H ready for review: 
"G:\ATD\ATD_GIS\DTS_GIS_Projects\2024\20241216_EM_bridge_and_road_treatment_maps\01_Working_Data\Working PDFs\Routes\20250109_Route_H.pdf"

[20250109_Route_H.pdf](https://github.com/user-attachments/files/18368334/20250109_Route_H.pdf)

**Comment by GravesW1** [comment]
The map look great! No comments.

**Comment by GimnichD** [comment]
@grantstatton the legend looks significantly different than the other maps. is it possible to quickly change that? If not, then this totally works

**Comment by grantstatton** [comment]
@GimnichD The legend didnt come in correctly from the layout file so i had to remake it, i'll try to fix it

**Comment by grantstatton** [comment]
@GimnichD Heres the updated pdf with the correct legend
[20250109_Route_H.pdf](https://github.com/user-attachments/files/18368547/20250109_Route_H.pdf)

**Comment by amenity** [comment]
@GravesW1 @OwenAMyers - looks fantastic! 

Optional, but if you've got other edits and it's easy:
- [ ] Add more space between "Pleasant" and "Valley" in inset b
- [ ] Add more space between "William" and "Cannon" in the mainstage map

**Comment by grantstatton** [comment]
@GimnichD @amenity 
updated Route H map
[WW ER Map - Road Route H - 2025-01-10.pdf](https://github.com/user-attachments/files/18380681/WW.ER.Map.-.Road.Route.H.-.2025-01-10.pdf)

**Comment by GimnichD** [comment]
@amenity @grantstatton I have given this map a final look and it is ready for deployment

**Comment by amenity** [comment]
Sharepoint: [2025-01 -- Winter Weather Emergency Response Maps](https://cityofaustin.sharepoint.com/sites/tpwDTS/Shared%20Documents/Forms/AllItems.aspx?csf=1&web=1&e=15Ph79&CID=891a78a1%2Dc009%2D7000%2D7e32%2Dd86156587790&FolderCTID=0x0120001B9845F0F9BFA94DBB7EA7D76E548F20&id=%2Fsites%2FtpwDTS%2FShared%20Documents%2FDTS%5FGIS%2F2025%2D01%20%2D%2D%20Winter%20Weather%20Emergency%20Response%20Maps)

[WW ER Print - Road Route H - 2025-01-10.pdf](https://github.com/user-attachments/files/18447871/WW.ER.Print.-.Road.Route.H.-.2025-01-10.pdf)
