### ISSUE TITLE
Coordinate the Migration / Go Live for TCP Tracker in ROW Portal

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#2051]
Todo:
- pick a date to switch over: I propose evening of Monday, 8/31. Go-live in new system starting morning of 9/1
- communicate this to staff — full list of ~20 users
    - new URL
    - time the change will take effect
- run migration
- share new link with staff

**Comment by dianamartin** [comment]
- [ ] All records need to be migrated.

**Comment by amenity** [comment]
@johnclary - please forward an example of a "What's Happening" email to Chrispin

**Comment by amenity** [comment]
Also please add docs to the Knack wiki.

**Comment by ChrispinP** [comment]
Drafted email and sent to John for review

**Comment by ChrispinP** [comment]
Sent new email for Migration

**Comment by amenity** [comment]
@ChrispinP @johnclary - will y'all update the milestone on this to whatever you think is a realistic time.

**Comment by ChrispinP** [comment]
Meeting 7/1



**Plan**
July 2nd
- [ ] Send Email reminding everyone of Migration Plan

July 4th
- [ ] Migrate 2021 records to new ROW Portal
- [ ] Setup Automated Statuses
- [ ] Test
- [ ] Limit Access to TCP Tracker in Data Tracker, include messaging

July 5th
- [ ] Send Email on if Migration was Success/ any issues
- [ ] Update issues, finalize testing and migration

July 6th
- [ ] Will be available for support

**Comment by ChrispinP** [comment]
Migration Success email sent. Attachments also migrated successfully.

Resulting/Followup issues from Migration: #6615
