### ISSUE TITLE
Update to Performance Measures

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#2065]
Crystal T. 
Finance

- [ ] Asked to edit the goals for performance measures
  - turned on inline editing for `goals` field only
- [x] Add `9187  - Percent of new developments undergoing transportation analyses`
- [x] Add `6797 - Lost Time Injury Rate per the equivalent of 100 employees`
- Updated fields `Amended`, `Proposed`, `Goal` to accept 1 decimal place
- Update frequency of these measures:
• Measure ID 7575 – Change from Quarterly to MONTHLY
• Measure ID 8414 – Change from Annually to MONTHLY
• Measure ID 8594 – Change from Annually to MONTHLY
• Measure ID 6800 – Change from Annually to MONTHLY
• Measure ID 6802 – Change from Annually to MONTHLY

**Comment by dianamartin** [comment]
- [ ] Turned off inline editing
- [ ] Added the 2 missing measures
- [ ] Updated measure frequency from Annual to Monthly
