### ISSUE TITLE
Add UPS tracking fields into Data Tracker

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#2082]
Update `cabinet` object, signal details page, new cabinet, and edit cabinet pages:

- [x] Add UPS Install Date field - _date_
- [x] Add UPS Battery Replacement Date Field - _date_
- [x] Add UPS IP Address Field - _short text_
- [x] Add UPS Port # Field  - _short text_

**Comment by dianamartin** [comment]
@johnclary Do we need to update any APIs because of these changes?

**Comment by dianamartin** [comment]
Updated:
- [x] Signal Details>Edit Signal Cabinet form 
- [x] Cabinet Details>Edit Signal Cabinet form

**Comment by johnclary** [comment]
thanks @dianamartin. hmm, looks like we need to add an "add cabinet" form. There are 34 turned-on signals without cabinets. that's an oversight! Would you create a backlog issue for this, and to add the UPS fields to Socrata/API?

Here's the docs about the latter: https://app.gitbook.com/@atd-dts/s/austin-transportation-knack-guides/knack/open-data-portal-socrata-integration

 cc @amenity

**Comment by dianamartin** [comment]
@johnclary I created an `Add Cabinet` form to that page. I did a little rearranging of the fields so that the `Details`, `Edit Form` and `Add Forms` were consistent. I'll create a backlog issue to add the UPS fields to Socrata.
