### ISSUE TITLE
Additional Microsoft Teams training for staff

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#2114]
Scheduled for 6/11 and 6/16.

- [x] [Peruse materials from last training](https://github.com/cityofaustin/atd-data-tech/issues/2103)
- [x] Update Teams section of DTS' [ATD Staff Resources wiki](https://atd-dts.gitbook.io/atd-staff-resources/o365/teams)
- [ ] Coordinate with managers (Gilda/Karla/Nathan?) to schedule and notify/invite ATD staff
- [ ] Hold training(s) & record
- [ ] If necessary, update wiki based on staff feedback/questions

**Comment by amenity** [comment]
@johnclary - have you heard any requests for additional Teams training?

**Comment by johnclary** [comment]
Just followed up with the handful of folks who may require training.

**Comment by amenity** [comment]
@dianamartin scheduled a meeting about this for 6/2.

**Comment by dianamartin** [comment]
@amenity so the 6/2 meeting you made is another planning meeting or an actual meeting time for ATD staff?

**Comment by amenity** [comment]
@dianamartin - oh, that wasn't clear. I meant _you_ scheduled the meeting on 6/2. 🙃

**Comment by amenity** [comment]
@dianamartin - would you recommend we hold a third training or are we good to close this?

**Comment by dianamartin** [comment]
@amenity I think we can close this

**Comment by amenity** [comment]
Diana confirmed that this is good to close.
