### ISSUE TITLE
Hire an AMANDA BSA

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#2122]
- [x] PRF
- [x] Job Posting (will interview one candidate then post if needed)
- [x] Select Panel / Schedule Interview
- [ ] Write Interview Questions
