### ISSUE TITLE
Teams channel for COVID-19 activity logs

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#2152]
- Individual workgroups asking for guidance
- New time-tracking needs now that we need to pull reports to send to Homeland Security
-

**Comment by amenity** [comment]
@johnclary  - You mentioned that this ask has evolved. Would you please update & assign accordingly? 🙏

**Comment by dianamartin** [comment]
- [ ] Move `Employee` fields to `Accounts
- [ ] Re-do connections to Accounts
- [ ] Make sure tables are correct

**Comment by JaceDeloney** [comment]
Closing this out based on new requirements.
