### ISSUE TITLE
Integrate authoritative employee data from Banner

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#2167]
We're currently keeping employee records up to date manually via import and/or cross referencing other sources. We should pull authoritative employee data into the app, e.g:

- name
- email
- phone
- employee ID
- employee supervisor
- division name
- PCN (position control number)
- timesheet reporting codes (e.g. `1012` COVID code)

This data can come from Banner and/or Active Directory

**Comment by johnclary** [comment]
Not required for MVP. I reached out to both HRD (for Banner) and CTM (for Active Directory) to understand our options. Will report back.

**Comment by JaceDeloney** [comment]
@johnclary do any of these data sources include an "essential" designation? Asking re #2170

**Comment by johnclary** [comment]
negative. the essential designation is being determined on an ad-hoc basis by staff. will comment on that issue.

**Comment by johnclary** [comment]
we have API access from HRD! i've added that info to 1password. next step is to integrate the appropriate data from that API into the system. leaving in backlog for now.

**Comment by johnclary** [comment]
Making progress in [this repo](https://github.com/cityofaustin/atd-knack-banner). Reached out to Nathan today with a problem:

> Nathan—I've been working to set up the integration between the Banner system and our Knack HR app. This will ensure that anyone who needs to submit their NEO forms, telework request, etc. will have access to the system automatically.
> 
> I've run across an issue where it seems that employees' email addresses in Banner are not current. A few employees have a missing email address, and others' email addresses in Banner are different than what's in Outlook.
> 
> So I'm assuming the situation is that (1) sometimes the employee is created in Banner before they're assigned an email address and (2) there's no way for y'all who maintain Banner to get notified when CTM makes a change to someone's email address. Is that right?
> 
> In the near term, I think we'll just have to let you know when we run into this problem, and ask you to update Banner. In the longer term I will reach out to CTM to see if they can provide us the data we need to keep things square.
>

**Comment by johnclary** [comment]
Todo:
- [x] add configuration info for HR app
- [ ] add configuration info for DTS portal
- [ ] test out setting of user roles

**Comment by amenity** [comment]
@johnclary - Sprint 39?

**Comment by amenity** [comment]
@chiaberry - eying this for you. @johnclary said it will need to be better scoped and is probably a two-weeker.

**Comment by amenity** [comment]
Use case for this integration: Power users who manage applications need to be notified when an employee is separated. E.g. Staff from other divisions who have accounts in Signs and Markings' GIS need access revoked.

**Comment by moorerst** [comment]
@chiaberry we had a brief discussion with HR about the Banner Integration project being active. Here are a few comments they had about what is important for them:

- bi weekly update to Knack of any changes in Banner ( new/inactive employees, title change, supervisor change)

- Track Reg, Temp and Interns employees

- Contractors do not need to track - may need to have a separate page for contractors so they can be manually entered if needed

- Keep historical records i.e. employee status changed to Inactive then Active keep all the records

**Comment by chiaberry** [comment]
@moorerst thank you for the updates!

**Comment by chiaberry** [comment]
I count 8 employees in the email spreadsheet in the gdrive that don't have employee IDs associated with their names and emails, a few are in banner (with employee ids), but I found one so far that is in the CTM list and not in banner. 

Is it safe to ignore emails in the csv without employeeIDs?

**Comment by dianamartin** [comment]
@chiaberry I think it's safe to do that because perhaps the employee ID will be updated in BANNER and come over in a different update. 

This morning I did notice some accounts were "inactive". Did you run an update by chance? It was for the test accounts, I had to just re-add the passwords from 1password.

**Comment by chiaberry** [comment]
Or is it that the Test Accounts got their passwords overwritten?

**Comment by dianamartin** [comment]
@chiaberry It's a little bit of both. We never normally inactive Test accounts bc they're always used/shared with the team in our password manager. I think also bc their passwords got wiped, the password managers passwords didn't work. So it was an easy enough fix to update them in Knack, but that was when I realized that could be the issue. Not sure if it's possible to keep them outside of the updates.

**Comment by chiaberry** [comment]
PR ready for review: https://github.com/cityofaustin/atd-knack-banner/pull/1

@moorerst & @dianamartin How frequent do you want the script to run? And is there a preferred day and time?

Can we request a consistent filename from CTM for the email address csv? Instead of `2021-07-12-ATDUsers.csv`, `ATDUsers.csv` perhaps?

**Comment by dianamartin** [comment]
@chiaberry @moorerst Nathan said it can run as often as the Banners system updates. So I think every pay period (ex. 9/17, 10/3)

**Comment by moorerst** [comment]
@chiaberry @dianamartin - so you want the consistent filename ATDUsers.csv with no dates. 
So the filename will stay the same and be overwritten bi weekly?

**Comment by chiaberry** [comment]
@moorerst @dianamartin @johnclary ideally yes. They are free to upload a version of the csv with the date in the filename, along with overwriting the ATDUsers.csv. 

Otherwise I'll need to update the code to figure out how to handle the filenames.

**Comment by moorerst** [comment]
@chiaberry @dianamartin CTM wants to know what day/time you want the Active Directory employee data exported and starting on what date. i.e. every other Sunday @ midnight???

**Comment by moorerst** [comment]
@chiaberry Diana and I have a meeting with HR later today to talk about their HR forms Go Live but they always want to know how the Banner integration is going. Do you have an update I can provide them? Thanks

**Comment by chiaberry** [comment]
update: script is done and has been run, but I have not turned on the scheduled run yet. 

Friday I realized that you @moorerst are not included in the list of employees in Banner, I am guessing it only includes full time employees? This script will mark anyone not in Banner as "inactive", will it be an issue if part time employees are marked as inactive in the HR app?

As for the previous question about CTM, could they do Friday night or Saturday night? I am scheduling our script to update at 5am on sundays.

**Comment by johnclary** [comment]
@chiaberry i know you already talked to Diana about this. Stephanie is a contractor now. If you want to double-check a part-time employee you can verify that Tilly is not deactivated.
