### ISSUE TITLE
Test COVID-19 Tracking App on Brazos device

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#2182]
@dianamartin will need to work with PB to test COVID-19 Tracking App on Brazos device

**Comment by dianamartin** [comment]
Paul B. reached out to me and we're chatting about testing a Brazos device as I type. I'll give him the URL try.

**Comment by dianamartin** [comment]
@amenity @JaceDeloney @johnclary 

I send Paul a link to the HR app through teams, he put it into the Brazos browser and he said that their chrome profile is linked to the other devices. He just had to bookmark it. 

- [x] Able to sign in using COACD button, went through City of Austin login page
- [x] Was able to see the form
- [x] Was able to submit the form
- we noticed the employee table was missing, I added that back and added the `Employee` field back to the form. 
- I approved it and he confirmed that he saw the table change to `Approved` - Yes
- [ ] Paul is going to confirm on other devices that he sees the bookmark

Success!!!

**Comment by dianamartin** [comment]
Paul confirmed
>I have all the Brazos devices that are here at the shop updated.  The Bookmark is on all of them

on 3/26, I asked if Firefox could be installed on the Brazos devices
> Yes they can, and I just downloaded on all of them.
