### ISSUE TITLE
COVID-19 Time Tracking App Refinements

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#2190]
This is a running list of small enhancements to the COVID-19 Time Tracking App

### Update navigation tabs

Staff:
- [ ] Log Time (currently Home) | Help

Supervisors:
- [ ] Log Time (currently Home) | All Logs (currently Time Logs) | Employees | Reports | Help

**Rational:**

Log Time (currently Home)

- Right now this is where users log their individual time. When a user logs in, they're taken to https://atd.knack.com/hr#add-time/. If you try to go to https://atd.knack.com/hr#home/, it redirects to add-time. Log Time is just more descriptive of the actual task use case.

All Logs (currently Time Log)

- Right now this page shows all logs and the manager has to filter to see their respective employees.

### Time Logs Tab
On https://atd.knack.com/hr#time-log/

- [x] Update Needs Approval | COVID-19 Time Logs heading to **Needs Approval**
- [x] Update Approved | COVID-19 Time Logs heading to **Approved**
- [ ] Remove **Approved** column from Needs Approval table
@JaceDeloney I'd like to keep this column as it separates the `Approve` button and the `Delete` button
- [ ] Remove **Approved** column from Approved table
- [x] Update checkbox in Approve column to match blue of other icons
@JaceDeloney 
>This was because the when i increased the icon size it went from blue to black

**Comment by amenity** [comment]
A few more suggestions:

**Comment by amenity** [comment]
On https://atd.knack.com/hr#add-time/

- [ ] Update _COVID-19 Time Log_ to _Add Entry_

**Comment by dianamartin** [comment]
Had meeting with Jace on 3/26 about application refinements, we went over the proposed changes list and discussed what we should and shouldn't do to get the application out to the employees.
