### ISSUE TITLE
Implement MVP Warehouse Inventory Application

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#220]
Demo-able prototype should include:
- [ ] New Inventory Order Form (warehouse staff)
- [ ] New Inventory Order Form (customers)
- [ ]  Restock inventory items
- [ ]  Create inventory items
- [ ]  Move inventory items (_Stock Transfers_)
- [ ]  Create barcode
- [ ]  Scan barcode to lookup item
- [ ] Generate purchase request for item

**Comment by johnclary** [comment]
- [ ] New Inventory Request Form (warehouse staff)
- [ ] New Inventory Request Form (customers)
- [ ]  Move inventory items
- [ ]  Restock inventory items
- [ ]  Create inventory items
- [ ]  Move inventory items
- [ ]  Create barcode
- [ ]  Scan barcode to lookup item
- [ ] Generate purchase request for item

**Comment by dianamartin** [comment]
@dianamartin Create issue cards the checklist items

**Comment by dianamartin** [comment]
### Must Have List from Requirements Doc

Submit an inventory request online | Must have | Order management | x | x |   |  
-- | -- | -- | -- | -- | -- | --
Submit an inventory request in-person | Must have | Order management | x |   |   |  
Return an inventory item to the warehouse | Must have | Order management | x |   | x |  
Fulfill an inventory request | Must have | Order management |   |   | x |  
Track person to whom an item is issued | Must have | Order management |   |   | x |  
Bill inventory items to one or more task orders | Must have | Order management |   |   |   |  
Receive an inventory shipment | Must have | Purchasing/Receiving |   |   | x |  
Restock Inventory Items | Must have | Purchasing/Receiving |   |   | x |  
Create/Print barcode labels | Must have | Purchasing/Receiving |   |   | x |  
Manually adjust inventory levels to reconcile discrepancies | Must have | Purchasing/Receiving |   |   |   | x
Export inventory requests to spreadsheet | Must have | Reporting and admin | x | x | x | x
Create, modify, and remove users | Must have | Reporting and admin |   |   | x |  
Generate report of inventory levels | Must have | Reporting and admin | x | x | x | x
User roles and permissions - technicians can submit only | Must have | Reporting and admin | x | x | x | x
Scan barcode | Must have |   | x |   | x |  
Create barcode label | Must have |   |   |   |   |  
API — Create inventory requests | Must have | API |   |   |   |

**Comment by dianamartin** [comment]
**Restock Items**
- [ ] Create new `Restock items` form 
- [ ] Add to Page drop down menu
- [ ] Remove from button from Transactions page

**Move Items button**
- [ ] Create new `Move items` form 
- [ ] Add to Page drop down menu
- [ ] Remove from button from Transactions page

**Test Forms**
