### ISSUE TITLE
AMD Workflow Mark-up Meeting

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#2217]
Schedule for 4/20, Monday

- [x] Scheduled for 2-3 weeks out from 3/31/2020

### Agenda
Add agenda here or create agenda from [this template](https://docs.google.com/document/d/1d_49KW5C_vSz8Bs50v-cxyIJuTNJMwMrh7ypcxRHgZI/edit#) and add link. 

------
- [ ] Schedule meeting
- [ ] Optional: Schedule debrief
- [ ] Meet and take notes
- [ ] Optional: Debrief with DTS team members
- [ ] Create resulting issues

**Comment by amenity** [comment]
@dianamartin - plz create issues for follow up meetings.

**Comment by amenity** [comment]
@dianamartin - my (not-very-useful) notes:
Brian: 
- Need ability to prioritize
- Vision is that work order system drive schedule
- If it all goes into one repository and there is standard set of information that **has** to be completed it will make it a lot better

Robin: 
- Would like this to trace work status end-to-end: concept ---> in design ---> scheduled 
- This is all "project"-based - 
  - 1 per year - e.g. 5th St bus lane, contraflow bus lane
    - Vary in size - small as a single work order (back and forth about this); 
    - Projects can span multiple locations
    - Could have unique names; worst case scenario would add direction; would also be grouped by TK number
