### ISSUE TITLE
Feature request: [Feature name]

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#2233]
Jonathan T.
ROW

Messaged
>I have a query I need run.  It's not something we need to have as an ordinary function, this is a unique instance.  I need to create a list of TCP #'s in which the Sealing Engineer is Frank M. Is that something you can help me with, or can you point me in the right direction to who might be able to run that?

**Comment by dianamartin** [comment]
Messaged user back
>Okay, I've updated the TCP List page (Advanced Search). I added the "Submitted Name" and "Sealing Engineer" to the search fields and made the table exportable. 
- [x] Fixed all search fields to be Proper case
- [x] Fixed all search table fields to be Proper case
- [x] Tested the query for Sealing Engineer, got 131 records returned

**Comment by dianamartin** [comment]
User confirmed this was what they needed
>That's what I got...and that seems about right.  That should do it. Thanks again.

**Comment by amenity** [comment]
@dianamartin - what should this issue be named?
