### ISSUE TITLE
Nelson Nygaard Micromobility Usage Data Request

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#2283]
We have been requested to provide Nelson/Nygaard with micrromobility usage data using custom polygons that are more granular than Census tract, which is how the data is currently delivered on https://data.mobility.austin.gov/micromobility-data/.

**Background:** The city is working with DAA and Nelson Nygaard to conduct a study on local circulation in the downtown and downtown-adjacent areas. They are looking at all modes, and are wanting to get more granular O/D pairs to determine where micromobility solutions could have the biggest impact. The current format is based on census tract, but this doesn't give their team the granularity needed. 

To further minimize privacy concerns, we will not be providing timestamps of O/Ds. 

Request:
- [x] Recommend a month to use that is representative of "average" usage throughout the year. We will need to account for seasonality, school schedules, festivals, etc.
- [x] Pull usage (O/D, not timestamp) data for the month
- [x] Use that month's worth of data and geoprocess it using custom polygons provided by Nelson Nygaard
- [x] Create final output data to share with N/N

**Comment by mateoclarke** [comment]
we're going with April 2019 O/D trip data

**Comment by mateoclarke** [comment]
Data has been pulled and shared with @JaceDeloney in csv format.

**Comment by mateoclarke** [comment]
This task has been complete and NN has the data. If more followup is required, we can open as a new issue.
