### ISSUE TITLE
SMB "Work Schedule" calendars, Coordination - Y, set Color Highlight: Lime Green

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#2305]
> What application are you using?

Signs & Markings Operations

> Describe the problem.

On the Signs & Markings Operation application "Work Schedule" calendars, we would like to identify work orders that have Coordination = "Yes" with a different color. This would be for all of the various views of the Work Schedule calendar. 

> Describe the outcome you'd like to see when this feature is implemented.

By highlighting all coordination work with a different color, it will help staff identify when we need to be coordinating. There have been coordination issues.

> Describe any workarounds you currently have in place or alternative solutions you've considered.

We try to catch if they are coordination projects when work is being scheduled out, but there have been circumstances when this has been missed and we don't coordinate properly.

Request ID: DTS20-100625

**Comment by dianamartin** [comment]
Evaluating the `work_orders_markings_jobs`, it doesn't have the Coordination field on it. Have to make a text formula to get it from the parent table. 

- [x] Added `Coordination Jobs`
- [ ] Create `LL Coordination`
- [ ] Create `SL Coordination`
- [ ] Create `SM Coordination`
- [ ] Create `RPM Coordination`

Add filter to 
- [ ] Markings Technician Calendar view
- [ ] Marking Supervisor Calendar view

**Comment by dianamartin** [comment]
Talked to Christina and it looks like it can be done, but need to check with Supervisors to see if they want all work groups to be in the filter.

**Comment by dianamartin** [comment]
Christina sent to SMB supervisors

>Just want to say that y’all are awesome!
