### ISSUE TITLE
[RPP Back Office] Refinements after Usability Testing / Application Part 1 - 3

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#2334]
**Part 1: CONTACT INFO**

- No problems here
- Default caps were unexpected

- [x] She was able to put in only an initial and was able to move forward (question to RPP Staff)

- [ ] Phone and Email fields are automatic hyperlinks, check on this. User felt like it didn’t need to be.

- Users would like the autofill aspect (browsers have this)

**Part 2: PERMIT INFO**

- Nice that the address autocompletes. 

- [x] User is confused about language. Language is confusing. Current language: “Combination of hang-tags and decals should equal 4.”. Suggests: “Equal up to 4”. 
Preferred seeing: “maximum 2”, “maximum 4”

- Number of permits wasn’t clearly stated anywhere for her address to reference
- Read the NOTE, as a resident doesn’t sound applicable to residents. Cap on how many hang-tags, decals. Doesn’t think a resident should need to be aware of this. 
- Language under hang-tags isn’t clear. Interpretation for hang-tag/decals for the street and not their address. 
- *** Stars, footnote to link about Day Passes, Link to Mueller. Day passes field is confusing

- [x] (** Astrisk) Makes it feel like user has to get Day Passes. Is currently required, but shouldn’t be required. 

- Lots of asterisks. Seems like part of the notes section, but coherent. Know that the asterisk could be related, felt like a footnote. Lots of asterisks in that section. Reformatting the section.

- [x] Don’t know what days passes are, need to change. (Need to have pop-ups to explain what permit types are)
- [x] Permits/Day passes good for the whole year? Do they expire?
- [x] Include they are one time user day passes

**Part 3: REQUIRED DOCS**

- “Add Documents” button is confusing. 
- [ ] User suggested to change button to “Continue”
- [x] “Add Documents”, change “Save Documents”

**Comment by dianamartin** [comment]
## New - Part 1: Contact Info
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/e27ae8ff-82c7-4ebc-98b9-e4855f0d2d18)

**Comment by dianamartin** [comment]
## New - Part 3: Required Documents
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/958569e7-d8af-42ce-9df2-40792d4f1f1f)

- New button name `Save Documents`
