### ISSUE TITLE
Project: PPE Inventory Tracking

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#2351]
Help ATD staff manage the purchasing and issuance of personal protective equipment (PPE) so that we can ensure staff are able to maintain adequate personal protection while working through the COVID-19 pandemic.

## Description
We have received a request to create a PPE Inventory Tracking solution. Currently, each division has been requesting and purchasing their own PPE, causing confusion as to the current inventory of PPE across the department. The goal is to consolidate and centralize PPE requests, purchases, and distribution across ATD. 

Finance and HR have been doing most of the purchases for PPE. Finance is approving purchases in Knack. New purchases are happening almost every day. Each of the divisions is managing or distributing their supplies on an as needed basis.

Currently there is a spreadsheet that staff have been using to keep track of deliveries. That spreadsheet does not provide information on how much is left, only what the department has received and distributed to each facility since March 16th. 

**Spreadsheet here -->** [https://app.zenhub.com/files/140626918/d06e9e92-7837-4fda-a8e1-e426a9767335/download](https://app.zenhub.com/files/140626918/d06e9e92-7837-4fda-a8e1-e426a9767335/download)

We need to set up workflows to track the quantities of personal protective equipment (PPE) on hand at all facilities.

### Components
The PPE Inventory Tracking tool should enable the following:

**Add Inventory**
- Category
- Type
- Quantity

**View Current Inventory**
- Category
- Type
- Quantity

**View Added Inventory History**
- Category
- Type
- Quantity
- Date

**View Distributed Inventory History**
- Category 
- Type
- Quantity
- Date
- Facility PPE was distributed to

### Definitions
**Definition of Category:** A category is a group of similar PPE items (e.g., hand sanitizer vs masks)
**Definition of Type:** A type is a more specific PPE item that may come in a special size (e.g., 60 oz hand sanitizer vs 12 oz hand sanitizer)
**Definition of Quantity:** Quantity is the number of separate items 

**Categories**
Hand Sanitizer
Hand Soap
Masks
Gloves
Gowns
Disinfectant Wipes
Disinfectant Spray

**Types**

- [x] Hand Sanitizer - 67oz
- [ ] Hand Sanitizer - 40oz
- [ ] Hand Sanitizer - 12oz
- [ ] Hand Sanitizer - 8oz
- [ ] Hand Sanitizer - 4oz
- [x] Hand Soap - 8oz
- [x] Hand Soap - 1 gal
- [ ] Hand Soap - container
- [ ] Disinfectant Spray - Lysol
- [ ] Disinfectant Spray - Alcohol
- [ ] Disinfectant Spray - Sets of 3 Spray Bottles
- [ ] Disinfectant Spray - Large Spray Bottle
- [ ] Disinfectant Spray - Spray Bottle
- [x] Disinfectant Spray - Disinfectant Spray 32oz
- [x] Disinfectant Spray - Disinfectant Spray 16oz
- [x] Disinfectant Wipes - Wipes
- [x] Masks - Masks
- [x] Gloves - Gloves
- [x] Gowns - Gowns

**Comment by JaceDeloney** [comment]
Just got off of the phone with Gilda. Here are my notes:

- > Is this tool intended for Peggy and Gilda or for division managers to keep track of their own inventory?
The goal of this tool is for the dept to have a centralized process and tool to track PPE inventory. Right now, division managers and teams are purchasing their own PPE without communicating that to the department. So when the department requests and receives new PPE, they have no idea who has what. The goal of this tool is to centralize PPE requests and distribution.
- > Are all PPE products disposable, or is there a need to track returns of PPE back to the central inventory?
All PPE products are disposable. No need to support PPE returns
- > Do we need to track sub-inventory (e.g. current inventory of masks on the Arterial Management Division)?
Not now. This may be a need in the future, but the focus should be on the department-level inventory
- > What do the colors on the spreadsheet mean?
It was just a way to group types of PPE products, not really used anymore
- > Are the fields listed in the spreadsheet a comprehensive list of PPE product?
No. This list was compiled mid-March and is an exhaustive list. Most PPE requests moving forward will be hand sanitizer, masks, gloves, gowns, wipes, and disinfectant spray

**Comment by JaceDeloney** [comment]
Reference #500 for similarities

**Comment by JaceDeloney** [comment]
**Status update**
No real changes to this app overt he past several months. Gilda is the main power user and has been asking for relatively small changes, which Diana has been able to handle quickly.

**Comment by patrickm02L** [comment]
Removed Product: Financing & Purchasing tag because it was pulling unrelated PPE Issues into the DTS website description page.

**Comment by dianamartin** [comment]
@patrickm02L but the PPE Inventory is a module in the Finance and Purchasing system..?

**Comment by patrickm02L** [comment]
@dianamartin I want to see what it looks like without the tag. We can revert it back if we want to. 

But I removed it because when I'm looking at the Issues tab there's a ton of Issues that aren't relevant.

![Screen Shot 2022-11-28 at 10 49 30 AM](https://user-images.githubusercontent.com/5566727/204335211-26528227-c122-43ca-85cc-aaa9b2ed42f8.png)

**Comment by dianamartin** [comment]
@patrickm02L Oh I see what you mean..
