### ISSUE TITLE
Create PPE Tracking pages in Finance & Purchasing app

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#2354]
After discussion with John and Jace we decided to build out

### ppe_inventory_items
- [x] PPE INV ID
- [x] CATEGORY
- [x] ITEM NAME
- [x] STATUS
- [x] CREATED BY
- [x] CREATED DATE
- [x] MODIFIED DATE
- [x] UNIT OF MEASURE
- [x] UNIT PRICE
- [x] REORDER THRESHOLD

### ppe_transactions
- [x] PPE TRANS ID
- [x] TYPE: Restock, Issue
- [x] DATE
- [x] QUANTITY
- [x] COMMENT
- [x] LOCATION
- [x] connection - issued by
- [x] connection - issued to
- [x] MODIFIED DATE
- [x] MODIFIED BY
- [x] CREATED DATE
- [x] CREATED BY

## Tabs/Pages To Build
- [x] New Tab - PPE TRACKING
- [x] Current Inventory (Report Pivot table) - _Stand alone page_
  - [x] Restock Items (add)
  - [x] Issue Items (distribute)
- [x] PPE Inventory  Items _Stand alone page_
  - [x] Inventory Item Details 
  - [x] Add Inventory Items
  - [x] Edit Inventory Items

**Comment by dianamartin** [comment]
## Tabs/Pages
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/3569afe9-03fa-4c9d-a39f-d7010ca774dd)

# Current Inventory
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/b3ed4747-5e2a-4426-8762-e1a1274f87f8)

## Restock form
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/5140ebdc-7d85-4709-b772-fdc0bfafad58)

## Issue form
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/5f00023e-3e0f-4a68-9591-d41481f38b6d)

# PPE Inventory Items page
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/8987ec4d-6595-45c8-895e-b3a68b0d4a12)

## Add PPE Inventory
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/aec45259-0f69-4043-96e4-3a1693a782b6)

## Edit PPE Inventory
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/03f34b89-ee9c-4e83-b3a6-386c45137f41)

## PPE Inventory Details
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/06cbd35c-ef4d-49cc-8bff-2724fccdfa57)

# PPE Transactions page
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/8a5daf15-764b-44cf-abc8-e5eb024d539b)

**Comment by dianamartin** [comment]
@JaceDeloney @johnclary If you don't get a chance to log in, I've added some screen shots to this issue so you can see the pages that I've created. Let me know if we have any changes.
