### ISSUE TITLE
PPE Inventory Tracking UI Updates

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#2359]
### Changes to PPE Current Inventory Tab
**PPE Current Inventory** 
- [x] Change `PPE Current Inventory` to `Current PPE Inventory`
- [x] Change `Restock` button to `Add`
- [x] Change `Issue` button to `Distribute`
- [x] Change `ATD PPE Inventory` to `Current ATD Inventory`
- [x] Add `Category` column to `Current ATD Inventory` table
>This "Category" column, isn't on the transactions table. I'll have to figure this will be possible to do
- [x] Change `Count` to `Quantity`

_Open Question: Should we remove these bottom two tables? The PPE Transactions page allows users to filter this information._

**Restocked Inventory Transactions**
- [x] Change `Restocked Inventory Transactions` table to `Added Inventory History` 
- [ ] Add `Date Added`, `Category`, and `Quantity` columns to `Added Inventory History` table
>This "table" isn't a real table. It's a pivot table, so I'll have to figure this will be possible to do.
I've added the other fields on the expanded table view.
- [ ] Remove Location column from `Added Inventory History` table

**Distributed Inventory to ATD Locations**
- [x] Change `Distributed Inventory to ATD Locations` table to `Distributed Inventory History`
- [ ] Add `Date Added`, `Category`, `Item`, `Quantity`, and  `Location` columns to `Distributed Inventory History` table
>This "table" isn't a real table. It's a pivot table, so I'll have to figure this will be possible to do.
- [x] Added `Category` to the table. I've added the other fields on the expanded table view.
### Changes to PPE Inventory Items tab
- [x] Change `Add PPE Inventory Item` button to `Create New PPE Inventory Item`
>I changed it to `New PPE Inventory Item", the other way was really long.

**Comment by dianamartin** [comment]
@JaceDeloney some of these things are not possible bc the "tables" are actually a pivot table and some fields you requested can't be added. Also, I disagree with some of the suggested naming of the pages/tabs.

**Comment by dianamartin** [comment]
@JaceDeloney @johnclary Changes updated, please review.
