### ISSUE TITLE
Meeting: Transition TIA process into Knack - TDSD Tracker

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#2373]
### Meeting Info
**Date/Time:** 4/30 @ 11am
**Attendees:** Diana, Tracy, Joan, Nathan Aub.
**Agenda in comment below** 

> What application are you using?

Other / Not Sure

> Describe the problem.

Transition from using the TIA Primary List off a Spreadsheet into Knack for inputting projects and project tracking.

> Describe the outcome you'd like to see when this feature is implemented.

Knack keeps track of ROW IDs, project names, timelines, integrated with Amanda to facilitate project tracking. We would also like to be able to audit our response times for performance measure tracking.

> Describe any workarounds you currently have in place or alternative solutions you've considered.

TIA Primary List (excel spreadsheet)

> Is there anything else we should know?

As soon as possible, entering data (not automating) is time-consuming and we need to find a better use of City resources. 

Request ID: DTS20-100660

**Comment by dianamartin** [comment]
## Agenda of topics to cover for TDS Tracker 2.0 enhancement meeting:
•	Transition from current TIA Primary List (Excel Spreadsheet) into Knack for inputting/tracking projects
•	IT’s perspective on best way to achieve and implement this transition
•	Time-line for piloting and implementation
•	TDS would like Knack to include features that would allow keeping track of ROW IDs, project names, time-lines, and audit response times for performance measuring tracking.
•	Knack vs. Amanda for project tracking? Integration?

**Comment by dianamartin** [comment]
Reference #1695

**Comment by dianamartin** [comment]
Note to self: Need to reschedule as soon as we know when Tracy will available.

**Comment by dianamartin** [comment]
## Diana Notes

[`TIA Primary List`](
New project and enter in manually
Enter case numbers
District 

How do you know if you have a new project?
Emailed a project

People reach out to TDSD, TIA
Developers, Engineers reaching out to them
- held up at DSD or at OTC

Need a TIA
They ask: What do I need to do for it?
Customer based initiation

Not assigned in AMANDA, all offline

**Comment by TracyLinder** [comment]
### Tracy's Notes

- The spreadsheet that is being replaced is called 'TIA Primary List'
- Every new project is entered manually
    - New projects are emailed to them by a developer directly
    - About 70 cases a year, so receipt by email isn't overwhelming at this time
    - Diana thinks having the customer initiate this process through a form is possible
    - Diana says the solution will be modeled after the TCP tracker
- Round 1 of reviews the team has 28 days to review, on subsequent reviews it is 2 weeks max
- Diana suggesting a deep-dive into requirements for TIA locations, and how KNACK should handle the case location(s)
- There are multiple review comments for each review round - so follow a the TDS app lead for this feature
- TIA are reviewed by council district, so each reviewer is assigned a district
- Currently customers are emailing the plans that TIA reviewers need to perform the review. Staff would like an option for the customer to submit that with the form submittal. Diana asked how large these files are on average. Nate says whatever Outlook normally handles. 

Tracy: 
- [ ] schedule requirements gathering, 1 1/2 hours, once a week for 3 weeks. Wednesdays are good. 
- [ ] Setup project in Github
- [ ] Create user story matrix

Nate hoping for MVP prototype by mid-july.

**Comment by dianamartin** [comment]
## Internal 
### Management of TIAs
- As TIA Staff, would like ability to track non TIA requests
- As TIA Staff, would like ability to get TIA requests aggregated on a table to see what requests I need to work on
- As TIA Staff, would like ability to have request organized by Council Districts/Reviewer Areas
- As TIA Staff, would like ability to elicit comments from other ATD work groups for a TIA submission
- As TIA Staff, would like ability to aggregate a final decision comment about a TIA project

### TIA Submissions
- As TIA Staff, would like ability to track TIA submission rounds per TIA (Parent>Child records)
- As TIA Staff, would like ability for other ATD work group reviewers to be able to make comments and attach files as needed

### TIA Reporting
- As TIA Staff, would like ability to track the duration of a single TIA submission from start to finish
- As TIA Staff, would like ability to track the average duration of TIA submissions of a reviewer 

## External
- As a TIA Customer, would like ability to know how to contact ATD staff to get conversation going about a TIA
- As a TIA Customer, would like ability to submit a request through a form (not email)
- As a TIA Customer, would like ability to check on my request status
- As a TIA Customer, would like to get emails from TIA Reviewer on things I need to change/do
- As a TIA Customer, would like ability to upload plans/attachments or enter in a web link to a dropbox/box account for oversized files
