### ISSUE TITLE
Meeting: Markings Assets - Asset maintenance date in Knack

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#2383]
### Objective 
**Background**
To be able to track when work is being done on a markings asset, Susanne asked me to create a table in MAINT that would be related to our markings assets through the MARKINGs_ID field. The related table would include the ID field, a type of work being done field (Installed, Maintained, Removed), and a Work Order ID. The Work Order ID would allow us to find the time stamps from the jobs.

To test the tables, I created them for each marking type and loaded all existing IDs. This would allow me to keep editing in a version, which I currently do to circumvent parcel fabric editing errors in MAINT.

After digitizing in ArcMap, I’d add the Work Order ID and type of work into the related table.

However, once I loaded the tables into my editing mxd, they would show up correctly through the Identify tool, but not show up during editing. I am not sure why this happened. The tables are registered as versioned, but I’m only able to bring them into my “staging” version. (In anticipation to having new GIS techs, I made a DTS staging version and version for myself to edit in).

At this point, I updated Susanne on testing the tables, and we wondered if it would be easier to track the assets in the jobs page in knack, similar to how we track street segments, so that Susanne is able to pull up the date of install, maintenance, etc., for each asset in ArcMap.

I’m not sure how it would work best for Knack, but my idea was to see if we could create a one to many relationship to a table from each job to all the assets that are updated in GIS. This table would be populated from the form that catches the Markings IDs in Knack (like the street segment form). From a workflow perspective, this might be simplest solution for GIS staff.

### Participants
Alan, Susanne, Christina, Diana & John

### Agenda
Talked about various things. What has been tested, some troubleshooting methods, proposed enhancement in Knack SMB Data Tracker

------
- [x] Scheduled meeting: 4/17
- [ ] Optional: Schedule debrief
- [x] Meet and take notes
- [ ] Optional: Debrief with DTS team members
- [ ] Create resulting issues

**Comment by dianamartin** [comment]
## Diana's Notes
Most of the dates in markings assets don't have historical maintenance dates

**Briefed about process**
Marking WO - `table`
Markings jobs - `table`
1:M - relationship

Susanne looks at:
Job -"Completed date/Install date"

**Current State**

GIS assets - doesn't have a historical maintenance date
- LL
- SL
- SM - PNT
- SM - LN

`Date`: _Last date maintenance (Installation date gets overwritten))

Alan is currently versioning - while editing
He created a related table (in MAINT env): created a relationship class
- Created rules in relationship class
- Make edits in related table
- To fill out fields

**FIELDS ON RELATED TABLE**
`Markings ID` - associate to GIS asset
`Work Task Done`

**ISSUES**
doesn't work in current environment
related table: table/records weren't editing session

**PROPOSAL**
Adding Markings ID to Jobs
Markings ID - Segment (Parcel fabric) 

**EDITING ERROR**
Parcel Error: Everyone edits in Maint 
50 like error lines
Parcel Fabric team - known issue CTM

**Work around: couldn't save, couldn't post the edits
copy them to feature class (copy GDB)
ERROR IS NEW??
Option 1: Then bring them back in to Maint
Option 2: During compression at the end of the week (4-6 pm)
Started versioning - due to this fact

Jaime finally ran into this error recently

**PROPOSED**
New field added? 
Field that collected several fields 
Street Segment field - Markings WOs

Related table to Jobs table (would stay the same)
- Add Markings ID 
- SM PNT (35 k)
- 57k 
- SL 15k
- RPM 6k

Think about in Knack - custom field (looking up related table from somewhere else)
- Search for asset and get populated from another dataset
- Purpose of asset in Knack to have the data quality ID 
- 3 tables (load) 
- Asset table (asset ID, asset type, job ID) 
Create assets in Knack


Tie Asset ID (C&P) to GIS

Specifications - convert to asset

Generate IDs outside of MAINT - bring them into the jobs
Importing all the assets into Knack..

Use Jobs Date for metrics 

Start capturing the asset attributes: asset data in GIS 

### NEXT STEPS
Get with Product Managers
Create a Work Plan
Every month or 6 month - backlog

Set-up a meeting
Work Plan presentation

**Comment by alan-deanda** [comment]
## Alan's Notes

* We settled on the date of a Work Order's closing as the most appropriate to track for asset work history.
    * Sometimes jobs are open for long periods of time, and there is a business need to close jobs and work orders sooner.
    * From a materials' longevity perspective, there is not a significant difference in tracking an installation date within a margin error of a few days, or even 2 months. (Currently the time between installation and final inspection can take as long as 2 months, but the work flow is changing to lower this time. 
    * The only markings that may need more precise date keeping are markings with shorter lifespans, like temporary tape markings. In these cases we can refer to the job dates.
* Digitizing markings in GIS will continue, and changes will be implemented as they develop.
