### ISSUE TITLE
Scaffold Infrastructure/DevOps pipeline

### ISSUE THREAD

**Issue by zappfyllc** [cityofaustin/atd-data-tech#2410]
JD has a local instance of Hasura running on a docker container. This will need to be deployed through whatever DevOps setup ATD has.

**Comment by amenity** [comment]
Per #2440, we are going to wait a bit before standing up this infrastructure.

**Comment by zappfyllc** [comment]
Removed #2326 because we can proceed to set up the infrastructure regardless of Hasura and then migrate the metadata over. @sergiogcx let me know if there are any foreseen challenges with that approach, as I don't mind migrating over immediately but trying to clean up things before we start tracking/committing all the changes only because it speeds things up a bit on my end.

Action items that can be turned into issues per @amenity's [notes](https://docs.google.com/document/d/1SuJ6rxT1fPrPVnJQQgZ7JPluqYjMgzO-7bSiStESg3c/edit#) and our discussion on 8/24:

- [ ] Create repo for Moped
- [ ] Research GitHub actions for potential CI/CD (they deploy to Firebase in this article, but [I quickly scanned to see if this was helpful](https://medium.com/@giologist/ci-cd-multi-environment-deployment-for-a-react-app-on-firebase-using-github-actions-f48bc6b08b21))
- [ ] Set up Netlify
- [ ] Set up Cloudfront distribution(s) with relevant subdomains

I'm sure I'm missing something so we will discuss in sprint planning and can create resulting issues from there

**Comment by sergiogcx** [comment]
Thanks for these notes, excited to get started.
