### ISSUE TITLE
Create help guide videos for PPE Tracking

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#2415]

**Comment by dianamartin** [comment]
**PPE Requester**
- [ ] How to fill out PPE Request

**PPE Request Manager**
- [ ] How to manage a PPE Request (beginning to end)

**PPE Distributors (Warehouse)**
- [ ] How to Add Inventory Item
- [ ] How to create Restock record
- [ ] How to create Distribute record

**Comment by dianamartin** [comment]
I messaged on Slack on 4/22 at 6:11 pm
>I'm done with the videos.
