### ISSUE TITLE
Design & Construction Service workflow with Contractors

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#2433]
### Objective 
Scheduled 4/27/2020

### Agenda
This meeting is to talk more about the Design & Construction Services work group (Inspectors) and what the workflow looks like coordinating with Signal Contractors/Signal Technicians. 

I’d like to update the AMD work group work flow to include this. 

------
- [ ] Schedule meeting
- [ ] Optional: Schedule debrief
- [ ] Meet and take notes
- [ ] Optional: Debrief with DTS team members
- [ ] Create resulting issues

**Comment by dianamartin** [comment]
## Diana Notes

Renee O. talking about
Coordinate use their resources, like Ben/Julian. Using the same contractors. EARTC leave the coordination with Brian C. 

### Vendors that AMD has construction contracts
- **Austin Traffic Signal (ATS)** - does above and below ground (adjacent to cabinet -pull box)
  - AMD Techs are doing the wiring (in-house)
- **MASTEC** (below ground work normally)

### IDIQ Contract: different types of work (Non-site specific contract)
_Indefinite delivery, indefinite quantity_
- Knock down: foundation, pole/arm set
- Cost estimate, work authorization

- New Signal 
- Cost estimate, materials

### Grant Projects
- Contract
- Signal design, contractor review unit price and provide cost estimate to AMD
- Unit prices/quantities are set

Use contractors for Mods & Upgrades, Knock-down, and New Construction
- ex. pouring new foundation 
- Contractors use boom truck, AMD doesn't have this truck. Lifting and setting poles. 
- Installing wiring for video detection 

MMC is the liaison unless they have
- Coordinate with contractors, they call the MMC to confirm 
- ex. installing device (like camera), confirm operation for the contractors
- remote connectivity

Joshil creates WO for EARTC
- Then assign work to them in Data Tracker


### Knock Down (large impact - contractor needed)
- AMD Technicians, patch up what they can at the signal (functional/safety)
- Coordinate with Design & Construction Services to get contractor out
  - Come up with design (if required)
  - Goes through IDIQ steps
  - Create at DO, AMD provide cost estimate 
  - Have to do DIGTESS and possibly move foundation
  - Issue the work order with the Contractor
- Coordinate with SMB to get signage/markings (temporary fix)

### New Construction (Grant work)
- **IDIQ**
- Internal design (AMD) / External design (AECOMM), from Development Services
- AMD will give Cost Estimate to contractor 
- AMD prepares DO (Direct order)
- AMD permit from ROW 
- AMD issues work order to Contractor 
  - Work Assignment (includes DO, instructions) - CMO: Contract Management Office
- Work is done
- Invoice is turned into AMD, AMD approves
- CMO pays contractor

- **Grant**
- Public Works (Engineering Services Div, ESD) External design (AECOMM), from Development Services 
- Contractor provides bid cost based on design and return to AMD
-

**Comment by dianamartin** [comment]
## Action Items
- [ ] Update AMD Work group work flow
- [ ] Create Design & Construction Services workflow - detailed
