### ISSUE TITLE
Proposed Dream AMD Work Order fields

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#2434]
### Objective 
Consolidate the work group fields needed from each work group
[Meeting Notes](https://docs.google.com/document/d/16-bKanftMot74eAbtC-pQQYK3NVgWd3Kzp2OVfnVJ9o/edit)

### Agenda
From now until the meeting please be thinking about what you’d want to see on a work order for your work group or a work order you’d create to give to another work group. 
Mock up drawings and drafts are welcome!

We will be discussing and comparing the fields that all the AMD work groups have in common at this meeting. Hopefully, it will be a good starting point to getting everyone’s needs and requirements. Also be prepared to share your form/concept.
------
- [x] Schedule meeting
- [ ] Optional: Schedule debrief
- [ ] Meet and take notes
- [ ] Optional: Debrief with DTS team members
- [ ] Create resulting issues

**Comment by dianamartin** [comment]
Robin's [Signal Engineer Work Order Fields.xlsx](https://app.zenhub.com/files/140626918/096c2569-72aa-4f70-a306-ce562e5f18f2/download)

**Comment by dianamartin** [comment]
### Follow-up

- [ ] **Summarize what we discussed in the meeting → meeting notes**

- [ ] **Create of internal Service Requests**
Functions    
- Add Activity
- Activity - attachment

**Service Request convert to global work order**
- Similar to MMC converting to Signal work order

**Update Work Order functionality:** time/labor tracking, materials tracking/specification tracking

**Process changes**
Signal engineers start creating Signal Work Orders

- [ ] **Technical Review of Requirements**
- [ ] **Technical Plan** 
- [ ] **Schedule Review with stakeholders - 2 weeks: propose the plan/set timelines**

**Comment by dianamartin** [comment]
Sync'd with Amenity and talked about the idea of AMD Service Requests and then Projects
`Projects` > `Service Requests`> `Work Orders`>`Assets`>`Locations`

Will need to have a proper builder huddle for this.
