### ISSUE TITLE
Vision Zero Viewer User Testing

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#2455]
This issue is created to track all of the work around VZV user testing and feedback, pre and post release.

- [x] Schedule user testing
- [x] User acceptance testing
- [x] Post-release feedback mechanisms (surveys, forms, recurring user testing sessions)
