### ISSUE TITLE
Document recommended approach to Work Order extension and refactoring

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#2561]
- [x] **Summarize what we discussed in the meeting → [meeting notes](https://docs.google.com/document/d/16-bKanftMot74eAbtC-pQQYK3NVgWd3Kzp2OVfnVJ9o/edit)**

Ideas from meeting
**Create of internal Service Requests**

Functions    
- Add Activity
- Activity - attachment

**Service Request convert to global work order**
- Similar to MMC converting to Signal work order

**Update Work Order functionality:** time/labor tracking, materials tracking/specification tracking

**Process changes**
Signal engineers start creating Signal Work Orders
- [x] **Set up Builder Huddle** (John, Amenity, Surbhi)
  - [x] **Create Technical Review of Requirements**
  - [x] **See these notes to [Create Technical Plan](https://docs.google.com/document/d/1Q6HvFHGqUruBI6ccdljscPUfrIGNJ2VSvyW8KHVrNwc/edit#heading=h.2dpn7q735twr)**
- [ ] **Schedule Review with stakeholders - 2 weeks: propose the plan/set timelines**

**Comment by johnclary** [comment]
Notes from this meeting [here](https://docs.google.com/document/d/1Q6HvFHGqUruBI6ccdljscPUfrIGNJ2VSvyW8KHVrNwc/edit#heading=h.2dpn7q735twr).
