### ISSUE TITLE
Feature request: TIA Folder Status Updates (NN)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#2631]
### As a TIA reviewer, I need the folder statuses to make sense, and better align with how we are using the TIA folder. 

**Stakeholders:** Sangeeta, Nazlie
**DTS Manager:** Nate

**Acceptance Criteria:**
- At initial folder creation, fees do not insert
- At initial folder setup/creation, the status should be **Pending**
    - This is already happening (per Sree)
- After fees have been billed, the status should be **Pending Payment**
- After fees have been paid, the status should be **Paid**. This should not require user action. 
- On Submittal Intake Process, when 'Complete' attempt is saved, folder status updates to **Approved**

**Questions:**
- Are the fees the system inserts during folder insert providing value, or are they deleting them? 
- At what point in the real-life TIA workflow are fees collected? How many times are fees collected?
    - For example, many permitting processes have application fees and approval fees which are billed and paid at different times throughout the review.

**Comment by TracyLinder** [comment]
Prioritization From Customer:

![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/5e9c79bd-0167-4b50-a290-9c8154427a43)

**Comment by TracyLinder** [comment]
Will begin analysis on this w/ Sree & Nate today at 4pm.

**Comment by TracyLinder** [comment]
@Nadin-Nader please work w/ stakeholders to answer questions in the description.

**Comment by Nadin-Nader** [comment]
Sent email to Sangeeta and Nazlie:

> Sangeeta/Nazlie,
> 
> Hope you are both doing well and staying safe. I was reaching out to you regarding the TIA Folder Status Updates #2631. We were looking over this and scoping it  with Sree and came u with a few questions we needed answers to. If you would please look over them and send us the answers so we can have Sree work on this.
> 
> •	Are the fees the system inserts during folder insert providing value, or are they deleting them?
> •	At what point in the real-life TIA workflow are fees collected? How many times are fees collected?
> o	For example, many permitting processes have application fees and approval fees which are billed and paid at different times throughout the review.
> Also can you please look over the requirements to see if they are correct and what you are looking for. I have pasted them below. Please add any notes you think will help or need to add.
> 
> •	At initial folder setup/creation, the status should be Pending
> o	This is already happening (per Sree)
> •	After fees have been billed, the status should be Pending Payment
> o	Option: Use 'Calculate Fees' attempt on Initial Intake, this would add any missing fees and create one bill for all fees on fee tab. First we'd need to make sure the system isn't adding unnecessary fees. Then folder status would update to Pending Payment
> o	Currently, "Entered" attempt checks if the completeness check fees have been paid, and closes the attempt.
> •	After fees have been paid, the status should be Paid. This should not require user action.
> •	After the memo is approved, the status should be Approved
> o	Saving 'Approved' attempt on TIA Case Manager review process currently issues the folder, and updates status to Approved & Released.
> Once I get that information, we will have a better idea of what will be needed to be done and the time frame to get this completed for you.
> Thank you for your time.
> 
> Respectfully,
> 
> Nadin A. Nader 
> IT Business Systems Analyst
> Data and Technology Services 
> Austin Transportation Department

**Comment by Nadin-Nader** [comment]
Sent another email asking for an update:

> 
> From: Nader, Nadin 
> Sent: Tuesday, June 9, 2020 1:56 PM
> To: Jain, Sangeeta <Sangeeta.Jain@austintexas.gov>; Saeedi, Nazlie <Nazlie.Saeedi@austintexas.gov>
> Cc: Linder, Tracy <Tracy.Linder@austintexas.gov>
> Subject: RE: TIA Folder Status Updates #2631 Questions
> Importance: High
> 
> Hi Sangeeta and Nazlie,
> 
> Hope you both are doing well. I was reaching out again to see if you were able to answer the questions and go over the requirements?
> 
> If you have not and would like to set up a meeting to discuss this further, just let me know what day and time works for you this week.  As of right now I have available, 9-10am tomorrow 6/10/2020 , Thursday 6/11/2020, 9am-1230pm open.
> 
> Please let me know what works for you. The sooner the better as our developer is waiting for an update to continue working.
> 
> Respectfully,
> 
> Nadin A. Nader 
> IT Business Systems Analyst
> Data and Technology Services 
> Austin Transportation Department

**Comment by Nadin-Nader** [comment]
Notes from #2631 with responses from Nazlie bolded and quoted:


From: Saeedi, Nazlie <Nazlie.Saeedi@austintexas.gov> 
Sent: Tuesday, June 9, 2020 4:30 PM
To: Nader, Nadin <Nadin.Nader@austintexas.gov>
Cc: Linder, Tracy <Tracy.Linder@austintexas.gov>; Jain, Sangeeta <Sangeeta.Jain@austintexas.gov>
Subject: RE: TIA Folder Status Updates #2631 Questions

Hello,

Below are our responses in red.

Let us know if you have any additional questions.

Thanks,

Nazlie Saeedi, P.E.
Transportation Development Engineer – Lead (Central)
Transportation Development Services Division
Austin Transportation Department
901 S. MoPac Expressway, Building 5, Suite 300
Austin, TX  78746
(512) 974-4073
nazlie.saeedi@austintexas.gov
Transportation Development Services Division Website

*Out of an abundance of caution, the Transportation Development Services Division is working remotely. We are committed to completing reviews and projects in a timely manner and will remain available to the public and development community. Please continue to reach out to us via email (preferable) or our desk lines with any development related questions. In order to ensure health and safety of the citizens of Austin, we are moving from in-person-meeting setting to online meetings for the next few weeks.         

From: Nader, Nadin <Nadin.Nader@austintexas.gov> 
Sent: Tuesday, June 9, 2020 1:56 PM
To: Jain, Sangeeta <Sangeeta.Jain@austintexas.gov>; Saeedi, Nazlie <Nazlie.Saeedi@austintexas.gov>
Cc: Linder, Tracy <Tracy.Linder@austintexas.gov>
Subject: RE: TIA Folder Status Updates #2631 Questions
Importance: High

Hi Sangeeta and Nazlie,

Hope you both are doing well. I was reaching out again to see if you were able to answer the questions and go over the requirements?

If you have not and would like to set up a meeting to discuss this further, just let me know what day and time works for you this week.  As of right now I have available, 9-10am tomorrow 6/10/2020 , Thursday 6/11/2020, 9am-1230pm open.

Please let me know what works for you. The sooner the better as our developer is waiting for an update to continue working.

Respectfully,

Nadin A. Nader 
IT Business Systems Analyst
Data and Technology Services 
Austin Transportation Department



From: Nader, Nadin 
Sent: Friday, June 5, 2020 3:03 PM
To: Jain, Sangeeta <Sangeeta.Jain@austintexas.gov>; Saeedi, Nazlie <Nazlie.Saeedi@austintexas.gov>
Subject: TIA Folder Status Updates #2631 Questions

Sangeeta/Nazlie,

Hope you are both doing well and staying safe. I was reaching out to you regarding the TIA Folder Status Updates #2631. We were looking over this and scoping it  with Sree and came u with a few questions we needed answers to. If you would please look over them and send us the answers so we can have Sree work on this.

•	Are the fees the system inserts during folder insert providing value, or are they deleting them? 

**> **No, they can be deleted****

•	At what point in the real-life TIA workflow are fees collected? How many times are fees collected? **

> Fees must be paid before or at the time of the first TIA submittal. Once, for two fees: TIA scoping fee and TIA review fee, as they are billed together

**
o	For example, many permitting processes have application fees and approval fees which are billed and paid at different times throughout the review.

Also can you please look over the requirements to see if they are correct and what you are looking for. I have pasted them below. Please add any notes you think will help or need to add.

•	At initial folder setup/creation, the status should be Pending
o	This is already happening (per Sree) 

•	After fees have been billed, the status should be Pending Payment
o	Option: Use 'Calculate Fees' attempt on Initial Intake, this would add any missing fees and create one bill for all fees on fee tab. First we'd need to make sure the system isn't adding unnecessary fees. Then folder status would update to Pending Payment **

**> Yes, we want this**

**

o	Currently, "Entered" attempt checks if the completeness check fees have been paid, and closes the attempt. **

**> **We don’t have a completeness check process or fees for the TIA folder****

**

•After fees have been paid, the status should be Paid. This should not require user action.
•	After the memo is approved, the status should be Approved
o	Saving 'Approved' attempt on TIA Case Manager review process currently issues the folder, and updates status to Approved & Released. 

**> After the TIA has been approved and released, we would like the folder to be removed from our task list in AMANDA**

Once I get that information, we will have a better idea of what will be needed to be done and the time frame to get this completed for you.
Thank you for your time.

Respectfully,

Nadin A. Nader 
IT Business Systems Analyst
Data and Technology Services 
Austin Transportation Department

**Comment by Nadin-Nader** [comment]
Meeting is set for 6/10/2020 at 11am

**Comment by TracyLinder** [comment]
**Status:** We should be getting a demo today or tomorrow.

**Comment by Sreelatha-BlazeKannan** [comment]
Submitted the Demo on 06/19/2020. Waiting for feedback.

**Comment by TracyLinder** [comment]
@Nadin-Nader please make time to review the demo sent to us on 6/19.

**Comment by Nadin-Nader** [comment]
- [ ] At initial folder setup/creation, the status should be Pending
- [ ] After fees have been billed, the status should be Pending Payment
              - [ ] Option: Use 'Calculate Fees' attempt on Initial Intake, this would add any missing fees and create one bill for all fees on fee tab. First we'd need to make sure the system isn't adding unnecessary fees. Then folder status would update to Pending Payment
- [ ] Currently, "Entered" attempt checks if the completeness check fees have been paid, and closes the attempt.
- [ ] Fees must be paid before or at the time of the first TIA submittal. Once, for two fees: TIA scoping fee and TIA review fee, as they are billed together
- [ ] After fees have been paid, the status should be Paid. This should not require user action.
- [ ] After the memo is approved, the status should be Approved
- [ ] Saving 'Approved' attempt on TIA Case Manager review process currently issues the folder, and updates status to Approved & Released.
- [ ] After the TIA has been approved and released, we would like the folder to be removed from our task list in AMANDA

**Comment by TracyLinder** [comment]
@Nadin-Nader I created a child issue for the promote to DEV #3263

**Comment by TracyLinder** [comment]
@Sreelatha-BlazeKannan we need to remove the tech surcharge (per meeting w/ Sangeeta today) before moving to DEV.

**Comment by Nadin-Nader** [comment]
Sent CM Team the request to have this deployed to DEV (SCTASK0081754) #3263

**Comment by TracyLinder** [comment]
@Nadin-Nader I added you as DTS Manager to this one.

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder  This has been deployed to DEV and now needs UAT on DEV for promotion to TEST

**Comment by Sreelatha-BlazeKannan** [comment]
Deployed to DEV and testing in progress

**Comment by Sreelatha-BlazeKannan** [comment]
@aishwarya2505 , @Nadin-Nader - As per Nadin this is already in DEV. Martin Deployed it today morning!

**Comment by TracyLinder** [comment]
**Status:** Will demo work to stakeholders on 7/31. Updating milestone to 30.

**Comment by TracyLinder** [comment]
Acceptance criteria has been updated.

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder , @Nadin-Nader  - Aishwarya is working on the changes

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @aishwarya2505 @TracyLinder Reviewed the demo with the added changes and in my opinion it looks good.

**Comment by TracyLinder** [comment]
@Sreelatha-BlazeKannan @aishwarya2505 The demo looks great. Please promote to DEV.

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder , @Nadin-Nader - Commited changes in DEV on 08/19 and submitted DEV deployment plan and tested the same in DEV Ready for UAT in DEV

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder @aishwarya2505 I have UATd this on DEV and found that it is working as asked. 

**Status:**
Ready for TEST then User acceptance demo

**Comment by aishwarya2505** [comment]
TEST Deployment Plan sent on 9/10/2020

**Comment by TracyLinder** [comment]
### DEV UAT Feedback

- See DEV folder ROW ID 11895327: The fee was paid and the folder status did not update to Paid. Per acceptance criteria, when fee is paid the folder status should update to Paid without any further user input. 
    - User must save attempt result 'Entered' on Initial Intake to make folder status update to Paid.

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder , @Nadin-Nader - Aishwarya will start looking into this issue.

**Comment by aishwarya2505** [comment]
Hello @TracyLinder @Nadin-Nader , I checked the mentioned folder in DEV 11895327 and the folder status was updated to "Paid" on attempt "Entered" in the Initial Intake Process. 

I created another folder in DEV , RSN11895365 and tested the entire work flow for this ticket and it worked as expected. 

Let me know if there's an issue in any other environment and I can always fix that for you. Thanks :)

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder, @Nadin-Nader - If still issue exists please send us the folderrsns to do further testing. thank you

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @aishwarya2505 @TracyLinder I have sent this to the CM DevOps Team to deploy to TEST under TASK SCTASK0101403.

**Status:**

Waiting on CTM to deploy to TEST

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @aishwarya2505 @TracyLinder this has been deployed to TEST.

**Status and Next Steps:**

UAT on TEST

**Comment by aishwarya2505** [comment]
Tested this on TEST 12396002. @Nadin-Nader @TracyLinder @Sreelatha-BlazeKannan

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @aishwarya2505 @TracyLinder I have UATd this on TEST **(RSN:12396019)** and it met all of the acceptance criteria below:

- [ ] At initial folder creation, fees do not insert
- [ ] At initial folder setup/creation, the status should be Pending
- [ ] After fees have been billed, the status should be Pending Payment
- [ ] After fees have been paid, the status should be Paid. This should not require user action.
- [ ] On Submittal Intake Process, when 'Complete' attempt is saved, folder status updates to Approved

**Comment by TracyLinder** [comment]
UAT with stakeholders scheduled for 10/29

**Comment by TracyLinder** [comment]
### UAT Results (Failed)
- After fees have been paid, the status should be Paid. This should not require user action. **This did not happen; no status change when fee was paid.**
    - User has to save attempt 'Entered' on Initial Intake to make the folder status update to 'Paid'.
        - Can the folder status update to Paid when bill is paid, instead of being on a process attempt? 
    - Users asked to take out from workflow saving 'entered' on Initial Intake... not adding value to TIA workflow

**Proposed Workflow:**
1. 'Initial Intake' is inserted
2. User saves 'Calculate fees' attempt
    - System deletes existing unbilled fees
    - System updates folder status to 'Pending Payment'
    - System inserts & bills the correct fees
    - System closes 'Initial Intake Process'
    - System inserts 'Submittal Intake Process'
3. Fee/Invoice is paid
    - System Updates folder status to 'Paid'
4. User saves 'Complete' attempt on 'Submittal Intake Process'
    - System issues folder, updates status to 'Approved'


@Sreelatha-BlazeKannan let's discuss this afternoon when we speak.

**Comment by aishwarya2505** [comment]
The demo for the revised AC has ben sent for review on 11/2/2020. 

Need clarification on one question: 

Do we remove the attempt "Entered" from the Initial Intake Process?

If you aren't sure on removing it but don't want the user selecting it at this point, we could throw in an error message that reads . "Not a valid attempt for this process". 

@TracyLinder @Nadin-Nader @Sreelatha-BlazeKannan

**Comment by TracyLinder** [comment]
### UAT in DEV Passed, Ready to promote to TEST

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @aishwarya2505 @TracyLinder per our meeting this has passed UAT and is ready to be deployed to PROD

**Comment by Nadin-Nader** [comment]
## **Approved for Deployment to PROD🎉🎉🎉!!**

**Comment by Nadin-Nader** [comment]
@aishwarya2505 @Sreelatha-BlazeKannan @TracyLinder I have sent this to the DevOps CM Team for PROD deployment under **SCTASK0105644**

## **Status:**
Waiting on Promotion to PROD by the DevOps CM Team

**Comment by TracyLinder** [comment]
This is done; closing issue;
