### ISSUE TITLE
Knack: Synchronize Data Tracker Tables

### ISSUE THREAD

**Issue by sergiogcx** [cityofaustin/atd-data-tech#276]
We need to consider the possibility to break down Knackpy or write a different application that:

- [ ] Syncs two tables with attachments.
- [ ] Synchronize two tables with attachments.
- [ ] One way sync between the two tables.
- [ ] Does not mess with Austin Transportation Data Tracker / Production environment (Create Test Env)
- [ ] Handles file attachments (images)
- [ ] Inserting records with file attachments
- [ ] Knackpy needs a method to download the file.

This issue will be edited as more requirements arise. Perhaps it could be broken down into an Epic and multiple issues.
