### ISSUE TITLE
VZA Work Session: Officer UX, reference map, and signals scheduling 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#2782]
### Objective 
Review Officer UI and make any refinements necessary before demonstrating to Pat.
- [x] _Sign Up_, _My Assignments_, and sign up workflow
- [x] Cancellation workflow 
- [x] On-assignment workflow

Other:
- [x] Decide how to store/reference signal locations, see #2700 
- [ ] ~Discuss potential improvements to VZA reference map #1306~ 
- [ ] ~Decide how Officer accounts are created (import, self-register, admin-created after a training, etc.)~ added to #2566 

### Participants
Surbhi, Diana, Amenity

------
- [x] Meeting - 6/1/20
- [x] Meeting - 6/2/20
- [x] Create resulting issues

**Comment by dianamartin** [comment]
## Diana's Notes

Discussion - Officers create an account
## Officer tabs
**Sign up**

**My Assignments**
- Calendar
- Assignments Table View
  - One for reach shift assignment

**Comment by amenity** [comment]
For the search table format instead of filters on the Sign-Up table: 
- Sectors (multi-select)
- From (date-picker) 
- To (date-picker)

When they cancel a shift, do we need to use the "Sign Up" form? Does that mean "Notes for cancelling" will always show on the details page? 

Ideally clicking the "Remove" icon from the "My Assignments" table takes user to a modal or new page
> Why won't you be able to work this assignment on ______? 
>
> [text field for explanation] 
>
> [ ] I have read the [SEU Cancellation Policy](https://docs.google.com/document/d/16S8eMTLPapQWFcOIDU6TnB3UNUs8j7uToceAx6kJ1jw/edit#heading=h.6uhjg7i3iw3e) and understand that by cancelling this assignment with less than 48 hours notice I am responsible for finding another Officer to work the shift or risk losing eligibility for SEU assignments.  
>
> **Remove me from this assignment** <--button

**Comment by SurbhiBakshi** [comment]
Notes from second session - 

Sign up - 
- **Search Table** 
- [ ] Remove Keyword Search
- [ ] Date From
- [ ] Date To
- [ ] Remove Export function
- [ ] Sign Up icon same as the one used on the Page Menu

- **Unavailable Assignments**
- [ ] Change Unavailable Assignments to Filled Assignments

**My Assignments** 
- Create table Today's Assignments 
- [ ] Fields same as earlier My Assignments table, except the details on this one will open to let the officer record in the assignment.

- **Future Assignments**  renamed from My Assignments
- [ ] same as before, except details will open in a modal and not be editable.

**Calendar**
- [ ] Show Assignment Location only

**Assignment Records when on the shift.**
- [ ] Start Assignment button becomes bigger, use a triangle as the icon
- [ ] Move End Assignment to the bottom of the page, use a square as the icon.
- [ ] Assignments Details - do we need to include Team and Assignment Number ? these were mainly for Randy's benefit.
- [ ] Notes will morph into two notes with two types - 
1. No Violation Observed
2. Observation / Cause for Concern
Officer will have to select one of the two options and then record note.

- [ ] Will need to change the Notes table below to show Type of Note.
(Jen would like to see these notes, need to make those available in the Viewer interface)


- [ ] Back to Assignments button needs to be made bigger.
