### ISSUE TITLE
LaunchIT DO

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#2807]
### IT Purchasing approved this contract on 8/19/20. 
- Contracts located [here](https://drive.google.com/drive/u/1/folders/1ah5oWXsycKxoMXhiIN2rmQ9XJfakR7GC)

**Tasks to Complete**

- [x] Get estimate from LIT
- [x] Submit Service Now ticket
- [x] Send quote feedback/updates to Raj
- [x] Request approval (from finance) to update monthly budget by $3k for LIT PM hours
- [x] Send updated quote to David B
- [ ] ?

**Service Now #: REQ0051258, submitted 6/2/20**
**Purchase Request PR0011296 **

**Comment by TracyLinder** [comment]
**Email 5/26:**
Hi Raj,

ATD finance is going to request a new DO for your services, and for that we’ll need a quote from LaunchIT. The quote will need to cover monthly estimates for ATD’s work from June through December please. 

Do you think that’s something you can have prepared by the end of the week? Let me know if you’d like a call to discuss. 

All the Best,

Tracy Linder, Product Manager

**Comment by TracyLinder** [comment]
The Service Now ticket was submitted today at 5pm.

**Comment by TracyLinder** [comment]
**Email From CTM:**

Good Morning Tracy,

 

This purchase will require the vendor to list a DIR contract number on the quote. Additionally, the quote should include a “not to exceed” amount for the SOW. Please send me a revised quote when you have it in hand.

 

The PR you reference isn’t actually with Launch IT. It is with a company called Sistema Technologies, Inc. I suspect it was processed this way, because Launch IT is unable to directly sell its services via the TX DIR contract.

 

Thank you,

 

David B

IT Support Analyst

Communications and Technology Management

City of Austin

**Comment by TracyLinder** [comment]
**Status:** Next steps, respond to David's email, get quote updated & signed.

**Comment by TracyLinder** [comment]
**Email to Raj, a few minutes ago:**

Hi Raj,

Please accept my apologies for the delay in providing an update on this. I've attached the quote with a handful of changes, which were tracked for your review in the document. There are three other updates needed to the document; please see the list below and let me know if you have questions/comments. 
- Quote must include the DIR contract number
- Add a "not to exceed" amount of $180,000
    - This limit was set recently by our CAO
- Update the monthly payment due to $33k

All the Best,
Tracy Linder, Product Manager

**The quote I attached is [here](https://drive.google.com/file/d/12Vt7rMfsvClnXk-eOMV9ZrLOzUqs-tt5/view?usp=sharing).**

**Comment by TracyLinder** [comment]
**Conversation w/ Raj Today re: Quote | 4pm | Recap**

- Include June - December
- Current approved monthly budget is $33k
- Raj requested increasing monthly budget to $36k, to cover LIT PM costs
    - Tracy to request finance approval
- Not to exceeds @ $36k is $252k

**Comment by TracyLinder** [comment]
I emailed Peggy after my call w/ Raj, requesting approval to increase monthly budget by $3k.

**Comment by TracyLinder** [comment]
### Update

- Peggy approved the funding increase this morning
- I emailed Raj w/ the update, and asked him to send me the updated quote

**Comment by TracyLinder** [comment]
### Update 6/12/20

- Raj sent me the updated quote this afternoon
- I responded with this question:
    - From the quote: _"Based off initial discussions, ATD will be provided with Launch IT resources for a minimum of 166 hours per month."_ **Question: Is this 166 hours total, or per resource?** 
- I sent the updated quote to David B @ CTM, asking what the next steps are
    - Doc sent to David is [here](https://drive.google.com/file/d/1jg1f-UDshzVFq1di6UH-tqwXF7fL_Z21/view?usp=sharing)

**Comment by TracyLinder** [comment]
### Update

Purchasing rejected the quote because LaunchIT doesn’t have authority to do business under the DIR contract with Sistema that we’re using for this engagement. Raj w/ LaunchIT expects to send me a new quote from Sistema tomorrow, and we’ll get it pack to purchasing.

**Comment by TracyLinder** [comment]
### Update

PR0011296 was assigned to Jane N. on 6/22. I sent the email below to her today :


Hi Jane, 

I see that this has been assigned to you. This is my first PR request since 2010 when we still used a paper form, so I’m unfamiliar with the process. Can you please inform me of the next steps?

All the Best,

Tracy Linder, Product Manager

**Comment by TracyLinder** [comment]
**Email sent to Peggy today:**

Hi Peggy,

The LaunchIT PR was assigned to IT Purchasing on 6/22. I sent the email below on 6/30 and haven’t gotten a response. Who can we escalate this to, or can you help?

Thanks,

Tracy Linder, Product Manager
Data & Technology Services 🚲 Austin Transportation

**Comment by TracyLinder** [comment]
The IT Purchasing review was reassigned on 7/14 to Darralyn J.

**Comment by TracyLinder** [comment]
**Update Provided Today to Dan V. (ATD) & David D (DSD):**

Hi All,

I’ve got a DO in progress currently for ATD’s engagement with LaunchIT (all info about this is captured here). It’s been in IT Purchasing review since 6/22. The PR # is PR0011296.

Dan, please see the attached email where I asked Peggy for assistance with this. I’m not sure if she has done anything with it yet, but I did notice the service now ticket was re-assigned yesterday to a different IT Purchasing staffer. 

Thanks,

Tracy Linder, Product Manager
Data & Technology Services 🚲 Austin Transportation
————————————————————————

**Comment by TracyLinder** [comment]
### Update

- IT Purchasing began their review on 8/3/20
- To date, we have provided all requirements IT Purchasing has requested of us
- See [this email](https://github.com/cityofaustin/atd-data-tech/files/5065930/LIT.PR.Email.Update.pdf) regarding recent communications
