### ISSUE TITLE
Feature request: Enhancements to Damage Reports module

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#2843]
## Overview
Damage Reports are created so that
- ATD can recoup the cost of damaged equipment and labor for repairs
    - AMD creates an invoice for Legal
    - Legal files a claim with insurance company for reimbursement
- AMD can improve budgeting
    - Know the total cost of replacing damaged equipment - _Being as that it is time-consuming to keep up with damage reports, is this something we can capture this on the work order instead? Probably not: We cannot rely on technicians to provide accurate data_
- Future state: Aggregated reporting to drive policy and resourcing, e.g.
    - What % of damages are eligible for reimbursement?
    - What % of reimbursements are realized?
    - How might we improve ROI on Damage Report processing

### Request
Several enhancements to AMD Data Tracker [Damage Reports](https://data.mobility.austin.gov/data-tracker/#home/damage-reports/): 
- Ability to apply different indirect cost percentages based on the year of the work ticket. 
- Upload PDFs 
- Additional _Status_ field options 
- Overall layout updates to improve usability

### Users
- AMD - Construction group
- Financial (possible reimbursement estimates)

### Enhancement 4: Reformat Layout of Edit Form
- **APD INFORMATION** (How many APD Reports? 15-20 tickets per month, 5-7 only have APD Reports)
  - APD Report - Y/N
  - Have a APD number
  - Upload an APD File (New field!)
  - `At Fault Identified` - only with APD Report
- **INSURANCE INFORMATION**
  - Insurance Info - Y/N
  - Should not be seen if no APD Report
- **AMD Work Ticket**
  - Work Ticket - Y/N
  - Task Order is added if Work Order Ticket is `Y`
  - Link `Work Ticket` here (suggestion)
  - Collisions/Knock down - that gets reported by APD
  - Task Order Report (backup labor report created manually - MicroStrategy) 
  - `Interdepartmental Charges` (haven't used it in awhile, pay APD)
- **ADMIN TRACKING INFORMATION**

### Change: Need more statuses or new field that has Review
- Active - Compiling Information
- [x] `Admin Review` change to `Ready to Review` - Scott's turn to review
- [x] `Review Completed` - (New status!) 

Field is populating date: `Send to Legal Date` - should be blank
- Date is already populated
- [x] Should be blank

Field `Contractor Invoice` 
- Why is there an `N/A`?  Should we remove this?

Field `Contractor Cost` - Upload attachments for Contractor cost documents (.pdf) 
- 1 document 

Field `Task Order`
- There might be more than task order
- Follow up work - need to add more task orders

### Update Damage Report table
- [x] Add `Work Ticket Number`
- [x] Add `APD Report` - Y/N  

### Friday Action Items
- [x] Organize Damage Report Details
- [x] Organize Edit Form (hiding fields that don't need to be shown)
- [x] Indirect Cost research (calculation or open field)

**Comment by dianamartin** [comment]
## Before - Details Page
### Top Part
![image](https://user-images.githubusercontent.com/21112975/83296831-0993f500-a1b7-11ea-9848-5c2dd826efd6.png)
![image](https://user-images.githubusercontent.com/21112975/83296885-24ff0000-a1b7-11ea-80fd-68cd863bedb0.png)

## Before - Edit Page
![image](https://user-images.githubusercontent.com/21112975/83296958-49f37300-a1b7-11ea-8963-8b41dba8009b.png)

**Comment by dianamartin** [comment]
## After - Detail Page
![image](https://user-images.githubusercontent.com/21112975/83312108-ea0cc480-a1d6-11ea-958d-d561acb264bf.png)
![image](https://user-images.githubusercontent.com/21112975/83312126-f729b380-a1d6-11ea-961d-3fe1b0ef454b.png)

## After - Edit Page
![image](https://user-images.githubusercontent.com/21112975/83312165-0dd00a80-a1d7-11ea-8177-53b66161f506.png)

### Added Attachments form/table to Edit Form, made Forms smaller buttons above tables
![image](https://user-images.githubusercontent.com/21112975/83312190-1e808080-a1d7-11ea-9f22-2fdb605d9f7f.png)

**Comment by dianamartin** [comment]
Emailed user and product manager of all enhancements that were done last Friday

>Thanks for talking to me and Amenity last Friday about your pain points regarding the Damage Report module in the Data Tracker. I was able to get a lot of the enhancement items you requested finished. Mainly, I was going to work on tackling: 

>**Enhancement 4: Reformatting of the Damage Report table, Damage Report details, Edit form and Print Review pages.** 
•	Not only did I change up the formatting on those pages

>**Damage Report details**
•	Reformatted layout
•	Move buttons (Work Orders) to the top of the page
•	Created button (Edit Cost & Reimbursement) placed at top of the page
**Edit Form**
•	Reformatted layout
•	Added new field (Task Order #2)
•	Made field (Sent to Legal Date) not show current date anymore
•	Made (Edit Form) smarter by hiding fields that are logically connected to each other. If field is “No”, other related fields don’t show up)
•	Created a new Edit Form for (Edit Cost & Reimbursement) so the Edit Report form wasn’t super long
•	Added Attachments Form and Table to Edit Form

>But I was also able to get to: 
**Enhancement 1: I addressed the “Indirect Cost” issue.**
•	I added a field so that you can add the ATD Indirect Cost percentage. (Found on the Edit Cost & Reimbursement form)
•	 ![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/0349987c-d5a0-4ce7-9c49-ffd0e25a8908)
Cost Summary on Damage Report details (looks like this right now)
•	 ![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/4e9a67c2-a5c0-4fb3-a222-f0a54abc7dd4)
**Enhancement 2: Multiple attachment functionality.** 
•	Added a related Damage Reports – Attachments form/table on the Edit Form and the Damage Report details page
What it looks like on the Edit Form
•	 ![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/e37852d5-4b1f-4957-8708-5075d692ef1c)
New Attachment form
•	 ![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/23ce6405-d4b2-4f6f-9681-dd2f3e9e7d37)
Attachment Types
•	 ![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/5b1862aa-e3af-48d5-82dd-d11926aab597)
**Enhancement 3: Create Damage Report Invoice page**
•	The only thing that is outstanding and left to do. I’ll just need your feedback on what you want this to look at, I can show you some of our invoice page examples if you’re interested or if you already have an idea you can share with me what you want this page to look like. 

Take a look and let me know if you have any changes.

**Comment by dianamartin** [comment]
@amenity can we close this?

**Comment by amenity** [comment]
@dianamartin Yesss! Great work.🙌
