### ISSUE TITLE
Follow up on AMD Data Tracker Damage Reports enhancements

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#2853]
### Objective 
Review [enhancements](https://github.com/cityofaustin/atd-data-tech/issues/2843) made to Damage Reports module and determine what further functionality we should spec out for future work. 

### Participants
Diana, Amenity, Ivonne
Optional: John, Andres Z, Scott F

### Agenda
- Ivonne walk through new workflow
- Do we need to have a compiled PDF in addition to the APD report, or can we just have links to other Data Tracker pages and the ability to upload PDFs for the APD report and vendor invoices?

------
- [x] Schedule meeting
- [ ] Optional: Schedule debrief
- [x] Meet and take notes
- [ ] Optional: Debrief with DTS team members
- [ ] Create resulting issues

**Comment by dianamartin** [comment]
@amenity Did you hear back from Ivonne?

**Comment by dianamartin** [comment]
## Diana's Notes
### Damage Report table
- [ ] `Work Order ID` - link to Work Order details

### Damage Report details
- Change attachment table  - Created By- Created Date - change to `Uploaded By`, `Uploaded Date`

### Edit Report
- [ ] `Attachment Damage` button - rename to "Add Attachment"
- Description (not required)
  - [ ] If `Other`, show `Description` otherwise hide it in display rules
- Sent to Legal Date - has already been changed to not show the current date

### Edit Cost & Reimbursement form
- Add `ATD Indirect %` - reference percentage
- [ ] Clean up `ATD Indirect` - Closed (snap shot of indirect)
  - 2017 (1.5%) - Closed
- [ ] Total Cost % - Change to currency

### Print View details
- Replacement Equipment - manual entry 
- Inventory section in work order 
  - there's not an easy way to do that

### Damage Report Reports
- Need to change this in the future?
- Annual Equipment Costs for Knockdowns - report for Scott
  - asking Scott to send the report

**Comment by dianamartin** [comment]
@amenity I created a new issue to do the refinements

**Comment by amenity** [comment]
**Participants**

*Diana, Amenity, IvonneOptional: John, Andres Z, Scott F*

**Data point:** For FY16 and FY17, damaged equipment totaled $168,702k; estimate that 15-20% of the incidents are eligible for reimbursement (equipment + labor)

### Feedback on refinements

[Details page](https://data.mobility.austin.gov/data-tracker/#home/damage-reports/view-damage-report-details/5ed143f86f3ac10015ed2755/) 

- Attachments
    - "Created" —→ "Uploaded"

[Edit Report](https://data.mobility.austin.gov/data-tracker/#home/damage-reports/view-damage-report-details/5ed143f86f3ac10015ed2755/edit-cost--reimbursements/5ed143f86f3ac10015ed2755/) 

- "Attachment Damage" —→ "Add Attachment"
- Hide "Description" unless "Other" is suggested for Attachment Type
- Add reference list of the indirect cost for each fiscal year

[Damage Reports page](https://data.mobility.austin.gov/data-tracker/#home/damage-reports/)

- Work Order ID = hyperlink to WO detail page
- Remove "Description" column

[Cost Summary on Print View](https://data.mobility.austin.gov/data-tracker/#home/damage-reports/view-damage-report-details/5ed143f86f3ac10015ed2755/print-damage-report/5ed143f86f3ac10015ed2755/)
- Only total $ amount of indirect cost needs to be shown
- Scott mentioned adding breakdown - equipment, contractor — not sure why
- Would it be helpful to show empty fields to spot check what's missing, compare reports consistently, etc.?

**Data housekeeping** 

- Set indirect % to 1.5 to all closed damage reports and delete old field

**Comment by amenity** [comment]
@dianamartin - super. I just added one task to your refinements. Also made [this into an epic](https://github.com/cityofaustin/atd-data-tech/issues/2843) for all these issues.
