### ISSUE TITLE
Migrate RPP Data into RPP Portal

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#2856]
- [x] Review RPP Tracking spreadsheet
- [x] Determine level of effort for importing historical records
- [x] Test Import
- [ ] Import Records for Go-Live?

**Comment by dianamartin** [comment]
Called Steve to get some background on the RPP Tracking Spreadsheet

- Have to create customer records
- Have to create app records?
- Have to create permit records

Zone Colors to Test (order of smallest to largest)

- [ ] Blue - 55
- [ ] Purple - 78
- [ ] Teal - 237
- [ ] Green - 242
- [ ] Pink - 342
- [ ] Red - 511
- [ ] Orange - 731

**Comment by dianamartin** [comment]
- [x] Reformatted excel spreadsheet (BLUE tab) and Saved As `Customers_BLUE_25`, imported those customer records in
- [x] Reformatted excel spreadsheet (BLUE tab), excluding any unpaid permits, imported those records in as permit_applications. 
- [x] Manually Issued permits based on excel spreadsheet (BLUE tab), got through 5 records

#### To Do - 6/2/2020
- [ ] Reformatted excel spreadsheet (BLUE tab) into permit records
- [ ] Test import the permit records to see how easy it is to create

**Comment by dianamartin** [comment]
#### To Do - 6/11/2020
- [x] Import Teal Zone customer records - `Completed - `
- [ ] Export Teal Zone customers not associated with an application
- [ ] Reformat Permit Application spreadsheet
- [ ] Import Permit Application spreadsheet
- [ ] Reformat Purple Teal Permit spreadsheet
- [ ] Import Purple Teal Permit spreadsheet

**Comment by dianamartin** [comment]
#### To Do - 6/24/2020
- [x] Import Green Zone customer records - `Completed - 6/24`
- [ ] Export Green Zone customers not associated with an application
- [ ] Reformat Permit Application spreadsheet
- [ ] Import Green Permit Application spreadsheet
- [ ] Reformat Green Teal Permit spreadsheet
- [ ] Import Green Teal Permit spreadsheet

**Comment by ChrispinP** [comment]
Documentation is about 2/3rds done in being updated and accurate to facilitate efficient process moving forward. Templates and folder organization is also underway.

Green Zone is now complete and ready for import. Pink Zone was started last week and now will be primary focus.

**Comment by amenity** [comment]
@ChrispinP - please add other data you're importing to this epic🙏

**Comment by moorerst** [comment]
@ChrispinP emailed both Steve and Jacob. Per Steve I would say with all the Zones having gone through the Renewal process since Knack’s implementation, that the data migration from the spreadsheets wouldn’t be necessary anymore. That’s my thought process on it. 

Let wait a day or two to see if Jacob has a different opinion. If not we can close the migration issues early next week. Thanks

**Comment by ChrispinP** [comment]
no further action needed, closing
