### ISSUE TITLE
Update PPE request status category

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#2878]
Under the PPE request status categories, please change the word `Pending Distribution` to `Approved for Distribution`. Currently, Gilda is the only one that is reviewing the request and approving for distribution so once she reviews it, she clicks on `Pending Distribution`. She has requested that is be changed to `Approved for Distribution`.

![download.png](https://images.zenhubusercontent.com/5dc05535495c1e0001182c16/3c0baef8-f64c-4e68-ae0d-744a74ba2254)

**Comment by dianamartin** [comment]
- [x] Changed the `PPE Request Status` from `Pending Distribution` to `Approved for Distribution`
- There was only 1 record that was in a **Pending Distribution** status
- [x] Changed 1 record from **Pending Distribution** to `Approved for Distribution`
- [x] Changed filter on PPE Request table from **Pending Distribution** to `Approved for Distribution`

![image](https://user-images.githubusercontent.com/21112975/83589099-88bb5d00-a518-11ea-9785-12502af44e69.png)
