### ISSUE TITLE
Create Signal Locations object in VZA App and import from Data Tracker

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#2879]
Create a Signal Locations object in the VZA App
Display Name | Description | Location Type | Status | APD Sector | Council District
-- | -- | -- | -- | -- | --
Calculated field | Short Text | Multiple Choice(?) | Multiple Choice | Multiple Choice | Multiple Choice

- [x] Add signal locations to object and additional field on location type (signal/vza)
- [x] Configure a second form to add a signal assignment and a new button 
![Screen Shot 2020-11-12 at 11 59 11 AM](https://user-images.githubusercontent.com/1463708/98978163-2a3ed580-24df-11eb-999b-57c65e98e07f.png)

**Comment by amenity** [comment]
@SurbhiBakshi - once this is complete, please let @johnclary know and block off three hours on his schedule to do 

Note that if the field names match Data Tracker it makes the import easier.

**Comment by SurbhiBakshi** [comment]
**### To Do List**

- [ ] Rename `Add Assignment` form to `Add VZ Assignment`
- [ ] For Record Rules under Form Rules, set `Assignment Type` for all records created using this form to `Vision Zero`
- [ ] For Location, set the Filter - `Location Type` to `Vision Zero`
- [ ] Create a new form page from the Add Assignment Menu to create an assignment for Signal Engineers- [ ] Rename `Add Assignment` form to `Add VZ Assignment`
- [ ] For Record Rules under Form Rules, set `Assignment Type` for all records created using this form to `Vision Zero`
- [ ] For Location, set the Filter - `Location Type` to `Vision Zero`
