### ISSUE TITLE
Builder Huddle: PHB Ranking Refactor

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#2890]
Size the implementation of #2785 
- [x] Schedule meeting
- [ ] Meet and attach notes to issue
- [ ] Size implementation and add to AMD Product Prioritization agenda
- [ ] Follow up with Renée
