### ISSUE TITLE
Damage Report Refinements from follow-up feedback meeting

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#2945]
### Damage Report table
- [x] `Work Order ID` - link to Work Order details
- [ ] Remove `Description` column - not necessary on this view and can be very long
  - Talked to Ivonne, she said to leave it so she can determine if she really wants it removed or not.

### Damage Report details
- [x] Change attachment table  - Created By- Created Date - change to `Uploaded By`, `Uploaded Date`

### Edit Report
- [x] `Attachment Damage` button - rename to "Add Attachment"
- Description (not required)
  - [x] If `Other`, show `Description` otherwise hide it in display rules
- Sent to Legal Date - has already been changed to not show the current date

### Edit Cost & Reimbursement form
- Add `ATD Indirect %` - reference percentage
- [x] Clean up `ATD Indirect` - Closed (snap shot of indirect)
  - 2017 (1.5%) - Closed
- [x] Total Cost % - Change to currency

>Indirect cost
2016  1.63%
2017  1.50%
2018  1.47%
2019  1.73%
2020  1.81%

### Print View details
- Replacement Equipment - manual entry 
- Inventory section in work order 
  - there's not an easy way to do that

### Damage Report Reports
- Need to change this in the future?
- Annual Equipment Costs for Knockdowns - report for Scott
  - asking Scott to send the report

**Comment by dianamartin** [comment]
## Clean up ATD Indirect - Closed (snap shot of indirect)
- [ ] Change all `Closed` Statuses to `2017 (1.5%)` - ATD Indirect Cost

Inventory 
Name | Count
-- | -- 
All | 293
Active | 95
Admin Review | 39
Submitted to Legal | 37 
Closed | 121
Void | 1

**Comment by dianamartin** [comment]
@amenity did you already add the task to this issue? I'm pretty much done now. Just wanted to see if I could close it.

**Comment by amenity** [comment]
Yes, @dianamartin ! It was just removing the `Description` column.
