### ISSUE TITLE
TIA Module: Usability Testing

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#3010]
### This is the epic for usability testing. 
[Usability Testing Folder](https://drive.google.com/drive/u/2/folders/15z5HvRsfmZUEVT-rjRtUcbYVEEZUAKm1)

**Comment by TracyLinder** [comment]
### Status/Update
- [ ] Usability with internal reviewers
- [ ] Usability with external reviewers
- [ ] Reporting usability with TIA managers
