### ISSUE TITLE
Publish Core Signs and Markings data to the Open Data Portal

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-data-tech#3114]
Published datasets:
- [Markings Work Orders](https://data.austintexas.gov/Transportation-and-Mobility/Roadway-Markings-Work-Orders/nyhn-669r)
- [Sign Work Orders](https://data.austintexas.gov/Transportation-and-Mobility/Street-Sign-Work-Orders/ivss-na93)
- [Markings Jobs](https://data.austintexas.gov/Transportation-and-Mobility/Roadway-Markings-Jobs/vey3-7n3x/)
- [Time Logs](https://data.austintexas.gov/Transportation-and-Mobility/Street-Signs-and-Roadway-Markings-Work-Order-Time-/qvth-gwdv)
- [Signs/Markings Reimbursements](https://data.austintexas.gov/Transportation-and-Mobility/Street-Signs-and-Roadway-Markings-Reimbursements/pma8-yy5k)

**Comment by SurbhiBakshi** [comment]
**Prep for Discovery Day** 
- [ ] Install Homebrew
- [ ] Install Python 3
- [ ] Install MiniConda
- [ ] Install Visual Studio
- [ ] Install VS Python extension
- [ ] Set up dataset in the Open Data Portal

**Comment by johnclary** [comment]
Great. I suggest playing around with a few of the `sodapy` examples. See if you can upsert data, as described here: https://github.com/xmunoz/sodapy#upsertdataset_identifier-payload-content_typejson

And feel free to add something on my calendar for pair programming.

**Comment by SurbhiBakshi** [comment]
1. Specification Counts Table - view_3304
2. Reimbursable Trackings - view_3305
3. work_orders_signs_markings_time_logs - view_3307

**Comment by johnclary** [comment]
@SurbhiBakshi send me the dataset configuration info when possible.

**Comment by SurbhiBakshi** [comment]
@johnclary - Here is the [dataset configuration info](https://docs.google.com/spreadsheets/d/1aZEXR9Udi9-pgg_qtBF6JxxUZ1Hlx3fhp-eEalVk4ME/edit?usp=sharing). After our discussion at Apps Sync yesterday, I looked at the field names to see if there could be any potential issues. 
The first view seems fairly straightforward. 
The other two have some potential problems with field names from Knack not aligning with Socrata. I highlighted those in the spreadsheet for the second one. 
I  think the third view might be the most complex.

**Comment by johnclary** [comment]
Thanks @SurbhiBakshi 

I have completed the setup for Specification Counts Table. A few things to note that I failed to mention.

#### Field names

The Socrata API field names need to match the field name in the Knack object, not the view. Re-naming a field _in the view itself_  has no effect on this process. This is a limitation of the Knack API, not my scripts ;)

And I'll repeat the caveat that the Knack field name does not have to be lower case, and spaces will be replaced with underscores. So, if your field in Knack is  "Asset Name", your field in Socrata should be "asset_name". The field's "Display Name" in Socrata can be freely modified as you see fit.

#### ID Field and Row Identifiers

Each dataset needs to have a dedicated ID field which will be automatically populated with Knack's built-in record IDs.

The field's display name can be freely-defined, but the field name must be `id` and they field type must be `text`. This field must also be assigned as the dataset's [row identifer](https://support.socrata.com/hc/en-us/articles/360008065493) to ensure that upserts are handled properly.

It can be a bit tedious to change row identifiers—because it requires that all records in the dataset have a unique value in the ID field before you set it to be a row identifier. The easiest work around is to download the data and upload just one row of a data that meets that requirement.

If you have a conflicting field in your Knack data named "ID", we should as general best practice rename it. So let me know if you run into that situation. As an FYI, if we absolutely must keep our "ID" field in Knack, this column name will be translated to `_id` when publishing to Socrata.


#### Connection fields

It's a best practice to not use a connection field in the API view, because the value in that field will be the "Display Field" value as it is configured for the object. If someone were to change the display field for that object, it could break the ETL.

Instead, when you're adding columns to the view, use the drop-down menu to pick the related object, then add the field from that object that you want in the view.  See below screenshot as an example of this for the "ATD_WORK_ORDER_ID" field for the specifications table.

<img width="1365" alt="Screen Shot 2020-12-28 at 2 36 36 PM" src="https://user-images.githubusercontent.com/14793120/103242146-e2eb9780-491a-11eb-89e9-8152e1f4c7ff.png">

**Comment by johnclary** [comment]
Just followed-up with Susanne:
>Question for you: two of these tables have a "Created By" column, which I imagine is helpful for your reporting, but we don't like to publish staff names in public datasets. One alternative would be to assign each user in the system an ID #, and we could publish that ID number instead. Would that work for you?

**Comment by johnclary** [comment]
@SurbhiBakshi r.e. the Time Logs dataset. As you suggested, would you split this into two separate Knack views, one for signs and one for markings? On the Socrata side, we can either merge these two datasets or publish to separate ones. If we merge them, we'll want to touch up the Knack field names that are common to both signs and markings so that they match. E.g. rename COUNT_TIME_LOG (signs) to  COUNT_TIME_LOGS (as in markings).

**Comment by amenity** [comment]
It's most important that this data goes to MAINT — Socrata is a nice-to-have.

**Comment by jaime-mckeown** [comment]
@amenity currently data does not go from AGOL to Maint, only from Maint > AGOL. Are the time logs data that Susanne is working with in Data Tracker?

**Comment by johnclary** [comment]
OK, we'll need to talk about this a bit more. As Jaime mentioned, the data has not and will not live on MAINT in the near future. It'd would be good to understand the attribute rule's need as well, since the AGOL layers are meant to be read-only.

**Comment by SurbhiBakshi** [comment]
@jaime-mckeown, @johnclary - So it sounds like Susanne could potentially pull in an AGOL read only dataset to join and then populate. She needs the date field from the time logs. I am unclear which dataset on MAINT will be populated - I thought she had the time logs data already on MAINT and wanted it updated. But it could be a work order dataset. @jaime-mckeown  the time logs data is in the SMB Data Tracker.

**Comment by jaime-mckeown** [comment]
Susanne has related tables to the short line, specialty line, and specialty point layers all located in MAINT. Each table has a WORK_DATE field.

**Comment by amenity** [comment]
She just needs the last maintenance date (will be tracked in Knack once we've figured out #4732) from AGOL.

**Comment by amenity** [comment]
@SurbhiBakshi - do you want to put this in the backlog and mark as a future sprint?

**Comment by SurbhiBakshi** [comment]
Going back to the original intent of this issue (which got a little side tracked due to other issues) there are three tables that need to be connected from Knack to the Open Data Portal so Susanne can connect to those from Power BI. 

1. **Specifications Counts**
- The dataset for this table has been created on the Open Data Portal. 
- John has completed the setup for this table to be updated on the Open Data Portal. 
- Will need to create a Created By ID so names are not populated on the Open Data Portal (referring to John's email to Susanne mentioned above). Will this list live in Knack (Accounts?) and how will the ID be created automatically when new accounts are created (will this be an incremental ID field in the Accounts  object?)

2**. Signs Markings Time Logs**
- The dataset for this table has been created on the Open Data Portal. 
- Need to create separate tables for Signs and Markings time logs. These can either be combined in Power BI or before uploading to the Open Data Portal. 

3. **Reimbursement Trackings**
- The dataset for this table has been created on the Open Data Portal. 
- Need to check if separate tables need to be created for Signs and Markings. Similar to Signs Markings Time Logs, these can either be combined in Power BI or before uploading to the Open Data Portal.

**Comment by amenity** [comment]
Christina and Susanne are going to discuss this and get back to us. Also consider if/how any of these needs are met by the high-level dashboard. https://github.com/cityofaustin/atd-data-tech/issues/4732

**Comment by SurbhiBakshi** [comment]
I have added the fields that Christina and Susanne needed to the datasets for the High Level Dashboard for Signs Markings Time Logs.

**Comment by SurbhiBakshi** [comment]
### Update : 
    **Specifications Counts**

    The [dataset](https://data.austintexas.gov/dataset/SMB-Specifications-Counts-Table/dp8d-apw9) for this table has been created on the Open Data Portal.
    John has completed the setup for this table to be updated on the Open Data Portal.
    Will need to create a Created By ID so names are not populated on the Open Data Portal (referring to John's email to Susanne mentioned above). Will this list live in Knack (Accounts?) and how will the ID be created automatically when new accounts are created (will this be an incremental ID field in the Accounts object?)

2. Signs Markings Time Logs

    The dataset for this table has been created on the Open Data Portal.
    Need to create separate tables for Signs and Markings time logs. These can either be combined in Power BI or before uploading to the Open Data Portal.

    Reimbursement Trackings

    The [dataset](https://data.austintexas.gov/dataset/SMB-Reimbursable-Tracking/9b46-v7qm) for this table has been created on the Open Data Portal.
    Need to check if separate tables need to be created for Signs and Markings. Similar to Signs Markings Time Logs, these can either be combined in Power BI or before uploading to the Open Data Portal.

**Comment by dianamartin** [comment]
- [x] Chia finished writing the automated script for the data updates for the SMB datasets to the Open Data portal #6676

**Comment by johnclary** [comment]
I noticed the datsets did not have an `id` column set as the row identifier, which is what ensures the Knack > Socrata upserts process correctly. I fixed that asked some more questions:

- Should we create the reimnurseables dataset for you? 
- Is the Total Labor Cost field on the time logs dataset even useful?
- Do we need to add additional fields to the work orders/jobs datasets which are required for the high level dashboard?

Susanne's response:

- Yes, the reimbursable dataset does need to be added to Socrata. Currently the dataset is exported as a CSV, but it hasn’t been updated since May. I’m not sure on whether that should be public or private though.
- The Total Labor Cost field on the time logs dataset doesn’t need to be used if it’s already provided in the reimbursables tracking as you said.
- The additional fields do not need to be added, since they are already calculated through PowerBI

**Comment by johnclary** [comment]
I am creating the reimbursements dataset. Note to self—we are likely going to be able to remove some of the calculated fields that Surbhi created for the high level dashboard—I forgot that this was going to be one of the main benefits of moving to PowerBI. Will have to identify those fields once we get the all-clear from SMB.

**Comment by johnclary** [comment]
Sent [reimbursements dataset](https://data.austintexas.gov/dataset/Signs-and-Markings-Reimbursement-Tracking/pma8-yy5k) for review. We will need to complete #6888 in order to deploy the ETL.

> Susanne—I created the reimbursements dataset, [here](https://data.austintexas.gov/dataset/Signs-and-Markings-Reimbursement-Tracking/pma8-yy5k). Let me know how that looks. I wasn't quite sure if these are all the fields you need. We'll clean up the field names and add metadata before we make these public.

**Comment by johnclary** [comment]
Also—we should tackle #6637 while we're doing this. So to recap todos:

- get feedback on reimbursements table
- create atd-knack-services and airflow dag deployments for reimbursements table
- #6637 
- #6888 
- Clean up Socrata field labels and add dataset metadata
- Publish Socrata datatsets publicly

**Comment by johnclary** [comment]
Well, we've actually got 3 reimbursement datasets now. The one I created, plus:
- https://data.austintexas.gov/dataset/Draft_Reimbursables/jfip-72zj
- https://data.austintexas.gov/dataset/SMB-Reimbursable-Tracking/9b46-v7qm

I'm guessing Chia created one and Surbhi created one. Will reconcile/clean up

**Comment by johnclary** [comment]
Did some minor tweaking of the time logs dataset. Waiting for additional feedback before finishing tasks in my [comment above](https://github.com/cityofaustin/atd-data-tech/issues/3114#issuecomment-894562461).

**Comment by johnclary** [comment]
All datasets have been published publicly:
- [Markings Work Orders](https://data.austintexas.gov/Transportation-and-Mobility/Roadway-Markings-Work-Orders/nyhn-669r)
- [Sign Work Orders](https://data.austintexas.gov/Transportation-and-Mobility/Street-Sign-Work-Orders/ivss-na93)
- [Markings Jobs](https://data.austintexas.gov/Transportation-and-Mobility/Roadway-Markings-Jobs/vey3-7n3x/)
- [Time Logs](https://data.austintexas.gov/Transportation-and-Mobility/Street-Signs-and-Roadway-Markings-Work-Order-Time-/qvth-gwdv)
- [Signs/Markings Reimbursements](https://data.austintexas.gov/Transportation-and-Mobility/Street-Signs-and-Roadway-Markings-Reimbursements/pma8-yy5k)

**Comment by johnclary** [comment]
The reimbursements DAG has been deployed! Data is live. We have a few minor follow-up tasks listed above.

**Comment by johnclary** [comment]
Susanne provided additional metadata changes for the datasets. I made the changes and set the reimbursement dataset to be private as she requested.

**Comment by johnclary** [comment]
@johnclary you need to exclude disassociated reimbursements
