### ISSUE TITLE
6/29 AMD Progress and Prioritization Meeting

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#3126]
### Objective 
- Update AMD on the progress of current projects
- Discuss next steps on
    - PHB Ranking 
    - Project Tracking
- Review backlog and re-prioritize as necessary

### Agenda
[Google doc](https://docs.google.com/document/d/1erIRRmY1GrhYrAdDjL-AvWSbskOBPH8pzyyZthdNq8A/edit#heading=h.9y2xzfo6m7nc)

------
- [ ] Schedule meeting
- [ ] Optional: Schedule debrief
- [ ] Meet and take notes
- [ ] Optional: Debrief with DTS team members
- [ ] Create resulting issues
