### ISSUE TITLE
Add a distinct "NO DETECTORS" option for "DETECTOR_TYPE" 

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#3143]
Data Tracker tracks detectors of various types installed on traffic and pedestrian signals. 
<img width="381" alt="Screen Shot 2020-06-25 at 5 58 27 PM" src="https://user-images.githubusercontent.com/1463708/85803763-86aa7f80-b70d-11ea-9bf0-15479b7cdf66.png">

Currently, we have a single "DETECTOR_TYPE", "CBD/NO DETECTORS" used for both 
- CBD - In the Central Business District and pre-timed for optimization
- Signals that have had no detection but could use it (interchanges)

Distinguishing between the two would:
- Help classify signal detection status into working, broken, no existing detection, pretimed, and unknown
- Prioritize repairs based on signal attributes 

Workarounds:
- Manually split them out
- Pass it through Excel using vlookup

Approach:
About 30% of signals with the "CBD/NO DETECTORS" are actually “NO DETECTORS”, so it would be most efficient to assign all of those to "CBD" and then manually designate the “NO DETECTORS”. Joshil says this could be done by himself or the MMC and would take about two hours. 

Desired timeline:
- End of the year to streamline detection prioritization. 

---
Requested by Joshil B., AMD
Request ID: DTS20-100845

**Comment by amenity** [comment]
Emailed Joshil these questions
-   What does CBD stand for? 🙂
-   What questions will this distinction help you answer?
-   Once we have the fields updated, who would be in charge of updating the values on existing signals? How long would that take?
-   What is the approximate percent of signals currently assigned "CBD/NO DETECTORS" are actually "NO DETECTORS"? Are *all* the others "CBD"?

**Comment by dianamartin** [comment]
@amenity CBD = Central Business District

**Comment by amenity** [comment]
@dianamartin @johnclary - Updated the description based on answers from Joshil and reviewing Data Tracker... but I'm a little confused. 🙃

My concerns: 
- Is there any historic data that would be corrupted if rename "CBD/NO DETECTORS" to "CBD"? 
- This terminology... What does it even mean when a detector type is "NO DETECTORS"? And "CBD" is a location... wouldn't it be more accurate to call the detector type for those "Pretimed"?

That said, it seems like an "easy" request to fulfill. Defer to y'all.

**Comment by dianamartin** [comment]
@amenity @johnclary I'm a little weary for this change to take affect, I think we need to make sure all primary stakeholders sign off on this change as well. That would be the MMC and Brian VDW. Brian does a lot of detection reporting and I don't know the affect it would have on his historical reporting (if any). 

That's why these AMD requests can be difficult bc they don't funnel them through to 1 primary stakeholder for different parts of the application.

**Comment by amenity** [comment]
@dianamartin - thanks, let's definitely make sure everyone is on board. Adding it to Monday's AMD meeting agenda.

**Comment by amenity** [comment]
From Joshil by email:
> _I was hoping to replace the blanks with “NO DETECTORS” so it is easier to filter them than just look for both a blank field and a “NO DECTECTORS”. Hope that clarifies things._

**Comment by johnclary** [comment]
Agreed—discussing today. FWIW I think this is a reasonable request, size 3. Will need to reconfigure some reports and possibly make a few minor updates to the detection module workflows.

**Comment by johnclary** [comment]
OK w/ Brian VDW and Ben / TMC

**Comment by dianamartin** [comment]
Querying `signals_detectors`
- [ ] Detection Type `CBD/NO DETECTORS` is 69 records
- [ ] Detection Type `CBD/NO DETECTORS` rename to `PRE-TIMED`
- [ ] Delete Detection Type `CBD/NO DETECTORS` - after Joshil updates the field with either `PRE-TIMED` or `NO DETECTION`

**Comment by amenity** [comment]
@amenity email Joshil to ask about this.

**Comment by dianamartin** [comment]
Joshil emailed 7/23
>I finished off changing the “CBD/NO DETECTORS” to either “Pretimed” or “No detectors” in the Data Tracker and there seems to be no more detectors with this “Detector Type”. I’m assuming you’re all good to go to remove the field and finish off the ticket!

- I checked the records and none were associated with the old Detector Type
- 20 records were PRE-TIMED
- 22 records were NO DETCTORS
- [x] Deleted that choice `CBD/NO DETECTORS`
