### ISSUE TITLE
Update Hazard Flasher Asset Tracking

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#3172]
- Change hazard flasher display name to include flasher type
 - Rename Hazer Flashers to "Flashing Beacons"
- Update page titles, buttons, etc on Work Orders, Location Details

**Comment by dianamartin** [comment]
- [ ] Rename Hazer Flashers to "Flashing Beacons"
- [ ] Change hazard flasher display name to include flasher type
- [ ] Update page titles, buttons, etc on Work Orders, Location Details

**Comment by dianamartin** [comment]
@johnclary should I make the changes in Knack, Socrata and AGOL and you'll update the script that is associated and might break?

**Comment by dianamartin** [comment]
- [x] Create `New Work Order` (old) - Under `Hazard Flasher`, shows `Hazard Flasher` - rename to `Flashing Beacon`
- [ ] Create `New Work Order` (old) - Under `Asset Type`, shows `Hazard Flasher` - rename to `Flashing Beacon`
  - change under object table
- [ ] Check `Edit Work Order` (Old)
- [ ] Check `Edit Work Order` (New)
- Update TMC Activity Form
  - [ ] Record Rules
  - [ ] Display Rules

- [ ] Change `hazard_flasher` object to `flashing_beacon` object
- Fields on object table
- [x] Change `ATD FLASHER ID`, `FLASHER_TYPE`, `FLASHER_STATUS`, `FLASHER_COMMENT` in Knack
- [ ] Change `ATD FLASHER ID`, `FLASHER_TYPE`, `FLASHER_STATUS`, `FLASHER_COMMENT` in Socrata
  - In Socrata, okay to just rename the field
- [ ] Change `ATD FLASHER ID`, `FLASHER_TYPE`, `FLASHER_STATUS`, `FLASHER_COMMENT` in AGOL
  - create New fields, delete the old fields
- Update `MODIFIED DATE` to update script

**Comment by dianamartin** [comment]
## Updated in Socrata
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/caeae42b-643d-42fa-ad1d-d8d116f70694)

**Comment by dianamartin** [comment]
@johnclary if i change the name of the knack object from `hazard_flashers' to `flashing_beacon`, will it break the script?

I plan to check the AGOL layer to see if it updates, I think it updates at around 3 am. 

Also, I didn't change the AGOL dataset name to "Flashing Beacons" bc I was scared it would break. I didn't touch it. I did rename the Socrata dataset however. 

Let me know what I should do.

**Comment by dianamartin** [comment]
@johnclary FYI: I just checked the Data Publication log, there was an error for the `hazard_flashers_agol` bc it seemed like it was looking for that "ATD_FLASHER_ID" field.

**Comment by dianamartin** [comment]
Talked to John and he said that I could change the name of the `hazard_flasher` object tablet in Knack to the new updated name `flashing_beacons`.

**Comment by dianamartin** [comment]
@johnclary I'm going to create an issue to update the python scripts and close this one.
