### ISSUE TITLE
Ability for other AMD groups to create work orders for signal techs

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#3177]
This functionality exists today. Mostly just a training issue, with some minor mods discussed today:
- need to add attachment type dropdown to signal attachments
- need to verify/test permissions & workflows for non-technician users
- ask Jonathan/signal engineer to test

**Comment by dianamartin** [comment]
Emailed the users that had been identified as having submitted a bunch of "File Attachments". I needed to get feedback on "Attachment Types" so we can add them to File Attachments. We also need to create a better workflow for the AMD Work Order.

**Comment by dianamartin** [comment]
## Attachment Type categories
I’m seeing these categories come up repeatedly: 

- [ ] Diode Card
- [ ] Field Images
- [ ] Permit
- [ ] Phasing Sheet
- [ ] Signal Modification
- [ ] Signal Layout
- [ ] Timing Sheet
- [ ] Traffic Control Plan (TCP)
- [ ] Wiring Plans
- [ ] Other
- [ ] 

We can plan on keeping the field “File Description” to allow a more descriptive field of what the attachment is.

**Comment by johnclary** [comment]
Nice!

**Comment by dianamartin** [comment]
- [x] Created new field `ATTACHMENT_TYPE` on `signal_file_attachments` object table 
- [x] Made required
- [x] Added field to `Add signal_file_attachment` form on the Signal Details page

## Back end of form
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/4cfdcfef-9872-47d1-9030-90d59e3af15f)

## Front end of form
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/02b6d55c-892f-4e27-bb50-00847606af30)

**Comment by amenity** [comment]
🙌
