### ISSUE TITLE
Allow Requesters to Add Location Points when Creating a Work Order

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#3201]
- Do this in TEST first
- Have Christina test it in TEST
- "move" to prod

### Update: use this issue to have dev work on map enhancement to allow users to create locations in SMB Tracker

**Comment by dianamartin** [comment]
@johnclary So do you want me to just coordinate with Christina on when she can set-up training for the engineers on how to create locations?

Should we sync up before I do this?

**Comment by dianamartin** [comment]
- [ ] Copy new test environment
- [ ] Christina to test 
- [ ] Make changes in "Prod"

**Comment by johnclary** [comment]
@dianamartin remember to do this please.

**Comment by dianamartin** [comment]
@john I submitted ticket to Knack 7/15

**Comment by dianamartin** [comment]
@johnclary 
- Knack was able to cancel the old copy task and restart a new copy task 7/16
- Checked today and the environment was set-up
- Added App ID to Application Inventory

### Testing
- Was on the phone with Christina and we were able to test together
- [x] Removed page rule, logged in as Test Viewer --> Saw two tables, two maps but not the correct map (Add Location button)
- [x] Put rule back
- [x] Changed view ID in JS for Viewer, logged in as Test Viewer --> Saw two tables, two maps but not the correct map (Add Location button)
- [x] Put view ID back in JS

### Next Steps
-  I don't think it has anything to do with a Knack page rule, I think it's part of the JS code looking at user roles perhaps. 
- Need to have @mddilley take a look and explain what is happening
  - Need to get user role "viewer" to be able to see the "Add Location" button on the Editable map/Editable Table

**Comment by johnclary** [comment]
@dianamartin plz reach out to Mike

**Comment by dianamartin** [comment]
@johnclary cc: @mddilley I reached out to Mike and we synced up to talk about what SMB wants the viewers to be able to do.

We did a few tests together in the new `15 JULY 2020 | TEST -  Signs and Markings` environment.
- Modified the page rules
- Added page rules
- changes JS code from one view number to another

Mike thinks that there might be other code in react, so we're still looking into it as of right now.

**Comment by mddilley** [comment]
Need to dive deeper into how showing an editable or read-only map to a user is controlled with the iFrame map messenger

Related code: 
https://github.com/cityofaustin/atd-knack-signs-markings/blob/4757eee0f7ea34bf6d2f194efc16258953c2a7cd/knack/index.js#L285-L295

**Comment by johnclary** [comment]
@mddilley we forgot to tag this as a `dev` issue. You have time to look into this during the Sprint 30?

**Comment by mddilley** [comment]
@johnclary I have a pretty good handle on this, but I need more context about what map features need to display to which roles. Right now, the read-only map renders if the Knack app renders `view_2619` to the logged-in user and the editable map renders if the Knack app renders `view_2573`. I'm not sure where requesters fit into that picture.

**Comment by johnclary** [comment]
Ah, so it looks like we just need to fix the logic in the Knack app to render view_2573 when we want it to

**Comment by johnclary** [comment]
@mddilley I assigned this to myself. thanks!

**Comment by amenity** [comment]
@mddilley @johnclary - would it make sense to do #3777 alongside this one?

**Comment by amenity** [comment]
@johnclary is doing research on this to see if there is dev work needed. Stay tuned.

**Comment by johnclary** [comment]
I've been focused on the #3521 (Setup Work Order Automation), which will automatically create the work order location points from TED's AGOL map. Assuming this is still needed, but is lower priority.

**Comment by amenity** [comment]
TED and Parking have also expressed interest in this AGOL-based process to geolocate work orders.

**Comment by ChristinaTremel** [comment]
Iceboxing until a request comes up for enhancements on the sign work order creation.

**Comment by ChristinaTremel** [comment]
The goal at this time was to have Requesters create work orders using the sign inventory, but they are not interested in changing their process at this time. Closing this because we didn't move forward with this request at that time and our scope has changed.
