### ISSUE TITLE
Feature request: Add "Locations" choices to COVID Time Log Form/Tables/Reports

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#3202]
Peggy M. 
Finance

Emailed 
>I am submitting the first phase of data for the COVID response.  One additional data required is to identify the location where staff worked.  Can you add a field to the log asking for this information:

Locations
--
7AC1 (alternate Care Site)
7If1 (ISOFAC 1 - Crowne Plaza)
7IF2 (ISOFAC 2 - Embassy   Stonelake)
7LW1 (Logistics Warehouse 1   (Expo Center))
7MTC (Mobile Testing Centers)
7PL1 (Prolodge 1 - LaQuinta)
7PL2 (Prolodge 2 - Motel 6)
7PL3 (Prolodge 3 - Days Inn)
7PL4 (Prolodge 4 - Country Inns   & Suites)
7PL5 (Prolodge 5 - Roadway Inn)
7TC1 (Testing Ctr 1 - St.   Johns)
7TC2 (Testing Ctr 2 - Pleasant   Valley)
&EOC (Emergency Operations   Center)
7DOC (Department Operations   Center
Remote (Teleworking)
Systemwide

**Comment by dianamartin** [comment]
- Peggy replied on 6/30 (Tuesday) that this can get done "next week"
- [ ] Adding new field `Locations`
- [ ] Adding choices provided by Peggy
- [ ] Email Peggy, Jace that this was done

**Comment by dianamartin** [comment]
## Add Time Log
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/c96e4959-6101-43f5-a369-c9b764dcad6c)

## Review Time Log table
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/d4367a7d-0a56-4aa1-a842-975cf003c270)

## HSEM Report
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/77a2f310-22eb-4f13-a1ce-188c2f73b096)
