### ISSUE TITLE
AMANDA - FY 20/21 Fee Updates (TL)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#3296]
### Update all fees as needed for FY 20/21

**Stakeholders:**
- TDS
- ROW
- OSE
- Signs/Banners

**DTS Manager:** Tracy

**Next Steps**
- [x] Talk to Van and Dan about fee updates during sprint 30. 
- [x] Create ATD AMANDA Fee Workbook
- [x] Review FY21 fee updates with Van & Dan

**Notes:**
- Together with Finance, we've decided to create an ATD AMANDA Fee comprehensive workbook that will allow us to more easily identify and implement fee changes. 
- Fee Folder is [here](https://drive.google.com/drive/u/2/folders/17nc2pJqTVMqo7CncLaPKwWYJgwVpTGSi)

**Comment by TracyLinder** [comment]
**Email today to Dan & Van:**

Hi Dan & Van,

I think I’ve got our ATD AMANDA Fee Workbook in good shape; it’s attached. I’m thinking the next step is to identify which fees need to be updated, and start inserting new fees that don’t exist yet. Should I schedule a meeting for that, or is there another way I can find the fees that are being updated? (Sorry I feel like we discussed this and I can’t remember it now.)

Thanks,

Tracy Linder, Product Manager
Data & Technology Services 🚲 Austin Transportation

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder, @Nadin-Nader - Sent an email to Tracy & Sangeetha on 09/22/2020 to get the clarifications and confirmations; Continuing to work on the issue.

**Comment by TracyLinder** [comment]
**Status:** Met with Sangeeta today to review fee changes. Work continues into sprint 34.

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder 
I have sent the task to Amanda support to deploy to DEV. It is under TASK SCTASK0097752

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder This has been deployed to DEV by Martin Under SCTASK0097752. Please check the fees and let me know if anything is needed

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder Per Martin, e2bb65e36055, 5d64c3df5ced been committed.

**Comment by TracyLinder** [comment]
@Nadin-Nader great work!

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder i submitted SCTASK0098019 to deploy commits: e2bb65e36055 and 5d64c3df5ced to TEST.

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder Martin has deployed this to TEST

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder , @Nadin-Nader  - Sent PROD Deployment Plan on 09/30/2020 to promote changes from TEST to PROD by EOD after 5pm.

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder created SCTASK0098236 for the Fee deployment TASK to PROD.I also let Martin know.
## Waiting on Deployment to PROD

**Comment by Nadin-Nader** [comment]
Everything has been deployed to PROD. Waiting on UAT from USERS

**Comment by Nadin-Nader** [comment]
> From Kim:
> 
> From: Perez, Kimberly <Kimberly.Perez@austintexas.gov> 
> Sent: Thursday, October 1, 2020 8:21 AM
> To: Linder, Tracy <Tracy.Linder@austintexas.gov>; Nader, Nadin <Nadin.Nader@austintexas.gov>
> Cc: Amayo-Ryan, Paloma <Paloma.Amayo-Ryan@austintexas.gov>
> Subject: RE: INFO: FEE ERROR ON 09/30
> 
> Good Morning Everyone,
> 
> So the DS inspection fees all work great this morning!
> 
> Thanks,
> Kim

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder , @Nadin-Nader - This card can be closed. :-)

**Comment by TracyLinder** [comment]
Fees have been deployed. Closing ticket.
