### ISSUE TITLE
Learn about issues signal technicians are experiencing with Work Order submission

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#3301]
### Objective 
Have Billy walk us through the process his team expects, how Data Tracker isn't meeting that need. 

Workflow Brian VdW proposed:
- Create Work Order and leave unassigned
- Assign to technician during weekly meeting

### Participants
Billy, Brian VdW, Diana
Optional: Chrispin, Surbhi, John

### Agenda
- [Video](https://atd.knack.com/amd#school-zone-beacons/school-zone-beacon-zones/school-flashers-zone-details/58e7f553171d3b433922dca4/)

------
- [x] Schedule meeting 7/17/20
- [ ] Optional: Schedule debrief
- [x] Meet and take notes
- [ ] Optional: Debrief with DTS team members
- [ ] Create resulting issues

**Comment by dianamartin** [comment]
## Diana's Notes

**Comment by SurbhiBakshi** [comment]
### Notes - 

1. Concern - others start to morph the process, who will close the work order? all submitted tickets come to 4 technicians. Only supervisors have rights to close tickets on the front end. This might cause a deluge of work orders that need to be closed.
2. School Zone Issue - to be addressed a little later.
3. Other work groups like engineers need to have a process to assign work orders, so Billy or staff are not responsible for closing those work orders.
4. Need a separate work order type.
5. If it is a trouble call, the technician is instructed to look at every single beacon.
6. Now there will be upgrades to each beacon, so need tracking at that level - could be a big change.
7. Tracking will need to be done at beacon level, and not at a school zone level to enable the upgrade process.
8. School Zone beacons are never across each other. MMC gives the address. This might relate to multiple different locations at which the actual build might need to take place. How is the actual location of the designated beacon related? The technician needs to have accurate information about the location, possibly more detailed than a street address.
9. One beacon may be the primary, with the WO? that needs to be connected to the secondary beacons.
10. Might need a total refresh of the school zone dataset.
11. We need to get the right data - template to get the data updated.
12. Clock?
13. Beacon address and Map heading may differ and may be misleading.
14.Billy could dispatch someone to get information on exact address/location of the beacon and record that.
15. It might be a few steps to update the location details on the beacon. Collect x, y point.
16. Could do a spreadsheet or a mobile app.
17. Eltech and Harmony - run clocks, database, all the clocks are backed up.
18. MMC keeps a spreadsheet that has all school zone information updated each year.
19. Billy keeps up with PMs.


9.

**Comment by dianamartin** [comment]
@amenity I've added the link to the recording to the issue description

**Comment by amenity** [comment]
@dianamartin @SurbhiBakshi @johnclary 
Watched this and wanted to check with you on my takeaways: 
- [ ] DTS to determine the process that Billy's team should use to clean up data, i.e. collect precise coordinates on individual beacons. Cloud-hosted spreadsheet? Fulcrum? Data Tracker mobile app?
- [ ] DTS to scope out the LOE to attach Work Orders to individual beacons instead of school zones.

Re: initial intent of meeting: People from other divisions who will be submitting work orders are techy; problem will not be that it's complicated technically but on the information they should be including. Mandate + guidance will come from AMD/VdW.

**Comment by amenity** [comment]
@dianamartin @SurbhiBakshi @johnclary 
Following up here with some issues and questions: 
- [ ] DTS to determine the process that Billy's team should use to clean up data, i.e. collect precise coordinates on individual beacons. Cloud-hosted spreadsheet? Fulcrum? Data Tracker mobile app? **_Created an issue [here](https://github.com/cityofaustin/atd-data-tech/issues/3472) for that._**
- [ ] DTS to scope out the LOE to attach Work Orders to individual beacons instead of school zones. _**Does that essentially mean sizing [this](https://github.com/cityofaustin/atd-data-tech/issues/1555)?**_

After this is done, will we be ready for https://github.com/cityofaustin/atd-data-tech/issues/1644?

And should we take care of https://github.com/cityofaustin/atd-data-tech/issues/1841?

**Comment by dianamartin** [comment]
@amenity Looks like all these issues you've created are all related and if we update the ability to create a work order and associate it to a particular school beacon, then yes, we'd could potentially start working on the downstream "school beacon" requests.

**Comment by amenity** [comment]
@dianamartin - thanks. I didn't create https://github.com/cityofaustin/atd-data-tech/issues/1555 — so want to make sure that is the issue that captures what we said we'd size.
