### ISSUE TITLE
Tracy's Various Overdue Work - Tackling During Sprint 29

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#3402]
- [x] #1729
- [x] #1823
- [x] #1713
- [x] #1580
    - Tried to test, DEV permissions not working. Asked Sree to issue the permit for me. 
- [x] #2632
- [x] #2634
- [x] #1576
- [x] #2401 - Look into Sangeeta's testing results
- [x] #3347 - Schedule GIS PNTS Meeting
- [x] #1766 - Ready for UAT
