### ISSUE TITLE
Builder Huddle: Dispatch Tracking

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#3418]
### Objective 
Estimate work load based on requirements from https://github.com/cityofaustin/atd-data-tech/issues/3367

https://docs.google.com/spreadsheets/d/1o0Q_xIx0c1njAg6opnAJwyCIhAkU7W-hK_7P8jgMCug/edit#gid=0

### Participants
John, Surbhi, Diana, Chrispin

### Agenda
What they have is currently working for them fairly well
https://cityofaustin.sharepoint.com/sites/ATD/dispatch/Lists/Dispatch/Dispatch%20mode.aspx

Parking Dispatch
Keep track of workflow of officers

Dispatchers call for radio checks

Line of communication that is open

Calls come in through CSR

Phone call to main line/cell phone goes to dispatcher

majority come from citizens
complaint or report an issue or set of issues
Address of complaint
Dispatch officers to address the situations

Input notes in the outcomes

Documents what happens during the dispatch

What they did for SharePoint

pull stats
put into a report
not very friendly

Categories:
are pretty static
is the list pretty good? Yes, for the most part

Improvements

- Reporting - monthly by category, by dispatcher, by address (will think of more criteria)
- Status - Open, In progress and Closed
- Received By - CSR and Phone
- Comments field

Future Enhancements

- Ability to determine which officers are available - list of officers with status in/lunch/out
- Integrate with CSR
- View map locations

------
- [x] Schedule meeting
- [ ] Optional: Schedule debrief
- [ ] Meet and take notes
- [ ] Optional: Debrief with DTS team members
- [ ] Create resulting issues

**Comment by moorerst** [comment]
Scheduled 7/23

**Comment by dianamartin** [comment]
### Diana's Thought on the App Build: 

- Add New Dispatch log form
  - Fields might need refinement
- Dispatch details 
 - Add New Attachment form
 - Attachment table
- Dispatch Table
- Employee Sign/Sign out
  - Employee history of sign/sign out - ex. lunches
- Advanced Search
- Dispatch Report Page

**Comment by moorerst** [comment]
Effort 5
Value 9
Other improvements that came from the discussion:

- Nice to Have - Integrate with ArcGis online to capture the points for the complaint addresses on the map 
- Use ArcGis Collector for officer location information
- Will need to allow for multiple attachments
- Break out information currently captured in the Address field - Address, PEO # dispatched, complaint, resolution/findings

**Comment by amenity** [comment]
@ChrispinP — heads up, this is coming your way. 😎
