### ISSUE TITLE
Backup, Delete Signs and Markings modules and records from Data Tracker 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#349]
>Update: We might keep a link from the Data Track to the new Signs and Markings Operations application. It will not be connected to the old pages/tables.

- [x] Backup
- [ ] Delete Signs and Markings modules
>These have been hidden currently
- [x] Delete Signs test/dev records from Data Tracker 
- [ ] Delete Signs and Markings records from Data Tracker

**Comment by johnclary** [comment]
Before we delete any modules from data tracker, let's make a record-less copy of the data tracker as preserve it.

**Comment by dianamartin** [comment]
- [x] Made the copy of the PROD app **30 JULY 2019 | Austin Transportation Data Tracker | Production (Record less)**

**Comment by dianamartin** [comment]
- [ ] Delete `work_order_signs_DELETE`
- [ ] Delete `work_order_signs_locations_DELETE`
- [ ] Delete `work_order_signs_asset_spec_DELETE`
- [ ] Delete `work_order_signs_asset_spec_actual_DELETE`

**Comment by johnclary** [comment]
@dianamartin i think we agree that we need a fresh copy of a Data Tracker test environment **with records**. Would you do that, and then I'm comfortable deleting the signs and markings modules from Data Tracker?

**Comment by dianamartin** [comment]
@johnclary Just started the copy for the new TEST app for PROD. `  7 AUG 2019 - TEST | Austin Transportation Data Tracker | Production`

**Comment by dianamartin** [comment]
@johnclary the application is done copying. I called it `7 AUG 2019 - TEST | Austin Transportation Data Tracker | Production (With Records)`

**Comment by dianamartin** [comment]
Signs and Markings Pages in Data Tracker PROD

## Deleting Pages

- [ ] Work Order Markings Login
- [ ] New Work Order (Signs & Markings) Login
- [ ] Jobs (Signs & Markings) Login
- [ ] Specifications (Signs & Markings) Login
- [ ] Requester (Signs & Markings) Login
- [ ] Reference: Calculators

## Deleting Data (object tables)
- [ ] `work_orders_signs_markings`
- [ ] `work_orders_signs_markings_attachments`
- [ ] `work_orders_signs_markings_comments`
- [ ] `work_orders_markings_specification
- [ ] `work_orders_signs_markings_specification_actual`
- [ ] `work_orders_signs_markings_jobs`
- [ ] `work_orders_signs_markings_time_log`

**Comment by dianamartin** [comment]
Deleted all Signs and Markings object tables and pages in the Data Tracker Prod environment
