### ISSUE TITLE
Project: Right of Way Permitting Team Attendance Tracking

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#357]
The right-of-way permitting team needs to be able to track times and hours worked so that they can  improve the accuracy of overtime reporting and anticipating wait times for our customers.

## Description
This application will be used to track times and hours worked for the Right-of-Way permit team. This will improve the accuracy of overtime reporting and anticipating wait times for our customers. 

**Submitted via email to Tracy on 7/12/19 by Paloma A-R**

### As a manager I want to be able to track my permit staff's time more closely, so that I can better report on overtime needs and provide customers with a better idea of wait times. 

**Describe the outcome you'd like to see when this feature is implemented.**
Staff will be able to log their arrivals and departures.
I will be able to report more accurately on overtime worked. 
Perhaps we can tie this attendance tracking into our current (KNACK enabled) customer sign-in app, to inform a larger picture out our walk-in customer management. 

**Describe any workarounds you currently have in place or alternative solutions you've considered.**
Currently staff sends me an email when they arrive and leave. Its very difficult to answer questions about time worked using this solution. 

**What else should we know?**
We're considering using an existing CTM solution for this. 

**How would you rate the impact of this issue?**

- [ ] Must have — The application is illegal, unsafe, or not functional without it.
- [X] Should have — This is important but not vital functionality or there is a temporary workaround. 
- [ ] Could have — We want this but there are more important requests. 
- [ ] Unsure

**If it is critical that this feature is delivered by a certain date, when and why?**

**Comment by amenity** [comment]
@dianamartin @johnclary - do you need any more info to estimate LOE here?

**Comment by dianamartin** [comment]
@amenity @john Yes, I think there still needs to be a scoping meeting, unless Tracy's already done one. Like what exact functions they're looking for (Start Time, End Time) Day duration or Breaks and lunch included so they have to sign out in the middle of the day. What kind of reports or reporting numbers they're looking for so we can design the database correctly to capture those things.

**Comment by johnclary** [comment]
@TracyLinder @amenity whether this is a new feature to Visitor Sign-In, or a new application, this is definitely a project-size work. Adding the `Index` label.

**Comment by TracyLinder** [comment]
There will be an informal "Discovery" conversation w/ Paloma. Issue #806

**Comment by TracyLinder** [comment]
**Dev Huddle Note:**
* KNACK solution will be ideal
* Small project size (2-4 weeks)

**Comment by TracyLinder** [comment]
### Update
Per Paloma, they're using Teams to meet this need currently, but would still like to see it in the ROW Portal at some point in the future.

**Comment by TracyLinder** [comment]
ROW gave us approval to close this request.
