### ISSUE TITLE
TCP Tracker: New Page - TCP Deficiencies Advanced Search

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#3603]
### Create a new page that will allow users to query and filter deficiencies on the Submissions table. 

- This page can either look similar to the 'Export Submissions' page, or it can be an advanced search page (examples can be found in other KNACK apps)
- [x] Page includes an export feature

Query Parameters/View Filters
- [x] Review Dates, both a start & end (query off of Submittal Date)
- [x]  Submission Status
- [x]  Submitting Agency (TCP Case details)
- [x]  Department Name (TCP Case details)
- [x]  Sealing Engineer (TCP Case details)
- [x]  Submission Reviewer

- Table columns/view:
![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/613fc6d4-14ad-42ed-8b07-1a8009e22a04)

**Comment by TracyLinder** [comment]
On deck for Chrispin to begin development. Around 3-6 hours of build time.

**Comment by ChrispinP** [comment]
So I just realized this issue has a bit of a Frankenstein problem. It would be a table consisting of two different objects and thus wouldnt mesh well. Deficiencies and Review Dates live on the Submission object whilst the other fields live on the TCP Project object. Since it is a one to many relationship, pulling multiple records of Submission data won't be ideal. Its similar to how the TCP Status is reliant on a bunch of conditional rules that roll all Submission statuses up to the parent TCP Status.

I think the ideal scenario is to create a TCP Deficiency Status field and use boolean fields like we do in TIA to roll up the child statuses and set conditional rules for the parent.

For the Review Dates, instead we would need to use TCP Project Date fields or do the same as above and create a Review Date Status or use the existing TCP status as the filter instead.

Lastly, since most of these fields do live on the TCP Project object, we could use same TCP Projects search page or TCP Reviews table for the Deficiency Status.

For now I have created a TCP Deficiencies Search page that allows you to search Deficient Submissions and open those Submission details.
![image](https://user-images.githubusercontent.com/67915167/140838961-749cb119-2500-47fc-878f-81766b0862a8.png)

**Comment by TracyLinder** [comment]
**Stakeholder Review:

Chrispin's deficiency page is looking good. Please add columns to the table from the TCP Case Details. (See description.)

**Comment by ChrispinP** [comment]
Created text formulas in Submission object to pull down Submitting Agency, Department Name, and Sealing Engineer for each Submission.
![image](https://user-images.githubusercontent.com/67915167/146241590-47d932d4-5287-4a32-b159-71ff71e98913.png)

Added Search inputs and results to the Search TCP Deficiencies page
![image](https://user-images.githubusercontent.com/67915167/146241744-45dfaf2f-f559-4149-a3c0-e95e25bdf13e.png)

Deficiencies added to Submission Details
![image](https://user-images.githubusercontent.com/67915167/146241908-9c417bca-b8a5-47e4-a5cf-96ff7b6b9bca.png)

Ready for review

**Comment by TracyLinder** [comment]
Meeting to review w/ stakeholders scheduled for 1/17

**Comment by TracyLinder** [comment]
This is live and in use. It may need some enhancements, but I'll let those surface organically by stakeholders.
