### ISSUE TITLE
[Feature] Project Staffing

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#3665]
As a project manager, I want to view and manage all associated employees of a project so that I can keep track of who to contact for a given project based on their role.

**In-scope:**
- Assignment of COA employees to project roles within a project.

- Likely a tabular view--nothing fancy

**Out-of-scope:**
- Automated assignment of employee to projects via Project Templates/Standards

- Staff assignments external to COA

**Additional notes:**
This feature solely refers to the ability to assign individual employees/staff members to project roles underneath a project. This would in turn impact views that are filtered by project role or employee.

**Comment by zappfyllc** [comment]
@zappfyllc break up this Epic into:
- [ ] Create wireframe @amenity
- [ ] Postgres DB @zappfyllc 
- [ ] React code
- [ ] GraphQL queries/mutations

**Comment by amenity** [comment]
@mddilley - don't think #5308 needs to keep this epic open. Thanks for wrapping it up!
