### ISSUE TITLE
Refine various MMC components in Data Tracker

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#3849]
**Update references to outdated name**
- [x] Update slug/URL: `https://atd.knack.com/amd#tmc/`--> `https://atd.knack.com/amd#mmc/` - will close #1707 
- [x] Update button on Data Tracker homepage to "Mobility Management Center"

**Modify [SR table](https://atd.knack.com/amd#tmc/) structure**
Lance initially submitted a [request to widen the table on the MMC page](https://github.com/cityofaustin/atd-data-tech/issues/3772) but we'd like to start by seeing if some tweaks to the table could resolve their issue first. 
- [x] Reorder columns so that `Status` is between `Details` and `Issue ID`
- [x] Remove `Engineer Area`

**Comment by amenity** [comment]
@amenity - email Lance et al. to let them know about the slug change — they likely have bookmarks for this...

**Comment by amenity** [comment]
Beautiful, @ChrispinP !

**Comment by amenity** [comment]
It is fine to leave "TMC" on Builder side for now. There are several integrations — CSR/311 in particular — that might break.
