### ISSUE TITLE
Refine Officer interface after internal testing

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#3920]
_Adding small Apps issues here; will add larger issues or Dev issues to this epic._

## Sign Up
- [x] Remove the "Filled Assignments" table from the Sign Up page. This may be useful down the line as its own page/tab, but it's not very discoverable at the bottom of this page (especially on mobile) and doesn't match the other tables. 

## My Assignments
- [x] Remove "Sector" and "Date" from "Today's Assignments" table — [have horizontal scroll on mobile](https://user-images.githubusercontent.com/1463708/92561239-7482ac80-f239-11ea-92d9-0346fda2a990.png) and these columns aren't necessary
- [x] Add "Date" and remove "Sector" from "Future Assignments" table; order of columns should match "Today's Assignments"
- [ ] Disable sort-by-column on "Today's Assignments" table and "Future Assignments" table — should always be in chronological order - Had a Slack conversation with @amenity 
- [x] Replace trash can icons with [`times-circle`](https://fontawesome.com/v4.7.0/icon/times-circle) and change those column headers from "Remove" to "Cancel." (This will eventually be covered by #3614 but would be nice to have it match in the meantime. Not necessary if it's time-consuming to fix.)
<img width="422" alt="Screen Shot 2020-09-08 at 6 28 33 PM" src="https://user-images.githubusercontent.com/1463708/92538171-9feaa480-f203-11ea-878b-de1772341c4d.png">

- [x] Assignments should not disappear once they have ended. They should remain and show a status of "Ended". We can't prevent the timestamps from being overwritten if the assignment is reopened, so we will take away the folder icon so that it can't be reopened. This relates to #3923... 
- [x] "Special Event Unit Cancellation Policy" link should go to https://atd.knack.com/vza#help/ 

## Assignment Details
- [x] Rename page "Assignment Details" to match breadcrumb and slug - @amenity not sure what this means?
- [ ] ~Update CSS for "Start" and "End" buttons~ - #3929 
- [x] Rename "Start" button to "Start Assignment"
<img width="382" alt="Screen Shot 2020-09-09 at 1 09 00 AM" src="https://user-images.githubusercontent.com/1463708/92562945-64b89780-f23c-11ea-974b-93a714004a25.png">
<img width="373" alt="Screen Shot 2020-09-09 at 1 29 48 AM" src="https://user-images.githubusercontent.com/1463708/92562974-726e1d00-f23c-11ea-9103-f3ebd4552c4d.png">

- [x] Change pop up notification text:
    - "Assignment started." (sentence case)
    - "Assignment ended." 
- [x] Change text under "Add Notes" to 
> During your shift, please report any safety concerns, e.g. "pedestrians crossing without crosswalk Cesar Chavez between Comal and Chicon", "low visibility around corner at 12th and MLK", etc. 
- [x] Remove "Type" field from notes
- [x] Change "Notes" notes field to "Description"
- [x] Remove column sorting from Notes table — should stay in chronological order
- [x] Remove time and date fields from notes "Edit" modal

## Miscellaneous
- [x] Remove "Print" link from top of "Assignment Details" page
<img width="397" alt="Screen Shot 2020-09-09 at 2 24 48 AM" src="https://user-images.githubusercontent.com/1463708/92567818-dfd17c00-f243-11ea-8e33-50e87ee72085.png">

- [x] Remove "Print" link and duplicate heading from the top of the "Account Settings" modal 
<img width="1001" alt="Screen Shot 2020-09-08 at 6 44 15 PM" src="https://user-images.githubusercontent.com/1463708/92538699-f3a9bd80-f204-11ea-8a00-99131c229c56.png">

- [x] Change heading from "Cancellation Policy" to "Special Event Unit Cancellation Policy" on https://atd.knack.com/vza#help/

**Comment by SurbhiBakshi** [comment]
@amenity - think I am done with everything except for Sorting for the table, and the breadscrumb and slug.

**Comment by amenity** [comment]
@SurbhiBakshi ah, sorry — that wasn't very clear. 
<img width="800" alt="Screen Shot 2020-09-09 at 5 40 13 PM" src="https://user-images.githubusercontent.com/1463708/92662162-e43d7980-f2c3-11ea-8ec4-3db0f74986f1.png">

Right now at the top of the page it says "Current Assignment Details", so we need to take out "Current" to make it consistent.

**Comment by SurbhiBakshi** [comment]
thanks @amenity - fixed that!
![image](https://user-images.githubusercontent.com/13035849/92740771-a122eb00-f343-11ea-9bc3-0670bf5bbc85.png)

**Comment by amenity** [comment]
@SurbhiBakshi — 🤪 Sorry, I meant they should all say "Assignment Details". Take out "Current. :)

**Comment by amenity** [comment]
- [ ] Account Settings modal still has duplicate heading 
- [ ] Remove past assignments from the calendar

**Comment by SurbhiBakshi** [comment]
@amenity - changed Current Assignment Details to Assignment Details
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/51bc7c67-3d7b-4a85-843d-d9aa6d937731)
