### ISSUE TITLE
Enable COACD button on all Knack login URLs, add fancy buttons, and document process 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#3924]
If I log out, or trying to access a valid URL (e.g. https://atd.knack.com/vza#my-assignments/) without being logged in, the login screen I get is missing the "Sign in with COACD" button. 

Apps to check:

- [x] Data Tracker [done]
- [x] Signs and Markings [John]
- [x] VZA [Surbhi]
- [x] RPP [Chrispin]
- [x] Development Services [Chrispin]
- [x] ~DTS Portal~ [Diana] - _this already has 2 buttons and COACD enabled_
- [x] HR [Chrispin]
- [x] Finance [Chrispin]
- [x] Shared Mobility [Surbhi]
- [x] Street Banners [Diana]
- [x] ROW Portal [Chrispin]

**URL tested:** https://atd.knack.com/vza#my-assignments/assignment-details/5f3db2b4911f490a5ab49321/

Open [URL](https://live.browserstack.com/dashboard#os=iOS&os_version=12.0&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fatd.knack.com%2Fvza%23my-assignments%2Fassignment-details%2F5f3db2b4911f490a5ab49321%2F&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://atd.knack.com/vza#my-assignments/assignment-details/5f3db2b4911f490a5ab49321/&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) on Browserstack

|Property | Value|
|------------ | -------------|
| Device | iPhone XR |
| Browser | Mobile_safari |
| Operating System | iOS 12.0 |
| Resolution | 828 x 1792 px |
| Screen size | 6.1 in - 2.56 x 5.54 in |
| Viewport | 414 x 896 dp |
| Aspect Ratio | 19.5 : 9 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/b57e69b992fbf6fef2b52d883a81c8c31a53dd8e/realios_iPhone_XR.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/b57e69b992fbf6fef2b52d883a81c8c31a53dd8e/realios_iPhone_XR.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=iOS&os_version=12.0&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fatd.knack.com%2Fvza%23my-assignments%2Fassignment-details%2F5f3db2b4911f490a5ab49321%2F&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://atd.knack.com/vza#my-assignments/assignment-details/5f3db2b4911f490a5ab49321/&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) to reproduce the issue on Browserstack**

**Comment by amenity** [comment]
In the custom code we have a list of pages where we show the COACD pages; need to make a list of all pages and add to the code. @johnclary will help with this.

**Comment by amenity** [comment]
@ChrispinP — please add to Knack docs

**Comment by SurbhiBakshi** [comment]
@johnclary , @ChrispinP - meeting scheduled for Sept 15th

**Comment by SurbhiBakshi** [comment]
Rescheduled meeting to Sept 24th, had to postpone earlier one

**Comment by SurbhiBakshi** [comment]
@amenity  - We were not able to get this done yesterday. @johnclary is going add documentation. @ChrispinP and I are working on the first step - adding a big button, and then we will add the sign in functionality to all the pages based on the documentation John is adding to the wiki. Rescheduled meeting to October 5th.

**Comment by amenity** [comment]
@SurbhiBakshi @johnclary thanks for the update. Can you all implement this in Data Tracker as well during the work session? 

For some reason I thought it was already implemented there, but yesterday during #3914 Billy pointed out that he has to use a particular URL in order to use his COACD login. Otherwise he needs to use a Data-Tracker-specific login but he has trouble keeping track of that password.

**Comment by amenity** [comment]
~[30 Data Tracker pages will need this](https://knack-explorer.netlify.app/5815f29f7f7252cc2ca91c4f). 😅

**Comment by johnclary** [comment]
@SurbhiBakshi @ChrispinP list of apps to update is in the issue description

**Comment by amenity** [comment]
@JaceDeloney @moorerst @TracyLinder — heads up, this enhancement is coming to your apps at some point. :)

**Comment by amenity** [comment]
@ChrispinP @SurbhiBakshi @johnclary - making this into an epic so it doesn't stay in progress 4ever. Please create sub-issues for the chunks you do together and close as you go.

**Comment by SurbhiBakshi** [comment]
Met with @mddilley today to talk about this need. Used the Finance Portal sign in buttons as reference.

**Comment by amenity** [comment]
@mddilley - do you want me to make you an issue for 👆? We're definitely eager to get #4251 taken care of soon. :)

**Comment by mddilley** [comment]
@amenity Yes, that would be great. Thanks for checking in on this, and I'm eager as well after the VZA screen sharing the other day!

**Comment by amenity** [comment]
Super, thanks: https://github.com/cityofaustin/atd-data-tech/issues/4390

**Comment by ChrispinP** [comment]
Enabled all login pages for TDSD with COACD login. Pending any metadata changes. JS and CSS working as expected. Non-COA login working as expected.

**Comment by dianamartin** [comment]
@amenity @ChrispinP @SurbhiBakshi I was going to take a stab at coding Street Banners.

- [x] Added JS and CS (small button code)
- [x] Refresh and tested "Sign-in" button
- [x] worked as expected with auto entry
- [x] logged out
- [x] Refresh and tested "Non-COA Sign-in" button
- [x] worked as expected with manual pw entry
- [x] logged out

DONE!

**Comment by dianamartin** [comment]
I had add the new code that Mike created to the **Street Banners app** and it passed all the browser tests, the sign-in pages showed up as intended. I moved on to the SMB Tracker, I realized that various applications already had some COACD Sign-in buttons enabled. 

I continued to test their various home pages to see if I could find a sign-in page that wasn't configured to see if I even had to add the new code. I found a page and added the code, without modifying the existing code. The login page duplicated the big buttons from the previous code that was already there, so I removed it. I decided to test the SMB Tracker's login pages on the various browsers and discovered that all browsers except Internet Explorer showed up correctly. 

I thought perhaps it was just a fluke, but then I tested only on Internet Explorer v. Chrome to see if the same situation occurred. It did, the big button view that I see on Chrome looked like a sign-in page that wasn't updated. 

![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/e8fbc801-56ee-49d8-b52c-e23a2a9f9eac)

I think the code needs to be revised on a handful of applications. When I tested "Street Banners" works properly. SMB, AMD, Finance, DTS Portal do not, haven't tested the other apps yet.

**Comment by johnclary** [comment]
@dianamartin are there any console errors on Internet Explorer? It's very possible Mike used a javascript function that is not supported in IE.

**Comment by dianamartin** [comment]
@johnclary Didn't occur to me to check that, but that makes sense that could be the issue. I'll investigate it

**Comment by dianamartin** [comment]
not seeing any console errors on this page

![image](https://user-images.githubusercontent.com/21112975/103790793-4787b000-5007-11eb-9bf1-0cac733e395e.png)

**Comment by SurbhiBakshi** [comment]
@johnclary,  @dianamartin, @mddilley  and @ChrispinP - Unless you have already tried it out, we can test the COACD button on the New Builder on the Test VZA - 3rd Feb 2021 application. I got COACD logins enabled on it recently.

**Comment by johnclary** [comment]
great idea!

**Comment by ChrispinP** [comment]
I have updated the SSO code for both TDS and it is now in RPP with all login pages enabled for SSO.

**Comment by ChrispinP** [comment]
HR is now updated with SSO and all login pages enabled for SSO.

**Comment by ChrispinP** [comment]
DTS SSO code verified and enabled. Updated and cleaned up code.

**Comment by SurbhiBakshi** [comment]
hi @ChrispinP - i had enabled SSP on the DTS application when I enabled it and updated the code [here](https://github.com/cityofaustin/atd-knack/tree/master/code/dts-portal). If you made changes to limit the clickable area, please make sure to update in Github.

**Comment by ChrispinP** [comment]
Will need to create new SSO token for ROW once new app is established. ROW Prototype was the only ROW app with SSO enabled so I updated code for clarity and enabled on all login pages.

**Comment by johnclary** [comment]
Oh dang I forgot we had SSO setup for the ROW prototype. I think we can actually migrate that without too much headache. We'll need to take a look.

**Comment by ChrispinP** [comment]
@johnclary Ill go ahead and migrate it. gonna look at ROW holistically tomorrow, we should touch on data migration during or after grooming.

**Comment by johnclary** [comment]
@ChrispinP would you just make a backlog issue for it and we can pick it up during grooming?

**Comment by dianamartin** [comment]
Closing issue since ROW SSO configuration happened in a different issue
