### ISSUE TITLE
Change "Hazard Flashers" to "Flashing Beacons" in AMD Asset Map

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#3961]
> What application are you using?

Data Tracker

> Describe the problem.

In the asset map, can we change "Hazard Flashers" to "Flashing Beacons"? Hazard flashers are one type of flashing beacon. Also, if you click on the "Hazard Flashers" in the asset map, it doesn't seem to be pulling the attribute data. For example, Treadwell and Shoal Creek has a RRFB, and this is stated in Data Tracker, but the beacon type is blank in the asset map.

Internet Browser: Chrome

> Requested By
Jen D.

Request ID: DTS20-101160

**Comment by johnclary** [comment]
@jaime-mckeown let's discuss at next sprint planning

**Comment by jaime-mckeown** [comment]
@johnclary we didn't get a chance to discuss Wed. Should I schedule some time to go over this?

**Comment by johnclary** [comment]
yes please :)

**Comment by jaime-mckeown** [comment]
- [ ] Re-publish Flashing Beacons, overwrite current feature layer. CSV saved in: G:\ATD\ATD_GIS\Arterial_Management\Flashing_Beacons

- [ ] Reconfigure in AMD Asset Map, rename to Flashing Beacons.

**Comment by jaime-mckeown** [comment]
@johnclary the Flashing Beacons feature layer has been re-published:
https://austin.maps.arcgis.com/home/item.html?id=6c4392540b684d598c72e52206d774be

**Comment by jaime-mckeown** [comment]
- [ ] Re-publish Flashing Beacons with new CSV with correct coordinates.

**Comment by jaime-mckeown** [comment]
@johnclary The Flashing Beacons Feature Layer has been updated with the new data and has been updated in the Web Map. Do you have a separate Issue for fixing the script from Knack?

**Comment by jaime-mckeown** [comment]
Emailed Jen that the layer has been updated in the AMD Asset Map and that John will be getting the automatic updates from Knack going again soon.
