### ISSUE TITLE
Enhance navigation to CCTV feed

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4030]
MMC frequently wants to look at the CCTV 
- [ ] Add IP addresses to the [main Signals listing table](https://atd.knack.com/amd#signals/)
- [ ] Make 👆and the IP address on the Signal Details page into hyperlinks

**Comment by amenity** [comment]
Since there are multiple cameras per signal, would make more sense to provide this functionality on the [Cameras page](https://atd.knack.com/amd#cameras/?view_344_search=35&view_344_page=1):
- [ ] Add Signal ID column
- [ ] Make IP address hyperlink

**Comment by amenity** [comment]
Ran👆by MMC folks and they said that sounds good. With that in mind, can you size this, @johnclary ?

**Comment by johnclary** [comment]
@amenity i took care of this. the bad news is that i cannot easily add the signal ID to this page. if this is a major issue for them i can look further at what it will take to do it.

<img width="1404" alt="Screen Shot 2020-10-14 at 3 19 27 PM" src="https://user-images.githubusercontent.com/14793120/96041054-dafa7c00-0e30-11eb-92c0-9a5cc525c2a0.png">

**Comment by amenity** [comment]
@johnclary cool, thanks for the speedy work. I'll touch base with MMC-crew and let them know where we got. It was definitely a nice-to-have, not a major issue.
