### ISSUE TITLE
Create VZV Preview

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#4036]
Each month since the release of VZV, the team has had to scramble to verify whether the new month of crash data going live in VZV is accurate. This has caused distractions and context-switching issues with the team. We need to provide a tool that enables staff to review each new month of crash data before it goes live on VZV. 

**Current Options:**
- [ ] Create a dashboard in VZE that displays the new month of crash data using VZD as the data source
- [ ] Create a new dataset on Socrata that includes the new month's worth of crash data, allowing staff to verify data accuracy
- [ ] Create a SQL query using the same logic used in VZV that allows staff to quickly verify monthly crash data

@sergiogcx has already created a branch that allows the ETL to run with or without time constraints at will by just providing a flag. https://github.com/cityofaustin/atd-vz-data/pull/932

This is gonna help us in the future if we decide to create a permanent preview app and a permanent preview dataset in socrata. We could have a separate ETL that works differently in that it will feed production data without time constraints into that preview dataset.

**Comment by JaceDeloney** [comment]
Should we use [this preview](https://preview--atd-vzv-staging.netlify.app/) that @mateoclarke created and just update the frequency of when this updates. It might be useful to have this preview update nightly.

**Comment by JaceDeloney** [comment]
Notes from 10/16 meeting: 
See miro whiteboard sesh [here](https://miro.com/app/board/o9J_kiN2vpA=/)

### Action items:
1. **NEW ISSUE** Update ETL to Socrata vzd-to-socrata-test to run nightly dumps all data from VZD, no date range restrictions
2. **NEW ISSUE** Add environment variables to Netlify to differentiate between production vs master (staging)
3. **NEW ISSUE** Use Netlify config settings to make another instance from master with "preview" environment variables

For discussion, are these still needed?
- Use the correct environment variable to know which socrata 4x4 database ID to use
- Checking how the date range parameters are set. staging env should use data up to end of last month
- Look for ways to automate updates to both prod and preview
- Rename "master" to "staging" (tech debt item, do not do yet)
