### ISSUE TITLE
Expiring permits notification email

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#4066]
As city staff, I want to send a notification email to providers to let them know that their permit will be expiring in 30 days.

- [x] Send notification email 30 days before expiration date
- [ ] Send notification email to provider SPOC, CC Joseph, Mary, and Andrea (revised to shared mobility headless account)

Email notification content:

**Comment by SurbhiBakshi** [comment]
@JaceDeloney - Do you have the content from an existing email that SMO staff use for expiration notifications? I can incorporate that language into the automated notifications.

**Comment by SurbhiBakshi** [comment]
@JaceDeloney - Which email address should this notification be sent from?

**Comment by SurbhiBakshi** [comment]
The email content needs some work.
 Also I am not sure if we can put in a City seal as the background or incorporate into a header. 
 Mary asks the provider to reply all if there are any additional questions, who is the primary sender?

**Comment by johnclary** [comment]
you can find a city seal image in the RPP invoice page

**Comment by SurbhiBakshi** [comment]
Moved this back to On Deck - need to 
- [ ] look at ways to share ACH information - @surbhi will reach out to Diana to look into attachments for emails, @JaceDeloney will reach out to Mary to see what is the preferred way of getting this information to the provider.
- [ ] verify Provider contact email 
- [ ] test email notifications

**Comment by johnclary** [comment]
@SurbhiBakshi FYI any sensitive data you configure in an email would be exposed publicly through the Knack app metadata

**Comment by JaceDeloney** [comment]
**Update:**
Surbhi and I met with SM team yesterday to discuss automated emails. We decided the following:
- Automated email notifications will be sent to provider's primary POC notifying them that their permit is expiring. Email will include a link to the SMO, where they will have a log in and access to the ACH info/instructions page.

**Outstanding:**
- Need to determine if we need to support changes in "amount to be paid" for new permits. Ex, if changes to the permits pricing structure occurs, that will need to be dynamically reflected in the email content.

**Action items:**
Jace to make this issue an epic and create new issues detailing:
- Build out of ACH page in the SMO app
- Changes to Providers page
- Update of provider POCs
- Add ability to export all provider contacts
- Test automated email notification with link to SMO ACH page
- Open SMO access to providers

**Comment by amenity** [comment]
@SurbhiBakshi is going to check with Mary and Andrea on this...

**Comment by SurbhiBakshi** [comment]
Scheduled a meeting on March 2nd.

**Comment by SurbhiBakshi** [comment]
**Meeting Notes** 

1. The team would like to use a resource account as the sender. Eliminate the `reply all` in the email text. Providers can reply to the resource account. 
2. The amount to be paid (right now the amount that was paid for the permit) should be the number of devices multiplied by the amount per device. Will need to add a field to calculate those values. The amount will not change unless cleared by Council. SMO staff will keep us updated on any changes so the calculation can be changed accordingly.
3. Mary and Andrea will enter new permit information. 
4. Include resource email for Finance instead of asking Provider to send details to Van or Crystal.

**Comment by SurbhiBakshi** [comment]
Meeting notes from meeting on April 19th, 2021 in #5849

**Comment by SurbhiBakshi** [comment]
Closing this issue, additional work has been addressed in #5957
