### ISSUE TITLE
Ability to track traffic signal monitor type and IP addresses

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#4148]
> What application are you using?

Other / Not Sure

> Describe the problem.

In the Arterial Management page I would also like to ask if in the Signals in the Cabinet we could add a line for the EDI 2010ECL resettable monitors, so we can keep track of them and their IP addresses.

> How soon do you need this?

Flexible  — An extended timeline is OK

> Requested By
Kenny M.

Request ID: DTS20-101205

**Comment by johnclary** [comment]
I added a MONITOR_TYPE and MONITOR_IP fields to the `signals_cabinet` object. screenshots below. I'll let Kenny/TMC know.

![Screen Shot 2020-10-21 at 8.08.03 AM.png](https://images.zenhubusercontent.com/5caf676becad11531cc417cb/2f008d52-be84-4627-8c8e-262d1d6c189d)

![Screen Shot 2020-10-21 at 8.07.36 AM.png](https://images.zenhubusercontent.com/5caf676becad11531cc417cb/5244fcf1-4ced-488c-9d5e-28ceef018089)

**Comment by johnclary** [comment]
@dianamartin do you mind taking this issue if there's any follow-up? I cc'd you on my response.

>I added a "Monitor Type" and "Monitor IP" to the signal details page. The field is also available when you add or edit a signal cabinet. I set the Monitor Type field to "Other" for all signals.
>
> Are there other monitor types that we should add? If you have a list of which signal IDs have which monitor type and/or IP address, we can import that for you. Just let us know.

**Comment by dianamartin** [comment]
@johnclary I thought we'd have the run through the AMD project review meeting?

**Comment by johnclary** [comment]
since we're not modifying functionality i was ok with implementing it. we will still discuss at the monthly meeting.

**Comment by dianamartin** [comment]
Kenny requested adding
>...a box to show the port it is connected to. It is most often connected to port 7 but there are a few locations where it cannot be connected to port 7.

I replied
>Do you want another field for “Monitor Port”, or what would you like the field to be called?

Kenny said
>`monitor port` would be fine.

**Comment by dianamartin** [comment]
Added `MONITOR_PORT` to `signal_cabinet` object. 

- [ ] the signal details
- [ ] add cabinet form
- [ ] edit cabinet form

**Comment by dianamartin** [comment]
Emailed user
>I’ve added the “Monitor Port” field. It should be seen under the following pages: “Signal Cabinet details page”, the Cabinet page to “Add Cabinet” or “Edit Cabinet”.
