### ISSUE TITLE
Create MVP for Signal Engineers

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#4166]
This popped up as a requirement for AMD warehouse inventory. All inventory checkouts are tied to work orders, so we need engineers to start creating work orders for their own work when they need to checkout materials.

We're going to use the same work_orders object that the technicians use, and we're going to keep these work orders silo'd (so that techs don't see them and vice versa) using a "Workgroup" field that is set automatically based on which form is used to create the work order.

Todo:

- [x] create a "Workgroup" field with choices "Technician" and "Timing Engineer"
- [x] set this workgroup field based on which "New Work Order" form is submitted
- [x] update the existing work orders to Workgroup = "Technician"
- [x] filter technician work order table to exclude work orders from "Timing Engineer" workgroup
- [x] create a new work order table, details, edit, etc. specifically for the timing engineers.

**Comment by johnclary** [comment]
I've got this setup in prod and am meeting with engineers next week to discuss.  my last communication:

Signal engineers,

We recently rolled out an electronic inventory module for in Data Tracker. The signal techs have been using it for two weeks now, and we need to begin moving all AMD staff to the new electronic process. The goal is to replace the paper ICF form as soon as possible.

The inventory workflow is tied to work orders, so we need you to start creating work orders whenever you need to check out inventory materials.

I mocked something up for you to look at in the Data Tracker, with goal of keeping it as simple as possible. Whereas for signal techs we have a number of controls and approvals in place, the timing engineer work orders are not.

I’m going to be meeting with y’all on 10/21. Ahead of that meeting, would you take some time to check out what I build? 

I'm aware that we'll probably need to update the choice list for the schedule work types and problems reported. Will be looking for your input on that.

1. Login here or navigate there using the “Work Orders” drop-down menu > “Work Orders - Engineers”
2. Click the “New Work Order” button to create a new work order.
3. Once you create a work order, you will be redirected to the work order details page.
4. To add inventory materials, use the form on the bottom half of the page to add your items. Any item that has a “Source” of Warehouse Inventory will be added to an electronic ICF form that is visible to the inventory planners. When you pickup your materials from Ray or Johnny, they will mark the items as “Issued”. Please add a comment that says "TEST" if you merely testing out the system.

If this is an acceptable first start, I'd like to ask you to start using this immediately for inventory checkouts. During this transition period, you'll need to continue to fill out the paper ICF in addition to this form.

That’s all for now. Happy to answer any question before we meet next week.
