### ISSUE TITLE
[Feature] Work Orders for AMD Inspections Team and Communications Team

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#4168]
This popped up as a requirement for AMD warehouse inventory. All inventory checkouts are tied to work orders, so we need the AMD Inspections team and Communications teams to create work orders.

We're going to use the same work_orders object that the technicians use, and we're going to keep these work orders silo'd (so that techs don't see them and vice versa) using a "Workgroup" field that is set automatically based on which form is used to create the work order.

Todo:

- [ ] add an "Inspections" choice to the signal_work_orders "Workgroup" field.
- [ ] set this workgroup field based on which "New Work Order" form is submitted
- [ ] create a new work order table, details, edit, etc. specifically for the inspections team.

**Comment by johnclary** [comment]
This is going to be very similar to #4166. Trying to decide if we can use the same work order for Inspections, communications, and timing engineers. If not I will hold off on inspections and communications work orders until timing engineers is stable, and create a copy of it.

**Comment by johnclary** [comment]
We ended up using the same "non-technician" work order for all other groups.
