### ISSUE TITLE
[Reports] Replicate Financial Reports from Finance & Purchasing System

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#4216]
In Finance and Purchasing App there were 7 pages, 6 reports that were built.

Buttons above on **Current Inventory** page: 

- Inventory Request Report
- Issued Report
- Returned Report
- By Purchase Type Report
- Returns Tracking
- Inventory Management Report

**Current Inventory** - page

**Comment by dianamartin** [comment]
Called Van 10/20 to talk to her about which reports she still needed to be rebuilt in the AMD Data Tracker, she confirmed that all reports need to be accessible.

**Comment by dianamartin** [comment]
## Rebuilt
- [x] Current Inventory page
- [x] Inventory Request Report
  - `Note`: This page is slightly different now that we don't have Inventory Request and only have Inventory Transactions. Overall the table is the same, but Request IDs have been substituted with Work Order IDs.

- [x] Issued Report
- [x] Returned Report
- [ ] By Purchase Type Report
  - `Note`: Original report originated from "purchase_requests" table in Finance & Purchasing app. Report to reside there?
This table is used to generate the CT DO PO Purchase reports and the RC Payments Report
- [ ] Returns Tracking
  - `Note`: This was created for the Warehouse staff to track "Return" transactions that they needed to enter into AIMS, since they've gone away from AIMS not sure if this is still needed. Can ask Johnny/Ray or Finance (Van) if this is still necessary. 
- [x] Inventory Management Report
  - `Note`:  "Commodity Code" column is different - references "commodities" object table> "Commodities Display Name" in Finance & Purchasing app.

**Comment by dianamartin** [comment]
Scheduled review on 10/22

**Comment by dianamartin** [comment]
Van reviewed it and provided comments via email
> **Issued Report:**
Does the Issued Report show the FDU pulling from Task Order? All transactions on this report show Fund 5125- Dept. 2400- Unit 3510 but they should show the FDU based on task order type (like Memo – FDU 5125-2400-3510 but Back Chargeable should show CIP FDU).
If I download a file with Task Order and CIP FDU, will you be able to show CIP FDU on this report? This report is very important because it is used as backup document for my monthly entries to record all items issued subtotal by FDU. 
Also, I don’t need the Column showing “Staff” so please change that column to “AIMS #” so John & Ray can put in OC ticket number during the trial/dual period.

>**Inventory Management Report:**
If the SKU numbers are the same as Commodity Code, then there is no need for another column to show Commodity code.
If the SKU numbers are different than commodity code, then I need to have a column for commodity code because the purchases and reconciliation are recorded by commodity code.

**Comment by dianamartin** [comment]
Had meeting with Van, Peggy, John to discuss changes to these reports and clarifications. 

## Notes
Van to requested the same user role to be able to modify the FDUs in the AMD Tracker
- We could add Inventory Status to report or
- Exclude "Inventory Status" doesn't have to include records that haven't been reviewed yet

Van's concern is that inventory items that are pulled may be stuck in queue, she'd like the ability to help adjust and change FDU so she can run the reports.

John said, we don't have that data right now, but if it exists then we can get it from the Comptroller's site potentially. Van was going to reach out to her contact to see if we could get the data.

"Buyer FDU" is something that Van is trying to pull out of MicroStrategy along with FDU information. 
- She's hoping we can pre-populate the FDU/Task Orders into the table or connects it
- Would like task order and FDUs to be connected automatically

#### Returns Reports
- [ ] Add `AIMS #` field
- [ ] Remove "Staff/Customer" on table

#### Timeline
October 1st - filter out "Inventory Mgmt Report"
Perhaps Nov. 16-20th - Reconciliation in a week
- Decided to pull for Wednesday to compare on the reports

### Add these to all reports globally
- Commodity Code - replace `SKU`
- Commodity Name - replace `Product`

## Changes
Issue Report - The `AIMS #` was the wrong field, changed it and the number started to show up again. Van requested that we associate the task order number and FDU info together.

**Comment by dianamartin** [comment]
After I made the changes, I messaged Van so she can review or let her know the reports are ready for review.

**Comment by dianamartin** [comment]
@johnclary Van reviewed the report changes and is good with the changes. She's just waiting on the Task Order/Buyer FDU sync of information. Should I close this?
