### ISSUE TITLE
AMD performance measure highlighting error

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#4224]
> What application are you using?

Data Tracker

> Describe the problem.

In the performance measures for measure 9197, we want to be less than or equal to 150. This year we were at 119, which is good! But the box is highlighted red, indicating we didn’t meet our metric. Can we get this changed?

> Requested By
Jen D.

Request ID: DTS20-101235

**Comment by johnclary** [comment]
@dianamartin lets discuss next week

**Comment by dianamartin** [comment]
Meeting scheduled 10/28

**Comment by dianamartin** [comment]
## Diana's Notes
9197 AMD
Below 150 - is GOOD
Would like it to be Green color

- Goes against the formula we have now

9244 TDM - Transportation Demand Mgmt
Below 1.3 - is GOOD

## STEPS

- [ ] Add "Target Direction" field -  Higher or Lower to `performance_measures` object
- [ ] Text Formula to get "Target Direction" On Fiscal object

Main performance measure table
- [ ] TO COLOR GREEN/RED: current display rule "expected_minus_approved" higher than 0 = GREEN
- [ ] add new filter "expected_minus_approved" higher than 0 + "Target Direction" is Higher then GREEN.

**Comment by dianamartin** [comment]
- Created `TARGET_DIRECTION` - multi-choice 
  - Set `Higher` as default for 272 records
- Added new filter that John and I discussed
> filter "expected_minus_approved" higher than 0 + "Target Direction" is Higher then GREEN

This didn't work. So I changed the 2 performance measures **(9197 & 9244)** to `Lower` and changed the filter on the `performance_measures_fiscal` table on the Main Performance Measures page. 

New Filter: 
- "Target Direction" is "Lower" then GREEN

### 9197
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/eec6d67f-b13c-4eba-9a21-b9a2d5e7daba)

### 9244
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/de99d516-85a3-4ba2-9017-3c66f2cd60dc)
It worked!
