### ISSUE TITLE
Tracy's Sprint 36 AMANDA Backlog Tasks

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#4239]
### UAT Ready
- [x] #1726 needs UAT in test
- [x] #2632, #2631, #2634, #2983 needs UAT in test (TIA updates)
- [x] #1713 (Test)
- [x] #3465 (Test, Performance measure report)
- [x] #1630 TCI Report (Test)
- [x] #1742 Test Ready

### Respond to Email / Clarifications / Demo
- [x] #1742 

### Other
- [ ] #3596 - Do data pull
