### ISSUE TITLE
Feature: Building SMB Contractor Tracking objects & connections

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#4259]
### Build new objects
- [x] `contractor_work_tickets` - Primary, Secondary Street, Feature ID (copy here), Work Order fields...
- [x] `contractor_inspections`

### Build connections
- [x]  Attachments table (exists) - connect to `contractor_work_assignments` (Photo attachments for SMB inspector)

### Add new fields to existing objects
- [x] `inventory_items` (materials)
 - Bid Item Number
 - Contractor Name
 - Unit
 - Unit Price  

#### Reference Information
Entering materials used form - Similar to AMD Construction Cost Estimate

    Activity - Installed, Removed, Maintained, Layout
    Marking Type/Material Name`
    Type
    Color
    Width
    Length (ft)
    Unit Price
    Total

Inspections process - returning to contractor to fix issues

    Button to update:
        Inspected field (Y/N),
        Inspected By,
        Inspected Date
        Issue/Comment,
        Inspection Status - default "Inspected - Pass/Fail",
        Follow-up (Y/N) default based on "Inspection Status"
    Inspection table has fields listed above but also another field for contractor to change
        Follow-up Status (Needs Correction/Resolved)
    Work Order would have buttons on the top like the (technician work orders)
        Submit - Form
            Contractor Signature
            Phone Number
            Date - default

### GIS TASK
new: build GIS layer (maint, AGOL) - Contractor Work Orders, Feature ID (originates here)
   
    
    Materials Used table (existing, just add new fields)
    Material Contractor (Name, Unit Cost)

**Comment by dianamartin** [comment]
Ultimately, created a new object table for the materials as well. 

### Object tables created
- contract_vendor
- contract_bid_items
- contractor_inspections
- contractor_materials_log
- contractor_work_order

### Existing tables
- work_orders_signs_markings_attachments
