### ISSUE TITLE
Feature: Build Contractor Work Tickets page

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#4260]
- [x] Build Page
- [x] Build Form
- [x] Test Add Form Creation
- [x] Test Edit Form

**Comment by dianamartin** [comment]
### Created Pages

- [ ] "Work Tickets | Contractors"
- [ ] "Add Contractor Work Tickets"
- [ ] "Contract Work Ticket Details"
- [ ] "Edit Contractor Work Ticket"

### Created Forms/Buttons
- `Add Contractor Work Ticket`
- `Edit Contractor Work Ticket`
