### ISSUE TITLE
Meeting: Inventory Check-In 10/27/20

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#4270]
### Objective 
Check-In with AMD staff on warehouse inventory
### Participants
Nicholas Merrick, Frank, John, Diana, Billy

### Agenda
Add agenda here or create agenda from [this template](https://docs.google.com/document/d/1d_49KW5C_vSz8Bs50v-cxyIJuTNJMwMrh7ypcxRHgZI/edit#) and add link. 

------
- [x] Schedule meeting
- [ ] Optional: Schedule debrief
- [x] Meet and take notes
- [ ] Optional: Debrief with DTS team members
- [ ] Create resulting issues

**Comment by dianamartin** [comment]
ugh..i lost my notes. Now I have to recall what happened.

Diana's Notes

Johnny asked who review FDU Review 
John said it was Ronnie

Wanted to know current FDU process
- John scans ICF to Ronnie
- Ronnie emails back

John is getting Ronnie trained up on FDU Review, so he can do them in the system. 

Frank asked when the Go Live was going to be for everyone in AMD
John said tentatively **Dec 1st**
- He's been meeting with other AMD groups to get them to start turning in digital ICF forms
- thinks by the end of the week that the AMD inventory planners can expect everyone to fill out Inventory work order request and stop expecting paper

### Issues
- When a line item request is cancelled, Johnny can't close it out. It's stuck in "Needs AIMS Entry"
- Also happens when items are returned

### Inventory Items discussion
- Inventory Planners are going to change/modify the "Common Names" in the system
- Supervisors will discuss among themselves to figure out the best common names and get with the planners
- ICF form has some SKU that aren't in the system yet @johnclary Should I enter them in or should AMD planners do that?
- [x] Make sure all inventory items have "Common Name" or they won't show up on pick list - DONE
- Inventory Items list is only editable/accessible to "Inventory Editor" user roles

**Comment by dianamartin** [comment]
@johnclary closing, not sure if you have any other notes for this meeting
