### ISSUE TITLE
Meeting: Review SMB Contractor Tracking (10/27)

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#4278]
### Objective 
Review SMB Contractor tracking, see what changes were made since last discussion on 10/26

### Participants
Christina, Diana

### Agenda
Add agenda here or create agenda from [this template](https://docs.google.com/document/d/1d_49KW5C_vSz8Bs50v-cxyIJuTNJMwMrh7ypcxRHgZI/edit#) and add link. 

------
- [x] Schedule meeting
- [ ] Optional: Schedule debrief
- [ ] Meet and take notes
- [ ] Optional: Debrief with DTS team members
- [ ] Create resulting issues

**Comment by dianamartin** [comment]
Contractor 
- [ ] Status in "Final Review ", on "Submit for Final Review", create an error message 
- [ ] Add "Instructions/Comments" on work order
- [ ] Update verification statement for "Submit for Final Review" form

**Comment by dianamartin** [comment]
I will create a new issue for the rest of the feedback tasks
