### ISSUE TITLE
Feature: Update/Modify Feedback Tasks, Build Contractor Reports page for contractors

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#4281]
### Contractor 
- [x] Status in "Final Review ", on "Submit for Final Review", create an error message 
- [x] Add "Instructions/Comments" on work order object
- [x] Add "Instructions/Comments" on work order Contractor Work Order Details
- [ ] Update verification statement for "Submit for Final Review" form
- [x] Add filter on "My Work Orders" table
- [x] Add "Follow-up Issue" on "My Work Orders" table

#### BUILD CONTRACTOR REPORT
- [x] Advanced Search page?
- [x] filter by the date
- [x] Add table that shows material logs for logged in account
- [x] exportable for contractor

### SMB Staff
- [x] Add "Instructions/Comments" on work order
- [x] Add status colors to Contractor Details page (contractor) - Inspection Status/Follow-up Status 
- [x] Moving "Issue" button to main work order contractor table
- [x] Add filter on "Contractor | Work Orders" table
- [x] Add "Instructions/Comments" on work order Add Contractor Work Order form
- [x] Add "Instructions/Comments" on work order Edit Contractor Work Order form

#### CONTRACT ITEMS
- [x] Add edit button on the table side

## Things Christina is doing 
- [ ] Provide spreadsheet for bid items
- [x] Provides work assignments to import for testing

**Comment by dianamartin** [comment]
Closing, other outstanding tasks have their own issues opened for them
