### ISSUE TITLE
Import SMB Contractor Bid Items list

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#4290]
- [x] Need to receive spreadsheet form Christina
- [x] Delete test items
- [x] Import bid items into system
- [x] Review & confirm items with Christina

**Comment by dianamartin** [comment]
- [x] Importing in 110 items from `contractor_materials.csv`

**Comment by dianamartin** [comment]
- [x] Looked at the all items, some came in with weird symbols. 
- [x] Fixed those records
