### ISSUE TITLE
Clean object tables before go-live, set up emails

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#4291]
## Remove test records in object tables
- [x] `contractor_bid_items`
- [x] `contractor_work_order`
- [x] `contractor_material_log`
- [x] `contractor_inspections`
- [x] `work_order_signs_markings_attachments`
- [x] `work_order_signs_markings_time_log`

## Set up actual contractor accounts/emails
- [x] Contractor 1
- [x] Contractor 2

## Set up actual accounts/emails for other email notifications
- [x] "Submit for Review" button email notification
- [x] "Approve" button email notification
- [x] "Mid-Project Inspection" button email notification

**Comment by dianamartin** [comment]
Christina is going to talk to Tooran about contractor emails and which one to use, so we'll address this on Monday

**Comment by dianamartin** [comment]
# Round 2 Testing 
## Remove test records in object tables
- [x] `contractor_bid_items`
- [x] `contractor_work_order`
- [x] `contractor_material_log`
- [x] `contractor_inspections`
- [x] `work_order_signs_markings_attachments`
- [x] `work_order_signs_markings_time_log`

**Comment by dianamartin** [comment]
- [x] Cleaned up all the test records with Christina
- [x[ Rolled back the work orders statuses to "Issued". 
- [x] Deleted all related records from the folder 
- exported table to check if all fields were clean
- Christina will test one more time the whole process to make sure things look good
- will delete on 11/13

@SurbhiBakshi Only outstanding thing is to change the email to the actual contractor's email in the back end so they can reset their passwords.

**Comment by SurbhiBakshi** [comment]
@amenity - reached out to Christina to check on replacing test emails with actual contractor emails. Waiting to hear back.

**Comment by SurbhiBakshi** [comment]
Heard back from Christina that contractor emails will need to be replaced next week.

**Comment by SurbhiBakshi** [comment]
Checked back with Christina on contractor emails, she will get back to me when she gets them, should be soon.

**Comment by SurbhiBakshi** [comment]
Have not heard from Christina. Think this came up in the Prioritization meeting, and the whole contractor process has been postponed? Will need to check with Christina.

**Comment by dianamartin** [comment]
When I chat with Christina on Friday 3/12, I'll ask her about this

**Comment by dianamartin** [comment]
Messaged Christina this morning 4/20
>Morning, did you guys end up meeting with the contractors yets? Tooran/Joe Mike need to do usability testing?

**Comment by amenity** [comment]
Tooran is moving to DSD; will need to run this by her replacement.

**Comment by dianamartin** [comment]
- Changed contractor email for SEFBO
- Christina confirmed that we are okay to change the emails to "Go Live" emails, to Kati
  - Kati can always request to be removed from the emails if it becomes overwhelming
- Confirmed all email configurations have "Go Live" user emails in

**Comment by dianamartin** [comment]
# Delete Test Records
- Christina and I already went through to the work orders and she gave me the instructions on which to delete and keep
## To Keep
Work Auth 13 in `CLOSED` status

## To Delete
`CLOSED` Status
- [ ] Ref # `156` 
  - [ ] 2 inspections
  - [ ] 1 time logs

`APPROVED` Status
- [ ] Ref # `6` 
  - [ ] 1 comment
  - [ ] 1 inspections
  - [ ] 2 time logs

- [ ] Ref # `152` 
  - [ ] # `153` related follow-up
  - [ ] 1 attachment
  - [ ] 1 inspection
  - [ ] 52 time logs

- [ ] Ref # `157` 
  - [ ]  3 inspections
  - [ ]  3 time logs

`ISSUED` 
- [ ] 106 Work Orders to DIJ? Confirm with Christina

**Comment by dianamartin** [comment]
Messaged Christina to review
>I deleted all the records for the Contractor Work Orders we discussed, what's left is
- 40 `ISSUED` work orders for SEFBO
- 19 `CLOSED` work orders from DIJ

**Comment by dianamartin** [comment]
Messaged Christina 5/25
>Did you get a chance to see the remaining SMB Contractor Work Orders in the system? If it's good I'll close the issue I have for it

**Comment by dianamartin** [comment]
C reply
>Closing that issue would be great! I'll probably send a request on Thursday afternoon to delete 2 more records because I'm going to Cameron Rd to work with Joe Michael a little more on the work order inspections (we met on last Thursday to walk through it but I'm going to get the page set up on his tablet so he can easily inspect.
