### ISSUE TITLE
Builder huddle to plan Data Tracker updates

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#4296]
Scheduled for 11/3

#### Participants
John, Diana, and Renee

[Workflow](https://miro.com/app/board/o9J_kgqqLXE=/)

**Comment by johnclary** [comment]
@dianamartin plz schedule

**Comment by johnclary** [comment]
@amenity FYI looks like Diana will have bandwidth to do this work

**Comment by dianamartin** [comment]
@johnclary schedule, but not sure if you're available for it

**Comment by dianamartin** [comment]
Reviewing the spreadsheet that Renee initially provided

#### Fields to include from spreadsheet
Type: Signal/PHB
Location: Location Name

**Comment by dianamartin** [comment]
# Part 2 Task
### TO DO
- [ ] (AMD) will creating PDF of the recommended and ranked signals and pdf - upload to city website 
- [ ] (AMD) will give us link to use to post to dashboard page

### Changes to Signal Request Dashboard 
- [ ] DEV: remove Map
- [ ] DEV: remove List
- [ ] DEV: Update text copy

### Changes to Open Data Portal 
- [ ] APPS: Cleaning up Signal PHB Request (Traffic Evaluations)

### Changes to Data Tracker - Apps
- [ ] (AMD) Renee will update Signal Requests - add traffic evaluations for 2020 for ones that are to remain
- [ ] APPS: Remaining locations/evaluations will be "Archived"

**Comment by dianamartin** [comment]
@johnclary  I scheduled another 30 min meeting on Monday so I can ask about field headings and her vision of the new refactor to make sure I've got all the details. I also invited her to the builder huddle in case you had questions for her as well.

**Comment by dianamartin** [comment]
## Questions for Renee

- Do you want the GIS data analysis scores to reside in Data Tracker?
- What happens to the scores?
- Did you need the ranking to live in the Data Tracker?
- Which status needs to have the new "Archived"  - Request Status v. Evaluation Status?
- How are studies going to be connected to evaluations?
- Will you do a study at the same location, multiple times (more than once ever?)
- Would you do a signal study one year and PHB study the next year?
- Will PHB evaluations be part of that list on the Open Data Portal?

**Comment by dianamartin** [comment]
@johnclary  add any notes you took here, then I'll close it or set-up a follow-up discussion with you
