### ISSUE TITLE
Import New Crash Location Polygons

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#4302]
The VZ Team is creating new polygons to make some small changes to existing polygons, as well as to accommodate the association of level 5 crashes to locations. We are still waiting for the updated locations from the team, but we can go ahead and break down the work needed to make this update, especially if there were lessons learned from the previous locations import.

@frankhereford  and  @sergiogcx have been meeting to outline next steps on import and testing of new polygons. Please list the technical steps needed to complete the location polygon update and backend portion of this project.

Steps as outlined in #4354
- [x] Update Vision Zero polygons (including updates to the existing polygons and new Level 5 street levels) in the database
- [x] Make sure VZE only shows level 4 and below, within the VZE configuration this should be an easy fix
- [x] Update ETL: https://github.com/cityofaustin/atd-airflow/blob/master/dags/python_scripts/atd_vzd_update_cr3_locations.py
- [x] Update AWS triggers if needed.

**Comment by sergiogcx** [comment]
This is done, closing.
