### ISSUE TITLE
Implement Automated CR3 Narrative and Diagram Extraction

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#4303]
Frank found python libraries that make short work out of extracting the narrative and diagram from CR3s. Frank now has a program that renders the PDF into a series of images, and then crops those images to isolate the narrative and the diagram. The diagram is saved as an image. The program then takes the narrative and feeds it into Google’s Tesseract Optical Character Recognition (OCR) library which they kindly have open sourced. Out of that comes the narrative text. This uses open source and free libraries.
 
Frank suggests that because the CR3 reported crashes are already well enumerated by the VZ database and the PDF files are already collected in the S3 bucket by the DTS team, there is going to be relatively little friction to get the great bulk of these CR3s parsed. Frank can’t anticipate what wrinkles might come up as he unleashes the program onto thousands of PDFs, but thinks this could be more promising.

There are two main bodies of work to complete this project, outlined below:

**Backend extraction script tasks**
- [x] Create and processes a backlog of un-OCR’d crashes
- [x] Python script that accesses VZD
- [x] Downloads PDF for the crash
- [x] Create image and crop portion of page (diagram and narrative)
- [x] OCR the image
- [x] Extract text, diagram as png
- [x] Saves the files in the S3 bucket
- [x] Update the crash record in Hasura

**Add text and diagram to VZE**
- [ ] Display Narrative as text and diagram as png on Crash details page
- [ ] Download File on Crash index page, crash details page, and location details page

**Comment by amenity** [comment]
Frank has been asked to de-prioritize this.

**Comment by sergiogcx** [comment]
@frankhereford has implemented all of it and it is working.

I have created the DAG and it is active in production. It runs 100 records every 10 minutes. With some napkin math, we deduced it would take some 19-20 days for all records past 2015 to be processed.

**Comment by JaceDeloney** [comment]
This is great news! Congrats @frankhereford
