### ISSUE TITLE
Feature: Make "Dates Worked" form not show up in "Issued" status

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#4305]
User is Issued WO
WO is completed
Add Date Worked (delete button)
Add Materials Used (delete button)
Submit for Final Review

Date Worked table (Non editable, no delete button)
Materials Used table (delete button)

**Comment by dianamartin** [comment]
Reviewed the "Work Order Details" Page rules and I already had a rule making the Material Log form not show up in an "Issued" status, I just added the "Time Log form" and it also didn't appear. Was easier than making a separate non-editable table.

**Comment by dianamartin** [comment]
- [x] renamed `work_orders_signs_markings_time_logs` to `time_logs | w/ DELETE BUTTON`
- [x] Created `time_logs | w/o DELETE BUTTON`
- [x] renamed `contractor_material_logs` to `contractor_material_logs | w/ DELETE BUTTON`
- [x] Created `contractor_material_logs | w/o DELETE BUTTON`

**Comment by dianamartin** [comment]
Reviewed and signed off by Christina
