### ISSUE TITLE
Phases and Milestones | Create project phase table to add/edit phases

### ISSUE THREAD

**Issue by zappfyllc** [cityofaustin/atd-data-tech#4332]
As a Moped user, I want to view a list of phases a project has advanced through, including dates and links to milestones completed within that phase, so that I can understand a project's lifecycle.

**Wireframe**
https://balsamiq.cloud/senhupm/p9y6tuy/r0869 (top table of this page)

**Details:**
- [x] Phases dropdown should populate from moped_phases
- [x] Data source: moped_proj_phases
- [ ] "View milestones" should link to view with list of milestones by that phase (#4335 is the issue for that view)
- [ ] "Add Phase" should log the user who added the next phase and store in the database as well ("Created By")

**Comment by zappfyllc** [comment]
Initial seed data for phases:
- Construction
- Design
- Planned
- Potential
- Scoping

**Comment by zappfyllc** [comment]
Table is implemented; ready for review @amenity and @zappfyllc

**Comment by mateoclarke** [comment]
The first two bullets are addressed in this PR: 
https://github.com/cityofaustin/atd-moped/pull/187

Will come back the the 3rd once we implement the Milestones by Phase table in https://app.zenhub.com/workspace/o/cityofaustin/atd-data-tech/issues/4335

4th one sounds like it might get implemented in a wholistic sweep of `created_by` & `modified_by` schema updates on the DB and accompanying mutation tweeks on the front end. TBD based on more convo with @zappfyllc 

Here is the preview link:
https://deploy-preview-187--atd-moped-main.netlify.app/
