### ISSUE TITLE
Update labor wages for invoicing in Data Tracker for SMB

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#4352]
> What application are you using?

Signs & Markings Operations

> Describe the problem.

Update labor wages for invoicing:
        
- [x] Technician - Direct: $26.11
- [x] Technician - Indirect: $95.82
- [x] Technician – Direct Overtime Rate: $39.17
- [x] Superintendent/Engineer/Division Manager – Direct: $42.11
- [x] Superintendent/Engineer/Division Manager – Indirect: $149.84
- [x] GWS Contractor: $27.31

> Describe the outcome you'd like to see when this feature is implemented.

For the labor wages to be updated to reflect costs in FY2021.

> Describe any workarounds you currently have in place or alternative solutions you've considered.

N/A

> Requested By
Christina T.

Request ID: DTS20-101280

**Comment by amenity** [comment]
@dianamartin — size, plz?

**Comment by dianamartin** [comment]
sized, small.

**Comment by dianamartin** [comment]
Scheduled short meeting with Christina to talk about this request 11/4

**Comment by dianamartin** [comment]
Christina and I updated the hourly rates and tested it
![image](https://user-images.githubusercontent.com/21112975/98161175-ecb9c700-1ea4-11eb-83e1-6f7668ead30d.png)
