### ISSUE TITLE
Create Studies object and import studies

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4379]

**Comment by dianamartin** [comment]
### FIELD NAMES
(From Green Spreadsheet)

**Type:** Signal/PHB _(exists on the Main Signal Requests table..)_
**Location:** Location Name - REQUEST_NAME (Similar)
**Data Collected:** Yes/No - `DATA_COLLECTION_COMPLETE`
**Data Collection Assigned To:** COA/AECOM - `DATA_COLLECTOR`
**Study Source:** Traffic Engineering, 2016 Ranking, 2017 Ranking
**Study Assigned To:** COA-Ed, Consultant - `STUDY_ASSIGNED_TO`
**Draft Report:** Yes/No - NEW!
**Final Report:** Yes/No - NEW!
**Study Status:** Turned in, waiting for WB volume, Ed almost done - `REQUEST_STATUS_PRE_CON`

`STUDY_DATE` - keep this field, only available when study has been completed
`STUDY_NOTE` - keep this field
`STUDY_STATUS` - keep this field
`STUDY_ATTACHMENT` - keep this field

Keep all other fields like "Pedestrian Counts" - from phb study table
Keep all other fields like "Warrant_1-9" - from signal study table

**Comment by dianamartin** [comment]
### Migration Effort
- [x] Export the `signal_request_signal_studies` 
- [x] Export signal_request_phb_studies` table
- Manipulate in excel to have the fields Renee wants for new object table
- Re-import to create new `Studies` table
- Export `Studies` table
- Update `signal_studies` table with connected ID to Studies table
- Update `phb_studies` table with connected ID to Studies table
- Import  `signal_studies` to create new `studies_signal_studies` table
- Import  `signal_studies` to create new `studies_phb_studies` table

**Comment by dianamartin** [comment]
- [x] created `studies` object table

#### Fields
LOCATION_NAME - map to Location Name from Locations table
STUDY_ID - `auto increment`
STUDY_TYPE - same `multi-choice` selection from `signal_requests`
DATA_COLLECTION_COMPLETE - Data Collected: `Yes/No`
DATA_COLLECTOR - `Multi-choice` - Data Collection Assigned To: COA/AECOM
STUDY_SOURCE - `Multi-choice` - - Study Source: Traffic Engineering, 2016 Ranking, 2017 Ranking
STUDY_ASSIGNED_TO - `Multi-choice` - - Study Assigned To: COA-Ed, Consultant 
DRAFT_REPORT - `Yes/No` (Brand new tracking fields)
FINAL_REPORT - `Yes/No` (Brand new tracking fields)
STUDY_REQUEST_STATUS - `Multi-choice` - Study Status: Turned in, waiting for WB volume, Ed almost done - `REQUEST_STATUS_PRE_CON`
- CONSTRUCTED
- CONSTRUCTION
- INELIGIBLE
- NOT RECOMMENDED
- RECENTLY RECEIVED
- RECOMMENDED
- STUDY
- UNDER EVALUATION

STUDY_DATE - `Date` - Date of study
STUDY_NOTES - `Short text` - Notes about study
STUDY_STATUS - `Multi-choice` - New, In Progress, Complete
STUDY_ATTACHMENT - `File` 
STUDY_ATTACHMENT : URL
WARRANT_1 - on signal study table
WARRANT_2  - on signal study table
WARRANT_3  - on signal study table
WARRANT_4  - on signal study table
WARRANT_5  - on signal study table
WARRANT_6  - on signal study table
WARRANT_7  - on signal study table
WARRANT_8  - on signal study table
WARRANT_9  - on signal study table
PED_BEFORE_DATE  - `Date` - on phb study table
PED_BEFORE_DATE_2  - `Date` - on phb study table
PED_BEFORE_AM  - `Number` - on phb study table
PED_BEFORE_MIDDAY  - `Number` - on phb study table
PED_BEFORE_PM  - `Number` - on phb study table
PED_BEFORE_TOTAL  - `Equation` - on phb study table
PED_AFTER_DATE  - `Date` - on phb study table
PED_AFTER_DATE_2  - `Date` - on phb study table
PED_AFTER_AM  - `Number` - on phb study table
PED_AFTER_MIDDAY  - `Number` - on phb study table
PED_AFTER_PM  - `Number` - on phb study table
PED_AFTER_TOTAL  - `Equation` - on phb study table
PCT_INCREASE  - `Equation` - on phb study table
CREATED_DATE  - `Date` - Date of Creation
CREATED_BY  - Person creating record
MODIFIED_DATE - `Date` - Date of Modification
MODIFIED_BY - Person modifying record

**Comment by dianamartin** [comment]
# Import signal and phb studies tables into `studies` object table

- `signal_requests_phb_study`
- `signal_requests_traffic_study`

**Comment by dianamartin** [comment]
# To Do
"Study Location" object table
Location ID
Signal Requests - Y/N
Number of Signal Requests - 
Study Location Status:  PreConstruction Status
Funding Status: Recommended/Not recommended

Locations > Study Location > Studies

**Comment by dianamartin** [comment]
Scheduled review/demo with Renee for 11/12

**Comment by dianamartin** [comment]
Followed-up with Renee 2/10. Asked if we could close it because there didn't seem to any outstanding things to do. We'd create new issues if anything was missing.
