### ISSUE TITLE
Build DOSAs in Data Tracker test environment

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4380]

**Comment by dianamartin** [comment]
@johnclary I have questions for you on which how many signals work order details pages there are. If we will eventually need to coordinate with the Dev group to add this to the mobile signals interface?

**Comment by dianamartin** [comment]
### AMD WO STRUCTURE 
- My Work Orders table - filtered by logged in user
  - My Work Order Details 

- Work Order (Signals)
  - Work Order - Technicians
    - Work Order Details

- Work Orders (Other) - Non-technician
  - Work Orders (Non-technician)  
    - Work Order Details

### Creating DOSA Object
- [x] created `dosa_tracking` object table

**Comment by dianamartin** [comment]
DOSA UI

**Comment by dianamartin** [comment]
Scheduled short demo meeting with Frank and Nicholas. Frank was unable to make it, Billy was out of town. Will make another meeting for next Thursday. 

### Meeting Notes
**Button location:** I had button on top menu bar with the "Edit Work Order" button and another one right above the DOSA table. We talked about removing it from the top menu and keeping the stand alone form button. Also talked about prototyping embed form into the work order details page directly to see what that looks like. 

**Traffic Control Plan field:** 
- [ ] add selection for "Other Traffic Control Plan"
- [ ] add short text field to describe the "Other Traffic Control Plan"

**PPE Field:**
- [ ] Spell out "Example", instead of "Ex." to make it more obvious

**Other Changes:**
- [ ] Test all submission situations to see which ones reject and have error message, some required fields allowed me to submit without filling into information
- [ ] Test on tablet to see what user experience is like
- [ ] Update Form Rule on "Submit" button to give error if DOSA hasn't been completed before submission
- [ ] If stand alone button color can match the other ones "dark blue, white text" - will see if form embed looks better to see if we have to go with custom code to fix it

#### Feedback
- Likes the DOSA layout, quick and simple.
- Set up follow-up meeting next Thursday at 11 am - DOSA review

**Comment by dianamartin** [comment]
## My Work Order Details
- `Add DOSA form` embedded in page (the mobile optimization is already turned on globally if on mobile device)
- `DOSA tracking table | Editable`
  - `Edit DOSA form` - modify audit fields (form rules)
- `DOSA tracking table | Non-Editable` - when "CLOSED" status (Need to update page rule)

#### Page Rule
**RULE 1**
- Work Order Status is `not` "Submitted", 
Work Order Status is `not` "Closed"  
Hide: 
`Work Order Completed Fields details`
`DOSA | Non Editable table`
`Work Order Time Log | Non-Editable table`

**RULE 2**
- Work Order Status is `not` "Assigned", 
 Work Order Status is `not` "Unassigned",  
Work Order Status is `not` "In Progress", 
Work Order Status is `not` "Assigned" 
Hide: 
`Menu menu`
`Add DOSA form`
`DOSA | Editable table`
`Add Time Log form`
`Work Order Time Log | Editable table`
`Add Inventory Form`
`Add WO Image form`

## Work Order Details (Technicians) - All Work Orders
- `Add DOSA form button` - Create audit fields (form rules)
- `DOSA tracking table | Editable`
  - `Edit DOSA form` - modify audit fields (form rules)
- `DOSA tracking table | Non-Editable` - when "CLOSED" status (Need to update page rule)

**Page Rule**
- Work Order Status is "Closed" 
Hide: 
`Admin menu`
`DOSA Button menu`

**Comment by dianamartin** [comment]
@johnclary 

# Mobile Optimization
Work Order Details (Signals - Technicians)
- Add DOSA button is small on tablet (not sure if we can enlarge this one button or if it's connected to all buttons globally)
  - this would only affect it on the "Work Order Details (Signals - Technicians)" view, the "My Work Orders" is not affected
- Form opens and submit button an other fields are already optimized

**Comment by dianamartin** [comment]
Review meeting scheduled with Billy, Frank and Nicholas. They were able to review and we made some minor changes, they approved the DOSA forms. I said I'd get it done!

- [ ] Adding DOSA to AMD Production

**Comment by dianamartin** [comment]
Closing, will create new issue for "Build DOSAs in Data Tracker PROD environment"
