### ISSUE TITLE
Update signal evaluations to new scores criteria and statuses

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#4385]
- [x] Renee will update Signal Requests - add traffic evaluations for 2020 for ones that are to remain
- [x] Remaining locations/evaluations will be "Archived"
- [x] Update scoring methodology

**Comment by johnclary** [comment]
here's the doc which outlines the scoring changes:
[https://app.zenhub.com/files/140626918/35baf206-6024-460a-976d-d36194e16ebd/download](https://app.zenhub.com/files/140626918/35baf206-6024-460a-976d-d36194e16ebd/download)

**Comment by johnclary** [comment]
we're still waiting on Renee to let us know when we're clear to proceed.

**Comment by johnclary** [comment]
Waiting for feedback from Renee

> OK, I've implemented the new traffic signal scoring.
> 
> As we discussed, I had to delete all previous traffic signal evaluations from the system to do this, because their scores would have been affected.
> 
> As well, I set to “Archived” status any signal request that was “Under Evaluation” and had no PHB or signal evaluations.
> 
> How would you like to handle PHB requests and evaluations in the system? We could remove them entirely, “Archive” them, or ...?
> 
> I assume we will want to adjust some things, so please take a look and let me know. Happy to discuss as well.
> 
> For your records, I’ve attached copies of all the signal requests, evaluations, and studies before I made these changes.

**Comment by amenity** [comment]
Renée has looked at this; good to go.
