### ISSUE TITLE
Tracy's Sprint 37 Backlog Work

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#4389]
11/16

- [x] #3526 (addendum) 
- [x] #2444 TCI inspections
- [x] #1742 TCI
- [x] #3302 Finance Report
- [x] #1802
- [x] #1630

-----

- [x] #1742 ready for DEV/TEST UAT
- [x] Review #1630 sample output
- [x] #3526 look at sample output
- [ ]  #3596 - Do data pull
- [x] #1802 watch demo 

----
**Done**

- [x] #3526 Report update in Dev & Test
- [x] #1742 - Completed and submitted the report for review. on 11/3/2020 and waiting for feedback.
- [x] #1630 - Completed and sent the new format in excel for review on 11/2/2020
- [x] #2983 Watch demo sent by Ash and Sree/ Nate has the demo if I can't open it
- [x] #3168 review sample sent by Subha
- [x] Make epic for #2395 & #4282
- [x] #3851 follow up with Mike Jones
