### ISSUE TITLE
Feature: Build AMD PHB and Signal Studies Pages, Tables, Forms

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#4403]
# Created Pages, Tables and Forms
- `Studies` page - main page
  - Studies details page 
- Edit Studies form

**Currently don't have an `Add Studies` form**

**Comment by dianamartin** [comment]
Had feedback meeting with Renee. 

There are some changes that we made together, these are the changes left to do.

- [ ] Warrant 6 - remove 
- [ ] Warrant 7 - "False/True"
- [ ] Add "New Study Location" button on Location details 
- [ ] Clean up Study Location Details
- [ ] import phb study records - 211

- Attachment links - keep until we attach to new "studies" table

- [x] Safety - RED 
- [x] Delay - ORANGE
- [x] Program - BLUE
- [x] Fiscal - GREEN

**Comment by dianamartin** [comment]
Followed-up with Renee 2/10. Asked if we could close it because there didn't seem to any outstanding things to do. We'd create new issues if anything was missing.
