### ISSUE TITLE
Discuss SMB Contractor feedback meeting with internal SMB 

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#4412]
Christina met with her colleagues and demo'd the SMB contractor tracking. This meeting is to discuss the feedback they had and if any modifications are necessary.

**Comment by dianamartin** [comment]
## Daily Tickets
Work Order: Starts in October but continues in November 
Invoice in October and separately in November
- [ ] Adding `Date` to Materials Used line item

#### Inspection Process change
- Wants to know `Issued` work (filter WO with materials)
  - Created `Work Status` field to see if in "Issued" status and Materials are being used to change status to "IN PROGRESS", otherwise "NOT STARTED".
- scenario: Contractor forgot to do part of job, SMB doesn't want to fail contractor
- would like a "COPY" of the work order in `Issued` status where SMB Inspector add "Instructions/Notes" saying work was missing
  - [ ] Copy function, DEV work? _maybe later once he's in the system_
 - [ ] Email in `Final Review`

**Comment by dianamartin** [comment]
Sync'd on copy function and made minor changes to the interface.
