### ISSUE TITLE
Meeting: Inventory Check-In 11/31/2020

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#4435]
### Objective 
Inventory Check-In
### Participants
Frank, Johnny, Diana

### Agenda
Add agenda here or create agenda from [this template](https://docs.google.com/document/d/1d_49KW5C_vSz8Bs50v-cxyIJuTNJMwMrh7ypcxRHgZI/edit#) and add link. 

------
- [x] Schedule meeting
- [ ] Optional: Schedule debrief
- [x] Meet and take notes
- [x] Optional: Debrief with DTS team members
- [ ] Create resulting issues

**Comment by dianamartin** [comment]
## Diana's Notes

- Johnny's bringing up issue: working from stock, shifts to completed 
- Notification to warehouse planners replenish in working stock

### Working stock process
- Removes from inventory, bc in working stock
- Generate a queue to replenish working stock
@johnclary Do we plan on building this out?
 - form of email, new work order?

Transaction of Working Stock
"New - Issued" - transaction status
Working Stock - skips the Inventory Request page 
- right now goes into "Needs AIMS entry", or "Completed"
- would like a new status

### Proposed Process
"Transaction" Status - "Needs to be Replenished" 
"Inventory Status" - "Needs to be Replenished" 
Replenish - Yes/No
"Inventory Status" - "Completed" 

### RETURNS
Situation: If Tech has items "Issued", please do a "Return" rather than a "Cancellation". Include notes as to why it was returned. 
- If it leaves shop or gone, it needs to be tracked as "Return"
- Cancellation: only if they actually don't need it

**How are returns processed now?**
- Was still using the paper return - Peyton Gin/Lamar

### RETURNS REPORTING
Returns - will link to Finance and Purchasing
Returns Tracking won't be used once AIMS goes away

### DISPLAY INVENTORY FORM
On Work Order Details
Inventory form - CLOSED Status
- Only warehouse and supervisors have access
don't want techs to have access and change anything without others knowing

**Comment by dianamartin** [comment]
Accidentally closed this. @johnclary Here are the notes, let m eknow if you wanna talk about the change requests.
