### ISSUE TITLE
Add FY21 Performance Measures to Data Tracker

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#4437]
> What application are you using?

Other / Not Sure

> Describe the problem.

I would like to request FY21 Performance Measures be created and available in Data Tracker.  FY20 was found at https://atd.knack.com/amd#performance-measures/
Attached is a list of FY20 Performance Measures with notes for those that are new, some to be moved to a different tab and others that should be removed. On the 2nd tab of the attachment, there is a complete list of FY21 Perf. Measures. Please let me know when this list will be live and if you have any questions.

> How soon do you need this?

Soon — This week 

> Is there anything else we should know?

I selected soon, but does not have to be this week so that I can review and employees can begin entering data when available.  Thank you!

> Requested By
Crystal T.

[Attachment](https://api.knack.com/v1/applications/595d00ebd315cc4cb98daff4/download/asset/5faaefa741df2d001583f5c7/fy21performancemeasuresdatatrackerupdates.xlsx) (18.74kb)

Request ID: DTS20-101310

**Comment by amenity** [comment]
@dianamartin - looks like another must-be-done-this-week request. 😕  LMK if you want me to reach out to Crystal in the case that this isn't a reasonable time frame.

**Comment by dianamartin** [comment]
@amenity I told John about this request and this is going to take time, to do and review. Not sure if I'll have time to do it, I may have to pass on discovery day to do the other work I have in order to finish.

**Comment by amenity** [comment]
@dianamartin -I totally missed "I selected soon, but does not have to be this week..."

Can you size it and we'll discuss at Backlog Grooming Thursday?

**Comment by amenity** [comment]
Emailed Crystal
> I wanted to circle back about your request to add FY21 performance measures to Data Tracker. Thank you for noting that you don't need the data this week, as it's a good chunk of work for the team to add the data and perform QA. I'd like to tee it up with their next set of work, which would get it to you by 12/1. 
> 
> Does that work for you? Otherwise we'll shuffle things around as needed. 🙂

**Comment by amenity** [comment]
Crystal is fine with that timeline, @dianamartin.

**Comment by amenity** [comment]
@dianamartin - should we assign this to someone for the next sprint? And/or anything we should extract from your 🧠 before you leave?

**Comment by dianamartin** [comment]
I'll try to update the GitBook documentation about it

**Comment by amenity** [comment]
@ChrispinP - please check to see if there's documentation on this.

**Comment by SurbhiBakshi** [comment]
@johnclary , @amenity - got a chance to look at this issue, and based on what I see 
- the dataset needs uploaded with the Measure ID as the common key, and then some need to be deleted (is this a permanent delete/or just a status change?)
- the Division is not included in the uploadable CSV but is in the form of a sub header row, going to ask Crystal if she has a spreadsheet with the Division in a row instead of a sub header. 
- There are 63 records in Data Tracker and 77 in the CSV, it would help to know which were added recently.

**Comment by SurbhiBakshi** [comment]
Scheduled some time with Crystal on 12/15. She is taking some time off later this week.
Will try to email her any questions before that.

**Comment by SurbhiBakshi** [comment]
Notes 
- [ ] Add field for Created Date
- [ ] Add field for Created By
- [ ] There are already some 2021 entries (93 of them) that were modified in Jan 2019. I am not sure if these still apply. It looks like the record got update on 11/3/2020, this issue came in on 11/10/2020. ![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/491e0a05-b270-44b7-a5fd-a7aa2012a136)
- [ ] These Measure ID's are new - 9349, 9353, 9354, 9355, 9356 and will have to be added to the performance_measures object.
- [ ] There are a few that need to be removed from this fiscal years' tracking. 
- [ ] Some measures will change Divisions, will the division change happen for earlier years as well?

**Comment by SurbhiBakshi** [comment]
Crystal could not make the 12/15 meeting, met later last week. She had to get some feedback from Van about performance measures that were to be removed. She sent me the spreadsheet yesterday.
