### ISSUE TITLE
Migrate legacy Knack publishing to new ETL

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#4471]
Migrate Knack data publishing scripts from [atd-data-deploy](https://github.com/cityofaustin/atd-data-deploy) to [atd-knack-services](https://github.com/cityofaustin/atd-knack-services)

todo:
- [x] mmc activities (socrata)
- [x] cctv cameras (agol + socrata)
- [x] detectors (agol + socrata)
- [x] dms (agol + socrata)
- [x] flashing beacons (agol + socrata):
- [x] pole attachments (agol + socrata)
- [x] ~signal_request_evals (tbd)~
- [x] signal_requests (tbd)
- [x] ~signal_retiming (socrata)~
- [x] signals (agol + socrata)
- [x]~traffic_study_locations (tbd)~
- [x] ~travel_sensors (agol + socrata)~
- [x] ~visitor log (socata)~
- [x] signal work orders (socrata)
- [x] Data tracker Locations (agol)

**Comment by dianamartin** [comment]
@johnclary @Charlie-Henry can we get the "Signal Request" ETL in the near future? AMD does reference the map fairly frequently.

**Comment by johnclary** [comment]
@dianamartin yes—it will be fixed with https://github.com/cityofaustin/atd-data-tech/issues/14960 which has PRs under review ✅
