### ISSUE TITLE
Implement high-level Signs and Markings workload and performance dashboard

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#4732]
> What application are you using?

Signs & Markings Operations

> Describe the problem.

Jim Dale has requested a special reporting page where he is easily able to see the Signs and Markings work load and the time that it takes for us to complete work orders. Most of the fields already exist, but there are some number of days calculations that will need to be built.

> Describe the outcome you'd like to see when this feature is implemented.

We would like to create a page where Jim Dale can see the following information for both signs and markings work orders:  
(1)Requester Work Order ID
(2) Requester
(3) Work Groups
(4) Status
(5) Priority
(6) Reimbursable Y/N
(7) Created Date / Active Date
(8) SBO Completed Date
(9) Completed Date

**New fields**
(10) Start Date - won't be able to get historic dates... but could bulk-import (or manually import only the open work orders) populating start date with the date from first labor line
(11) # of Days from Received to Start
(12) # of Days from Start to Completed
(13) Total Active Days

Also would like to see if we can bring in some of Susanne's PowerBI reporting into the Signs and Markings Application so Jim can access all the information he wants to see in one place. (performance measures/goals)

> Describe any workarounds you currently have in place or alternative solutions you've considered.

The other solution we've thought of is Susanne creating a PowerBI report with some of this information.

> Is there anything else we should know?

Would like to start working on this in January if possible.

> Requested By
Christina T.

Request ID: DTS20-101400

**Comment by amenity** [comment]
Susanne has been implementing performance dashboards in Power BI, but Jim has requested additional insight into SMB workload — what work orders are coming in, how long they're taking for completion, etc. Getting this data will require some additional fields, e.g. Start Date, in Knack. 

It would be preferable to give Jim access to all of this information in one place, whether it's Knack or PowerBI.

**Comment by amenity** [comment]
@mddilley just shared [this](https://github.com/microsoft/PowerBI-Client-React) in Dev Sync... I still prefer the idea of bringing Knack data into Power BI, but good to know this is out there. cc/ @SurbhiBakshi @johnclary

**Comment by johnclary** [comment]
Cool. yes to enabling Susanne to accomplish this in PowerBI. @SurbhiBakshi and I are already working to make the existing data available in Socrata so that Susanne can pull it into PowerBI. So I propose we hold off on adding these new fields until we complete that work. Marking this as blocked by #3114. @amenity would you let Christina know?

**Comment by amenity** [comment]
@johnclary -Once #3114 is taken care of, how big is this issue?

**Comment by amenity** [comment]
Hope to have #3114 done by mid jan. because we're setting it up on the new Knack ETL i'm anticipating a few issues to come up. After that, the additional fields should be a size 2.

**Comment by amenity** [comment]
- Two separate tables, one for Signs, one for Markings
- May not be a connection between the job time log and the work order that we can use to populate start time; in which case we will need to write a custom script

**Comment by SurbhiBakshi** [comment]
Met with Christina, Susanne, Diana on Jan 11th. 
**Notes -** 
Option 1 - Get help from a dev to populate only the first time log time stamp from Markings Jobs and Signs Work Order for Start Date. 
Option 2 - Create a field - Start Date in Signs Works Orders and Markings Jobs that gets populated when the first time log is filled out, set a conditional that allows only a blank record to get populated, use that for date forward. 

- Will need to create a connection between Reimbursable object and Markings Jobs to get that field in.

**Comment by SurbhiBakshi** [comment]
In the test instance, 

1. Added a field to the work_order_markings_jobs object - Date Last Worked as a date time field
2. Added a field to the work_order_markings_jobs object - Date First Worked as a date time field
3. Added a Record Rule on the Add Time Log form to record Date Worked on the work_order_markings_jobs object as Date Last Worked
4. Added a conditional on the Date First Worked field to only record from the Date Last Worked field if it is blank.

**Comment by SurbhiBakshi** [comment]
Spoke to @johnclary about the issued of having a parent object calculate a date field based on multiple records/entries from a child object. In this case, we would look for the earliest recorded date in the specific field in the child object. Knack has no readily available formula to get to that.


@johnclary suggested looking using a MIN field to look for the earliest date to populate the Start date for work_order_signs and work_order_markings_jobs objects to get populated from the Date_Worked field in the work_order_signs_markings_time_logs object. I tried that, but the MIN field type can only access numeric fields, and not date fields.

**Comment by SurbhiBakshi** [comment]
https://support.knack.com/hc/en-us/articles/226436527-Text-Formulas#build-a-text-formula

![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/439d0c9c-33c5-4292-b99b-587b49cc624c)

**Comment by johnclary** [comment]
@SurbhiBakshi I think I've got a solution for you. It's a bit of hack. Check out [this dummy object](https://builder.knack.com/atd/4-oct-2019-test-transportation-development-services-tracker#data/object_10/records) in the TDS test app. 

To summarize:
On the child object:
- Create an equation field that converts the date to a number
- Create a number field that is set with conditional rule the value of the equation number field

On the parent object:
- Create a "Minimum" formula that pulls the minimum number from the number field on the child
- Create a Date field that is set with conditional rule to the value of "Minimum" formula

Happy to step you through this. It definitely works, but there may be a performance hit here that we should consider.

**Comment by SurbhiBakshi** [comment]
thanks @johnclary ! Will try this approach.

**Comment by SurbhiBakshi** [comment]
For Signs - 

- [ ] Add a field `Time Log Date Worked Equation` to the `work_order_signs_markings_time_logs' object.
- [ ] Set the equation to a number with the Date Worked.
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/d7c8aa23-3780-4f64-a277-abf2283a9ac9)
- [ ] Add a Minimum field to the `work_order_signs` object set to the minimum of the field created above. 
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/f0f99210-a7b2-4e08-97c2-ba3bcc602b12)
- [ ] Add a Date field to the `work_order_signs` object with a conditional 
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/082ae629-e15e-4147-8595-a9ea140abca5)

**Comment by SurbhiBakshi** [comment]
Meeting - 1/21/2021

Notes - 

1. Completed Date or Closed Date?
2. Start Date - We are able to get this by using the approach suggested by John. 
3. Number of Days from Received to Start - calculate only when there is a Start Date otherwise 0?
4. Number of Days from Start to Completed - calculate only when there is a Start Date and a Completed Date, otherwise 0?
5. Total Active Days - number of days from Received to Completed, calculate only when a Completed Date is populated, otherwise 0.
6. Should the report table only look at jobs that are completed?

**Comment by SurbhiBakshi** [comment]
Number of Days Received to Start -  {Date Work Started}>0 &{ON_HOLD_DATE}>0? {Date Work Started}- {ON_HOLD_DATE} : {Date Work Started}>0 & {ON_HOLD_DATE}<0? {Date Work Started} -{CREATED_DATE}:0

![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/168e437c-dde4-4685-8afc-644578430919)

**Comment by SurbhiBakshi** [comment]
**Number of Days Start to Completed** - {Date Work Started}>0 & {COMPLETED_DATE}>0 ?{COMPLETED_DATE} - {Date Work Started}:0


![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/395f48bf-83de-45ee-9009-db5b83e9bdc4)

**Comment by SurbhiBakshi** [comment]
{ON_HOLD_DATE}>0 & {COMPLETED_DATE}>0?{COMPLETED_DATE} - {ON_HOLD_DATE} :{ON_HOLD_DATE}<0 & {COMPLETED_DATE}>0?COMPLETED_DATE} - {CREATED_DATE} :0

**Comment by SurbhiBakshi** [comment]
**Number of Days Active** - {ON_HOLD_DATE} > 0 & {COMPLETED_DATE}>0?{COMPLETED_DATE} - {ON_HOLD_DATE}:{ON_HOLD_DATE}<0 & {COMPLETED_DATE} > 0?{COMPLETED_DATE} - {CREATED_DATE}:0


![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/30231ffd-7afb-47b0-9a5e-80b166484d45)

**Comment by johnclary** [comment]
Looks really good @SurbhiBakshi!

**Comment by SurbhiBakshi** [comment]
### For Markings 
**Number of Days Received to Started** -{work_orders_marking.REMOVE_HOLD_DATE} > 0 & {Date Work Started} > 0 ? {Date Work Started} - {work_orders_marking.REMOVE_HOLD_DATE} : {work_orders_marking.REMOVE_HOLD_DATE}<0 &  {Date Work Started} >0 ? {Date Work Started} - {CREATED_DATE}:0

![image](https://user-images.githubusercontent.com/13035849/105520737-b2d8af80-5ca0-11eb-948d-bbbac5d38e1d.png)

**Comment by SurbhiBakshi** [comment]
### For Markings
Number of Days Start to Completed - {COMPLETED_DATE}>0 & {Date Work Started}>0?{COMPLETED_DATE} - {Date Work Started}:0

![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/9914edaa-c00e-48ec-ae7f-7a99ec261701)

**Comment by SurbhiBakshi** [comment]
### For Markings 
Number of Days Active - {COMPLETED_DATE}>0 & {work_orders_marking.REMOVE_HOLD_DATE}>0 ?{COMPLETED_DATE} - {work_orders_marking.REMOVE_HOLD_DATE}:{COMPLETED_DATE}>0 &{work_orders_marking.REMOVE_HOLD_DATE}<0?{COMPLETED_DATE} - {CREATED_DATE}:0

![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/5e7ba701-d329-41e6-924b-6f1c682087d6)

**Comment by SurbhiBakshi** [comment]
### For Markings 
**Number of Days Received to Start** -  {work_orders_marking.REMOVE_HOLD_DATE} > 0 & {Date Work Started} > 0 ? {Date Work Started} - {work_orders_marking.REMOVE_HOLD_DATE} : {work_orders_marking.REMOVE_HOLD_DATE}<0 &  {Date Work Started} >0 ? {Date Work Started} - {CREATED_DATE}:0

![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/6c46ac1e-0291-4834-8e14-8d6a3d61bdbb)

**Comment by SurbhiBakshi** [comment]
### For Markings Work Orders -
**Number of Days Received to Start** -  {REMOVE_HOLD_DATE}>0 &  {Date Work Started}>0 ? {Date Work Started} - {REMOVE_HOLD_DATE}:{REMOVE_HOLD_DATE}<0 &  {Date Work Started}>0 ?  {Date Work Started} -  {CREATED_DATE}: 0

![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/85b088b4-d8e2-4984-84db-0c7739cd2639)

**Comment by SurbhiBakshi** [comment]
### For Markings Work Orders 
Number of Days Active -{COMPLETED_DATE}>0 & {REMOVE_HOLD_DATE}>0 ? {COMPLETED_DATE} - {REMOVE_HOLD_DATE} :{COMPLETED_DATE}>0 &{REMOVE_HOLD_DATE}<0 : 0

![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/066e425c-2eea-4d4a-adfe-ab66403d72ef)

**Comment by SurbhiBakshi** [comment]
### For Markings Work Orders
Number of Days Start to Completed -{COMPLETED_DATE}>0 &  {Date Work Started}>0?{COMPLETED_DATE} - {Date Work Started}: {COMPLETED_DATE}>0 & {Date Work Started} <0?{COMPLETED_DATE} - {CREATED_DATE}:0


![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/902ff709-0194-4f93-be37-7004750caa99)

**Comment by amenity** [comment]
@SurbhiBakshi work with @johnclary to push to AGOL when this calculation is complete. May help, temporarily at least, with https://github.com/cityofaustin/atd-data-tech/issues/4985

**Comment by SurbhiBakshi** [comment]
To possibly fill the gap in Susanne's process, will need to create Date Last Worked from the Time Logs to 
- [ ] work_order_signs
- [ ] work_order_markings
- [ ] work_order_markings_jobs

Following the same process as Date First Worked, the change here is to use a Maximum numerical field to pull in the maximum date stored as a number in an equation field - Time Log Date Worked Equation

![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/4e46af3b-ab89-4ae0-ab17-627d49a698ca)

**Comment by SurbhiBakshi** [comment]
Had to put in an Equation field to get Remove Hold Dates from Markings Work Orders to Marking Work Order Jobs because the conditional equation for Number of Days Received to Start works this way. I think it was timing out when I was trying to use a connected field.

**Comment by SurbhiBakshi** [comment]
@dianamartin and I tested the forms for submitting a time log for both signs and markings works orders, markings jobs, and we did not see any noticeable time lag.

**Comment by SurbhiBakshi** [comment]
Met with Christina, Lauren, Susanne and Diana on 02/26. 
I showed them the three tables - Signs Work Orders, Markings Work Orders, and Markings Jobs Work Orders. 
Christina will test the three out and provide feedback on data validity, refinement in terms of fields and field names. I will move the changes to Production after I resolve those changes.

**Comment by SurbhiBakshi** [comment]
Wrote to Christina to check if she had a chance to test and to get feedback from her, have not heard back.

**Comment by SurbhiBakshi** [comment]
Christina messaged me last week to say she and Lauren were going to test it. I have not heard back. I Teams messaged her today to see if there were any updates, but have not heard back.

**Comment by SurbhiBakshi** [comment]
Christina replied to my message - she is meeting with Susanne and Lauren and will meet with me next week to give feedback.

**Comment by SurbhiBakshi** [comment]
Meeting to get feedback and determine next steps has been scheduled for April 13th.

**Comment by SurbhiBakshi** [comment]
Christina moved the feedback meeting to Friday April 16th.

**Comment by SurbhiBakshi** [comment]
Met with Christina and @dianamartin on Friday April 16th. 

Notes - 

1. Christina wants to see the date fields in the dashboard, but will work with Susanne to incorporate the fields for `number of day` in Power BI because it is much easier to work with date calculations and set multiple filters in Power BI. 
2. Here is the [spreadsheet ](https://teams.microsoft.com/l/file/54aa800b-e890-4478-96ea-2e7a664d6721?tenantId=5c5e19f6-a6ab-4b45-b1d0-be4608a9a67f&fileType=xlsx&objectUrl=https%3A%2F%2Fcityofaustin-my.sharepoint.com%2Fpersonal%2Fchristina_tremel_austintexas_gov%2FDocuments%2FMicrosoft%20Teams%20Chat%20Files%2FWork_Orders_High_Level_Dashboard.xlsx&baseUrl=https%3A%2F%2Fcityofaustin-my.sharepoint.com%2Fpersonal%2Fchristina_tremel_austintexas_gov%2F&serviceName=p2p&threadId=19:meeting_N2RkYzQ4MDgtODQzYS00YzM1LWJiYTctMjkyNzhjMTdmOTdj@thread.v2&messageId=1618603648933)of the fields she would like to see in the reporting tables. 
3. The location of the tables should be in Markings Reporting.
4. Ensure that the tables can be exported.
5. Look into the default 1970 dates. 
6. Instead of the Reimbursable Y/N fields which are rarely filled out, substitute TK, FDU. 
7. Retain Markings Work Orders, don't need to create Markings Jobs to Production. 


@dianamartin - please add any notes I might have missed.

**Comment by SurbhiBakshi** [comment]
I don't think this issue is blocked by #3114, but being able to set up a data pipeline for these tables on the Open Data Portal will help with getting the information in Power BI. This could be a potential project for our Civic Innovation fellow this summer - @johnclary thoughts?

**Comment by SurbhiBakshi** [comment]
Notes - If Count of Time Logs is zero

**Comment by SurbhiBakshi** [comment]
### Notes 

1. All the records in the minimum and maximum fields on the parent object are not getting populated. Some of the records are getting populated which tells me that the connection is working. I tried updating a few records using the Test Date field as a catalyst, but the records did not get populated. 
2. I have put in a support request with Knack to see if I can get some help figuring out why all the records are not getting populated.

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/d1266bab-56f4-41ab-8691-dc2fbec119bd)


![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/bb77b515-dc6d-4921-b340-9b12b52f94c7)

**Comment by SurbhiBakshi** [comment]
in this [instance](https://atd.knack.com/signs-markings#api-views-private/socrata-etl/work-orders-sign-details/5e45af1ffb8b3500182d207d/), the minimum date worked (numeric)is populated from the time_log object but not the maximum work order date (numeric). 


![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/396d7a02-120e-48e5-83a7-ee219c4f2d5b)

**Comment by SurbhiBakshi** [comment]
As opposed to the[ instance ](https://atd.knack.com/signs-markings#api-views-private/socrata-etl/work-orders-sign-details/6086da95c72da0001b43592e/)noted above, in this instance the maximum date worked is populated and not the minimum 

![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/04ca14f5-4951-433e-92f6-4e2e6f0723b7)

**Comment by johnclary** [comment]
@SurbhiBakshi can you see any differences in the record histories for these two? perhaps you can locate the event that caused the max date to populate correctly.

**Comment by SurbhiBakshi** [comment]
@johnclary - For both records, the Record Update : Formula was the trigger. 

![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/689535b4-4bab-401b-aa77-1d8485b12e98)

**Comment by SurbhiBakshi** [comment]
Email from Knack

**Comment by SurbhiBakshi** [comment]
Email from Knack -

**Comment by SurbhiBakshi** [comment]
Email from Knack -

**Comment by SurbhiBakshi** [comment]
Messaged Christina to give her an update on the dashboards and to let her know I am working with Knack to resolve the issue with populating all records.

**Comment by SurbhiBakshi** [comment]
Knack converted the equation field in the time_logs object from Number to Date, but that did not come through in the work_orders_markings object. The minimum and maximum field are still numeric and the translation into Dates is incorrect. 
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/0d2c63eb-208d-4d9e-b7d8-7811cde62742)

**Comment by SurbhiBakshi** [comment]
Increased the estimate on this request to an 8 due to the additional complexity introduced by all records not populating and communication with Knack.

**Comment by SurbhiBakshi** [comment]
The minimum and maximum fields in the work_orders_markings_jobs are populated for all records with 1 or more time logs. The minimum and maximum fields are populated by dates.
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/39318389-0eae-4337-81b0-6b7c64747487)

**Comment by SurbhiBakshi** [comment]
### Email to Knack - 
I did some spot checks, and it looks like the indexing process worked. 

I have documented the details for a similar issue below, in this case the added complexity is that I need records to be populated across three levels. Will you please investigate this?



thanks,

Surbhi









Application ID - 

5d13ae5b438091000ac0197d

 

**Parent object -** 

work_order_markings

 

Minimum field on parent object - Minimum Date Worked from Time Logs 

Maximum field on parent object- Maximum Date Worked from Time Logs 

 

**Child Object -** 

work_orders_markings_jobs

 

Minimum field on child object - Minimum Date Worked from Time Logs 

Maximum field on child object- Maximum Date Worked from Time Logs 

 

**Grandchild Object:**

time_logs

 

Field in grandchild object - Time Log Date Worked Equation

**Comment by SurbhiBakshi** [comment]
Sent in a separate request for indexing markings_work_order_jobs to Knack.

**Comment by SurbhiBakshi** [comment]
Have not heard back from Knack, I updated Christina on the status of this issue on Friday. 
I am going to see if I can source the dataset from a private dataset on the Open Data Portal, or the feature services available on AGOL. Discussed this with @johnclary on Monday at our 1:1. If this approach works, will discuss it with Christina and Sussanne.

**Comment by SurbhiBakshi** [comment]
Continuing my little novella here - 

Email from Knack

**Comment by SurbhiBakshi** [comment]
Email to knack - 
hi Jessie, 

I had set the settings for that Equation to Numeric before, but I think Norma from your team advised me to change it to Date, to make the processing faster. 

I reset the field to Numeric, but still see the Date Work Started field in the work_orders_markings object (object_140 - field_3915) populated for all the related records. 
I also see some 01/19/1970 values in the Date Last Worked (
object_140 - field_3955 ) field. I should not see any default values since I have set up a conditional to prevent that from happening. 

Attaching a screenshot for your reference. I am going to give it some more time in case the processing needs more time, will get back to you if I see any progress. 





![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/016dc33f-b1d9-44e4-9df3-f962c6f07627)

**Comment by SurbhiBakshi** [comment]
Email to Knack - 
Hi Jessie, 
I should add to clarify that I am using fields 
3915 and 3955 to read 3925 and 3926. I might not have needed them if the original field in the grandchild object had been a Date format field, but since that is a Number field, I need to translate the Number into a Date. 

Thanks for your help in resolving this issue, appreciate it!

**Comment by SurbhiBakshi** [comment]
Email from Knack - 


Thanks for your patience, the support load has been higher than normal lately, and the setup here requires re-familiarizing so I wasn't able to dive back in head first. 

I did sync up with Norma, and she did confirm that using a date type equation would work, and that it wasn't working before with numeric. To be honest, I have seen it set up both ways, and I can't particularly recall the circumstances where Numeric was required instead of using the straight Date value. 01/01/1970 is the date we apply to a value of null or 0. 01/19/1970 is probably something similar, or slightly higher than a value of 0 in the raw value it is calculating from for some reason. 

I do have some concerns about processing this many cascading values, and am wondering if the server would be able to consistently keep up with the index jobs, but I'm not sure if alternatives are an option or have been explored.

Since it's been a week since you wrote in, can you let me know if you saw those values populate after giving it time? I don't see any records with a value of 01/19/1970 at the moment. Other than tweaking the settings in these fields, checking for failed jobs or server overload, and forcing a re-index on my end, I'm coming up dry. We don't have any known bugs in this area per-say, but cascading complexity can certainly be enough of an issue to present inconsistencies. 

Let me know where you are at right now. Thanks!
Jessie

**Comment by SurbhiBakshi** [comment]
Going to write the epilogue to this novella - will ask Knack to close this ticket.  Current developments will be documented in #6131.

**Comment by johnclary** [comment]
Re-opening: we need to confirm SMB will take it from here and let Jim D. know.
