### ISSUE TITLE
[Feature] End User Documentation

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#4747]
After debriefing how the exec demo went, we talked about the idea of having the mission/purpose of this project clearly defined and as a living statement baked into the software.

This started as the idea of having the Mission of Moped at the top of an About page, but maybe it could be a jumping of page for links to documentation and version releases or even pulling in some of these resources via APIs in the future.

For now, I would say we can make an "About" page that is: 
- [ ] listed either at bottom of the left side bar
- [ ] Has a paragraph at the top of the page with the text from [pages 2 & 3 of this presentation](https://docs.google.com/presentation/d/1KJTrsH9WrvduKOPk4LIy5Sa14gNM-HKijXd5Un_ASi8/edit#slide=id.g7d97db3db4_0_0). Bonus points of this text could live in a separate Markdown file that is easy for a non-dev to edit and maintain and allows for the md content to just import into the page view.
- [ ] Links to relevant documentation: 
  - Data Dictionary
  - Dev Docs in Githbook or Confluence
  - User Docs in TBD?
- [ ] A link to or embed of our DTS Intake form for reporting bugs, requesting features, etc. Text above the form link or embed could explain the process for getting in touch with the DTS team for help, training, etc

**Comment by amenity** [comment]
Update: For now we're using Gitbook for end user documentation: https://atd-dts.gitbook.io/moped/

**Comment by amenity** [comment]
### Moped 1.0 Documentation
- [User guide](https://atd-dts.gitbook.io/moped/user-guides/getting-started) 
- [Data dictionary](https://db-docs.austinmobility.io/atd-moped-production/index.html)
- [Project index](https://austinmobility.io/projects/307)
- [High-level project presentation](https://docs.google.com/presentation/d/1pAHCgVao0tO5aq95I6nhXuAd2_--CmwMSF3FW3PQrxY/edit#slide=id.p) - Google slides
