### ISSUE TITLE
Enable COACD button on SMB Tracker login URLs, add fancy buttons, and document process 

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#4851]

**Comment by dianamartin** [comment]
Add COACD button code
- [ ] Added JS and CS (small button code)
- [ ] Refresh and tested "Sign-in" button
- [ ] worked as expected with auto entry
- [ ] logged out
- [ ] Refresh and tested "Non-COA Sign-in" button
- [ ] worked as expected with manual pw entry
- [ ] logged out

### Manually tested instead

**Internet Explorer**

- [ ] Refresh and tested "Sign-in" button
- [ ] Refresh and tested "Non-COA Sign-in" button

**Chrome**

- [ ] Refresh and tested "Sign-in" button
- [ ] Refresh and tested "Non-COA Sign-in" button

**Firefox**

- [ ] Refresh and tested "Sign-in" button
- [ ] Refresh and tested "Non-COA Sign-in" button

**Edge**

- [ ] Refresh and tested "Sign-in" button
- [ ] Refresh and tested "Non-COA Sign-in" button

**Comment by johnclary** [comment]
@dianamartin what's blocking this?

**Comment by dianamartin** [comment]
I recently tried to test this in the Test SMB environment. I was just cautious about removing your code and adding Mike’s new code for the sign in buttons. I believe @ChrispinP and I found a bug and he was going to follow up with Mike. 

There was an issue with specific pages and the log in buttons. I’ll have to get in and identify what it issue was again.

**Comment by mddilley** [comment]
@ChrispinP  reached out to me last Thursday, and I looked into it but I didn't follow up with him on Friday. I couldn't find an view where the some of the CSS wasn't working. Could y'all point me to a page? I'm curious to see what is going on. 🙏

**Comment by dianamartin** [comment]
@mddilley We have the TEST | SMB - 17 MAR 2021 | Signs and Markings Operations application that this is happening to. 

- Home page
Behavior: when a user clicks on empty space past the button it is still activated

- Need to replace John's JS big button code:
  - starts line 336
  - ends line 550
- CSS Code - Big button
  - starts line 31
  - ends line 71

**Comment by dianamartin** [comment]
# SMB TO DO
- **Need to replace John's JS big button code with Mike's new code**
  - starts line 336
  - ends line 550

- **CSS Code - Big button - Review to match new code** 
  - starts line 31
  - ends line 71

**Comment by mddilley** [comment]
The new code is now in Signs and Marking production as well as TEST | SMB - 17 MAR 2021 | Signs and Markings Operations. There is a [PR](https://github.com/cityofaustin/atd-knack/pull/29) with the updates to big button code and login code to address the underline text decoration and clickable right margin.

Next step is for me to document the updates now that the big button and custom SSO button styles are covered by the same CSS styles.

**Comment by mddilley** [comment]
Sorry y'all - accidentally closed this one with the "fixes" keyword in a PR. 🙃

**Comment by amenity** [comment]
Thanks, @mddilley !

**Comment by amenity** [comment]
@dianamartin — should this stay in Blocked for any reason?

**Comment by dianamartin** [comment]
This can be closed
