### ISSUE TITLE
Prepare for officer enrollment and training

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-data-tech#4865]
Steps to be taken before the four training sessions next week to clean and prepare application - 

- [x] Remove all Badge Numbers not associated with officers
- [ ] Remove the extra space between AP and number in Badge Number
- [x] Create [Google form](https://docs.google.com/forms/d/e/1FAIpQLScZ558UUPSrNB8kH9fxoL617fV9Sipg0M6Ig-3rLQAjGhx0tQ/viewform) for officers to put in their information
- [x] Restore Notes Types

**Comment by SurbhiBakshi** [comment]
@amenity  - Need to change the language above the notes form to indicate selecting type of note, 
should there be one more note type to show miscellaneous notes - non VZA work that came up during the assignment?

Otherwise  Note Type has been included in 
- [ ]  Note Form
- [ ] Notes table
- [ ] Edit notes form


![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/8c85584d-da50-41c6-968d-c378c6b75be9)

**Comment by amenity** [comment]
I was thinking instead of a spreadsheet we could make a Google Form.

**Comment by SurbhiBakshi** [comment]
@amenity - a Google form should work
Not sure we need to include a Call Sign. We had it in the Officer form, but I am not sure I have seen it referenced elsewhere. 

- [ ] First Name
- [ ] Last Name
- [ ] Badge Number
- [ ] Phone Number
- [ ] Email (austintexas.gov)
- [ ] Call Sign?

**Comment by amenity** [comment]
@SurbhiBakshi - up to you on call sign. I forgot you're using badge # for PowerBI. So seems like it's extraneous.

**Comment by amenity** [comment]
@SurbhiBakshi - I like the idea of more than one note type since we can have help text for each. If that's not too hard for you to do...

**Comment by amenity** [comment]
![Screen Shot 2021-01-08 at 2 50 14 PM](https://user-images.githubusercontent.com/1463708/104062881-dee43300-51c0-11eb-915e-890d7808cd1b.png)

@amenity - provide updated wording for this.

**Comment by SurbhiBakshi** [comment]
@amenity - Slacked you the link to the Officer Registration Form and the related spreadsheet for Pat to use to verify attendance.
Going to leave Call Sign as an optional entry for now.

**Comment by amenity** [comment]
@SurbhiBakshi it all looks great. I think leaving out call makes sense so as not to make it seem like it's used in the app somewhere. Knowing now that call signs can be changed at whim, I can't imagine we would ever use them. Right?
