### ISSUE TITLE
Project: Transportation Mitigation Web Map

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#4937]
We are creating a web map to display TIA mitigation data for our internal stakeholders.

## Background
ATD has collected and manages funds for TIA fee in lieu program. These funds are available for use by various stakeholders such as The Public Works Department. These stakeholders need a tool to explore the mitigation data spatially, identify potential funding opportunities, and link back to the KNACK TIA case to continue research. 

## Scope & Deliverables
This effort will involve resources from several teams:
- Transportation Engineering Review
- Transportation Development Services
- DTS Product
- DTS Apps
- DTS Geo
- DTS Dev
- DTS AMANDA

**Deliverables include:**
- Mitigation data scrubbing 
- Create TIA Mitigation feature layer
- Build a prototype of possible visual solutions
- Build solution _(web map)_
- Automate: Knack to AGOL
- Test & iterate
- Release 

## Desired Outcomes

The mitigation funds ATD has collected will be easier for our stakeholders to find and use to construct the identified mitigation improvements. 

## Timebox

We estimate this will take 80-100 hours of total work. 

![53055145922_418cd5dfb4_o Cropped](https://github.com/cityofaustin/atd-data-tech/assets/49930868/3e8fd64c-9de6-462e-a26c-d64f90259ec3)

---
This Github issue represents a project of Austin Transportation's [Data & Technology Services](https://austinmobility.io/) team. Project status is documented regularly in the comments below.

**Comment by TracyLinder** [comment]
@ChrispinP can you please work with @johnclary to identify the next steps on this? I'd like to be able  update the stakeholders on Monday

**Comment by johnclary** [comment]
Might want to turn this into an epic. Here are the steps @ChrispinP. Happy to review with you.

- Load all street segments into a new object in Knack. Create connection to mitigations object. @alan-deanda can get you a CSV of these records.
- Create a dedicated arcgis online map and app so that customers can easily lookup their street segment and view the segment ID (@alan-deanda can help with this)
- Embed the ArcGIS online app into the TDS app. See [this rich text view](https://builder.knack.com/atd/amd#pages/scene_100/views/view_907) in the Data Tracker for example

**Comment by TracyLinder** [comment]
This is already in an epic for TIA Mitigations. #4938

**Comment by TracyLinder** [comment]
@ChrispinP are you able to give me an estimated completion date based on John's input above?

**Comment by TracyLinder** [comment]
@johnclary I think you were correct, the mapping portion of mitigations will need it's own epic. I'm converting this one into an epic. It will be 1st three tier epic!

**Comment by ChrispinP** [comment]
Scheduled meeting with Alan to discuss work we need to do for this.

**Comment by johnclary** [comment]
Thanks @ChrispinP! Let me know if you need any help.

**Comment by ChrispinP** [comment]
Added Segment ID map to Mitigation page, pending update to add Mitigations to map.

**Comment by johnclary** [comment]
@TracyLinder it looks like we need separate issues for the TIA feature which enable users to map their mitigations in the TIA module, versus this feature for allowing staff to view all mitigations on the map.

@ChrispinP has setup the former, which allows users to add their mitigation street segments—y'all need to review this together to decide what else is needed. E.g., page layout, map symbology, etc.

**Comment by ChrispinP** [comment]
Starting CSV import for Segment ID's into TIA_mitigation_geo

should take about an hour, will create connection with mitigations once complete.

**Comment by ChrispinP** [comment]
Updated mitigation fields. Mitigation Segment ID is now set automatically from the connected Mitigation Geo Segment ID. Alan updated Mitigation map to display Segment IDs without commas. Replaced Mitigation Location with Mitigation Geo connection field so reviewers can search or paste Mitigation Location by street name or segment ID. Updated GeoDisplay to show both Segment ID and Street Name for Mitigation Location and sorts mitigation tables alphabetically

**Comment by ChrispinP** [comment]
tested and everything looks good, closing as complete

**Comment by TracyLinder** [comment]
Reopening this to serve as the epic for all things related to the stakeholder map we will build for the TIA Mitigations data.
- This work is not in scope for the TIA Mod Project

**Comment by TracyLinder** [comment]
@dianamartin & @ChrispinP 
This is the epic i'm going to use for the mitigation map. I created it 2 years ago during the TIA Project waiting for prioritization. Just an FYI.

**Comment by TracyLinder** [comment]
### Team Huddle Sync 3/23/23

- Chrispin sent mitigation table data to Andrew, Andrew put together an initial workflow, the table had 1,026 items and only 57 had a feature ID and can be tied to an intersection/segment and the others can't be mapped w/ existing data.
- Has Nelson spoken to Gilda about help with data scrubbing? - Not yet, Nelson has been out.

**Comment by TracyLinder** [comment]
Gilda approved Drew helping backfill.

**Comment by TracyLinder** [comment]
### Team Sync 4/3/23

- [ ] Recap from last sync
- [ ] Drew approved to help w/ backfill
- [ ] Review backfill pages & workflow. 
    - _Where did we put notes from the internal review last week? I know we have clarifications to ask._
- [ ] Discuss next steps

**Comment by TracyLinder** [comment]
### Synced with Dev team
- John added notes to the huddle issue, [here](https://github.com/cityofaustin/atd-data-tech/issues/11591#issuecomment-1505818736)

**Comment by TracyLinder** [comment]
### Update

The historical mitigation data is being scrubbed to add mappable ID's. The mitigation map draft looks great; next step is to identify and map the data we want published.

**Comment by TracyLinder** [comment]
### Project Mtg Scheduled
- 5/30/23
- Discuss data backfill and next steps

**Comment by TracyLinder** [comment]
### Update

The majority of historical mitigation data has been scrubbed to add segment ID's. There are 110 records remaining that can't be mapped with the information available in KNACK. The team is meeting on 6/5 to sync and discuss next steps which should include:
- Identify methodology for adding segments to the 110 records without location data.
- Discuss the data to publish and where it maps.

**Comment by TracyLinder** [comment]
### Team Sync 6/5/23

- [ ] 110 Records w/o location data
- [ ] Sync on web map (Andrew)

**Comment by TracyLinder** [comment]
### Update 6/22/23

_Tracy, Cody, Diana, Chrispin, Matiur, Andrew_


- Nelson no longer with TPW

**Comment by TracyLinder** [comment]
### 8/3/23
- Drew is done; only 22 record locations couldn't be found.


Action Items
@ChrispinP export data related to the 22 records without a mitigation location
Move forward with action items on #12478

**Comment by TracyLinder** [comment]
### Project Update as of Aug 17, 2023

We are done scrubbing the mitigation data to add geo ID's. We've moved into data mapping and are currently working on 2 major items:
1. Migrating all TIA Memos to their respective TIA Case in the TDS Portal
2. Learning about how TPW manages the allocation of mitigation fees, and where we can find data about fees allocated to date.

**Comment by TracyLinder** [comment]
- ATD began with TIA program in 2019
- The mitigation data we have in KNACK does not match the revenue data Van is maintaining. 
- Van will have time to help us after mid-september
- These are considered CIP funds and currently reviewed by Tim T. in finance

Who manages the mitigation money collected prior to 2019? - DSD



![image](https://github.com/cityofaustin/atd-data-tech/assets/49930868/8089e3f5-4552-4e3b-a065-fdc985c28356)

**Comment by TracyLinder** [comment]
I updated the project evaluation for this today.

**Comment by TracyLinder** [comment]
### Project Sync Notes

- Chrispin wants to do a data analysis w/ Van's finance data against our KNACK data
- Cody is onboarding a new Nelson soon - a few weeks. 
- Tracy is super confused about how to understand the KNACK data.

**Comment by TracyLinder** [comment]
### Project Meeting 11/8/23

- Meet Kat! 
- Review data together
- Here is the G drive location for the memos: \\Coacd.org\dfs\TPW\ATD\Trans\Transportation & Engineering\Programs\Development Transportation Improvements Fiscal Projects\Program Management\Accounting_Finance

**Comment by TracyLinder** [comment]
Mitigation Record Column Discussion:
- Thinking of removing Mitigation Cost, Share$, Share Paid --- but more research is needed to determine if those data points are needed or not based on the way the original data was captured.

**Comment by TracyLinder** [comment]
### Project Meeting 1/5/24

- [ ] Remove fee fields from edit mitigation form (screenshot below)
- [ ] 



<img width="901" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUtoQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dcc11e726304a7f70848eb56a0a6faa953351ed2/image.png" alt="image.png" />

**Comment by TracyLinder** [comment]
### Debrief with Kat on TDS Sync 1/30/24

- People need to see information about encumbered funds. Where do we put that data? 
    - Adding ecapri number so users can get more info about encumbered/spent projects 
    - `Or rename the SPENT field to ENCUMBERED ` 
- Scope should be financial management of mitigations vs project/implementation management. 

**Remembering the goal: For people who can spend mitigation monies to identify available funds**




### For Discussion @ Project Sync
- Rename the SPENT field to ENCUMBERED
- Reorganizing mitigation table columns and edit form to make data entry easier. On the landing page, and mitigation details page.
     - `Review all fields to determine if they are still necessary and identify why they exist`
-

**Comment by TracyLinder** [comment]
### Project Team Sync 2/1/24


**Summary:**
- We attempted to define the mitigation data columns. Why they exist, what data is meant to be there, who uses it.... We hit a wall due to TDS using the same data object and not being in the room. 
- It's agreed we don't need to collect data on how the money is spent. The scope is only what is necessary to publish available funds. 
- We've decided to pause on data cleanup until there is a consensus on the data. To that end DTS is meeting internally to devise a POA as to how we approach this challenge. Then we will meet with the project team and TDS to define the data. 
    - DTS meeting internally on 2/8
    - Larger group meeting scheduled for 2/20 




### Steps to publishing available data
1. Making sure we understand our data
2. Determine what data to be published on the map, per case
3. Map the data and bring Andrew in to setup the map

**Comment by TracyLinder** [comment]
### Feb 20, 2024

Today we brought together TDS & TED to review the mitigation page data fields and discuss:
- Why they exist
- Which group maintains it
- Definitions of certain fields
- Overview of formula fields

**Comment by TracyLinder** [comment]
### Project Sync Feb 26, 2024

![image](https://github.com/cityofaustin/atd-data-tech/assets/49930868/a65b3bf4-09dc-45cb-b16f-c54ec3200f62)

**Comment by TracyLinder** [comment]
### Selecting Fields for Mitigation Map

**Project Level:**
- Show projects with status of Verified & Allocatable 
- and Remaining Funds is >$0



**Mitigation Line Item:**
- Only show mitigation line items with a Fund Status of Available





# We need to figure out the expiration date logic

**Comment by TracyLinder** [comment]
### Project Sync May 2, 2024

**Agenda:**
- [ ] Map updates (#16480 #16481 #16482)
- [ ] Next steps for publishing map

**Comment by TracyLinder** [comment]
The project team needs to discuss mitigations that apply to trails. See #11462.

**Comment by TracyLinder** [comment]
**Missing mitigation cases**
1. Nate said he had a resource for the data entry. Update? 


**Accounts w/ Issues**

**Comment by TracyLinder** [comment]
### Project Closing

The [mitigation webmap ](https://austin.maps.arcgis.com/apps/dashboards/b89c344a9fd54e73a10d2b651c9c928b)has been in production for over a month. There are no other outstanding deliverables.
