### ISSUE TITLE
Project: Right of Way AMANDA Permitting Metrics

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#4946]
Enhancements to the AMANDA permitting system to 1.) Capture Right-of-Way permitting metrics data, and 2.) Create all AMANDA reports requested by ATD Executive Management. 

## Background

ATD Executive Management has requested a series of AMANDA reports related to Right-of-Way permitting and has identified 4 major reporting metrics. Unfortunately the majority of the data required for this reporting does not currently exist. 

## Scope & Deliverables
There will be two (2) phases of development. 

- Phase 1: Update AMANDA permitting folders so the necessary data can be captured.
- Phase 2: Create the reports for our stakeholders.

Desired   Outcome | Deliverables
-- | --
Staff   can create and view data related to permitting turnaround times. | All permit folders updated to   capture dependable application and issuance timestamps.
Staff   can create and view data related to permitting review cycles. | All permit folders workflows are   updated to capture review cycle data.
Staff   can create and view data related to permitting review duration. | All permit folders workflows are   updated to capture data related to duration of reviews.
Staff   can create and view data related to permitting review deficiencies. | All permit folders workflows are   updated to capture data related to permitting deficiencies.
Staff   has access to on-demand reporting for Right-of-Way permitting metrics. | Custom AMANDA permitting metrics   reports are available in the ATD AMANDA Custom Report Library, which is   available to all ATD staff.
Staff   understands the new enhancements and how to use them. | Employee training is provided to   Right-of-Way management.

## Timebox
From kickoff to delivery, we estimate this project will take 4 – 6 months.

**Phase 1: AMANDA Enhancements**

Project   Task | Estimated Time/Duration
-- | --
Scoping | 8 Weeks
Acceptance   Criteria | 1 Week
Development | 6-12 Weeks
User Acceptance Testing | 4-6 Weeks
Staff   Training | 2 Weeks
**Total:** | **21-29 Weeks (7 Months)**

**Phase 2: Custom Reports**

Project   Task | Estimated Time/Duration
-- | --
Scoping | .5 Weeks
Acceptance   Criteria | .5 Weeks
Development | 1 - 3 Weeks
User   Acceptance Testing | 2 Weeks
**Total:** | **4 - 6 Weeks**

![image](https://user-images.githubusercontent.com/49930868/112259735-c66bac80-8c36-11eb-9729-ac2ebc32e718.png)

---
This Github issue represents a project of Austin Transportation's [Data & Technology Services](https://austinmobility.io/) team. Project status is documented regularly in the comments below.

### Resources
- [Project Folder](https://drive.google.com/drive/u/1/folders/1Kp3PsxEBy-bhJNKUduWsjxUJW6Kq3jOR)
- [Teams Channel](https://teams.microsoft.com/l/team/19%3a9a42043aacd94f6cacd56f26c0027224%40thread.tacv2/conversations?groupId=f9f1bbb3-ac1c-49da-9e2a-ae4886302e38&tenantId=5c5e19f6-a6ab-4b45-b1d0-be4608a9a67f)

**Comment by johnclary** [comment]
I removed the `Project Index` label from this pending the missing info.

**Comment by TracyLinder** [comment]
@TracyLinder work on cleaning this up & scheduling regular project meetings.

**Comment by TracyLinder** [comment]
### Update

A project kick-off has been scheduled for Wednesday April 14, 2021. We will refine the scope, assign project members, and plan logistics.

**Comment by TracyLinder** [comment]
## KICK-OFF MEETING NOTES
_Issue #5734_

Attendees: Tracy, Nate, Vish, Ryan, Paloma, Izzy

### 1. Success & Failure
**Why are we doing this, what problems might we solve?**
- So we can have better insight into how permitting team is performing, create accurate & repeatable metrics, measure performance in an automated way that cuts down on manual data manipulation by staff. 



**What will make this project fail; what are your concerns?**
- With Jim having the vision for the deliverables/outcomes, there's risk that expectations and possible solutions may not be communicated clearly and we could spend time building features that aren't needed or don't fit Jim's vision. Also executive management, since they don't directly work in AMANDA and don't have a full understanding of it's features/limitations, could create quite a bit of scope creep during the project. 
- Building new features without realizing the full impact on current features and possibly breaking current features like automated fees or procedures. 
- Regarding the scoping/discovery work, with this involving all of ROW's permit workflows, scoping will need to be organized well and in smaller, defined increments. 
- What AMANDA features/solutions are available that we're not aware of?

### 2. Scope / Deliverables

**In Scope**
- Reviewed current deliverables/outcomes; discussed how each deliverable will need to be further defined to identify actual solutions.
![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/82e15188-d184-4b0b-874a-728d741e5828)


**Out of Scope**
- Non-AMANDA solutions


### 3. Project Team
![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/3fd76b23-0677-433b-bbed-77c596452e78)


### 4. Logistics
**Sprint Logistics:** 
- Cadence: 2 week sprints.
- Sprint Planning & Sprint Reviews will be combined in one bi-weekly project meeting. 


**Communications:**
- Core Team, Support Team, and Advisory Team will communicate on a dedicated project Teams channel
- Awareness Team will receive monthly email updates, or more frequently as needed.


### 5. Next Steps
**Tracy Will:**

- [ ] Schedule re-occurring project meetings
- [ ] Create Teams channel
- [ ] Schedule sync with Nate & Vish to plan next steps re: scoping.

**Comment by TracyLinder** [comment]
Metrics need to be collected for all permit folders: RW, DS, EX, PSM

**Comment by TracyLinder** [comment]
**Core Team Mtg 5/12/21**




----
**Discussed Vish's analysis of current permit workflows:**
- All review activity currently happening in/on Web Acceptance process, which isn't good for our desired outcomes. This process is an enterprise process that we can't customize. ROW will need to stop leaning on this process for capturing intake/review data. 
- Proposing that we automate a bypass through the Web Acceptance Process. We are now capturing the correct review start date in the folder in-date field, so using the Web Acceptance process may not provide any value anymore. 
- We should update this project from 2 phases to 3 phases:
    1. Updates necessary to capture data for initial permitting
    2. Updates necessary to capture data for renewals/extensions
    3. Create reports
**OR**
    1. Updates necessary to capture data for initial permitting
    2. Create reports
    3. Updates necessary to capture data for renewals/extensions
    4. Create reports



**Discussed Possible Solutions:**
- Auto-bypass the Web Acceptance process
- Use a new process 'ROW Permit Intake & Review'
    - Certain permit types may need their own intake/review process, depending on requirements, TBD
- Use this single process to:
    - Begin Review
    - Record review determination (approved, rejected...)
    - Record review cycle #'s
    - Record review deficiencies using process deficiency features
    - Allow customer to resubmit online via Portal, and automatically kick-off the next review (using the same process, over and over until complete)

**Comment by TracyLinder** [comment]
I made an issue to document notes from our biweekly project meetings. See #[6218](https://github.com/cityofaustin/atd-data-tech/issues/6218)

**Comment by TracyLinder** [comment]
### Update - Project on Hold Until 10/19/21

![Screen Shot 2021-08-10 at 2.12.02 PM.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/ea536bac-d63a-4c12-b614-19d6c6198bb8)

**Comment by TracyLinder** [comment]
### Update

This project was placed on hold in Aug 2021 due to the FY23 fee update project and then for the AMANDA V7 and Portal upgrade projects. This project needs to be prioritized with ROW again. I spoke with DTS' Data Science team about this today and asked Charlie to join me in a meeting with ROW next Monday 6/5/23.

**Comment by TracyLinder** [comment]
### Update Mtg

P: This is a big project - should we wait for ECM before trying this? Still a need - consider that it will be replaced so the solution won't last for more than 1-2 years. 

D: Does DSD's expansion of PDox affect this at all? UC, GP - They're in UAT and training now.
A: Wherever the data lives, we'll need to grab it there.

**Comment by TracyLinder** [comment]
### Update Feb 13, 2024

Performance metric data continues to be a high priority for ROW. The best solution is a new permitting system which is being procured as part of the ECM Replacement. Given our constraints we've altered our approach by prioritizing sprint sized work that improve performance data collection and reporting. Our data science team has provided ROW with a performance dashboard that has been updated to accommodate new data points as they are added to ROW's workflows. This project is likely to stay in the backlog, with the deliverables being tracked through the ECM Project.
