### ISSUE TITLE
Restructure Inspection table in Contractor work order module

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#5033]
- [x] Reformat "Materials Used"
- [x] Attachments need to have "plans" type
- [x] Add Comments (edit only) - SMB and Contractor
- [x] Adding prototype work order (ATSD example of multi-day, multi-week w/Christina)
- [x] Adding "Corrected Date" - Contractor side to inspection table/form

**Comment by dianamartin** [comment]
@amenity I think the work I did was documented in #5052

**Comment by amenity** [comment]
Sweet, thanks!
