### ISSUE TITLE
Project: Refactoring AMD Technician Work Orders

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#5125]
This AMD Technician Work Order refactoring will allow for better work tracking and asset management.

## Background
When the AMD Data Tracker was built in 2017, a lot of the components were created organically, and being in the application for many years, there are some usability enhancements that the Arterial Management Division (AMD) would like to see. This refactoring project also includes the enhancement of getting the other AMD workgroups the ability to use work orders for their own discipline areas. 

Discussions began around Nov 2021. 

## Scope & Deliverables
This first refactoring is focused on Signal Technician Work Orders. The goal is to redesign the forms to improve efficiency of filling out work orders and to standardize the data collected in the work order to improve reporting capabilities. 

## References
- [Data Tracker interface](https://atd.knack.com/amd#work-orders/?view_713_filters=%5B%7B%22field%22%3A%22field_3601%22%2C%22operator%22%3A%22is%22%2C%22value%22%3A%22Technicians%22%7D%5D)
- Initial Requests: 
  - #881
  - #1921
- [AMD Work Orders Flow Chart](https://miro.com/app/board/uXjVO_E4pQg=/)
![53158033348_2caf1418a7_o Cropped](https://github.com/cityofaustin/atd-data-tech/assets/61209591/bc0c4783-4c6e-4e51-8d6c-068ea2e4ff1d)

_Requested by Brian C., Arterial Management_

---
This Github issue represents a project of Austin Transportation's [Data & Technology Services](https://austinmobility.io/) team. Project status is documented regularly in the comments below.

**Comment by amenity** [comment]
_@dianamartin update from today's AMD meeting:_ 

Have been working with users over the last few months to reimagine the AMD Work Orders. Started with creating a standardized list of the "Work Completed" on a job location. 

Refactored elements of"New Work Order" form and "My Work Orders details page" in the test environment. 

-   Layout changes on details page

-   Feature for "Scheduled Work" in table format 

     -   Need stakeholders to finalize the list of "Scheduled Work" - IN PROGRESS

-   Feature for "Completed Work' in table format 

     -   Need stakeholders to provide final list of "Actions" and "Components" - IN PROGRESS

-   Preventative Maintenance log - IN PROGRESS 

     -   Stakeholders to review fields and do preliminary test in test environment with AMD technicians - ON DECK

-   Feature for "Adding Comments"

-   Feature for "Adding Attachments" - IN PROGRESS

     -   Feedback changes, discovery/testing of alternate structure

Will begin on refactoring the Edit Work Order Forms next - ON DECK

**Comment by amenity** [comment]
Meeting today with AMD: 
## Notes
- AMD has not completed pick lists, but working on them and close
- Not all work orders are going to have inventory - make it required but have a “no inventory required” option
- Going to need to train technicians that they can now enter “Follow-up Description” without submitting work order using the modal
- Important that techs can truthfully report that checks were not performed but still submit work order 
- BB work orders will always needs to have some sort of free text box to describe work, in the past attempts to convert everything into structured data has hurt communication
- 80% of the “non-technican” work orders are currently just ways to create inventory tickets right now; Ivonne has been using for Moped projects but technicians don’t see them; Ultimately will want non-AMD people to “request” a work order - need to identify how we can bridge the gap until that’s implemented or expedite implementation 

## To-do
- [ ] “Checked All Pads, Colors, Buttons…” needs to be changed to multiple choice, required, no default value
- [ ] “Submit” in modal changed to “Save/Submit”
- [ ] Technicians should not be able to reassign work order
- [ ] “Project ID”  change to “Moped Project” everywhere, including “New Work Order” page
- [ ] Cost estimate should be required to submit cost estimate in addition to material list
- [ ] @amenity set up meeting w/ AMD to think about the Moped work order work flow

**Comment by amenity** [comment]
@dianamartin - can you add a link to the Miro board to this index issue?

**Comment by amenity** [comment]
Also, @johnclary @dianamartin ... I think this probably constitutes a project. 😬

**Comment by dianamartin** [comment]
@amenity This workflow was in Visio, will need to migrate it to Miro soon. When I create it, I'll link it.

**Comment by amenity** [comment]
@dianamartin - gotcha. Will you post a screenshot of it here or paste it where you want it in Miro? I need the Miro link to schedule that meeting.

**Comment by dianamartin** [comment]
## Screen shot of workflow AMD
### Top of flow
![image](https://user-images.githubusercontent.com/21112975/161626562-3d5de1e1-7665-49fa-9e27-0198cb30a259.png)
### Bottom of flow
![image](https://user-images.githubusercontent.com/21112975/161626731-ee771758-f1b3-44bc-a8e8-20db7492c7d1.png)

**Comment by amenity** [comment]
Thanks, @dianamartin - started the board here: https://miro.com/app/board/uXjVO_E4pQg=/

**Comment by amenity** [comment]
@amenity convert to Project Index

**Comment by dianamartin** [comment]
@amenity I started the Project Index description stuff, one less thing you have to do

**Comment by amenity** [comment]
Thanks, @dianamartin 😊

**Comment by amenity** [comment]
@ChristinaTremel is going to take the reigns on this project. 🎉

**Comment by amenity** [comment]
@dianamartin @ChristinaTremel - please write a several-sentence update here & delete this comment. ✍🏻 🗑️

**Comment by dianamartin** [comment]
There was a revamp to the Technician work orders that was pushed out Oct 2022, a technician training was schedule on 10/19/22 to go over the new work order functionality.  
- roll out of Scheduled Work form/tables
- roll out of Completed work form/tables
- new Trouble Call work order form
- new Scheduled work order form
- enhancement to follow-up work orders
At the end of 2023 we had discussions focusing on Non-Work Order technician pages. Discussions will resume in Feb 2023 as we get our new Product Manager onboard.

**Comment by ChristinaTremel** [comment]
## Status Update - 4/27/2023
DTS has been meeting to strategize how to move forward with Enhancing AMD's Data Tracker Application. I met with Brian and Henry to discuss the Divisions needs for Data Tracker and realized the scope of this project is potentially a large scale refactoring of the application.

- Plan is to start meeting with AMD's groups to document what they use and manage in Data Tracker. With this effort we will start developing a Data Tracker Blue Print and a plan for how to enhance AMD's work orders. 
- While developing the Data Tracker Blue Print, we will also continue rolling out new, non-technician work order forms. A Communications Work Order form has been implemented and DTS will start looking at Contractor Work Orders and Signal Engineer Work Orders next.

**Comment by ChristinaTremel** [comment]
## Status Update - 9/29
- **AMD Data Tracker Blue Print**
   - Over the past several months, there have been immediate needs from AMD to create work orders for all of the AMD work groups. This has caused us to pause discussions on the bigger Data Tracker Blue Print, but we plan to start diving into the Data Tracker Blue Print in October. 
   - In this next fiscal year, we have also decided to increase the amount of sprint reviews we have with AMD. Instead of meeting monthly, we will start meeting every other week. This will allow us to start meeting more regularly and start discussing improvements that AMD would like to make to the Data Tracker 
- **Signal Engineer Work Orders**
   - Throughout this summer, we have worked in coordination with Brian C and Brian G to build out simple work orders for the Signal Engineers to use to track the work they are doing on a daily basis. We built out the work order form and had Signal Engineer staff test it for several weeks. The feedback we received was positive and we were able to roll out these work orders in August 2023. 
- **Inspection Work Orders**
   -  Currently, we are working with AMD to build out work orders for their inspector work group. We built a prototype and met with AMD to show them the progress. Through this conversation we found that there was a need to clearly identify the purpose of these work orders because this will help us determine how to build out these work orders the most efficiently.

### Future Enhancements
- Once we build out the inspector work orders, we will be continuing to enhance AMD's work order management by: 
   - Developing an AMD project intake form and tracking process
   - Developing preventative maintenance contractor work orders

**Comment by ChristinaTremel** [comment]
This project was completed in 2022 and the additional features that Arterial Management requested such as the inspector work orders, signal engineer work orders, and project requests have been split into their own individual projects. Closing this out as it has been completed! 🎉
