### ISSUE TITLE
[Enhancements] Phases

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#5210]
These are follow-up tasks and feature enhancement requests that spawned from https://github.com/cityofaustin/atd-moped/pull/187

### Quick fixes

- [x] Can you transform the UI values for "Active?" to Yes/No instead of True/False? Fine with true/false in the database but I think generally yes/no is preferable for user-facing copy. (also fine with changing this in the database if that's easier, will let you decide that). Actually, a toggle between yes/no would be very nice, but no worries if that's difficult.
- [x] Default sorting: can you make this sort chronologically from newest to oldest phase instead of by phase name?

### Larger enhancements

- [ ] User cannot add a phase name that's already been added. [Pending]
- [ ] If a user adds an active phase, set any other active phases to inactive. (I'm not positive of this requirement, let's discuss it as a group, but my instinct is to say that two phases shouldn't be simultaneously active)
- [ ] Current phase stored in moped_projects should automatically reflect the newest phase chronologically where "active is true" [#5309]
- [x] What do you think about moving the "+" from the upper right to below the table as a [FAB](https://material.io/components/buttons-floating-action-button)? (Similar to the "Assign team" page...)
- [ ] it would be nice if the date-picker calendar opened automatically when a date field is active. if y'all agree, we might move this into a separate issue to address it globally since we need this enhancement in Sergio's advanced table filters and will need it elsewhere.

### Other feedback
- [ ] When I first clicked the add button to add in a phase, I stupidly forgot to click the checkmark to save and lost the row. Totally user error but I'm just flagging it in case we run into that error during user testing.
- [ ] The slight lag between entering a new row and saving it, and then the row appearing is something I'm noting. Is this because we're waiting to see if the mutation is successful (otherwise it would display an error)? Really not a big deal but just thought I'd point out if anyone else thought anything of it.
- [ ] I'm unsure about all the pagination and search controls, and think users may want to see modified by/modified date columns here—but we can table that pending user testing.

**Comment by johnclary** [comment]
Related to #5309, I find it confusing to select the "Current Phase" during project creation. Possible alternatives:
-  Remove this entirely. The user can add a phase later.
- Automatically create a new phase record based on the value the user selects during project creation
- Add a step in the new project workflow which enables the user to add one or more phases

**Comment by amenity** [comment]
- [ ] User cannot add a phase name that's already been added. 
_We're opting to let users add phases multiple times for now. No extra business logic unless warranted by user feedback or usability testing._
- [ ] If a user adds an active phase, set any other active phases to inactive. 
_Addressed in https://github.com/cityofaustin/atd-moped/pull/274_
- [ ] Current phase stored in moped_projects should automatically reflect the newest phase chronologically where "active is true" [#5309]
- [x] What do you think about moving the "+" from the upper right to below the table as a [FAB]
_This will be covered by #5375_
- [ ] it would be nice if the date-picker calendar opened automatically when a date field is active. if y'all agree, we might move this into a separate issue to address it globally since we need this enhancement in Sergio's advanced table filters and will need it elsewhere.
_Adding this as a suggestion to https://github.com/cityofaustin/atd-data-tech/issues/5375_

### Other feedback
- [ ] When I first clicked the add button to add in a phase, I stupidly forgot to click the checkmark to save and lost the row. Totally user error but I'm just flagging it in case we run into that error during user testing.
_This was covered in https://github.com/cityofaustin/atd-moped/pull/268_
- [ ] The slight lag between entering a new row and saving it, and then the row appearing is something I'm noting. Is this because we're waiting to see if the mutation is successful (otherwise it would display an error)? Really not a big deal but just thought I'd point out if anyone else thought anything of it.
_Adding this as a suggestion to https://github.com/cityofaustin/atd-data-tech/issues/5375_
- [ ] I'm unsure about all the pagination and search controls, and think users may want to see modified by/modified date columns here—but we can table that pending user testing.
_Adding this as a suggestion to https://github.com/cityofaustin/atd-data-tech/issues/5375_
