### ISSUE TITLE
Onboard IT Geospatial Analyst Sr.

### ISSUE THREAD

**Issue by jaime-mckeown** [cityofaustin/atd-data-tech#5269]
### Accounts
- [x] CTM New Employee form [Jaime]
- [x] Network account request [this was part of New Employee Form]
- [x] Phone request (phone request was on new employee form)
- [x] Microsoft Teams
- [x] 1Password
- [x] Slack (request sent to Amenity)
- [x] Google Drive
- [x] Github Team (post Andrew's user name in atd-dev slack and the dev's can add him to the "Transportation" team
- [x] DTS Email Group (he was automatically added)

### Software
- [x] Zenhub Extension
- [ ] Docking station driver (mac only)

### Hardware
- [x] Desk/Office Space [space behind Jaime]
- [x] Computer
- [x] Monitors
- [x] Docking station
- [ ] Chair
- [ ] Power supply
- [ ] Keyboard
- [ ] Mouse
- [ ] Badge

### Meetings
- [x] Introduction to DTS [Jaime pls schedule for andrew's first morning]
- [x] Add Andrew to the above meeting after his account is created
- [x] Service Delivery Training @jaime-mckeown please schedule with Amenity (training scheduled for 3/19)

### Calendar Invites
- [x] Upcoming Sprints
- [x] Recurring Sprint Retro and Sprint Planning meetings

### Communications
- [ ] Newsletter announcement
- [ ] Email to Cameron Rd employees

### Work plan
- [x] First day, week, month plan

**Comment by jaime-mckeown** [comment]
@johnclary Andrew's account has been created in the system.

**Comment by johnclary** [comment]
Thanks!

**Comment by jaime-mckeown** [comment]
@johnclary do you know when Andrew be meeting with Scott to get his computer? Just wondering if our 10am Intro meeting is too early if he needs to pickup his computer on his first day.

**Comment by johnclary** [comment]
scheduled meeting to make a work plan for Andrew.

**Comment by jaime-mckeown** [comment]
@johnclary can we close this?

**Comment by johnclary** [comment]
@jaime-mckeown closed. thanks :) :)
