### ISSUE TITLE
Feature: Need to rebuild Officer Citation Tracking - Officer Management - disconnect from "Officer Names" object reconnect to "Account" object

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#5276]
Officer Management page used an object table called `Officers`, this was a list of PE officers to select from for the Officer Citation Tracking. Using the `Account` object to link to the Dispatch/SR Tracking in the system. 

Need to rebuild this perhaps if they have a need, the list is old and redundant to the accounts table. We'd want to make a decision so that PE staff don't have to keep up with 2 lists.

**Comment by dianamartin** [comment]
This was done last week
- [x] Added connection to `Name` field (from Accounts)
- [x] Added "Name" field to Add Officer Citation Tracking
- [x] Added "Name" field to Edit Officer Citation Tracking
