### ISSUE TITLE
Sprint Review - Dispatch Tracking

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#5279]
Review with stakeholders at the next Sprint Review meeting on 3/4

Parking Enterprise Service Request Page
- Built page out, similar to AMD and Signs and Markings
- Added several fields to show 311 SRs or Non-311 SRs

Service Request Details Page
- Added SR Details page

Service Request Activities Form
- Created "Activities" form
- Used canned activities from Signs and Markings
- Combine the "Dispatch Categories" into the Activities form

**Comment by moorerst** [comment]
Notes from Sprint Review
When do you add activities to the 311 SR?
Receive SR from email notification
Dispatch Officer / provide officer the details/officer goes to site
Report back to Dispatcher/ Dispatcher adds activity to SR

Different Types of CSR's / CSR is sent via email notification to everyone
Residential
Booting
Parking Violation
Pay By Phone - Joseph team will pick up the CSR's for technical issues related to Pay by Phone
CSR's received outside of normal business hours - these should be flagged by 311 and sent to PD but we are receiving them anyway. 

- [ ] a need process for handling these types of CSR's 
New Activity - Received After Hours / Outside Agency Transfer???
Activity 311 Feedback with a email notification back to 311 indicating SR received outside of normal business hours???

- [ ] need to set up separate meeting with Levi, Jasmine, Shavyvonne and Joseph to discuss the process for handling different CSR's - preferred time W - F after 10:00 
- [ ] need to set up Technical Huddle to discuss when to start the process of integrating CSR's into Knack
- [ ] need to determine when is a good time to have the dispatchers do a small sample of double entry into SP and Knack to become familiar with the system and provide feedback
Questions:
Can I modify what the day shift was working on? - Yes you can see what is In Progress and what has been did done
Can I review the photos the Officers attached from the field? - Yes you can see them from the In Review status which is 
 where the Dispatcher should review the SR and take any further action needed. 

- [ ] What if the photo needs to be retaken?

- [ ] Need to URL for Netmotion which is used to manage tablet locations - one of the stakeholders will provide the URL
- [ ] Reports - needs a report on the # of citations issued

**Comment by moorerst** [comment]
created separate issues for items that were identified during Sprint Review and need to be addressed. Closing
