### ISSUE TITLE
Implement DSDD tracking module in Data Tracker

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#5288]

**Comment by dianamartin** [comment]
# Builder To Do
- [ ] Create `DSDD Asset` object table
- [ ] Create `DSDD asset` - object table
- [ ] 
- [ ] Create connection Asset to `signal_work_orders`
- [ ] Create `DSDD Locations` object table 
- [ ] Create DSDD Asset page
- [ ] Create DSDD New Asset form
- [ ] Create DSDD location

**Comment by johnclary** [comment]
@dianamartin take a look at the StreetsOnCloud export. Once you have a template figured out you can pass the data entry to Max.

**Comment by dianamartin** [comment]
# Discussion Notes
- After I sync'd with Max, he share a DSDD Deployment spreadsheet that showed DSDD locations that were queue up for the rotating DSDD program. This seemed to be the biggest need for DSDD mgmt
- Email function and tracking 
- Max downloaded DSDD units/locations that I an import into the system
- Creating a workflow of all the stakeholders and their functions in the bigger system

**Comment by dianamartin** [comment]
- Sync'd with Max again today so he could see the progress I made with the DSDD asset pages and DSDD location pages
- He was happy with the latest configuration
- Created an account for him 
- He will test the functionality by populating missing Serial # for the doors and adding the locations in the deployment queue

**Comment by dianamartin** [comment]
Checking in with Max 3/18
>How's DSDD testing?

**Comment by dianamartin** [comment]
Max wrote back on 3/19
>District 6 DSDD's need to have their own asset list and queue because the units are only to be rotated in district 6. On Monday, can you assist me in figuring out how to accomplish that?

>Also, we have an urgent need for DSDD's on Westgate Blvd, (not urgent as in needs to be solved today, but needs to jump to the top of the queue. Let's discuss how to do that on Monday. There was no request behind this - the Council office wants it and is experiencing intense pressure from he neighborhood.

>One last note: I was reviewing Daniel's queue and realized after attempting to put in some locations that Daniel did not include addresses, block #'s or a section of the roadway in his requests. I emailed TED requesting email requests dating back to May 2020 so I could resolve this issue and update the queue. It looks like there are not too many outstanding requests overall. I imagine requests slowed down due to the pandemic.

**Comment by amenity** [comment]
@dianamartin - thanks for the update. 

What do you recommend for the District 6 assets? Would it be simpler to include "District 6" in their names rather than give them a new list and queue? 

What are we expected to do with regards to the Westgate Blvd requests? 🤔

**Comment by dianamartin** [comment]
@amenity I talked to Max and I simply updated the "Display Name" of the asset to include the "Category" field which indicates if the asset is District 6 asset, so that fixed that issue. The high priority DSDD request issue was fixed by Max changing the request date to be earlier than what is in his queue (basically skipping the queue) per Council or neighborhood reasoning. I told him how to sort/filter on the DSDD locations page and for him to try that out first before we create a new field specifically for "District 6" locations.

**Comment by amenity** [comment]
Sweet, sounds good. 🧠

**Comment by dianamartin** [comment]
Max has been using the DSDD module for a few weeks now, no additional features to be added besides AMD WO connection
