### ISSUE TITLE
Feature: Create DSDD Locations page

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#5411]
DSDD locations

The primary management of DSDD program manager is managing the DSDD Locations. 

Max was able to share the DSDD Deployment Log that was used to manage which DSDD location was next to be installed.

**Comment by dianamartin** [comment]
Showed Max the new DSDD locations page. I was able to show him how to add a location and associate a DSDD unit. 
- We decided to have the `Location Status` be automated:  
- [x] when a location was added without a DSDD unit then it was in "Pending" status
- [x] when a DSDD unit was added to a location, the status would update to "Active" status
- [x] when an "End Date" was added and submitted the status would update to "Inactive"
- [x] the "Edit" button was hidden when in an "inactive" status
- [x] Removed the "Location Status" on the "Edit Location" form
- created an account for Max in Data Tracker
- confirmed he could log in

He's going to do a soft test and get in there and start cleaning up and populating missing fields

**Comment by dianamartin** [comment]
Closing as feature has been built out and being tested, will create additional if major changes are needed.
