### ISSUE TITLE
ROW Specific AMANDA V7 Training

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#5421]
- [ ] How to perform conflict checks
    - #5422 
- [ ] Inspections
    - #5423 
- [x] How to create LC folders
    - Will be included in Tier 4 training
- [x] In-depth process tab training
    - Will be included in Tier 3 training
- [x] Advanced search 
    - Will be included in Tier 3 training
