### ISSUE TITLE
New Knack Builder 2.0 Migration

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#5426]
## Knack Announcement

On May 1st, 2021 all apps will be upgraded to the new Knack Builder. This means on that date your apps will load using the new Knack Builder and the old Builder will no longer be available.

If you haven’t enabled the new Builder yet, you can do so on any app in your Dashboard. Read more here.

Watch the webinar introduction and read more about what's included in the new Builder on this page.
Visit the New Builder knowledge base.
Learn how the new Builder will affect custom code.

## Application Assignments
COMBO
- [x] Data Tracker [John/Diana] 
- [x] Visitor Sign-In [John?]
- [x] RPP [Chrispin] - Dev. assist

DEV ASSIST
- [x] VZA [Surbhi] - Dev. assist
- [x] Signs and Markings [Diana] - Dev. assist

SURBHI
- [x] DTS Portal [Surbhi] 
- [x] Shared Mobility [Surbhi]
- [x] ATD Forms [Surbhi]

CHRISPIN
- [x] ROW Portal [Chrispin]
- [x] Development Services/TIA [Chrispin]
- [x] HR [Chrispin]

DIANA
- [x] Finance [Diana]
- [x] Street Banners [Diana]
- [x] Parking Enterprise Reporting Portal [Diana]
- [x] ASMP [Diana]

**Comment by dianamartin** [comment]
# Issue Template for testing
SET-UP
- [ ] Test Environment - check if one exists for 2021 , if not create new one
- [ ] Update Application Inventory
- [ ] Get an application power user to help test
- [ ] Set up password for testing env - power user

BACK END
- [ ] Big button re-direct links
- [ ] Big button (rich text) - add tags 
- [ ] Coordinate with dev team
- [ ] Get code working in test application
- [ ] Schedule maintenance down time for app

FRONT END
- [ ] Check for broken icons
- [ ] Check for broken links
- [ ] Check multiple columns
- [ ] Document every change that needs to be changed in Prod application
- [ ] Get code working in test application
- [ ] Schedule maintenance down time for app

### Before Migration May 1st, 2021
- [ ] Create back-up for application - April 29/30th

**Comment by ChrispinP** [comment]
TDS Switchover complete

**Comment by ChrispinP** [comment]
RPP Switchover complete

**Comment by ChrispinP** [comment]
HR Switchover complete

**Comment by ChrispinP** [comment]
Visitor Sign In Switchover complete
