### ISSUE TITLE
New Knack Builder: Data Tracker Application Testing

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#5432]
SET-UP
- [x] Test Environment - check if one exists for 2021 , if not create new one
- [x] Update Application Inventory
- [ ] Get an application power user to help test
- [ ] Set up password for testing env - power user

BACK END
- [ ] Big button re-direct links
- [ ] Big button (rich text) - add tags 
- [ ] Coordinate with dev team
- [ ] Get code working in test application
- [ ] Schedule maintenance down time for app

FRONT END
- [ ] Check for broken icons
- [ ] Check for broken links
- [ ] Check multiple columns
- [ ] Document every change that needs to be changed in Prod application
- [ ] Get code working in test application
- [ ] Schedule maintenance down time for app

### Before Migration May 1st, 2021
- [x] Create back-up for application - April 29/30th

**Comment by dianamartin** [comment]
- Created backup for app `BACKUP| APR 22 2021 | Austin Transportation Data Tracker`
- Updated Application Inventory to add back up
- App finished copying, Copy time: 4:57 pm - 9:08 pm (~4 hrs, 11 min)
- Checking BACKUP - still missing SSO functionality in the back end
- Had checked reports in TEST, believe the only report that might have an issue an possible rebuild it on "
  - Traffic Count & Data Collection Request>Reporting>`Completed Requests - By Assigned To`
  - it has Jamie & Brandon - assignment metrics

**Comment by dianamartin** [comment]
# Report Configuration for Traffic Count and Data Collection

**Comment by dianamartin** [comment]
Created issue for reporting bug in new builder #5924, closing this.
