### ISSUE TITLE
Feature: "Mid-Project Inspection" request button for SMB Contractor

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#5457]
- [x] Email notification when contractor clicks "Submit for Review", emails Joe Mike
- [x] Email notification "Approved" - email Tooran? (Not necessary, as she will likely see it in her queue)
- [x] `Request Mid-Project Inspection` button - At the end of the day if the work order wasn't completed (multi-day) this will trigger an email notification for Joe Mike

**Comment by dianamartin** [comment]
Rescheduled Friday meeting with Christina to 3/16. Christina is good with all the email notifications. She'd like to update the GitHub help guides before switching to Joe Mike and Tooran's email. 
- Will switch to Christina's email so she can test and create help guide material.

**Comment by dianamartin** [comment]
Talked to Christina an she got reassigned to something, will be having a meeting with SMB folks next week so they can plan to kick off this month with SEFBO.
