### ISSUE TITLE
Projects page 2.0 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#5482]
- [x] - Implement design refinements #6061 
- [x] - [Bug] Advanced search on Projects page doesn't allow "is not blank" or "is blank" operator #6066 
- [x] - Remove road icon and link "Project name" to project page #6065 
- [x] - Filter all projects by project team members #5517 
- [x] - Update columns displayed in table and available as filters #6063
- [x] - Change default sort order to show most recently-modified first #6094

**Comment by johnclary** [comment]
My not strongly held opinions:
- Project name should be hyperlinked to open the project summary
- That “edit road” icon that opens the project summary can be removed
- The project description can probably go away and be replaced with more useful fields once we have them
- Projects should sort by most recently modified first, and there’s something funky going on with default sorting. The initial sort icon suggests that projects are being sorted newest > oldest by start date, but that’s clearly not happening (screenshot below)
 
<img width="1207" alt="Screen Shot 2021-03-11 at 10 36 23 PM" src="https://user-images.githubusercontent.com/14793120/110969338-2fd9ea00-831e-11eb-9b85-68141f2d853f.png">

**Comment by zappfyllc** [comment]
@sergiogcx with phase/team please consider if we should be making any data model changes for the many-to-many relationships in project phase and project team. Are there any values that should be auto-generated (e.g. which phase is active, a list of all active users in a project team) by the database and not the UI? Any benefits there?

**Comment by amenity** [comment]
@johnclary @amenity — @chiaberry is going to take this on. Need to get a new mockup. @johnclary - do you have this somewhere? if we could do one without color changes, that would be great.
