### ISSUE TITLE
Project: Custom Sign Fabrication Requests

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#5485]
Build a page to accept custom sign fabrication requests. These include signs for special events, staff retirement, City of Austin parking lots, etc. 

> Describe the outcome you'd like to see when this feature is implemented.

We would like to see a page that allows: 

1. Requesters from ATD and other City departments to submit work orders for sign fabrication requests (including special events, retirement signs, signs for AFD/APD/AW/SBO). 
2. Sign shop to fill out the information on the signs types that they fabricated.
3. Allow sign fabricators to email VERY simple invoices to Crystal Torres so the Department that requested the sign can be charged.

**Notes**
Currently, we don't track how many signs we fabricate only other than through emails that the Sign Shop receives. 

> Describe any workarounds you currently have in place or alternative solutions you've considered.

This process is done in different ways depending on the Requester. This can include the requester coming by the sign shop, emailing, or calling. Invoices are created using a simple excel document and are emailed to Crystal Torres to be processed.

> Requested By
Christina T.

Request ID: DTS21-101725

![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/a2f8cb97-7626-47e8-b6c8-3ea0cb806c01)

---
This Github issue represents a project of Austin Transportation's [Data & Technology Services](https://austinmobility.io/) team. Project status is documented regularly in the comments below.

**Comment by dianamartin** [comment]
Talked to Christina about the scope of this project: 

## Builder Notes
- **Form**: Non-ATD requests (outside departments) - this form would also be able to handle ATD non MUTCD sign requests that are are not associated to a SMB work order. 
  - `Department`
  - `FDU`
- **Table**: Manage the requests 
  - Status: `New`, `In Progress`, `Fabricated Completed`, `Closed`
  - Closed: would be once the sign has been invoiced (if invoice is needed)
- **Related Tables**: 
  - Materials Used: Type of Sign, Size, What message was, Cost
  - Attachments: photo design, completed
- **Invoice Button**: that generates an invoice details page 
  - Option 1: email automates link to Crystal, she can pdf it. 
  - Option 2: ATD sign shop pdfs invoices, sends email to Crystal

**Comment by dianamartin** [comment]
Prototyped Sign Fabrication Work Order Requests
- [x] Created Sign Request Form
- [x] Created Sign Fabrication Work Order table (Dashboard)
- [ ] Build out Comment feature
- [ ] Email invoice
- [ ] Notification to Crystal T. - Finance

**Comment by dianamartin** [comment]
After having discussion with Christina, need to do

### Add fields 
- Type: `Custom - COA Operational signs`, `Location Signs`
- Design Approved: Y/N
- Status: `New, In Progress, Fabrication Completed, Closed`
- Photo Attachment: 
- Instructions/Comments:
- Size: predetermined list
- Colors: predetermined list (multi-select)
- Materials: `Aluminum or Corrugated board`

### Add/Configure Form - Internal
- Internal Request (Special Events, Parking (SXSW), ATSD)

### Needs more testing
- Validation Rules
- Display Rules

**Comment by amenity** [comment]
@dianamartin - please add whatever issues you'd like for the👆 refinements & additional features (e.g. Comments, attachments).

**Comment by amenity** [comment]
Meeting with users to review tomorrow. Will be adding more issues once we have their feedback and specifications.

**Comment by dianamartin** [comment]
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/a2f8cb97-7626-47e8-b6c8-3ea0cb806c01)

**Comment by dianamartin** [comment]
6/2: Sent finalized email to SMB stakeholders and Finance contact. Christina will work the new requester form distribution with the Sign Shop.
