### ISSUE TITLE
(EPIC) ROW Cost of Service Management [KNACK - ROW Portal]

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#5574]
### New features on the KNACK ROW Portal to facilitate the fee recovery portion of the COS workflow. 

**Fee Recovery Means:**
1. Data warehouse of all _valid_ COS payments
2. Ability to export COS data to be provided to partner departments
3. Ability to import updates to existing COS data
4. Ability to reconcile AMANDA COS payments with it's JVD entry
5. Ability to track COS payments that are disapproved by partner departments.

**Comment by TracyLinder** [comment]
### Permits by City Department, Report #1
Grouped by Submitted, Issued
Then sub grouped by CIP VS Non-CIP
- Primary (priority 3)
- Secondary (priority 4)
    - Managed by a MOU; not really reviewed
- Emergency (priority 1) 



----
### TCP Reporting, Report #2
_KNACK report._
- _Per Ryan, will require changes to the app so the data they need to report on can be captured_
- [ ] Schedule time w/ Ryan & Chrispin to scope this one.



----
### AULCC, Report #3
- Various data related to resubmissions and review cycles
- My feedback: This folder is not being used consistently ...



----
### Inspections, Report #4

**Comment by TracyLinder** [comment]
Tasks

**Scheduling:** 
- [ ] Reoccurring syncs w/ Ryan & Darren as optional every 3 weeks.
- [ ] KNACK scoping w/ Chrispin & Ryan
- [ ] AULCC scoping w/ Ryan, Darren, Isiah, Jacyln

**Git/Zenhub**

- [ ] Create issue for each report
- [ ] Add blockers on #2397

**Comment by TracyLinder** [comment]
### Update

I met with Ryan & Darren today to give them an update. 
- In Scoping: Permits by City Department, Inspections
- In Progress: AULCC, CIP Info
- Blocked: TCP Tracker work

**Action Item:**
- [ ] Schedule another sync 3 weeks from now, include Vish

**Comment by TracyLinder** [comment]
### Status/Update
**Delivered:**
- #5580 New Info CIP

**Review Q/A:**
- #2397 Merge Facility Owner and COA Division Infos
    - In DEV environment. Next: UAT & DevOps
- #5579 Inspections Report
    - In UAT, then DevOps

**In Progress:**
-   #5578 AULCC Report 

**On Deck:**
- #5576 Permits by City Department 

**Blocked:**
_Blocked by #1554 TCP Tracker Migration_
- #5577 TCP Tracker Features for ROW Cost of Service
    - New Fields: Owner, CIP Funded Project
    - Add cycle # to the submissions table
    - Add submission count to TCP details
    - Reporting: New & enhancements




----
- I'm going to cancel the sync meetings & instead send email updates.

**Comment by TracyLinder** [comment]
<img width="704" alt="Screen Shot 2021-05-25 at 2 26 33 PM" src="https://user-images.githubusercontent.com/49930868/119556993-490f0600-bd65-11eb-812c-3381546f38ad.png">

**Comment by johnclary** [comment]
Tracy and I are meeting on 10/7 to scope a the reporting solution/process

**Comment by TracyLinder** [comment]
I updated the name & description with our refined scope.
