### ISSUE TITLE
Update historical Data Tracker SR statuses to correct for bug reported in #5660

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#5661]
_@johnclary via email; okayed by Lance B._ 

After resolving #5660, we can compile a list of all issues that should be Closed (Duplicate) by pulling the issue ID from any activity of type "Close Issue (Duplicate)".  Once we have that list, we can do a bulk update to correct all the issue statuses.

There may be a small percentage of edge cases where the Close Issue (Duplicate) activity was added by mistake, and another activity was added to re-open the issue. We wouldn't catch those, but it's probably safe to assume that's < less than 1%.

**Comment by dianamartin** [comment]
- [ ] Created back up of `tmc_activities` - 135,519 records
- this kept failing :(
- [x] Exporting TMC_ACTIVITY = Close Issue (Duplicate) - 6107
- 1518 of the 6107 has issues with statuses of Closed Issue (Resolved), spreadsheet will have to be created for import
- [x] Created new .csv of the 1518 activities and their matching TMC issues
- Turned into pivot table to find the duplicates
- [x] Created new list
- [x] Created new test list (3 records to import before importing the whole Shibang!)
- confirmed the 3 SR records were "closed_resolved"
- [x] Imported 3 SR records as test
- confirmed the 3 SR records were "closed_duplicate"

REAL DEAL
- [x] Importing 1428 SR records
- confirmed the 2 spot check SR records were "closed_duplicate" from "closed_resolved"

**Comment by dianamartin** [comment]
@chiaberry John asked if you could manually re-publish the data in [this view](https://github.com/cityofaustin/atd-knack-services/blob/7032751ccc095c2875ebcc6365fd399549fbf392/services/config/knack.py#L43)

services/config/knack.py:43
        "view_2892": {

**Comment by amenity** [comment]
@chiaberry do you want an issue for 👆, or is it literally a button-push?

**Comment by chiaberry** [comment]
@amenity no need for an issue, the button pushing is in progress

**Comment by amenity** [comment]
Closing this, @chiaberry - thanks!
