### ISSUE TITLE
Enable inline editing for notes fields on "Signal Construction Status" table

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#5674]
_Requested by Rene o._

> What application are you using?

Data Tracker

> Describe the problem.

Difficult to update statuses during project meeting on Signal Construction Status page:  https://atd.knack.com/amd#signals/signal-construction/ .  Would like to be able to edit the "Internal Note" and External Note"  columns on this page.  

> Describe the outcome you'd like to see when this feature is implemented.

Would like to be able to edit the "Internal Note" and External Note"  columns on this page.  

> Describe any workarounds you currently have in place or alternative solutions you've considered.

Have to open each "Edit Signal Construction Status" page as we go through the meeting.  It is difficult to keep up during the meeting. 

> Is there anything else we should know?

If I have requested this in the past or it is not possible, my apologies.  Thank you!!! :) 

> Requested By
Renee O.

Request ID: DTS21-101795

**Comment by TracyLinder** [comment]
@amenity I'm moving this to needs scoping.

**Comment by amenity** [comment]
@dianamartin - what do you think about this one? Are you able to size with the info provided?

**Comment by dianamartin** [comment]
She's asking for a quick feature to be turned on "in line editing", but right now the information is being updated through an edit form. We are capturing the audit fields (Modified By, Modified Date), but also `Construction Note Date` which seems to be a particular note to see if the note has been updated recently. I think it's used to pull it into a process to update the feature in the Data and Performance Hub. @johnclary correct me if I'm wrong here.

**Comment by johnclary** [comment]
@dianamartin you are correct that inline editing is not ideal, because we need to capture the modified date and construction note date in order to propagate changes to Socrata and AGOL.  This will no longer be a limitation once we migrate to the new Knack builder in May.

In the meantime, I suppose we could allow Renee to inline edit the modified date, construction note date, and the internal/external construction notes. She would need to manually set those date fields in order to ensure that the ETLs pickup the changes.

Another consideration is the construction status email updates that go out daily when a note or a status have changed.
I took a quick look at the [form rules](https://builder.knack.com/atd/amd#pages/scene_910/views/view_2334) for the "Edit Construction Note" form and the [email tasks](https://builder.knack.com/atd/amd#data/object_12/tasks) that send updates to AMD staff. **There are no concerns here—that process does not rely on date fields.**

**Comment by dianamartin** [comment]
@johnclary thanks! I'll convey that to Renee and maybe we can come to a compromise until May!

**Comment by amenity** [comment]
Thanks, @dianamartin🙏

**Comment by SurbhiBakshi** [comment]
Notes - 

- [ ] Switch inline editing to Yes for Internal Note
- [ ] Switch inline editing to Yes for External Notes
- [ ] Add Modified Date to the table and allow inline editing
- [ ] Add Construction Note Date to table and allow inline editing
- [ ] Communicate to Renee that requested changes have been made and once AMD Data Tracker is migrated to the New Builder in May, she will not need to put edit the Modified Date field.

**Comment by dianamartin** [comment]
Renee reached out to thank us for this feature
>Hey just wanted to say that having the ability to edit statuses on this [page](https://atd.knack.com/amd#signals/signal-construction/?view_1988_sort=field_2452|asc), without having to open each location works great!!  This is very helpful and makes it easier to keep up during the meeting!!!  Just wanted to say thanks!  

>If your group is like most, you only hear when things are not working.  Thought you might like to know when something is working well.  

Surbhi and I talked to Renee because she needed to know that she was needing to update the "Modified Date" and the "Construction Note Date". 
- @SurbhiBakshi will update on the backend some records that Renee changed today bc she wasn't aware she had to change the dates yet

**Comment by SurbhiBakshi** [comment]
Updated the Modified Date and Construction Note Date for the records that were changed in the meeting today morning.

**Comment by johnclary** [comment]
Thanks for sharing the feedback. Great work y'all!

Heads-up, in order for the changes to be propagated to AGOL and Socrata, the modified date has to be the current date. For example, say that Renee made an edit three days ago, but forgot to set the modified date. So today she goes into the data tracker and sets the modified date to three days ago, the ETL will not pickup those changes. Does that make sense?

**Comment by dianamartin** [comment]
@johnclary Thanks for the clarification. Yes, it makes sense it won't update if you backdate a record. We made Renee aware that she's responsible for updating the `Modified Date` and `Construction Note Date` right now. When the new builder is switched, she'll just be responsible for the `Construction Note Date`, but not the `Modified Date` anymore. She's also aware that if she doesn't put the dates in they won't push to the Socrata or the dashboard map.
