### ISSUE TITLE
Deploy DSDD Work Order changes to AMD Data Tracker production

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#5714]

**Comment by dianamartin** [comment]
In TEST | AMD - 17 MAR 2021 | AMD Data Tracker
- looked at existing AMD Work Orders that originate from the asset
- noticed they had the wrong asset types, probably bc you can edit after it gets created, just a quick way to create work order
- they are unassigned which I confirmed when going to the "unassigned" tab of the work orders (technicians)
- reviewed the signal work order fields to see which ones can be pre-populated when a new DSDD work order form is created

## TO DO in AMD DATA TRACKER PRODUCTION
- On DSDD page>View DSDD details
- Added Menu>New Page (renamed to "DSDD Work Orders")
  - Added form `work_orders_signal` connected to page's `dsdd`

### Back end prep
- [ ] ASSET_TYPE field on `work_orders_signal` object
- Need to add `Dynamic Speed Display Device (DSDD)` to "ASSET_TYPE" field - drop down choice

### Added Fields to form
- [ ] WORK_TYPE_TROUBLE_CALL 
  - rename to "Problem Reported"
- [ ] WORK_TYPE_OTHER 
  - rename to "Work Type - Other"
  - description: _Types from the drop down will appear on AMD Work Order table. Other Type - doesn't actually get seen._ 
- [ ] JOB_DESCRIPTION 
  - rename to "Job Description"
  - description: _This appears on the AMD Work Order table. Include the keyword: DSDD_ 
- [ ] WORK_ORDER_INSTRUCTIONS 
  - rename to "Work Order Instruction/Comments"
  - description: _This appears on the the AMD Work Order details page_

## Form Rules

### Submit Rules
- Redirect to parent
 
### Display Rules
- WORK TYPE TROUBLE CALL - Other
  - Show/Hide: WORK TYPE OTHER

### Record Rule Configuration
- WORK TYPE - TROUBLE CALL
- CREATED BY
- CREATED DATE
- WORK REQUESTED BY - Austin Transportation Staff
- ASSET TYPE - Dynamic Speed Display Device (DSDD)
- Workgroup - Technicians
- WORK LOCATION - to connected value `dsdd>Current Location`

**Comment by dianamartin** [comment]
- Reordered the button on the menu bar
- Added menu bar, new page on DSDD details page
- Added form on new page
- Added work order signals table on DSDD details page

**Comment by dianamartin** [comment]
Messaged Max
> do you have some time to talk about DSDDs sometime?

**Comment by dianamartin** [comment]
@amenity are you able to schedule a quick 30 min meeting with the stakeholders: Billy, Max, you and me to finalize the DSDD work order process or do you want me to?

**Comment by amenity** [comment]
Totes able, @dianamartin!

**Comment by amenity** [comment]
Would that be https://github.com/cityofaustin/atd-data-tech/issues/5290 or should I add an additional issue?

**Comment by dianamartin** [comment]
@amenity I think we can reuse #5290 bc I just did a crash course demo with Max this morning. I showed Billy the other day when I had done it in the test environment.

**Comment by dianamartin** [comment]
Closing since we have the final demo meeting this Friday, 4/16 and we have a different issue for it as well
