### ISSUE TITLE
Feature: Configure DSDD emails, Follow-up created, DSDD WO Closed

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#5820]
Needs a new component
When a follow-up work order 
- [x] Updated form record rule for follow-up to associated the dsdd

NEW FEATURES
**Email configuration at at the create of a follow-up
**Email configuration at the time of WO Closed

WORK FLOW
WORKFLOWS
- Work Order by max, say needs Follow-up, Submit WO
- Follow-up Created by Supervisor, Closed WO (EMAIL)
- Follow Created - Unassigned (EMAIL)

Email to contain
- WO details link
- Problem
- Asset ID

**Comment by dianamartin** [comment]
Delete Test WOs in PROD

- [ ] WRK21-110995	
- [ ] WRK21-111825	
- [ ] WRK21-111830
Time Logs

**Comment by dianamartin** [comment]
- [ ] Test that Follow-up work order associated DSDD asset
- [ ] Configure Follow-up work order email from this [page](https://builder.knack.com/atd/amd#pages/scene_644/views/view_1718)
- [ ] Configure Close work order email from this [page](https://builder.knack.com/atd/amd#pages/scene_435/views/view_1226)

**Comment by dianamartin** [comment]
Email issue is on #5409, closing this
