### ISSUE TITLE
DSDD Queue. I need to be able to remove DSDD items in the queue built in Knack Data Tracker.

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#5867]
> What application are you using?

Data Tracker

> Describe the problem.

DSDD Queue. I need to be able to remove DSDD items in the queue built in Knack Data Tracker.

> Describe the outcome you'd like to see when this feature is implemented.

TED will be able to remove DSDD requests in the queue when/if engineering staff determines a site is not viable for placement.

> Describe any workarounds you currently have in place or alternative solutions you've considered.

None

> Requested By
Max S.

Request ID: DTS21-101915

**Comment by ChrispinP** [comment]
@dianamartin Would you be able to scope this?

**Comment by dianamartin** [comment]
@ChrispinP yeah I talked to him before he put this in, it basically needs a delete button for his table.

**Comment by dianamartin** [comment]
Changes Made
- [x] Added "Cancel" form (edit form)
- [x] Added "Cancel Reason" - required
- [x] Added "Cancel" field to right side of table
- [x] Moved "Edit" field to left side of table
- [x] Disabled in-line editing
- [x] Added display rule to table, "Cancel" will only show up on "Pending" statuses, hidden for the other statuses

Messaged Max
>I got your request and I added a "Cancel" button to your DSDD Locations table
>- It changes the "Location Status" to "Cancelled", and makes you enter a "Cancel Reason"
>- Cancel button is on the far right hand side now
>- The "Edit" button moved from the far right hand side to the far left hand side
>- I disabled the in-line editing from the Locations table in case of accidents, just use the "Edit" button for updates

**Comment by dianamartin** [comment]
Emailed Max 
>I messaged you about being able to “Cancel” a DSDD Location rather than delete it. It’ll change status and will be removed from the “Pending” queue. 
- Let me know if you have questions. You can look at my Teams message about the other minor things I did as well.
