### ISSUE TITLE
Meeting: Check in on Signal Requests Dashboard, 4/21

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#5876]
### Participants
John, Renee, Diana

### Agenda
Add agenda here or create agenda from [this template](https://docs.google.com/document/d/1d_49KW5C_vSz8Bs50v-cxyIJuTNJMwMrh7ypcxRHgZI/edit#) and add link. 

------
- [x] Schedule meeting
- [ ] Optional: Schedule debrief
- [x] Meet and take notes
- [ ] Optional: Debrief with DTS team members
- [x] Create resulting issues

**Comment by dianamartin** [comment]
# Diana's Notes

Signal Dashboard Discussion 4/21

PHB Evaluations
- Sent the date to Renee already
- Remove and archive data

Signal Evaluations
- were updated to match the list
- Signal Requests - to keep until Renee is done reviewing 
- Once she's populated everything in studies
- Remove Signal and PHB Studies and archive data

Signal and PHB Requests
- Signal Requests (CSR and Staff requests)
- PHB requests (anything older than 2 yrs old we can archive) 
Change status to ARCHIVE - How long do we keep something? 5 yrs, 10 yrs
"Archive" tab

Study Locations tab
- 95% have the requests - still using Signal Requests
(Create locations, new location/search location)
Study Locations>M: studies over time

More about "Funding Status"

studied in 2018- no funding - recommended
studied in 2020 - funding
 
Requests v. Studies
PHB side: like the idea detaching the study from the request, not request based process anymore
Requests at location can be given a point of 2
Signals side: Request based process at this point
  - observations
 
PHB Study Location 
- Looking at data Jaime puts together
- New study location and new study: Jollyville & Hamilton

Old Evaluation Score - ranked 

 "Not Studied" status
N. Lamar, meets criteria, not studied
