### ISSUE TITLE
Dispatch Tracking Go Live Task

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#5944]
- [x] Set cut off for entering test records into Knack application 
- [x] Delete test records from Knack
- [x] Establish start time for entering into Knack
- [ ] Disable SharePoint
- [x] Will there be any In Progress/unfinished SR's in SharePoint that need to be entered into Knack?

**Comment by dianamartin** [comment]
- [x] Stephanie communicated to stakeholders to stop using Parking Enterprise Portal to enter SRs into until Monday morning
- I finalized the last bit of changes the stakeholders requested before Go - Live
- Configuring "Inspection" reporting by Officer
- Had to test in old builder environment, testing auto-populating of "Assigned To" on the activity form for (Inspections, Citations, Warnings) so that the reporting pages will work

**Comment by dianamartin** [comment]
Shavyvonne messaged this morning 5/3
>Can we start using the new KNACK Parking Enterprise Portal this morning or do I need to wait until you reach out for us to go LIVE?

I said
>Let me check and delete the records real quick. It shouldn't be a problem for Hilary to start using it, I'm just deleting stuff that was old. She'll see the Service Request dashboard cleaned up when it's all done. 

Shavyvonne
>Good deal, I'll let her know. Thanks Diana!

**Comment by dianamartin** [comment]
## DELETING TEST RECORDS
Deleted 1012 records -`csr_issues`
1 was from today

Deleted 3012 (3016 total) - `csr_activities`
4 from today

**Comment by dianamartin** [comment]
Creating new issue for SharePoint document migration task, that is the only task left from this issue.
