### ISSUE TITLE
Fiber Optic Cable GIS Data Mgmt

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#5984]
- [x] Merge all Kimley Horn lines into one layer
- [x] Merge lines based on area and aerial/underground status
- [x] Got a copy of AGOL fiber optic cable from Edgardo that Brian/Edgardo had modified. Added those changes to my copy of the AGOL fiber optic cable layer
- [x] Create new Project, copy updated AGOL layer and Kimley Horn CAD drawings merged layer to Project for AMD

12/16/21: Changed how we are going to work on this as some of the CAD drawings are 20+ years old, and may be out of date. AMD will work on getting a current fiber optic cable GIS layer created by using the 2 layers that I sent to them mentioned above.

**Comment by jaime-mckeown** [comment]
Reassigning Epic to Andrew for any future work to be done regarding the Fiber Optic Data.

**Comment by amenity** [comment]
@andrewshensky @dianamartin let's convert this to a project/product index and close it. 

@maccallump - do you have an issue for the work you're doing with fiber optic cable now?

**Comment by amenity** [comment]
@amenity - set up a meeting w/ Diana and Geo-ers to figure out a doable Geo dev ops process

**Comment by andrewshensky** [comment]
@ChristinaTremel I think this one fizzled out even prior to Jaime leaving. I am supportive of closing this issue and will do so now
