### ISSUE TITLE
Add DSDD assets to MMC activities

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#6054]
John was testing MMC Activities form and noticed that the DSDD asset wasn't configured on there.

I checked and it sure wasn't there, so will be adding it.

**Comment by dianamartin** [comment]
- Testing `TEST | AMD - 17 MAR 2021 | AMD Data Tracker DOS` environment what needs to be changed before changing it
-

**Comment by dianamartin** [comment]
## IN TEST
1. On `tmc_issues` object
- Add connection `dsdd`
- Add connection `locations_dsdd`
- On `ASSET_TYPE` `field - `Dynamic Speed Display Device (DSDD)`

2. Under MMC Details page
- `Assign Asset` section
- On the form: 
  - add `dsdd` field
  - rename `Dynamic Speed Display Device (DSDD)`
  - add page rule #8
ASSET TYPE is `Dynamic Speed Display Device (DSDD)`

**Comment by dianamartin** [comment]
## John's suggestions
pretty similar to the way you set the location name for DSDD work orders.  `tmc_issues` has a field called `ISSUE_LOCATION_NAME` [(link)](https://builder.knack.com/atd/amd/schema/list/objects/object_83/fields/field_1963/settings) that is either the `LOCATION_NAME` from the asset `location` connection, or it’s the `CSR_ADDRESS` short text that comes in from 311.

Diana 
ahh, maybe that's the field I needed to be using "Issue Location Name" and I didn't know what it was..

John
yes. on the “Assign Asset” form, I think you want a rule that sets the `ISSUE_LOCATION_NAME` to the “Current Location”  field on the dsdd. i don’t think you need the connection to `dsdd_locations`

Diana
okay. I don't need the `dsdd_location` connection for either the `tmc_issues` or `tmc_activities`?

John
i don’t think so. just use `dsdd > Current Location` like you’re doing on the [DSDD work order form](https://builder.knack.com/atd/amd/pages/scene_1211/views/view_2956/form/rules/record)

**Comment by dianamartin** [comment]
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/aca6c516-ecf6-4351-9036-390357b66eb1)

**Comment by dianamartin** [comment]
6/1/21
Testing in TEST Environment
- Created new MMC Issue
- `Asset Type` form - taking forever to load
- Have to manually refresh page
- When page is refreshed, New "Identify Activity" has been added to details

**Comment by dianamartin** [comment]
Also configured "Assign Asset (API)" form
- [x] added `dsdd` field
- [x] added Display Rules
- ASSET TYPE does not contain DSDD - Hide `dsdd`
- [x] added Record Rules
- When `dsdd` is not blank - ISSUE LOCATION NAME to a connected dsdd> Current Location
- MODIFIED DATE - Current Date
- MODIFIED BY - logged in account

**Comment by dianamartin** [comment]
Messaged MMC Leads (Allyson/Lance)
>Hey, we had made it so that in the Data Tracker Max S. who manages DSDD's can put in an AMD Signal Work Order for Billy's team. I just configured the MMC Actvities form to also allow the MMC to identify DSDD assets and create SRs or WO. Please let me know if there are any issues with it.

**Comment by dianamartin** [comment]
Lance confirmed
>just tested, and I see them! thanks!

I said
>Thanks for testing

Lance
>not sure if we know what all to do with them yet, but functionality seems to work!

I replied
>We think you probably won't use it as heavily as the other asset types. I guess in the instance if someone calls in an says one is broken, then you have that option to designate the asset that a technician should visit
