### ISSUE TITLE
Projects page 2.0 | Update columns displayed in table and available as filters

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#6063]
- [x] Remove "Project Description" column from view (should still be able to tap this field for search)
- [x] [Add "Team" column](https://github.com/cityofaustin/atd-data-tech/issues/5517)
- [x] [Add "Phase" column](https://github.com/cityofaustin/atd-data-tech/issues/4331) 
- [ ] Add "Team" and "Phase" filters to the advanced search (this will take care of part of #5775)
