### ISSUE TITLE
Enable bulk work order entry in Data Tracker

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#6121]
> What application are you using?

Data Tracker

> Describe the problem.

Looking for a method to create number workorders by importing data from a spreadsheet. 
We currently have 40+ Workorder that need to be created to issue material to a contractor. 

> Describe the outcome you'd like to see when this feature is implemented.

Ability to fill out field in an excel spreadsheet that can be imported into the Data Tracker to automatically create Work tickets and inventory requests.

> Describe any workarounds you currently have in place or alternative solutions you've considered.

Manually entering Work tickets

> Is there anything else we should know?

Need to issue 40 work tickets in the next week and would like to know if an import is a nearterm solution or if these 40 work tickets need to be manually created. 

> Requested By
Brian C.

Request ID: DTS21-102045

**Comment by amenity** [comment]
@johnclary @dianamartin — is this doable? If so, do you have a template he should follow?

**Comment by dianamartin** [comment]
I talked to Brian, he sent an email and gave us a heads up on this. He can do an import request, we'd have to give him a template to fill out if we can't create a copy work order function.

**Comment by amenity** [comment]
@dianamartin - thanks; did he tell you when he needs it?

**Comment by dianamartin** [comment]
He seemed to want to issue these work orders to EARTC somewhere in the near future I believe. I don't remember an exact timeframe.

**Comment by dianamartin** [comment]
- Asked Brian what work order to use as template `WRK21-115190`
- Opened New Work Order (Non-technician) form in TEST
- Compared to `WRK21-115190` back end record
- Documented what fields were needed on the New Work Order (Non-technician) form
- Exported the `WRK21-115190` from PROD to get field headings
- Will created some fake work orders and do import test in TEST environment

**Comment by dianamartin** [comment]
- [x] Added `Installation – Battery Backup System` to "WORK_TYPE_SCHEDULED_WORK" on `work_order_signals` object

**Comment by dianamartin** [comment]
Email Brian tomorrow
- re-export task order list from PROD
- email new instructions
>email address instead of name, signal ID instead of long name, task order ID # or code instead of that display name

**Comment by dianamartin** [comment]
Brian emailed back the template already before I was able to re-write template instructions
- I'll reformat the template before attempting to import in TEST

**Comment by dianamartin** [comment]
- Imported the spreadsheet into TEST, realized that the ATD_LOCATION_ID is critical for bringing in the Location Name without it those fields were blank
- Could just re-save the work order and then it would work
- I personally added the ATD_LOCATION_ID field to the spreadsheet and it all populated properly
- Signal ID - should be the ID only and not the display name (like John said), I ran into 3 records not populating due to 1 less space in the display name
- After work orders imported in TEST, added the 2 inventory items needed and exported it out
- Updated inventory items import spreadsheet
- imported inventory items spreadsheet for 4 work orders, only 1 had a duplicate (4 records)

Ready to import in Production!

**Comment by dianamartin** [comment]
# PRODUCTION
- [X] Added `Installation – Battery Backup System` choice to `WORK_TYPE_SCHEDULED_WORK` field, `work_order_signals` object
- [x] Imported 27 records
- [x] Exported 27 records that have new ATD WORK ORDER ID field
- [ ] Create inventory item spreadsheet for import
- [ ] import inventory item spreadsheet linked to the work orders entered

**Comment by dianamartin** [comment]
Send a second email 5/27, because I made some small changes. 
>I updated your work order “WRK21-115190”, the scheduled work was “Installation – Other” and I had added the new choice “Installation – Battery Backup System”. I checked the Inventory Request page was part of your screen shots. Does the FDU information look alright? Work orders look okay too?

**Comment by dianamartin** [comment]
Haven't heard from user, closing issue. Will reopen if any issues arise from this.
