### ISSUE TITLE
Update Reports for Dispatch Tracking

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#6170]
- [x] Discuss with Shavyvonne the number of reports they requested be expanded - it's a lot
- [x] Update reports based on the feedback we received from the leadership

![image](https://user-images.githubusercontent.com/56606465/119368420-9eb9b480-bc78-11eb-906a-44bd05319e5c.png)

**Comment by dianamartin** [comment]
# Diana's Notes
Meeting with stakeholders 5/27
- Met with Parking Enforcement stakeholders to discuss their spreadsheet they submitted to us
- Clarified what reports were needed/not needed, which to expand/not expand
- Convert activity type `Towed - ATD` to `# of Tows` 

## Report Changes
### Call Log Reports
| REPORT NAME | ACTION |
| -- | -- |
| Daily Call Count (Current Week) - BAR CHART | No Changes |
| Calls by Status (Current Month) - PIVOT TABLE | No Changes |
| By Source (Current Month) - PIE CHART | No Changes |
| Current Month (By Issue Type) - PIVOT TABLE | No Changes |
| Number of Citations & Warnings (Current Month) - PIVOT TABLE | Add "Towed - ATD" to this report and enable Expanded Table view. Use field headings from "By Issue Type" table? |

**Comment by dianamartin** [comment]
Configure `csr_activity` Object Table
- [x] Added new field `Number of Tows` - multiple choice (up to 20), required
- [x] Added new field `Num of Tows` - number
Configure SR Details - Activity Form
- [x] Add 'Number of Tows` field to form
- [x] Update Display Rules

**Comment by moorerst** [comment]
@dianamartin all the report modifications and the new # of tows field look great. They all work as documented.

**Comment by dianamartin** [comment]
Stephanie has reviewed and we'll close it and show stakeholders at our next Sprint Review.
