### ISSUE TITLE
Design refinements to Summary tab

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#6232]
- [x] Make "Description" full-width
- [x] Remove drop shadow on Data Table
- [x] Tighten vertical spacing; maybe remove all the `margin-bottom: 16px` on Data Table rows?
- [x] Change "eCapris subproject ID" to "eCAPRIS subproject ID"

![summary](https://user-images.githubusercontent.com/1463708/119774962-8e782400-be88-11eb-8032-aa8a935e2068.png)
