### ISSUE TITLE
Implement v1 reporting functionality

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-data-tech#625]

**Comment by SurbhiBakshi** [comment]
individual performance

**Comment by SurbhiBakshi** [comment]
As per LLweis
- [ ] If there could be a way to add up number of citations written per shift (based on individual citation #, not violations), that’d be great.  We’d like to aggregate that and come up with an overall average
- [ ] Will we be able to quickly determine how many individual shifts were filled per month?  (For example, there are two teams of two officers for two periods of the day, so 8 ‘shifts’ are available.)
- [ ] I know Randy would like to have a total number of hours worked per officer easily available to him for billing purposes.  We’d like to use that with the citations written number to see a ratio of citations per hour.

**Comment by amenity** [comment]
https://docs.google.com/presentation/d/16A8vnQZa8AAjV3mz4DW0oZocnZVWwtfks7joFi_4Ank/edit#slide=id.g65129eec4b_0_9 Prioritized here

**Comment by SurbhiBakshi** [comment]
Issues with Reports

**Comment by amenity** [comment]
@SurbhiBakshi Reports are looking beautiful! Moving this into the backlog.
