### ISSUE TITLE
Onboard Patrick M. 👋✨ 😊

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#6273]
## Accounts - Amenity

- [x] Submit a [CTM New Employee Request Form](https://atx.service-now.com/sp?id=sc_cat_item_guide&sys_id=b714eb12db7a3f0021ccef92ca961972&sysparm_category=ea848d3adbce37405b03f482ba96193c) for a COA network account, eAccess PIN/HR Portal, and phone 
- [x] Submit a CTM service request to add to DTS Distribution Email Group — also add Janet:
  > Add "First Last Name" to email distribution list "ATD Data and Technology Service" \([ATDDataTechnologyServices@austintexas.gov](mailto:ATDDataTechnologyServices@austintexas.gov)\) and "ACE ATD DL"
- [x] Add to City of Austin Slack - `austininnovation.slack.com`_- need to switch to City email_
- [x] Add to DTS Google Drive _- need to switch to City email_
- [x] Have them sign up for [Gitbook](https://app.gitbook.com/@atd-dts/s/dts-service-desk-knowledge-base/onboarding/general#gitbook-wiki) 
- [x] Add to [Austin Transportation Github Team](https://github.com/orgs/cityofaustin/teams/transportation/members) 
- [x] Add to [DTS Team Slide](https://docs.google.com/presentation/d/1tHKTfUgQ-uAXdRBkEdXqR7ryBo_LTU86IzQxo1gJoeA/edit#slide=id.gc64f254bde_0_91)
- [x] Add to 1Password

## Hardware — DTS Systems Admin
Coordinate with DTS System Admin \(Scott\), make sure there is enough lead time for equipment to be acquired.
- [x]  Laptop
- [x]  Monitors
- [x]  Chair - check availability, _ask John to ask Peggy how we're handling this_?
- [x]  Power supply
- [x]  Keyboard
- [x]  Mouse
- [x]  Docking station

## Calendar invites 
- [ ] Monthly Team Meeting — John
- [x] Sprints — Amenity
- [x] Sprint Ceremonies — Apps/Dev: Amenity; Geo: John 
- [x] 1:1 — Supervisor
- [x] First day: DTS Team Orientation — John
- [x] First Week: DTS Product Ops — Amenity
