### ISSUE TITLE
Inactivate Brandon B. from Data Tracker

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#6274]
### I am in Data collection thru Arterial Management. My former co-worker no longer works in our group so need to get his name taken off, Brandon Burgess.

**Customer:** Jamie

**Comment by dianamartin** [comment]
- [ ] Change the "Assigned To" drop down
- [ ] Update Account Management, make Brandon B. - Inactive

**Comment by dianamartin** [comment]
### BB - Unscheduled - 19
- [x] switched to Jamie A. - 19

### BB - Scheduled - 19
- [x] switched to Jamie A. - 19

### BB - Rescheduled - 5
- [x] switched to Jamie A. - 5

**Comment by dianamartin** [comment]
- Filtered `traffic_counts` records 
- Status is not COMPLETED or CANCELLED to check the records

Messaged Jamie
>In the system, I made Brandon "Inactive", I switched the work tasks that has Brandon assigned that weren't already "Completed" or "Cancelled". There are few in the system that are "Installed" that have Brandon tagged. 

>- Unscheduled - 19
>- Scheduled - 19
>- Rescheduled - 5

>I switched all these to your name. I opted not to remove his name under "Assigned To" just yet, bc if you have to filter any records with his name you won't be able to if it's removed.

**Comment by dianamartin** [comment]
Jamie replied
>Diana, Thanks again and I am in the process of doing the other request right now.
