### ISSUE TITLE
Update Journal Voucher fields in AMD Data Tracker

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#6280]
- [ ] Import spreadsheet information to capture Journal Voucher Dates and Numbers
- see [spreadsheet](https://app.zenhub.com/files/140626918/b39ed7cf-1cb0-4a3d-9f95-2e5e80f61f75/download)

### Steps
- [x] remove all columns from the spreadsheet except `TXN ID`, `Journal Voucher Date`, and `Journal Voucher ID`
- [x] import the file into the `inventory_transactions` object. match on `TXN ID` and map the other columns
- [x] the JV status field will update automatically from a field* rule
- [x] confirm that the JV status field is updated

**Comment by dianamartin** [comment]
1403 JV blank

**Comment by dianamartin** [comment]
Emailed Van back
>I’ve update the transaction records with the related JV Date/Numbers. Total 60 records updated. Filter for “JVDA 21052400036” on Completed Inventory Transaction Report.
