### ISSUE TITLE
Update AMD Work Orders - Close and Move Workgroups

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#6281]
Billy B. 
AMD

Assigned Folder:
Please move these to non-technician

- [x] Wil L. - 37 - `there were 36 when I checked`
> I moved him to "Timing Engineers"
- [x] Fanta K. - 1
> Moved to "Timing Engineers"
- [x] Joshil B. - 30
> Moved to "Communciations"
- [x] Reza V. - 11 - `there were 10 when I checked`
>Moved to "Timing Engineers"

 
Please close these out of date work orders

- [x] Test Tech - 6
- [x] EARTC - 14

**Comment by dianamartin** [comment]
6/2: 
- [x] Closed 6 Test Technician records
- [x] Closed 14 EARTC records

**Comment by dianamartin** [comment]
Emailed Billy back
>I’ve updated the work orders you requested modifications for. Included screen shot.
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/da1b3cb6-bbda-4cba-840d-24855695715f)
