### ISSUE TITLE
New Features - HR App - On-Boarding Forms

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#6309]
**Customer:** Nathan B w/ HR

> What application are you using?

Other / Not Sure

> Describe the problem.

We are looking at adding additional forms to the HR Knack system for our new on-boarding process that we are rolling out this summer.  I have spoken with Diana and we will be scheduling a meeting with her to discuss, but she asked to have a ticket put in the system.  

> How soon do you need this?

Flexible  — An extended timeline is OK

> Is there anything else we should know?

July timeline.  

> Requested By
Nathan B.

Request ID: DTS21-102150

**Comment by dianamartin** [comment]
Nathan has scheduled a meeting for 6/15 to discuss this. Will forward Stephanie the meeting invite.

**Comment by dianamartin** [comment]
Linda emailed the ATD HR forms that they're looking to digitize into Knack forms. 

- 30 day Supervisor Survey Request for Employee SSPR
- 90 day Supervisor Survey Request for Employee SSPR
- 120 day Supervisor Survey Request for Employee SSPR
- Employee 30 Day Feedback

forwarded email to Stephanie

**Comment by dianamartin** [comment]
@moorerst I was going to use this issue to start configuring the HR onboarding forms

# To Do
- create 2 new object tables for the new forms 
  - [ ] Supervisor Survey Request for Employee SSPR
    -  30 day 
    -  90 day
    -  120 day
  - [ ] Employee 30 Day Feedback
- [ ] create form pages
- [ ] configure forms, display rules, record rules
- [ ] test process
- [ ] configure the table pages for HR Admin and Supervisor/Employee
- [ ] test process

**Comment by dianamartin** [comment]
Learned more about HR/New Employee Process

New ATD Supervisory Training
All supervisors & managers going through training
- 3-4 Training for the first month

NEO Table: 


NERF First- 
BANNER purposes when they start - beginning of a pay period
Week 1, Thursday at noon

2 Week delay due to  payroll

submit forms to remove access
Banner termination

Scott- audits
List to managers that they have or haven't done this
Fill out the forms, city property
Letter to employee

**Comment by johnclary** [comment]
@dianamartin @moorerst please make sure relevant issues are captured in this epic.

**Comment by johnclary** [comment]
It looks like this complete minus the lingering backlog issue. Closing...
