### ISSUE TITLE
Update "Journal Voucher" info in AMD Data Tracker - Warehouse Inventory- May 2021

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#6450]
- [x] Spreadsheet emailed from Van month of: `4/19-5/31`
- [x] Number of records being updated: `78`
- [x] Format spreadsheet [(Review instructions)](https://atd-dts.gitbook.io/atd-knack-operations/warehouse-inventory-updating-journal-vouchers-jv-information)
- [x] Spot check Transaction IDs, no JV information before import - `10569`
- [x] Import records
- [x] Spot check Transaction IDs, no JV information after import - `10569`
- [x] Email Van that update task complete
>I’ve updated the Journal Voucher fields for the May transactions you sent over with a JV Date of 6/4/21, there should be 78 records. Let me know if these changes are all you need.

**Comment by dianamartin** [comment]
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/64fd754e-0a49-4a05-b16b-06e0fb1b3a3b)
