### ISSUE TITLE
Release Moped 0.7.0 and update Alpha users

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#6523]
- [x] @sergio make 0.7.0 release candidate branch and open [PR to deploy to Production](https://github.com/cityofaustin/atd-moped/pull/355)
- [x] @sergio [draft new release w/ release drafter and clean up notes](https://github.com/cityofaustin/atd-moped/releases/tag/v0.7.0)
- [x] @amenity recreate [Alpha user](https://docs.google.com/spreadsheets/d/1fXeQo6LGYMacOLOSE_mFs6OYKIr4ISbQefP-gh0NDn0/edit?resourcekey#gid=1139105757) accounts on Production 
- [x] @johnclary deploy release to Test
- [x] @janet @john @patrickm02L [do QA](https://docs.google.com/spreadsheets/d/1n_O6MLh9cwwPf57HUM394Ea-z9uuoEV1-QW4axNZXLE/edit#gid=1412386484), create issues as needed
- [x] @john & @patrickm02L decide if any issues need to be addressed as patches or if they can be backlogged for next release…
- [x] @patrickm02L / @john assign any patches needed to devs and repeat QA as needed
- [x] @john / @patrickm02L approve deploy-to-production PR & merge
- [ ] @janetchuhl  create new XD feedback mockups for 0.7.0 release - _can wait until next week_
- [x] @amenity  email Alpha users to let them know about release and invite them to log in and poke around; share 1) link to bug report SR and 2) URL for new XD - _can wait until next week_

**Comment by johnclary** [comment]
v0.7.0 has been released with [this PR](https://github.com/cityofaustin/atd-moped/pull/355). [Release notes](https://github.com/cityofaustin/atd-moped/releases/tag/v0.7.0).
