### ISSUE TITLE
Update "Journal Voucher" info in AMD Data Tracker - Warehouse Inventory- JUNE 2021

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#6551]
- [x] Spreadsheet emailed from Van month of: `4/28-6/21`
- [x] Number of records being updated: `110` 
- [x] Format spreadsheet [(Review instructions)](https://atd-dts.gitbook.io/atd-knack-operations/warehouse-inventory-updating-journal-vouchers-jv-information)
- [x] Spot check Transaction IDs, no JV information before import - `10343`
- [x] Import records
- [x] Spot check Transaction IDs, no JV information after import - `10343` and `10073`
- [x] Email Van that update task complete

**Comment by dianamartin** [comment]
Emailed user
>I’ve updated the attached 110 records with the JV information on them for June.
