### ISSUE TITLE
Parking Enterprise Portal - Dispatch Tracking Check-in & minor enhancement requests

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#6577]
During our Sprint Review with Parking Enforcement on 7/1, they mentioned a few things report configurations to change and one other small thing. 

# Change Requests
## Scooters Issues Responded by Officer
- [x] Removed the Current Month filter

## Completed Inspections By Officer
- [x] Removed the Current Week filter

## Attachments table
- [x] Changed `Created Date` field to include time

**Comment by dianamartin** [comment]
Updated the application with stakeholders in meeting, they were happy with the changes.
