### ISSUE TITLE
Go-Live Tasks for: TDS - TIA Module

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#6611]
### Planning/Prep
- [x] Meeting with stakeholders to talk about go-live, roll out plan to end users (**July 14th & 19th**)
- [x] Set Go-Live Date (**July 26th**)
- [x] Create workflows, status matrix #5487
- [ ] Create user help guides _(embed in application, GitBook pages/space, Google Doc)_ #6377, #5474, #5473
- [ ] Create help guide videos _(optional, time permitting)_
- [x] Provide user training (**July 22nd TDS Workshop**)

### Testing
- [x] Test all buttons (as each user role)
- [x] Check page permissions (sign in as each user role)
- [ ] User testing, user acceptance #3010 

### Clean-up/Finalize
- [x] Cleanup Reviewer roles
- [x] Delete all test records from everything (object tables)
- [x] Provide access to users for new modules/new user roles
- [x] Change out email addresses for email notifications (already set)
- [x] Remove any page rules that have pages hidden (no pages hidden)
- [x] Modify page log-in user roles for Go Live (login roles already setup)

### Application Banner - New Applications only
- [x] Create application banner

### After Go Live
- [x] Stakeholder/Power users available during Go-Live dates to make sure they are QA/QC for any issues coming from end users
- [x] Schedule app builder to be available during Go-Live day to be available in case of issues
- [x] Check in with stakeholders day of Go-Live and 1-2 days after Go-Live
- [x] Do #5133 (automated notification to Mike)

**Comment by ChrispinP** [comment]
Asked stakeholders to create a real TIA and non-TIA case in the system to use for the Training Workshop.

**Comment by TracyLinder** [comment]
![Screen Shot 2021-07-19 at 3.21.49 PM.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/25e23cbc-b9d0-453a-aeb6-682d52ed45ac)

**Comment by ChrispinP** [comment]
Test records are now removed and the app is ready for go-live.

**Comment by ChrispinP** [comment]
Checked in with stakeholders for followup issues. Issues #6776 and #6787 derived from Go Live. #5473 is available for help guides and #3010 available for any followup user testing.

No further action needed, application is now live.
