### ISSUE TITLE
[ROW & Data Tracker] TCP Migration Cleanup

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#6621]
Tentative date for cleanup, Sept 6th

**New ROW Portal**
- [x] Update TCP Reviewer field from tcp_project object
- [x] Remove Assigned To old field from tcp_project object
- [x] Remove Submitter Name old field from tcp_project object
- [x] Update Submission Reviewer field from tcp_submission object
- [x] Remove __tem__should_have_attachment field from tcp_submission object
- [x] Remove Submission Reviewer old field from tcp_submission object
- [x] Remove any test records from both objects

**Data Tracker**
- [x] Remove TCP Tracker records, both the tcp_tracking and tcp_tracking_submissions objects
- [x] Remove the Menu Button/Navigation
- [x] Remove the TCP Tracker pages
- [x] Inactivate users that no longer need access to Data Tracker

**Comment by ChrispinP** [comment]
ROW Portal cleanup complete, removal from Data Tracker pending

**Comment by ChrispinP** [comment]
Data Tracker cleanup almost complete, still need to cleanup users. Sent an email to confirm no TCP users still need access to Data Tracker.

**Comment by ChrispinP** [comment]
ROW/TCP users are now marked as inactive in the Data Tracker. Ryan & Darren left active for reporting & management purposes.

cleanup is now complete, closing
