### ISSUE TITLE
Meeting 10/21/19: TDSD Application Check-In

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#665]
### Objective 
Project team debrief on the implementation of the TDSD application that went live on 10/1. Identify any blockers to or resources needed for full user adoption. 

### Participants
Sangeeta Jain, Nathan Aubert, Joe Calabrese, Amber Mitchell, Diana Martin, Tracy Linder, Surbhi Bakshi

### Date/Time/Location
Oct 21, 2019 / 1:30-2:30pm / ATD Barton Oaks Rio Grande

### Agenda
* Is the application meeting the business needs? Why or why not?
* User Adoption:
    * How do you feel the users are doing in utilizing this tool to meet business needs? (Project Managers, Vision Team Reviewers)
    * Identify any blockers to user adoption and brainstorm solutions
* Training Needs:
    * If not already identified, discuss any training needs. How will these needs be met?
* Test Data: 
    * Has any test data been entered that needs to be deleted? 

------
- [x] Schedule meeting
- [ ] Meet
- [ ] Attach meeting notes to this issue
- [ ] Create resulting issues

**Comment by dianamartin** [comment]
### Meeting Notes
- folks aren't able to do the review (3 day auto complete)
- 2 weeks Vision Team members are testing
- [x] Change to 7 days. auto-complete status
- [x] Change language in "My Reviews" page (add helpful text)
- [x] Make `Area` field (required)
- [x] Delete 1 test comment - Number 14 (`review comment` object table)
- Suggested Development Assessment number - `TA-201910121`
- [x] Change language on Details page "Add Reviewer"
- [x] Add `Count of cycles` on Development Reviews - sort by Count of Cycles (cycles --> 0)
- [x] Update User guide
- [x] Add tab "Help" link to user guide

### Bugs
- [x] Need to check `Due Date` on My Reviews page
  - looks to be created date of cycle rather than auto-generated due date
 
### Future 
**Development Assessments**: meeting with developer before it formalizing into an official Development Review. 
- Tracking Purpose: Need to track development that won't start for another 3 years. Criteria introductions, documenting criteria and notes and plans of the developer. Seeing what is possible, reviewer says "not possible" or "possible".

**Comment by SurbhiBakshi** [comment]
Date - October 21st, 2019
Attendees - SJ, AM, TL, DM, SB, JC

###  Meeting notes - 
### To- Do 
- [ ]  three day rule not working
 - [ ] sent an automated email to bring to reviewer's attentions when he/she hasn't completed a review in 5 days, concern there might be too many emails sent out. 
- [ ] add text to previously reviewed that explains it more
- [ ]  make area field north, south, central a mandatory field
- [ ] test data needs to be deleted - SJ has created one record

### Training and Help Guide 
- [ ] Training needs to be done to ensure app is used as intended. SJ will set up training in 2 weeks. 
- [ ]  Help Guide needs to be shared with staff, after comments from TL are addressed. 


### Comment and Review Time 
- no response received status 
- subd  3 days, site plans 7 days, not sure if calendar or business days, app is calendar days
- make it 7/ 10 days or 8 (7 + 1) . What if case is assigned in the evening at 5 pm versus 8 am in the morning? consensus is 7 calendar days, but could lean on division manager to make reviewer responsive.don't make process too lenient to begin with. This would be communication tool when reviewers move to Highland. First day is Day 1.
- SJ - How to reassign a case if it hasn't been reviewed in 5 days.




 
### Possible New Features - Transportation Assessment (secondary purpose)
- Row ID , does it have any validation rules?  could be used for pre assessment reviews. TL - more things will go wrong if the app is used for unintended purposes. DM suggested a suffix to seperate/
-  TL suggests that this sounds like a sprint's work for app to accommodate the DA needs.
- use TA-yyyymmdd for Transportation Assessment to pull up DA's over last year, which helps with budgeting and forecasting for next fiscal year. 
- Development Assessment (pre formal submittal meetings, that could lead to documentation that should be used to guide review process if needed) could be a way to to make the vision team aware of the meetings/ results that happened before the case is submitted for review.
- As per CK, lots of planning issues need to be brought into the conversation, that don't always find the right place/ right time.

### Miscellaneous 
- need to track who is responsive and who isn't
- add a new reviewer with the same review cycle number
- council districts were filled out - DM, appreciation from SJ.
- Comments and Attachment fields only show up if there is content in the records. 
- SJ asked for archives to see old closed cases, DM spoke about status change affecting visibility, and filtering by predetermined status and location.

**Comment by TracyLinder** [comment]
### What is blocking full user adoption, or would make adoption easier?

**Most vision team members are not able to complete their reviews**
    * Sangeeta: They don't see where to add their reviews is what they tell her. 
    * Reviews past the review deadline do not allow reviewers to provide a comment

**The 3 day review deadline is not working…. So what will work?**
    * Sangeeta: 10 days
    * Sangeeta: Can we get an automated email reminder, on the 5th day before the review is due?
        * Joe: Then they'll get so many emails that they'll begin ignoring them all. 

**The ability to "reactivate" a review after it has closed.**
    * Tracy doesn't like the idea of updating the status for the closed review, because you lose your ability to track non-responsive reviewers. 
    * Idea: Add another review with the same cycle #. (Accepted)
    * Sangeeta: That's too much, if they can't get it done in 10 days, they should just lose the opportunity. 
    * Joe: It's easy to make it more lenient, it's hard to pull it back in. Should start w/ 7 days and change it to 10 if needed.
    * **Everyone: Agree - 7 days is better.**

**Training:**
    * No group training performed yet. 
    * Joe: Let's have a user kickoff event, w/ training incorporated, so they can reinforce the entire dev review process. 
        * Users: Currently 23 members
    * Sangeeta will coordinate the training & invite DTS
	
**Test Data:**
    * Sangeeta thinks she's created only 1. Diana found it & deleted it. 
	
**Development Assessment Needs:**
    * How to use the app to inform the team of upcoming developments that the PM's are involved in?
    * How to use the app so PM's can record meeting with developers where they provided feedback on a possible development that has not been submitted for review yet?
    * ROW ID: There isn't a ROW ID for these, but it may convert into a review at some time in the future. 
        * Everyone: Follow a naming convention for the ROWID field so we can filter & find them easily. TA-YYYYMMDD
    * Sangeeta: She invites Vision Team members who need to be involved to the DA meetings. 
    * Tracy: Asked staff to Band-Aid the current app until we can have a full discovery on the DA needs.
	
### Tasks:

- [ ] (Diana) On the 'My Reviews' page, add text under the 'Previously Reviewed' section to explain that the items there cannot be edited…. Read only. 
- [ ] (Diana) The review due dates still may not be calculating based on the correct information
- [ ] (Diana) Make the "area" field mandatory
- [ ] (Diana) Finalize the user guide & send it out
    * Joe wants to see it too. 
- [ ] (Diana) Add a link to the user guide in the app, wherever it makes the most sense
- [ ] (Diana) On the Development Review Details page, rename the button +Add Review Comment to  +Add Reviewer 
    * Move the button to above the Reviewer Comments table
    * Update the user guide
- [ ] (Diana) On Development Reviews page, update the sorting order of the open cases. The logic is in Diana's head. 
- [ ] (Tracy) Add an issue for TDSD Phase 2, and add an item for Development Assessment needs
- [ ] (Sangeeta) Schedule training

**Comment by TracyLinder** [comment]
@dianamartin & @SurbhiBakshi - I think I captured all of the tasks identified in our notes and put the full list in this issue's description.
