### ISSUE TITLE
TED Speed Limit Change Tracking Data/Map Updates

### ISSUE THREAD

**Issue by andrewshensky** [cityofaustin/atd-data-tech#6688]
Make changes/updates to Speed Limit Change Work Orders App to meet needs of Transportation Engineering group.

**Comment by andrewshensky** [comment]
- [ ]     Modify current Desktop Web Map / App
- [ ]     Remove edit ability on the proposed speed limit field in the Layer View
- [ ]     Add final speed limit field (Max will be editing this field after Work Orders are complete)
- [ ]     Add Signs Work Orders feature layer to the map for Area Engineer Teams to use to see what work orders have been submitted (filter by Requester: transportation engineering)
- [ ]     Add transportation engineering areas feature layer to the map

**Comment by andrewshensky** [comment]
7/16 - Met with Transportation Engineering. Happy with updates. Additional changes below:

- [ ] Final speed limit to include domains 25-50mph at 5 mph increments
- [ ] Final speed limit editability only in existing speed limits layer
- [ ] Figure out good symbology to show features with Final Speed limit populated
- [ ] Remove Filter widget and add all filters (TED, Closed, Speed Limit) directly into Sign Work Order layer on load.
