### ISSUE TITLE
Update "Journal Voucher" info in AMD Data Tracker - Warehouse Inventory- July 2021

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#6896]
Reference old issue #6551

- [X] [Spreadsheet]([https://app.zenhub.com/files/140626918/ee7435a0-536e-4283-ab74-ddfe9570502c/download](https://app.zenhub.com/files/140626918/ee7435a0-536e-4283-ab74-ddfe9570502c/download)) emailed from Van month of: 06/04/2021 - 07/19/2021 (JV Date 07/28/2021)
- [x] Number of records being updated: 94
- [x] Format spreadsheet [(Review instructions)](https://atd-dts.gitbook.io/atd-knack-operations/warehouse-inventory-updating-journal-vouchers-jv-information)
- [x] Spot check Transaction IDs, no JV information before import
- [x] Import records
- [x] Spot check Transaction IDs, no JV information after import 11450 & 11460
- [x] Email Van that update task complete

**Comment by ChrispinP** [comment]
Sent email to Van & Diana, complete
