### ISSUE TITLE
I would like to be able to sort studies (Study Locations) by various columns 

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#6944]
> What application are you using?

Data Tracker

> Describe the problem.

I would like to be able to sort studies by various columns including:
- `Study Status` _- field already available_
  - **Cannot be sorted** 
- `Study Assigned To` _- field already available_
  - **Cannot be sorted** 
- Council District _- field already available_
   - Field can be sorted
- `Data Collected` _- field already available_
  - **Cannot be sorted** 
- `Type` _- field already available_ 
  - **Cannot be sorted** 
- Ranking for Construction _- field already available_
  - Field can be sorted
- Ranking Level _- field already available_
   - Field can be sorted

Here is the page:  https://atd.knack.com/amd#study-locations/ 

> Describe the outcome you'd like to see when this feature is implemented.

See above

> Describe any workarounds you currently have in place or alternative solutions you've considered.

I could export the data to excel and sort there

> Requested By
Renee O.

Request ID: DTS21-102535

**Comment by dianamartin** [comment]
User said that they realized that most of the items are already available and only a few items are new, but apologized for not checking before entering in a request.

**Comment by dianamartin** [comment]
Checked the page and determined that some fields can't be sorted because they're being brought in from another table
- `Study Status` _- field already available_
  - **Cannot be sorted** 
- `Study Assigned To` _- field already available_
  - **Cannot be sorted** 
- `Data Collected` _- field already available_
  - **Cannot be sorted** 
- `Type` _- field already available_
  - **Cannot be sorted**

**Comment by johnclary** [comment]
@dianamartin you'll need to make renee a studies view. The primary table will be studies and you can add columns from the  study_locations as needed.

**Comment by dianamartin** [comment]
Created new page on menu button under Study Locations, called `Studies export`
- Table will be created from the `studies` object so that Renee can export and sort based on those fields
- Added all field from "Study Locations" table, these fields are sortable
- There were `15` records that seemed orphaned, definitely `2` that should be deleted
- Will email Renee tomorrow

**Comment by dianamartin** [comment]
Emailed Renee 8/25
>I was able to create a new page on the “Study Locations” page. It’s called “Studies” that has the columns you’ve been looking for that can be sorted. 

![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/b5cdfcae-7721-47ee-bca5-4252372abfd2)

**Comment by dianamartin** [comment]
Sync'd with Renee 8/31
- [ ] Add export function on the "Studies" table
- [ ] Add ability to edit from that "Studies" table
- [ ] Remove "Delete" button on "Studies" table
- [ ] Add edit ability on the Study Information table in Study location details page

**Comment by dianamartin** [comment]
Messaged user
>Hi Renee, I was able to add: 
 - DONE - Add export function on the "Studies" table
- IN PROGRESS - Add ability to edit from that "Studies" table (<--- THIS ONE IS BEING BUGGY, There's a Bug request for Knack on it.)
- DONE - Remove "Delete" button on "Studies" table
- DONE - Add edit ability on the Study Information table in Study location details page

**Comment by dianamartin** [comment]
Updated "Studies' table to have "in-line editing"
- [x] Type
