### ISSUE TITLE
Under "Work Orders - Technicians" "Advanced Search", there is a "Created Date" search term. Add Date Range fields.

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#6949]
> What application are you using?

Data Tracker

> Describe the problem.

Under "Work Orders - Technicians" "Advanced Search", there is a "Created Date" search term. Unfortunately, it only allows the selection of one type of data and not a range of dates (created between ____ and ____.) Please add this criteria.

We also need a field that allows us to see if a follow up work order was created when it is submitted by the technician. This would be a separate search term under "Work Order Status".

> Describe the outcome you'd like to see when this feature is implemented.

With these changes, ATD will be able to determine the number of completed work tickets dealing with detection.

> Describe any workarounds you currently have in place or alternative solutions you've considered.

An alternative solution would be to have the entire Work Order database dumped into Excel and manipulate it manually.

> Is there anything else we should know?

Jen wants to include this in this month's maintenance report, so turnaround would be very quick.

> Requested By
Brian V.

[Attachment](https://api.knack.com/v1/applications/595d00ebd315cc4cb98daff4/download/asset/611a932fe49fa50020f03c9f/datatrackderjpg.jpg) (55.34kb)

Request ID: DTS21-102545

**Comment by dianamartin** [comment]
Reviewed the page, only "Created Date" was there. 
- [x] Added another "Created Date" field
- [x] Renamed "Created Date" to "Created Date/From Date" with helpful description `If searching for a date range, enter "is after" and [date].`
- [x] Renamed "Created Date" to "Created Date/To Date" with helpful description `If searching for a date range. Enter "is before" and [date].`

**Comment by dianamartin** [comment]
User replied
>- This gets me part of the way there. I need to determine if the signal tech indicated that a follow up is needed when he submitted the work order.
- Can we also add a date range to the “Updated” field. (Same as for the Created Date / From Date and Created Date / To Date. It wasn’t in the original work request, but I’m finding that it would help in my data search. Do you want me to update the work request and re-submit?

I replied
>I can add the “Follow-up” field to the search and add the Update Date on the search criteria. I’ll let you know when that is done, no need to turn in another request. I’ll just add it to the existing one.

**Comment by dianamartin** [comment]
- [x] Added `FOLLOW_UP_NEEDED` field
- [x] Added another `Modified Date` field, renamed to "Updated (To Date)"
- [x] Renamed to "Update" field to "Updated (From Date)"

**Comment by dianamartin** [comment]
Messaged user
>Hey, I'm following up on the enhancement I made for the Advanced Search for the "Work Order - Technician" page. Is that working for you? I'd like to close the issue I have open for it.

**Comment by dianamartin** [comment]
Brian came by and talked to me more about the Advanced Search page, he said he isn't able to query based on some of the fields he has available. He turned in a new request to add those. Closing.
