### ISSUE TITLE
Prepare TIA Historical Data for Mitigation Tracking Solution

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#6964]
### Scope
- [x]  Scrub & join data
- [x] Import historic TIA Cases
- [x] Update Geo Records (removed from this epic; #8727) 
- [x] Import historic TIA Mitigation Data

**Comment by amenity** [comment]
@dianamartin and @ChrispinP met with Joann and learned that they may not have time to do the legwork to import this data. They need to get the okay from Curtis. Waiting for confirmation on that. We let them know that if they're not able to help Chrispin with the data clean-up, he will have to take time away from his other TDS work to handle it.

**Comment by ChrispinP** [comment]
Updated and Added Import Issues to Epic

**Comment by ChrispinP** [comment]
@dianamartin I'm okay closing this since its not reliant on the geo records being updated and users now have the power to view and edit historical mitigation data including locations.

**Comment by dianamartin** [comment]
@ChrispinP you still have this open though.. [[TDS-TIA] Data Research: Updating Intersections & Street Segments with CTN/CTM data] #8727
