### ISSUE TITLE
Stop Archiving Flex Notes from Data Tracker

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#700]
We archive flex notes for SR flex notes in the data tracker in our postgrest db. We do this because they create a lot of space in our knack apps, so we delete them periodically from the Knack app and back them up in postgres. This data is always retained in the CSR system, so this is a redundancy.  

However, we have never in the past year needed to retrieve this data. Let's kill this process. 

It's all described here: https://github.com/cityofaustin/atd-knack-data-tracker/wiki/CSR-%7C-Flex-Note-Archiving

TODO:
- [ ] update atd-data-deploy scripts to remove this job
- [ ] deprecate script from atd-data-publishing
- [ ] update wiki
- [ ] update AMD on this change

**Comment by amenity** [comment]
@johnclary - should we stick this in the backlog or assign to Sprint 12?

**Comment by amenity** [comment]
@johnclary - Sprint 13?

**Comment by amenity** [comment]
@johnclary - Sprint 14?

**Comment by amenity** [comment]
@johnclary Can you update the estimate, pipeline, and milestone on this, please?

**Comment by johnclary** [comment]
edit this was done here: https://github.com/cityofaustin/atd-data-deploy/commit/7a03b2db5d85890bef1aaab62ce201d4e1d2b209
