### ISSUE TITLE
Ability to link signal work orders to projects

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#7016]
As part of #6854—staff would like to be able to tag/link work orders to specific projects. This work may entail:

- [x] Adding a connection between work orders and projects (`one project connects to many work orders`)
- [x] Adding a project selector field to all places a work order is created (there are quite a few at this point)
- [x] Adding a connected "Work Orders" table to the project details page - `project details`
- [x] Adding the `project ID` column to the primary work orders table and work order details (TBD, need input from Billy/staff)

**Comment by johnclary** [comment]
@amenity here's one that needs to be groomed/assigned

**Comment by amenity** [comment]
@dianamartin - giving this to you for next sprint. Happy to talk through it with you and Billy if that's helpful.

**Comment by dianamartin** [comment]
- [x] Created connection on `work_order_signals` object able to `projects` object table (projects many to one work order)- - [x] Added "Work Order" table to Project Details page, added same columns as in "Work Order - Technicians" table

**Comment by dianamartin** [comment]
Need to set-up meeting with Renee & Billy

**Comment by dianamartin** [comment]
Met with Billy and Renee 9/2 about the enhancement. Billy had concerns over what kind of projects would go on this list. They agreed larger more long term projects made sense here. Renee mentioned that this is new and a work in progress, I mentioned it's an interim solution until MOPED gets configured. It works for what they need right now.
