### ISSUE TITLE
Update "Journal Voucher" info in AMD Data Tracker - Warehouse Inventory- (7/13/2021 - Inventory Adjustments)

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#7023]
- [x] Spreadsheet emailed from Van month of: `July - 7/13`
- [x] Number of records being updated: `56`
- [x] Format spreadsheet [(Review instructions)](https://atd-dts.gitbook.io/atd-knack-operations/warehouse-inventory-updating-journal-vouchers-jv-information)
- [x] Spot check Transaction IDs, no JV information before import
- [x] Import records
- [x] Spot check Transaction IDs, no JV information after import
- [x] Email Van that update task complete

**Comment by dianamartin** [comment]
Emailed user
>I’ve updated the JV record information for spreadsheet with the inventory adjustments on them. I believe the spreadsheet was only for the “Transaction Date” 7/13/2021, and JV Status of “Completed”. Here is a helpful filter. 
Let me if you need anything else.
