### ISSUE TITLE
Data Driven PHB Updates for 2022

### ISSUE THREAD

**Issue by jaime-mckeown** [cityofaustin/atd-data-tech#7024]
- [x] Large Retail (Andres)
- [x] Schools (from MAINT dataset)
- [x] Churches (Andres, gave him updated data that he is working with)
- [x] Parks (from GISDM)
- [x] Large Office (waiting for updated data from Chris R. at the Chamber of Commerce)
- [x] Multi-Family (script, will run closer to end of year)
- [x] Social Services (?)
- [x] Public Trans (should work on this now as it changed quite a bit)
- [x] Household Income (ACS data updates March 2022, will have to use last years data)
- [x] Population Density (ACS data updates March 2022, will have to use last years data)
- [x] CSR (wait until closer to end of year)
- [x] # of Travel Lanes (based on ASMP, has not changed)
- [x] Speed (I don't think this has changed either, but need to check)
- [x] Street Lighting (received update from AE)
- [x] Distance to Signalized Crossing (wait until closer to end of year)
- [x] Median (I don't think this has changed)
- [x] HIN (static layer)
- [x] Pedestrian Crashes (wait to collect from VZ database until closer to end of year)

Checked with Renee, will process all other data the 1st week of January.
