### ISSUE TITLE
Offboard CICs

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#7063]
Let's make sure all accounts and access have been appropriately retired.

[Separated Employee Request Form (SERF)](https://atx.service-now.com/sp?id=sc_cat_item_guide&sys_id=72fb6289db9f73405b03f482ba961956) (Supervisor must complete)
- [x] Jorge -> Mateo
- [x] Annie -> Diana - Req `REQ0091243`
- [x] Janet -> Amenity - Req [# REQ0091206](https://atx.service-now.com/sp?id=sc_request&is_new_order=true&table=sc_request&sys_id=895232e41b9e7c10f4da55392a4bcb5b)

Other
- [x] Remove all from Github team
- [x] Remove all from Slack
- [x] Remove from Miro
- [x] Revoke Google Drive access
- [x] Remove from 1Password
- [x] Remove from Knack apps @dianamartin - _no apps were affected_
- [x] Revoke VZE access @mateoclarke 
- [ ] Move to Alumni on DTS website, post #7067

**Comment by johnclary** [comment]
thank you @amenity! you went serf-ing 🏄‍♀️ ?

**Comment by dianamartin** [comment]
- [x] 1password, suspended Annie's access
- [ ] ~ Knack~ Surbhi mentioned a few places to check but she never had any access when I checked them

**Comment by amenity** [comment]
Mateo filled out Jorge's SERF.
