### ISSUE TITLE
Automate Cost of Services (COS) Monthly Reporting

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#7071]
Automate cost of service (COS) reporting. Users must be able to download, on demand, two reports:

- a transaction report which can be uploaded into the AIMs system to transfer funds from other departments to ATD. This is the "JVD" report
- a report which itemizes fees that will be charged to each department, and can be provided to each department for review before processing the transactions in AIMS. Let's call this the "Department Report"

### Resources:
- [Miro board](https://miro.com/app/board/o9J_lrnxMhs=/) with basic data flow
- [Google sheet](https://docs.google.com/spreadsheets/d/132IH0tTLHp9KeuWYN9xhTY7cmad6ojam64jzvU5phPE/edit#gid=983197605) with report template and field mappings
- [Github repo](https://github.com/cityofaustin/atd-cost-of-service-reporting)

### Todo:
- [x] Develop AMANDA SQL Queries
- [x] Develop Knack queries
- [x] Create a sample JVD Report **with real data** for staff review
- [x] Create a sample Department Report **with real data** for staff review
- [x] Write ETL scripts
- [x] Set up database pipeline/infrastructure
- [ ] Determine how reports will be delivered. A UI would be nice, but an email may have to suffice in the near term.

**Comment by TracyLinder** [comment]
### Dev Team Convo
_Possible solution_

1. Import data from KNACK & AMANDA (2 scripts, one for each source)
2. Dump data into database table (where?)
3. Run a script that creates the AIMS JVD template w/ the imported data. 
4. Load AIMS JVD data into another table
5. Provide a link to staff to download the data in CSV format.

**Comment by TracyLinder** [comment]
I'm meeting w/ John on 10/7 to review the AIMS template.

**Comment by TracyLinder** [comment]
**Update**

I created a mockup of the report/data that our partner departments will receive each month & sent to Peggy for review. 
[COS Stakeholder Report MOCKUP.xlsx](https://github.com/cityofaustin/atd-data-tech/files/7255111/COS.Stakeholder.Report.MOCKUP.xlsx)

**Comment by TracyLinder** [comment]
Note to my future self: Should we include the applicant people rsn in the data warehouse? We won't need to show it to stakeholders, but it may be helpful for data validation.

**Comment by johnclary** [comment]
Have a basic working query:
```sql
SELECT  distinct folder.folderrsn, folder.foldername, folder.folderdescription
       , validaccountfee.glaccountnumber
       --, abf.feecode
       , validaccountfee.feedesc
       , accountbillfee.feeamount 
       , accountbillfee.billnumber  
       , accountpayment.paymentamount
       --, accountpayment.amountapplied
       , accountpayment.paymenttype
       , accountpayment.paymentnumber
       , accountpayment.paymentdate last_paymentdate
       , accountpayment.locationcode location_code
       , accountpayment.paymentcomment checknumber
       , accountpayment.stampuser
       , validsub.subcode
       , validsub.subdesc
       , validwork.workcode
       , validwork.workdesc
       , people.namefirst
       , people.namelast
  FROM accountbillfee 
   JOIN validaccountfee ON (accountbillfee.feecode = validaccountfee.feecode)
   JOIN folder ON (accountbillfee.folderrsn = folder.folderrsn)
   JOIN accountbill ON (accountbillfee.billnumber = accountbill.billnumber)
   JOIN accountpaymentdetail ON (accountpaymentdetail.billnumber = accountbill.billnumber)
   JOIN accountpayment ON (accountpayment.paymentnumber = accountpaymentdetail.paymentnumber)
   JOIN validsub on (folder.subcode = validsub.subcode)
   JOIN validwork on (folder.workcode = validwork.workcode)
   JOIN folderpeople on (folder.folderrsn = folderpeople.folderrsn)
   join people on (folderpeople.peoplersn = people.peoplersn)
  where accountpayment.voidflag is not null
    and accountpayment.paymenttype = 'COS'
    and rownum < 10;
```

**Comment by TracyLinder** [comment]
@dianamartin thank you.
I just gave you access to view my meeting recording in case you wanted to watch it.

**Comment by johnclary** [comment]
do'h—i've made all the requested changes except:
> filter on payment_status = paid on accountpayment table. Might be a code, not a description.

@johnclary do this!

**Comment by johnclary** [comment]
Ready to deploy daily ETL via [this DAG](https://github.com/cityofaustin/atd-airflow/pull/72)

**Comment by johnclary** [comment]
Made [some progress](https://github.com/cityofaustin/atd-cost-of-service-reporting/blob/production/knack_run_jvd_report.py) on the JVD report. Going to hold off on further development until Van runs her test with controller's office. She will manually complete the JVD template, and I'll reference it once the controller's office approves it.

**Comment by TracyLinder** [comment]
### Convo w/ PWD

- TCP Engineering staff at PWD can't figure out which TCP the review fee relates to by looking at the COS data. Tracy will schedule mtg w/ PWD & Darren's staff to scope a solution so the COS data is sufficient for TCP fee review.

We need to document the process for dpt to disapprove of a fee.

1. Dpt asks us to invoice the contractor instead of paying w/ COS
2. Dan voids the payment & informs ROW. (This opens the invoice back up for payment. It also drops the record from the COS data on KNACK.)
3. ROW informs contractor to pay the invoice. (_This is my assumption; we need stakeholder feedback because i'm not sure._)
4. Contractor/Applicant pays the invoice.


@johnclary is the data updating daily?

**Comment by johnclary** [comment]
@TracyLinder yes—the data updates daily at ~10pm
