### ISSUE TITLE
Update "Journal Voucher" info in AMD Data Tracker - Warehouse Inventory- August 2021

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#7088]
- [x] Spreadsheet emailed from Van month of: `August, 8/23/2021` - Posted in August (TXN: 4/5/21-8/18/21)
- [x] Number of records being updated: `644`
- [x] Format spreadsheet [(Review instructions)](https://atd-dts.gitbook.io/atd-knack-operations/warehouse-inventory-updating-journal-vouchers-jv-information)
- [x] Spot check Transaction IDs, no JV information before import
- `11686`
- `11341`
- [x] Import records
- [x] Spot check Transaction IDs, no JV information after import
- [x] Email Van that update task complete

**Comment by dianamartin** [comment]
- There were 345 records for - `JVDA 21081900046`
- There were 299 records for - `JVDA 21082300047`

**Comment by dianamartin** [comment]
Emailed Van
>644 records were updated with the JV information requested. I’ve also added filters for each JV number below.
•	There were 345 records for - JVDA 21081900046
•	There were 299 records for - JVDA 21082300047
Let me know if you need anything else.
