### ISSUE TITLE
Added new choices "Scheduled Work" drop down menu for AMD Work Orders

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#7097]
> What application are you using?

Data Tracker

> Describe the problem.

I would like to have some items added to scheduled work drop down menu.
Please add:
- [x] Installation - Cell Modem
- [x] Installation - Ethernet Switch
- [x] Installation - Fiber Switch
- [x] Misc - Communications

> Describe the outcome you'd like to see when this feature is implemented.

I will be able to categorize work orders better. 

> Describe any workarounds you currently have in place or alternative solutions you've considered.

N/A

> Is there anything else we should know?

As soon as possible, please.

> Requested By
Harrell M.

Request ID: DTS21-102585
