### ISSUE TITLE
[BUG] KNACK - Inline editing error

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#7100]
**Describe the bug**
When a builder activates "in-line editing" function to make the record rule capture an audit field. It has an error message.
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/4be05098-c851-41df-a1c0-529f1c5b4405)

Messaged Knack
> when i enabled inline editing and tried to add any rule I get an error message

**How would you rate the impact of this issue?**
- [ ] Severe — cannot perform work, no workaround
- [ ] Major — can only perform work using a workaround
- [x] Minor  — can perform work, but could be easier or faster
- [ ] Does not affect work performance
- [ ] Unsure

**Comment by dianamartin** [comment]
@ChrispinP 

Knack said
>Hi Diana,
Thank you for reaching out and for reporting this.
We, unfortunately, do have a known issue currently causing that error to get thrown when inline editing is enabled and the rule is set to "update record". We have tagged this conversation with that issue and will follow up here once a fix has been deployed to confirm everything is working properly.

>In the meantime, we have noticed the rule should save if you switch the "action" to "send custom email" and then flip it back to "update record" and then try to save again.
Please let us know if you have any questions about the above and once we see an update on this bug we will follow up here.

>Thank you, Diana!

**Comment by dianamartin** [comment]
Tested the work around and it works.

**Comment by dianamartin** [comment]
Knack's last reply
>You're welcome! We will keep a close eye on this and follow up once we see a fix deployed.
