### ISSUE TITLE
While working in the Studies page, there were several screens where the location was blank.  

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#7112]
> What application are you using?

Data Tracker

> Describe the problem.

While working in the Studies page, there were several screens where the location was blank.  

> Website Address

https://atd.knack.com/amd#study-locations/studies/?view_3002_page=16

Internet Browser: Chrome

> Requested By
Renee O.

[Attachment](https://api.knack.com/v1/applications/595d00ebd315cc4cb98daff4/download/asset/6131261f44273a001ec68984/datatrackerstudypage.pdf) (102.31kb)

Request ID: DTS21-102595

**Comment by dianamartin** [comment]
Need to follow-up with user to see if these studies were intentionally blank or became blank, if having manually connect or re-import records will resolve the issues.

**Comment by dianamartin** [comment]
Talked to Renee this morning and we weren't sure about these being on purpose. We compared a Study details of one that has a Location ID v. a record that didn't have it. 

## Has Location ID
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/b601e677-3358-46b1-9398-500565e0a1a3)

## Do not have Location ID
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/34f98e76-9ad8-4a7e-aeec-68afc1c4f60a)

# Method
- Only 63 studies that don't have a location id
- Will export the 63 and try to re-import, but field match based on the `Study Location` field

**Comment by dianamartin** [comment]
- [x] Checked the new "study" record Renee created, it didn't have the "location" field populated
- [x] Checked the "Add study" form, looked like the connection value wasn't being transferred to the study
- [x] Added a record rule 
- `location` to a connected value `study_locations>location ID`

**Comment by dianamartin** [comment]
Messsaged Renee 9/8
>I was able to successfully import them, however there are 2 records that are blank and look orphaned. These were the ones that were entered before and after the 2 records, `411` and `414` were the orphaned ones.

![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/f51f8913-3a62-43fe-a82e-47f3df9b380e)

User replied
>Thank you!

I replied
>welcome, let me know if you need me to delete those 2 records
