### ISSUE TITLE
Create new tab "Communications" page, table (exportable) for better Communications device status tracking

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#7126]
> What application are you using?

Data Tracker

> Describe the problem.

Looking for a new exportable table to be added that includes the following
Cabinet
- [x] Cabinet ID
- [x] Cabinet Type
- [x] Cabinet Communication Type - Ask Brian to clarify this one
- [x] UPS
- [x] UPS Install Date
- [x] UPS IP Address
- [x] UPS Port
- [x] Monitor Type
- [x] Monitor IP
- [x] Monitor Port
- [x] Cameras	ID
- [x] Status
- [x] Camera IP
- [x] Camera Type
- [x] Signal ID
- [x] Location
- [x] Type
- [x] Owner

> Describe the outcome you'd like to see when this feature is implemented.

Allow us to better track device status 

> Describe any workarounds you currently have in place or alternative solutions you've considered.

exporting multiple tables and joining outside knack

> Requested By
Brian C.

Request ID: DTS21-102610

**Comment by dianamartin** [comment]
Make an "Advanced Search" table/page
Try to stick it into Signals "Communications" section - maybe?

**Comment by dianamartin** [comment]
Emailed Brian 
>I have made your request to “Create new tab "Communications" page and exportable table for better Communications device status tracking”. It can be found on the home page button. 

![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/7e874f17-4ba8-4365-b1e2-61ee5055532f)

>I had to create a new user role for the page as we can’t grant individual access to pages. You and Lance have the “Communications Editor” role to be able to access the page: /amd#communications/
-	The only clarification I needed was for the field you requested to add to the table “Cabinet Communications Type”, can you make sure that this field is there or which field I need to add.

**Comment by dianamartin** [comment]
- Sync'd with Brian, figured out the "Cabinet Communication Type" field he was wanting. 
- Added to the search table and search fields
- Switched some field orders around
