### ISSUE TITLE
Update "Journal Voucher" info in AMD Data Tracker - Warehouse Inventory- Sept 2021

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#7188]
- [x] Spreadsheet emailed from Van month of: `Sept  21 & 22`
- [x] Number of records being updated: `621`
- [x] Format spreadsheet [(Review instructions)](https://atd-dts.gitbook.io/atd-knack-operations/warehouse-inventory-updating-journal-vouchers-jv-information)
- [x] Spot check Transaction IDs, no JV information before import
- `9953`
- `11577`
- `11880`
- [x] Import records
- [ ] Spot check Transaction IDs, no JV information after import
- [ ] Email Van that update task complete

**Comment by dianamartin** [comment]
Synced with Van on 9/16. Clarified the transaction IDs are unique while the work order IDs are not. She's looking into the transactions that can be completed for their "JV Status".

**Comment by dianamartin** [comment]
Van said that all transaction for the month of August seemed to have been populated, but will confirm again - 9/21

**Comment by dianamartin** [comment]
Van didn't need this anymore for August. Repurposed this for the September JV request she had.

**Comment by dianamartin** [comment]
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/7c3b2e08-78ce-464e-851b-7ea31033b2c1)
