### ISSUE TITLE
Add the "art box" field show up in the Signal Details page

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#7194]
> What application are you using?

Data Tracker

> Describe the problem.

Can you please have the "art box" field show up in the Signal Details page? Right now it only shows up in the Cabinets page for a signal.

> Describe the outcome you'd like to see when this feature is implemented.

Easier identification of which signals have art box cabinets, since this impacts what types of changes we can make at that intersection.

> Describe any workarounds you currently have in place or alternative solutions you've considered.

We can use the query tool and can go into the cabinet page. The Signal Details page is more convenient, because we use that page for all types of general inquiries.

> Requested By
Jen D.

Request ID: DTS21-102650

**Comment by dianamartin** [comment]
- [x] Added `Art Box` field on Signal Details list
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/751bc3ea-8cb0-4d2c-ae23-3df63a119f66)
- [x] Added `Art Box` field on Signal List search inputs
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/0d8460cd-8fe2-4546-9418-ef2f6e28a1d7)
- [x] Added `Art Box` field on Signal List search results table
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/bac6937e-5ffc-4fc5-8131-6fecb3096440)

**Comment by dianamartin** [comment]
Emailed Jen
>- Added Art Box field on Signal Details list
- Added Art Box field on Signal List search inputs 
- Added Art Box field on Signal List search results table
