### ISSUE TITLE
Develop prototype for Parking Meters non 311 SR tracking tool 

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#7218]
Develop a prototype to present to Parking Enforcement team
Parking Enforcement Officers will be entering the new SR's 

Parking Meters requirements: 
- We would like to utilize the "My Assignments" tab to allow technicians to take photos of the SR being completed

- We would like to see parking enforcement work orders for bike rack damage, graffiti on pay stations, scratched screens etc. show up on Parking Meters knack page.

- Officers will enter new service request when they encounter Parking Meter related issues in the field

**Comment by dianamartin** [comment]
- [x]Created a new page `Parking Meters`
- [x] Created a new page `Service Request Meters`

Found out the 311 Ownership code to use to differentiate between Parking Meters (PARKINGM) and Parking Enforcement (PARKING2). 

- [x] Created Menu button on "My Assignments" (only I can see it) - New Page `new-service-request-meters`
- [x] Created Page/Form for PEO to submit a Meter SR (removed all unnecessary fields, very simple form)
- [x] Created Table on `Service Request Meters` of the `csr_issue` records with the Ownership code `PARKINGM`
  - Grouped by "Issue Type"
- [x] Created a brand new details page
  - Copied all components from Parking Enforcement SR Details page
  - Added Rules that were reuseable
- [x] Kept old link to SR details page 
  - Added new Activity Form for Meters,  (removed all unnecessary fields)

**Comment by dianamartin** [comment]
Sync'd with Stephanie on 9/23, she gave feedback about allowing the PEOs to attach a photo. Need to test and rework this to include being able to add an activity to "add an attachment".

**Comment by moorerst** [comment]
Prototype is ready for demo to the stakeholders in Sprint Review 10/21
