### ISSUE TITLE
Requesting some changes in the Contractor Work Order tracker.

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#7224]
> What application are you using?

Signs & Markings Operations

> Describe the problem.

Requesting some changes in the Contractor Work Order tracker.

> Describe the outcome you'd like to see when this feature is implemented.

Would like to 1) allow Requesters (ATSD/TED/etc) to access the contractor work order page as a viewer. Should not be able to submit work orders but view the information. Would also like to 2) add a notes field to the "mid project inspection" button so the contractor can provide more information regarding the work and locations that they completed that day.

> Describe any workarounds you currently have in place or alternative solutions you've considered.

Would like to roll this out in October. 

> Requested By
Christina T.

Request ID: DTS21-102695

**Comment by dianamartin** [comment]
- [x] Changed log in permissions for "Manage Contracts" page to allow "Viewer" user roles

On Contractor Work order Details
- [x] Added "Comments - NON-EDTITABLE" table
- [x] Added page rule if User has "Viewer" roles, to hide the "Comments - EDITABLE" table and the "Buttons" menu

**Comment by dianamartin** [comment]
Syncing with Christina on 10/5 to review changes on the Mid-Project Inspection form, with new "notes" field

**Comment by dianamartin** [comment]
- Tested mid project inspection
- Update Page rules to not submit if a work log wasn't completed
- Tested mid project inspection comments
- Fix record rule to create a new comment
- Added new "WORK TYPE" choice, `Mid-project inspection request submitted`
- Added "WORK TYPE" field to my-workorder-c details on comments table
- Removed "Delete" button from comments table
- Added "WORK TYPE" field to work-orders-contractor details on comments table
