### ISSUE TITLE
Import school beacon data from AGOL into Data Tracker

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#7232]

**Comment by dianamartin** [comment]
Sync'd with Jaime about the datasets she created in #7148

**Comment by dianamartin** [comment]
Ask Jaime to get street segment of the beacon
- nearest segment
- lat fields
- long field
Will have to create new locations for the new school beacons
- import segment
- lat
- long
- temp field for locations (give school beacon id) to connect to import the beacons
Use the existing School beacon object
Delete and replace with new imported data from AGOL

**Comment by dianamartin** [comment]
## Dataset comparison 
- Data Tracker - GIS dataset 
- Update GIS dataset with street segment or copy with it

**Comment by johnclary** [comment]
Ooh nice work! So most can be deleted.

**Comment by dianamartin** [comment]
John said 10/15
>just delete the beacons, we can cleanup the locations later

- [x] Created new object table `school_zone_beacons_new`
- [x] Renamed the old object table `school_zone_beacons_old`
- [x] Imported 708 records into new table
- [x] Rearranged the fields to be more logical
- [x] Added audit fields (Created_By & Modified_By)
- [x] Renamed CreatedDate and ModifiedDate to normal audit field names

**Comment by dianamartin** [comment]
LOC21-018005 is the last location in the system before I do a test import for 5 records
