### ISSUE TITLE
Ability to create work order at school zone beacon

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#7233]
Add the ability to create a signal technician work order at a school zone beacon.

**Comment by dianamartin** [comment]
Need to talk to stakeholder about options

**Comment by dianamartin** [comment]
Talked to Billy and Allyson
>they said that MMC/Technicians need to have the ability to create a work order on a School Zone Beacon and a WebIO
- John and I talked and need to discuss further the WebIO asset configuration (it's complex)
- Will move forward with the School Zone Beacon configuration

**Comment by dianamartin** [comment]
Apparently the work order was connected to the "School Zones", the MMC SR's were connected to the "School Zone" and "School Zone Beacons.." 

# TMC Activity Configuration in TEST
## School Beacon configuration - Work Order
- [ ] New Work Order>My Work Orders - add SZB field
- [ ] Add Display Rule - show/hide fields
- [ ] Add Record Rule - asset>Location connection
- [ ] New Work Order>Work Orders (Signals) - add SZB field
- [ ] Add Display Rule - show/hide fields
- [ ] Add Record Rule - asset>Location connection

# TMC Activity Configuration in PROD
## School Beacon configuration - Work Order
- [ ] New Work Order>My Work Orders - add SZB field
- [ ] Add Display Rule - show/hide fields
- [ ] Add Record Rule - asset>Location connection
- [ ] New Work Order>Work Orders (Signals) - add SZB field
- [ ] Add Display Rule - show/hide fields
- [ ] Add Record Rule - asset>Location connection

**Comment by dianamartin** [comment]
Updated the "Display Name" for school beacon connection as I think this is more helpful for users

![image](https://user-images.githubusercontent.com/21112975/141539366-e9be3d3d-8822-4246-803c-83aa55217c0d.png)

**Comment by dianamartin** [comment]
@johnclary I added the "School zone beacon" on the asset types for TMC and also for the AMD Work Orders. I have both the school zone and school zone beacons right now.

**Comment by dianamartin** [comment]
Sync'd with Allyson on 11/16 and seems as though MMC staff are able to create SRs/WOs against school zones
