### ISSUE TITLE
[Spike] Strip out features from Data Tracker for Moped work

### ISSUE THREAD

**Issue by zappfyllc** [cityofaustin/atd-data-tech#7241]
JD will look at the project management functionality implemented by @johnclary  in Data Tracker and do a quick check of what needs to be built in Moped vs. what can be used that's there already

- [x] Compile missing data pieces (whether sourced from Moped or Data Tracker, where they're being stored, etc.)
"Task Order" is another field that can be sourced via Open Data Portal (same implementation as #7016)

Project type will start with the AMD options given in Data Tracker (Signal - Mod, Signal - New, RRFB - New, PHB - New, PHB - Mod), knowing that for v2.0 we will then import the [following list](https://docs.google.com/spreadsheets/d/1VGO57EL1TtASbLz2yeWyLwcTB1lT9LR8G6_QZ4WSifs/edit#gid=1128465159)

Contractor/Contract, Project DO #, and Work Assignment ID all should be short text fields in Moped. We can discuss updates sending to Data Tracker but initial impression is that we don't necessarily have to do this because those fields are at the project level and should therefore be tracked in Moped, not Data Tracker.

Other fields that should be 1:1 matches between Moped and Data Tracker:
- Funding > Funding source
- Name > Project name
- Current phase > Current phase
- Internal status note > Current status
- Targeted construction phase > Phase start for Construction phase in the project

- [x] Identify missing UI features that will need to be implemented in Moped

We will discuss in Grooming, but ideally we'd like a new editable table for bulk editing projects, then a link to the current project details page for any given project.

- [x] Decide on reusable strategy for integrating with Knack API on-demand (w/ @sergiogcx and team)

For data going from Knack > Moped, we will borrow from the previous Signals work in #7016 and use the same strategy. For data going from Moped > Knack, we need to decide on a strategy but we just need to send project IDs when a new project is entered in Moped, and when a project is closed. (so we need project ID, project name, and current status sent to Knack)

**Comment by johnclary** [comment]
[Link to the AMD projects page in Data Tracker](https://atd.knack.com/amd#projects/).

**Comment by johnclary** [comment]
At a quick glance, these are the fields that don't have a home in Moped yet. Would be really good to scope these individually to keep them moving into the hands of devs:

- Project type
- Contractor/Contract
- Project DO #
- Work Assignment ID

**Comment by zappfyllc** [comment]
"Task Order" is another field that can't be sourced via Open Data Portal (same implementation as #7016)

Project type will start with the AMD options given in Data Tracker (Signal - Mod, Signal - New, RRFB - New, PHB - New, PHB - Mod), knowing that for v2.0 we will then import the [following list](https://docs.google.com/spreadsheets/d/1VGO57EL1TtASbLz2yeWyLwcTB1lT9LR8G6_QZ4WSifs/edit#gid=1128465159)

Contractor/Contract, Project DO #, and Work Assignment ID all should be short text fields in Moped. We can discuss updates sending to Data Tracker but initial impression is that we don't necessarily have to do this because those fields are at the project level and should therefore be tracked in Moped, not Data Tracker.

Other fields that should be 1:1 matches between Moped and Data Tracker:
Funding > Funding Source

**Comment by zappfyllc** [comment]
Created #7310, #7311, and #7316 from this issue in the epic
