### ISSUE TITLE
[Feature] Daily status logs for all AMD devices

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#7303]
> What application are you using?

Data Tracker

> Describe the problem.

We'd like to log a daily status for each of the devices tracked at https://atd.knack.com/amd#communications/

This data would be fed into a PowerBI dashboard to monitor performance for network devices over time. 

Currently, it provides current status, but we want to log and track the status over time.

> Describe the outcome you'd like to see when this feature is implemented.

Create a device status log for all of our connected devices. I envision the following fields:

Date; Signal ID; Location; Device Type; IP address; Status

> Describe any workarounds you currently have in place or alternative solutions you've considered.

None

> Requested By
Lance B.

Request ID: DTS21-102745

**Comment by amenity** [comment]
@johnclary I spoke to Lance about this this morning and he indicated that it was originally a request from Brian C. and that y'all have discussed it by email? Sounds vaguely familiar, but Outlook search is failing me ...

**Comment by johnclary** [comment]
Per discussion with MMC. We will track:

- Device ID
- Device Type
- Signal ID
- Location (ATD) – we’ll have some that aren’t associated with a signal (like high rise CCTVs)
- IP Address
- Timestamp (with date)
- Online (true/false)

I blocked off 11/11 and 11/12 to spike on this

**Comment by johnclary** [comment]
Ready for AMD review. Repo is [here](https://github.com/cityofaustin/atd-signal-comms).

**Comment by johnclary** [comment]
I sent a sample CSV to Brian, Lance, and Allyson on teams.

> questions for you:
> 	
> can you live without the IP address on here? i'd like to avoid including in the data portal dataset, even if the dataset is private. as an alternative, we could generate a direct URL to the device info in the Data Tracker?
> 	
> the signal ID is not included, but it can be. just wanted to re-confirm that it will be useful?
> 	
> the log is currently designed to update on a daily basis. so, one record per device per day. that's what y'all want?
> 	
> the timestamps are in UTC time. i can alter them to be local time, but given that there's only record/day, i assumed the timezone doesn't matter to you. but let me know.

**Comment by johnclary** [comment]
Per Lance,

> - We're ok without the IP
> - We need the Signal ID
> - Daily is what we want. we think run it overnight. After a year's time, we may need to talk about aggregating archive data somehow to keep thing stidy
> - UTC time is fine as long as the date is correct

Next on my list:
- [ ] configure scripts for additional devices ( bbu, mmu, cabinet switch, signal switch )
- [ ] add signal ID 
- [ ] deploy to airflow

**Comment by johnclary** [comment]
I've updated the scripts to include signal ID. I'm working on the DAG for cameras and detectors before moving on to other device types. I just realized I need to install the pertino VPN client on atd-data02 in order to reach devices on cell modems. Working on that now....

**Comment by johnclary** [comment]
I've deployed this for cameras and detectors and let AMD folks know:

> Hi folks,
> 
> I've deployed the automated task which updates the daily device status log. It is currently configured for cameras and detectors only.
> 
> Here is the dataset. It will be updated around 2am daily. Let me know how that works for you.
> 
> I've come across some data cleanup that is needed before we implement additional devices. I'll reach out to you separately once I have a handle on what needs to be done.

I need to configure additional device types, but there's issues with the cabinet data in Data Tracker. I'll open a new issue and post back here.
