### ISSUE TITLE
[Enhancement] Integrate with Data Tracker to send new AMD projects over to Knack

### ISSUE THREAD

**Issue by zappfyllc** [cityofaustin/atd-data-tech#7311]
Since we are planning to archive the Projects page in Data Tracker and instead roll out Moped as the source of truth for AMD Projects, we need to send newly created projects over to Data Tracker.

**Details:**

- [ ] [`projects` object in Data Tracker](https://builder.knack.com/atd/amd/records/objects/object_201) needs to contain a place for Moped project ID (needs created), the Moped project name (field_3857), and the Moped project status (needs created). All of these can be strings.

- [ ] When a user creates a new project, the project should send a POST request to the [`projects` object in Data Tracker](https://builder.knack.com/atd/amd/records/objects/object_201). This request must be fault-tolerant and the newly created record must appear within Data Tracker within minutes.

- [ ] Save the Knack record ID from the POST request response above within Moped for future PUT requests and linking.

- [ ] When a user updates the project name or project status, a process (ETL?) should update the project name or project status in Data Tracker. This does not need to occur frequently; daily updates to the project name and project status (if there's a change) would be fine.

**Comment by zappfyllc** [comment]
Per call with @sergiogcx and @johnclary on 10/4:

- Sergio posed a few different options for a solution, including creating a Zapier-like, serverless service that stores failed payloads sent out from Moped (time exhaustive, would likely involve SQS or similarly hard-to-configure service), using Apache Kafka for stream processing (expensive), or Google Pub-Sub (less expensive, but would still require an additional set up for the consumer side of the message) messaging.
- John suggested we may want an intermediary database, such as the one created for [atd-knack-services](https://github.com/cityofaustin/atd-knack-services), and running a similar ETL setup.
- Sergio proposed that we could use S3 (failed, pending, completed buckets) since it would not be expensive and would be reliable to query against with an ETL setup. But this still might be a bit of over-engineering for what's needed.

We discussed moving forward (for the purposes of time and the next sprint) with an ETL approach like in [atd-knack-services](https://github.com/cityofaustin/atd-knack-services) where we can send data over to Knack and then periodically compare the records to one another, while acknowledging that a longer term, sustainable solution might be helpful for future integrations.

Additionally, Sergio and John agreed that the deployment process of atd-knack-services could use some work (deploy, then checking for failure currently, and that's not ideal).

cc @amenity FYI

**Comment by amenity** [comment]
🙌

**Comment by zappfyllc** [comment]
FYI re: looking into cron triggers--

I thought maybe we could use the metadata API to dynamically create cron triggers so we could have a daily sync from Moped to Knack via Hasura and not exhaust the system during the same time it's in use (e.g. adding to event triggers) for the simple act of keeping two tables in sync where the table in Knack is a read-only table to the Knack users, but I did not account for the fact that the cron triggers are not set up for batch requests and that I believe this method would lead to generating many cron triggers, which is not likely a good path for implementation and is even messier.

**Comment by zappfyllc** [comment]
@amenity @frankhereford @johnclary Convo today unearthed an oversight on my part, which was considering the current signals integration on the new project and project components screens, and how projects will be related from within Data Tracker (specifically, my expectation was to relate these within Data Tracker's UI itself, but it makes sense that users will already be using Moped to relate them which would cause immediate data issues).

I'm going to add some thoughts here while things are fresh for me and we can sort it out in subsequent discussions and/or issues.

If we are to send signal_ids, which will be an array of signal_ids that represent Knack record IDs corresponding with rows in the `signals` object in Data Tracker, we have a few issues to sort out:
- The signal Knack record IDs are currently stored in a JSONB column `moped_proj_features` (this was discussed in @chiaberry's work with #7316). If they are not, I think @johnclary has mentioned it should be a relatively quick fix to make sure those are stored.
- We need to remove the ability for Data Tracker users to relate signals to a project (this should be done from Moped).
- At the moment, I think the "use signal asset ID" only works for one signal, but the goal was to be able to group multiple signals under the same project. This can be done in Data Tracker currently, but we'd be removing that ability so I think it makes sense to modify the current functionality to support multiple selection of signals from creation of a new project.

TBD, there might be more...
