### ISSUE TITLE
Update "Journal Voucher" info in AMD Data Tracker - Warehouse Inventory- YEAR END ADJUSTMENT 9/2021

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#7330]
- [x] Spreadsheet emailed from Van month of: YEAR END 
- [x] Number of records being updated: `20`
- [x] Format spreadsheet [(Review instructions)](https://atd-dts.gitbook.io/atd-knack-operations/warehouse-inventory-updating-journal-vouchers-jv-information)
- [x] Spot check Transaction IDs, no JV information before import
- `12711`, `12713`
- [x] Import records
- [x] Spot check Transaction IDs, no JV information after import
- [x] Email Van that update task complete

**Comment by dianamartin** [comment]
- I formatted and imported the 20 records. Spot checked before and after. 

Emailed user
>Hi Van, 
I’ve updated the inventory transaction records with the 20 year end adjustments from your spreadsheet from 9/30. Here is the page filtered for it.
- Let me know if you have questions.
