### ISSUE TITLE
Update "Journal Voucher" info in AMD Data Tracker - Warehouse Inventory- Sept 2021

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#7390]
- [x] Spreadsheet emailed from Van month of: FILL MONTH OUT, DATE RANGE
- [x] Number of records being updated: `347`
- [x] Format spreadsheet [(Review instructions)](https://atd-dts.gitbook.io/atd-knack-operations/warehouse-inventory-updating-journal-vouchers-jv-information)
- [x] Spot check Transaction IDs, no JV information before import
- `12722`
- `12375`
- `11289`
- [ ] Import records
- [ ] Spot check Transaction IDs, no JV information after import
- [ ] Email Van that update task complete
