### ISSUE TITLE
Convert "Conflict/Shared Work Zone Analysis" intake form in Smartsheet to Knack in ROW Portal

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#7397]
### Replace the Conflict/Shared Work Zone Analysis in Smartsheet with a KNACK app on the ROW Portal. 
- The scope is limited to standing up like-for-like features. 
- [Here ](https://cityofaustin-my.sharepoint.com/:v:/g/personal/tracy_linder_austintexas_gov/EUW0poTqeKNKsoUeE4FMcvMBlpK6h-rgH7-lK-iGvSFabQ)is the recording of the scoping meeting

**Basic Requirements:**

- New service landing page on public ROW Portal
- Intake form/workflow on public ROW Portal
- Email confirmation of submittal 
- Status automated are _Application Incomplete_ and _Pending Intake_

**Smartsheet Columns:**
1. ROWID assigned by Smartsheet _(not needed)_
2. Created Date
3. Request # 
4. Applicant Info (see screenshot; many data points collected that need to be split out in KNACK.)
5. Conflicting Party Info (same data as Applicant info, but for the current permit holder)
6. Type of Review (drop down: Shared TCP or TCP Conflict)
7. TCP Being Used (Only applicable for Shared TCP)
8. Consent (Only applicable for Shared TCP)
9. Modifications (open text to gather details about any modifications made to existing TCP)
10. Internal Comments
11. Status of Review (We need to update the statuses being used to align with TCP Case statuses.)
12. Due Date (Same due date logic as TCP submissions)
13. Adjusted Due Date (Same feature as TCP Submissions) 
14. Assigned Reviewer
15. Completed Date
16. Completed Checkbox 

----
### DTS Request Submittal by Darren:

> What application are you using?

Data Tracker

> Describe the problem.

The TCP review team is very interested in converting our current intake form (Smartsheet)  to the Knack ROW portal for all of our "Conflict/Shared Work Zone Analysis". 

> Describe the outcome you'd like to see when this feature is implemented.

We would be able to have a Knack intake form for "Conflict/Shared Work Zone Analysis" reviews. We'll copy the same data entry fields in our Smartsheet to Knack. After intake, we want to be able to assign it to a reviewer. Ideally, we'd like it to sync with our TCP reviewer portal so that the reviewer can see it in their review list. 

> Describe any workarounds you currently have in place or alternative solutions you've considered.

We currently have Smartsheet and it is a bit cumbersome for the reviewers, which we hope to remove. 

> Is there anything else we should know?

We hope to have it as soon as possible? We typically receive 100 review request per month and the Smartsheet is a bit of an antiquated process. Thanks! 

> Requested By
Darren U.

Request ID: DTS21-102785

**Comment by dianamartin** [comment]
@TracyLinder cc: @amenity This came up at a meeting (10/19) Chrispin and I had with Peggy about TCP reports. When do you expect to scope this?

**Comment by TracyLinder** [comment]
**Quick Stakeholder Feedback:**
_Darren_

- Still a need. Visioning a new mod on ROW Portal that links up w/ TCP cases where possible. 

- Smart sheet is being maintained by Robert A, and Kim P. 
- I need to schedule discovery.

**Comment by TracyLinder** [comment]
Discovery: Samsun Negeri, Robert Alvarez, Mooney, Darren, Peter

**Comment by TracyLinder** [comment]
**Discovery meeting** scheduled for 1/6/21 at 11am.

**Comment by ChrispinP** [comment]
TCP is already Approved/Approved Standard Detail, or Permit is pending
Volume: 70-100 a month
TCP Conflict Review (come in after) or if a TCP can be Shared

Need: Intake Form for 2 types
as Applicant or Conflicting Party
All Applicant Info fields including Permit Number, Case ID, and TCP Phase
Have a unique Case ID code (WZR)
Multiple Attachments (Zip files, PDFs, and Images)
Internal Comments
Status: Returned, Approved/Completed
Due Date
Assigned Reviewer
Completed Date
Completed (boolean)
Application Type
Auto Increment Request #

Confirmation Page & Email
May need to reach out to customer for new or additional documentation
Customer Submissions

Portal Page with ROW Permit Conflict Instructions and Options

Overall: Could be a TIA 2.0 in the long run after several iterations. Short term, New Application process that connects to TCP's with a Details Page

**Comment by TracyLinder** [comment]
### Email to Darren

Hi Darren,

The discovery meeting was really informative; thank you. After speaking with Diana & Chrispin i think the best way to move forward with this request is to begin by replicating your current smart sheet and it's functionality in KNACK. We call this a like-for-like where we limit our focus and our scope to building only what you currently have. 

For this request I see 2 major features: 
A public facing intake form
A tabular view of the data (same as current, jut in KNACK)
This is a simple lift for us and we'd be able to deliver it within 2-4 weeks after we start building (depending on stakeholder availability). After we get the like-for-like stood up we could then start iterating on updates (like automated emails and workflow management features.)

How does this sound to you? Next step will be a meeting to dig into the smartsheet fields. 

Thanks,

Tracy Linder, Product Manager

**Comment by TracyLinder** [comment]
@TracyLinder needs to schedule next mtg w/ stakeholder to analyze the smartsheet fields.

**Comment by TracyLinder** [comment]
### Grooming Notes:

- @KaroEngstrom may be able to move this On Deck soon. She'll read through the issue to get updated. 
- We need to scope how this mod will intersect with the TCP Review mod in the future. Strategic planning. 
- @TracyLinder will schedule next scoping sesh.

**Comment by TracyLinder** [comment]
### Scoping scheduled for 11/24
_Alyse is out until then._

**Comment by ChrispinP** [comment]
**Field Details:**

- Created Date is Submitted Date on Smartsheet
- Can use new Sequencing and Identifier as long as we do not use existing
- Possible future enhancement to enable customer to save time and submit multiple Conflicts at the same time.
- Applicant Info: Name, Email, Phone, Company/Dept, Project Address, Permit Number, TCP ID, General Permit ID, Site Plan ID [Required]. Conflicting Party same info. Conflicting party has the existing permit.
- TCP Sheet #'s or TCP Phase
- Type: Shared Request or Conflict Review
- TCP being used when its a Shared Request - Applicant or Conflicting party
- Consent when its a Shared Request (Email/Attachment)
- Modifications (paragraph text)
- Reviewer Notes (Internal Comments)
- Status: Pending, Needs Review, In Review, Returned, Review Completed
- Due Date
- Due Date Override
- Assigned Reviewer
- Completed Date
- Completed Boolean

**Comment by TracyLinder** [comment]
### Scoping Notes

**High-level Workflow:**

1. ROW Permitting identifies the potential conflict and directs the customer to submit via the Smartsheet
2. Customer submits for conflict review using the Smartsheet
3. TCP Intake reviews for completeness, updates the data as needed, assigns a due-date, and assigns to a TCP Reviewer
4. TCP Reviewer begins review. They update the status to 'Approved Completed' when done. 
5. Customer must submit the conflict approval to ROW Permitting to move forward with the permit review. 

**Smartsheet Columns:**
1. ROWID assigned by Smartsheet _(not needed)_
2. Created Date
3. Request # 
4. Applicant Info (see screenshot; many data points collected that need to be split out in KNACK.)
5. Conflicting Party Info (same data as Applicant info, but for the current permit holder)
6. Type of Review (drop down: Shared TCP or TCP Conflict)
7. TCP Being Used (Only applicable for Shared TCP)
8. Consent (Only applicable for Shared TCP)
9. Modifications (open text to gather details about any modifications made to existing TCP)
10. Internal Comments
11. Status of Review (We need to update the statuses being used to align with TCP Case statuses.)
12. Due Date (Same due date logic as TCP submissions)
13. Adjusted Due Date (Same feature as TCP Submissions) 
14. Assigned Reviewer
15. Completed Date
16. Completed Checkbox 

**Service Landing Page:**
- Build a landing page for Conflict/Shared Work Zone Analysis 
- Add content

**Next:**

- [ ] Karo needs SmartSheet access (ask Kimberley P.)
- [ ] Karo will build a prototype
- [ ] Tracy will schedule the tech review for the week of 12/27
- [ ] Tracy will schedule customer demo for the 2nd or 3rd week of January

**Comment by TracyLinder** [comment]
I removed the epic connection on this because it's not included in the TCP intake scope.

**Comment by KaroEngstrom** [comment]
## T 12/27/22 

@TracyLinder - Can we schedule an internal tech review this week, or next? I'll then move this to PROD with all the notes from the team. Lmk if you'd like me to set this up, I can also schedule.

**Comment by TracyLinder** [comment]
### Tech review scheduled on 1/6/23

**Comment by TracyLinder** [comment]
### Review Notes

**Public Application:**
1. Landing page ✅
2. Applicant Info ✅
3. Conflicting Party 💬
    - Keep application description at the top
    - Add field 'Conflicting Party Project Address'
4. Attachments 💬
    - Add 3 new types (I didn't catch them but Karo did)
    - Add a radio button for 'Applicant' and 'Conflicting Party'
 5. Edit & Review 💬
     - Update the word **Requestor** to **Applicant**
 7. Submittal Confirmation 💬
     - Language likely to be updated
     - Add a tracking number feature
     - Will need email confirmation email content. Darren said to copy the TCP Intake confirmation email.

**Comment by TracyLinder** [comment]
### Next stakeholder review scheduled for 2/7/23

**Comment by TracyLinder** [comment]
Note to myself: Inform ROW Permitting group of this feature after we roll out; they should be able to find these records & understand them.

**Comment by TracyLinder** [comment]
**Note to discuss w/ stakeholders**: Migrating existing records & working with cases that aren't closed yet.

**Comment by TracyLinder** [comment]
### Meeting scheduled to discuss migrating existing records. 
- 2/10/22
