### ISSUE TITLE
Update signal retiming corridor extents and prototype new approach

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#7421]
Create Excel template for Brian and Lance to identify updated signal retiming corridors and perform bulk update through Knack back end. 

### Request
> What application are you using?

Data Tracker

> Describe the problem.

Need help changing extends of existing retiming corridors, but don't see where the corridor to signal definitions exist. 

> Website Address

https://atd.knack.com/amd#sync-corridors/?view_367_filters=%5B%7B%22value%22%3A%22ACTIVE%22%2C%22operator%22%3A%22is%22%2C%22field%22%3A%22field_533%22%7D%5D

Internet Browser: Chrome

> Requested By
Lance B.

Request ID: DTS21-102805

**Comment by amenity** [comment]
[Email exchange with Lance, Brian, and John](https://drive.google.com/file/d/11EDQMXkI8kIMbLQ8wrKWxawRULb5Rm3T/view?usp=sharingc). Scoping a more extensive solution in https://github.com/cityofaustin/atd-data-tech/issues/7462. 

@dianamartin - will you please make a template for Brian & Lance for this round?

**Comment by amenity** [comment]
[Email thread about this request](https://drive.google.com/file/d/1ksjpuQc8wQJXkurGknSs8Ws2VnP0Z4HB/view?usp=sharing). @dianamartin is helping out with this update, but we're also discussing the process and how things may need to change in #7620 ...

**Comment by dianamartin** [comment]
Brian checked in with me today and asked if the things we talked about changing were going to happen. I said we'd probably want to wait until we all talk on 11/10/21. 
- I did mock up a primary corridor and secondary corridor tracking in the `TEST | Austin Transportation Data Tracker | 11 June 2021`
  - won't delete that until AMD approves the concept and it's built in the PROD environment

**Comment by dianamartin** [comment]
- Reference spreadsheet in `app_AMD_DATA_TRACKER\Signal_Retiming`

**Comment by dianamartin** [comment]
To Do:
- [ ] create new `corridor` object 
  - [ ] Set up (many to many) connection w/ signals
  - [ ] Set up (many to many) connection zone (one zone to many signal)
- [ ] create new `zone` object
- [ ] New Field in signal object field called `last retime date`
- add ability set all of these things to signal details/edit
- create (hidden for now) new corridor page for signal engineers

**Comment by dianamartin** [comment]
## Added section in Signal Details for 
![image](https://user-images.githubusercontent.com/21112975/142288378-802d2704-6189-468a-b1ba-9ab7876bb08d.png)

## New Corridor Retiming page
![image](https://user-images.githubusercontent.com/21112975/142290130-aaddf3e2-327f-4167-bb3c-5895529869bc.png)

- Created new page for "corridor-retiming", need to show stakeholder for feedback
- Messaged Brian
>Hey, check this out (included screen shot of Signal Details with corridor info)
>- here's the prototyped corridor page. 
>- we still have to figure out how you guys want to track the actual retiming data

**Comment by dianamartin** [comment]
@amenity we probably need to schedule another stakeholder meeting to figure out how stakeholders are going to track the actual re-timing efforts

**Comment by amenity** [comment]
@dianamartin - thanks! I'm confused though... 🤪 Would that discussion actually be scoping #2669? cc/ @johnclary

**Comment by amenity** [comment]
@dianamartin is going to demo to stakeholders tomorrow.

**Comment by dianamartin** [comment]
Meeting again with stakeholders on 12/3, will get confirmation on whether or not we want to retire old page and move forward with new prototype page.

**Comment by dianamartin** [comment]
We talked with stakeholders at AMD Project Prioritization meeting. Stakeholders said they still need to meet internally to decide what they will do. For the time being they want to track as is. @amenity correct me if I'm wrong here.

**Comment by amenity** [comment]
@dianamartin - Thanks for the reminder. I am good to call this issue closed based on all the work you've put in.

**Comment by dianamartin** [comment]
@amenity it's not live in Data Tracker yet. At least I don't have a button for the users yet.

**Comment by amenity** [comment]
This is prototyped and users have seen it.

**Comment by dianamartin** [comment]
I just added a button 3/8 on the AMD Data Tracker Home Page

Add to AMD Data Tracker

[Signal Re-timing Systems](https://atd.knack.com/amd#systems-retiming/)
- Remove "Isolated" from "Corridor Name" field
- Grouped Corridor (New line to Comma Separated)

Status: Change from 
- PLANNED - Set as default
- READY FOR DATA COLLECTION - Removed this
- WAITING FOR EVALUATION
- COMPLETED - Renaming TIMING COMPLETED
- DATA COLLECTION COMPLETED - New Status

Brian also added a new request today related to this
