### ISSUE TITLE
Update "Journal Voucher" info in AMD Data Tracker - Warehouse Inventory- OCT 20 2021

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#7517]
Van submitted email 10/22

- [x] Spreadsheet emailed from Van month of: Oct 20, 10/20/21
- [x] Number of records being updated: `203`
- [x] Format spreadsheet [(Review instructions)](https://atd-dts.gitbook.io/atd-knack-operations/warehouse-inventory-updating-journal-vouchers-jv-information)
- [x] Spot check Transaction IDs, no JV information before import
  - `13022`
  - `13212`
  - `12942`
- [x] Import records
- [x] Spot check Transaction IDs, no JV information after import[
  - [x] `13022`
  - [x] `13212`
  - [x] `12942`
![image](https://user-images.githubusercontent.com/21112975/138526269-2d0747e2-3d54-4612-b321-16b6ef09616d.png)

- [x] Email Van that update task complete
