### ISSUE TITLE
Create fields in Data Tracker's project object for Moped project IDs

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#7565]
All strings:

- [ ] Moped Project ID
- [ ] Moped Project Name
- [ ] Moped Project Status

**Comment by frankhereford** [comment]
Re #7567, these columns are going to need to be writable via a "view based POST," so in addition to creating these records, a view needs to be created with an un-authenticated API endpoint that can be used to create new records in the projects object.

**Comment by frankhereford** [comment]
Steps taken in Knack's "TEST | Austin Transportation Data Tracker | MOPED DEV - 12 OCT 2021" app: 

* Create short_text field called `Moped Project ID`. Not required. Must be unique. No default value. "Moped's internal ID for a project." as the description.
* Create short_text field called `Moped Project Name`. Not required. Not required to be unique. No default value. "Project name as defined in Moped." as the description.
* Create short_text field called `Moped Project Status`. Not required. Not required to be unique. No default value. "Project status as defined in Moped." as the description.

**Comment by frankhereford** [comment]
POST'ing to `https://api.knack.com/v1/pages/scene_514/views/view_3047/records` using headers

![image](https://user-images.githubusercontent.com/3653206/140800533-12b2999f-944b-4ea6-ab3f-410ac49f0362.png)


```
{
    "field_3998": 124,
    "field_3999": "Frank's New Project Test POST API",
    "field_4000": "Active"
}
```

creates a new record in Knack.
