### ISSUE TITLE
Solution to stop use of "2432" task order, instead use "24ART21" 

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#7614]
> What application are you using?

Data Tracker

> Describe the problem.

Update default TK number to reflect new nomenclature when creating work orders in Datatracker. All new numbers should start with 24ART21 and are replacing 2423 numbers. 

> Is there anything else we should know?

Currently techs can manually reassign work orders but its not ideal. 

> Website Address

https://atd.knack.com/amd#mmc/

Internet Browser: Chrome

> Requested By
Allyson R.

Request ID: DTS21-102930

**Comment by dianamartin** [comment]
We discussed this in our weekly inventory meeting. 
- We talked about potentially solving it by training the techs to stop using the old task orders and user the new task order.
- Idea to add a "Display Name" so that on the task order it is tagged with "DO NOT USE" to alert the technicians to not choose it
- Have back end check box to filter pick list, to hide task orders that are not in use and use as override to the integration script

**Comment by dianamartin** [comment]
- [x] Created new field `Deactivate` - Yes/No
- [x] Batch updated Status = "Active", Deactivate = "No" - `814`
- [ ] Batch updated Status = "Inactive", Deactivate = "Yes" -`1,614`

**Comment by dianamartin** [comment]
@johnclary I'm just trying to remember. Allyson wrote we're overriding `2423`, but is it `2432`?
- 2423 - has `188` records
- 2432 - has `0` records - this is what is on the issue title now..
Which is it?

**Comment by dianamartin** [comment]
@johnclary the only concern I have is the 2423 Miscellaneous Other Tasks that get used. Does Billy and Supervisors have an alternative for those types of things?

**Comment by dianamartin** [comment]
Emailed Allyson, Lance, Billy and Ronnie 11/8
>I’ve prototyped a way we can hide the Task orders starting with `2423` that will be replaced with task orders starting with “24ART21”. I was just wondering because I know that “2423015000 | Miscellaneous Other Tasks” gets used pretty often by various groups. 

at Billy 
>do the technicians have a replacement for this task order, 2423015000 | Miscellaneous Other Tasks in the “21ART21” task order types?
>- I wanted to ask his before I deactivated it. If they still use it, I can manually keep it as “Deactivated” = No and it will still show up for folk. 
>- Please let me know ASAP as this is the only thing that’s blocking me from making the change. 

Ronnie replied
>I believe all but 2 of the "2423" task orders can be closed because there are no pending labor or inventory costs to be posted to them.  There are two that need to remain open due to some pending inventory transactions.  Each of the old 2423 task orders that was still active has a replacement 24ART2 task order.

**Comment by dianamartin** [comment]
Emailed back 11/8
>Hi Ronnie, 

>We have the task orders list and the plan was to add a new field to be able to filter the field for task orders when a user selects one to only show only the ones we want. The task orders will still have their “Active” or “Inactive” statuses in the Data Tracker. I do confirm that I only see the 2 task orders that are in an “Active” status:
•	2423210700, Signal Trouble Calls
•	2423002000, Signal Knockdowns

>I just checked the system again and It seems as though “2423015000 | Miscellaneous Other Tasks” was updated on 11/5/2021 to be “Inactive”. I believe the Comptroller’s list was updated and it finally updated the Data Tracker list. It is possible we had a period of time where technicians were able to select the old task orders, but now they shouldn’t be able to. I can just make sure that the filters are on the task order field are set to show only “Active” ones.

Checked PROD environment and updated work orders>"task order" fields that were missing the filter. 
1. New Work Order form
- [x] Added "Status" = "Yes" filter
2. Work Orders>Edit Work Orders | Mobile
- [x] Added "Status" = "Yes" filter

**Comment by dianamartin** [comment]
I switched the last two task orders
• 2423210700, Signal Trouble Calls
• 2423002000, Signal Knockdowns
to be "Deactivate" = "Yes". 

I'll switch the filters for the task orders from "Status" = "Active" to "Deactivate" = "No". 
1. New Work Order form
- [ ] Added "Deactivate" = "No" filter
2. My Work Order Details - Embedded "Work Details"
- [ ] Added "Deactivate" = "No" filter
3. Work Orders (Technician)>Edit Work Order
- [ ] Added "Deactivate" = "No" filter
4. Work Orders>Edit Work Orders | Mobile
- [ ] Added "Deactivate" = "No" filter
5. Work Orders (Non-Technician)>New Work Order
- [ ] Added "Deactivate" = "No" filter
6. Work Orders (Non-Technician)>Work Order Details>Edit Work Order
- [ ] Added "Deactivate" = "No" filter

**Comment by johnclary** [comment]
@dianamartin can this be closed?

**Comment by dianamartin** [comment]
Stakeholders never replied for any modifications, closing issue.
