### ISSUE TITLE
Set-up scheduled delete of Resource Tracking Logs 

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#7647]
DTS

Create scheduled delete of Resource Tracking Logs
- [x] Write out deletion steps
- [x] GitHub Issue Template
![image](https://user-images.githubusercontent.com/21112975/140553167-49905501-0cda-43d5-b260-582f0da6201e.png)
- [x] Outlook event notification (quarterly)
![image](https://user-images.githubusercontent.com/21112975/140553367-3889d85d-6bc8-479b-a78d-86e7e32ec4b8.png)
