### ISSUE TITLE
Update "Journal Voucher" info in AMD Data Tracker - Warehouse Inventory- NOV 5 2021

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#7678]
- [x] Spreadsheet emailed from Van month of: Nov 5, 2021
- [x] Number of records being updated: `136`
- [x] Format spreadsheet [(Review instructions)](https://atd-dts.gitbook.io/atd-knack-operations/warehouse-inventory-updating-journal-vouchers-jv-information)
- [x] Spot check Transaction IDs, no JV information before import
- `13266`
- `12929`
- `11278`
- [x] Import records
- [x] Spot check Transaction IDs, no JV information after import
  - [x] `13266`
  - [x] `12929`
  - [x] `11278`
- [ ] Email Van that update task complete

**Comment by dianamartin** [comment]
![image](https://user-images.githubusercontent.com/21112975/140768544-b1ac1447-7434-4dd8-9ebf-97b5a5565ca2.png)
