### ISSUE TITLE
Add a new field to the School Zone Beacon Zone data indicate "System" integration

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#7681]
> What application are you using?

Data Tracker

> Describe the problem.

We'd like to add a new field to the School Zone Beacon Zone data that tells us what "System" it is integrated into. 

https://atd.knack.com/amd#school-zone-beacons/school-zone-beacon-zones/

> Describe the outcome you'd like to see when this feature is implemented.

Two options for the new "System" field would be 'Zone Watch' or 'Stratos'. We can provide a list or update the fields ourselves once able.

> Describe any workarounds you currently have in place or alternative solutions you've considered.

None

> Requested By
Lance B.

Request ID: DTS21-102965

**Comment by johnclary** [comment]
@dianamartin this looks like a straightforward ask. Maybe need to confirm w/ Billy B. if this belongs on the zone vs beacon?

**Comment by amenity** [comment]
@dianamartin pointed out that it's probably the MMC who knows where this belongs

**Comment by dianamartin** [comment]
- [x] Checked the `school_zone_beacons` object and currently does not have a "System" field
- [x] Added new field `System` - multi-choice
  - [x] Added choices "Zone Watch" and "Stratos"
- [x] Add "System" to "Add School Zone" form, below "HOP" field
- [x] Add "System" to "Edit School Zone" form, below "HOP" field
- [x] Add "System" to "School Zone Beacon Zones" main table, to the right of "Area", left of "Status"

**Comment by dianamartin** [comment]
Emailed stakeholders
>I’ve added the new field “System” under the “School Zones” object table. You can Add/Edit a system from the forms and see it on the main table. (Inserted screen shots from above)
