### ISSUE TITLE
Project: ATD Executive Dashboard Alpha

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#7700]
Develop a PowerBI [dashboard](https://app.powerbigov.us/links/tQAnbdsvMB?ctid=5c5e19f6-a6ab-4b45-b1d0-be4608a9a67f&pbi_source=linkShare) that provides an overview of our department's performance. 

## Background

The Transportation Department utilizes multiple datasets from multiple sources across multiple platforms to perform analysis. Some data is ingested through an automated process while others are manually loaded into Business Analysis tools like PowerBI and ESRI. The analysis is happening differently for different divisions and teams. The Executive Dashboard proposes to consolidate the data collection into one platform for quick and easy viewing to create consistent and clear analysis. 

## Scope & Deliverables
A dashboard in PowerBI for the Transportation Department that keeps real-time data to perform current analysis of division outcomes and goals.

## Desired Outcomes
Quarterly performance information as well as monthly financial information

## Timeline
- Alpha version Fall 2022
- Version 1 early 2023

## Concepts and references
[Public Works dashboard](https://cityofaustin.sharepoint.com/sites/PW/OPM/PWStat/Pages/SBOReports.aspx)
[Signs & Marking work order performance](https://app.powerbigov.us/groups/me/reports/30965f93-638d-4afa-b079-7cb1d0f5a857/ReportSection653191453343a9767bba?ctid=5c5e19f6-a6ab-4b45-b1d0-be4608a9a67f)

![Screen Shot 2022-09-21 at 1.18.11 PM.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/a02d8b60-14bb-4b31-ae05-8ae808b06613)

[Executive Dashboard link](https://app.powerbigov.us/groups/me/reports/43bfda27-ba5e-4d7b-b523-60789509b2c6?ctid=5c5e19f6-a6ab-4b45-b1d0-be4608a9a67f&bookmarkGuid=ac22587a-2646-4741-bc46-453a0a3b79ef)

**Comment by johnclary** [comment]
@Charlie-Henry we'll use this epic to track all things related to this work. Would you please issues to this epic as they come up?

**Comment by Charlie-Henry** [comment]
[Susanne's signs and markings dashboard](https://app.powerbigov.us/links/3kPXC3SABt?ctid=5c5e19f6-a6ab-4b45-b1d0-be4608a9a67f&pbi_source=linkShare) is in PowerBI and includes data from:

- 311 service requests. She loads data in from an excel spreadsheet monthly. 
- Crosswalk GIS data. Not exactly sure how this is accessed but I believe through an ESRI plugin for PowerBI
- Work orders. From the Socrata dataset (https://data.austintexas.gov/Transportation-and-Mobility/Street-Signs-and-Roadway-Markings-Work-Order-Time-/qvth-gwdv)

She says the dashboard really has evolved to include different tabs/views to reduce reporting headaches and speed things up.

**Comment by Charlie-Henry** [comment]
Leaving this here for later, we'll need the admin to enable web publishing if we are to make this public: [Publish to web from Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-publish-to-web)

**Comment by Charlie-Henry** [comment]
Spoke to Lance B and Allyson R about their MMC dashboards. They use a ton of different datasets both from socrata (data tracker generated) and from outside sources. 

The INRIX segment-level travel time and intersection (signal analytics) data they are using in their COVID-19 impacts dashboard is currently downloaded separately and has to be loaded manually into PowerBI. CTR setting up a pipeline to put this data in Socrata so the dashboards can be automatically updated. 

John is working to get device uptime data into the Data Tracker/Socrata.

**Comment by amenity** [comment]
Peggy is going to attend our team meeting next week to review @Charlie-Henry's SXSW presentation. She'll be able to guide the direction to take things with intended audiences and @patrickm02L will PM the work.

**Comment by amenity** [comment]
Here's the [CoA Compass Power App](https://apps.gov.powerapps.us/play/543b60d5-c5f9-4a5e-bf51-c5cb8924c619?tenantId=5c5e19f6-a6ab-4b45-b1d0-be4608a9a67f).

**Comment by amenity** [comment]
@patrickm02L Please [convert this to a project index](https://atd-dts.gitbook.io/wiki/product-ops/index-issue-specifications#project-issue-specification) so it is represented in our dashboard and reports. 

cc/ @mateoclarke

**Comment by patrickm02L** [comment]
_Original Description_

Near-term tasks:
- [x] Meet with Signs & Markings (Susanne G) to review their current dashboards and metrics
- [x] Meet with Arterial Management (MMC)  to review their current dashboards and metrics
- [x] Meet with ATD Finance to understand their current reporting needs (scheduled for 11/30)
- [ ] Begin to develop a list of key metrics to include in dashboard

**Comment by patrickm02L** [comment]
@maccallump Please create a list of data from the divisions that you want. 

Here's what we have so far...
* Bonds
* ROW
    * Permits
    * Time
    * Traffic Control Plans
* Signals
    * Work order data
* 311

**Comment by Charlie-Henry** [comment]
Peggy mentioned these issues as possible additional tabs for the executive dashboard:

- https://github.com/cityofaustin/atd-data-tech/issues/815
- https://github.com/cityofaustin/atd-data-tech/issues/9876

**Comment by patrickm02L** [comment]
In Planning 10/20/22, Peggy suggested adding End of Year [performance metrics](https://www.austintexas.gov/budget/eperf/index.cfm?fuseaction=home.SearchResults&DEPT_CD=ATD&KEYWORD=) to the dashboard. 

Also from [data tracker.](https://atd.knack.com/amd#performance-measures/?view_1735_filters=%5B%7B%22value%22%3A%22Parking%20Management%22%2C%22text%22%3A%22Parking%20Management%22%2C%22operator%22%3A%22contains%22%2C%22field%22%3A%22field_1939%22%2C%22key%22%3A%2218%22%7D%5D&view_1735_page=1)

**Comment by amenity** [comment]
Alpha launched! We'll be continuing work in #11078 .
