### ISSUE TITLE
Add project types to signal project dashboard and project summary views

### ISSUE THREAD

**Issue by zappfyllc** [cityofaustin/atd-data-tech#7713]
- [ ] Add a multi-select dropdown for "Project types" in the Signal projects dashboard as completed in #7316.
- [x] Add a multi-select dropdown for "Project types" in the Project summary view.

![Summary Page – 5 0](https://user-images.githubusercontent.com/1463708/144162312-5fc03d63-d7d7-43a5-ab8d-e6ca31fb257b.png)
- [ ] Dropdown should contain options from `moped_types` (see #7533 for additional details)
- [ ] Dropdown state/chosen values for each individual project should originate from and be stored in `moped_project_types` (see #7533 for additional details)

**Comment by amenity** [comment]
@chiaberry -added the screenshot I showed you to the issue description. 🙏

**Comment by zappfyllc** [comment]
@amenity I'm placing some context here for why Project Types is many-to-many at the moment based on [your comment in this PR](https://github.com/cityofaustin/atd-moped/pull/483#pullrequestreview-822148031).

Project Types is a many-to-many relationship primarily because of the Interim Mobility Project Database it was derived from, but this definitely does fit for larger use cases moving forward which will involve multiple components (e.g. Shoal Creek) and would allow for groups like AMD to track projects that incorporate multiple components (if they want to group a set of newly "to-be-built" signals with some modifications for a school safety program, for example) even if they are not doing that now.

With that being said, IIRC the way the IMPD works, project type is actually derived by the "project type" of a component, meaning that if a project combines new signal construction, signal modifications, a new bike lane, and a change to a PHB, the "project type" stored at the project level would actually be a reflection of all of the project types of its child components (e.g. Signal - new, Signal - mod, PHB - mod, Bike Lane). This makes sense but introduces some dependencies in the existing mapping and component functionality and IMHO opens up the eventually necessary conversation about how we handle nesting projects under components when one workgroup considers a single component of a larger project to be a project in and of itself.

All of that is to say, I basically split the difference here and decided to conform to the IMPD data model while ignoring all of the logic governing project type and component type, which are two interrelated (and maybe even redundant in some situations) entities. But that is something we will want to address in Moped v2.0.
