### ISSUE TITLE
Connected Cases Feature in TDS Portal

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#7714]
### I'd like the connect cases feature to work/look/behave the same across all 3 mods in the TDS Portal. 
- _Tracy_

**Tasks**

- [x] Connected Cases should live under the project description
- [ ] Add the feature to Development Review mod
- [x] Development Reviews should be able to connect to both TIA & TDA
  - Currently is connected to TIA Connected Cases
- [x] TIA & TDA should be able to connect to Development Review, but don't need to be able to connect to each other
- [x] For Development Review & TDA, the `Connect Cases` button should look identical and be on the same place on the case details page.

**Comment by ChrispinP** [comment]
Built in Test:

TDR Case Details

- Connect Cases button & Connected TDA and TIA fields in Case Details
![image](https://user-images.githubusercontent.com/67915167/145882803-abe8ec3f-cf43-4628-b146-49697e64d1bc.png)

- Connected fields hidden if blank 
![image](https://user-images.githubusercontent.com/67915167/145882876-48a9cedb-349a-4007-83b3-2572dfda8ad0.png)

- Connect Cases form 
![image](https://user-images.githubusercontent.com/67915167/145883053-0c440e89-99f5-479b-b010-b2620256c659.png)

- TDR Reviews PM Table includes Connected case fields and allows inline editing 
![image](https://user-images.githubusercontent.com/67915167/145883432-67dfc6f3-4fac-4bba-a55d-7ca3b1652aa6.png)

Listed elements applied to TDR mod above would apply to TDA & TIA mods

**Comment by ChrispinP** [comment]
Connected Fields created in Prod for TDR object 
![image](https://user-images.githubusercontent.com/67915167/145898231-83e1b66f-da3f-45bb-9b2b-08ad3c88c6f2.png)

Display rules and forms updated for TIA & TDA if they were not correct.

This is ready for Prod. @TracyLinder 

@dianamartin I'm thinking we should leave the table values unlinked since selecting the cell would both navigate to the page and open the inline edit popup. thoughts?

**Comment by dianamartin** [comment]
@ChrispinP I agree, in the table un-linked. In the details widget can be linked for easy navigation.
