### ISSUE TITLE
[Meeting] Maintenance Work Order Discussions

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#7822]
### Participants
Organizer: Renee 
Participants: BC, Billy, Jorge, Ed, Ivonne, John, Amenity, Diana

### Agenda
Add agenda here or create agenda from [this template](https://docs.google.com/document/d/1d_49KW5C_vSz8Bs50v-cxyIJuTNJMwMrh7ypcxRHgZI/edit#) and add link. 

------
- [x] Schedule meeting
- [ ] Optional: Schedule debrief
- [x] Meet and take notes
- [ ] Optional: Debrief with DTS team members
- [ ] Create resulting issues

**Comment by dianamartin** [comment]
## Diana's Notes
- Better follow-up tickets for deficiencies
- Work Order pick-lists - Brian VDW meeting
  - separately, but are related

**Comment by amenity** [comment]
Goals for revised Data Tracker work orders:
- People like Signs & Markings work orders
- Want better data instead of free text fields
- Have the ability to identify deficiencies in the system for follow up projects

Three types of follow-ups
- Short term - Billy’s team will handle
    - 183 & Montopolis - contractor cut through cable, sent technician out to assess, made temporary repair instead of replacing entire stretch of cable on his own 
- Mid-term - plan for it but not urgent
    - Signal pole is damaged but not in danger of to fall over
-  Long-term - 
    - Intersection with broke conduit underneath roadway; not sure when we would be able to; work will be done by contractor

BC: New type of tracking for damaged assets?

Major pain-point: Engineer work needs to be broken down into work orders and added into queue with ongoing maintenance work

**Comment by dianamartin** [comment]
The meeting series expired. I re-created the meeting series so that I can control if I need to move meeting dates and things since I heard that Renee may not be able to manage the meetings after June.

**Comment by dianamartin** [comment]
5/2: Last time we meet we went in depth on the AMD workflow looking at the schedule work v. trouble call work. We said we'd need to schedule some time with the specific work groups to scope out and redefine what they need in terms of work order functionality. 

This meeting 5/2, I play to demo the new work orders for Trouble Call v. Schedule Work (from Test env). Also, talk about moving over the table, building out slowly the work order page.

**Comment by dianamartin** [comment]
## Add Attachment/Image
- Make it similar to understand - add file formats

**Comment by dianamartin** [comment]
# Meeting 5/24
## Follow-up
- [ ] Brian C: Decision about "no inventory used" and keeping quantity of "no inventory used" in the system

## Update
- [ ] Allowed all "amd work groups" to have access to all items on the components list, for Completed Work section

## In Progress
- [ ] Need to test Edit Form, to make sure all things are working
- [ ] Show Trouble Ticket? - showed on 5/16
- [ ] Show Schedule Ticket?  - showed on 5/16

**Comment by dianamartin** [comment]
# Testing Scenarios

1. Submitted: Supervisor needed to return
Assigned: Returned to Tech to re-do
- Status: In Progress 
  - Technician: updates work order (Quantity changes, material change, add, cancel)
  - More information in description

**Comment by dianamartin** [comment]
# 6/27
- [ ] Brian C: Decision about "no inventory used" and keeping quantity of "no inventory used" in the system
# 9052 - was discussed on 5/31 with dev to see if it is possible.

**Comment by dianamartin** [comment]
# 7/20
Talked to Ronnie about 
>Decision about "no inventory used" and keeping quantity of "no inventory used" in the system

Ronnie said he didn't think that would impact inventory, but said to confirm it would be "Non-Financial" and "0" Unit Cost. 
- [x] Added to Finance and Purchasing as new Inventory Item
- have to wait for it to refresh in Data Tracker tomorrow

**Comment by dianamartin** [comment]
# 8/10

## Status Update
### AMD Technician Work Orders 
  - help guides created
  - NEED TO DISCUSS: Edit Work Order form 
  - NEED TO DISCUSS: Follow-up Work Order form 

### Demo: Reassignment script
- 

## Discussion: 
- Edit Work Order page - update layout
- Follow-up Work Order form 
- Contractor Work Orders 
- Work Orders for other AMD work groups

**Comment by dianamartin** [comment]
# 9/7
## Status Update
Completed this: # 10131

**Comment by dianamartin** [comment]
# 9/7
## Status Update
Completed this: #10131

**Comment by dianamartin** [comment]
# Next Time 
Discuss: 
Work Orders - No Location

**Comment by dianamartin** [comment]
Had cancelled old meeting series and replaced with meeting series for Friday occurrences. Wanted to focus on the AMD work order roll out before moving into more contractor discussions.

New meeting series 

# 10/7
## Reviewing 
- AMD Work Order discussions 10/3 - Billy, Jorge, Ed, Brian
- AMD scheduled work follow-up 10/6 - Diana
- AMD follow-up enhancement 10/7 - John

**Comment by dianamartin** [comment]
This was the epic I used to track stakeholder meetings. We can either close it or create a new one.

**Comment by ChristinaTremel** [comment]
Synced with Diana and this reoccurring meeting ended at the end of 2022. Closing this issue out!
