### ISSUE TITLE
Discovery Day June 2022

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#7823]
### Prep checklist
- [x] Schedule brainstorming & HH
- [x] Prep Miro board
- [x] Follow-up with Peggy on ordering food
- [x] Schedule stand ups Friday
- [x] Schedule closing ceremonies/presentations
