### ISSUE TITLE
Update "Journal Voucher" info in AMD Data Tracker - Warehouse Inventory- Nov 2021

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#7825]
Van emailed 11/23
>Hi John,
Please update the JV Date, JVD ID# and Status Complete for the November entries in the attached file.

- [x] Spreadsheet emailed from Van month of: Nov, 18 & 22, 2021
- [x] Number of records being updated: `87`
- [ ] Format spreadsheet [(Review instructions)](https://atd-dts.gitbook.io/atd-knack-operations/warehouse-inventory-updating-journal-vouchers-jv-information)
- [ ] Spot check Transaction IDs, no JV information before import
- [ ] Import records
- [ ] Spot check Transaction IDs, no JV information after import
- `13684` - JV Date 11/18
- `13131` - JV Date 11/18
- `13067` - JV Date 11/18
- [x] Email Van that update task complete
- John emailed Trish, Van, Dan
> Done. Trish, you should see new TXNs ready for you.
