### ISSUE TITLE
[EPIC] TDS Portal Dec 2021 Upgrade 

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#7875]
### Tentative go-live is Dec. 27th. 

Documentation [here](https://docs.google.com/document/d/1t1xMsJdxESkJtlHkU_K9crM4AvP89GlFLp8NkSx5yjk/edit?usp=sharing)

**Comment by TracyLinder** [comment]
#6288 
#4624 
#7873 
#7714 
#5657
#6869

**Comment by TracyLinder** [comment]
### Mtg w/ Stakeholders 12/7/21

**Reviewer Dashboard**
- Implement a page rule so users only see the tables based on user roles/permissions. 
- Move completed work to it's own page & add a button to the dashboard. 


**Lead Reviewer** - Stakeholders asked that it be auto-assigned to the user that creates the record, with the ability to update it later as needed. 

**Review Cycle Status'**
- Update values to: In Review, Comments Submitted
- Default value should be In Review when cycle is created. 

**Vision Reviewers we can talk to:** Mike Scofield, Dipti, Jonathan Lammert
- [ ] Tracy to schedule mtg w/ them

- Sangeeta asked how we can better re-assign reviews for situations when a staffer is out on extended leave. Diana said we can look into that.

**Comment by dianamartin** [comment]
## Diana's Notes
- Name change "Development Reviews" change to "TDR"

## TDR Reviews page
- Create `TDR Display Name` - "Site Plan | Project Name"
- Have TDR start using "Lead Reviewer" field
  - [ ] Add ability to pull from "Created By" to set the "Lead Reviewer"
- Move buttons to stand alone menu above "+New Case"
- [ ] Close Review cycle - "Comment Submitted"
- [ ] Update Review Cycle Status: "In Review", "Comment Submitted"
- Default value "In Review" upon creation

## TDR Case Details
- Don't need "Case Reviewers", just lead
  - [ ] Add to "Edit Case Details & Notes"

### Review Cycles
- Remove "Review Cycle Metric" fields since only 2 statuses

### Review Cycle Details

### Review Cycle Comments Details
- New page, didn't exist before
- Click "Begin Review" - pops up comment box

## TDR Reviewer Dashboard
- [ ] Implement page rule so only user roles for their section 
  - TIA user role only see their tables
  - TDR user role only see their tables
- [ ] Move Completed Work to stand alone page

## Area Case Load
- Configured "Development Case Load" pivot table
- Configured "Reviewer Case Load" pivot table

## Action Item - Tracy
Feedback from Vision Reviewers
- Mike S., Dipti B., Alison M., Rose, Jonathan L.

Send cases to alternate person
- Long term (extended period)
-

**Comment by TracyLinder** [comment]
**Mtg w/ Vision Reviewers is scheduled for Friday 12/10 @ 11am.**

**Comment by dianamartin** [comment]
# Diana's Notes - "Discuss TDR Mod Updates" - 12/10/21

Update to TDR Reviews Mod in 

## Dipti's comment
>Comments close if interrupted, don't get saved - Need a "Save" button
>Click "Review Complete", but not gone to the deadline. - Recommendation, have "edit" button available until deadline date passes
- Accidentally, said "Not-Recommended", had to email a Reviewer
- Sangeeta: typically waits until all comments are entered
- Dipti asked for longer than 7 days review, but it seems like the business days would be nice rather than normal days

Review Cycle Status: "Under Review", "Comments Sent"

## Diana's Observances
- Need to change the "peach" colored background `In Draft`, the color is so illegible 

## Chrispin's Demo
Vision Reviewers Point of Contact
- Shows "Review Cycle Details" page
- PMs can assign Vision Team 
- Assigned 5 vision teams to review cycle
- Shows "TDR Comment Details"
 - has notification messages to alert user what they need to do
Steps
 - Start Review - captures time stamp
 - Edit Review Comment (Rich Text field)
 - [ ] Change from "Submit" to "Save Changes"
 - Will be in "In Draft" status until user click "Review Complete"
 - [ ] Will change so that user can edit even if the clicked "Review Complete"
 - Edit Attachment button - Update Attachment Types?
 - [ ] Remove Attachment Type

Mike's Q: When does the deadline actual happen, 
- We confirmed it's 12:00 am on that date

**Comment by TracyLinder** [comment]
### 12/10/21 Discovery w/ TDR Reviewers

Dipti: I need to be able to save draft review comments. 
Dipti: I have no idea of editing a comment after I've submitted 'review complete'. I need to be able to edit the comment up until the review deadline. She also needs to be able to update the review comment status.

- [ ] Update Review cycle comments table: do not allow edits if the deadline has passed or if Review Cycle Status is 'Comments Sent'
- [ ] Remove 'Attachment Type' from reviewer comment table & attach form. 
- [ ] Add an attachment table to the TDS Comment Details page

**Comment by ChrispinP** [comment]
Completed all action items and updated associated rules or views as necessary.

**Comment by TracyLinder** [comment]
Per Chrispin, this is all ready to push to the prod environment. The 'push' will take about a day to complete. 

I will send an email to TDS informing them that updates begin this thur & fri ... ask them to choose a SPOC to report bugs & report directly to us through Friday of next week. Let TIA folks know their dashboard will change.

**Comment by TracyLinder** [comment]
**Stakeholders Notified**

- Email just sent to power users.

**Comment by TracyLinder** [comment]
### Mtg w/ Stakeholders 1/4/22
_Allison, Amber, Mike, Chrispin, Tracy_

Vision Team Dashboard - Assigned Work:
- There are 3 links to 3 pages that must be used to find all info

They need to see these to do their job: 
Attachments: Cycle specific & review specific
Review cycle details
Everyone else's comments
For iterative cycles, to see past comments

Mike: I may need to read through all previous review comments. Is there a way to do this without having to open each review individually? Allison agrees. 

**Needs:**

Update assigned work table with one link to a page that gives them everything if possible
A page that is a one source for reviewers (review comment page)

- [ ] Attachments: Cycle specific & review specific
- [ ] Review cycle details
- [ ] Everyone else's comments
- [ ] For iterative cycles, to see past comments

**Comment by TracyLinder** [comment]
### Update & Closing

Updates went live on Dec 27th. Bugs have been resolved and the update is stable.
