### ISSUE TITLE
Feature: Relocate the UI element that is used to initiate a project synchronization from Moped to Knack's Data Tracker

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#7929]
Stemming from the review and discussion around [Moped PR #455](https://github.com/cityofaustin/atd-moped/pull/455), various team members have suggested that the user-interface element that is used to trigger a synchronization of Moped project data to Data Tracker in Knack out of the Project Menu Dropdown be changed. I believe the most recent direction would be to transform it into a button which initiates and indicates the state of synchronization. This button would be found on the Project Summary Page, and could also be used to convey the state of an ongoing synchronization, as requested in this issue: cityofaustin/atd-data-tech#7927.  

@mateoclarke suggested that I spin off the various enhancements which had come to light from the discussion around [PR #455](https://github.com/cityofaustin/atd-moped/pull/455), and this is certainly one of the most forward-facing ones. I remain happy to take a stab at picking the right element and its parameters to fill this role, but I would be more than eager to take direction on how best to design that user interaction and messaging to the user. 

cc @johnclary @zappfyllc @amenity @patrickm02L, as you each have been involved in some or all of these conversations.

---

**Acceptance criteria**

- [ ] Remove synchronization entry from Moped Project dropdown menu.
- [ ] Add a new element to the Project Summary page to initiate a synchronization. 
- [ ] Convey the state (as in, we've done a synchronization in the past, or not) of the project with this page element.

**Comment by frankhereford** [comment]
This issue is a duplicate of https://github.com/cityofaustin/atd-data-tech/issues/7777. Closing in deference to it.
