### ISSUE TITLE
[BUG] Need location information for "WRK21-133020"

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#7963]
Brian C./Willard
AMD

Emailed
>I think we are going to need your assistance with this one. Can the three of you find some time together and determine how to get this resolved.

Originally brought to light bc Willard and Ronnie were discussing that fact that a work order didn't have a Location Name on it. Ronnie asked if it could be edited. Willard said he couldn't edit since he moved groups. 
- Willard got permission from BC and Billy to get "Tech Lead" access
- I looked into the issue, was a school zone issue
- The SZ had not Location ID associated to it, we recently changed that someone can add a school zone now, but the "Location ID" was missing from the add/edit forms. 
- [x] Added missing fields
- [x] Corrected the "Overton" School zone with the Location ID from the School Zone Beacon
- [x] Updated the 3 (AMD Edit forms) with the ability to associated a SZ, SZB and DSDD

**Comment by dianamartin** [comment]
Emailed stakeholders
>
