### ISSUE TITLE
Need a way to "Void" an invoice

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#7994]
> What application are you using?

Shared Mobility Operations

> Describe the problem.

Need a way to "Void" an invoice so I can provide documentation to finance and the providers

> Describe the outcome you'd like to see when this feature is implemented.

Will be able to track voided invoices.

> Describe any workarounds you currently have in place or alternative solutions you've considered.

We do not currently have a process in place for the knack invoices but will probably write void on them and send them to finance.

> Requested By
Andrea M.

Request ID: DTS21-103175

**Comment by dianamartin** [comment]
Sync'd with Andrea - 12/15
we talked about this issue and tested a few scenarios out. 

- [x] Added a new choice field `VOID` for "Invoice Status"
- [x] Added Rich Text for "VOID" on "Invoice" page
- [x] Added Page Rule to only show the "VOID" text when status is "VOID"
![image](https://user-images.githubusercontent.com/21112975/146588186-dbba8124-1a50-4690-84fd-2ae2bfc009e9.png)

Showed it to stakeholders today - 12/17
