### ISSUE TITLE
Align on timeline template workflow for new projects

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#8010]
Pre-populate timeline based on project type
- Add "Project type" drop down (on signals table and "Summary" tab) to the "New project" screen 
- Add support in existing new project mutation for the pre-population of milestones based on type

@zappfyllc's [thoughts](https://github.com/cityofaustin/atd-data-tech/issues/7993#issuecomment-996000848): 
> I'm guessing we would need to add another table to the database for something like moped_project_templates and have it store a template name, references to the project types the template will impact (or whatever attribute we choose), and then relate that template to a given project so we can create the list of phases upfront. If we want to keep the pattern consistent with our previous requirements of entering a "Potential" phase for every newly created project, we could create a placeholder "Default" template that does just that, but this would only be if it simplified the refactoring needed to happen to support the overall feature.

**Comment by amenity** [comment]
@mateoclarke  is going to schedule a discussion with @chiaberry and @amenity so that we can go into next week's backlog grooming with a shared idea of strategy and scope for this. 

@amenity - please attach Renée's latest spreadsheet here.

**Comment by amenity** [comment]
From Renée:
> Attached please find the proposed milestone template for new signal and new PHB projects.
>
> If the user has the ability to remove unneeded milestones from the list, this template will probably work for signal and PHB mods projects as well.
>
> I’m sure we will have some tweaks along with way, but at least it’s a start.  Please let me know if you have any questions or wish to discuss.

[Signal Project Milestones_040622.xlsx](https://github.com/cityofaustin/atd-data-tech/files/8636559/Signal.Project.Milestones_040622.xlsx)

**Comment by amenity** [comment]
![image](https://user-images.githubusercontent.com/1463708/167475876-b9fd2c86-12f8-4410-a867-9d1b2f64a75a.png)

**Comment by chiaberry** [comment]
Here is the current list of milestones in moped_milestones
- [ ] Unknown
- [ ] Award
- [ ] Bid open
- [ ] Cabinet set
- [ ]  COA-hosted community engagement
- [ ] Concrete construction end
- [ ] Concrete construction start
- [ ] Construction contract award by Council date
- [ ] Construction contract execution
- [ ] Design Notice-to-Proceed
- [ ] Environmental field work complete
- [ ] Environmentally cleared
- [ ] Feasibility study
- [ ] First advertisement
- [ ] Initial field visit complete
- [ ] Issue COA striping work order for striping
- [ ] Issue DO for construction
- [ ] Markings construction end
- [ ] Markings construction start
- [ ] Notice-to-Proceed
- [ ] Other community engagement
- [ ] Permit approved
- [ ] Preliminary schematic complete
- [ ] Resurfacing complete
- [ ] Resurfacing or marking removal due date
- [ ] Resurfacing requested
- [ ] Resurfacing start
- [ ] Set up task order
- [ ] Signal construction end
- [ ] Signal construction start
- [ ] Study complete
- [ ] Submit ESPA
- [ ] Survey complete
- [ ] Work order submitted

**Comment by chiaberry** [comment]
notes from meeting: 
Proposed MVP solution
1. on the new project page, pick 1 project type (and only 1 project type)
2. behind scenes mutation to create milestones based on template

Questions / Issues
- [ ] we will need more templates for the other types
- [ ]

**Comment by mateoclarke** [comment]
_Here is the scope we decided on for the implementation of our MVP Timeline Template:_

## Timeline Template MVP

1. Add a the "Project Type" field to the "New Project" page `moped/projects/new`
    - This field should be single-select (unlike on the Project Summary page where it is a multi-select field)
1. Using Renée/Ivonne's excel sheet above to implement 1 hardcoded `SignalAndPHBMilestoneTemplate`. 
    - this `SignalAndPHBMilestoneTemplate` would only get appended to the standard `addProject` mutation when the `project_type` field is one of these four types:
        - new signal
        - new PHB
        - signal mod
        - PHB mod
     - make sure the mutation also updates the `project_milestone`'s `milestone_order` field using the order provided in the Excel sheet.
1. Update the Projects Timeline page `/moped/projects/:id?tab=timeline`, Milestone table to use the `milestone_order` field as the default sorting for the table display. (We'll address drag & drop reordering in a future issue)


## Other notes from the discussion:

**Ordering of milestones is important**
- eventually we want drag and drop UI to reorder
    - standardized order is important for phases but different departments may not have the same order, especially with sub phases
- how should phases/milestones be ordered in the dropdown select (alphabetical) vs in the table display (manual sort order column)?

**Subprojects**
- once implemented, how will subprojects and their types complicated milestone templates?

**Visualizations with Gantt chart**
- Ideally, we'd present milestones in a view (Gantt chart?) thats more like a standard project timeline or calendar view for viewing milestones and phases within a project. A basic table isn't the best presentation of this data.
- We also envision having a Gantt chart view for all projects.

**Milestone Template implementation options**
- We could implement this first template as hard coded GraphQL mutations or as a proper DB Table with SQL trigger. The DB route would allow for features like admin (non-dev) editing of templates. 
- For now, since we only have one example and since the details of this feature could change, we can implement this as hardcoded front-end code until we see the need to create the full schema and triggers in the DB.

**Comment by mateoclarke** [comment]
Closing this now that we are aligned to do this: https://github.com/cityofaustin/atd-data-tech/issues/9102
