### ISSUE TITLE
Update "Journal Voucher" info in AMD Data Tracker - Warehouse Inventory- Nov 2021

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#8013]
- [x] Spreadsheet emailed from Van month of: 12/16/2021
- [x] Number of records being updated: `187`
- [x] Format spreadsheet [(Review instructions)](https://atd-dts.gitbook.io/atd-knack-operations/warehouse-inventory-updating-journal-vouchers-jv-information)
- [x] Spot check Transaction IDs, no JV information before import
- 14204
- 14101
- 13408
- 13346
- [x] Import records
- [x] Spot check Transaction IDs, no JV information after import
  - [x] 14204 - 600030
  - [x] 14101 - 600030 
  - [x] 13408 - 600031
  - [x] 13346 - 600030 
- [x] Email Van that update task complete

**Comment by dianamartin** [comment]
![image](https://user-images.githubusercontent.com/21112975/146580281-031c6ff7-e2f2-4689-bee1-22bc81cb0dd2.png)
