### ISSUE TITLE
Original Request: ROW Portal Volume Tracking (Darren)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#8018]
### Features to help with fiscal planning. 

1. Would like the UC team to have the ability to know the volume of intake, how many plans received, help w/ staffing & resource planning. He'd prefer to see this in KNACK vs an AMANDA report because KNACK is better, faster, and he'd like to see his metrics all in one place. This will involve an AMANDA integration so it will be a bigger lift. 
2. CSR/311 Request Data .... Would like to see CSR volume data in the ROW Portal, similar to the UC need above. 
3. Perhaps create a new tab on ROW Portal for 'Volume Reporting' (or a better name). Create a page for each reporting category: TCP, UC, 311

**Comment by TracyLinder** [comment]
Discovery w/ stakeholder scheduled for 3/31/22 @ 10:30

**Comment by TracyLinder** [comment]
### Discovery Notes

**AMANDA Data:**

**UC Folder**

Formal Distribution Data:
- Cycle # so we can determine how many are initial reviews, and how many are resubmittals. 
- Need to filter by Private / Public / Franchise (We consider CIP to be public)

**311**
- 311 is upgrading their system so the workflow is likely to change soon
- How many CSRs are submitted for each category: (Concerns in ROW, Construction in ROW, Obstruction in the ROW) The date ROW is assigned to the SR, the inspector assigned, resolved date, mis-assigned SRs (should have gone to public works as an example)


CSR workflow: Customer submits online/app/call - 311 assigns to the intake specialist (Alyse R) - can she resolve it herself or does she need to assign an inspector? Field investigation is conducted, the ROW inspector resolves the issue & reports the update to Alyse, then Alyse resolves the CSR (closes it.)



**Q:** What is the priority of this request: --- ASAP w/ deadline of Dec 2022. 

**Next Steps**

- Chrispin to learn from John how to import AMANDA data into KNACK
- Huddle w/ Diana to talk about 311 integration
- Map data sources & write queries (311 w/ Alyse & Paloma)

**Comment by TracyLinder** [comment]
**Backlog Grooming Notes:**

- Let's do PowerBI
- Huddle w/ Diana, Charlie, Chrispin

**Comment by dianamartin** [comment]
# 311 ODP

**Comment by TracyLinder** [comment]
### Huddle Notes

- Diana: 311 data is available on the open data portal
- TCP tracking data is in KNACK. We would need to push data to the open data portal (ODP).
- AMANDA data: Tracy can write the AMANDA queries. 
- 311 data being requested is considered 'activity data' which isn't available on ODP

Charlie:
- Going from KNACK to Socrata is straight forward. 

Tracy:'
- prefer to push AMANDA data to open data portal / not KNACK
    - DSD is already doing this

**Basic Next Steps:**
- Publish AMANDA & TCP data to ODP
- Verify the 311 data Darren wants is in the ODP data. 
- Start building the data set & BI Dashboards


Tasks:
- [ ] (T) Learn how DSD is pushing AMANDA data to ODP
- [ ] (T) Write AMANDA sql for AMANDA data
- [ ] (Charlie) Setup TCP KNACK data to ODP
- [ ] (D) Make a comment on this issue w/ your 311 analysis. How do we get the data we're missing?

**Comment by TracyLinder** [comment]
- I emailed an update to Darren. I told him I'd update him again after our next huddle. 
- Our next huddle is scheduled on 5/3.

**Comment by Charlie-Henry** [comment]
Here is the repo for our Knack -> Open Data Portal data publishing. https://github.com/cityofaustin/atd-knack-services#publish-records-to-the-open-data-portal

Chia, Frank, and Mateo didn't know of a time we did a AMANDA -> Open Data Portal script

**Comment by TracyLinder** [comment]
**Conversation w/ Amenity:**

- This is a project and the creation of a new product. 
- Are we building a new product? We'd be doing iterative updates & maintaining a product. 
- Create a very basic project index. 
- Prioritizing: Charlie will be the hardest to resource. We'll have to ask Peggy. He is our only PowerBi resource right now and has a large backlog. So this must be prioritized among the other PowerBi requests. 
- How does this prioritize among ROW's other work? Is there another backlog issue that we know we can tackle?

**Comment by dianamartin** [comment]
# Update about 311 Data 

Emailed stakeholder 5/2
>Thanks for syncing with me today, 5/2. Per our discussion, I’d send you a copy of the data points our stakeholder, Right of Way (ROW), is looking to report on: 

311 Data points:

•	How many CSRs are submitted for each category: (Concerns in ROW, Construction in ROW, Obstruction in the ROW)
o	This can currently be answered using the dataset: https://data.austintexas.gov/Utilities-and-City-Services/Austin-311-Public-Data/xwdj-i9he
o	Filtering by “SR Description”
•	The date ROW is assigned to the SR,
o	Potentially answered by this dataset: https://data.austintexas.gov/Utilities-and-City-Services/Austin-311-Public-Data/xwdj-i9he
o	“Created Date”
•	the inspector assigned,
o	I believe this can be answered by the related Activity records
•	resolved date,
o	Potentially answered by this dataset: https://data.austintexas.gov/Utilities-and-City-Services/Austin-311-Public-Data/xwdj-i9he
o	“Closed Date”
•	mis-assigned SRs (should have gone to public works as an example)
o	I believe this can be answered by the related Activity records to send to “311 Feedback”

**Comment by TracyLinder** [comment]
### Huddle #2 5/3/22


Tracy:

Charlie:
- Yup, has a backlog.
- TCP KNACK data isn't on ODP but there are other KNACK data on ODP so we know it's possible. 

Diana:
- Will post her notes as a comment

**Comment by TracyLinder** [comment]
I spoke w/ Darren about this and asked him to choose his next highest KNACK priority for us to work on while this awaits prioritization amongst Charlie's other work. 
- Darren chose #8378

**Comment by amenity** [comment]
Will open a new issue with a specific use case if and when the need arises.
