### ISSUE TITLE
Create scripts to migrate Data Tracker projects to Moped

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#8067]
Create scripts which import Knack Data Tracker projects into Moped.

I've opened [#510](https://github.com/cityofaustin/atd-moped/pull/510) which is a work in progress.

- [x] phases/subphases/status
- [x] work assignmen ID
- [x] contract
- [x] contractor
- [x] purchase order number
- [x] signal components
- [x] project notes
- [x] task orders
- [x] project type
- [x] eCapris ID (ready but waiting for AMD feedback)
- [x] funding - unit (ready but waiting for AMD feedback)
- [x] funding - fund (ready but waiting for AMD feedback)
- [x] funding - source (ready but waiting for AMD feedback)
- [x] funding - program (ready but waiting for AMD feedback)
- [x] project sponsor (ready but waiting for AMD feedback)
- [x] project team
- [x] create a script which updates Knack record with Moped project ID
- [x] target construction start - no data
- [x] target construction end - (excluding this but will log what can be done manually - 7 records)
- [x] create project files index so that we can manually upload them
- [x] updated at - excluding this because it will be overwritten by database events
- [x] create a report that summarizes any fields/values excluded from migration (a handful of units and funds)

**Comment by johnclary** [comment]
Questions for AMD:
- would you like to add subproject IDs before I migrate?
