### ISSUE TITLE
Build CSR Pages for SMRT

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#8088]
After the main 3 SR tables are build out
The process of building the pages/tables/forms for the Service Request details

- [x] Main Service Request page & table
- [x] Service Request Details page
- [x] Embed web map
- [x] Activity Form
- [x] Activity Table
- [x] flex notes - modal page

**Comment by patrickm02L** [comment]
Diana is going to give @ChrispinP a walk through for future training or incase he needs to take over. Diana is also working on documentation.

**Comment by dianamartin** [comment]
Chrispin and I plan to get together on Friday afternoon to go into detail about CSR tables and page components.
