### ISSUE TITLE
Refine JavaScript related to Moped Project ➡️  Knack Data Tracker

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#8213]
This issue is a spin-off from the work related to #7925 and PR [#522](https://github.com/cityofaustin/atd-moped/pull/522). 

John provided a set of really helpful recommendations on how to improve this code. They include:

* [x] Utilize the known knack ID for a signal as found in the JSON stored in the moped DB. 
  * Caveat: Doing so complicates testing this in development vs. production as the IDs stored are from production data tracker. 
* [x] Simplify the building of the Knack request payload. Just build up everything we know in Moped and ship it to Knack. No harm in overwriting a value with the same value.
* [x] Make sure all field key values for knack columns are abstracted into the environment. No magic numbers! **This is required for a production release.**
* [x] Move hooks as high as possible in the component 
* [x] Refactor `Promise.reject()` into a `throw`n exception
* [x] Remove explicit use of `Promise.resolve()` and just return a value; they compile up to the same and it's more readable.
* [x] Remove `forwardRef()` from this new component; not needed like it was in the drop down.
* [ ] Utilize `await` and `async` to simplify the knack sync method

**Comment by amenity** [comment]
@frankhereford - should this be in Review/QA?

**Comment by frankhereford** [comment]
> @frankhereford - should this be in Review/QA?

I think this is good to close. I'm going to do so - thank you for pointing it out. This refers to work that went into the PR that got merged this morning. Thanks @amenity!
