### ISSUE TITLE
Mock up AMD Work Order (new structure)

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#8224]
At our last Problem Found/Action Taken pick list meeting we discussed what it would be like to have a new work order structure specifically for a particular work group.

**Comment by dianamartin** [comment]
I said I'd try to mock one up based on SMD's work orders to keep with a streamlined design also one that external requesters are familiar with.

**Comment by dianamartin** [comment]
Feedback from meeting 1/24
## WEEK 1
Separate ticket for Trouble Calls
Separate ticket for Scheduled Work


Trouble Call Type - one selection
  Change - List 
Scheduled Work Only
  Still in a table

+ Link to put Moped Project?
+ Commenting Feature in work order

*** Do not hide blanks

## WEEK 2
-Preventative Maintenance Tickets 
- mock up like a DOSA
- Field: PM'd By
- Field: There is a PM? Y/N
+ PM Report Page

**Comment by dianamartin** [comment]
Sync'd w/ Billy - 1/25
Asked him if technicians need to have the ability to add Trouble Calls & Scheduled Work and he confirmed that they did. He also confirmed all the elements that are on the existing work order should remain on the work order. 

- The Call Back/OCP - can create Trouble Call ticket during non MMC business hours and general operation tickets (Scheduled Work). 
- Technicians not on Call Back/OCP shifts can create general operation tickets any time of day, but are required to contact MMC if they notice a trouble call during MMC business hours. 

While configuring the mock pages, the "Scheduled Work" table has been challenging to incorporate into a new work order. It seems to make sense to add it on the details page once the work order has been created. 

Will be experimenting creating a `preventative_maintenance_tracking` object table (mirrored like the DOSA).

**Comment by dianamartin** [comment]
## Preventative Maintenance Feedback
- All things are **REQUIRED**
- Things need to be added or modified
- Remove school zone stuff?
- Use display rules to show/hide

Frank: See if there is a follow-up
- Monitor is an important thing
- Using Follow-up is an old process, not what they're doing for the contractor

Brian C: 
Want to see more options when it comes the PM fields
- Multiple Choice
- Radio 
- Drop down

### PM Assets
- Intersection & PHBs
- Monitor
- BBS
  - Battery Voltage
  - 
- School Zones

- [ ] Move "Asset Type" to the top
- [ ] All "Asset" fields should all be REQUIRED
- [ ] Scheduled Work choice removed
  - Call-Back (Test Monitors and Cabinets)
  - On Call Person (OCP)

**Comment by dianamartin** [comment]
New Fields for PM
- Monitor Replaced - Y/N
- 12 Month (no categorize)

PM School Zones Fields
- `Communication` - Y/N/ Intermittent
- `Check terminal strip connections` - Y/N
- Update fields OK, REPAIR, N/A
- `Check Speed Limit and Cell Phone signs` - Y,N, N/A
- Move Solar Power and AC Power together

**Comment by dianamartin** [comment]
For Attachments
- used existing object `work_order_signals_images` 
- [ ] Added new field `Attachment` (file type)
- [ ] Added new field to existing "Add Image" form
- [ ] Added new table on Work Order Details page
- Fields: Attachment, Date, Attached By

**Comment by dianamartin** [comment]
Edit Work Order (My Work Orders - OG)
![image](https://user-images.githubusercontent.com/21112975/155358667-84466641-9ecb-4916-b887-b0fc53fbaef8.png)

Edit Work Order (Work Order - Technicians)
![image](https://user-images.githubusercontent.com/21112975/155359251-54d789de-2066-45b7-9f83-e59a60917436.png)

**Comment by dianamartin** [comment]
@dianamartin Do the feedback modifications for AMD work order mock up

**Comment by dianamartin** [comment]
Brian C. emailed work order red-line PDFs on 3/7
Started to review 3/11

# Remarks Screen 1
## Already On-Site? field 
>Is this needed
## Assign to Self? field
>Not needed Tech will assign themself
-[ ] Need to remove display rule for this
  - SELF ASSIGN is YES
  - TECHNICIAN LEAD - to logged in account
  - ASSIGNED DATE to current date

## "Work Type" field
>Not needed. This will be determined by the Work Ticket opened.
- Based on work order designed this will open the type of ticket

## "Trouble Call Type" field 
>Move below Signals
- I'm confused, I thought this would be removed bc we're removing the "Work Type" field

# Remarks Screen 2
## Move "Signal" - ID under "Location Name"
![image](https://user-images.githubusercontent.com/21112975/157986784-b4b2b937-5af5-4142-809a-e4728cce019d.png)

## Financial Information section
>Move "Task Order(s)" above "Fund" field
- [ ] Move "Task Order" field

## Work Requested By
>re. "MMC", I never added this data. Where did it come from?

**Comment by dianamartin** [comment]
# Notes 3/21

3/21
Feedback 

Signal Attachment/Image - showing
Signal Details

Main Work Order page
- Add "Follow-up" is "Yes"
- Trouble Call, Scheduled

Close Work Order
- Add field "Supervisor Comment"

Time Log
- Require - Technicians
- Require - Vehicle

Make Time, Inventory, Work Completed 
- Menu button, modal pop-up

Already On-Site 
- Remove this button for now, archive field

Assign to Self
- Remove this button for now, archive field

Work Requested By/Work Requested By
- Reported By - Trouble Call
- Requested By - Scheduled Work

WORK ORDER STRUCTURE
- My Work Orders
- All Work Orders
- Work Orders - Technicians
- Work Orders - Comm
- Work Orders - Signal Timing
- Work Orders - Inspectors
- Work Orders - Contractors

Revisit Reassign Work Process

**Comment by dianamartin** [comment]
Primarily worked on making:
Make Time
- [x] converted from embedded form to menu button, modal pop-up
Inventory
- [x] converted from embedded form to menu button, modal pop-up
Work Completed
- [x] converted from embedded form to menu button, modal pop-up

**Comment by dianamartin** [comment]
## "Save/Submit Work"
- No Inventory is needed

## Follow-up
- request follow-up first
- then submit

**Comment by dianamartin** [comment]
- [x] Worked on AMD workflow - 4/12

**Comment by dianamartin** [comment]
After 5/2 meeting, will close this issue because meeting notes and feedback will be captured under #7822
