### ISSUE TITLE
Update "Journal Voucher" info in AMD Data Tracker - Warehouse Inventory- JAN 2022

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#8245]
- [x] Spreadsheet emailed from Crystal month of: JAN 14-18
- [x] Number of records being updated: `390`
- [x] Format spreadsheet [(Review instructions)](https://atd-dts.gitbook.io/atd-knack-operations/warehouse-inventory-updating-journal-vouchers-jv-information)
- [x] Spot check Transaction IDs, no JV information before import
- `14311` 
- `13789`
-  `13604`
-  `13597`
- [x] Import records
- [x] Spot check Transaction IDs, no JV information after import
  - [x] `14311` 
  - [x] `13789`
  - [x] `13604`
  - [x] `13597`
- [x] Email Crystal that update task is complete

**Comment by dianamartin** [comment]
Emailed stakeholder - 1/24
>The JVs have been updated. Here is the filter for the updated records.
> - Let me know if you have any questions.
