### ISSUE TITLE
[Enhancement] Update links to Data Tracker on "Project Summary" tab

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#8251]
### Existing "Data Tracker signal IDs" field:
![Screen Shot 2022-01-24 at 2.15.45 PM.png](https://images.zenhubusercontent.com/5a5f8dc94b5806bc2bc322a5/d2e53aed-9315-4d62-b1b0-1675999ba661)
- [x] Rename "Signal IDs" 
- [x] Update "Synchronize" text to "Synchronize with Data Tracker" 
![Screen Shot 2022-01-24 at 2.24.53 PM.png](https://images.zenhubusercontent.com/5a5f8dc94b5806bc2bc322a5/e6c72323-1599-4660-b7eb-99d333b05e4d)
- [x] Once synced, display signal IDs like we do on the "Signal projects" page instead of link 
![image.png](https://images.zenhubusercontent.com/5a5f8dc94b5806bc2bc322a5/6c577d1f-557c-4b6e-a74e-2532e7caabe6)

### New link to work orders list 
![Moped - Summary.png](https://images.zenhubusercontent.com/5a5f8dc94b5806bc2bc322a5/d117f589-2f61-4235-a2a0-f726c1184873)
- [x] Add a "View in Data Tracker" link using the pattern below (with encoded JSON):
```
https://atd.knack.com/amd#work-orders/?view_713_filters={"match":"and","rules":[{"field":"field_4133","operator":"is","value":<project_id>}]}
```

See example links [here](https://github.com/cityofaustin/atd-data-tech/issues/8249#issuecomment-1022467455).

**Comment by johnclary** [comment]
> Add link to a list of the project's work orders in Data Tracker

@amenity the URL pattern for this link will be

```
https://atd.knack.com/amd#work-orders/?view_713_filters={"match":"and","rules":[{"field":"field_4133","operator":"is","value":<project_id>}]}
```

Note that the json will need to be encoded.

**Comment by chiaberry** [comment]
@amenity , what do you want the work order link to say if the project hasnt been synced with data tracker yet? (If the project has no knack project id associated with it)

**Comment by amenity** [comment]
I couldn't think of anything besides showing the same "Synchronize" link again, but it wouldn't look great. Chia and Mateo suggested hiding the element altogether if it hasn't been synced and I think that will look cleaner and work great.
