### ISSUE TITLE
Configure Production Data Tracker for Moped integrations

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#8263]
- [x] Restrict “Projects” page access to `System Administrator` role only
- [x] “Projects” menu item should go to https://mobility.austin.gov/moped/dashboard
- [x] Update "Projects" section of Signal Details pages to point to Moped: [Before](https://user-images.githubusercontent.com/1463708/150925375-3bb29a97-26b1-470f-a23b-04f54a074cec.png) | [After](https://user-images.githubusercontent.com/1463708/150925065-92a066cb-8aa8-4580-8780-ccc6e913152f.png) (does not need this excessive amount of spacing, tho!) Use a list instead of a table to render the link. Sort by project ID newest to oldest. 
- [x] On [Work Orders page](https://atd.knack.com/amd#work-orders/), rename "Project ID" column "Project" and update links to point to Moped using a text formula field `https://mobility.austin.gov/moped/projects/[Moped Project ID]` 
- [x] On [Work Order details page](https://atd.knack.com/amd#work-orders/work-order-details/61b8f0419fbb8a00213606e1/), rename "Project ID" row "Project" and update links to point to Moped using this same text formula

**Comment by amenity** [comment]
This will take @johnclary an hour. Will want to schedule a maintenance window for it.

**Comment by amenity** [comment]
@johnclary - please review this to-do list ... @frankhereford - please add the list that you've already prepared here.

**Comment by johnclary** [comment]
@amenity this is done. let me know if i can tweak anything.

also, test out the "Projects" link on the top nav. it's built with a page rule that redirects you to Moped. alternatively we could write a tiny snipped of custom JS that turns that nav link into an external link.

**Comment by amenity** [comment]
Remove the "New Project" button on the "Signal Details" page.
![Screen Shot 2022-02-10 at 9 10 02 PM](https://user-images.githubusercontent.com/1463708/153532224-3fb484be-6855-4b57-9e1f-23dc29a63601.png)
![Screen Shot 2022-02-10 at 9 09 55 PM](https://user-images.githubusercontent.com/1463708/153532229-bc411b70-49b8-4c3f-ba2a-e55f5c105da3.png)

**Comment by amenity** [comment]
This "Projects" breadcrumb takes me to the Data Tracker "Projects" page on its own little island without a menu to other Data Tracker. 
![Screen Shot 2022-02-10 at 9 16 53 PM](https://user-images.githubusercontent.com/1463708/153532620-6fc86b06-fba9-44c4-a037-031ef8c52f15.png)

Can we use this other URL to get a different breadcrumb? 
![Screen Shot 2022-02-10 at 9 25 00 PM](https://user-images.githubusercontent.com/1463708/153533192-8942df4a-490e-4f44-992e-6cfb34b0e383.png)

.

**Comment by johnclary** [comment]
dang—yes, the link in moped should use this instead:
```
`https://atd.knack.com/amd#signals/signal-details/<knack_signal_record_id>`
```

**Comment by johnclary** [comment]
> Remove the "New Project" button on the "Signal Details" page.
Done.

**Comment by amenity** [comment]
Perfect, thanks!

**Comment by amenity** [comment]
Issue for the link fix here: https://github.com/cityofaustin/atd-data-tech/issues/8455
