### ISSUE TITLE
Project: DTS Service Delivery

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#83]
## Description
Design and document processes the DTS team can use to intake, manage, and deliver services.

### Resources
- [Project Folder](https://drive.google.com/drive/u/1/folders/1nAzamPSCveOHjGf2Pj70MFlFOtZitpow)
- [Draft Workflow Diagram](https://www.draw.io/#G1qPEKQG9LyTcbrmIdR7qjlcAEGcJ55y2R)
- [Project Templates](https://drive.google.com/drive/folders/1Sio1YZkUCPoWP5NtZ_oDcfZnoq6zx6f1)
- [Project Overview Presentation](https://docs.google.com/presentation/d/1xlkXrsygvql9YOi_DVKldWdUB2Dm8sYmTure9glm6Bg/edit#slide=id.p)

**Action Items**
- [x] A - Create ~Project Parent~ Epic label
- [x] All - Collaborate on intake form fields #193 
- [x] T - Setup meeting w/ Amenity to keep working on this later this week
- [x] J - [Create issue for Mateo to look at pushing github project info to transportation.austintexas.io](https://github.com/cityofaustin/transportation.austintexas.io/issues/245) 
- [ ] Define 'Triage' and the tasks involved
- [ ] Define which services are 24/7, if any
- [ ] Further define what should happen during 'Review/QA'
    * What does 'User Acceptance Testing', 'Usability Testing' mean to the team?
- [x] Form submission confirmation message (1 for severe issues, 1 for everything else)
- [x] Create a template for the email sent to customers after they submit an issue in the portal
    * All form submission confirmation emails should include some sort of 'What to expect' message to the customer.
    * Link it to the github issue, which can't happen until the issue is assigned to the correct repo
- [x] Figure out how severe issues will be quickly & easily identifiable, both in GH and in the email confirmations
- [x] Make sure that the default status of new GH issues is 'New Issue' - Be sure before implementing new procedures.
- [x] Add a new pipeline for 'Discovery/Scoping'
- [x] John would like work groups to get some type of monthly update on their backlog & the work we're doing for them. #468
- [x] Implement a quarterly department prioritization & collaboration communication. Inform customers of their backlog, among other info to be identified.  #688
- [x]  Test what happens to a GH issue link after the issue is transferred to a new repo.
- [x] Add to project workflow: assign a PM before the ~~intake~~ kickoff meeting. 
- [x] Gather standard discovery meeting questions from John & Diana (questions they want asked at all intake meetings). #469 
- [x] Create some type of formal discovery meeting artifact docs(s). #470

**Comment by TracyLinder** [comment]
**My Existing Notes**
=
**Questions, Topics & Tasks**
- Define the apps we support and don't support. 	Generally, all ATD IT support will be provided by DTS, and DTS will determine if escalation to CTM if needed.
-    ○Exceptions: Voice Services, Computer Password Reset, applications we don't support…
- Q: Hours of service coverage?
>A: 8-5
- Q: Reports to guarantee in the SLA? 
- Q: KPI's? 
- Q: How do we confirm w/ the customer that we're building exactly what is needed? 
- Q: Should different apps have different SLA's? 
- Q: Who should be managing the product owner backlog? How often should we meet w/ product owners to groom their backlog? 
- Q: Do we have automated request due dates? If we do, how do we assign a due date to something in the backlog?
- Q: How can our end users have access to their backlogs?    
****

**Service Request Urgency Ratings**
1. Critical Issue Severely Impacting Service
   1. Triage, creation of a plan of action, and communication with customer - 4 Hours or Less 
      a. Plan of Action - Either us escalating it, or beginning development 
   2. User updates &  communication goes out as needed 
   3. Update the customer each business day 

2. Minimal Loss of Service - BYPASS AVAILABLE
   1. Triage, creation of a plan of action, communication with customer - 24 Hours or Less 
      a. Plan of Action - Either us escalating it, or beginning development 
   2. User updates &  communication goes out as needed 
   3. Update the customer each business day 

3. User Request/Problem Not Affecting Functionality (all enhancement requests)
   1. Triage in 24 hours
   2. User Story & Work Estimate - 2 Weeks
   3. Prioritized in Backlog Meeting - 1 Month
   4. Moved to Active Work - Dependent on Customer
   5. Write Technical Requirements & Perform Development

**Comment by amenity** [comment]
Definition of a "Project":
 - 

Each Project should have: 
- Top-level description
- Want

**Comment by TracyLinder** [comment]
[Notes](https://docs.google.com/document/d/1V4XfnfQRsNph2m_OYIQwNNzL33tEERCnxrFwLTdcJnI/edit#heading=h.3wwi07wxshj)

**Comment by TracyLinder** [comment]
Just a note to myself & @amenity to think about adding a "maintenance/stabilization" step to the product manager Workflow.

**Comment by TracyLinder** [comment]
@amenity - Look at my last comment on this... it's the term I couldn't think of during our meeting today about 'waiting to see if anything breaks before closing the issue' :laughing:

Also, I think it would be best to track tasks in the description of this issue, instead of on the meeting notes doc. So I moved them over a few minutes ago (scroll up). Let me know if that works for you. 

I also updated the description to add a resources section, with a few more resources.

**Comment by johnclary** [comment]
Hey, so, let's get meta. This feels like a "project", and thus needs an index issue. This seems like the right issue to become an Index.

As I started looking at our new "Projects Overview" workspace, it occurs to me that I'd prefer to err on the side having more index issues rather than fewer. E.g., if an epic will span multiple sprints, it's probably big enough be a Project with a capital P. Going to sleep on that thought...

**Comment by johnclary** [comment]
also, what are your opinions about tagging people in issue comments? if the people who i want to read my comment are assigned to the issue, should I tag them in a comment? is there a downside to tagging people? @amenity @TracyLinder

**Comment by amenity** [comment]
I say tag people, don't see a downside. I don't know a lot about the GH notification settings, but I suspect that tagging people has a higher likelihood of them getting an email. 
If people complain they get too many emails or aren't seeing things, we could look at something like [this](https://zapier.com/apps/github/integrations/slack/11499/get-direct-messages-on-slack-for-new-github-mentions).

**Comment by TracyLinder** [comment]
### Update

This project is near 60% complete. Currently we are working on finishing the service delivery road map diagrams, creating project document templates, and updating the customer submittal forms.

**Comment by TracyLinder** [comment]
Important Note: For the purposes of Service Delivery, we will refer to the Apps, Dev, and Geo/Map groups as *Builder*.

**Comment by amenity** [comment]
**Status update**
We have soft-launched the service request form along with some of the templates and processes that will be fundamental to the new delivery workflow. We're excited to loop our new Product Manager in to the project and work with them to fine-tune and roll out the workflow to the team and our customers.

**Comment by amenity** [comment]
**Status update**
During our [Product Ops Work Sesh](#880), we documented a proposal for a v1 of the DTS Product Ops Workflow. We will be sharing it with team leads and preparing for implementation in the coming weeks.

**Comment by amenity** [comment]
**Status update**
- We've are in the process of running our backlog of products and projects through a [prioritization rubric](https://docs.google.com/spreadsheets/d/1jIioQwPmXKJ-8SpJBc-x4hr6la6bS_zg_R8LF85Mdlw/edit#gid=473810243) and will be presenting that assessment process and the resulting prioritized project list for feedback at an upcoming ATD Managers Meeting. 

- We're transitioning into our new scrum ceremony cadence with Wednesday starts to our sprint cycles and the introduction of Sprint Retros and Backlog Grooming.  

- After much discussion, we have decided on the following revised Github repo structure: 
     - All issues in atd-data-tech, migrate old issues
     - Code will remain in their respective product/project repos
     - Consolidate all of the knack repos into a single `atd-knack` repo with subfolders for each application

**Comment by amenity** [comment]
**Status update**
- We [completed prioritization of our current and backlog projects](https://docs.google.com/spreadsheets/d/1o0Q_xIx0c1njAg6opnAJwyCIhAkU7W-hK_7P8jgMCug/edit#gid=0).
- We [presented our methodology to the ATD Management Team](https://github.com/cityofaustin/atd-data-tech/issues/812)
- We [consolidated all of our project management into the `atd-data-tech` repo](https://github.com/cityofaustin/atd-data-tech/issues/1038)

Up next, we'll be meeting with a group of managers to review our prioritization framework and begin [documenting our service delivery workflow](https://github.com/cityofaustin/atd-data-tech/issues/668) in our new wiki.

**Comment by amenity** [comment]
@TracyLinder @johnclary - are you good with calling this closed? We can always make new issues as they arrive.
