### ISSUE TITLE
Request to add vehicle models/name for vehicle tracking

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#8376]
> What application are you using?

Signs & Markings Operations

> Describe the problem.

Need to add a couple vehicle models and a vehicle name for vehicle tracking. We would also like to make the vehicle "name" editable in the edit window because we are going to clarify which trucks are bucket truck and which trucks are signs trucks in the tracker. 

https://atd.knack.com/signs-markings#manage-vehicles/

> Describe the outcome you'd like to see when this feature is implemented.

Models to add:
- Bolt EV
- Ram 1500

Vehicle Name to add:
- Sign Truck

> Describe any workarounds you currently have in place or alternative solutions you've considered.

None needed.

> Requested By
Christina T.

Request ID: DTS22-103445

**Comment by amenity** [comment]
@dianamartin - for you for whenever

**Comment by dianamartin** [comment]
Sync'd with Christina - 2 /9
- [x] Renamed Vehicle Model to Vehicle Make
- [ ] Updated Vehicle Display Name
- [ ] Reordered field in add and edit form
- [ ] Made Vehicle Make and Vehicle Name editable on the edit form
- [ ] Enabled "Add new option" to Editable form
