### ISSUE TITLE
Delete deprecated project columns in Data Tracker

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#8449]
- [x] Delete deprecated columns

🧹 **Only** keep the following columns:
- Name
- Signals (connection)
- Modified Date
- Moped Project ID
- Moped Project Status
- Moped URL (text formula)
- Moped Project Link

- [x] Delete (the old) "Projects" page
https://builder.knack.com/atd/amd/pages/scene_1202

- [x] Delete Project_attachment object

First make a backup!
