### ISSUE TITLE
Create new test instance of Data Tracker and point Moped staging to it

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#8466]
The prod and Moped test versions of Data Tracker have drifted. The task is to:
- [x] Clone prod Data Tracker
- [ ] Dev update Moped env variables to use the new Data Tracker test instance in staging
- [ ] Delete the old Moped test version of Data Tracker

**Comment by ChrispinP** [comment]
New Test instance for Data Tracker: [TEST | 25 FEB 2022 | DT | Austin Transportation Data Tracker](https://builder.knack.com/atd/test--25-feb-2022--dt--austin-transportation-data-tracker)

**Comment by ChrispinP** [comment]
@amenity moving back to On Deck for Dev Team

**Comment by johnclary** [comment]
thanks @ChrispinP !

**Comment by amenity** [comment]
Thanks, @ChrispinP ! @frankhereford - you good to take this one?

**Comment by frankhereford** [comment]
@amenity  - you bet, I'll get the app updated to point to this instance.
