### ISSUE TITLE
Onboard IT BSA Sr (Apps) 

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#8480]
Our new app analyst starts on 8/19! Here's my list from our last go-round:

### Accounts
- [x] Submit a [CTM Transfer Employee Request Form](https://atx.service-now.com/sp?id=sc_cat_item_guide&sys_id=b714eb12db7a3f0021ccef92ca961972&sysparm_category=ea848d3adbce37405b03f482ba96193c) for a COA network account, eAccess PIN/HR Portal, and phone 
- [x] Submit a CTM service request to add to DTS Distribution Email Group 
  > Add "First Last Name" to email distribution list "ATD Data and Technology Service" \([ATDDataTechnologyServices@austintexas.gov](mailto:ATDDataTechnologyServices@austintexas.gov)\) and "ACE ATD DL"
- [x] Add to City of Austin Slack - `austininnovation.slack.com`_- need to switch to City email 
- [x] Add to DTS Google Drive _- need to switch to City email_
- [x] Have them sign up for [Gitbook](https://app.gitbook.com/@atd-dts/s/dts-service-desk-knowledge-base/onboarding/general#gitbook-wiki) 
>She might have to change her email later
- [x] Add to [Austin Transportation Github Team](https://github.com/orgs/cityofaustin/teams/transportation/members) 
- [x] Add to [DTS Team Slide](https://docs.google.com/presentation/d/1tHKTfUgQ-uAXdRBkEdXqR7ryBo_LTU86IzQxo1gJoeA/edit#slide=id.gc64f254bde_0_91)
- [x] Add to 1Password

## Software
- [x] Zenhub Extension
- [x] Docking station driver

## Hardware — DTS Systems Admin
Coordinate with DTS System Admin \(Scott\), make sure there is enough lead time for equipment to be acquired.
- [x]  Laptop
- [x]  Monitors
- [x]  Chair 
- [x]  Power supply
- [x]  Keyboard
- [x]  Mouse
- [x]  Docking station
- [x] Badge
>She's going to City Hall at 1 pm to get her badge, has temp badge right now

## Communications
- [ ] newsletter announcement | 
- [ ] email to Cameron Rd employees | 

## Calendar invites 
- [x] App Sync - Diana
- [x] Monthly Team Meeting — John
- [x] Sprints — Amenity
- [x] Sprint Ceremonies — Apps/Dev: Amenity; Geo: John 
- [x] 1:1 — Supervisor
- [x] First day: DTS Team Orientation — John
- [x] First Week: DTS Product Ops — Amenity

**Comment by dianamartin** [comment]
I think it's safe to say she's on-boarded and gotten all the technical set-up behind her
