### ISSUE TITLE
Archive the data and take the AWS resources down

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#8492]
- [x] Postgres db instance
- [x] GraphQL API (Hasura cluster)
- [x] PostgREST API
- [x] delete contents of S3 bucket for raw data and secrets
- [x] PG dump of current database

_Set a reminder to revist in 5 years for records policy retention._

**Comment by mateoclarke** [comment]
@johnclary Did we do this yet?

**Comment by johnclary** [comment]
we did!
