### ISSUE TITLE
Update public MDS dashboards and datasets

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#8493]
The following places need to have a message about the retirement of our MDS data support. 
- [x] https://data.mobility.austin.gov/micromobility-data/
- [ ] https://micro.mobility.austin.gov/
- [x] https://data.austintexas.gov/Transportation-and-Mobility/Shared-Micromobility-Vehicle-Trips/7d8e-dm7r

Can link to Ride Report once that's available. 

This should be done by March 1.

**Comment by amenity** [comment]
Unless we expect people to be confused/frustrated by the retirement of our dashboard, I'm fine with a simple redirect.

**Comment by johnclary** [comment]
sounds good to me—thanks @mateoclarke!

**Comment by mateoclarke** [comment]
John has now added this language to the Socrata dataset:

> Effective March 1st, 2022, this dataset is no longer maintained. For current micromobility data, please refer to our 3rd-party data provider’s dashboard: https://public.ridereport.com/austin

**Comment by mateoclarke** [comment]
I've put in a request via ServiceNow to redirect the https://micro.mobility.austin.gov/ URL to https://public.ridereport.com/austin.

I'm also advising PIO that they should update language on this website:
https://www.austintexas.gov/sharedmobility
