### ISSUE TITLE
SMS Sprint Review Meeting 2/25/22 updates for SMRT

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#8574]
Things to update in SMRT

- [x] Goat license cost defaulted to $1500.00, should be $0. Change amount
> License Cost was `$1500`, I changed it to `0`
![image](https://user-images.githubusercontent.com/21112975/156625796-18f96f3b-b140-4f3f-8c20-858c8fb59abc.png)
- [x] Remove impound table from the Home page
- [x] Connect invoice to the impound table under the Fee/Payments page
  - [x] added `Permit`, `Monthly Trip` and `Impoundment` connection fields on Edit Invoice Item form
  - [x] added display rules on the Edit Invoice Item form
- [x] Create a form on the Bonds page to account for Fees in Lieu 
![image](https://user-images.githubusercontent.com/21112975/156643934-8236fcd1-eb71-49ef-8cd0-b92f28d6d29c.png)
![image](https://user-images.githubusercontent.com/21112975/156644113-890b1281-3466-4922-bf11-72bf65fc7df8.png)

**Comment by dianamartin** [comment]
Will follow-up with SMS staff this week and see if this is good to go.

**Comment by dianamartin** [comment]
followed up with user 3/22, messaged them
>[1:44 PM] Martin, Diana
Hey Andrea, just checking that the last update I made to SMRT was all good with you? the last message I sent you on 3/3
