### ISSUE TITLE
WRK22-138325
doesnt show the location or map on the WRK. The intersection # is entered (821). Just n...

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#8585]
> What application are you using?

Data Tracker

> Describe the problem.

WRK22-138325
doesnt show the location or map on the WRK. The intersection # is entered (821). Just no location or map on the WRK.

other WRK for that intersection show just the location (intersection name) while others show the location and map.

WRK22-138705 has a similar issue. intersection 645.

Internet Browser: Chrome

> Requested By
Billy B.

Request ID: DTS22-103540

**Comment by amenity** [comment]
@dianamartin - can you take a look at this?

**Comment by dianamartin** [comment]
Looking into WO WRK22-138325 & WRK22-137605

**Comment by dianamartin** [comment]
WRK22-140865 - LOC20-017265

**Comment by johnclary** [comment]
We have rules configured on [this page](https://builder.knack.com/atd/amd/pages/scene_634/views/view_1681/form/rules/record) to set the location ID, but in the case they did not work as expected when Frank set the signal asset for this record.

**Comment by dianamartin** [comment]
## Testing 
- Created work order from "Work Orders | Technician" page w/ NO asset - Chose "Other/No Asset"
  - DSDD asset type was showing up
  - [ ] Need to update display rule for (New Work Order)
- Work Order created without Location - `WRK22-138650`
- Clicked "Edit Work Order" 
- Selected "Asset Type" - `Signal`, no. 165
  - Hazard Flasher is showing up 
  - [ ] Need to update display rule (Edit Work Order)
- Location Name does not show up!!!

@johnclary looks like this is broken in AMD Data Tracker PROD since this test env is fairly recent (Jan 31 22)

**Comment by dianamartin** [comment]
## Corrections
- [ ] Added to display rule no.10 (WORK_TYPE_TROUBLE_CALL is "Other")
  - [ ] Add - Hide/Show - dsdd

**Comment by dianamartin** [comment]
Messaged stakeholder 3/8
>I was able to fix the [Bug] WRK doesn't show the location or map in Data Tracker, when a user creates a work order without an asset and then edits and adds an asset. We had some wonky display/record rules in there. It should be fixed now.
