### ISSUE TITLE
Update "Complete" status on migrated Data Tracker projects

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#8593]
- [ ] Run a query for [John or Chia plz advise] on the read replica database and export as CSV — Frank
- [ ] Share CSV with AMD and align on what the data _should_ be — John & Amenity
- [ ] Update production database accordingly? — Frank

**Comment by amenity** [comment]
This won't be necessary, see https://github.com/cityofaustin/atd-data-tech/issues/8457#issuecomment-1055841623
