### ISSUE TITLE
Remove all of the prepopulated search criteria

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#8648]
> What application are you using?

Data Tracker

> Describe the problem.

On the following page, can you remove all of the prepopulated search criteria

[Advanced Search Signal Work Orders](https://atd.knack.com/amd#work-orders/advanced-search-signals/ )

> Describe the outcome you'd like to see when this feature is implemented.

The removal of all of the prepopulated search criteria

Advanced Search Signal Work Orders

- [x] Remove _"Work Type" = "Trouble Call"_
- [x] Change _"Status" contains "Assigned"_ to "_Status" is any_
- [x] Change _"Followup Needed" to "Select"_

> Describe any workarounds you currently have in place or alternative solutions you've considered.

Need to manually unselect items

> Requested By
Brian C.

Request ID: DTS22-103570

**Comment by amenity** [comment]
@dianamartin @johnclary - do you remember why we set these up? I sized this as a 1 optimistically hoping that we no longer need them.🤞

**Comment by dianamartin** [comment]
@amenity I think this was the way things were configured on the page. We'll have to see if we can remove the defaults, I'm pretty sure you can

**Comment by amenity** [comment]
Checked with Billy and he said he doesn't use the page often. So let's try to remove these so users have a clean slate when they visit the page.

**Comment by dianamartin** [comment]
Removed default selections for advanced search fields

## Updated Advanced Search
![image](https://user-images.githubusercontent.com/21112975/157159579-1d1dd6be-e253-4f80-b806-b5c69a2dcae4.png)
![image](https://user-images.githubusercontent.com/21112975/157159601-99e46227-d589-4adb-81aa-671e29518147.png)

Will email/message user on 3/8

**Comment by amenity** [comment]
Thanks, @dianamartin!

**Comment by dianamartin** [comment]
Emailed stakeholders 3/8
>Hey everyone, 

I wanted to let you know that the “Work Orders – Advanced Search” page was updated to remove all the pre-populated search criteria. See below screen shot. 

**Updates Made**
>• Remove "Work Type" = "Trouble Call" 
>• Change "Status" contains "Assigned" to "Status" is any 
>• Change "Follow-up Needed" to "Select"
> Let me know if you have any questions or additional modifications
