### ISSUE TITLE
[Data Tracker] Update Journal Voucher Transactions for Warehouse Inventory - February 2022

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#8659]
- [x] Transaction Date Range: 10/14/21 - 02/15/22
- [x] Number of records being updated: 284
- [ ] Format spreadsheet [(Review instructions)](https://atd-dts.gitbook.io/atd-knack-operations/warehouse-inventory-updating-journal-vouchers-jv-information)
- [ ] Spot check Transaction IDs, no JV information before import
- [x] Import records
- [ ] Spot check Transaction IDs, no JV information after import
- [x] Completion Email
