### ISSUE TITLE
Add ATS 662A contract to cost estimate module

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#8661]
On the ["Manage Contracts" page](https://atd.knack.com/amd#construction-cost-estimates/manage-contracts/)
- [ ] Rename existing` 662A | ATS 2016` tab to `662A | ATS (2016)`
- [ ] Add a new contract with [these](https://api.knack.com/v1/applications/595d00ebd315cc4cb98daff4/download/asset/62262cee58199e001ec81927/662a_2022contractextensionbiditems.xlsx) costs, tab should read `662A | ATS (2022)`

### Original request

> What application are you using?

Data Tracker

> Describe the problem.

We need to update item costs for the ATS 662A contract which recently had a 1 year contract extension approved with across the board price increases.  I am attaching a spreadsheet with updated costs.  We will need a new Tab for the "2022 662A Contract Extension" in the Cost Estimate page.

> How soon do you need this?

Urgently — Today or tomorrow

> Is there anything else we should know?

ASAP for cost estimates, DO requests, etc.

---
> Requested By
Erin B.
Request ID: DTS22-103575

**Comment by amenity** [comment]
@dianamartin - I checked with Erin and clarified that getting this is not needed by tomorrow. Getting it done this week is fine.

**Comment by dianamartin** [comment]
On "Manage Contracts" page 
- [ ] Update tab `662A | ATS 2016` to `662A | ATS (2016)`
- [ ] Add a new contract items to `const_cost_items` object table with [these](https://api.knack.com/v1/applications/595d00ebd315cc4cb98daff4/download/asset/62262cee58199e001ec81927/662a_2022contractextensionbiditems.xlsx) costs, tab should read `662A | ATS (2022)`
- [ ] Field `VENDOR_NAME` - need to create new choice `662A (2016)` and `662A (2022)`
  - [ ] Update all `100` records that are `662A` to  `662A (2016)`
- [ ] Create new record on `contract_solicit_vendor` 
  - [ ] `Solicitation_Vendor_Name`: 662A 
  - [ ] `Vendor Name`: ATS 2022 Mobility Bond Traffic Signal & PHB Installation IDIQ? - Check with Erin/Ivonne

**Comment by dianamartin** [comment]
Reviewed spreadsheet and made table/field, page updates. 

Emailed stakeholders, 3/8
>I’ve updated the Construction Cost Estimate tables that the “Manage Contracts” page has been updated based on your request. There is a new tab and the new contract bid items (100 records) have been imported.

![image](https://user-images.githubusercontent.com/21112975/157292646-281baab3-3fec-4dd8-8639-4cece2939845.png)

>Let me know if you have any questions or feedback.
