### ISSUE TITLE
[Enhancement] Annual Signal Retiming Work Plan Management

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#8675]
> What application are you using?

Data Tracker

> Describe the problem.

I would like to add this table to Data Tracker and have the assigned engineer fields and the start date in-line editable and for the ones that could autopopulate to do so based on info already in the Data Tracker, such as Corridors (don't worry about limits for now), signals count and PHB count.  We need one table per year that we would build on over time.

> Describe the outcome you'd like to see when this feature is implemented.

I want to have this amazing Excel table in Data Tracker so Diana and I can smile ourselves to sleep at night.

> Describe any workarounds you currently have in place or alternative solutions you've considered.

I just use the spreadsheet.

> Is there anything else we should know?

End of April as the summer is when we start moving forward on next fiscal year's timings.

> Requested By
Brian G.

[Attachment](https://api.knack.com/v1/applications/595d00ebd315cc4cb98daff4/download/asset/6227de8615c144001ee99257/20222023asrsummary.xlsx) (18.55kb)

Request ID: DTS22-103595

**Comment by dianamartin** [comment]
Planning to sync with user at 4 pm, 3/28

**Comment by dianamartin** [comment]
# Sync Notes 3/28
- showed him the Work Plan page
- he mentioned having a page that shows the zone and the CURRENT YEAR assignment
  - CURRENT YEAR - system/corridors
  - NEXT YEAR
- Keep "Option 1" 
- [ ] Add Start Time to form
- [ ] Add Engineer Name to table "Re-timings"

Will email or sync with changes

**Comment by dianamartin** [comment]
Messaged user 3/28
>Hey, the mock up is ready for your review

**Comment by dianamartin** [comment]
Need to follow-up with Brian

**Comment by dianamartin** [comment]
Brian was still out when I wanted to check in with him - 4/12, will try this week to sync up. 

Lance emailed 4/8, and shared spreadsheet of **Proposed ASR Metrics** with Brian G., Allyson and me. 
>I was waiting to send this to Diana until we had done more discussion internally, but figured I’d go ahead and get us all together to talk feasibility before finalizing the fields.
>- Please let me know your thoughts, comments, etc.

Goldberg replied
>I am on board with these being our metrics.

**Comment by dianamartin** [comment]
## Input
![image](https://user-images.githubusercontent.com/21112975/163055830-7db6c522-c0d8-4488-baba-09d25897393d.png)

## Calc
![image](https://user-images.githubusercontent.com/21112975/163055903-1aa04bfe-b81c-482c-9008-8a63e5697170.png)

## Display
![image](https://user-images.githubusercontent.com/21112975/163055949-26cd2027-a5d3-4cf0-8281-dd5a99609c70.png)

**Comment by amenity** [comment]
@dianamartin - circle back with Lance, Brian optional.

**Comment by dianamartin** [comment]
I emailed  Lance, Allyson, Brian G, Brian C 4/20
>Were we going to meet about the proposed metrics? I took a look at it and wanted to make sure what we were tracking because when I was planning out the new data table for it, I was coming up with a lot of fields to create like 56 and I wanted to make sure that was correct.

**Comment by dianamartin** [comment]
# Diana's Notes
- [ ] New Details page
- [ ] New Edit Form

Keep 
## Data Collection fields
- Data Collection - Before - Start/End
- Re-timing Start/End
- Data Collection - After - Start/End
- Data Collection Notes

Timeline: 
Have it stood up by August!

**Comment by amenity** [comment]
From today's AMD Sprint Review: It would be ideal if this could be completed before re-timing in August. @dianamartin @karo can review with Allyson, Lance, and Brian.

**Comment by dianamartin** [comment]
- [ ] Exported `signal_corridor_retiming`
- [ ] Created new spreadsheet for import
- [ ] Imported spreadsheet
- [ ] Created details widgets and added all field sections

**Comment by amenity** [comment]
@dianamartin met with them yesterday and Lance was wondering why[ the data and performance hub dashboard](https://data.mobility.austin.gov/signal-timing/) wasn't showing the correct numbers because the status and volume numbers weren't being entered. 

She also let them know that we're [planning to deprecate that dashboard](https://github.com/cityofaustin/atd-data-tech/issues/6482#issuecomment-1175235000) as part of #6482 and that we expect that a PowerBI dashboard will be a better option. Lance agreed.
