### ISSUE TITLE
Add "Switch IP" field to Camera Maintenance Priority List so we can easily verify comm while verifyi...

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#8676]
> What application are you using?

Data Tracker

> Describe the problem.

Add "Switch IP" field to Camera Maintenance Priority List so we can easily verify comm while verifying camera operations.
https://atd.knack.com/amd#cameras-maintenance/

> Describe the outcome you'd like to see when this feature is implemented.

Add "Switch IP" field to Camera Maintenance Priority List so we can easily verify comm while verifying camera operations.
https://atd.knack.com/amd#cameras-maintenance/

> Describe any workarounds you currently have in place or alternative solutions you've considered.

have to look at separate lists and it just takes longer

> Requested By
Lance B.

Request ID: DTS22-103600

**Comment by amenity** [comment]
This is complicated since there's not currently a relationship that supports this query. 


However, it may make sense to rework the data structure so that cameras are associated to a **cabinet** in addition to a location.  
- [ ] DTS create an association between the camera and cabinet
- [ ] DTS add column for cabinet switch IP address in the [Camera Maintenance Priority List](https://atd.knack.com/amd#cameras-maintenance/)
- [ ] Update the "Details" and "Edit" pages for cameras and cabinets so that they can be associated
- [ ] Populate _Cabinet ID field_ on camera records by matching _Signals_ to _Locations_ to _Cameras_

**Comment by amenity** [comment]
AR - Not every camera associated with signal, e.g. the one on top of the Austonian. 

BC - Have discussed with John and thinks we could come up with a logic that makes sense.

**Comment by amenity** [comment]
@dianamartin - what would you recommend?

**Comment by dianamartin** [comment]
@amenity I would say we should circle back with Lance to see if he's given this more thought about how the AMD assets should be related. We need to figure out if the "Switch IP" is captured anywhere else already and if we need to associate the cameras to another table to bring in that information.

**Comment by dianamartin** [comment]
## 8/2

Switch IP (Cabinet)
Cabinets are not always associated with Signals 
Cameras are associated to Locations (can be shared to a Signal)

Current Relationships
Cabinets 
  Separate location (X, Y)

Locations
  Signals (Switch IP exists here)
  Cameras

Long Term: 
Locations: 
  Signals
  Cabinets
  Cameras
