### ISSUE TITLE
 Move AMD Work Order Functionality from Test to Production

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#8752]
This issue is to help document what steps are necessary to transition functionality from TEST to PRODUCTION in AMD Data Tracker

**Comment by dianamartin** [comment]
# 10/3
Met with stakeholder (Brian VDW, Billy, Jorge)
- to figure out the timing and the plan to get this ready for go-live

# Changes
## My Work Order page
- [ ] Remove the old table on "My Work Orders"
- [ ] Remove field "Scheduled" on new "My Work Orders" table
- [ ] Move menu for new work order buttons from this page to "Work Order - Technicians"
- [ ] Keep "All Work Orders" button

## Work Order - Technician page
- Move menu navigation here
- Remove "New Work Order" button on second menu

**Comment by dianamartin** [comment]
Made all the necessary changes to production, Closing - 10/7. Training scheduled on 10/12
