### ISSUE TITLE
Creation of 8 new object tables

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#8753]
Add
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/291d825a-0eaf-435f-9d7c-c4e229f1c222)

**Comment by dianamartin** [comment]
## amd_workgroups
- [ ] Auto Increment
- [ ] Workgroup Name - Short Text
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/6837e472-c15a-4d26-a9b6-f1be5031b59b)
Connections
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/abe68549-4b0b-4b70-93d1-f8ae488af437)

**Comment by dianamartin** [comment]
## work_order_signal_components
- [ ] Create object `work_order_signal_components`
- [ ] Get finalized table from AMD staff
- [ ] import table `work_order_signal_components`
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/3c824f61-477d-4041-82ad-b92b14250820)

**Comment by dianamartin** [comment]
## 3. work_order_component_actual
- [ ] Create object `work_order_component_actual`
- [ ] import table `work_order_component_actual`
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/156bb37c-4b71-4c2d-a54f-560bab4b1b09)

**Comment by dianamartin** [comment]
## 4. work_order_signals_component_actions
- [ ] create object `work_order_signals_component_actions`
- [ ] import table `work_order_signals_component_actions`
![image](https://user-images.githubusercontent.com/21112975/159577934-2967e960-db19-4d13-97cc-ec5e8e4f47fb.png)

**Comment by dianamartin** [comment]
## 5. work_orders_signals_scheduled_work
- [ ] create object `work_orders_signals_scheduled_work`
- [ ] get finalized table from AMD Staff
- [ ] import table `work_orders_signals_scheduled_work`
![image](https://user-images.githubusercontent.com/21112975/159578134-5e855245-fcfb-479d-a288-8e5f4949da38.png)

**Comment by dianamartin** [comment]
# 6. work_order_signals_scheduled_work_actual
- [ ] create object `work_order_signals_scheduled_work_actual`
![image](https://user-images.githubusercontent.com/21112975/159578878-d598206b-ff73-4ed0-b1fd-7bca93b48cf2.png)

**Comment by dianamartin** [comment]
## 7. preventative_maintenance_tracking
- [ ] create object `preventative_maintenance_tracking`
- [ ] get finalized preventative maintenance fields 

![image](https://user-images.githubusercontent.com/21112975/159579211-f6b417c7-a1ad-45b5-ac73-41447a60f77a.png)
![image](https://user-images.githubusercontent.com/21112975/159579269-c52f2bbe-f0b4-47ba-833b-8e80713aa2b2.png)
![image](https://user-images.githubusercontent.com/21112975/159579305-74cb5ec3-dcc6-47e0-8568-e94ce3f7b674.png)
![image](https://user-images.githubusercontent.com/21112975/159579425-ea42296f-033a-406a-9b12-a19acd80fc27.png)

**Comment by dianamartin** [comment]
Created new object tables in AMD Data Tracker PROD
![image](https://user-images.githubusercontent.com/21112975/166303688-cda3bb53-0ca2-43c3-a859-ba12c897b74e.png)
