### ISSUE TITLE
MDS ETL Upgrades

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#879]
This is an epic to capture issues related to MDS ETL improvements

Tasks that could/are sub issues:
- [x] Rethink the whole stack, move ETLs to Airflow or some other framework
- [x] break apart data from data-rodeo RDS in new AWS org
- [x] Reimplement with Terraform 
- update code to retrieve data from new providers #878

**Comment by sergiogcx** [comment]
All done here, let's close this epic and focus on new issues with new re-defined epics.
