### ISSUE TITLE
[DT] Delete CSR Flex Notes - May 2022

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#8822]
Received automated reminder to delete flex notes in AMD Data Tracker PROD and reference the Flex Note Archiving wiki

Ran filter on: https://builder.knack.com/atd/amd/records/objects/object_95

Filter:
`ISSUE_STATUS_CODE` contains `closed`
`CREATED_DATE` is `before` 03/01/22 (2 months prior)

Total Records: {value}
To Delete: {value}
New Total: {value}

**Comment by KaroEngstrom** [comment]
T 5/3/22

- [x] Validation check - filtered the csr_flex_notes object to see how many records will be deleted using the following criteria: ISSUE_STATUS_CODE contains closed, and CREATED_DATE is before 3/3/22. 

Total Records: 22468
To Delete: 6956
New Total: 15512

![image](https://user-images.githubusercontent.com/100615928/166461943-fcc88a85-8135-41d1-ac51-491c25dbd424.png)

- [x] Batch deleted with the same filters and verified that the number of records to be deleted was the same:
![image](https://user-images.githubusercontent.com/100615928/166469808-c0d4a383-b913-4b30-88e7-a773de4fe408.png)

- [x] Checked the remaining number of records against New Total (15512):
![image](https://user-images.githubusercontent.com/100615928/166473553-034cc71f-8d1f-4c40-b627-bc66d447617a.png)

- [x] Checked the records for the discrepancy and 13 new records were added during the time it took to complete the batch delete 

- [x] Updated the change log in the app
