### ISSUE TITLE
Update "Journal Voucher" info in AMD Data Tracker - Warehouse Inventory- FEB 2022

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#8844]
Crystal emailed spreadsheet 4/5 

- [x] Spreadsheet emailed from Finance staff month of: FEB 15-16 2022
- [x] Number of records being updated: `284`
- [x] Format spreadsheet [(Review instructions)](https://atd-dts.gitbook.io/atd-knack-operations/warehouse-inventory-updating-journal-vouchers-jv-information)
- [x] Spot check Transaction IDs, no JV information before import
  - `14689`
  - `14380`
  - `13772`
- [x] Import records
- [x] Spot check Transaction IDs, no JV information after import
  - [x] `14689`
  - [x] `14380`
  - [x] `13772`
- [x] Email Finance staff that update task complete

**Comment by dianamartin** [comment]
![image](https://user-images.githubusercontent.com/21112975/161829305-03b50be6-dc90-4c10-a42d-39615eae6efe.png)

Start import: 1:56 pm
End import: 

Email stakeholder
>
