### ISSUE TITLE
[Enhancement] Implement refinements to Work Order Advanced Search

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#8849]
We noticed today that `ASSET_TYPE` filter is not available in the [advanced search for work orders](https://atd.knack.com/amd#work-orders/advanced-search-signals/). 

- [ ] Add `ASSET_TYPE` to [work order advanced search](https://atd.knack.com/amd#work-orders/advanced-search-signals/?view_2133_page=1&view_2133_filters=%5B%7B%22operator%22%3A%22is%20blank%22%2C%22field%22%3A%22field_2080%22%7D%2C%7B%22value%22%3A%22Yes%22%2C%22field%22%3A%22field_1354%22%2C%22operator%22%3A%22is%22%7D%5D)
- [ ] Try changing title and slug to remove the specific reference to signals

### Original request

> What application are you using?

Data Tracker

> Describe the problem.

Ability to search by asset type for work orders or service requests

> Describe the outcome you'd like to see when this feature is implemented.

Ability to search by asset type for work orders or service requests

> Describe any workarounds you currently have in place or alternative solutions you've considered.

N/A

> Is there anything else we should know?

N/A

> Requested By
Allyson R.

Request ID: DTS22-103750

**Comment by amenity** [comment]
Teams message to Allyson: 

> Reviewing your request for searching work orders/srs by asset type. Where were you wanting those filters? I first looked at the main lists for each but they both have filtered search available on every field. 🤔
> - ([Signal) Work Orders](https://atd.knack.com/amd#work-orders/?view_713_filters=%7B%22match%22%3A%22and%22%2C%22rules%22%3A%5B%7B%22field%22%3A%22field_977%22%2C%22operator%22%3A%22is%22%2C%22value%22%3A%22Signal%22%2C%22field_name%22%3A%22ASSET_TYPE%22%7D%5D%7D&view_713_page=1)
> - [(Signal) Service Requests](https://atd.knack.com/amd#mmc/search-mmc-issues/?view_1713_page=1&view_1713_filters=%5B%7B%22field%22%3A%22field_1649%22%2C%22operator%22%3A%22is%22%2C%22value%22%3A%22Signal%22%7D%5D)

**Comment by amenity** [comment]
@dianamartin - Allyson said she spoke to you about this?

**Comment by amenity** [comment]
Talked to Allyson and confirmed that she doesn't need anything for service requests, but we should add "asset type" to the advanced search for work orders.

**Comment by dianamartin** [comment]
Yes, that's what I talked to her about bc I noticed it and I suggested it thinking it would be useful for users.

**Comment by amenity** [comment]
@dianamartin - please check to see whether this page is pre-filtered in any way (it has "signal" in the name and URL, so maybe this explains why asset type isn't available?). 

Also, would be good to understand why "Follow up needed" value must be supplied. We updated that [here](https://github.com/cityofaustin/atd-data-tech/issues/8648) and now it's kind of tricky because no work orders come up unless the user takes it off of "Select" but it's not immediately apparent why. Ideas to address this:
- Prevent the form from submitting without that value (there is a red "required" asterisk, but the form submits), or 
- Make that the first field, on its own line...

**Comment by dianamartin** [comment]
@amenity there was just a setting on the "Follow-up Needed" field I switched off, it was a required value that didn't need to be. 

The table itself is not filtered to any particular "Asset Type"
![image](https://user-images.githubusercontent.com/21112975/162058801-3f680834-3e6e-4cd5-95a0-d68c952afc8d.png)

**Comment by KaroEngstrom** [comment]
4/11/22

- [x] Added Asset Type option to the Advanced Search 

![image](https://user-images.githubusercontent.com/100615928/162798174-3e0de1a1-770d-482e-847d-c59c3ea4f37e.png)

- [x] Added Asset Type column to the results table on the same page 

![image](https://user-images.githubusercontent.com/100615928/162798255-cb846d9f-d0ac-4a72-b123-abcd98bf2cfa.png)

- [x] Contacted the requester via email for QA (with the images above): "Per your request, we added Asset Type as an option to the Advanced Search: We also added an Asset Type column to the results table: Please let me know if this looks good to you."

**Comment by KaroEngstrom** [comment]
- [x] Removed specific reference to signals from the slug and title 

![image](https://user-images.githubusercontent.com/100615928/162834851-05b46413-adde-447e-804c-21b09d2d96df.png)

- [x] Removed signals from the view tag in Knack builder 

![image](https://user-images.githubusercontent.com/100615928/162834902-f4884d8d-90dd-49c3-ba45-3712d287de04.png)

**Comment by amenity** [comment]
Karo reached out to Allyson and hasn't gotten feedback so closing.
