### ISSUE TITLE
[Meeting] SMS Sprint Review Meeting 4/7 - Feedback

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#8865]
### Agenda
Add agenda here or create agenda from [this template](https://docs.google.com/document/d/1d_49KW5C_vSz8Bs50v-cxyIJuTNJMwMrh7ypcxRHgZI/edit#) and add link. 

------
- [x] Schedule meeting
- [ ] Optional: Schedule debrief
- [x] Meet and take notes
- [x] Optional: Debrief with DTS team members
- [x] Create resulting issues

**Comment by dianamartin** [comment]
# Diana's Notes 4/7
## Payment Information section
- 1500 and 750 
- Collect payment at six month term
- Put $750 first then $1500 total over 12 months 

## Eligibility section on Get Started
- [ ] Add bullet, expression of interest form
- TX Sales Tax License

## Application Changes
- Add new field "Adding to Fleet?" - Mary V.
- If "Renewal" - don't show "Initial Fleet" only 
  - "Additional Units" 
  - "Number field"
 
## Add New Fields to App
- Type of device
- Permit Term 
>She will provide choices for these

## Change "Comment" field
 - [ ] from Short Text to Rich Text

# Future Ideas
Renewal - Past Performance reporting
- Grading sheet per provider
  - Number of Trips
  - Impounds
  - Fees Paid
  - how long it takes to pay invoice
  - how long it takes to closing CSRs
  - Unresponsive
  - Not wearing PPE

## Diana's Performance Idea for Attachments
Edit - Approve attachments individually 
- Approve

## Additional Processes
### BEFORE APPROVAL
- Working API feed
- Bond 
- Insurance

### AFTER APPROVAL
- Device Inspection - done after approval
- Take device photos (use Attachments table?)

# NEXT STEPS - Discovery of Attachments
1. Table Creation - SMS app ahead of time
2. Adding attaching attachment one by one
3. Attachments related app

Plan is to create 3 forms that really allow use to test different attachment layouts/structure
- make attachments not required - FOR TESTING
- 5-6 attachments on forms

# Proposed Process
1. Expression of Interest
2. SMS Staff to create account and application
3. Provider create or edits application?
4. Provider then work on attachment requirements
5. Provider to submit application
6. SMS Staff to review application
- In Progress - Pending Action
- In Progress - Complete Action
- Pending Approval - Pending Action
7. Provider finalizes additional requirements (API, Bond, Insurance)
7. SMS Staff to "Approve"
8. Provider get device inspection
9. SMS upload photos of inspection & inspection report
10. Provider receives license
