### ISSUE TITLE
Update "Journal Voucher" info in AMD Data Tracker - Warehouse Inventory- March 2022

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#8914]
- [x] Spreadsheet emailed from Finance staff month of: March 2022, Journal voucher date 3/18/22
- [x] Number of records being updated: 248
- [x] Formatted spreadsheet [(Review instructions)](https://atd-dts.gitbook.io/atd-knack-operations/warehouse-inventory-updating-journal-vouchers-jv-information)
- [x] Spot checked Transaction IDs, no JV information before import (14719)
- [x] Imported records
- [x] Spot checked Transaction IDs, JV information after import (14719)
- [x] Saved Excel and csv files in G drive 
- [x] Emailed Finance staff that update task complete 4/14/22:"We’ve updated the Journal Vouchers for March 2022. Here is the [filter](https://atd.knack.com/amd#inventory-reports/issued/?view_2799_filters=%7B%22match%22%3A%22and%22%2C%22rules%22%3A%5B%7B%22field%22%3A%22field_3825%22%2C%22operator%22%3A%22is%22%2C%22value%22%3A%2203%2F18%2F2022%22%2C%22field_name%22%3A%22Journal%20Voucher%20Date%22%7D%5D%7D&view_2799_page=1) for them. Let me know if you need anything else."

**Comment by amenity** [comment]
No response from Crystal to Karo's email, so going to close.
