### ISSUE TITLE
Expand Projects List table with columns from Signal Dashboard

### ISSUE THREAD

**Issue by chiaberry** [cityofaustin/atd-data-tech#8929]
In order to achieve an eventual goal of "One Table to rule us all" aka getting parity between the Signals Dashboard table and the Project List View Table, we need to be able to get the same information from the Signals Dashboard table in the SQL View

Here are the columns on the signals table missing from the View

Issue 8901
- [x] task order
- [x] contractor
- [x] project DO # 

Issue 8930
- [x] signal IDs -- in _moped_proj_components_ 
- [x] project types -- _moped_proj_types_

Issue 9006
- [x] funding source -- _moped_proj_funding_

Issue 9044
- [x] status update -- _moped_proj_notes_ where note ID === 2

Issue 9073

- [x] construction start -- _moped_proj_phases_ where phase_name is const
- [x] project completion -- _moped_proj_phases_ 
- [x] ~~current phase -- _moped_proj_phases_ where is_current_phase~~ already in badge form

issue 9078
- [x] designer -- _moped_proj_personnel_ where role === designer
- [x] inspector -- _moped_proj_personnel_ where role === inspector

**Comment by chiaberry** [comment]
@amenity @mateoclarke @johnclary  I made this epic and have two issues opened for some of the columns. I havent made issues for the other columns, are there any that you think AMD would not want? 

Also, should all of the columns that are added to the project list table also be able to be selected in the dropdown filters (aka advanced search?)

I also opened an issue for persisting displayed columns when filtering or refreshing the page. I dont have a size on it yet.

**Comment by chiaberry** [comment]
| column     | show | Filter |
| ----------- | ----------- | --------- |
| task order    | must      | could |
| contractor   | must       |  must | 
| project DO  | must     |  |
| signal IDs  | must     | could   | 
| project types  | must   | should  |
| current phase    | must      | must |
| status update   | must       |  could | 
| funding source    | must     | should |
| designer   |     |   | 
|  inspector    |    |  |
|  construction start   |        |   | 
|  project completion  |        |   |
