### ISSUE TITLE
Release public parking datasets

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#8948]
- [x] [Meet with internal stakeholders](https://github.com/cityofaustin/atd-data-tech/issues/8944)
- [x] Finalize dataset metadata and descriptions
- [x] Make datasets public

**Comment by johnclary** [comment]
@Charlie-Henry would update this issue description with a link to all the related Socrata datasets?

**Comment by johnclary** [comment]
I reviewed the datasets and added a bit of context in the dataset description, specifically a link to the ArcGIS Online layers of parking assets. This is done! 🎉
