### ISSUE TITLE
[Meeting] SMS Sprint Review Meeting 4/22 - Feedback

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#8986]
### Objective 
Bi-weekly meeting to review improvements to SMRT application. This meeting focused on attachments and comments.

### Participants
DTS & SMS 

### Agenda
[link](https://docs.google.com/document/d/1ON5j-wlFHzI94eNYhWsiezusfX0KKwqKEyEoaJe3gU8/edit?usp=sharing) 

------
- [x] Schedule meeting
- [ ] Optional: Schedule debrief
- [x] Meet and take notes
- [ ] Optional: Debrief with DTS team members
- [x] Create resulting issues

**Comment by patrickm02L** [comment]
## Patrick's Notes

### Option 3 - Table

- [ ] Add note to indicate how long the page will take to load
- [ ] Check to see if there are validation issues with attachment files have the same name

### Approval letter

- [ ] create template on City of Austin letter head
- [ ] include Mary & Courtney's signatures

### Submittal Deadline

- [ ] Create time range to close application
- May 13 for June cycle
- November 4th for December cycle

### Testing

- [ ] Conduct user testing with DTS or other folks in SMS division with Free-to-move and Boaz test files.

**Comment by dianamartin** [comment]
Configure Attachment Option - 3 (Table), ping Patrick so he can start testing

**Comment by patrickm02L** [comment]
#9033 is addressing the approval letter.

**Comment by dianamartin** [comment]
## Create new fields in `application` object
![image](https://user-images.githubusercontent.com/21112975/166500116-d8aee771-62b7-4bbe-aaee-67042d0abdff.png)

## Exp MONTH
- To set Permit Terms: June 1 to December 1 to:  5
- To set Permit Terms: December 1 to June 1 to: 11

## Exp DATE
- To set Permit Terms: June 1 to December 1 to:  13
- To set Permit Terms: December 1 to June 1 to: 4

## Exp YEAR
`getDateYear({Created Date})`

## Exp Date EQ
`{Exp MONTH}/{Exp DATE}/{Exp YEAR }`

## App Expiration Date 
- set to `Exp Date EQ`

## Added a task to the `applications` object
![image](https://user-images.githubusercontent.com/21112975/166500008-9e60e4f6-c9f2-41b2-9892-a804d611b17a.png)
![image](https://user-images.githubusercontent.com/21112975/166500041-4baea946-7118-484e-97e0-ad61471b1fba.png)

**Comment by patrickm02L** [comment]
@patrickm02L look into making new issues for these.

Option 3 - Table
- Add note to indicate how long the page will take to load
- Check to see if there are validation issues with attachment files have the same name (Create New Issue)

**Comment by dianamartin** [comment]
During the demo, users saw the task that sets applications to expire after 90 days. They seemed to like it. I showed them that an applicant can't do anything on their application in an "Expired" status, but the reviewer can still add information, comments to their application if they need to.
