### ISSUE TITLE
Cause data count requests to have an assignee name listed, when possible

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#8990]
> What application are you using?

Data Tracker

> Describe the problem.

In the Traffic Count & Data Collection page on Data Tracker, there’s several requests that come in initially “Assigned To” one employee, and when another employee goes into the Details and modifies that "Assigned To" to their name, it no longer lists that Assigned To column on the main page of lists.  One example is the Tara/Salt Springs count request, which came in assigned to Jamie A., and Ray L. modified it to be assigned to himself, but no longer shows that Assigned To column on the main page, which keeps you from being able to Sort by Assigned if some are blanked out.  

> Describe the outcome you'd like to see when this feature is implemented.

All of the data count requests should have an "Assigned To" name listed, unless they are truly unassigned (i.e., the field in the details is blank).  

> Describe any workarounds you currently have in place or alternative solutions you've considered.

Have just been going into individual Details pages of counts to see if the Assigned is listed there, one-by-one, which is time-consuming. 

> Is there anything else we should know?

I would say by the end of June 30th, to do a quarter-end review of the statuses and workload.  

> Requested By
Jonathan L.

[Attachment](https://api.knack.com/v1/applications/595d00ebd315cc4cb98daff4/download/asset/6262fc9b93d605001ec0e345/datarequestsassignedto.jpg) (234.12kb)

Request ID: DTS22-103875

**Comment by amenity** [comment]
@dianamartin - are you able to work with Jonathan to intake and prioritize this issue?

**Comment by dianamartin** [comment]
@amenity this is an easy fix. The other pages that are for the Data Collection team, Jamie have the "Assigned To" field viewable.

**Comment by dianamartin** [comment]
@KaroEngstrom When I took a look at this page, the field already exists on the table. I think I just need to email the requester to give clarification.

**Comment by KaroEngstrom** [comment]
T 4/26/22 Synced with Diana and explored potential batch update need for this (none at this time).
 
- [x] Updated [Traffic Count & Data Collection Requests table](https://atd.knack.com/amd#traffic-count-traffic-data-requests/) to initially show both old ASSIGNED TO and new Assigned To fields for side-by-side comparison
- [x] Compared the fields and if they are matching, remove the old ASSIGNED TO field from the table view, leaving the new Assigned To field that displays the correct assignment
 
![image](https://user-images.githubusercontent.com/100615928/165385619-b42b9846-dde8-4b80-9272-660a8cfb62c7.png)
 
<br>
 

- [x] Updated related [Edit Request pages](https://atd.knack.com/amd#traffic-count-traffic-data-requests/edit-traffic-count/5c6ea6b92a32322f4b29d08c/) to display the new field for both the Data Collection Team and Non-Data Collection Team users
- [x] Updated the [Details page](https://atd.knack.com/amd#traffic-count-traffic-data-requests/traffic-count-details/5c6ea6b92a32322f4b29d08c/) to display only the new field at the top under the street detail
 
- [x] Updated filtered cases (2 records; Jamie A. in both cases) where the new field Assigned To was blank and the old field ASSIGNED TO contained data
 
- [ ] Contact the requester about these updates and ask about the need to updating historic data where the Assigned To fields are blank
