### ISSUE TITLE
[Meeting] Shared Mobility Digital License Application Feedback

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#9033]
### Objective 

Update Mobility Services Division Manager and Permitting Supervisor on how the Digital License Application for Smart Mobility works and get buy-in for a digital permit approval process

### Participants

Jacob C., Courtney H., Joseph A., Mary V. Diana M., Patrick M., Karo E.

### Agenda
None

------
- [x] Schedule meeting
- [ ] Optional: Schedule debrief
- [x] Meet and take notes
- [ ] Optional: Debrief with DTS team members
- [ ] Create resulting issues

**Comment by patrickm02L** [comment]
## Patrick's Notes

- [ ] Create single sign-on for 6 team members who need approval permissions
- [ ] Approvers are not required to sign, but there would need to be a space that automatically records who approved the license. (Approved by:______________)
- [ ] Add option:  Pending Approval - Complete Action 
- [ ] Add option: Pending Permit Approval; generate email for licensing staff
- [ ] Mock-up approval letter

**Comment by dianamartin** [comment]
# Diana's Notes
**SHARED MOBILITY **
Jacob was talking about how cumbersome the permitting process is, having to log into multiple systems and generating new SOPs and training staff

They preferred the simple process of:
- They wouldn't review if the application wasn't completed - don't accept it
- They would generate a permit license on document and sign in 

## Enhancement
Add `Account Management` page - so that users can add/remove users to SMRT system 

## New Statuses
- Pending Approval - Completed Action
- Pending Approval - Permit Team
- Upload Signature on a document 

## Next Steps
- [x] Approval Document from Mary's team - Mary emailed it

## Proposed Process 
When the status goes to "Pending Approval - Permit Team"
Send an email to staff (Courtney's staff)
They upload their signed signature as an attachment
Shows up on the Approval Letter document
Status changes to "Approve"

**Comment by dianamartin** [comment]
@patrickm02L 
Worked on these enhancements on Friday 4/29. Added an "Approve" button and a new page for "Approval Letter". I was able to mock up the Approval letter so it looks very similar to the existing one. 

![image](https://user-images.githubusercontent.com/21112975/166250731-b5c7f1fb-7ee4-4f6c-b256-d055d181d61b.png)

## Approve form
There is a field "Approval Letter Details" if we want the reviewer to free hand create a custom response
- captures Approved By and Approved Date, status changes to "Approved"
![image](https://user-images.githubusercontent.com/21112975/166250845-8bb22021-4087-46fc-9f03-c94b471c94c8.png)

## Approval Letter
![image](https://user-images.githubusercontent.com/21112975/166251507-325fb22b-10e9-4975-bbcf-4063210026a0.png)

**Comment by patrickm02L** [comment]
Overall the mock-up works. Here's my initial reaction to the draft. 

![SMS-Permit Mock Up](https://user-images.githubusercontent.com/5566727/166254241-a010762c-178c-40a5-801a-02b16a4335f8.png)

**Comment by dianamartin** [comment]
#Update
![image](https://user-images.githubusercontent.com/21112975/166504522-84151c5c-129f-4f6a-b30d-cea1953d87c8.png)

**Comment by dianamartin** [comment]
## Created "Account Management" page
![image](https://user-images.githubusercontent.com/21112975/166512161-088c9b91-4c7d-4773-8fd2-faf76198ef0c.png)

## Added "Add Account" button
![image](https://user-images.githubusercontent.com/21112975/166512775-f751d7eb-b1de-4bdf-b8d4-7ca3c00eabf8.png)
- Grouped by "User Status" - Inactive/Active
- Tested it by adding an account for Karo

**Comment by dianamartin** [comment]
## Email auto-generated in "Pending Approval - Permit Team"
![image](https://user-images.githubusercontent.com/21112975/166513481-5fd84372-978c-4976-97e6-cf6f2d09246f.png)

**Comment by dianamartin** [comment]
Will show them at 5/6 meeting

**Comment by patrickm02L** [comment]
Add Jacob's team to SMRT. What credentials do they need? Ask Mary V.

**Comment by dianamartin** [comment]
Showed stakeholders on 5/13 and they seemed to like and understand the process. The reviewer needs to create Provider permits first do that the Area and Number of Devices table shows up on the Approval Letter.
