### ISSUE TITLE
[DT] Delete CSR Flex Notes - June 2022 

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#9055]
Received automated reminder to delete flex notes in AMD Data Tracker PROD and reference the Flex Note Archiving wiki

- [x] Run filter on: https://builder.knack.com/atd/amd/records/objects/object_95

Filter:
`ISSUE_STATUS_CODE` contains `closed`
`CREATED_DATE` is `before` 04/03/3033 (2 months prior)
Results appear as expected.

![image](https://user-images.githubusercontent.com/100615928/171950581-489876e1-7130-4d7b-b8ef-df25d8172a96.png)

Total Records: 23205
To Delete: 7482
New Total: 15723

- [x] Delete records as outlined above.
![image](https://user-images.githubusercontent.com/100615928/171951870-16490bfa-5d98-4436-aed9-7b7858659f9a.png)

- [x] Note activity in change log.
- [x] Create a new issue for next month.
