### ISSUE TITLE
[SMRT] Technical Review Feedback 5/3

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#9066]
# Meeting Notes

## Application Process
- [x] Change "Submit" button to "Save for Later"
- [x] Add Page Rule on Submit button to not submit until 13 attachments are submitted. 

## My Application Details Page
- [x] Remove - Add Attachment

## Suggestion to stakeholders
- Recommend reviewers request .PDFs, user can not preview files that are not .pdf files

## Application Dashboard - Reviewer Details
Test again:
- Feedback Comments button
- Add Reviewer Comment button
- [x] Configure email notification to provider
![image](https://user-images.githubusercontent.com/21112975/166577435-58809e2f-d0c3-47e1-bcd1-461d2a42a1a4.png)

## Customer Action Button
- Not big or blue
- [x] Email has wrong text 
![image](https://user-images.githubusercontent.com/21112975/166562169-1b8a63b6-76e8-48fe-810b-3663dff79690.png)

## Attachment object
- [x] Add new field `Requirement Met?` - Y/N
- to show provider attachment was "Accepted"
- Review Comments for deficiencies

## Page banner - yellow 
- In "In Progress - Pending Action" status
- Add Context about how to re-load
`Click on link to edit attachment`
- [x] Created an info link on "Attachment" field
![image](https://user-images.githubusercontent.com/21112975/166568019-c18347d0-c071-40a9-b7cc-3bf752c64b70.png)

## Form Pop-up
![image](https://user-images.githubusercontent.com/21112975/166568051-9285b176-ec3e-4edb-93c9-436cd46e9ffc.png)

**Comment by dianamartin** [comment]
Synced with Patrick 5/4
Showed him the Attachment Status
- how it would reset attachment to "Needs Review"
If in "Pending Approval - Pending Action" - the "Completed Action" (Y/N) would be reset

- [ ] Edit Button for App Details - Reviewer and Provider
- [ ] Count of Rejected Attachments filter, Page Rule for "Completed Action"

**Comment by dianamartin** [comment]
# Edit Button
## Reviewer
![image](https://user-images.githubusercontent.com/21112975/167035215-ef9ca1b7-9e3e-438a-af82-2413f974481b.png)
## Provider 
![image](https://user-images.githubusercontent.com/21112975/167035296-6a37b80d-269e-4d66-8722-ed8ddff4a23e.png)
## Edit Form
![image](https://user-images.githubusercontent.com/21112975/167035505-b2de2b18-a6e1-46b7-917c-7edd9e9c0d1f.png)
![image](https://user-images.githubusercontent.com/21112975/167035592-6f42d00d-16d5-4695-bf11-5f39384fa0a0.png)
![image](https://user-images.githubusercontent.com/21112975/167035729-157cc79c-9ac7-4a64-8630-41c1044fd179.png)
![image](https://user-images.githubusercontent.com/21112975/167035770-317fc4a2-7995-45af-8736-a167638a5784.png)

# Count of Rejected Attachments
![image](https://user-images.githubusercontent.com/21112975/167035815-43b5be4a-c7be-4d8c-bbdf-0b2fa4a49454.png)
![image](https://user-images.githubusercontent.com/21112975/167035839-517ef01a-8764-4d73-a0ec-4144337ff734.png)

**Comment by dianamartin** [comment]
Showed stakeholders application on 5/13, went through workflow and let them know these things were updated: 

- "Save for Later" button
- Updated Page Rule to prevent a user from submitting their application until 13 attachments were added. 
- Removed - "Add Attachment" button to My Application details page
- Updated email notifications
- Added banner information on what to do
- Attachment table is hidden if no attachments are added
- Showed info button on Attachments field
- Added Edit button
