### ISSUE TITLE
Onboard Peggy to DTS

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#9094]
## Accounts 
- [x] Submit a [CTM service request](https://atx.service-now.com/sp) to add to DTS Distribution Email Group:
  - Add "First Last Name" to email distribution list "ATD Data and Technology Service" ([ATDDataTechnologyServices@austintexas.gov](mailto:ATDDataTechnologyServices@austintexas.gov)) and "ACE ATD DL"
- [x] Add to City of Austin Slack - austininnovation.slack.com @mateoclarke 
- [x] Add to DTS Google Drive @amenity 
- [x] Add to [Gitbook](https://app.gitbook.com/@atd-dts/spaces)
- [x] Add to [Austin Transportation Github Team](https://github.com/orgs/cityofaustin/teams/transportation/members) 
- [x] Add to [DTS Presentation Template Team section](https://docs.google.com/presentation/d/1tHKTfUgQ-uAXdRBkEdXqR7ryBo_LTU86IzQxo1gJoeA/edit#slide=id.gfd2da31025_0_6) - two places
- [x] Add to DTS 1Password - @amenity 

## Hardware 
_Some of this may be complete/unnecessary_ 
- [x]  Laptop
- [x] Monitors
- [x] Chair - check availability, ask John to ask Peggy how we're handling this?
- [x]  Power supply
- [x]  Keyboard
- [x]  Mouse
- [x]  Docking station

## Calendar invites
- [x] Monthly Team Meeting — John
- [x] Sprints — @amenity 
- [x] Sprint Ceremonies — @amenity  
- [x] First day: DTS Team Orientation — @mateoclarke 
- [x] First Week: DTS Product Ops — @amenity 

## To-do for Peggy
- [x] Send out new DTS Team meeting invite. @johnclary's current invite is monthly, for 2 hours, next one is June 14th. Then let John know so he can delete his. 
- [x] Set up Cameron Road wifi: coa-atd-secure-wifi — password in 1password
- [x] [Set up your email signature](https://docs.google.com/document/d/1OAoBll9rIl6XZq2uOShm5HCbHJboOt0SLP_wK6tjkEE/edit)
- [x] [Create a Google account for your Austintexas.gov email address](https://atd-dts.gitbook.io/atd-staff-resources/general/using-google-as-a-city-employee)
- [x] If you don't have one already, [create a Github account](https://github.com/join) 
- [x] Install [Zenhub Browser Extension](https://www.zenhub.com/)
- [x] Post your [daily standup in Slack](https://atd-dts.gitbook.io/wiki/slack#daily-stand-up)
- [x] [Set yourself up for remote work](https://atd-dts.gitbook.io/atd-staff-resources/working-remotely/getting-started)
- [x] Upload a headshot [here](https://drive.google.com/drive/folders/1y_yhkZQE5uSRhLZAHJn2kFuXPBixVJ2G) and add your title and preferred pronouns [here](https://docs.google.com/document/d/1gRjTic8FD3s-t0sVZhErAidMIAktU-0Vn2GYPpPcUeg/edit) (Google Drive access must be set up first)
- [x]  [Create a Github issue](https://github.com/cityofaustin/atd-data-tech/issues/new) for adding yourself to the [DTS "About Us" webpage](https://austinmobility.io/about) (labels: Service: Dev, Type: Operations, Product: DTS Website) including the link to your photo and preferred pronouns
- [ ] Familiarize yourself with the [DTS Resource Index](https://github.com/wiki/resource-index)

**Comment by amenity** [comment]
[Onboarding notes](https://docs.google.com/document/d/1Gd7IAJrv6n2lrbIE_4iVYiwRr8t27Hi8ymBEIeluEnw/edit#heading=h.la5t7kkn1hd9)  from meeting today w/ Peggy and @mateoclarke.

**Comment by amenity** [comment]
@maccallump - please let us know here when you've added your headshot and pronouns. This is currently a blocker on #9376.

**Comment by maccallump** [comment]
Issue #9390 https://github.com/cityofaustin/atd-data-tech/issues/9390
Refresh DTS Presentation Template

**Comment by amenity** [comment]
Thanks, @maccallump! We've already got this issue for the website so you won't need to create the issue for that.
