### ISSUE TITLE
Update "Journal Voucher" info in AMD Data Tracker - Warehouse Inventory- April 2022

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#9108]
- [x] Spreadsheet emailed from Finance staff month of: April 2022 (April 29-30,2022)
- [x] Number of records being updated: 621
- [x] Format spreadsheet [(Review instructions)](https://atd-dts.gitbook.io/atd-knack-operations/warehouse-inventory-updating-journal-vouchers-jv-information)
- [x] Spot check Transaction IDs, no JV information before import (15090; 15245)

- [x] Import records
- [x] Spot check Transaction IDs, have JV information after import (15090; 15245)
- [x] Email Finance staff that update task complete

Hello Crystal, 

We’ve updated the Journal Vouchers for April 2022. Here is the [filter](https://atd.knack.com/amd#inventory-reports/issued/?view_2799_page=1&view_2799_filters=%7B%22match%22%3A%22and%22%2C%22rules%22%3A%5B%7B%22field%22%3A%22field_3825%22%2C%22operator%22%3A%22is%20after%22%2C%22value%22%3A%2204%2F28%2F2022%22%2C%22field_name%22%3A%22Journal%20Voucher%20Date%22%7D%2C%7B%22match%22%3A%22and%22%2C%22field%22%3A%22field_3825%22%2C%22operator%22%3A%22is%20before%22%2C%22value%22%3A%2205%2F01%2F2022%22%2C%22field_name%22%3A%22Journal%20Voucher%20Date%22%7D%5D%7D) for them. 

Let me know if you need anything else. 

Best,
Karo
