### ISSUE TITLE
New account setup to access Data Tracker.

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#9130]
> What application are you using?

Data Tracker

> Describe the problem.

I am a new hire and need a new account setup to access Data Tracker.

> How soon do you need this?

Soon — This week 

> Requested By
Shanice J.

Request ID: DTS22-103985

**Comment by dianamartin** [comment]
@KaroEngstrom Can you confirm with the user what they're doing in the Data Tracker? or whose permissions should be mirrored?

**Comment by KaroEngstrom** [comment]
F 5/13/22 -Emailed requester to get these details

**Comment by KaroEngstrom** [comment]
F 5/13/22 

- [x] Received more information from requester regarding requested permissions 
- [x] Created an account for the requester mirroring the permissions for Maggie C. 
- [x] Notified the requester of the new account and gave instructions for logging in
