### ISSUE TITLE
[BUG] "Controller IP Cabinet” is visible but not editable

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#9138]
Allyson R. 
AMD

Emailed
>Bit of an odd one for you, I think it’s stemming from cabinets being separate searchable assets from signals but signals having an internal cabinet reference table. 

We noticed on signal #168 (Airport and IH 35), the Cabinet Summary table (seen below) shows the controller IP cabinet IP as `67.68`. If you go into signal details and scroll to cabinet controller IP, it lists `67.52`. The correct IP is the .67.52, and we’d like the cabinet summary in signal summary to reflect. 

If you go to assets -> cabinets -> and look at the IP listed there, it is also the `67.52`. 

We aren’t sure where the `.110.68` IP address is being hosted from, or how to change it. Could you take a look and let us know? Thanks!

**Comment by dianamartin** [comment]
I emailed 5/13
>Thanks for letting me know about this. It looks like the field “Controller IP Cabinet” is on the cabinet table and it’s showing on the Signal Details page. However, when we updated the cabinet page/form/details, we never exposed the “Controller IP Cabinet” field to be shown or editable. This field might be a historical artifact now that your group doesn’t use anymore, is that accurate?

>So, I can update the Cabinet section that shows on the Signal details. It looks like “Controller IP Cabinet” needs to be replaced with “Monitor IP”, is that correct? 
>- If you would like to see this change, just put in a DTS ticket. 

Allyson replied
>We’d like the IP to be the controller cabinet IP, which is172.16.67.52. The Monitor IP is a different device.

**Comment by dianamartin** [comment]
- [x] Added "Controller IP Cabinet" field on Cabinet Details
![image](https://user-images.githubusercontent.com/21112975/168370140-bf4e06e4-066f-4136-9d36-2aa883a45ede.png)

- [x] Added "Controller IP Cabinet" field on Edit Cabinet form
![image](https://user-images.githubusercontent.com/21112975/168366427-c04a243e-aa90-40ee-92e3-b3f808620c77.png)

- [x] Added "Controller IP Cabinet" field on Add Cabinet form
![image](https://user-images.githubusercontent.com/21112975/168361167-3545384c-e766-48ca-a7e0-44e280d69cb4.png)

**Comment by dianamartin** [comment]
Emailed stakeholders 5/13
>I created an issue to update the Cabinet page to include the missing field “Controller IP” field
•	Added "Controller IP Cabinet" field on Cabinet Details
•	Added "Controller IP Cabinet" field on Edit Cabinet form
•	Added "Controller IP Cabinet" field on Add Cabinet form
So now you can edit the IP information on Signal #168.

**Comment by dianamartin** [comment]
Allyson replied 5/16
>Thanks Diana!
