### ISSUE TITLE
Create Soft deletes columns instead of using status_id

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#9150]
We started with a table of statuses, and they were originally intended to be used as Project Status options, but were then adopted as statuses describing other tables’ records (ex: users, phases, project types etc).

We have been using soft-delete across the board, one option for identifying these is within mutations of interest. Search for “delete” in the editor file hierarchy.

Let's identify where we actually need a soft-delete system, and create a column in those tables containing rows that may need soft-deletion. We could track what is soft-deleted via a new boolean column on that table, perhaps `is_deleted`. 

[PR Comment #1](https://github.com/cityofaustin/atd-moped/pull/529#issuecomment-1016087634)
[PR Comment #2](https://github.com/cityofaustin/atd-moped/pull/645#discussion_r869675634)

Here's my proposed way of tackling this tech debt. These could be broken into sub issues as needed:
- [x] Identify and list which tables should add `is_deleted` column in place of a `status_id`
- [x] Prioritize the list of tables
- [x] Make discreet PRs for each one to isolate code review and testing

**Comment by mddilley** [comment]
Made a sweep through the code this morning. Will break these into groups of work and add the specific table names.

- Projects
  - Mutation `PROJECT_UPDATE_CURRENT_STATUS` in project.js line 745
- Project Comments
  - Mutation `DELETE_PROJECT_COMMENT` in comments.js line 52
- Project Funding
  - Mutation `DELETE_PROJECT_FUNDING` in funding.js line 77
- Project Phase
  - Mutation `DELETE_PROJECT_PHASE` in project.js line 353
- Project Milestone
  - Mutation `DELETE_PROJECT_MILESTONE` in project.js line 364
- Project Component, subcomponents, and features
  - Mutation `DELETE_MOPED_COMPONENT` in project.js lines 640, 646, 652 
  - Code that marks subcomponents for deletion in ProjectComponentsMapEdit.js line 366
- Project partners
  - Mutation `PROJECT_UPDATE_PARTNERS` in project.js line 716
- Project types
  - Mutation `PROJECT_UPDATE_TYPES` in project.js line 770
- Project Team Table
  - Soft delete in the delete project personnel action function in ProjectTeamTable.js line 374
  - Soft delete in the update project personnel action function in ProjectTeamTable.js line 355
- Queries that filter status_id > 0 (not soft deleted)
  - Query `SUMMARY_QUERY` in project.js line 111
  - Query `STATUS_QUERY` in project.js line 129

**Comment by johnclary** [comment]
Closing this epic and leaving #9747 in the backlog.
