### ISSUE TITLE
(Epic) ROW Portal Update for TCP Intake

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#9164]
**Scope:**
- Public intake form, 1 workflow
- Upgrade internal review workflow to accommodate unmet business needs & upcoming changes to the TCP review workflow. 
- Create a new internal review workflow for Conflict/Shared Work Zone Analysis

**Risks:**
- **Low** The TCP workflow is currently being updated but not in a way that would significantly change the new features that we build.
- **Medium** ROW's assistant director recently changed from Jim to Upal. This may result in unexpected changes in priority and/or workflows. 

----
### Final Workflow
![TCP Intake Workflow.jpg](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/b8dd37d9-c92e-4aed-b52b-5def7f68d427)

**Comment by TracyLinder** [comment]
### Sync w/ Darren 5/17/22

**Scope:**
- Public intake form, 1 workflow
- Upgrade internal review workflow to accommodate unmet business needs & upcoming changes to the TCP review workflow. 
- Create a new internal review workflow for Conflict/Shared Work Zone Analysis

**Risks:**
- **Low** The TCP workflow is currently being updated but not in a way that would significantly change the new features that we build.
- **Medium** ROW's assistant director recently changed from Jim to Upal. This may result in unexpected changes in priority and/or workflows. 

**Misc. & Next Steps:**
- Tracy & Darren will be out on VCU until mid June. Then SIF goes live. The next meeting will need to be in early July. 
- Darren & Samson are working on creating a TCP Intake & Review Workflow diagram that we can use for discovery. 
- Tracy created a miro board for the TCP workflow & invited Darren to edit. Miro Board [is here](https://miro.com/app/board/uXjVO0VEV0o=/?share_link_id=558346725368).

**Comment by TracyLinder** [comment]
### Update

- Created this epic & added 2 feature cards.
- Scheduled discovery kickoff & created issue #9165

**Comment by TracyLinder** [comment]
### Update

During the discovery meeting #9165 we determined the scope of this request meets DTS's criteria for a project based approach. Introducing a public intake workflow to the TCP Review Mod will require significant updates to the existing mod, and building case management features similar to TIA. @TracyLinder will create a project index

We also determined we can move forward building a public TCP intake form, #8378. 

_TBD what I'll do with this epic._

**Comment by TracyLinder** [comment]
### DRAFT TCP Status List & Notes
_(By Tracy & Chrispin)_



- Under Creation
- Pending Intake (When it lands in Alyse’s queue) 
- Pending Payment (Alyse has provided the invoice)
- Completeness Check (we need more scoping)
- Needs Review (when assigned to a TCP reviewer by Alyse) (now Alyse is done) (this triggers the system to insert the TCP due dates)
- Review in Progress
- Review Complete - (ROW wants to use this instead of Approved)
- Approved - Should we remove this & replace existing Approved status’ to Review Complete? 
- No Review Required
- Cancelled
- Rejected
- Returned
- Inactive

**Comment by TracyLinder** [comment]
### Status Workflow for Customer Demo on 11/22

![TCP Intake Status Workflow](https://user-images.githubusercontent.com/49930868/200668288-1d285659-7305-4b79-8fa0-85e7c2c626d5.jpg)

**Comment by TracyLinder** [comment]
## Go-Live Review 1/31/23

🎉 **APPROVED!**

## To-Do's from review:

- [ ] Update the validation error when the applicant enters an invalid value. Tell them what is wrong and how to fix it. 
- [ ] Take CIP question out of the edit application page
- [ ] Remove AMANDA ROW ID field
- [ ] Only show CIP field on case details when there is a value to view
- [ ] Update submittal status text from **Pending** to **Needs Review**
- [ ] Update Reviewer Dashboard TCP Submissions filter from **Pending Review** to **Needs Review**



----
### GO-LIVE Notes
- Target rollout date is **3/1/23**, Chrispin will perform updates the previous day after business hours. No downtime expected. 
- External and internal training is needed. Darren/ROW is already working with ATD-PIO to develop customer training and will add this to that initiative. 
- Email blasts to be coordinated by Darren, we can help provide email addresses if needed. 
- Darren will followup on training needs.

**Comment by TracyLinder** [comment]
This was delivered in March and is stable. Yay!
