### ISSUE TITLE
Refactor Moped Test pipeline

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#9196]

**Comment by frankhereford** [comment]
During the course of looking into https://github.com/cityofaustin/atd-data-tech/issues/9162, it was observed that because we use a multi-tenant database server provided by Heroku. This reality makes the automated disabling of JIT more complicated, as you have to find a way to set the setting via migrations, as we do not have access to server configuration settings at run time. 

The above wrinkle in addition to ongoing database deployment issues experienced with Heroku by members of the Dev & Product teams, has prompted the creation of this epic. While it only contains a single issue presently, that first issue is related to scoping and documenting a proposed solution.

**Comment by amenity** [comment]
@frankhereford and @mddilley are going to provide more information here and add tasks representing the work ahead.

**Comment by mddilley** [comment]
Adding the task from the flow that Frank and I talked through so far so we can keep adding issues to this epic. Most of the create and destroy pairs will likely make up a single issue. Current priority is the DB and GraphQL engine tasks.
- [x] Create DB
- [x] Destroy DB
- [x] Create Hasura GraphQL cluster
- [x] Destroy Hasura GraphQl cluster
- [ ] Create SQS for activity log
- [ ] Destroy SQS for activity log
- [ ] Create activity log Lambda
- [ ] Destroy activity log Lambda
- [ ] Create Moped test API
- [ ] Destroy Moped test API

**Comment by frankhereford** [comment]
These comments were in our main flow file, and I want to pull them out of there, but not loose them, as they ask valuable questions which may or may not have been addressed:

```
# Database Tasks

# Frontend:
# 1. When feature PR is opened, a deploy preview spins up and is linked in PR
# 2. Env vars are available to introspect PR # and context (CONTEXT = deploy-preview)
#    https://docs.netlify.com/configure-builds/environment-variables/?utm_campaign=devex-tzm&utm_source=blog&utm_medium=blog&utm_content=env-vars&_gl=1%2agvssna%2a_gcl_aw%2aR0NMLjE2NTQ1NDAxNzcuQ2p3S0NBand5X2FVQmhBQ0Vpd0EySUhIUUFud3NXc1ltbXJybGs5SnVfWTJlazlkUF9hVmM4WVZuTjR5Zk5QR0Y2U2ZOLTMycl93ekFCb0M2Y0lRQXZEX0J3RQ..&_ga=2.210432213.1131530997.1654540177-2032963523.1654540177&_gac=1.123937528.1654540177.CjwKCAjwy_aUBhACEiwA2IHHQAnwsWsYmmrrlk9Ju_Y2ek9dP_aVc8YVnN4yfNPGF6SfN-32r_wzABoC6cIQAvD_BwE#read-only-variables

# Considerations:
# 1. Auth (use staging user pool) needs a callback URL set in the user pool. How does this work
#    for the deploy previews? (I know that we can't use SSO)
#    - Just do whatever deploy previews do for auth

# Questions:
# 1. What S3 bucket does current moped-test use for file uploads?
#    - Extend directories in S3 bucket to keep files for each preview app
```
