### ISSUE TITLE
Update Project Phases and Project Milestones tables with `is_deleted` column

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-data-tech#9210]
Project comments and project funding currently use status_id = 0 for soft delete. We should update with a boolean is_deleted column.

Update:
- [x] Tables listed below and comment new fields in DB
- [x] Mutations and code that soft delete
- [x] Any UI that filters on status_id = 0
- [x] Any code that sets status_id = 1 on record update or creation

Tables:
- moped_proj_phases
- moped_proj_milestones

Mutations:
- DELETE_PROJECT_PHASE in project.js line 353
- DELETE_PROJECT_MILESTONE in project.js line 364
