### ISSUE TITLE
Meeting: V7 UAT Planning Tasks

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#9214]
### 5/19/22
_Nate, Tracy, Vish_

**Agenda:**

- [ ] Find & list all tasks
- [ ] For each task: identify resources needed for each, level of effort, next steps, reference materials, deadline
- [ ] Delegate tasks

<img width="911" alt="Screen Shot 2022-05-19 at 3 10 23 PM" src="https://user-images.githubusercontent.com/49930868/169396182-076e4196-760a-41d4-a725-208a1cd5399d.png">

----
<div ccp_infra_version='3' ccp_infra_timestamp='1652993098672' ccp_infra_user_hash='881534590' ccp_infra_copy_id='c10ecde6-c56f-41a7-8cd2-77ebbd6f6f51' data-ccp-timestamp='1652993098672'><html>

<head>
<meta http-equiv=Content-Type content="text/html; charset=utf-8">
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">

</head>

<body link="#0000FF" vlink="#954F72">

Workflow Name | Division | Manager | SMEs
-- | -- | -- | --
RW - Street Event | OSE | Frances | Maria
RW - Parking | OSE | Frances | Maria
TIA | TDS | Nathan | Joan
TDS fees on DSD folders | TDS | Nathan |  
TDS fees on GF folder | TDS | Nathan |  
SB | Signs & Markings | Lauren | Cathy K
RW - TURP | ROW | Paloma | LaTonya, Peter
RW - Parking | ROW | Paloma | Johnathan W.
RW - Street Vendor | ROW | Paloma |  
RW - Film | ROW | Paloma | Josh W.
RW - Valet Annual | ROW | Paloma |  
RW - Valet Temporary | ROW | Paloma |  
RW - Valet Operator | ROW | Paloma |  
EX | ROW | Paloma | Izzy, John C,
DS | ROW | Paloma | Alyse R., John C
UC | ROW | Darren | Jaclyn, Isiah
PSM | ROW | Paloma |  
LC | ROW | Paloma | Daniil
ECV | ROW | Darren |  
GF Fees | ROW | Darren |  
SIF | ROW | Nathan | Amber, Tracy
TCP Inspections | ROW | Darren |  

</body>

</html>
</div>

**Comment by TracyLinder** [comment]
### Notes

**Test Cases:**

- RW - Each subtype, portal, online payment (7 types)
- EX - Private, COS, Franchise, portal, online payment
- DS , portal, online payment
- UC - COS , portal, Self-Assign, online payment, iterative review cycles
- GF - TDS & Row TCP, online payment
- LC, online payment
- PSM , portal & each subtype, online payment, iterative review cycles
- TIA online payment
- TDS Fees on SP, C8, SPC, ZC, _any other places they charge fees?_
- SB (ATD subtypes only), online payment,
- TCP Inspections
- SIF


**Tasks:**

- [ ] Document the Parking workflow steps for UAT template @vschandramouli 
- [ ] UAT Template for TURP, EX, CP Inspections
- [ ] Maybe: TCP Inspections, vendor, valet
- [ ] No: Film, Street Event, 
- [ ] Ask for testers from OSE, TDS, SB @TracyLinder 
- [ ] Schedule UAT planning w/ Paloma
