### ISSUE TITLE
Crash mapping ~9 locations

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#9220]
> What application are you using?

ArcGIS

> Describe the problem.

We have a VZ need for help with crash mapping ~6 locations so we can continue to make progress on the Vision Zero bond scopingdesign pipeline we’ve built up.  I can handle the upfront crash QA/QC on it so it’s mostly just any remaining QA/QC and then using the crash diagramming tool Frank built to move crashes to the right spots in the way that we've been doing it.

> How soon do you need this?

Flexible  — An extended timeline is OK

> Is there anything else we should know?

We'll identify the next locations in the next 2 weeks or so and then would like to get the crash diagrams done soon after that.  No exact timeline so open to conversation about availability of staff time.  Thanks so much for helping while Adrien is on maternity leave!

> Requested By
Lewis L.

Request ID: DTS22-104055

**Comment by patrickm02L** [comment]
reference #7271

**Comment by patrickm02L** [comment]
Via Lewis on 5/26/22

> With updated prioritization analysis we have some locations we’d like to get crash mapped while Adrien is out to keep making scoping/design progress. 
> 
>  
> 
> I mentioned wanting six locations to Patrick, but I’ve noticed that since we’re focusing on City streets for this round these are relatively smaller crash volume locations so let me know if this list is doable. And if you want me to do the initial crash QA/QC on some, I’m glad to. This would be in order of priority from top to bottom:

- [ ] Fairway / Montopolis - 63EC821F4A
- [ ] E. Oltorf / East Side - 5A2363A648
- [ ] Burton / E. Oltorf - C19CA012A1
- [ ] Collinfield and Mearns Meadow / Rundberg - 897FECAA37
- [ ] Rundberg / North Creek - ADE670C0E9
- [ ] E US290 SVRD EB / Cameron Rd - C471A66C69
- [ ] Riverside / Metro Center - 4B8769EC9E
- [ ] Center Line Pass/Lakes / Howard - 8481CA376C

**Comment by patrickm02L** [comment]
@frankhereford sounds like a good plan. Go for it!

**Comment by frankhereford** [comment]
Update on progress: All AOIs are drawn, allowing me pull crash lists for QA/QC. That process is about 1/3 complete as of writing. Tomorrow's plan is to finish that QAQC and start laying out diagrams.

**Comment by frankhereford** [comment]
Feedback on individual maps have been completed for the maps in the first wave of 5. The remaining 4 maps have been completed.

Deliverables sent via OneDrive to Lewis, Mario & Gavin include:

* The PDFs of the maps themselves
* A file hierarchy of CR3s organized by approach for each intersection
* A spreadsheet of crash data organized by approach for each intersection
* Shapefiles including all this work for use in GIS applications
* An link to the updated AGOL representation of this work, available [here](https://austin.maps.arcgis.com/apps/instant/interactivelegend/index.html?appid=f7f97779debf4f84ba97307482008a49). This isn't shared department wide, so please let me know if you need access to it.
