### ISSUE TITLE
[BUG] Unit Cost/Estimate Cost fields inaccurate, correct decimal places for Unit Cost

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#9331]
Erin B. 
AMD

**Describe the bug**
>Noticed that the contract item costs for the ATS contract extension do not always exactly match what I get from the contractor in invoices and cost estimates. I finally did a little looking into it and the spreadsheet of item costs I sent you previously was rounding to 2 decimal places, throwing off the total costs by a few cents when multiplied.  

**URL**
https://atd.knack.com/amd#construction-cost-estimates/manage-contracts/

**Spreadsheet**
[662A_2022 Contract Extension Bid Items_not rounded.xlsx](https://github.com/cityofaustin/atd-data-tech/files/8806624/662A_2022.Contract.Extension.Bid.Items_not.rounded.xlsx)

**Comment by dianamartin** [comment]
Checked the system and the "Unit Cost" field on the `const_cost_items` table was a "Currency" type. - [x] Created a new field "Unit_Cost_No". - `Number` field, set to 4 decimal places
- [x] Set a conditional rule to point to original Unit Cost field
- [x] Exported out 662 (2022) items to update the Unit Cost field through an import - `100 records`
- [ ] Imported the 662 (2022) items with corrected Unit Cost to the 4th decimal

**Comment by dianamartin** [comment]
Messaged user 5/31
>I updated the Unit Costs and have been trying to update the pages for the Construction Cost Estimates. (Provided screenshots)

She replied
>Yes, that looks correct.  Is there a way for it to round to the second decimal place in the Total Cost field?
