### ISSUE TITLE
Connect [ROW Portal - COS] to AMANDA V7

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#9332]
## Connect ROW COS Integration to AMANDA V7 - DUE 8/1/22

----

- Need a query that pulls data from Oracle DB.
    - John will add existing query to comments 
- Is the schema different from the previous version? If so, we’d ask AMANDA team to provide that new query
    - Tracy will ask CTM to review query 
- Apps will need to make a test copy of the COS module
- Devs will need credentials to v7 DB, new/updated SQL query, test instance
- Can test using Knack test app + AMANDA 7 test

**Comment by TracyLinder** [comment]
@johnclary can you please add the query here before 1pm tomorrow 6/1?

**Comment by johnclary** [comment]
@TracyLinder [here](https://github.com/cityofaustin/atd-cost-of-service-reporting/blob/production/queries/fees.sql) is the query we're currently using.

**Comment by TracyLinder** [comment]
### Notes - Mtg w/ CTM 6/1/22
_Tracy, Nate, Chrispin, Mateo, Gita, Jenice, Richard_

- [ ] Ask if any tables from the query have changed. 
- [ ] ATD Devs will need credentials to v7 DB (test & prod)

**Comment by TracyLinder** [comment]
**Question:**
_ask at sprint planning_

- Is there a risk of losing the existing COS data?

**Comment by mateoclarke** [comment]
@frankhereford will help with this on the Dev team. I'll make a new issue in this Epic with the specific Dev tasks and scope it out clearly for him.

**Comment by TracyLinder** [comment]
### Update
- Chrispin made a copy of the KNACK app
- Frank has successfully connected to it
- Next the 3 of us will sync on next steps on 7/5
- We meet w/ CTM on 7/6

**Comment by TracyLinder** [comment]
**Sync w/ Frank & Chrispin:**

- We need V7 PROD credentials from CTM.

**Comment by TracyLinder** [comment]
### Meeting w/ V7-CTM 7/6/22

- Gave CTM update: We've connected our test KNACK app to V7 test without issue. 
- Discussed go-live & switching PROD KNACK from V6 to V7. 
- DTS will switch connection on the morning of Mon Aug 1st. Frank said it will take about 10 minutes. 

**Action Items:**

- [ ] Tracy: Create git issue for connecting to Prod
- [ ] Tracy: Block calendar for Frank & Chrispin the morning of 8/1
- [ ] Tracy: Notify ATD Finance of the downtime. 
- [ ] Gita: Will email DTS the credentials for V7 PROD. The user id & password are the same.

**Comment by TracyLinder** [comment]
**Downtime Email:**

Hello,

DTS will be updating the COS Reporting integration to connect to AMANDA V7 the morning of 8/1. 
When: Monday Aug 1st
Time: 8am - 12pm 
What to Expect: The COS Reporting app will be buggy and the data will not be reliable during the update.  
Action Required: ATD Finance should hold on exporting COS data until notified the update is complete. 

Please let me know if there are questions or concerns. 

Thank You, 

Tracy Linder, Product Manager

**Comment by frankhereford** [comment]
👋 @TracyLinder - is this issue something that could be closed? Thanks!

**Comment by TracyLinder** [comment]
This is complete.

**Comment by johnclary** [comment]
Nice!

On Jul 6, 2022, at 17:34, Tracy Linder ***@***.***> wrote:

﻿
*** External Email - Exercise Caution ***

Downtime Email:

Hello,

DTS will be updating the COS Reporting integration to connect to AMANDA V7 the morning of 8/1.
When: Monday Aug 1st
Time: 8am - 12pm
What to Expect: The COS Reporting app will be buggy and the data will not be reliable during the update.
Action Required: ATD Finance should hold on exporting COS data until notified the update is complete.

Please let me know if there are questions or concerns.

Thank You,

Tracy Linder, Product Manager

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcityofaustin%2Fatd-data-tech%2Fissues%2F9332%23issuecomment-1176771024&data=05%7C01%7Cjohn.clary%40austintexas.gov%7C61cb737cb9ab457c063508da5f975353%7C5c5e19f6a6ab4b45b1d0be4608a9a67f%7C0%7C0%7C637927400802832271%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=9SgS3qQq4kv%2FrXDLu5vkZm0xNBhKYI0inILPsi%2BcRcE%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADQ3TIFTLBGY7GESP25AGB3VSX3WZANCNFSM5XOELDMA&data=05%7C01%7Cjohn.clary%40austintexas.gov%7C61cb737cb9ab457c063508da5f975353%7C5c5e19f6a6ab4b45b1d0be4608a9a67f%7C0%7C0%7C637927400802832271%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=eWLKLxDA4K3%2FauCRGEnwI%2B2FvMTbEnBKhTfVrdZjsbQ%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

CAUTION: This email was received at the City of Austin, from an EXTERNAL source. Please use caution when clicking links or opening attachments. If you believe this to be a malicious and/or phishing email, please forward this email to ***@***.***
