### ISSUE TITLE
[Feature] Incorporate sign data into SMD work order processes

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#9343]
> What application are you using?

Signs & Markings Operations

> Describe the problem.

Would like to start conceptualizing how to incorporate the sign data into our Signs Work Order process in Knack. 

> Describe the outcome you'd like to see when this feature is implemented.

Would like to start working out the new process for when we have our full sign dataset. We should receive the full sign data collection by the end of November, but will receive the data in 4 batches.

> Describe any workarounds you currently have in place or alternative solutions you've considered.

N/A

> Requested By
Christina T.

Request ID: DTS22-104160

**Comment by dianamartin** [comment]
We have been meeting in the Future Sign Data Management meetings regularly 
(Andrew, Christina, Susanne and I)

- We've been talking about how we'd incorporate some elements together to link the authoritative sign data to sign work order process. 
- We've added a few field and documented it on a Miro board and tested what it might look like
- We are being mindful that with the new Traffic Register app/process it might make a lot of work/steps for the engineers (we're figuring this out now)

**Comment by dianamartin** [comment]
We were supposed to meet last week, 8/31 but rescheduled due to GIS interviews. We have done some testing on the sign work order creation with new assets in the Test Environment. We had to add 2 new fields to some object tables.

**Comment by dianamartin** [comment]
# 1/25
12 STEPS THAT VIEWER TAKES TO:
## Create a Work Order
1. Home
2. New Work Order Signs button
3. Page 1: WO ID #, Locations & Instructions & Comments
4. Review Details
5. Attachment required
6. Regulation attachment/URL

NEW STEPS
## Create a Work Order and Location & Assets
1. Search for location
2. Add point
3. Add GIS LOC ID
4. go to Details
5. Add asset
6. Add asset details
7. Add GIS ASSET ID

- [x] We logged in as a Test-Viewer and created a new signs work order we time it, 
-  `36 seconds` - create work order, attach attachment plan
- [ ] We logged in as a Test-Technician and created a new signs work order, attachment, create location, create asset
- `1 min, 10 seconds` 

It added an extra 7 steps to the current process

 

Action Items
- Christina wants to shadow TED users to see how they create their graphic work orders

**Comment by dianamartin** [comment]
# 3/8
Christina reached out to TED and got some volunteers that we can shadow
- Leslie
- Ed
- Anthony A. 

- [ ] Will schedule shadow sessions in the next few weeks

**Comment by ChristinaTremel** [comment]
This was the first issue used to start tracking this discovery. The goal at this time was to have Requesters create work orders using the sign inventory, but they were not interested in changing their process at the time. Closing this because we didn't move forward with this request at that time and our scope has changed.
