### ISSUE TITLE
Update "Journal Voucher" info in AMD Data Tracker - Warehouse Inventory- May 2022

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#9386]
- [x] Spreadsheet emailed from Finance staff month of: May 2022, 5/27-5/31/22
- [x] Number of records being updated: 527
- [x] Format spreadsheet [(Review instructions)](https://atd-dts.gitbook.io/atd-knack-operations/warehouse-inventory-updating-journal-vouchers-jv-information)
- [x] Spot check Transaction IDs, no JV information before import: 16351; 15799
- [x] Import records
- [ ] Spot check Transaction IDs, no JV information after import
- [ ] Email Finance staff that update task complete
