### ISSUE TITLE
Research and Test Auto-Capture Software for Knack Documentation & Training

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#9434]
### Goals 🥅 🚨 
1) Determine if a software solution that automates the task of capturing screenshots and generating descriptions for documentation and training might help the Apps team in the delivery of Knack projects
2) Gather knowledge of which solutions might be the best fit, based on research and testing

### Primary Software Setup and Links 👁️ 👁️

[**TANGO** ](https://www.tango.us/) 
- [x] Free account created Th 6//9/22 (covers Chrome extension, no desktop functionality)
Description: "Press “capture” and Tango turns your process into a step-by-step guide with screenshots and instructions. Capture your work in the browser with the free extension. Upgrade to Pro and capture on Desktop too."

**[SCRIBE](https://scribehow.com/)**
- [x] Free account created Th 6/9/22, with Chrome extension
Description: "Scribe turns any digital process into a step-by-step guide. Simply turn on the Scribe recorder and walk through your process. Scribe automatically creates your step-by-step guide, complete with text and screenshots."
 
**[USERGUIDING](https://userguiding.com/)**
- [x] Free account created Th 6/9/22, with Chrome Extension
Description: "Create a smooth user onboarding experience for your users. Empower your team with the ability to create product tours and guides with no coding."

**[IORAD](https://www.iorad.com/)** 
- [x] Free account created Th 6/9/22, with Chrome extension
Description: "Instantly make guided, step-by-step directions for any website directly in the browser."
### Secondary Software Solutions (⏳ permitting)

Crickets... 🦗🦗

### Rejected Software Solutions 🙅‍♀️

**[UIPATH](https://www.uipath.com/)** 
Not testing because they only have a downloadable Windows app
The Task Capture feature/app looked interesting

**[FLEEQ](https://www.fleeq.io/)** 
Not testing this because they offer "bitesize videos" and lack the automation I'm looking for here; this is basically serial Snagit with annotation (take a screenshot, highlight/mark up/annotate, and create a GIF or video of the steps)

**[CLOUDAPP](https://www.getcloudapp.com/)**
Not testing because this looks mainly focused on video and GIF capture, with manually added annotations and feedback options (only?); the product is also download only and I suspect they don't offer a Mac version; the demo is behind a sign-up so I can't get a good sense of the product without giving them my info

**[LOOM](https://www.loom.com/)**
Not testing because while this was suggested as a Scribe alternative, it seems focused on video messaging only

**[BLUEPRINT](https://www.blueprintsys.com/)** 
Not testing because this seems more focused on analysis than documentation, does not offer a free trial, and would require a request for a demo

**Comment by KaroEngstrom** [comment]
### Project Plan

| Time      | Planned Tasks |
| ----------- | ----------- |
| 8am      | Finalize test process       |
| 9am   | Launch Standup?        |
| 10am   | Test and document Tango        |
| 11am   | Test and document Scribe        |
| 12pm   | Test and document Userguiding        |
| 1pm   | Break - City PE Class        |
| 2pm   | Test and Document Lorad        |
| 3pm   | Compare and write finals notes        |
| 4pm   | Presentations Standup?        |

**Comment by KaroEngstrom** [comment]
### Test Process Overview 
- Testing a short Add Violation sequence in the draft ROW Court Case Management Portal 
![DiscoveryDay_TestProcessSteps](https://user-images.githubusercontent.com/100615928/173079673-edf0ad81-e849-42e9-8bc2-eb57fcb512cb.gif)
For the actual tests, I'll add the step of adding a new people record as well (excluded from the example for length) to specifically test how the software handles the pop-up screen

**Comment by KaroEngstrom** [comment]
### Comparison Chart 📊

### Recommendations 👍

### Further Stuff to Look Into 🕵️

**Comment by KaroEngstrom** [comment]
### Plan to Present for the Team 

* 5 minutes max 
* Quick intro 
* Tango in a Nutshell
* Scribe in a Nutshell
* Iorad in a Nutshell
* So Many Nutshells...what's the verdict?
