### ISSUE TITLE
Connect to Data Tracker data — signals and school zones

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#956]

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/6fc0a83f-7387-4e41-a0aa-2b57a4504da7)

**Comment by SurbhiBakshi** [comment]
[ ] Will need to regularly upload new locations from Data Tracker.

**Comment by SurbhiBakshi** [comment]
- [ ] Have added a basic email trigger when a new location is added by LLeff. Might need to add to/ refine the email to include more details. ![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/bd04994a-e6b1-4eda-8a95-b0140efe7e46)

**Comment by SurbhiBakshi** [comment]
- [ ] Example of a long street segment passing through districts and that will need a reference map.
- [ ] Need help with removing extra text.


![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/1129213c-20ce-41bf-8e92-edb936cd9f58)

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/6283fdfc-b87d-4d24-97e8-f5b63ee71272)

William Cannon is the link between Escarpment and 290.

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/fe7c300b-3de4-4bbb-a0cc-8e82a9ab37f3)

**Comment by amenity** [comment]
No longer applicable, see https://github.com/cityofaustin/atd-data-tech/issues/1260.
