### ISSUE TITLE
Review and refactor list of phases and milestones for PD & TE

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#9593]
Need to provide clear specs to dev team on what updates these tables will need to add more workgroups. 
# To-do
- [x] @johnclary - get Amenity the current state of [these tables](https://docs.google.com/spreadsheets/d/13EbvdJNoZRCXQOJZJdrUqTUb2-o2puMXhiZN_94_go0/edit#gid=33802623) in the database
- [x] @johnclary ~update doc~ update Moped `/dev/lookups` view
- [x] @johnclary - post in Teams for discussion

Cody S requested these after an exchange via email:
- Draft Study Submitted
- Draft Preliminary Schematic Submitted
- Need to Assign Study

**Comment by johnclary** [comment]
i sent the current phases and milestones to @amenity via slack

**Comment by amenity** [comment]
@johnclary please 
- Add "Related phase" to the [Milestones lookup values documentation](https://moped.austinmobility.io/moped/dev/lookups)
- If possible, add anchors in to the heading HTML on that page so we can provide direct links to each section

**Comment by johnclary** [comment]
I opened https://github.com/cityofaustin/atd-data-tech/issues/9973 for the task of creating three new milestones.
