### ISSUE TITLE
[Meeting] Review proposed enhancements with stakeholders

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#9602]
Set up meeting with stakeholders to determine how we should use the "Received Items" if inventory planners will be involved in the process and show proposed enhancements. 

# 7/27
Talked to AMD stakeholders on 7/26 to get agenda together to talk to Finance team.

## Finance Enhancements
- [x] Discussion: How Finance utilizes "Received Items" - Allow Inventory Planners access?
>Dan would like to keep these processes separate
- [x] Discussion: If received items needs to be separate, than show proposed [TEST Finance and Purchasing page](https://atd.knack.com/backup-apr-23-2021-finance-and-purchasing-system#order-report/) for order tracking
>Dan thinks it's fine to build out a different order tracking module in Finance and Purchasing 
- [x] [Enhancement] Search Purchase Request Items (Purchase Request | Purchase Request Items)
>Can move forward
- [x] [Enhancement] Unit Cost - increase decimal places to 4
>Dan does not think this is a good idea, high level of risk and work if this were to change.
- [x] [Enhancement] Add "Item ID" to Purchase Request Item table in PROD
>Can move forward

## To Do
- [x] Invite users:
- Diana, Dan, Ray, Johnny, Ronnie, Brian VDW, Brian C. (cc’d)

Meeting Scheduled - 8/2

**Comment by dianamartin** [comment]
# Add "Item ID"
![image](https://user-images.githubusercontent.com/21112975/182417266-c2a86dae-ac2b-4e57-bc9a-367d92866960.png)

# Unit Cost to 4 decimals
- Currently as a "currency" field
- Need to create a number field, extend to 4 decimal places
- Requires maintenance outage - users to not work in it
![image](https://user-images.githubusercontent.com/21112975/182417737-f97aca17-8877-4d10-aa1d-7fa4426e9e8a.png)


#  Search Purchase Request Items (Purchase Request | Purchase Request Items)
- Under `Finance and Purchasing>Reporting>Search Purchase Request Items`
- Would like this as a stand alone page or added to the "Advanced Search" page

## Search Inputs
![image](https://user-images.githubusercontent.com/21112975/182418066-6d28ec30-f8b2-48bc-98b1-88649673fe19.png)

## Search Table
![image](https://user-images.githubusercontent.com/21112975/182418128-ff1c7399-d683-44c2-982b-8127cddd4ab8.png)

## Current Advanced Search page
![image](https://user-images.githubusercontent.com/21112975/182418340-78527357-4691-404f-aa49-585b51dd8a38.png)

**Comment by dianamartin** [comment]
## Received Items - display when PR is Closed
- Add "Non-Editable" Received Items table

**Comment by dianamartin** [comment]
Moved discussion notes to what enhancements were approved on #9768
