### ISSUE TITLE
Implement new order tracking fields in TEST

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#9603]
Building out Order Tracking fields in TEST Finance and Purchasing
- new object table
- reference #9370

**Comment by dianamartin** [comment]
Improvements
- [ ] Add "Item ID" to Purchase Request Item table in PROD
- [ ] Comment: Order Notes:
- [ ] Follow-up Order Notes per item v. purchase request

Enhancement
- [ ] Advanced Search - Received Items (invoice_items) 
- [ ] Unit Cost - increase decimal places to 4

**Comment by dianamartin** [comment]
Had worked on this but forgot to document my progress
- [x] Re-ordered the fields and added additional fields to the Inventory Report page
- [x] Added new details page for "Item Details"
- [x] Added `order_tracking` object
- [x] Added `delivery_received` object
- [x] Created forms for "order tracking" and "add delivery"

**Comment by dianamartin** [comment]
This was shown to stakeholders and no further feedback was given.
