### ISSUE TITLE
Add column to table on "Camera Maintenance Priority" list

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#9606]
> What application are you using?

Data Tracker

> Describe the problem.

Adding work order status to [Camera Maintenance Priority summary page](https://atd.knack.com/amd#cameras-maintenance/?view_1484)

> Describe the outcome you'd like to see when this feature is implemented.

Having work order status as a column to Camera Maintenance Priority summary page

> Describe any workarounds you currently have in place or alternative solutions you've considered.

None

> Requested By
Allyson R.

Request ID: DTS22-104485

**Comment by Nate-Nader** [comment]
@amenity this one is for Data Tracker but i cant add you to the card or update it in anyway that is not a comment

**Comment by dianamartin** [comment]
This is the email Allyson sent to some of the stakeholders 6/30
>Comment Summary
•	Request to add work order status to camera maintenance priority summary page
•	Updated camera work order detail status
- [ ] Remove ‘to assign’
- [ ] Add ‘Assigned to CoA staff’
- [ ] Add ‘Assigned to Contractor’
- [ ] Add ‘Installed: MMC Verified’
- [ ] Add ‘Installed: MMC Not Verified’

**Comment by dianamartin** [comment]
Messaged Allyson 7/6
>Hey Allyson, question about the "Camera Work Order Status", did you want me to also remove the choice "Assigned"?
![image](https://user-images.githubusercontent.com/21112975/177623728-94cd5505-563c-4471-b0ba-eaef3fc01ae5.png)
>I already removed the "To Assign" choice
