### ISSUE TITLE
Reorder Inventory Report to match PR Tracker spreadsheet in TEST

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#9615]
After discovery meeting on 6/29. Talked to Brian V. and Ronnie about which fields they think they need in this new report page. Since had already prototyped a page in the Test environment, I was going to just adjust the fields in the system and add a few missing elements to make the table a bit better. 

- [x] Reorder the fields to be in the same order as PR Tracker spreadsheet
- [ ] Add `Purchase Type` - text formula to `purchase_request_items`
- ended up using the connected field but might go back to this if I can't control the display rules on the table without these fields
- [ ] Add `Purchase ID` - text formula to `purchase_request_items`
- ended up using the connected field but might go back to this if I can't control the display rules on the table without these fields

**Comment by dianamartin** [comment]
Prototyped an Order Tracking page

- Created new object: `order_tracking`
- Created new object: `delivery_received` 
- Created new Item Details page
- Created Tracking Info table
- Created Add Order Tracking form
- Created Deliveries Received
- Created Add Delivery form

![image](https://user-images.githubusercontent.com/21112975/176558541-3a8f4cfc-6b21-4590-bad4-5817cebd7d1f.png)

**Comment by dianamartin** [comment]
Gave link to Brian VDW for the inventory planners and AMD to review 7/12

**Comment by dianamartin** [comment]
This was reviewed with stakeholders, worked with them to update test the way they need to see it
