### ISSUE TITLE
Project Management Milestones

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#9659]
Include a page in the P3 Portal that captures the milestone for each phase on the pilot program workflow.

<hr>

![Screen Shot 2022-08-24 at 10.07.36 AM.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/3934e51a-8e3e-4f19-9e61-4be74219476c)
[Link to diagram](https://cityofaustin.sharepoint.com/sites/SmartMobility-PublicPrivateInitiatives/Shared%20Documents/Pilot%20Program%20Knack%20Workflow/01_Workflow/Pilot%20Program_by%20Phase.pdf)

**Comment by KaroEngstrom** [comment]
W 8/24/22 

- [x] Added milestone date fields into the `p3_business_case_analysis`object
- [x] Created a Details view on the Project Details page to display the Project Milestones dates 
- [x] Created a pop-up form for the PM to Add Milestone to the project to track important dates
![image](https://user-images.githubusercontent.com/100615928/186532303-9683796a-963b-4ccc-98ca-d59b1d66e241.png)

**Comment by patrickm02L** [comment]
Things to do:
- [ ] configure the milestone functionality like BCA attachments
- [ ] remove signature date
- [ ] add estimated date
- [ ] add other

**Comment by KaroEngstrom** [comment]
### M 9/12/22

After consulting with @dianamartin, simplifying to the following functionality: 
- [x] Cut down Milestones selection to manual entries only
- [x] Push BCA Exec decision to Project Milestones only when `Move Forward to Contract` where Milestone = Contract and  Notes = BCA Review Status 
![image](https://user-images.githubusercontent.com/100615928/189687577-7408a82a-8c6f-4301-9793-b8ae27749299.png)
- [ ] Add new Details view to show Executive Review results on the BCA Details page

**Comment by KaroEngstrom** [comment]
## M 9/19/22

Reviewed. 

**Tasks to complete before meeting with stakeholders:** 
- [ ] Make Milestones inline editable 
- [ ] Make sure Date Modified updates from that edit as well
- [ ] Make sure the table shows Milestone ordered by date 
- [ ] Add Delete Milestone column

**Comment by KaroEngstrom** [comment]
Reviewed 9/22/22 with stakeholders, all approved.
