### ISSUE TITLE
Add user Sharon M. to Data Tracker for Grant Billing

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#9663]
> What application are you using?

Data Tracker

> Describe the problem.

Need access to https://atd.knack.com/amd#home/ for grant billing process

> How soon do you need this?

Soon — This week 

> Is there anything else we should know?

Needed by 7/22/22

> Requested By
Sharon M.

Request ID: DTS22-104535

**Comment by KaroEngstrom** [comment]
Th 7/7/220

- [x] Heard back from Dan that this should be Viewer level
- [x] Added Sharon as a Viewer
- [x] Notified requester via Outlook
