### ISSUE TITLE
Set Up New Employee Kate L with Laptop, Business Phone, and Mifi

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#9690]
> What application are you using?

Data Tracker

> Describe the problem.

New employee setup.  Kate L. will start on July 18 and will need a laptop and a business phone number.  She will most likely need a MIFI as well.

> How soon do you need this?

Soon — This week 

> Is there anything else we should know?

Kate will be in the office on Wednesday to fill out paperwork.

> Requested By
Peggy M.

Request ID: DTS22-104580

**Comment by KaroEngstrom** [comment]
F 7/8/22

- [x] Urgency consult with Diana to get this done in the next few hours
- [x] Contact Peggy about creating a NERF, if not yet done
- [x] Contact Scott about the hardware items (Teams and Outlook)
- [ ] Follow up on all items

**Comment by mateoclarke** [comment]
Seems like this item is just part of our normal [New Employee Checklist](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-LzDGg7hKQ_fUjXnzGGx/onboarding/new-employee-checklist). 

@maccallump, we usually copy that checklist as a new issue and assign to the onboarding supervisor instead of going through the DTS Service Request process. I'm making a new issue to capture that and assigning to Peggy, Amenity and me. https://github.com/cityofaustin/atd-data-tech/issues/9702

One of the first steps in that checklist is the NERF form, which I started to complete but I don't have enough info about the new hire and I'll need Peggy's help.

**Comment by mateoclarke** [comment]
Nevermind, I found enough information and made a few guesses to complete the NERF form. Here is the SN Request Number: REQ0114464

**Comment by KaroEngstrom** [comment]
Closing this as #9702 has it covered
