### ISSUE TITLE
New Employee Checklist - Kate L

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#9702]
## Accounts - Team Lead
- [x] Submit a [CTM New Employee Request Form](https://atx.servicenowservices.com/sp?id=sc_cat_item_guide&sys_id=b714eb12db7a3f0021ccef92ca961972) for a COA network account, eAccess PIN/HR Portal, and phone 
- [x] Submit a [CTM service request](https://atx.service-now.com/sp) to add to DTS Distribution Email Group:
- [ ] Add "First Last Name" to email distribution list "ATD Data and Technology Service" ([ATDDataTechnologyServices@austintexas.gov](mailto:ATDDataTechnologyServices@austintexas.gov)) and "ACE ATD DL"
- [x]  Add to City of Austin Slack - austininnovation.slack.com
- [x]  Add to DTS Google Drive
- [x] Add to [Gitbook](https://app.gitbook.com/@atd-dts/spaces)
- [x] Add to [Austin Transportation Github Team](https://github.com/orgs/cityofaustin/teams/transportation/members) 
- [ ] Add to [DTS Presentation Template Team section](https://docs.google.com/presentation/d/1tHKTfUgQ-uAXdRBkEdXqR7ryBo_LTU86IzQxo1gJoeA/edit#slide=id.gfd2da31025_0_6) - two places
- [ ] Diana, Amenity, or Mateo add to DTS 1Password (if needed; we pay for seats)

## Hardware — DTS Systems Admin
Coordinate with DTS System Admin (Scott), make sure there is enough lead time for equipment to be acquired.
- [x]  Laptop
- [ ]  Monitors
- [ ]  Chair - check availability, ask Amenity/Peggy how we're handling this?
- [ ]  Power supply
- [x]  Keyboard
- [x]  Mouse
- [ ]  Docking station

## Calendar invites 
- [ ] Monthly Team Meeting — Peggy/Amenity/Mateo
- [ ] Sprints — Amenity
- [ ] Sprint Ceremonies — Apps/Dev: Amenity; Geo: Amenity 
- [ ] 1:1 — Supervisor
- [ ] First day: DTS Team Orientation — Amenity/Mateo
- [ ] First Week: DTS Product Ops — Amenity

**Comment by mateoclarke** [comment]
I've completed the NERF to the best of my abilities.
ServiceNow Request # REQ0114464

**Comment by mateoclarke** [comment]
I met with Kate today and added her to Gitbook, Github COA Transportation Team, and went through some of our basic processes and resources including Zenhub and Google Drive.

**Comment by mateoclarke** [comment]
Going to assume this is good to close.
