### ISSUE TITLE
Perform background research on failed checkouts

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#9735]
>Start by looking at the transaction history of each checkout to see how/when items were JV'd.

Review [WRK21-135015](https://atd.knack.com/amd#inventory/inventory-request-details/61bb8888472e0d001ea4777d/work-order-details/61bb8888472e0d001ea4777d)

Looks like the item was JV'd starting - 5/10/22

### 4/25/22

ID | Item Name | Quantity | Notes
-- | -- | -- | --
15951 |  120 AC Color VIVIDS Camera | 
15952 | Pelco SH-0537-PNC, 1 piece Tilt & Pan Camera Mount Bracket | 
15953 | Video surge suppression panel | 
15954 | Male, 75 ohm, BNC RG-59, Double Braid type, Coax Connector |

### 4/29/22
ID | Notes | Quantity | Notes
-- | -- | -- | --
15985 | Composite Camera Cable Double Braid 75 Ohm Coax | 342
15986 | Composite Camera Cable Double Braid 75 Ohm Coax | 111
15987 | Composite Camera Cable Double Braid 75 Ohm Coax | 540

**Comment by dianamartin** [comment]
So the 4 items were added 4/25 - in Review Needed status
turned to 4/27 - to NEED TO BE ISSUED
three more items add 4/29 -

**Comment by amenity** [comment]
@johnclary - do you have documentation on the inventory statuses? @dianamartin has been working with Ronnie on this and it's proving to be pretty complex to sort out.

**Comment by johnclary** [comment]
[this doc](https://docs.google.com/spreadsheets/d/1ymL2Wm-ohW6iWCPLaqgO3jttz9vISiSQ8AIpibgEUlo/edit#gid=1751853183) is the best i've got, but it's not complete.

@dianamartin i'm happy to look at this with you to show you how to trace where the different status rules are happening

**Comment by dianamartin** [comment]
Synced with John 8/4
**Proposed Solution, Need to Test

- [ ] Change rule 6 on "JV Status' - `inventory transaction`
CURRENT
- WO Inventory Status contains "Review"
- work_order_signals - is not blank
Set to - Not Ready

UPDATED RULE
- WO Inventory Status DOES NOT contains "Completed"
- work_order_signals - is not blank
Set to - Not Ready

(this should prevent the JV from being ready if there are any open transactions on the work order)
- Any transactions that haven't been issued or reviewed

![image](https://user-images.githubusercontent.com/21112975/182882628-93064c30-d78d-4f60-a3cc-781adcef1f06.png)

# Testing Scenario
- [ ] Add items
- [ ] Task order backchargeable - FDU flag is on
- [ ] Complete FDU Complete
- [ ] Complete Work Order
- [ ] Re-open 
- [ ] Try to add more inventory items
- [ ] See what the JV status does and document what happens

# Discussion Topics
Reopen - work order not have the ability to add more inventory. 
- If they reopen and FDU review complete, add materials to it, it by passes FDU review 
- They're going to go into ready to JV

**Comment by dianamartin** [comment]
@johnclary I just tested the JV rule update we talked about and it didn't seem to work. 
Test Steps
- Created WO
- Added Items
- made task "Billed Internally" - to trigger FDU Review
- Went to Inventory Request Status - Needs to be issued
- Issued Items --> Complete
- Inventory Request Status --> FDU Review
- Completed FDU review
- Closed Work Order
- Checked JV Statuses - went to "Ready"

- Reopened WO
- Added Items
- Went to Inventory Request Status - Needs to be issued
- Issued Items --> Complete
- Inventory Request Status --> Completed (**Rather than FDU Review!!**)
- Closed Work Order
- Checked JV Statuses - went to "Ready" (All 4 items went to "Ready")

**Comment by dianamartin** [comment]
@johnclary I don't know what we should do from here. When I tested it didn't seem to work.

**Comment by dianamartin** [comment]
@johnclary Should we try something else for this?

**Comment by amenity** [comment]
@johnclary @dianamartin [this continues to create headaches](https://github.com/cityofaustin/atd-data-tech/issues/9808#issuecomment-1366156993). 😞

**Comment by amenity** [comment]
The preparation for the next (January) JV will be done the week of January 16-20.

**Comment by amenity** [comment]
Opting to close this and [discuss revisions to the AMD inventory --> Finance workflow](https://github.com/cityofaustin/atd-data-tech/issues/11066#top)
