### ISSUE TITLE
[Feature] Hardware Management

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#9744]
> What application are you using?

Data Tracker

> Describe the problem.

Manage Hardware Module

> Describe the outcome you'd like to see when this feature is implemented.

This will serve as page that we could use to track tools and materials that the Superintendent and Supervisors will have access to. This will help with accountability of materials.

> Describe any workarounds you currently have in place or alternative solutions you've considered.

Currently using spreadsheet. Which is prone to errors.

> Requested By
Jorge G.

[Attachment](https://api.knack.com/v1/applications/595d00ebd315cc4cb98daff4/download/asset/62cf1bfcebbb31001e101f9d/capture3.jpg) (68.28kb)

Request ID: DTS22-104605

**Comment by amenity** [comment]
@dianamartin - do you have an idea what this is about?

**Comment by dianamartin** [comment]
@amenity Yeah, I was talking to AMD (Jorge, Ed, Billy) and it came up and I showed them something on the SMB app and they were like "we want that". They know that this is a backlog item, but would like to prioritize it in the fall. They've just submitted so they don't forget about it.

**Comment by dianamartin** [comment]
1. Track device assignments to technicians
3. Track high ticket item tools within AMD

Access will be only for Supervisors/Superintendents

**Comment by dianamartin** [comment]
- [x] Exported `hardware` table from SMB tracker
- [x] Clean up spreadsheet for import
- [ ] Created new `hardware` object in AMD Data Tracker

**Comment by dianamartin** [comment]
- [x] Added a new field "Written Signature" and it toggles the eSignature fields
- [x] Messaged Jorge 8/26
![image](https://user-images.githubusercontent.com/21112975/186995109-53f82ed0-5ca5-4c51-b2b8-2c8a019b980d.png)

**Comment by dianamartin** [comment]
# Equipment Table
![image](https://user-images.githubusercontent.com/21112975/186995470-ca8ab1c7-3c46-4c3e-9703-77bb3662a83d.png)

# Add Equipment 
![image](https://user-images.githubusercontent.com/21112975/186995511-dacd1a9c-66e9-4ab1-b598-ceb93b176a3b.png)

# Manage Equipment Type
![image](https://user-images.githubusercontent.com/21112975/186995573-08cbc27d-2115-446a-951a-35db0f0a2a24.png)

**Comment by dianamartin** [comment]
#8/26
Jorge replied
>Perfect. Thanks!

I replied
>I'll check in with you guys on Monday too

# 8/29 
Hey, checking in - get a chance to see the Hardware Management today?

**Comment by dianamartin** [comment]
Had added "Issue Date" but forgot to add it to the forms and tables. 
- [x] Added to the Add form, Edit form, Details page and Table view

Jorge said
>Can we add it to the table?
>perfect
