### ISSUE TITLE
[Feature] Cable Usage Tracking - Request Intake Meeting

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#9759]
> What application are you using?

Data Tracker

> Describe the problem.

Need a module to track cable usage, and location used at other than the inventory module. Cable is always a big issue for us because there is always discrepancies in the way its reported so we track it ourselves apart from the inventory planners.

> Describe the outcome you'd like to see when this feature is implemented.

Our team will be able to efficiently and effectively track and report cable usages and pair it to the location and work order. This will help negate any discrepancies in the quarterly and end of year inventory counts.

> Describe any workarounds you currently have in place or alternative solutions you've considered.

Currently we use a spread sheet to track this along with a fillable PDF I created which are prone to mistakes or not being submitted properly. We also have to jump back and forth from Data Tracker and the spreadsheet to pair everything together. This task is very time consuming and hard to keep up with.

> Requested By
Jorge G.

Request ID: DTS22-104620

**Comment by dianamartin** [comment]
- Access: Jorge, Ed and Billy only for this page

**Comment by ChristinaTremel** [comment]
### Billy's Reconciling Process

- SharePoint spreadsheet "Cable Truck Quantities" is a tracking form that only a few people have access to. Cables that Billy tracks are: 
     - COOP: for emergency response only
     - 5 cond
     - 7 cond
     - 20 cond
     - composite
     - twisted pair
     - double
- Yellow highlighted on the spreadsheet is the cable he's checked
- Cable is held securely and to get cable, the technician has to ask Billy or one of Billy's appointees (only 1 at all times) to release the cable to them. Billy or Josh will go to the inventory person and ask for the reel - inventory person sets the cable outside the secure area and the inventory people track that cable in their own way. They will tell Billy the reel number. 
- Each reel has a measurement embossed in the cable so we know exactly how much is there.
- **Two thing happens when a tech uses the cable:**
     - Whoever completes the work order marks the beginning and ending footage on the Data Tracker work order. Footage is included in the notes part of the module.
     - Tech contacts Billy's point of contact (currently Josh) via phone, email or text and text them the cable type, number, and footage.
 
- **To check the cable usage:** Billy looks at Transactions of the cable in Data Tracker and if it's correct, he highlights the spreadsheet. Currently he can't check the transactions on Data Tracker to confirm he's already seen it. Billy would like having that on Data Tracker. 
     - Reason for tracking it to this depth is because they need to keep track of all cable at all time

### Short Term Solution: 
- Billy would like to have a way to mark the transactions on Data Tracker to show that he's already looked at that transaction. A field to mark the line item as checked. 
- Add field to transactions list "Cable QC"
- Billy would like that field to highlight if it has been checked
- Only editable by Billy or someone Billy assigns (specific user)
- Include a beginning, end, and calculated footage field

### Long Term Solution
- When selecting a cable inventory item on the work order, have fields available to track "Beginning" footage and "End" footage
- Also a new calculated field to find the amount of cable used
- Cable Management Data Tracker Page:
     - Vehicle the cable comes from
     - Line items for inventory type - unique value will be the reel number
     - More advanced thing is it would take the technicians numbers and add it to this table

**Comment by dianamartin** [comment]
# Diana's Notes
## Current Process

- Data Tracker>Inventory Items
    - In secured inventory
- SharePoint Cable Truck Quantities (access: billy, josh, edward, jorge)
    - yellow highlight, confirm in Data Tracker and in this list

3 Cable Trucks

Technicians need cable reel for a work task

- Billy and Josh (backup)
    - will go to inventory personnel (Ray)
    - gets reel of 5 conductor
    - documents in their own way (new process system) - releases reel of cable
    - Reel #13 (5 conductor)
    - Pulls cable off truck
        - Email fillable PDF
        - Text cable type, forwarded back and forth
        - Usage email -
    - Technicians enters on work order, beginning and end and footage
        - Note in inventory item (line item)
    - Looks up Inventory - using commodity code
    - Reviews inventory transactions

Reason:

- Keep up with all cable
    - *“Cable didn’t cost that much”*
- Check out all cable, check out to operating budget
- Problem with that huge hit to the budget, buying it every year
- 400 TKs, 250 are reimbursable
- transfer those funds back
    - too much of a hassle
- 

5 conductor

7 conductor

20 conductor

composite

twisted pair

double

### COOP

- several trails at airport for emergency response

## Short Term Solution

- Handed to a new person/employee
- [ ]  Add a check box “Cable QA” on `Inventory_transactions`
    - [ ]  Yes/No

## Long Term Solution

3 trucks

multiple variety of cable on it

9 reels of cable

- Laptop
- Tablet
- MiFi

Temps

- Only Josh has a laptop

- [ ]  New field “Beginning” (required)
- [ ]  New field “End” (required)
- [ ]  New field “Footage” (required)
- [ ]  New field “Difference” (auto-calculated)
- [ ]  New Page “Cable Management” module

**Comment by ChristinaTremel** [comment]
Created [11440](https://github.com/cityofaustin/atd-data-tech/issues/11440) and [11436](https://github.com/cityofaustin/atd-data-tech/issues/11436) to address issues discussed in the meeting.
