### ISSUE TITLE
Create Transfer of Ownership Documentation for Contractor Items 

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#9766]
> What application are you using?

Data Tracker

> Describe the problem.

Transfer of Ownership Documentation         Currently Materials are transferred between contractors and COA for jobs in advance but materials seem to get misplaced or used at a different location. When its time to do the job the items were intended for there's a we gave it to you and a no you didn't conversation that takes place with the materials magically appearing after the job has been completed.

> Describe the outcome you'd like to see when this feature is implemented.

Our team would be able to keep track and hold involved parties responsible for the loss or damage to materials given to us by a contractor or given to a contractor by us.

> Describe any workarounds you currently have in place or alternative solutions you've considered.

Currently working on a paper version of this form. The issue with this would be keeping up with all the different sheets for different locations and materials it also isn't easily searchable when looking for a specific item or location.

> Requested By
Jorge G.

Request ID: DTS22-104650

**Comment by KaroEngstrom** [comment]
@dianamartin I couldn't tell if this is a duplicate of #9765 or asking for something different

**Comment by dianamartin** [comment]
This can be handled in one new page "Manage Equipment"
- Specifically for COA items, loaned out to Contractors

**Comment by dianamartin** [comment]
I closed out #9755 as a duplicate and kept one open. 

Current Process
- Roman has a sheet that he's currently tracking
- Paper copy, can get lost easily

**Comment by dianamartin** [comment]
@dianamartin @KaroEngstrom @ChrispinP I'm going to look for the paper version of this or get it shared with us so we can prototype something in the system.

**Comment by dianamartin** [comment]
Jorge emailed this form template to me
![image](https://user-images.githubusercontent.com/21112975/187251178-8b59b6a3-193e-4acf-a53f-62d34977f1a9.png)

# Key fields: 
- Location
- Date
- COA Employee Name
- Contractor
- Quantity
- Item/Item Description/ Commodity Code
- Serial Number
- Notes
- COA Signature
- COA Printed Name
- Contractor Signature
- Contractor Printed Name

**Comment by dianamartin** [comment]
# Build Discussion
- Inventory Request 
- Manage Equipment

**Comment by KaroEngstrom** [comment]
9/2/22

* Do Contractors use the existing inventory? 
* If yes, then connection 
* If no, is there a separate inventory? Or just tracking of transactions? 

* Line items 

* Single transaction and line items with multiple quantities 
* Transaction types - CHECK IN/CHECK OUT/?

**Comment by KaroEngstrom** [comment]
**Meeting notes 9/6/22**

**Comment by KaroEngstrom** [comment]
## Prototyping Notes
- @KaroEngstrom and @dianamartin were planning this out in Data Tracker PROD on 9/7/22 
Drafted the following: 
- objects: `transfer_of_ownership_request`(**FORM**)  and `transfer_of_ownership_transactions` (**ITEMS**)
- pages: 
![image](https://user-images.githubusercontent.com/100615928/189222221-66ee7653-76a1-41cd-8e40-9c6235fd5d59.png)

### **9/8/22** 
- @KaroEngstrom checked in with Jorge: he would like **Contractor to be a multi-choice field with ability to add new** names as needed. I advised him that this will require best practices from submitters to not enter duplicates and always search existing Contractor list for accuracy. Jorge added: "I will work on getting you all the names for the contractors, staff, and ppl who need access."
- tidied up names, added all the fields (signature, Contractor, Commodity Code, etc.) for existing forms, tables, and Details pages

**Comment by KaroEngstrom** [comment]
### W 9/14/22 

**Updates to complete from Builder Sync** 
-----
- [ ] Forms Table on the home page: add **Count** of items column; add **Transfer Summary** field for brief items summary/purpose
- [ ] Add **Transfer Summary** field to the initial Add New Transfer Form 
- [ ] Add **Notes** to the initial Add New Transfer Form 
- [ ] Add pop-up table of the ATD Location to the initial Add New Transfer Form 
- [ ] Add display rule to the initial Add New Transfer Form  - based on TO or FROM selection, the Contractor field will reinforce the transaction type by showing **To Contractor** or **From Contractor**
- [ ] Make Edit Item form return to parent page on submittal 
- [ ] Update Signature block by modeling it after the Manage Equipment signature block (accessible option) 
- [ ] Add Item Description field 
   - [ ] to Item object
   - [ ] to Item form 
   - [ ] to Item table 
   - [ ] to Item Edit form 
- [ ] Add a Display Name field to the Form object (Form Number - Transfer Type - Subject)
- [ ] Add Display Name field to the Forms table 
- [ ] Add Display Name field to the Forms Details page 

**Talking Points and Internal Notes for the Follow-up Meeting** 
-----
- Will the Contractors need to have account access? Log in; My Forms views
- Should ATD be a specific person who signs as well, or is the logged-in Created By capture enough? 
- Pivot table for reporting?

**Comment by KaroEngstrom** [comment]
## Th 9/15/22

Jorge wants his team of three admins to have control over:

- adding new users from his team (folks who can to create new transfer forms and view/search them as needed)
- adding and removing Contractors from his list (the list is companies only: Mastec; ATS; Siemens; EARTC)

### One option: 
**CONTRACTORS as Accounts**

- Add contractors as accounts with no associated person and with a non-functional email. This allows them to be a Connection to choose from and lets J’s team have control to add and inactivate.

**CONTRACTOR TRANSACTIONS ADMIN TEAM**
- Create a new Contractor Transactions Admin (CTA) role. Add the three admin in this role and allow CTAs access to the existing Account Admin page in Data Tracker.
- Create a Page Rule on the Account Admin page that allows the CTAs to see only their own dedicated tables, which would include their own systems users and contractors (not all of Data Tracker). Jorge is already an Account Admin so he would see everything.

Checking with Apps team before implementing.

**Comment by KaroEngstrom** [comment]
**Custom Code Item** 
-----
- [ ] Add pop-up table of the ATD Location to the initial Add New Transfer Form 
Example from TIA: 
![image](https://user-images.githubusercontent.com/100615928/190240992-458d60ac-a4e5-4239-a702-a5bc9c6ceea6.png)

**Comment by KaroEngstrom** [comment]
# W 9/28/22 Meeting Notes 

- Allyson and Lance joined; the requesting team indicated that they would not need to be adding any locations 

## Items to Update for Go-Live
- [ ] Add a `Storage Location` connection that mirrors the `Contractor` object in function - ONLY supervisors can edit and add; include initial choices **Bullpen** and **Working Stock Shelving** 
- [ ] Create a `Manage Storage Location` link in the bottom-of-the-page menu next to the `Manage Contractors` button
- [ ]  
- [ ] Add the link to the Transfer of Ownership forms under the AMD menu on the Data Tracker home page 
- [ ] Schedule a 30-minute follow-up meeting to review and launch go-live

**Comment by dianamartin** [comment]
# Transfer of Ownership for Contractor Items Notes - 9/28

## Actionable Items

### Create new field "Storage Location"
- multi-choice: 
- add choices

### Create new field + "Status" (Parent-form)
- At Storage location
- Sent to location

### Create new field + Status Comment - form/table?

### Create new field + "Are you tracking a Serial Number?" (Multi-choice- radio or Y/N)
Yes - Serial Number field
Hide Quantity field
Record Rule - Quantity: 1

No - Serial Number
Show Quantity field
Hide Serial Number field

- [ ] Add button under "Arterial Management Operations" - Contractor Transfer Forms

**Comment by KaroEngstrom** [comment]
## 10/6/22 Go-live Meeting

**Comment by dianamartin** [comment]
# Last Check-in
Pilot Period until 10/31/22

Pilot period until the end of the month. 
- [ ] Check in 10/31
- [ ] Remove any test items

**Comment by KaroEngstrom** [comment]
## T 11/1/22 
- Not seeing any test items in the system 
- Emailed Jorge, Billy, and Edward to check in at the end of the pilot period
