### ISSUE TITLE
SMS Sprint Review 7/15 - Action Item Tasks

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#9774]
## EOI
"Other" - have explanation on No Smartphone Option
- [x] display rule, new field

## Email - resource account - Shared Mobility inbox
- [x] Creating email for Shared Mobility inbox
![image](https://user-images.githubusercontent.com/21112975/179319283-ce8a8563-df71-4e4c-932c-7efadd87d404.png)

## Review Dashboard
- [x] Consolidating Menu
![image](https://user-images.githubusercontent.com/21112975/179318473-e6072995-143d-40b6-ac74-017cab74a8de.png)
- Expression of interest 
- Applications

- [x] Add Banner on Change Status page 
Remind users to not select "Approved" status until permits have been entered.
![image](https://user-images.githubusercontent.com/21112975/179318942-d91ef08c-4e19-4a59-9024-b75a2e323698.png)
- this will only show when in "Pending Approval - Permit Team"

## Formalize Resources
- [ ] Cheat sheet of statuses - GitBook
- [ ] SMS Reviewer Workflow

## Testing
- SMS testing period
- Provider testing period

**Comment by dianamartin** [comment]
@patrickm02L this is ready for review

**Comment by patrickm02L** [comment]
@dianamartin I tried to test the "Stand-up Scooter" account to see if the pop-up banner would work. I'm not seeing a banner, however.

**Comment by dianamartin** [comment]
@patrickm02L the banner only shows when the status is in "Pending Approval - Permit Team" because it's supposed to be the status before "Approved".

**Comment by patrickm02L** [comment]
> @patrickm02L the banner only shows when the status is in "Pending Approval - Permit Team" because it's supposed to be the status before "Approved".

I see it now.

![Screen Shot 2022-07-18 at 9 05 04 AM](https://user-images.githubusercontent.com/5566727/179529238-f0de1293-af54-47dc-91a2-822f88f638ab.png)

Everything checks out.
