### ISSUE TITLE
Update "Journal Voucher" info in AMD Data Tracker - Warehouse Inventory- JUNE 2022

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#9827]
- [x] Spreadsheet emailed from Finance staff month of: FILL JUNE 23 2022
- [x] Number of records being updated: `152`
- [x] Format spreadsheet [(Review instructions)](https://atd-dts.gitbook.io/atd-knack-operations/warehouse-inventory-updating-journal-vouchers-jv-information)
- [x] Spot check Transaction IDs, no JV information before import
- `16611`
- `16542`
- `16244`
- [x] Import records
- [x] Spot check Transaction IDs, no JV information after import
  - [x] `16611`
  - [x] `16542`
  - [x] `16244`
- [x] Email Finance staff that update task complete

**Comment by dianamartin** [comment]
![image](https://user-images.githubusercontent.com/21112975/180348833-2abbd465-89a7-40cf-925d-efefbe9de255.png)
Start Import: 9:20 pm
End Import: 9:23 pm

**Comment by dianamartin** [comment]
Crystal emailed 7/25
>Please process additional entries for June JVDAs.  The list I sent you had a filter that hid the last 40+ rows for some reason and I didn’t notice.  Sorry for the additional work, thank you so much for your assistance.  

I created new issue for 2nd batch load #9844
