### ISSUE TITLE
Issue bulk work orders for electronic lock task (e lock)

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-data-tech#9830]
> What application are you using?

Data Tracker

> Describe the problem.

AMD is getting ready to roll out citywide Signal Cabinet Security Upgrades.  We need to issue WRKs to all signals so e-locks (inventory) are charged to appropriate location.  Can DTS help to create a batch of WRKs for this purpose.   There will be 2-3 inventory items per signal (per WRK).  

Additionally -- after project is completed we'll need to add serial number information from vendor website to traffic signal assets - cabinet front door, cabinet back door and BBS cabinet

> Describe the outcome you'd like to see when this feature is implemented.

ATD deployment staying on target by not having to create 1100 individual work tickets in data tracker. 

> Describe any workarounds you currently have in place or alternative solutions you've considered.

Besides assigning e-locks to each location (via serial number thru vendor application)  he will have to create one work order per location to charge the lock to inventory.  

> Is there anything else we should know?

Mid August - pilot corridor (25-30 signals)
Mid September - expected deployment of e-locks to 50 signals
October - September - e-locks citywide.

> Requested By
Ivonne N.

Request ID: DTS22-104730

**Comment by dianamartin** [comment]
Brian talked to me about this one, we talked about me providing him a template for batch uploading. I guess he delegated this to Ivonne, I'll make sure to give that to her then.

**Comment by dianamartin** [comment]
Related to #9762

**Comment by dianamartin** [comment]
Messaged by BC 8/22
>Let me know when you have some time to talk about the bulk import for Work Ticket creation
- I was out for jury duty

Messaged by BC 8/23
>Do you have time to quickly talk about the template?

Synced with Brian C. 8/23
- I told him which fields are not necessary to populate.
- We fixed some funding fields entry on the template work order
- [ ] Export table and email to BC

**Comment by dianamartin** [comment]
# Testing
- used template I gave Brian to see what it would be like to import the datasets in `TEST | Austin Transportation Data Tracker | 27 OCT 2021`
- it came in weird, the `LOCATION` field is blank - I think it's because the "LOCATION ID" isn't being populated.

**Comment by dianamartin** [comment]
# 8/25
## Testing in Austin Transportation Data Tracker | PRODUCTION
using template spreadsheet, 2 records only
- Made created date 8/8/22 
- Added "TESTING, DO NOT PROCESS"
- First attempt without "LOCATION ID" field populated

**Comment by dianamartin** [comment]
# 8/26
Reviewed Inventory Item - form - must have fields
- Item
- Quantity
- Source
- Comment

## Testing
- [x] Cleaned up transaction template
- [x] Test inventory import on `WRK22-156260`
- [x] Two inventory records came in correctly

Emailed BC 8/26
> As promised, I’ve updated the templates for you and tested importing in the work order and inventory template. They worked as expected for me and associated to each other.

>Attached Files:
- 20220823_eLock_AMD_Work_Order_Template – WORK ORDER TEMPLATE
- 20220825_locations – LOCATIONS LIST
- 20220825_inventory_transactions_eLocks – INVENTORY TEMPLATE
  - Will have to wait until I’ve uploaded the work order records to get the work order IDs
- 20220825_work_orders_signals_scheduled_work_eLock – SCHEDULE WORK TEMPLATE
  - Will have to wait until I’ve uploaded the work order records to get the work order IDs

Let me know if you have questions.

**Comment by dianamartin** [comment]
# 8/30 
Brian emailed me the work order template back to import into the system. 
>Here is the template with all of the locations that we need Work Orders create for. 
[20220823_eLock_AMD_Work_Order_Template_BWC.csv](https://github.com/cityofaustin/atd-data-tech/files/9456093/20220823_eLock_AMD_Work_Order_Template_BWC.csv)

**Comment by dianamartin** [comment]
Brian replied 8/30
>This looks good
Yes please delete  - WRK22-151740 - 07/14/2022 12:43pm – UNASSIGNED

# 8/31
- [x] Opened original file, deleted first two records since they were imported on 8/30
- [ ] Renamed the file `import_THE_REST_20220823_eLock_AMD_Work_Order_Template_BWC`
- [ ] Import Page showed `1067 records` being imported
![image](https://user-images.githubusercontent.com/21112975/187700786-05c3c6b1-b131-4aba-affc-b3117338c2a2.png)
- [ ] Query for records, spot check
- [ ] Export WO list
- [ ] Email Brian

**Comment by dianamartin** [comment]
Brian emailed me on 9/1
>Here is the Inventory info. Fingers crossed everything works

I accidentally archived it, but he ping me back on 9/12
>Have you tried importing these yet?

I replied 9/12
>Thanks for the nudge, I think it got archived in my email because I thought it was something else. I thought I was still waiting for this information. I just moved to my inbox, will let you know when it’s all imported.

**Comment by dianamartin** [comment]
# 9/12
- [ ] Reviewed spreadsheet that BC provided
- [ ] Created new spreadsheet with 2 test records in it for one work order: `WRK22-156790`
- [ ] Will import 2 test records
- [ ] Spot check 
- [ ] Import the rest of the inventory transaction records

**Comment by dianamartin** [comment]
Emailed Brian 9/12
>I’ve been able to upload the “inventory items” and associate them to the bulk imported work orders. I spot checked these one and they looked correct. 

>• WRK22-156790
>• WRK22-158510 
>• WRK22-159735 
>• WRK22-162115
 
![image](https://user-images.githubusercontent.com/21112975/189768223-77508db5-6023-4602-a489-ac6e78cc29bf.png)

>Let me know if there is anything else I can do for you.

**Comment by dianamartin** [comment]
Brian has not required any further modification, he will submit a new request for the other bulk import he wants to do.
