### ISSUE TITLE
Review APWA requirements

### ISSUE THREAD

**Issue by maccallump** [cityofaustin/atd-data-tech#9835]
Requirements:

- [x] Review APWA certification chapters
- [x] Create list of necessary items
- [x] Identify stakeholders
- [x] Create schedule
- [x] Create sprint cadence

**Comment by patrickm02L** [comment]
In Sprint Planning 9/8/22
- Created a schedule
- Created sprint cadence
- Kate and Peggy need to identify who would be good leads for every practice - 42 practices 
- 9/9/22 Kate is meeting with Diana and Karo about Sharepoint - will need clarity of permissions for Leads and SMEs
- Once Kate has access to AWPA she'll be able to identify libraries needed

Things to do
- [ ] @katelunceford to set up meeting with Traffic operations
- [ ] Kate is working on creating APWA account. Submit a ticket

**Comment by patrickm02L** [comment]
9/22/22 Update
- Planning @maccallump is helping with setting up Traffic operations meetings. 
- Kate needs to identify model practices
- Kate is also working on creating user guides and finishing up the tools page (deadline target 9/30/22) 
 - ATD procedures template. Will use this as an example to inform the ROW procedures
- User guide is in a slide deck, and Kate will also create user videos for each step.

**Comment by patrickm02L** [comment]
Chatted with Kate on 10/27/22, all the tasks in this Issue have been completed.
