### ISSUE TITLE
[MEETING] Post AMD Work Order Pilot Sync

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#9837]
### Objective 
To learn about that last week of user testing that AMD has with the new work order pages. 
- What went well
- What needs work
- Other insights

### Participants
Jorge, Ed, Miles, Diana

### Agenda
Add agenda here or create agenda from [this template](https://docs.google.com/document/d/1d_49KW5C_vSz8Bs50v-cxyIJuTNJMwMrh7ypcxRHgZI/edit#) and add link. 

------
- [x] Schedule meeting - 7/25
- [ ] Optional: Schedule debrief
- [x] Meet and take notes
- [ ] Optional: Debrief with DTS team members
- [ ] Create resulting issues

**Comment by dianamartin** [comment]
To ask Billy 
Can we add:
- Scheduled Work
- Completed Work
>Billy said yes we can go ahead and add it
Miles had said he was saying how he had to open up many windows for enter his work order information

Remove old field sections
- [ ] Remove the old sections

Inventory
We added the "no inventory used"' - quantity of 99,999
