### ISSUE TITLE
Update "Journal Voucher" info in AMD Data Tracker - Warehouse Inventory- JUNE 2022 (2nd Batch)

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#9844]
Crystal T. 
Finance

Emailed June, part 2
>Please process additional entries for June JVDAs.  The list I sent you had a filter that hid the last 40+ rows for some reason and I didn’t notice. 
- [x] Spreadsheet emailed from Finance staff month of: `June 23, 2022`
- [x] Number of records being updated: `39`
- [x] Format spreadsheet [(Review instructions)](https://atd-dts.gitbook.io/atd-knack-operations/warehouse-inventory-updating-journal-vouchers-jv-information)
- [x] Spot check Transaction IDs, no JV information before import
- `16100`
- `16132` - NOT READY
- `15921`
- [x] Added, further inspection of records 
- [x] Import records
- [x] Spot check Transaction IDs, no JV information after import
  - [x] `16100`
  - [x] `16132`
  - [x] `15921`
- [ ] Email Finance staff that update task complete

**Comment by dianamartin** [comment]
Noticed that some records seemed like they were in "Not Ready" status. 

Emailed Crystal 7/25
>I was doing some spot checks before I imported and noticed that some of the transactions are in a JV Status – “Not Ready”.. so right now I’m going through the list of 39 records to double check them.

>So I finished reviewing the 2nd batch of records (39 records) and 17 of them were in the JV Status “Not Ready” for Work Order # WRK22-145305. There are 20 items on the work order but seemed like 3 records might’ve been JV’d already. 

We synced around 4:30 pm and showed her what's going on. She's going to reach out to Ronnie to check if the financials are good, if so she'll let me know to process them.

**Comment by dianamartin** [comment]
I synced with Ronnie 7/26 and gave him the run down on what was happening, he said he'd take a look and responded:
>Since this entire work order was actually JVd in June, there is no current funding shortfall in 8119 2507 L057.  That only appeared to be the case because this work order did not appear to have been JVd.  

>I think once the TK and FDU information on WRK22-145305 is changed (back) to 24ART01165 and 8401 2507 1109  and it is removed from the FDU Review queue that this work order is totally completed.

**Comment by dianamartin** [comment]
Need to update Work Order: `WRK22-145305`
  - [ ] Fund - from `8119` to `8401`
  - [ ] Set FDU Review Complete from "No" to "Yes"
  - [ ] FDU Review Required?
- [ ] Change all transactions on WRK22-145305 to

**Comment by dianamartin** [comment]
Emailed Crystal & Ronnie
>Hi Crystal, 
I’ve updated the Journal Vouchers for June 2022, the 2nd batch this is the filter for all of them (1st and 2nd batch) – 191 records.

>The records that weren’t JV’d on Work Order: WRK22-145305 were updated so they were no longer in “Inventory Request Status” – Review Needed. They are all “Completed” and were also JV’d. 
>- Work Order: WRK22-145305 filter 

>Let me know if there is anything else I can help with.
