### ISSUE TITLE
Update "Journal Voucher" info in AMD Data Tracker - Warehouse Inventory- JULY 2022

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#9881]
- [x] Spreadsheet emailed from Finance staff month of: July
- [x] Number of records being updated: 328
- [x] Format spreadsheet [(Review instructions)](https://atd-dts.gitbook.io/atd-knack-operations/warehouse-inventory-updating-journal-vouchers-jv-information)
- [x] Spot check Transaction IDs, no JV information before import
- [x] Import records
- [x] Spot check Transaction IDs, no JV information after import
- [x] Email Finance staff that update task complete

**Comment by ChrispinP** [comment]
Completed update. Pending feedback on the 8 records that are missing data.

**Comment by ChrispinP** [comment]
Finished update for remaining 8 records. Sent email to Finance, complete

**Comment by dianamartin** [comment]
@ChrispinP In the future if you do any JV imports, we usually send out a link to the JV'd items in a filter like this 
![image](https://user-images.githubusercontent.com/21112975/182479105-5c34b810-9b2b-4b82-b6f2-6914f02ca2bb.png)
