### ISSUE TITLE
Configure ESB with Paging Activity enhancements in Data Tracker

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#9960]
Had discussion with John on 8/8

We looked at some SRs with paging activities:
- `22-00277229`
![image](https://user-images.githubusercontent.com/21112975/183470188-2773831b-f227-44d6-a6ca-98887176152f.png)
- `22-00284522`
![image](https://user-images.githubusercontent.com/21112975/183470424-1765acbc-36c9-49d6-afbc-095ab864f19c.png)

## Creating object & pages
had to create a new status on the `tmc_activites` object
- [x] `ACTIVITY_OUTCOME` - multi-choice
  - choices: Incomplete, Complete
- [x] Create new page "Paging Activities"
- [x] Copy "Activity" table from MMC Details

## Set Activity Outcomes on 
- [ ] MMC Details, Add new activity to "Complete"
- [x] Work Order Details, Form Rules for submitting work order  - when updates Repairs Complete, also add new rule to make outcome "Complete"

## Get Feedback from stakeholders
- get feedback from AMD supervisors and superintendents to see if this works for them

**Comment by dianamartin** [comment]
@dianamartin Configure this soon, planning to work on it at the end of the week
- Needs to set up "Activity" fields

@johnclary Testing needs to be completed on this before Oct 6th. We might need to schedule this with Robert.

**Comment by dianamartin** [comment]
# 9/29
Configured the **TEST - ESB ENV - AMD Data Tracker | 19 APR 2022** environment
- [x] Created `Activities` table - Activity Outcome = Incomplete & Activity Name = Paging On call staff
- [x] Created `Activities` table - Activity Outcome = Complete & Activity Name = Paging On call staff
- [x] Added `CSR Issues` table below, filtered to show only "New" and "All" - as a reference
- [x] Updated record rule for "Work Order Details>Submit Work Order" to make "Activity Outcome" = Completed

There should be another rule applied on the Activity form, but I think I might some help on this one. There are a lot of rules.. @johnclary

**Comment by ChristinaTremel** [comment]
@dianamartin can you check if this issue is complete?
