### ISSUE TITLE
Create Documentation for new AMD Work Orders for technician training

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#9961]
on `AMD Data Tracker | Help Guides` page, created new group "Work Orders" in [GitBook](https://atd-dts.gitbook.io/amd-data-tracker-help-guides/work-orders/new-work-order-or-trouble-call)
- [x] added page: New Work Order | Trouble Call
- [x] added page: New Work Order | Scheduled Work
- [x] added page: Submit a Work Order | Technician
- [x] added page: Closed a work order | Supervisor

**Comment by dianamartin** [comment]
Synced with Billy for a few minutes to ask him about the work order help guides to see if anything needed to be changed. He said to get with Jorge next week since he's out this week.

**Comment by dianamartin** [comment]
Sent link to Jorge on 8/16 via Teams messenger, he was able to review.
