### ISSUE TITLE
Enhancements for HR Employee Surveys

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#9965]
Enhancements requested by the stakeholders:

- [x] 1. Can we retitle the staff form from “Supervisor Surveys for Employee SSPRs” to “Onboarding Surveys for New Employees”  and 
- [x] 2. Can we retitle the employee form from “30 Day Employee Follow-ups” to “Employee Onboarding Survey”. 
- [x] 3. Could we also add a note and progress section on the HR employee tracking side?  Something similar to what you added to the supervisor side would be great. 
- [x] 4. On the 90 Day Survey, question 2. Can we move “Check all that apply” above the options? See below. 
 ![image.png](https://images.zenhubusercontent.com/5da61135c9a7f8000179986e/598503df-750e-47d4-acae-920594389df5)
- [x] 5. On the 120 survey, can we edit question 5 to ask “Do you require additional assistance for conducting the employee performance?”
- we should have an update on the start date for the onboarding surveys after our meeting.

**Comment by dianamartin** [comment]
## Task 1
Had to make all the changes on the form name
- “Supervisor Surveys for Employee SSPRs” to “Onboarding Surveys for New Employees”
- [ ] `form_management` object
- [ ] HR Form Management>Form Name
- [x] Form Details
- [x] Staff Forms>buttons
- [x] Staff Forms>table title
- [x] My Forms>buttons
- [x] My Forms>table title

## Task 2
“30 Day Employee Follow-ups” to “Employee Onboarding Survey”.

## Task 3
## Task 4
Was able change the "Check all that apply"
![image](https://user-images.githubusercontent.com/21112975/183689080-5876897c-8efb-430c-8bf3-42d37aa21b30.png)

## Task 5

**Comment by dianamartin** [comment]
Emailed stakeholder 8/9
>We’ve updated the different things you asked for re: Onboarding surveys, you can see all the individual changes documented on this [GitHub issue](https://github.com/cityofaustin/atd-data-tech/issues/9965). You can now go through the HR Application to review these changes. 

>Let us know if you require any other changes and what Jennifer said about a go-live date of the surveys.

**Comment by moorerst** [comment]
@dianamartin did you get any confirmation from stakeholder that the updates are ok?
Did you get any update on a go-live date?
Can this be closed?

**Comment by dianamartin** [comment]
@moorerst Hannah never replied back, maybe we can ping them (Hannah, Jennifer) ?

**Comment by moorerst** [comment]
Emailed stakeholder for updates.

**Comment by moorerst** [comment]
Response from stakeholder: 
Everything looks great. Thank you for all your work on this. 

Jennifer has requested we hold off on launch until after the Online SSPRs go out. So I believe we will be looking at some time in October. 

Closing issue
